### ISSUE TITLE
Sample lesson submission

### ISSUE THREAD

**Issue by wcaleb** [programminghistorian/ph-submissions#1]
I've uploaded my sample lesson. Reviewers, here is a [live preview](http://programminghistorian.github.io/ph-submissions/lessons/sample-lesson).

**Comment by wcaleb** [comment]
@fredgibbs Here is the new submissions repo. Check out the [front page](http://programminghistorian.github.io/ph-submissions/), which is `index.md` in this repo, for a rough work-up of what the new submission workflow would look like. I think you said you have a lesson coming that we could try this out with.

**Comment by acrymble** [comment]
Looks awesome!

**Comment by acrymble** [comment]
Can the permission level be abused by someone who wants to be a jerk?

**Comment by wcaleb** [comment]
A collaborator does have [pretty extensive privileges](https://help.github.com/articles/permission-levels-for-a-user-account-repository/). If someone abuses it, we just revoke them as a collaborator, but that seems unlikely. All they would be able to affect is this repo anyway, not the main one.

**Comment by fredgibbs** [comment]
it's pretty easy to revert changes as well. so, unfortunate commits, on purpose or accident, are more inconvenient than anything. i agree it's pretty unlikely that we'll have a contributing author so disgruntled that they decide to wreak havoc on the submissions branch--at least if we're not being jerks ourselves.

@wcaleb, do you have any sense of how easy or difficult it is to automate the last step of re-integrating the relevant files (lesson + images) into the main repo? this is not urgent, but it would be super helpful, if it's possible, to add relevant instructions for editors in the excellent directions you've already written out.

**Comment by wcaleb** [comment]
Assuming the editor has cloned both repos on his/her machine, it could be as easy as copying the lesson and images from one directory to another, and then committing and pushing from the published Jekyll repo. Will investigate other options as well. 

Sent from my iPhone

W. Caleb McDaniel
Associate Professor of History
Duncan College Master
Rice University

http://wcm1.web.rice.edu/
http://www.duncancollege.net/
