### ISSUE TITLE
Proposed Lesson: Topic Modeling with R

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/ph-submissions#103]
The Programming Historian has received a lesson proposal on Topic Modeling with R.

**Comment by jerielizabeth** [comment]
Draft submission due date: October 23, 2017.

**Comment by acrymble** [comment]
This was a while ago now. Any update @jerielizabeth ?

**Comment by jerielizabeth** [comment]
I'll follow up and update these issues.

**Comment by jerielizabeth** [comment]
In reviewing my notes, this was one of two lessons pitched by Sara Kerr, who is currently working with @walshbr . She is moving forward with word-embeddings for now, but I think this proposal can be closed for the time being.
