### ISSUE TITLE
Proposed Lesson: Word-Embedding in R

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/ph-submissions#104]
The Programming Historian has received a lesson proposal on Word-Embedding in R.

**Comment by jerielizabeth** [comment]
Draft of this lesson has been received on October 24, 2017.

**Comment by acrymble** [comment]
This was a while ago now. Any update @jerielizabeth ?

**Comment by acrymble** [comment]
Is this the same as #145? If so we can close this.

**Comment by walshbr** [comment]
Ah I believe it is @acrymble - can reopen if I'm mistaken.
