### ISSUE TITLE
Proposed lesson: Data visualization with R and ggplot2

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/ph-submissions#107]
The Programming Historian has received the following proposal for a lesson on 'Data visualization with R and ggplot2'. The proposed learning outcomes of the lesson are:
     
- harvesting data using SPARQL
- visualizing different aspects of it using ggplot2
 	
The main editorial contact for this lesson is @mdlincoln. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1 or @amandavisconti.

**Comment by mdlincoln** [comment]
(This is a much-delayed proposal that we got earlier in the year. I've actually got a full draft in my inbox now, but I want to review it before posting as a formal submission, and I'm going to be on vacation until August 20. I've checked with the author and they're aware of this schedule)

**Comment by mdlincoln** [comment]
I'm closing this because I haven't heard back from the author.

**Comment by mdlincoln** [comment]
I'm back in touch with the author and received a good draft. We're working on reducing the scope just a bit before posting here. I will be checking in again by February 13.

**Comment by acrymble** [comment]
@mdlincoln Just wanted to prompt this because 13 Feb has come and gone.

**Comment by mdlincoln** [comment]
Thanks - nothing yet. I'll check in again.

**Comment by mdlincoln** [comment]
The author needs a little more time - I will check in again by March 16.

**Comment by mdlincoln** [comment]
Review started in #155
