### ISSUE TITLE
Ticket de Revisión de Traducción: Introducción a Google Maps y Google Earth 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#130]
The Programming Historian en español ha recibido la siguiente propuesta de traducción de la lección "[Introducción a Google Maps y Google Earth](http://programminghistorian.github.io/ph-submissions/es/traducciones/intro-a-google-maps-y-google-earth)" por parte de @el-barto. Esta traducción se encuentra en estos momentos en revisión por @arojascastro y @jenniferisasi y puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/intro-a-google-maps-y-google-earth

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.
Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by el-barto** [comment]
He generado imágenes con las versiones en castellano de Google Maps y Google Earth. Sólo han quedado 3 imágenes que no pude reproducir:

* **Figura 12:** No logro hacer funcionar la "Visita guiada" de Google Maps. De todos modos, en el hilo del texto creo que esta imagen no es crucial. Puede dejarse en inglés o quitarse.
* **Figura 29:** He seguido detenidamente las instrucciones, pero cuando cargo el mapa de la vía marítima de Dan Macfarlane en Google Earth el mapa no se dibuja, así que no he podido replicar esta imagen.
* **Figura 40:** En este caso, los autores no proveen la imagen del mapa antiguo de Aultsville, así que tampoco pude replicarlo.

**Comment by mariajoafana** [comment]
@el-barto perdona la demora en asignar un revisor. @arojascastro va a ser el primer revisor de la lección.

**Comment by arojascastro** [comment]
Gracias @mariajoafana; espero revisar el tutorial antes de que acabe el mes, si va bien. Publicaré mis comentarios aquí.

**Comment by arojascastro** [comment]
Comentarios generales: 

- se abusa de la forma "puede" y "esto" para introducir frases. Se recomienda reescribir algunas frases para dotar al texto de mayor diversidad aunque se aleje del original inglés.
- se evita el uso de frases subordinadas o coordinadas. En español, creo, son más comunes que en inglés, sobre todo en textos formales; se recomienda utilizar más construcciones subordinadas o coordinadas en lugar de tanta frase corta. 
- el traductor hace uso formal del pronombre *usted*. En general, preferimos el uso del *tú* (pero queda a discreción de la editora @mariajoafana)
- click --> clic (preferible)
- software --> programa

Observaciones específicas:

- En el resumen: alternativa para --> manera de
- 1: alternativa para --> manera de
- 1: puede --> puedes
- 1: click --> clic
- 2: puede --> puedes
- 2: tiene --> tienes
- 2: vaya --> vayas
- 2: puede --> puedes
- 2: Sus --> Tus
- 2: son almacenados --> se almacenan (pasiva es poco habitual en español)
- 2: por Google --> en Google 
- 2: podrá --> podrás
- 2: puede: --> puedes
- 2: su sitio --> tu sitio

Ok, en adelante no señalaré los cambios de voz: si usamos el tú, todos los imperativos deben cambiarse. Por ejemplo: Abra --> Abre

A las tres primeras órdenes les falta un punto final. En el original también faltan, pero creo que se deberían añadir porque en el resto de instrucciones sí se pone punto y final.

- 3: en caso de ser necesario --> si es necesario (menos complicado)
- 4: click --> clic
- 4: signo de pregunta --> signo de interrogación
- 4: Visita guiada --> "Visita guiada" (faltan comillas en el original, creo)
- 6: Pruebe buscar --> Prueba a buscar (falta preposición *a*)
- 6: Pruebe buscar --> falta preposición y usa usted... además es una repitición, por lo que sugiero usar otra fórmula como "Intenta"...
- 9: click --> clic
- 11: Descargue estos datos de ejemplo y guárdelos en su computadora Archivos CSV del Suministro global de grasa de Reino Unido. --> A continuación, descarga Archivos CSV del Suministro global de grasa de Reino Unido y guárdalos en tu computadora (el orden de la frase es incorrecto y no se entiende)
- 14: Ahora puede explorar --> A contiunación o seguidamente (repites Ahora en dos instrucciones seguidas).
- 14: click --> clic
- 16: límites --> limitaciones 
- 16: hoja de cálculos --> hoja de cálculo
- 17: Puede encontrar  --> Encontrarás (repites "puede" muchas veces)
- 18: click --> clic
- 18: haga click en el botón de “Agregar capa”. Esto creará una nueva  --> haga click en el botón de “Agregar capa” y se creará una nueva (repites "Esto" muchas veces porque en el original usan mucho "This" pero en español no es necesario repetir el sujeto, puedes escribir oraciones coordinadas o yuxtapuestas)
- 19:  capa de UK Global Fats  --> " capa de UK Global Fats" (Faltan comillas ???)

(a partir de aquí no indico más cambios de "click" a "clic")

- Haga click en el botón de agregar marcadores debajo de la barra de búsqueda en la parte superior de la ventana. Luego haga click en el lugar del mapa donde quiere que aparezca el marcador. --> Haz clic en el botón de agregar marcadores debajo de la barra de búsqueda en la parte superior de la ventana y, a continuación, haz clic en el lugar del mapa donde quiere que aparezca el marcador ... (pienso lo mismo: en español podemos usar frases coordinadas, subordinadas y yuxtapuestas para evitar el uso de "haga click" en dos frases tan seguidas).
- 24: software --> programa
- 24:  (los diferentes tipos de puntos, --> falta terminar la frase
- 25: item --> ítem
- 27: You can also change the colour and width of the line. To do this, find the road you have drawn in Layer 2 in the menu box, and click to the right of the name of the road. --> falta traducción
- 28: Siéntase libre  --> calco del inglés (feel free), puede solucionarse con "Te recomendamos experimentar por tu cuenta creando líneas y polígonos".
- tras el párrafo 30: error de markdown (también en el original) --> quitar marcador de lista
- 31: on line --> en línea
- 31: Compartir --> quitar negritas y poner comillas --> "Compartir" (en el original también hay negritas, pero creo que es un error).
- 31: Éste provee un enlace  --> Al clicar, obtendrás un enlace... (para evitar empezar una frase con Este, que es calco del "This" inglés).
- las notas creo que las marcamos con > (en el original falta, pero creo que es error). Por tanto debería ser:

> Nota: actualmente no hay forma de configurar la escala por defecto o las opciones de las leyendas de un mapa insertado, pero si necesita eliminar la leyenda del mapa que aparece en su sitio HTML puede hacerlo reduciendo el ancho del <iframe> a 580 o menos.

- 34 - 35: repites muchas veces "Puede"... ¿Puedes reescribir las frases para que no suene tan repetitivo?
- 38: software --> programa
- no está basado en la nube --> no funciona en la nube 
- 40: familiarísese --> familiarícese
- 42: Note que  --> Ten en cuenta ("note" es un calco del inglés)
- pixeles --> píxeles
- ráster --> no tengo ni idea de qué significa... si es anglicismo debería ser *raster* (añadir cursiva y quitar acento)
- Cuando hace click en un ícono --> Al hacer clic
[Georeferenciando en QGIS 2.0][] --> falta enlace
- 47: software --> programa
- 52: (esto fue posible superponiendo mapas históricos, lo cual se explica más abajo),   --> (superponiendo mapas históricos, lo cual se explica más abajo), (quitar "esto fue posible", es calco del inglés y no es necesario en español).
- 58:  online --> en línea
- 58: Esto se conoce  --> lo cual (introducir frase subordinada...)
- 60: i.e. --> por ejemplo
- 64: ventaa --> ventana
- Éstos pueden ser utilizados para estirar, achicar y mover el mapa para que se alinee correctamente con la imagen del satélite. Éste es un modo sencillo ---> repetición de "Estos" y "Este". 
-  la siguiente lección .  --> quitar espacio entre "lección" y punto

Gracias.

**Comment by el-barto** [comment]
Muchas gracias por tus comentarios, @arojascastro. 

Además de los errores y mi abuso del "puede" y "esto", veo que hay algunas correcciones de estilo que tienen que ver con diferencias regionales. No sólo el "tú"/"usted" sino también, por ejemplo, en Argentina es muy infrecuente la construcción "probar" + "a" + infinitivo (que, efectivamente, es lo que dice la RAE). Comenzaré entonces a aplicar estos cambios para pasar a un lenguaje más neutro y pushearé una nueva versión en cuanto la tenga lista.

**Comment by arojascastro** [comment]
Gracias @el-barto por responder. Tampoco te tomes mis comentarios al pie de la letra; quizás sería mejor esperar a la segunda revisión y a que @mariajoafana decida si hay correcciones que no se deben realizar porque son, como dices, propias del habla argentina. De hecho, no sabía que eras argentino, pensaba que eras mexicano. En cualquier caso, son sugerencias.

**Comment by mariajoafana** [comment]
Hola @el-barto Estoy de acuerdo con Antonio sobre hacer el cambio de voz para usar el "tu" como lo hemos hecho en la demás traducciones y así guardar la consistencia. Sobre el ejemplo "probar a" no hay problema en dejarlo según el uso más común en Argentina, pues no modifica la claridad del texto.

**Comment by mariajoafana** [comment]
Encontré un segundo revisor para el tutorial. @el-barto, ¿me podrías avisar por favor cuando hayas incorporado las corecciones de @arojascastro para así darle luz verde al segundo revisor? Muchas gracias.

**Comment by el-barto** [comment]
Hola @mariajoafana, entendí que debía esperar a que estuviera la segunda revisión. Creo que podré hacer los cambios en el transcurso de la semana próxima. Saludos!

**Comment by mariajoafana** [comment]
Mil gracias @el-barto Creo que mejor incorporar primero las sugerencias del primer revisor y luego  si que lo mire el segundo revisor. Quedo pendiente ;)

**Comment by el-barto** [comment]
Perdón por la demora, tuve unas semanas más cargadas de lo que esperaba. Ahí hice el pull request con las correcciones. Espero no haberme pasado por alto ninguna!

Con respecto al término "ráster", lo dejé como estaba porque he visto que se usa esa castellanización (por ejemplo, en [Wikipedia](https://es.wikipedia.org/wiki/Imagen_de_mapa_de_bits)). Pero si no están de acuerdo, lo cambio a *raster*.

**Comment by mariajoafana** [comment]
Muchas gracias @el-barto . Añado a @norbr quien será el segundo revisor del tutorial. Por favor, introduce aquí tus propuestas de cambio, ojalá en un plazo de dos semanas. Quedo pendiente sobre cualquier duda que puedas tener

**Comment by mariajoafana** [comment]
Hola @jenniferisasi gracias por acceder a hacer la segunda revisión de este tutorial. Por favor, introduce aquí tus propuestas de cambio, ojalá en un plazo de dos semanas. Quedo pendiente sobre cualquier duda que puedas tener. Puedes ver los mensajes anteriores para familiarizarte con la forma de hacer las sugerencias. Cualquier duda me cuentas.

**Comment by jenniferisasi** [comment]
Hola a todos: 

Dejo aquí los comentarios de esta segunda revisión a [http://programminghistorian.github.io/ph-submissions/es/traducciones/intro-a-google-maps-y-google-earth](http://programminghistorian.github.io/ph-submissions/es/traducciones/intro-a-google-maps-y-google-earth). Puesto que Antonio ya había sugerido cambios, la mayoría de los míos tienen que ver con errores que han ido quedando. Pido perdón por adelantado si alguna de mis sugerencias refiere a regionalismos. 

- En el resumen y en #1: El párrafo del texto ha sido corregido pero el resumen superior sigue diciendo "son una buena alternativa para ..." 
- En contenidos: compartir su mapa personalizado --> compartir tu mapa personalizado
- 2: Esto automatiza una tarea que solía ser tediosa conocida como geocodificación. --> Esto automatiza una tarea, anteriormente tediosa, conocida como geocodificación. 
- 2: y de este modo y explorar cómo --> y de este modo explorar cómo (sobra la 'y')
- 2: mantenrelos --> mantenerlos
- 3: Identifícate con su cuenta de Google --> Identifícate con tu cuenta de Google
- 6: resultados mezclados --> resultados mixtos
- 6: algo importante para tener en cuenta --> algo importante a tener en cuenta (quizás es regionalismo) 
- 6: lugares y evitar el riesgo de que Google elija --> para evitar que Google elija
- 11: archivos CSV (...) y guárdalos --> archivo CSV (...) y guárdalo
- 17: conocidos como --> conocidas como (las capas del mapa)
- 17: múltiples componentes --> principales componentes (en el original dice "main components)
- 17: le permiten --> te permiten 
- 21: quiere --> quieres
- 21: Marcador ... marcador --> ¿mayúscula o minúscula? 
- 24: llamados --> llamadas (las formas)
- 28: punto de su línea --> punto de tu/la línea 
- 30: nombre de su polígono --> nombre de tu polígono
- 31: el cual puede ver --> el cual se puede ver
- 35: luego podrás exportar lo que hayas hecho a una base de datos SIG --> luego podrás importar lo que hayas hecho a una base de datos SIG o luego podrás exportar lo que hayas hecho para una base de datos SIG (aquí me crea confusión la preposición y los verbos importar e exportar; si es 'a una base de datos' entiendo que importo lo datos (a la plataforma), si es 'para una base de datos' entiendo que exporto los datos (de otra plataforma)). 
- 39: no le solicita (...) sus mapas --> no te solicita (...) tus mapas 
- 39: que cree --> que crees
- 41: distinto tipo --> distintos tipos
- 43: para usar se activan --> que se activan 
- 59: comparaciones útiles de los cambios --> comparaciones útiles de cambios
- 61: el área del mapa que donde --> el área del mapa donde 
- 65: desea --> deseas
- 70: probablmente --> probablemente

**Comment by el-barto** [comment]
Muchas gracias @jenniferisasi !

Ahí apliqué las modificaciones. Hubo dos que no apliqué:

*  2: "Esto automatiza una tarea...", me parece que esas comas no son necesarias. 

*  35: "exportar a una base de datos...", lo dejé así porque me parece que queda más correcto con la preposición "a" (por ejemplo, uno exporta carbón *a* otro país). Es cierto que, en rigor, en este caso uno exporta los datos a un archivo y luego importa el archivo en el programa que uno quiera, las veces que uno quiera. Pero creo que es suficientemente claro. Si no están de acuerdo, lo cambio.

**Comment by mariajoafana** [comment]
Perfecto, muchas gracias @el-barto @jenniferisasi @arojascastro Voy a revisar todo y a fijarme en lo de las imágenes que nos señalas @el-barto a ver cuál la mejor manera de solucionar. Esperemos que ya muy pronto podamos publicar el tutorial

**Comment by mariajoafana** [comment]
Ya está publicado el tutorial, si hay asuntos que corregir lo volvemos a abrir. Gracias a todos!
