### ISSUE TITLE
Review Ticket: Getting Started with Anaconda and Jupyter

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/ph-submissions#132]
The Programming Historian has received the following proposal for a lesson on 'Getting Started with Anaconda and Jupyter' by @jewellthomas. This lesson is now under review and can be read at:

[http://programminghistorian.github.io/ph-submissions/lessons/collaborative-digital-humanities-anaconda-jupyter](url)

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I will first read through the lesson and provide feedback, to which the author will respond.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by alsalin** [comment]
@jewellthomas I'm excited to see both part 1 and part 2 of this lesson together. As I go through part 1, I haven't tried the code quite yet because I'd like to see if we can tweak the format of the tutorial a little bit. Right now, I'd like to explore some possibilities for clarifying context and ensuring longterm sustainability for this lesson.

We've been having lots of discussions at PH about sustainability and longevity of lessons lately and one of the most important components of creating sustainable lessons is reducing the specificity of software dependencies within the lessons themselves. That goal may take different forms in different lessons, but here I'd like to see if we can offload a lot of the specificities of setup tasks (direct instruction for: installation, creating managing new environments, saving/exporting, and creating and working with new notebooks) to the product documentation. 

I know that this lesson is the setup for part 2 - but rather than focus on the nitty-gritty, I wonder if you can offload the specifics to product documentation and then add more on 'who this approach is specifically for' and 'why this particular setup will be helpful for that audience.' I think that each section could give a shout out to the product documentation, and then, where you deem appropriate, you could add in your output example (e.g. P7 where you introduce creating a new environment - the detailed instructions could turn into a link to product documentation and then you could add your example of what the user/reader should see as you do in P10). Rather than focusing on only the setup of sw, then part 1 becomes resources and steps for setting up environments with these tools along with setting the context for using Anaconda and Jupyter for DH research.

In light of that, I'd also like to see more of the context up front in P1. Without seeing part 2, I struggle to understand the applications of these tools, i.e. how exactly they will help with shareability and repeatability, and why you use these specific tools for those goals.

Let me know if any of these suggestions are unclear or if you have some more ideas for sustainability in the layout of this lesson!

**Comment by acrymble** [comment]
@alsalin this looks like it's been stalled. Do you have any progress updates you can give us?

**Comment by jbartonthomas** [comment]
Hi All,

This did stall last fall. When I first saw the edits requested, it felt
like the direction was somewhat orthogonal to what I had been in
conversation with the editors about already.  That’s neither here nor
there, I just wasn’t sure I was going to have time to put in for the
revision (I was just starting up at a new school). That said, if you all
still have interest, please let me know. It’s possible I can ask a coauthor
to make changes.

Thank you & sincerely,

Jewell

**Comment by alsalin** [comment]
@jbartonthomas we will go ahead and close this submission for now, but if you or your co-author are interested in picking it up again, please let us know!
