### ISSUE TITLE
Review Ticket: Wrangling Museum Collection Data with Pandas

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/ph-submissions#136]
The Programming Historian has received the following tutorial on 'Wrangling Museum Collection Data with Pandas' by @atiro. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/wrangling-museum-collection-data-with-pandas

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by walshbr** [comment]
Thanks for this, @atiro. I think that the tutorial offers a lot for readers in the way of a basic introduction to Pandas. Lots here that will be useful in the way of data analysis - I know Pandas is being used more and more for data structuring and processing, and I think it's a great idea to have a tutorial on it that is accessible to digital historians. I have several points below that are local as well as a few global suggestions. Most pressing is that I think the tutorial needs a lot more proofing before I send it around to readers. Just found a lot of dropped words, mispellings, grammatical errors, etc. All understandable since we're in the drafting phase, but we should clean those up before sending it out for review. So I'd suggest you take the time to take the following comments into account before I approach others to take a look. Let me know if you have questions! Otherwise I'll be on the lookout for a comment in this thread to let me know that you're ready for me to take another look. You should be able to commit directly to the repo now that I've added you as a contributor. More local points organized by section:

Assumptions

"can run a Unix/Linux shell commands on" - no 'a'?

"If you need a place to start, I also recommend working through the Programming Historian’s excellent Python tutorials." link to them?

Lesson goals - I might modify the fourth one, since whether or not one becomes a data detective seems largely subjective? But you could definitely assess whether or not you've explored and compared museum collections. Also see my note about the degree to which you're actually engaging with the collection datasets themselves. Think it's worth focusing on one collection only.

Introduction

Capitalize "world wide web"

I think paragraphs 2-6 are a bit out of scope for the sorts of lessons that Programming Historian offers. It's all fine, but it feels a bit thin and generalizing without more citation of external sources. I wonder if you could condense it into a meaty paragraph. For that matter, I wonder if it might be worth dispensing with the first lesson goal as out of scope for the lesson - you don't quite deal with the technical matters of working with data by API / bulk download / GitHub except in passing, so I think it might be a clearer subject if you keep the focus on Pandas explicitly. That's already the implied, real goal of the lesson based on the amount of real estate that you give to the museum discussion. I also think it might be worth only working with one of the three museum collections rather than all three. Then you could develop a single case study that really examines a collection thoroughly throughout the lesson and maybe talk a little bit more about the collection itself. As it is, you only barely (ok ok I hopped on board with the puns) touch the actual structure of the collections data itself. Digging more into a single one might help. And would be more sustainable to not depend on three different collections going forward.

Pandas: A quick introduction

I think this section could be expanded. If it's just a quote from another site it's probably not necessary to set it off in this way?

Pandas the Bare Essentials

"Data (in whatever state, we can worrying about tidying data later)" I'd go through and proof things a little more closely. Have noticed several typos so far with dropped words and grammar, etc.

At the discussion of one and two-dimensional arrays, I think it would be useful to give an example of each using the sample data you'll eventually have them use. It might, then, make sense to save these conceptual notes until they actually naturally come up. This sort of laying down of the concepts (in theory and in practice) is part of what makes a tutorial like this different from just the documentation for the package itself that you can find elsewhere. So I'd like to see more of that.

In general I might try to reduce the number of parenthetical asides - at times they make it difficult to follow what information is critical and which is supplementary. So I'd check to see what is necessary (and integrate it into the text proper) and what is actually supplemental (and potentially cuttable). You can also use footnotes to actually make them supplementary material and clean up the text itself.

Getting setup - the Pandas site will certainly have the most up-to-date versions of instructions, but would be good to show the steps for doing so inside the tutorial itself. Particularly since the Pandas API might change - would be good to note what version you're currently writing documentation for. A question of balancing sustainability with making the tutorial accessible for the widest possible audience.

Running Pandas
Which are you expecting your readers to do? Script or python session? I'd pick one - probably asking them to save the progress in a file. Short way of saying it will probably help readers to have a single and clear workflow to follow.

Reading in data
You'll need to indicate what is Python vs what is in the shell. I think a common convention is to throw '$' at the front of a line meant to be in the terminal to distinguish it, but you can also just convey this in the body of the text.

paragraph 22 - I would give the example of the error and the output. In general, giving example outputs in the previous three code blocks will help let readers know what they should be looking at.

paragraph 23 - "We’ve saved the results of reading in the file into a DataFrame called df_objects. By default Pandas will create a DataFrame to store the data." this seems like an excellent place to introduce the concept, rather than to introduce it much earlier and come back later to it as you do here.

I'm not sure I follow what the code block at paragraph 23 is illustrating. Can you clarify and expand on the context for it? Or it might just be a rendering issue.

paragraph 24 - I think having one consistent case study would help a lot here. That way you can reflect a bit on the process, why this is all necessary and how Pandas enables it, etc. I think you don't want to skate from code block to code block quite so quickly. Reflect a bit more at each stage. Same goes for each section - I'd want to see more digging into the results that you're getting at the beginning / ending of each section. Maybe offer a particular historical question as an example research problem and walk the reader through solving it.

paragraph 26 - say more about the information it is showing us? non-null objects, dtypes, memory usage, etc. Also later on might be worth noting what NaN means.

paragraph 29 - rather than assume any knowledge on the part of the reader, I'd explain what the head and tail commands do outright. Just a question of framing, particularly since they wind up being pretty important to the code you're using.

paragraphs 34 and 36 - make sure your code blocks are actually rendering as code blocks.

So far you've introduced some of the basic functions of Pandas, but I think the dataset itself is lost. I get that you've selected the search for the play on the library's title, but I think it might help to have a case study that you dig a bit more into that might play into historical analysis. Ie - something that could help answer the question "why might a historian use this sort of thing to help work with their data?" Digging a bit more into the ways in which, even at this basic level, Pandas is enabling your research could help. So when you, say, slice through a particular column of the data, talk about how that is a profound act that can help facilitate your work.

Paragraphs 37-40 I think are useful.

Paragraph 42 - why remove duplicate fields? why remove empty ones? Seem obvious, but probably worth explicitly mentioning the problems that these can cause for parsing data.

42-48
I think this is all good, but it might be a difficult to follow depending on the reader's familiarity with Python. In here and in general, you might consider offering recap code blocks with all of the lines in sequence, rather than simply offering a line here and there.

Data detective -

"Panda Fu" I'd take this out - seems like it might be a bit appropriative / taking the pun a bit too far.

paragraph 60 again the code block isn't rendering as a code block. Check it out in the live preview linked to above.

paragraph 69 - "Our relatively simple lambda function" - in general I think that there might be a bit too much assumed knowledge at work here. The reader might not find this simple. I'd go through and try to really think critically about the stuff you're introducing and ask what a newcomer might expect to be explained for them.

I think you'll want more of a wrap up at the end. Rather than just end the thing, maybe offer a moment to reflect on what you're illustrated, what the next steps might be for an interested person, etc.

So my main suggestions:
- Proof more.
- Focus on one collection and use it as a case study that you engage more thoroughly throughout the lesson. Maybe take a particular problem through the work so that a historian coming to the text will have a good sense of how to imagine applying this to their own work. This might necessitate a change in the lesson title, which I think is fine!
- Following on the last, try to treat the lesson a bit more as walking a reader through one or more research problems in digital history. That's just a question of genre and framing, largely asking for more digging into the code and results, giving them a bit more purpose as you're going along.
- Reflect on the amount of assumed knowledge that you're expecting here and try to illustrate things a bit more for the reader.

So take a run at revising based on those comments, and I'll take another look. Haven't taken the code blocks through the motion yet, as I imagine that they'll change pretty substantially from what I see here. Thanks for putting this together! Excited that it's moving forward, and I appreciate you taking the time.

**Comment by walshbr** [comment]
No rush on this @atiro, but we're engaging @zoeleblanc as one of your reviewers. She'll be giving a more thorough read through later on after you've taken my above comments into effect. But she had some initial thoughts that might be good to keep in mind as you're working. So we thought it worth looping in earlier. She'll be in touch on this thread.

Excited to see that this is coming to fruition! Thanks for writing.

**Comment by ZoeLeBlanc** [comment]
@atiro this is a great tutorial that I wish had been around when I was learning pandas! I agree with Brandon's detailed comments, and want to especially second his advice of focusing on the datasets a bit more, rather than the methods, to help clarify when/where to use pandas. 

Here's a few of my big picture comments and I would be happy to give more detailed feedback later on in the process. 

1) Explain why they might use pandas over other options. Specifically I think you should outline how pandas is great at medium sized data sets (bigger than ~2GB) that are too big for R or a for loop, but aren't so complex that they requiring a database (i.e. mostly tabular data that doesn't require data models). These aren't firm rules but rather guidelines that might help the audience decide whether pandas is right for them.

2) Linking to a [pandas cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/PandasPythonForDataScience+(1).pdf). This particular cheatsheet is one I've used and I think it helps visualize the difference between series and data frame, which is hard to explain. It also let's you gesture to other methods without having to go in depth

3) Explain what makes pandas powerful. You show them very thoroughly how to do column/row based data manipulations, which is great. However, I think it's worthwhile to note how this feature not only makes pandas super fast, but is also a different approach to data manipulation. Most of the audiences' instinct for data manipulation will likely be to try and use a loop, but in pandas that's actually counter to best practices. You don't have to belabor the point, but think it's worthwhile highlighting what are basic pandas best practices.

4) Biggest gotcha that I would recommend including is that after doing all these transformations, especially on larger datasets, that you should reset your index. Resetting is key to avoid index errors and will likely be one of the main errors they hit. 
```
eg.
    df.reset_index(inplace=True)
```
These are all pretty general points that I think will only strenghten your tutorial. Let me know if you want advice about where in the tutorial to incorporate them or if you have questions about them. Again great work on explaining how to use pandas!

**Comment by walshbr** [comment]
@atiro - just wanted to check in on this since it's been sometime since last contact. Do you have a sense of your timeline for revisions here? Hope you're well.

**Comment by acrymble** [comment]
@walshbr this looks like it's stalled. Is this still active, or should the submission be closed?

**Comment by walshbr** [comment]
@acrymble - I've been communicating with Richard backchannel in the last couple weeks. He's going to try to turn attention to this in the next week or two, and if that doesn't work out I think we can close it. I'll keep monitoring.

**Comment by walshbr** [comment]
Closing this for now. @atiro feel free to drop a note here when you've had a chance to do revisions and we can reopen this ticket for you.

**Comment by atiro** [comment]
Hi all, sorry for such a slow follow up to your excellent feedback. I'm going to try to re-write it as more of a "Data Science in Cultural Heritage" lesson, using Pandas as the tool for solving (or generating!) a problem, as suggested. Will add when have got somewhere on it.

**Comment by walshbr** [comment]
Sounds good @atiro! I'll reopen at that time. Thanks for your work on this.
