### ISSUE TITLE
Ticket de revisión de traducción: Contabilizar y minar datos de investigación con Unix

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#138]
The Programming Historian en español ha recibido la siguiente propuesta de traducción "Contabilizar y minar datos de investigación con Unix" de la lección "Research Data with Unix" por parte de @vgayolrs . Esta traducción se encuentra en estos momentos en fase de revisión por @jucmurciaga y puede leerse en:

### Texto
http://programminghistorian.github.io/ph-submissions/es/traducciones/datos-de-investigacion-con-unix

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros ombudpersons.

Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con María José Afanador-Llach.

**Comment by mariajoafana** [comment]
@vgayolrs Si te parece yo puedo hacer la primera revisión de este tutorial

**Comment by mariajoafana** [comment]
Acá van mis comentarios:
**Comentarios generales:**
- ¿Habrá instrucciones en español para la instalación de Git Bash? Podríamos empezar un proyecto paralelo de instrucciones para instalar paquetes de código y software... 

**Comentarios específicos:
- 33: Sugiero cambiar la segunda parte de la primera oración: "un historiador puede hacerse preguntas diferentes al volver a revisar los datos en un proyecto posterior."
- 35: Sugiero cambiar: "te muestra una serie de órdenes" por "te introduce a una serie de comandos" 
- 51: borrar espacio después de "cualquier locación"
- 61: añadir "a" antes de "donde lo necesites" . Cambiar "tiene un formato como" por "tiene el siguiente formato"
- 85: añadir espacio en ",lo"
- 91: última frase, cambiar "con el que dispongas" por "del que dispongas"
- 107: añadir espacio en "Excel,o"
- 115: tal vez cambiar "casos" por ocurrencias

**Comment by vgayolrs** [comment]
¡Muchas gracias @mariajoafana ! Atendidas las observaciones. Sobre el comentario general, sí hay varios tutoriales en español que cubren la instalación de Git Bash, varios en fomato de video. Podría poner un listado aquí para escoger el más adecuado y citarlo en la traducción como hice con la guía práctica de Unix y Linux.

**Comment by mariajoafana** [comment]
Hola @vgayolrs quería retomar este tutorial, entiendo que ya quedaron tus revisiones hechas y ahora es momento de involucrar a un segundo revisor para el texto.

**Comment by vgayolrs** [comment]
@mariajoafana ¡excelente! Ya ni me acordaba de éste...

**Comment by vgayolrs** [comment]
@mariajoafana , ¿algún nuevo revisor?

**Comment by mariajoafana** [comment]
Si, @jucmurciaga va a hacer la primera revisión

**Comment by jucmurciaga** [comment]
Hola  @vgayolrs y @mariajoafana , lo siento por la tardanza en mis comentarios.
He visto lo siguiente al realizar el tutorial:
**Comentarios generales**
- Una vez abrí Git Bash, el directorio en el que me ubica al principio es C:/users/NOMBRE DEL EQUIPO/ y no simplemente C:/ . No sé si sea bueno especificar que en windows también puede que sea ese el directorio automático
- Sugiero revisar el menú, pues el subtítulo "Conclusión" está como una subcategoría de la sección "Extracción de información o minería de archivos".
- Los links que están dentro de la lección y van hacia los tutoriales “Preservar tus datos de investigación" e “Introducción a la línea de comandos de Bash” están caídos y redirigen al repositorio de github y no al portal de programminghistorian.org

**Comentarios específicos**
0.  Sugiero revisar el párrafo de descripción del tutorial, la palabra extraídos lleva tilde.
También, en la parte que dice "Esta lección es parte de una serie. Quizás quieras consultar la lección anterior.", el link debería llevar a [la lección ya publicada](https://programminghistorian.org/es/lecciones/introduccion-a-bash). 
12. Al descomprimir los archivos descargados queda una carpeta llamada Data, por lo cual sugeriría. quitar la parte de \proghist\ tanto en la parte de Linux como en la de Windows, porque podría confundir a las personas en el primer paso de ubicarse en el directorio y acceder hasta \Data\ por medio del comando cd.
18.  Puede resultar útil indicar que si escriben wc --help pueden acceder a la lista de comandos para wc.
22 y 23. En Windows el comando wc -c es para contar bytes y el comando wc -m para contar carácteres. No sé si sea una modificación nueva, pero sugeriría modificarlo para que quedara bien el comando.
25. En este paso introduje el comando y también intenté copiándolo, pero no creó un archivo .txt. Creo que el error esta en los espacios en los comandos, me funcionó así: wc -l 2014-01-31_JA_a * .tsv > results/2014-01-31_JA_a_wc.txt 
31. Sugiero revisar el párrafo puesto que no da una idea clara de lo que se puede conseguir con dichos comandos. Me sentí perdido en ese párrafo al no saber qué es lo que me debería estar arrojando el sistema.



Quedo muy pendiente y de nuevo disculpas por la tardanza.
Camilo

**Comment by mariajoafana** [comment]
Gracias @jucmurciaga , quedamos ahora a la espera de que @vgayolrs  haga las revisiones del caso

**Comment by mariajoafana** [comment]
@vgayolrs ¿Acordamos una fecha límite para que incorpores las revisiones?

**Comment by vgayolrs** [comment]
En esta semana me hago cargo @mariajoafana !

**Comment by vgayolrs** [comment]
@jucmurciaga muchas gracias por tus observaciones. He modificado las que son posibles de modificar sin añadir o quitar cosas a la lección original. Una observación sobre los enlaces: ciertamente ninguno funciona cuando el borrador de la traducción está en este repositorio, pero funcionan cuando se traslada al repositorio de publicación.
@mariajoafana , queda de ti la decisión de publicarla.
Saludos y gracias!!!

**Comment by mariajoafana** [comment]
Ya quedó publicada la lección, gracias @vgayolrs y @jucmurciaga
