### ISSUE TITLE
Proposed Lesson: Visualizing WWII Bombing Runs with Pandas and Bokeh

### ISSUE THREAD

**Issue by ianmilligan1** [programminghistorian/ph-submissions#139]
The Programming Historian has received the following proposal for a lesson on 'Visualizing WWII Bombing Runs with Pandas and Bokeh' by Charlie Harper (@archaeocharlie). The proposed learning outcomes of the lesson are:
     
- loading, cleaning and visualizing raw data;
- uses the "Theatre of Historic Operations" datasets on aerial bombings as a running example to create web-ready graphs and maps for browser
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 4 December 2017. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 4 December 2017, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @ianmilligan1. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by drjwbaker** [comment]
Just to add, I'll be following the editorial process in a leaning the ropes capacity!

**Comment by ianmilligan1** [comment]
Received! @drjwbaker and myself will read the piece and provide early feedback, and then we'll open up the ticket for review. 😄

**Comment by ianmilligan1** [comment]
Just to update: we provided feedback, and the author is going through and rejigging. Then we'll open up the review ticket.

**Comment by ianmilligan1** [comment]
Forgot to close this - it is continuing in #152 as a submission. 🎉
