### ISSUE TITLE
Proposed lesson: Introduction to MySQL with R

### ISSUE THREAD

**Issue by amandavisconti** [programminghistorian/ph-submissions#141]
The Programming Historian has received the following proposal for a lesson, "Introduction to MySQL with R", by Jeff Blackadar. The proposed learning outcomes of the lesson are:
     
 - Set up and connect to a table in MySQL  
 - Store records to the table  
 - Query the table  
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than February 4, 2018. The author agrees to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by February 4, 2018, the editor will attempt to contact the author. If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author.
 
The main editorial contact for this lesson is Amanda Visconti. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1.

**Comment by jeffblackadar** [comment]
A draft of the lesson is here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/getting-started-with-mysql-using-r.md

I need to create a table of contents, but I am wondering if there is a utility that does that in a standardized way.

**Comment by amandavisconti** [comment]
I added a table of contents using a generator script, but it sounds like we can create a better one (if using kramdown) like so:
```
* TOC
{:toc}
```
(HT @jeremyboggs)
I've promised to return initial feedback by the end of this weekend (1/21). Am currently reading through the lesson and leaving Hypothesis annotations; we'll move to a public reviewing ticket once I've completed that. Thanks!

**Comment by amandavisconti** [comment]
@jeffblackadar Hi, Jeff! I got stuck at [this point in the lesson](https://hyp.is/n03Y5vxjEeeowY9t6ODZSA/programminghistorian.github.io/ph-submissions/lessons/getting-started-with-mysql-using-r), working on a Mac. I'll keep troubleshooting, but wanted to check if there was something obvious I'm not doing? Thanks!

**Comment by ianmilligan1** [comment]
FWIW w/ the table of contents, there's this command tucked away [here](https://programminghistorian.org/editor-guidelines#3-add-a-table-of-contents-to-the-lesson), which automatically generates one. It has saved me a lot of time. 😄 

```
{% include toc.html %}
```

**Comment by jeffblackadar** [comment]
Thanks Amanda
I will check this out this evening
Jeff

On Thursday, January 18, 2018, Amanda Visconti <notifications@github.com>
wrote:
> @jeffblackadar Hi, Jeff! I got stuck at this point in the lesson, working
on a Mac. I'll keep troubleshooting, but wanted to check if there was
something obvious I'm not doing? Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/_9Eu75k5xUwCwRbt5AHKz7_FOAA4hbipQgNa0mDMZ7EBNVPfNTEJidmCOsG_9QgZ-nM3M6F185EICex1iSxUOSV_563M762wK7g63mPqiYYTGyoAeqSyD0IG3xucIJyrI1ENM6a07SexGi1BRGJbNYrmwTQGsg=s0-d-e1-ft#https://github.com/notifications/beacon/AclCT3RBvEeVUT6EEYhwVYb3EYREIjh5ks5tL2OBgaJpZM4QTfs_.gif>

**Comment by jeffblackadar** [comment]
Hi Amanda
I can reproduce the problem on a Mac.  I believe I need to download the 
MySQL Community Server and install it, start it and connect to it before 
running the query.  I'll work up some instructions for that.
Great catch, Thank you.
Jeff

**Comment by amandavisconti** [comment]
@jeffblackadar Excellent, thanks for troubleshooting! I know it's a bother to teach across operating systems. Fantastic lesson so far—I'll wait to finish feedback until you have a chance to work up those instructions.

**Comment by jeffblackadar** [comment]
Hi Amanda
I have been able to make MySQL workbench work on a Mac and sketched in 
some instructions.  But I would like to uninstall and go through it 
again and add some pictures.  I found the Mac installation to be 
complicated.  I'll redo the PC installation instructions at the same 
time, that will take me a few days and I might need until the weekend to 
finish that.
Jeff

**Comment by jeffblackadar** [comment]
Hi Amanda
I have better tested instructions with some tips for the Mac.  I believe
it`s ready for you to have another look.
Jeff

**Comment by amandavisconti** [comment]
Excellent! Thank you, Jeff. I'll read over this early in the week.

**Comment by amandavisconti** [comment]
Hi, Jeff! I apologize for not finishing reading this over last week—realized I should set a public deadline for my finishing that here. I will complete my feedback for you by the end of this week (Sunday 2/11) and share our next steps with you then.

**Comment by jeffblackadar** [comment]
Many thanks Amanda
Jeff

On Monday, February 5, 2018, Amanda Visconti <notifications@github.com>
wrote:
> Hi, Jeff! I apologize for not finishing reading this over last
week—realized I should set a public deadline for my finishing that here. I
will complete my feedback for you by the end of this week (Sunday 2/11) and
share our next steps with you then.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci6.googleusercontent.com/proxy/gJXcKm5SgOXanTHJE3Cd8OnpUhjEd9heURnJqZbAOi8AwpRGlw0SE3a03ReO69Yq8XxL7AEVZEmFF-vHnDUshp4A-ZVtO7kogFNQVubpvcSKl1MMeb-SK-T9a567lESM-3uWjHBf9b0k3cDqgWJ0yMtHBU8asQ=s0-d-e1-ft#https://github.com/notifications/beacon/AclCT0ySZ--8MIuJXQ8dbGxQQbHWjcSEks5tRw0rgaJpZM4QTfs_.gif>

**Comment by amandavisconti** [comment]
Hi, Jeff! I ran into a problem [here](https://hypothes.is/a/gsEwug-WEeiK2Re1Bg65gw) in the lesson. Could you advise how to proceed? I'm just not sure how/where to complete that step. I'll be able to complete going through the lesson after hearing how to proceed.

I've finished working through the lesson up to that point, though! My notes (still [as Hypothesis annotations here](https://via.hypothes.is/programminghistorian.github.io/ph-submissions/lessons/getting-started-with-mysql-using-r#create-a-database)—please let me know if there's another way you'd prefer for me to share my comments with you) are all small changes from a Mac user perspective—just trying to guess at places where folks not yet comfortable with CL or databases might get confused:
1. I tried to mark annotations "resolved" if you've updated the lesson in response to them (or if they don't need any action). Would you read through these and update or respond as desired?
2. Before we invite reviewers, it would be good to update the broken image links throughout the lesson (I think the empty ""s at the end of the image link are the culprit.).
3. Here are 3 annotated screenshots I made to solve the errors I ran into using the lesson on a Mac—might drop these into the lesson? (see [this annotation](https://hypothes.is/a/dsIXNg97EeiwJof079rTGw) for where)
![screen shot 2018-02-11 at 5 21 30 pm](https://user-images.githubusercontent.com/899033/36080772-a9ab5bde-0f63-11e8-8706-826027bc8c63.png)
![screen shot 2018-02-11 at 5 21 40 pm](https://user-images.githubusercontent.com/899033/36080773-a9bab8ae-0f63-11e8-87bf-7f0439fd8ebb.png)
![screen shot 2018-02-11 at 5 22 22 pm](https://user-images.githubusercontent.com/899033/36080774-a9c5cbd6-0f63-11e8-8bde-8b039c8657c4.png)

**Comment by jeffblackadar** [comment]
Hi Amanda
Thanks for all this, I will make these changes.  Some of them I may do 
over the 17-18 weekend in order to do them right.
Jeff

**Comment by amandavisconti** [comment]
@jeffblackadar Sounds good to me! 

**Edit**: just saw the note you added on the place where I got stuck. I'll see whether I can continue moving through the lesson.

**Comment by jeffblackadar** [comment]
@amandavisconti I might have misunderstood your issue.  If I did, feel free to send me a screen shot. Thanks for all your work!

**Comment by amandavisconti** [comment]
@jeffblackadar No, I must have just missed the text that explained that part! Thanks for pointing to it. I've finished working through the lesson.

This is an excellent lesson—I was excited when I got to generating the plot at the end! Most of my annotations are just places where I wanted to be sure absolute beginners would be comfortable.

Edits and suggestions are all available [here as Hypothesis annotations](https://via.hypothes.is/programminghistorian.github.io/ph-submissions/lessons/getting-started-with-mysql-using-r#connecting-to-the-database-with-a-password-stored-in-a-configuration-file), but do let me know if another format for sharing these would be easier for you.

Will you let me know here once you've had a chance to read through my comments and make any changes you want to make in response? I feel the lesson is then ready to enter the review stage, unless there's anything you would like to work on or discuss further. Once I hear from you that you're done making any changes, I'll create a review ticket and invite two reviewers to read through the lesson and share their thoughts ([you can read more about the review process here](https://programminghistorian.org/reviewer-guidelines)). The ticket will include the deadline the reviewers have agreed to respond by.

_Side note:_ There's a code formatting issue that's thrown the format of the rest of the lesson below line 358 off—the formatting displays fine when looking at the lesson as a markdown file in the repo after I added a space [with this commit](https://github.com/programminghistorian/ph-submissions/commit/64affd5429771818142b0044442f87b865f8ba14), but [the GitHub Pages version](programminghistorian.github.io/ph-submissions/lessons/getting-started-with-mysql-using-r#connecting-to-the-database-with-a-password-stored-in-a-configuration-file) is still off—I had notifications for the repo turned off so I'm not sure, but I'm guessing some build error is preventing the update from appearing and the formatting is now okay?

**Comment by jeffblackadar** [comment]
Thanks very much Amanda
I am glad to hear this. I will make changes and let you know.
Jeff

**Comment by jeffblackadar** [comment]
Hi Amanda
I have went through the Hypothesis comments and noted the ones I worked 
on as Actioned.
I think it's ready for another look.
Thanks,
Jeff

**Comment by amandavisconti** [comment]
Hi, Jeff! Excellent. I'll read through the lesson and set up a review ticket by the end of this weekend (3/4).

**Comment by amandavisconti** [comment]
@jeffblackadar Your lesson is looking good! I'm going to close this proposal ticket; we'll move to [a review ticket](https://github.com/programminghistorian/ph-submissions/issues/153), where anyone interested in the lesson can comment, and where I'll solicit two reviewers to share feedback with you as they read your lesson.
