### ISSUE TITLE
 Ticket de Revisión de Traducción: Introducción a la línea de comandos de Windows con PowerShell

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#146]
The Programming Historian en español ha recibido la siguiente propuesta de traducción *Introducción a la línea de comandos de Windows con PowerShell* por parte de @vgayolrs  . Esta traducción se encuentra en estos momentos en fase de revisión por parte de @silviaegt  y @jamotilla  y puede leerse en:

## Texto

http://programminghistorian.github.io/ph-submissions/es/traducciones/introduccion-a-powershell

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros ombudpersons.

## Política contra el acoso

Esta es una declaración de los principios de *The Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con María José Afanador-Llach.

**Comment by silviaegt** [comment]
a) La [liga del párrafo 1](http://programminghistorian.github.io/ph-submissions/es/traducciones/introduccion-a-powershell#referencia-rapida) no lleva a la tabla al final.
b) Tampoco la del [párrafo 2](http://programminghistorian.github.io/ph-submissions/es/traducciones/introduccion-a-powershell#Utilizaci%C3%B3n-de-herramientas-de-l%C3%ADnea-de-comandos-y-ejecuci%C3%B3n-de-secuencias-de-comandos-en-Python)
c) La liga de MALLET y Wget del párrafo 4 lleva a las lecciones en inglés aunque el texto dice que están en español 
d) La imagen del párrafo 7 está rota
[después continúo]

**Comment by arojascastro** [comment]
Gracias @silviaegt y @jamotilla por aceptar la revisión de esta traducción. 

Os recuerdo la guía para traductores: https://programminghistorian.org/es/guia-para-revisores#traducciones

Lo ideas sería que termináramos la revisión en un menos de un mes, pero como están las Navidades de por medio, podemos tomárnoslo con más calma. En cualquier caso, si alguno de los dos no puede llevarla a cabo, hacédnoslo saber y buscaremos una alternativa.

**Comment by jamotilla** [comment]
Estimados, mis observaciones son las siguientes:
Párrafo 65, línea 2: structura / estructura 
"" 71, línea 1: entinde / entiende 
"" 155, línea 1: su / tu
"" 184, línea 6: adejcuado / adecuado
"" 193, línea 2: Revisar hipervínculo "tutorial python"

**Comment by arojascastro** [comment]
Gracias @jamotilla. 

Si @silviaegt o @jamotilla no quieren añadir nada más (sobre el estilo, por ejemplo), creo @vgayolrs que puedes introducir los cambios. 

Intentaré leerme el tutorial una vez hayas hechos los cambios, antes de publicarlo, si te parece.

**Comment by jamotilla** [comment]
@arojascastro considero que la traducción no tiene problemas de estilo. Me parece que es clara. Saludos

**Comment by arojascastro** [comment]
¿Alguna novedad @vgayolrs? Gracias.

**Comment by vgayolrs** [comment]
¡Muchas gracias @silviaegt y @jamotilla por sus comentarios y correcciones! @arojascastro este fin de semana hago los cambios, muchas gracias!!!

**Comment by arojascastro** [comment]
¿Alguna novedad @vgayolrs? Gracias.

**Comment by arojascastro** [comment]
Este ticket lleva abierto desde diciembre y los cambios, que son muy pocos, se podrían haber hecho desde enero. @vgayolrs si quieres hago yo los cambios y así podemos publicarla. Quedo a la espera. Si no me respondes, cerraré el ticket la semana que viene.

**Comment by vgayolrs** [comment]
Gracias por la paciencia @arojascastro . Ya están las correcciones hechas. Falta lo de los enlaces. En general deben funcionar una vez que se pase la traducción a `/programminghistorian/jekyll/tree/gh-pages/es`. Acerca de la existencia o no de traducción al español de lecciones que marca @silviaegt , decidí poner entre paréntesis que aún se encuentran en inglés. Si te parece que hay que ponerlo de otra manera @arojascastro , lo hacemos.
Aprovecho para comentar que ya estoy terminando las responsabilidades por las que me tomé unas vacaciones de PH, así que a partir de junio estoy de vuelta con todo.
¡Muchas gracias, de nuevo, a @arojascastro @silviaegt y @jamotilla por cuidar de esta traducción!

**Comment by arojascastro** [comment]
Gracias. Me pongo con ello este fin de semana con el objetivo de publicar la lección en los próximos días.

**Comment by arojascastro** [comment]
Traducción publicada con éxito: https://programminghistorian.org/es/lecciones/introduccion-a-powershell

Gracias a todos. Se ruega difundir.
