### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jkrybicki** [programminghistorian/ph-submissions#154]
In general, the lesson makes a lot of sense - especially if it is supposed to be all-Python. Nothing wrong with that, especially if it is aimed at PROGRAMMING historians rather than those who just need a ready-made tool for analysis without learning to code - in which latter case I would strongly recommend stylo, a package for R (naturally, since I am one of its authors). 
It is a good if perhaps somewhat ambitious idea to start off with the Federalist Papers. I am much less happy about Mendenhall, whose method is highly dubious from both linguistic and statistical points of view. Perhaps simple t-testing of most-frequent-word usage would work better? Or - even better - add Burrows's Zeta instead (perhaps as third method after his Delta). BTW, it's Burrows, nor Burrow (he's not some kind of Hobbit, just an Aussie), hence Burrows's, not Burrow's! :-)
In the introduction to the lesson, I would also suggest a stronger emphasis on the idiosyncratic use of most frequent words (rather than a more general "vocabulary"); and perhaps also a comment on how those frequent words yield the signals of genre and chronology as well as authorship; for the same reason, the link between styometry for authorship and stylometry for distant reading should be mentioned.
Overall, though: good stuff!

**Comment by acrymble** [comment]
Thank you @jkrybicki for this review. I've moved it to our review ticket number #147 where the author will be able to respond.

Thanks again for sharing your expertise.
