### ISSUE TITLE
Review Ticket: Visualizing Data in R with ggplot2

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/ph-submissions#155]
The Programming Historian has received the following tutorial on 'Visualizing Data with R and ggplot2' by Igor Sosa Mayor (@rogorido). The proposed learning outcomes of the lesson are:

This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/visualizing-data-with-r-and-ggplot2

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by mdlincoln** [comment]
@rogorido go ahead and fix up the image links.

**Comment by rogorido** [comment]
@mdlincoln done!

**Comment by mdlincoln** [comment]
Thanks @rogorido. I'm going to take time over the enxt week to read through one more time myself and check if I have any additional questions. After that, I'll recruit two formal peer reviews for the lesson, and I will keep you notified at each step along the way.

**Comment by mdlincoln** [comment]
Most importantly, let's get the images working. Make sure you follow our style guide here which explains how to properly link to them and include captions: https://programminghistorian.org/author-guidelines#including-images

Other notes:

- [ ] p.1 Your opening lines sound awkward. I suggest directly stating that visualizing quantities is a critical historical skill, and this lesson will explain how.
- [ ] p.3 add references to published lessons
- [ ] p.7 "You also can run the queries again changing" doesn't make sense in English. I think you should also say here that the rest of the results and figures in this lesson are made using the attached data file, and if users choose to download new data then their results may differ slightly. If you say this once, then you can remove all the other caveats later in the lesson (like in p.9 for example)
- [ ] p.8 This is a good place to reference specific parts of https://programminghistorian.org/lessons/r-basics-with-tabular-data, so that users who need to setup R can do so. 
- [ ] p.12 This link to the dataframe is broken - however, I would not offer it in the first place. It is confusing that you are offering multiple versions of data for the user to download, with too many optional paths for them to follow. Give them one CSV to work with, provide the simple dplyr code for running the transformations, and move on.
- [ ] p.15-16 Further resources for ggplot2 should come at the end of the lesson, rather than right at the beginning. It shouldn't take scrolling down 1/4 of the page before we start making plots.
- [ ] p.17 You already installed ggplot2 in p.12. Just have the user install `tidyverse` in p.12 when running the transforms so it's less confusing.
- [ ] p.36 Users may be confused by the sudden introduction of `stat_` layers without further explanation. I don't know if there's an easy way to explain what they do separately from the `geom_` functions... but I'd make a note of the difference, or instead do the same thing using dplyr code + ggplot instead. Just a suggestion.
- [ ] p.39 Boxplots may not be a natural way of visualizing data for many of our readers, so you probably need a sentence or two explaining what exactly boxplots do.
- [ ] ANOVA tests will also be totally unfamiliar. Since you are not showing how to do ANOVA tests here, I might remove this reference.
- [ ] You need a concluding paragraph that reminds readers of the core principles they have learned. This is also a good place to put the further ggplot2 readings from p.15-16

There are also still a fair amount of typos here, so you might want to read through again before we send it off to reviewers. Post-review I'll also be doing a close reading for other corrections so it is ok if we don't catch everything right now.

**Comment by rogorido** [comment]
@mdlincoln Thanks a lot for your comments. Next week I will be able to correct the issues you're mentioning.

**Comment by arojascastro** [comment]
Sorry to jump into this discussion - let me make clear that this is an unsollicited contribution. I was reading the tutorial and I found it very interesting. I think the author is posing very interesting questions from a transnational perspective - that is, making history beyond national borders. 

However, considering that this tutorial will be probably translated into Spanish, why not to answer some questions that the author is pointing to us such as "Have Spanish cities proportionally more relationships to the spanish-speaking American cities?". It would be great to see the relationship between Spain and Latin American countries... 

If that is not possible, can I ask why the dataset does not include Spanish data. The author says: "In the present tutorial we will use only the data of six EU-countries: Germany, France, Poland, Hungary, Portugal, Bulgaria (three of so-called Western Europe and three of so-called Eastern Europe)." For me that sample is fine, but it would be greater if it included data from Spain since the tutorial is going to be translated into Spanish and it will be addressed directly to Spanish speakers.

Thanks! And again sorry for jumping into your conversation.

**Comment by rogorido** [comment]
Hi, I'm the author and I'm Spaniard. I could translate the text into SPanish. Regarding your question: I had to make a selection of countries, because otherwise I had too many data and this was causing "problems" with some plots (overplotting). Besides, it could have been too much data for some computers. In any case the data are avalaible also for Spain in my repository. 

Give me a few days and I will correct all issues and think about your suggestion and the Spanish version.

**Comment by mdlincoln** [comment]
Thanks for your very thoughtful suggestions @arojascastro ! 

@rogorido I will ask you to please wait on implementing @arojascastro suggestions until we get our two official peer reviews in. I will explain our workflow:

The two peer reviewers will likely ask for additional substantive changes, and it will be easier for you and me if we **wait to collect all of this feedback** before significant rewrites. Once both peer reviewers have submitted their responses, I will summarize both their suggestions as well as any other suggestions (like @arojascastro gave) from this period of open review. Working together, you and I will then decide which of the changes make sense to implement. This way, we only do one more round of substantive rewriting, rather than multiple rounds.

For now, please just attend to my stylistic comments, mostly so we can get the images working. I think we will definitely attend to what @arojascastro suggests, but it will be very useful to plan those additions once we have all the feedback from reviewers.

**Comment by mdlincoln** [comment]
@rogorido Have you had a chance to address the last few stylistic comments before we begin the review process?

**Comment by mdlincoln** [comment]
@rogorido What's the status on this lesson? I need to hear an update from you within the next week, or I'll close this submission for now.

**Comment by nabsiddiqui** [comment]
@mdlincoln @rogorido What is the status of this lesson?  I was thinking about submitting a tutorial for ggplot2 but noticed that this one was already created but closed.

**Comment by mdlincoln** [comment]
@nabsiddiqui Thank you for checking. This lesson proposal has been closed. If you're interested in proposing a new ggplot2 lesson, please go ahead and email the appropriate managing editor: https://programminghistorian.org/en/author-guidelines

**Comment by nabsiddiqui** [comment]
Thank you.  I will go ahead and submit a proposal in the coming days.

**Comment by rogorido** [comment]
yes, I will finish the proposal in the next days.

**Comment by mdlincoln** [comment]
@rogorido as I noted in my email to you today, we closed this submission after losing contact with you over a year ago. The editorial board will discuss this issue and make a decision in January.

**Comment by nabsiddiqui** [comment]
@mdlincoln I'll cancel my attempt at the proposal then.  If anything changes, please let me know.  I will be happy to create a new tutorial or work with @rogorido to do it collaboratively if you guys need something.

**Comment by rogorido** [comment]
@mdlincoln I have answered your email. @nabsiddiqui maybe we could do something together...
