### ISSUE TITLE
Ticket de revisión de traducción: Crear exposición con Omeka 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#156]
'The Programming Historian en español' ha recibido la siguiente propuesta de traducción _Crear una exposición en Omeka_ de la lección _Creating an Omeka exhibit_ por parte de @mjcabra. Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/crear-exposicion-con-omeka

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

Política contra el acoso
_

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jenniferisasi** [comment]
La traductora de este tutorial no puede cargar el archivo en la carpeta de traducciones, @arojascastro @jamotilla @mariajoafana ¿alguno me puede ayudar?

**Comment by jenniferisasi** [comment]
Falta añadir las imágenes al archivo. 

@josebakmoreno se ha ofrecido como primer revisor de esta traducción al español. Joseba, antes de nada, por favor, revisa nuestra guía para revisores: https://programminghistorian.org/es/guia-para-revisores

**Comment by arojascastro** [comment]
¿Qué archivo? No acabo de entenderlo.

- las traducciones pendientes de revisar van en `ph-submissions/es/traducciones`
- los materales pendientes de revisar van en `ph-submissions/assets`
- las imágenes pendientes de revisar van en `ph-submissions/images`

Normalmente los editores suben los archivos, así que es mejor que te lo envíe todo a ti.

**Comment by jenniferisasi** [comment]
Muchas gracias @arojascastro. Era su traducción .md la que no podía subir a `ph-submissions/es/traducciones` ... Al final lo he subido yo para comenzar una primera revisión. Tendré esto en cuenta para el futuro.

**Comment by arojascastro** [comment]
En principio, según nuestra guía para autores, el autor debería subir la traducción, tras darle permiso en el repositorio: https://programminghistorian.org/es/guia-para-autores#enviar-una-traducci%C3%B3n-o-una-lecci%C3%B3n-nueva

Sin embargo, a veces es más rápido que lo hagamos nosotros. ¿Quizás deberíamos cambiar las guías? No sé, así es como lo hace el equipo inglés y nosotros lo copiamos, pero en la práctica, ya te digo, acabamos haciándolo nosotros.

**Comment by josebakmoreno** [comment]
**Párrafo 1** 
Sugerencia: "Es necesario pensar la exposición antes de empezar a crear la exposición."-->"Es necesario pensar en la exposición antes de empezar a crearla."
Cambio: "necesitatrás"--> "necesitarás"

**Párrafo 2**
Cambio: "Exhibit_ " y "Add an exhibit_."--> "Exhibit" y "Add an exhibit"
Cambio: "Formato"-->"Formulario" o alguna expresión similar como "campos" 
Sugerencia: "leíble" --> "legible". "leíble" aparece en el diccionario pero como  adjetivo poco usado. 

**Párrafo 5**
Cambio:  "solo"--> "sólo" (dos instancias)

**Párrafo 7**
Sugerencia: "También agregué un texto interno en el campo “Text”." --> El cambio a primera persona puede resultar un poco confuso al leer este párrafo, ¿es un cambio intencional? 

**Párrafo 8 y 9**

Sugerencia: "sitio Omeka" --> la traducción se entiende bien, pero puede que sea más apropiado incluir una preposición, "de" o "en", para acercar más la traducción a la convención española.

**Comment by mjcabra** [comment]
Hola,


Realizaré los cambios señalados y agregaré las imágenes correspondientes.


Saludos,


María José

________________________________
De: Joseba <notifications@github.com>
Enviado: domingo, 22 de abril de 2018 8:24:25 p.m.
Para: programminghistorian/ph-submissions
Cc: Maria Jose Cabra Montes; Assign
Asunto: Re: [programminghistorian/ph-submissions] Ticket de revisión de traducción: Crear exposición con Omeka (#156)


Párrafo 1
Sugerencia: "Es necesario pensar la exposición antes de empezar a crear la exposición."-->"Es necesario pensar en la exposición antes de empezar a crearla."
Cambio: "necesitatrás"--> "necesitarás"

Párrafo 2
Cambio: "Exhibit_ " y "Add an exhibit_."--> "Exhibit" y "Add an exhibit"
Cambio: "Formato"-->"Formulario" o alguna expresión similar como "campos"
Sugerencia: "leíble" --> "legible". "leíble" aparece en el diccionario pero como adjetivo poco usado.

Párrafo 5
Cambio: "solo"--> "sólo" (dos instancias)

Párrafo 7
Sugerencia: "También agregué un texto interno en el campo “Text”." --> El cambio a primera persona puede resultar un poco confuso al leer este párrafo, ¿es un cambio intencional?

Párrafo 8 y 9

Sugerencia: "sitio Omeka" --> la traducción se entiende bien, pero puede que sea más apropiado incluir una preposición, "de" o "en", para acercar más la traducción a la convención española.

**Comment by jenniferisasi** [comment]
@mjcabra ¿has podido avanzar en el tutorial? Gracias.

**Comment by jenniferisasi** [comment]
Hola @mjcabra, ¿has podido realizar los cambios? En cuantos los hagas yo haré la segunda revisión del tutorial para poder publicarlo a finales de este mes. Gracias.

**Comment by jenniferisasi** [comment]
Hola @mjcabra , ¿has podido realizar los cambios sugeridos por Joseba? Si es posible, me gustaría poder publicar este tutorial hacia finales de mes. Gracias.

**Comment by jenniferisasi** [comment]
Aquí mi revisión; algunas cosas son de estilo markdown: 
- Cambiar las comillas de "Exhibits", "Add an exhibit" etc. a formato en negrita 
- Sección: "Agrega un bloque de contenido a tu página" falta el último párrafo
- párrafo 12: puede --> puedes (todo en tú) 
- desde la sección "Agrega una página" las fotos no están en su sección
Dos notas sobre la traducción:
- Aunque las imágenes sean las mismas que el tutorial en inglés, hay que traducir la explicación que viene debajo (al pie de la imagen).  
- Conviene añadir el equivalente al español de los nombres de los botones, por ejemplo, Exhibits (exposición), Add an exhibit (agrega una exposición), etc. 

@mjcabra avísame por favor cuando realices estos cambios o si tienes cualquier duda, y proceder así a mi última lectura y posiblemente su publicación. Gracias

**Comment by jenniferisasi** [comment]
Traducción publicada [https://programminghistorian.org/es/lecciones/crear-exposicion-con-omeka](https://programminghistorian.org/es/lecciones/crear-exposicion-con-omeka). 
Gracias @mjcabra por tu trabajo y @josebakmoreno por tu revisión. Cierro.
