### ISSUE TITLE
Ticket the revisión de traducción: Instalar Omeka

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#157]
'The Programming Historian en español' ha recibido la siguiente propuesta de traducción _Instalando Omeka_ de la lección _Installing Omeka_ por parte de @melisacastro. Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/instalar-omeka

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

Política contra el acoso
_

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
El enlace da 404, creo que la ruta no está bien :)

Díría que falta el archivo en la `es/traducciones` o bien que el nombre del archivo es incorrecto.

**Comment by jenniferisasi** [comment]
@melisacastro gracias por tu traducción. @josebakmoreno será el primer revisor para este tutorial y yo revisaré el formato markdown puesto que hay algunos errores a primera vista. Muchas gracias.

**Comment by josebakmoreno** [comment]
Hola @melisacastro y @jenniferisasi ,

Después de leer la traducción creo que sería una buena idea que la autora revisara la ortografía y puntuación en general, ya que hay bastantes erratas. También parece que han quedado algunas palabras en inglés que hay que eliminar o traducir. Respecto a otras traducciones: puede que la traducción más apropiada de "run" en este texto no sea "correr" (párrafos 20/59).  Por último, en términos de estilo, puede que sea más conveniente usar la misma persona durante todo el tutorial, al principio se usa "tú" y después en el texto se cambia a "usted". 
Por favor escribidme con cualquier pregunta. Después de estos cambios estaría bien darle otra leída, ¿no?
Saludos

**Comment by melisacastro** [comment]
Buenas tardes,


¿Debo corregir el archivo en md y volverlo a subir a Gihub?. Con respecto a "run=correr" no he visto cual es el lugar en donde está exactamente, pero de lo que recuerdo hablaba de correr el programa, y así se dice al menos en mi paísad. Hay otras plabras en Inglés a las que no les encontré traducción.


Muchas gracias.

________________________________
De: Joseba <notifications@github.com>
Enviado: lunes, 4 de junio de 2018 1:08:28 p.m.
Para: programminghistorian/ph-submissions
Cc: Melisa Castro Diaz; Mention
Asunto: Re: [programminghistorian/ph-submissions] Ticket the revisión de traducción: Instalar Omeka (#157)


Hola @melisacastro<https://github.com/melisacastro> y @jenniferisasi<https://github.com/jenniferisasi> ,

Después de leer la traducción creo que sería una buena idea que la autora revisara la ortografía y puntuación en general, ya que hay bastantes erratas. También parece que han quedado algunas palabras en inglés que hay que eliminar o traducir. Respecto a otras traducciones: puede que la traducción más apropiada de "run" en este texto no sea "correr" (párrafos 20/59). Por último, en términos de estilo, puede que sea más conveniente usar la misma persona durante todo el tutorial, al principio se usa "tú" y después en el texto se cambia a "usted".
Por favor escribidme con cualquier pregunta. Después de estos cambios estaría bien darle otra leída, ¿no?
Saludos

**Comment by josebakmoreno** [comment]
[revision instalar omeka.docx](https://github.com/programminghistorian/ph-submissions/files/2069620/revision.instalar.omeka.docx)

He añadido un documento de word con marcas y correcciones para que te sea más fácil encontrar las erratas o las cosas que hay que traducir, son mis notas personales, así que espero que tenga sentido. 
Lo de "run", si tú crees que es algo actual que se entiende bien en general, déjalo como "corriendo". Una alternativa podría ser "ejecutar". Dime si no puedes ver el archivo que he adjuntado, por favor. 

Un saludo,

**Comment by jenniferisasi** [comment]
Muchas gracias por tus comentarios @josebakmoreno. @melisacastro puedes hacer los cambios en tu archivo .md y volverlo a subir, pero teniendo en cuenta los datos que yo ya añadí [en el archivo aquí en Github](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/instalar-omeka.md) o hacer los cambios directamente en el archivo en Github (hay un lápiz de editar arriba a la derecha). 
¿Para cuándo podrás hacer los cambios? Una vez que los realices yo revisaré el tutorial por última vez para publicarlo. Muchas gracias.

**Comment by jenniferisasi** [comment]
Hola @melisacastro, ¿has podido realizar los cambios sugeridos por Joseba? Si es posible, me gustaría poder publicar este tutorial hacia finales de mes. Gracias.

**Comment by jenniferisasi** [comment]
Doy cierre a este ticket por haber sobrepasado las fechas límite de entrega varias veces y por no recibir una revisión completa de la traducción tras haber recibido los comentarios por parte del revisor y de la editora. Si en algún momento la traductora se pone en contacto conmigo, volveré a abrir el ticket.
