### ISSUE TITLE
Review Ticket for Blog Post

### ISSUE THREAD

**Issue by tapar001** [programminghistorian/ph-submissions#16]
I'm not sure this is the right place for this announcement, since this space is for lesson submissions--but I just wanted to let you all know I submitted a re-introductory blog post. 

A few questions: 

1) The format for the metadata block seems off. Suggestions for what went wrong/how I can fix it? 

2) I know a link to a live preview is usually included here, but I don't know how to do that. 

3) Is this the right place to submit blog posts? Or should there be a separate directory for blog posts?

**Comment by ianmilligan1** [comment]
Fixed - it was the kind of dash used (a regular dash vs. an em dash, I think). 

Here's a live demo: http://programminghistorian.github.io/ph-submissions/lessons/ph-blog.

This looks great, @tapar001 and @miriamposner. I think when editors are writing posts we can go right ahead and publish it on the main repo, rather than using the `ph-submissions` branch. And I'd say handle how people submit blog posts however you think is best?

**Comment by tapar001** [comment]
Great, thanks Ian!

I like the idea of editors' posts being published on the main repo. As for
posts written by contributors who aren't on the editorial board, I wonder
if I might submit them to ph-submissions first so that editors, if they
wish, can check out new posts before they go live? I'm open to thoughts on
this.

On Tue, Mar 22, 2016 at 10:32 AM, Ian Milligan notifications@github.com
wrote:

> Fixed - it was the kind of dash used (a regular dash vs. an em dash, I
> think).
> 
> Here's a live demo:
> http://programminghistorian.github.io/ph-submissions/lessons/ph-blog.
> 
> This looks great, @tapar001 https://github.com/tapar001 and
> @miriamposner https://github.com/miriamposner. I think when editors are
> writing posts we can go right ahead and publish it on the main repo, rather
> than using the ph-submissions branch. And I'd say handle how people
> submit blog posts however you think is best?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/ph-submissions/issues/16#issuecomment-199867991

## 

Evan Taparata
Ph.D. Candidate, History Department
University of Minnesota
1100 Heller Hall
271 19th Ave S
Minneapolis, MN 55455

**Comment by acrymble** [comment]
Personally I don't need to see blog posts before they go out. I see that as
your domain. I may send things in from time to time but otherwise, all yours

All the best, Adam

**Comment by ianmilligan1** [comment]
Agree with @acrymble!

**Comment by miriamposner** [comment]
This looks awesome, @tapar001! Honestly, though, I don't think it's right for me to be a co-author. You wrote the whole thing; I just looked it over. We worked together on the other post, but this one was really your work.

**Comment by wcaleb** [comment]
I agree that blog posts don't need to go through `ph-submissions`. The repo isn't currently set up with a `_posts` directory anyway, so the live preview would not even be exactly correct. 

Remember that when you publish the post on the live site, you'll need to [name the file a certain way](https://github.com/programminghistorian/jekyll/wiki/Creating-Blog-Posts). Also, you won't need to include a header for the title, because the title and author will be automatically produced from the metadata block. See a [current post](https://github.com/programminghistorian/jekyll/blob/gh-pages/_posts/2012-06-27-welcome-to-ph2.md) for an example.

Thanks for jump-starting this!

**Comment by wcaleb** [comment]
P.S. @tapar001 If you do decide you want to preview non-editor posts, let me know and I can set up this repo so that it will live preview blog submissions. By noting that it's not set up to do that now, I didn't mean to suggest that it _couldn't_ be.

**Comment by fredgibbs** [comment]
I like the idea of not using the repo for blog previews, just to keep life simpler. While I fully agree, @tapar001, that you're in charge of the blog and that it's undesirable for others to micromanage it, I think there is something to be said for running a potential blog post by the group ahead of posting it. I think the Google Group email list could be helpful here. That way, we all know what's going on and if anyone has a quick comment of suggestion, it's easy to give feedback. And it's easy to ignore, too, but at least everyone is in the loop. And if there is a major concern (quite unlikely), we can defer to an editorial call. The email preview from last time seemed like a good process to continue in my opinion, but we don't need anything more formal.

**Comment by acrymble** [comment]
Does this need to remain open? Or has this been resolved?

**Comment by tapar001** [comment]
Hi all,

Sorry for my delay--been juggling deadlines and prepping for
research/conference travel.

Miriam--if you think it's more appropriate to take your name off the byline
I'll go ahead and make that edit.

Fred's idea to share posts via the Google list before posting sounds good
to me. I definitely don't want to give anyone more work, but I'd also like
you all to check out posts before they go live, if that's something you're
interested in doing.

I'll try to get the post online later this afternoon and I'll be in touch
again if I have any trouble. Maybe we can leave this ticket open for now
until the post is live?

Thanks again everyone,
Evan

On Monday, March 28, 2016, Adam Crymble notifications@github.com wrote:

> Does this need to remain open? Or has this been resolved?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/programminghistorian/ph-submissions/issues/16#issuecomment-202338383

## 

sent from a mobile device

**Comment by tapar001** [comment]
Hi again all,

Forgot to mention this in my last message but Caleb--thanks for sending
those links with instructions on the file name and how to publish posts to
the blog! They were very helpful.

I was able to get the post onto the site, but I'm running into a snag with
adding my avatar.

I tried adding my avatar info into the metadata front matter, but it
doesn't appear on the live post. Should I be adding the avatar somewhere
else?

Thanks again,
Evan

On Mon, Mar 28, 2016 at 11:36 AM, Evan Taparata tapar001@umn.edu wrote:

> Hi all,
> 
> Sorry for my delay--been juggling deadlines and prepping for
> research/conference travel.
> 
> Miriam--if you think it's more appropriate to take your name off the
> byline I'll go ahead and make that edit.
> 
> Fred's idea to share posts via the Google list before posting sounds good
> to me. I definitely don't want to give anyone more work, but I'd also like
> you all to check out posts before they go live, if that's something you're
> interested in doing.
> 
> I'll try to get the post online later this afternoon and I'll be in touch
> again if I have any trouble. Maybe we can leave this ticket open for now
> until the post is live?
> 
> Thanks again everyone,
> Evan
> 
> On Monday, March 28, 2016, Adam Crymble notifications@github.com wrote:
> 
> > Does this need to remain open? Or has this been resolved?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/programminghistorian/ph-submissions/issues/16#issuecomment-202338383
> 
> ## 
> 
> sent from a mobile device

## 

Evan Taparata
Ph.D. Candidate, History Department
University of Minnesota
1100 Heller Hall
271 19th Ave S
Minneapolis, MN 55455

**Comment by wcaleb** [comment]
@tapar001 The avatar was removed from blog posts in https://github.com/programminghistorian/jekyll/commit/9880df32664f895823586e461d3d1e58123e0e34, though I can't quite remember why we did this. It can be added back if that's what we want. At any rate, the post looks good!
