### ISSUE TITLE
Ticket the revisión de traducción:"Transformación de datos con XML y XSL para su reutilización"

### ISSUE THREAD

**Issue by jamotilla** [programminghistorian/ph-submissions#162]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Transformación de datos con XML y XSL para su reutilización* de la lección *Transforming Data for Reuse and Re-publication with XML and XSL* por parte de @arojascastro . Esta traducción se encuentra en estos momentos en fase de revisión por @pcarrillo y @jamotilla y puede leerse en:

### Texto 

http://programminghistorian.github.io/ph-submissions/es/traducciones/transformacion-datos-xml-xsl

### Materiales

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/scissorsandpaste-master.zip

### Imágenes

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/transforming-xml-with-xsl

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

**Política contra el acoso**

> El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Thanks @jamotilla. Revisaré el texto en los próximos días, y quizá añada alguna referencia bibliográfica al final.

I am wondering why the pre-visualization is not the expected. Can you help us @mdlincoln? What metadata field is missing?

**Comment by mdlincoln** [comment]
@arojascastro This error was really hard to see! A period placed outside the quotation marks in the lesson abstract meant that Jekyll could not properly read the YAML, and so didn't know to render this page using the `lesson` template. I've fixed it with cf459385d83b31fedfaa7d0ca622792963f3dfd7

**Comment by arojascastro** [comment]
Omg, thank you! I couldn't see it either. I really thank you and I apologize for writing you an email.

**Comment by pcarrillo** [comment]
Thank you so much @mdlincoln Now I can work properly :)

**Comment by arojascastro** [comment]
Hola, ¿alguna novedad @pcarrillo?

**Comment by pcarrillo** [comment]
Perdón por el retraso. La revisión está lista desde el día 2 del proceso. Pero quería revisar de nuevo con calma para no hacer los comentarios en caliente y tener algo de distancia. Estoy en ello ahora. Lo publico más tarde :)

**Comment by pcarrillo** [comment]
@arojascastro gran trabajo con la traducción. Siempre es un trabajo duro y un gran quebradero de cabeza no siempre reconocido :) Congrats!

Mis comentarios son meras observaciones. Lo único que me "preocupa" es que la estructura del texto original es susceptible de mejora, en mi opinión.  El cualquier caso esta es mi aportación. :)

1. P1. "Un colega te llama por teléfono". Colega o amigo? No queda claro si se refiere a un compañero de trabajo o a un amigo cercano. Habría que ajustar a la variedad lingüística de acuerdo a los destinatarios del texto. Propuesta: "compañero de trabajo", "amigo"
2. P3. "El degano". Typo.
3. P4. Podría ser útil enlazar a una definición de base de datos XML. O base de datos y luego a lo que es una BD XML.
4. P5. Me resulta algo extraño usar los términos en inglés y la explicación entre paréntesis. Ta vez sea más natural usar la traducción en castellano y la referencia entre paréntesis o con explicativas. Creo que que como esto se repite a lo largo del texto, podría hacerse de una manera sistemática para mantener la coherencia.
5. P6. Sería más claro si se conecta el concepto de las BD de este párrafo con lo del P4.
6. P10. Unificar criterio de traducción de acuerdo a lo que se use en P5 y siguientes.
7. P12 y P13. Estos párrafos están geniales pero serían muy útiles al inicio del texto a manera de guía para el lector. ¿Replicarlo, moverlo?
8. P14. 
	1. "programas para visualizar" por "visualizarlos".
	2. Además de los editores recomendados yo incluiría Sublime Text y Visual Studio Code.
9. P14 y P15. Hay cierta confusión en el asunto de los editores y formatos entre los P14 y P15.
10. P16 y P17. Estos párrafos son muy confusos. Supongo que es herencia del texto original. Yo lo revisaría para buscar claridad.
11. P18. No se explica lo que es un XML bien formado. Valdría la pena hacerlo o al menos enlazar a una explicación detallada que refuerce el concepto.
12. P19. 
	1. "*Scissors and Paste* es una colecciones". Revisar concordancia.
	2. No se ha explicado el concepto de metadatos. Un enlace sería conveniente.
13. P21. Una lista de recomendaciones y enlaces podría estar bien. ¿Linux? 
14. Me pregunto si no se pueden ampliar los textos más allá de la traducción. Por ejemplo, agregar enlaces adicionales como un tutorial de TEI existente como http://teibyexample.org. Esta consideración es muy seria porque el tutorial está muy bien pero creo que podría funcionar muy bien en Castellano si se adapta más allá de la traducción y de conservar los aspectos formales originales
15. P39. Desarrollar el acrónimo URI como en los otros casos? 
16. P40. Falta un punto después de "se producirá un error".
17. Tal vez "hacer coincidir o emparejar" sea más natural. No estoy seguro.
18. P46. Usar un fichero de texto plano tan básico me parece que genera un capa adicional de complejidad. ¿Por qué no usar un editor que le facilite el trabajo al usuario final?
19. P47. "Te habrás dado cuenta de que no hemos incluido una etiqueta de cierre". Esto podría explicarse junto al XML Well Formed y aquí enlazar.
20. P48. "Un mensaje de error", ¿no suena muy genérico?
21. P53. ¿Los paréntesis no son muy ingleses?, ¿mejor una explicativa?
22. P64. 
	1. La repetición de la palabra bucle podría resultar confusa. 
	2.  No quedan suficientemente destacadas las instrucciones del texto general. 
	3.  ¿Enlaces a explicaciones de estructuras de control en Wikipedia o similar?
23. P65. El lector tal vez no sepa lo que es un "registro" dentro de la terminología de Bases de Datos. ¿Enlace o explicación?
24. P70. Enlace roto. Sería esclarecedor dar un poco más de información sobre la ISO o el UNICODE.
25. P76. Un ejemplo con una fecha más explícita evitaría la confusión. Algo como "1789-01-30". Así el día no se confundiría con el mes. También se puede mostrar el formato entero: YYYY-MM-DD.
26. P82. "artículos ordenados de más a menos recientes". Esto podría explicarse mejor e introducir el concepto de fecha ascendente/descendente que es bastante común en criterios de ordenación.
27. P90. La explicación del uso del "." es muy sucinta. Podría enlazarse a una explicación más detallada ya que es algo un poco abstracto.
28. P91. Las sigas HEX no se han desarrollado ni explicado. ¿Enlace?
29. Fig 2: Tal vez la captura sea muy grande. ¿No sería más preciso una captura más sencilla?
30. Fig 3: las líneas son muy largas. ¿Reducir un poco la ventana para mejorar la legibilidad?

**Comment by jamotilla** [comment]
Muchas gracias @pcarrillo y @arojascastro, estoy a punto de terminar mi revisión, la subiré a la brevedad. Saludos.

**Comment by jamotilla** [comment]
Estimado @arojascastro. Mis observaciones son mínimas. Revisé las sugerencias hechas por @pcarrillo y me parecen pertinentes, definitivamente los dos han hecho un gran trabajo.

p.3 degano / decano 
p.17 Antes de seguir adelante, pues, te recomendamos descargar e instalar uno de estos dos navegadores, si aún no lo tienes en tu ordenador/ Creo que se podría eliminar el “pues”, está de más y resta formalidad al texto 
p.43, línea 2,  no se si sea pertinente entrecomillar la barra lateral “/“ para unificarlo con el de la quinta línea.

**Comment by arojascastro** [comment]
Gracias a los dos; haré los cambios durante el fin de semana (espero). Seguramente incluya algunas notas más y algo de bibliografía suplementaria.

**Comment by arojascastro** [comment]
He hecho los cambios que he considerado oportunos y he añadido bibliografía y notas. Por favor, sincronizad los cambios o bien consultad la lección en http://programminghistorian.github.io/ph-submissions/es/traducciones/transformacion-datos-xml-xsl

(He cambiado el nombre del archivo)

En general, he hecho todo lo que me pedís con muy pocas excepciones. Por ejemplo, no he modificado las imágenes como me pedía Pedro porque no tengo tiempo de volver a hacer todo el ejercicio de nuevo (además, las imágenes se pueden ampliar clicando sobre ellas); he preferido invertir el tiempo disponible en anotar el texto y dar más referencias bibliográficas. Sería genial si alguno de los dos pudiera revisar los cambios.

Quedo a la espera. Gracias a los dos.

**Comment by arojascastro** [comment]
El 15 de julio me voy de vacaciones. ¿Podemos publicar antes? De lo contrario, tardaremos un mes más.

**Comment by jamotilla** [comment]
Estimado @arojascastro he consultado la lección y creo que está lista para ser publicada

**Comment by arojascastro** [comment]
¡Genial! Todo tuyo.

**Comment by jamotilla** [comment]
La traducción "Transformación de datos con XML y XSL para su reutilización" ha sido publicada. Gracias a todos, especialmente a @arojascastro, @pcarrillo y @mdlincoln / @mhbeals your tutorial has been translated to spanish and published in the programming historial "en español" site, you can check the tutorial in https://programminghistorian.org/es/lecciones/transformacion-datos-xml-xsl
