### ISSUE TITLE
Ticket the revisión de traducción: "Datos tabulares en R"

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#164]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Datos tabulares en R* de la lección *[R Basics with Tabular Data](https://programminghistorian.org/lessons/r-basics-with-tabular-data)* por parte de @jenniferisasi . Esta traducción se encuentra en estos momentos en fase de revisión por @josebakmoreno y @ajspadial. Puede leerse en:

### Texto 

http://programminghistorian.github.io/ph-submissions/es/traducciones/datos-tabulares-en-r

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

**Política contra el acoso**

> El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jenniferisasi** [comment]
@josebakmoreno veo que hay algunos errores en la presentación del tutorial en cuanto a enlaces, las notas y, luego, dentro de lo que son los resultados de los códigos algunos números aparecen como enlazados a algo. Por favor, ignora dichos errores en tu revisión mientras yo le busco solución.

**Comment by josebakmoreno** [comment]
Hola @jenniferisasi, 

Aparte de los errores que mencionas tú, sólo he encontrado tres de cosas que, yo creo, podrían ser editadas.

108 "A veces es más fácil crear tu propio archivo usando un programa de hojas de cálculo como Excel u Open Office para asegurarte de que toda la información que quieres estudiar está organizada y para importar dicho archivo a R". Creo que esta frase se puede dividir en dos para clarificar el mensaje. 
110 "un archivo Excel"--> "un archivo de Excel"
121 "Esto tutorial" --> "Este tutorial"
Cuando soluciones lo de las imágenes y lo de los enlaces, lo puedo revisar de nuevo. 

Un saludo, 

Joseba

**Comment by arojascastro** [comment]
Gracias @josebakmoreno por tu revisión.

I am wondering if @mdlincoln can help us to solve the problems with Markdown. 

In the meantime, we wait until @ajspadial for his comments. After that, @jenniferisasi will change the her text accordingly.

**Comment by jenniferisasi** [comment]
Creo que he arreglado los problemas con mis enlaces y la visualización de las tablas (que no salían), y he realizado los cambios sugeridos por Joseba ya que eran pequeños.

**Comment by arojascastro** [comment]
Aquí mi lectura. Por favor, lee todos los comentarios antes de empezar a corregir porque son interdependientes. 

Lo que más me preocupa es la traducción (o no) al español de las variables y la nota 2, que debe corregirse. El resto muy bien. Gracias.

- 2: en recursos históricos incluyendo, sin estar limitado a ellos, test estadísticos. --> en recursos históricos que incluyen tests estadísticos, entre otros. (el gerundio me suena muy inglés)
- título de sección: ¿Para quién es esto útil? --> ¿Para quién es útil? (calco del inglés: "this")
- 5: Mientras que R es una gran herramienta para datos tabulares, puede que encuentres otros acercamientos al análisis de fuentes no tabulares (como transcripciones de periódicos) más útiles. --> Mientras que R es una gran herramienta para datos tabulares, puede que encuentres más útiles otros acercamientos al análisis de fuentes no tabulares (como transcripciones de periódicos). (Mover el "más útiles" al medio de la frase).
- 7: Cuando abres la consola de R por primera vez, se abre una ventana que se parece a esta: --> Cuando inicies la consola de R por primera vez, se abrirá una ventana parecida a esta: (repetición de "abrir" en la misma frase).
- 10: quizás en este párrafo habría que añadir que la consola de R solo está disponible en inglés (al menos, que yo sepa), más que nada para que el usuario no busque en vano la función cambiar de idoma en Preferencias.
- 11: Esto mostrará una lista de todos los grupos de datos disponibles en una ventana aparte. Esta lista incluye los títulos de todos los grupos de datos además de una pequeña descripción de la información de cada uno. --> Esto mostrará una lista de todos los grupos de datos disponibles en una ventana aparte; la lista incluye los títulos de todos los grupos de datos además de una pequeña descripción de la información de cada uno. (Repetición de "Esto" y "esta" muy seguida).
- 17: pulsa Intro --> pulsa 'Intro' (?) (en varios lugares, falta unificar, porque al principio sí pones el signo de puntuación)
- 19: creo que se debería aclarar que el nombre de las variables puede estar en español o cualquier otro idioma; podemos hacer esto bien traduciendo las variables, bien añadiendo un destacado o nota aclaratoria.
- 36: toma menos tiempo --> ¿es un calco del inglés "to take time"? No sé, yo diría "requiere más tiempo" o "precisa"... pero ya no sé qué es correcto en español dado que el español de Barcelona no es el mismo del español de Estados Unidos... así que como tú veas.
- 46: Ten en cuenta que el ejemplo de más arriba no se adapta bien para bases de datos más grandes - contar los puntos de datos para encontrar los correctos sería muy tedioso.  --> Ten en cuenta que el ejemplo de más arriba no se adapta bien para bases de datos más grandes: contar los puntos de datos para encontrar los correctos sería muy tedioso. (Yo pondría dos puntos en lugar de guion).
- 48: Motor Trend de 1974 [^2].  --> la nota no funciona ¿?
- 155: la Old Bailey online --> la Old Bailey en línea ¿?
- 58: Para hacer esto, creamos las variables Robos y RobosViolentos usando el total de cada década como puntos de datos: --> aquí has traducido las variables pero hasta ahora usabas las variables en inglés... no sé si convendría traducir todas las variables o no; pero me resulta extraño este cambio: si lo quieres mantener, aconsejo añadir una aclaración en este párrafo adviertiendo del cambio.
- 74: Ahora que has practicado con datos simples, estás preparado/a para trabajar con tus propios datos. Estos posiblemente están en una hoja de cálculo. ¿Cómo puedes trabajar con estos datos en R?  --> repetición de "datos" y "estos", me suena repetitivo. Sugerencia: "Ahora que has practicado con datos simples, estás preparado/a para trabajar con los tuyos. Si los tienes en una hoja de cálculo, te preguntarás cómo puedes trabajar con ellos." (O algo parecido)
- 76: Nota que las filas  --> "Ten en cuenta", "Advierte", etc. ("Nota" me parece un calco del inglés).
- 78: read.csv(file=Ófile-name.csvÓ,header=TRUE,sep=Ó,Ó) --> sé que el nombre del archivo está así en el original inglés, pero esas Ó me parecen muy raras... ¿sabes qué significan? ¿seguro que no es una errata del original?
- 87: la nota 2 tiene un error de Markdown porque no se visualiza bien (no sé cuál es)

Aún nos falta la lectura de @ajspadial.

**Comment by jenniferisasi** [comment]
He hecho los cambios que sugerías @arojascastro. Sobre la Ó, efectivamente, hay un error en el original y lo pasé totalmente por alto. Se trata de las comillas ":  read.csv(file="file-name.csv",header=TRUE,sep=",")  ¿cómo se procede ahora para cambiar el original? 

Creo que ahora la nota 2 funciona. Parece ser cuestión de no dejar espacio entre la palabra que llevará la nota y el corchete.

**Comment by arojascastro** [comment]
Mil gracias. Esperamos la lectura de @ajspadial 

En cuanto al error del original, @jenniferisasi si puedes, haz un *issue* mencionando al editor o a Adam en el repositorio de Jekyll y ellos lo cambiarán.

**Comment by arojascastro** [comment]
Querido @ajspadial ¿puedes confirmarnos que sigues intereado en revisar la traducción? Gracias.

**Comment by arojascastro** [comment]
@ajspadial se compromete a leer y publicar su revisión el 13 de junio.

**Comment by ajspadial** [comment]
No sé si os habéis dado cuenta, pero **me he equivocado** y en lugar de revisar esta lección revisé la de datos textuales con R (https://github.com/programminghistorian/ph-submissions/issues/172#issuecomment-396632782)

Esta semana buscaré un hueco para hacer esta revisión.
![](https://thumbs.gfycat.com/CleverSoftFowl-size_restricted.gif)

**Comment by arojascastro** [comment]
Hehe, no problem! Al final saldremos ganando nosotros con tus dos revisiones :)

**Comment by arojascastro** [comment]
Me gustaría publicar esta lección antes de irme de vacaciones (15 de julio). Gracias.

**Comment by arojascastro** [comment]
Hola, ¿alguna novedad @ajspadial ?

**Comment by arojascastro** [comment]
Hola, me volveré a leer la lección tras los cambios realizados, @jenniferisasi - y si veo que no hay más problemas, publicaremos sin más.

**Comment by jenniferisasi** [comment]
Me parece bien.

**Comment by arojascastro** [comment]
Algunas cositas:

- 31: puedes crear un vector para los datos de AirPassengers de 1949 y llamarlo ‘Air49’: --> no sé si sería mejor marcar las variables como código en Markdown... 
- 48: millas por galón podía viajar un coche --> uhmmm no entiendo qué es un galón... me falta contexto cultural o cultura automovilística... no sé si se podría cambiar un poquito el original para decir algo parecido pero más comprensible para un lector medio (por otra parte, no es un detalle muy importante, lo que decidas). En general, esta lección es muy...  aviones, coches, cilindradas... destila  testosterona. Obviamente, no es culpa tuya.
- 54: 33.9 millas por galón --> me quedo igual (en parte, porque no sé a qué equivale una milla en km). Además, no sé si los decimales deberían separarse por coma: 33,9, 10,4 etc. (hay más casos). En el código va con punto, claro. En el texto no sé si debería ir con coma. Lo que decidas.
- 77: no sé si el significado de la función `getwd` se entiende en inglés: ¿qué significa `wd`? Quizás podrías poner una traducción entre paréntesis.
- Box, G. E. P., Jenkins, G. M. and Reinsel, G. C. (1976) Time Series Analysis, Forecasting and Control. Third Edition. Holden-Day. Series G.  --> falta coma después de fecha?
- Henderson and Velleman (1981), Building multiple regression models interactively. Biometrics, 37, 391Ð411. --> Falta cursiva en los títulos ¿? ¿O no ponemos cursiva nunca? 
- Por último, no sé si conoces artículos o libros o tutoriales sobre R en español que pudieras recomendar y añadir a la bibliografía.

Por lo demás, muy bien, muchas gracias por el trabajo, y disculpa la demora. 

No hace falta que hagas todos los cambios que sugiero: queda a tu criterio, son cosas muy menores, el tutorial podría publicarse sin cambiar nada. Asegúrate de que los enlaces a The Programming Historian sean internos, eso sí. Yo lo revisaré también y actualizaré los metadatos.  

Así que cuando decidas algo, dímelo y pasaremos a publicarlo. Gracias de nuevo.

**Comment by acrymble** [comment]
@jenniferisasi please make sure the minor change from https://github.com/programminghistorian/jekyll/issues/939 is applied to this lesson.

**Comment by jenniferisasi** [comment]
@arojascastro gracias por ver estas cuestiones de contenido! Este fin de semana tengo tiempo y haré la adaptación al sistema métrico en la medida de lo posible (galones a litros y millas a km), etc. También voy a echar un vistazo a lo de las citas y creo que lo de la puntuación en los decimales lo voy a investigar un poco más. 

Lo de la testosterona jaja yo tampoco entiendo de coches pero, por ejemplo, a mi hermana le encantan y sabe todas estas cosillas.  

Thanks @acrymble for reminding me! I will take the changes into account for the final version.

**Comment by jenniferisasi** [comment]
@arojascastro me falta buscar y añadir alguna referencia bibliográficas extra (a ver si encuentro). Quiero también añadir una explicación para la función "write.xlsx" de casi el final - me he dado cuenta que no explica qué hace "sheetName =" y "row.names = TRUE" 

Con esto creo que para hoy a la noche (de EEUU) lo dejo listo.

**Comment by jenniferisasi** [comment]
¿Se entiende la siguiente explicación? 

> write.xlsx(x = OldBailey, file = "OldBailey.xlsx", sheetName = "OldBailey", row.names = TRUE)

En este caso, y dentro del paréntesis de esta [función write.xlsx] (https://www.rdocumentation.org/packages/xlsx/versions/0.6.1/topics/write.xlsx), estamos llamando a procesar la variable “OldBailey” con el argumento  <code class="highlighter-rouge"> x = </code>; a la vez, indicamos que el archivo guardado debe llamarse “OldBailey” con la extensión “.xlsx” mediante el argumento <code class="highlighter-rouge">file =</code>; además, damos el nombre "OldBailey" a la hoja de cálculo (<code class="highlighter-rouge">sheetName= </code> en que estarán los datos y, finalmente, establecemos que sí queremos (TRUE o verdadero) que los nombres de la fila en nuestra variable se guarden en el nuevo archivo. [N. de la T.]

@josebakmoreno @arojascastro @vgayolrs  ¿Qué pensáis?

**Comment by josebakmoreno** [comment]
Hola @jenniferisasi, 

Así de primeras, yo creo que se entiende bien y que los valores están claros.

**Comment by arojascastro** [comment]
Muy bien :)

**Comment by jenniferisasi** [comment]
@arojascastro con tu aprobación de ese último párrafo, entonces, doy por finalizada la edición de la traducción. Hay dos recursos muy buenos en español al final, y pronto tendremos más traducciones de los tutoriales de R aquí en PH. 
Gracias por la revisión y publicación.

**Comment by arojascastro** [comment]
Traducción publicada por fin: https://programminghistorian.org/es/lecciones/datos-tabulares-en-r

¡Por favor, difundid! Muchas gracias todos por colaborar.
