### ISSUE TITLE
Proposed Lesson - 'Creating Mobile Augmented Reality Experiences in Unity'

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/ph-submissions#169]
The Programming Historian has received the following proposal for a lesson on 'Creating Mobile Augmented Reality Experiences in Unity' by @jacobwgreene. This lesson will be a substantial revision of an older lesson, '[Intro to Augmented Reality with Unity](https://programminghistorian.org/lessons/intro-to-augmented-reality-with-unity)'. We've retired that lesson for sustainability reasons, as Unity has substantially changed their interface. This new lesson will aim to take some steps towards reworking that same material into a more sustainable lesson. The conversation about these issues can be found on [this pull request](https://github.com/programminghistorian/jekyll/pull/800) and this [issue](https://github.com/programminghistorian/jekyll/issues/717).

Normally we'd put learning outcomes here, but I'll shift that slightly given this is about revising old material rather than proposing an entirely new lesson. Key revision goals:
     
- improving the lesson's readability by incorporating more detailed steps and numbered lists
- removing screenshots where possible, particularly those that depict version-specific instances of Unity/Vuforia
- looking for any ways that the lesson could be written for more generalized AR development in Unity
 	
In order to promote speedy publication of this important topic, we have agreed to June 1st. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by June 1st, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @walshbr. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1 or @amandavisconti. Once we get the proposal in I will open a new review ticket for the lesson with @alsalin to continue the conversation since she has been instrumental in the conversation about its sustainability.

**Comment by jacobwgreene** [comment]
I have the lesson revisions completed, however, I'm having some trouble pushing my new lesson to the "ph-submissions" repo. I have the latest version of github desktop installed and I just cloned the repo but I keep the getting a filepath error (see screenshot). I assume this is because of a misnamed file somewhere, but I'm not sure where to fix it. Any advice on fixes? 
![capture](https://user-images.githubusercontent.com/9723206/40501872-2c3ee5fa-5f57-11e8-81b3-e9e62654ee00.PNG)

**Comment by walshbr** [comment]
It looks like this file got created somewhere along the line by mistake - https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/%5C

@mdlincoln am I right in thinking that can just be deleted? Looks like that lesson already exists elsewhere under a different filename. It looks like that might be tripping up your desktop app, and if we get rid of that things might clear up.

**Comment by walshbr** [comment]
@jacobwgreene I went ahead and pulled that file from the repo - since it had a filename that wouldn't resolve in the URL and was added by an author I can't imagine it was there on purpose. Take a swing at committing your code now and see if the GitHub app will work?

@mdlincoln let me know if this file was meant to be there in the lessons repo - https://github.com/programminghistorian/ph-submissions/commit/7ec3e953a865f0eb938b4bd6491f14c9fba6e08b#diff-cb21e427d2a4a11cc407361aaf672c5a. Can always toss it back in, since that is what git is for.

**Comment by jacobwgreene** [comment]
Thanks for your @walshbr. It looks like the commit went through.

**Comment by walshbr** [comment]
Thanks @jacobwgreene - I'll try to take a look at this ASAP, give some thoughts, and assemble some reviewers.

**Comment by amsichani** [comment]
I will have also a look on this in the next couple of hours/days, if that helps!

**Comment by walshbr** [comment]
Thanks @amsichani - would be great if you're up for reviewing. I'll close out this ticket and open a review ticket where the review conversation can take place. Will ping you there.

**Comment by walshbr** [comment]
Closed and continued in #175
