### ISSUE TITLE
Ticket the revisión de traducción: "Análisis de corpus con Antconc" 

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#170]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Análisis de corpus con Antconc* de la lección *[Corpus Analysis with Antconc](https://programminghistorian.org/lessons/corpus-analysis-with-antconc)* por parte de @cmvaronc y @arojascastro . Esta traducción se encuentra en estos momentos en fase de revisión por @jenniferisasi . Puede leerse en:

### Texto 

http://programminghistorian.github.io/ph-submissions/es/traducciones/analisis-de-corpus-con-antconc

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

**Política contra el acoso**

> El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Algunas sugerencias previas:

- 4: i. e. --> es decir
- 6: sofware --> programa
- 6: quizás se podría añadir una nota o un destacado aclarando que la interfaz del programa no está disponible en español.
- 9: e. g.  --> por ejemplo
- 12: i. e. --> puedes traducirlo como quieras
- 13: ¿alguna referencia bibliográfica en español? ¿Sabes si esos títulos han sido traducidos? ¿Puedes añadir alguna nota al respecto?
- 22 y 23: “movie reviews from ntlk”, “Negative reviews” y “Positive reviews”: me parece ok dejar el nombre en inglés, pero se podría añadir la traducción al lado, al menos la primera vez que aparecen esas expresiones
- 32: e. g. --> conviene traducir
- 84 y ss.: ¿conoces recursos similares en español o bien artículos que utilicen AntConc? Si es así, podrías añadirlos aquí.

Una duda: entiendo que no quieres cambiar o modificar ninguna imagen, ¿verdad?

Por favor, @cmvaronc introduce los cambios directamente en este archivo, clicando en el lápiz: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/analisis-de-corpus-con-antconc.md

Para hacer los cambios en nuestro repositorio debes aceptar la invitación de colaboración que te he enviado.

Una vez hayas hecho esos cambios, solicitaré dos revisiones externas. Gracias.

**Comment by cmvaronc** [comment]
@arojascastro , muchas gracias por las observaciones. Creo que ya efectué todos los cambios en el archivo, más algunas adiciones de recursos en español sobre el tema. Creo conveniente dejar las imágenes originales por cuanto corresponden a la versión específica del programa que se sugiere utilizar en el tutorial. Quedo atento.

**Comment by arojascastro** [comment]
Perfecto @cmvaronc - muchas gracias. Empiezo a buscar los revisores, pues.

**Comment by arojascastro** [comment]
@jenniferisasi revisará la traducción en los próximos días.

**Comment by jenniferisasi** [comment]
Tengo muy pocos comentarios sobre el tutorial, está bien traducido. Muchas gracias @cmvaronc por tu trabajo. Los números corresponden a los párrafos: 
- 12: usar un programa sencillo para recuperar archivos —> … para tomar archivos 
- 13: tópico —> tema 
- 17-18: en Concordance se ha omitido el “more on this in a minute” al añadir “KWIC, por sus iniciales en inglés” (En realidad no sé si es necesario añadirlo, pero me parece importante señalarlo) 
- 26: Se nos dificulta rastrear —> es difícil rastrear / nos es difícil rastrear 
- 26: que tal vez no hubiera identificado previamente. —> que tal vez no haya identificado previamente.
- 27: La pestaña en cuestión recibe el nombre de “visor de palabras clave en contexto” (keywords in context viewer). —> Este proceso / Esto recibe el nombre de “visor de palabras clave en contexto” (keywords in context viewer). (quisiera puntualizar esto porque el listado de KWIC es el output/producción en sí mismo, no la pestaña y puede llevar, creo, a confusión). 
- 45: Tarea: compara los resultados de las búsquedas de wom? y m?n. —> wom?n (falta la -n) 
- 57: ¿no te gustaría que hubiere una forma de que el programa te brindara una lista de palabras que aparecen con más frecuencia acompañando la palabra clave buscada? —> ¿no te gustaría que hubiera/tener una forma de que el ordenador te brindara una lista de palabras que aparecen con más frecuencia con la palabra clave buscada?

**Comment by arojascastro** [comment]
Gracias @jenniferisasi por tu revisión.

@cmvaronc puedes introducir los cambios que consideres oportunos. Creo que con esto ya estaríamos listos para publicar, no creo que haga falta otro revisor más.

**Comment by jenniferisasi** [comment]
@arojascastro no me quiero quedar con la duda en esta oración, si deberíamos corregirla o no (llevo días sin tener una conversación completa en español):

- 12: "Para efectos de este tutorial, en lugar de componer el corpus un documento a la vez, vamos a utilizar uno ya existente, compuesto por reseñas cinematográficas tomadas del Natural Language Processing Toolkit (NLTK)" 
Aquí mi duda: al usar el femenino plural en "tomadas" yo entiendo a primera vista (aunque sé que no es así) que las reseñas cinematográficas son del NLTK como si este se tratara de una web tipo Rotten Tomatoes; en realidad, lo que se toma del NLTK es el corpus de reseñas y, por tanto, yo usaría "tomado" 
¿?

**Comment by arojascastro** [comment]
En el original pone:

> Rather than build a corpus one document at a time, we’re going to use a prepared corpus of positive and negative movie reviews, borrowed from the Natural Language Processing Toolkit. The NLTK movie review corpus has 2000 reviews, organized by positive and negative outcomes; today we will be addressing a small subset of them (200 positive, 200 negative).

A mí también me parece un poco raro que el corpus esté tomado del toolkit, pero quizás viene incorporado por defecto como pasa con R, que tiene ya datos cargados. No sé.

¿Qué opinas tú @cmvaronc? 

También me asalta la duda sobre la corrección de "en lugar de componer el corpus un documento a la vez" como traducción de "Rather than build a corpus one document at a time". ¿Qué quiere decir esto? Me parece confuso. Quizás sería mejor: "en lugar de componer el corpus añadiendo documentos" etc.

¿Qué opináis @jenniferisasi y @cmvaronc ? Gracias.

**Comment by jenniferisasi** [comment]
Sí, el corpus efectivamente está disponible en NLTK como los de R. Mi problema es el origen de las reseñas (que no sabemos de donde vienen) que forman un corpus en NLTK, de ahí que yo quiera poner "compuesto por reseñas cinematográficas **(y) tomado** del Natural Language Processing Toolkit (NLTK)" para indicar que es el corpus el que se descarga de NLTK. (Alguien ha seleccionado esas reseñas para crear ese corpus y, como tal, el NLTK no tiene reseñas; no sé si así me explico mejor). 

Por otro lado, la traducción para "one document at a time" podría ser: En lugar de componer el corpus documento por documento - quiere decir que para efectos del tutorial el usuario no tiene que crear su propio corpus descargando archivos de uno en uno porque se usa el de las reseñas, ya compuesto.

@arojascastro se me olvidaba... Concuerdo en que no hacen falta más revisores.

**Comment by arojascastro** [comment]
Vale, ahora te entiendo @jenniferisasi. Me parece bien lo que propones. Si al traductor le parece que mejora el texto, recomiendo hacer el cambio. Todo tuyo @cmvaronc. Avísanos cuando estés satisfecho para que siga con el proceso de publicación.

**Comment by cmvaronc** [comment]
@jenniferisasi , muchas gracias por tus observaciones y comentarios. Atendí a prácticamente todas las sugerencias y me permito comentar solo dos:

17-18: no mantuve en la traducción la expresión “more of this in a minute” porque me pareció que la información a la que se alude está muy cerca, en la sección “Comenzar por una búsqueda básica”. Me sucedió algo parecido con un paréntesis posterior que en original introducía el párrafo anterior a la sección “Operadores de búsqueda”. Allí, la autora escribió “this might be easier to read!” entre paréntesis antes de la primera oración del párrafo; me pareció un fragmento que podría resultar inadecuado para lectores interesados en el análisis de corpus pero no familiarizados con él, y por ello tampoco lo traduje. ¿Lo consideras adecuado?

26: efectué el cambio, pero elegí el adjetivo ‘complicado’ en lugar de ‘difícil’ para no repetirlo en la misma línea (la oración inmediatamente anterior dice “nos resulta difícil…”). Igualmente, en “que tal vez no haya identificado previamente” resolví usar ‘detectado’ para no repetir “ayuda al investigador a identificar patrones que tal vez no haya identificado (…)”

Concuerdo con tu apreciación sobre el fragmento que se encuentra en 12: cometí un error porque hice la concordancia de género y número con ‘reseñas’, con lo cual pasé por alto el hecho de que ese sustantivo es solo parte de una frase nominal más grande, esto es, “el corpus (…) compuesto por reseñas (…) *y* tomad*o* del NLTK…”. Queda así entonces.

En relación con “un documento a la vez”, debo decir que se trata de un vicio de mi parte como hablante del español de Colombia: en este dialecto es común emplear ese préstamo del inglés en alusión a “uno por uno”, pero concuerdo en que es mucho mejor “documento por documento” para efectos de claridad; hecha la modificación.

Quedo atento y de nuevo muchas gracias @jenniferisasi y @arojascastro por el apoyo. Un saludo cordial.

**Comment by arojascastro** [comment]
Quedamos a la espera de la aprobación / respuesta de @jenniferisasi. Gracias @cmvaronc por realizar los cambios con tanta premura y eficencia.

**Comment by jenniferisasi** [comment]
@arojascastro , por mi parte, el tutorial está listo para ser publicado. Gracias @cmvaronc por las explicaciones, la atención al detalle y la prontitud con la que has respondido a nuestros comentarios.

**Comment by arojascastro** [comment]
Lección publicada: https://programminghistorian.org/es/lecciones/analisis-de-corpus-con-antconc

Muchas gracias a los dos. Por favor, difundid por redes sociales :)

**Comment by cmvaronc** [comment]
Muchas gracias nuevamente; voy a compartirla de inmediato. Un saludo cordial.
