### ISSUE TITLE
Ticket de revisión de 'Procesado básico de textos en R'

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#172]
The *Programming Historian en español* ha recibido la propuesta de traducción titulada *Procesado básico de textos en R* basada en la lección [Basic Text Processing in R](https://programminghistorian.org/lessons/basic-text-processing-in-r) por parte de @jenniferisasi  . Esta traducción se encuentra en estos momentos en fase de revisión por @rivaquiroga y  @vgayolrs . Puede leerse en:

### Texto

http://programminghistorian.github.io/ph-submissions/es/traducciones/procesado-basico-de-textos-en-r

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](https://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

### Política contra el acoso

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o José Motilla - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Hola @rivaquiroga, ¿puedes confirmar que te interesa revisar la traducción y darnos una fecha de recepción de tus comentarios? Gracias.

**Comment by rivaquiroga** [comment]
¡Confirmo! El lunes 4 de junio podría tener listos los comentarios.

**Comment by vgayolrs** [comment]
@arojascastro : si me quitas de ombudsperson con gusto la reviso.

**Comment by arojascastro** [comment]
Ok, el segundo revisor será @vgayolrs; ¿nos puedes dar una fecha aproximada? El ombudperson sutituto será @jamotilla

**Comment by vgayolrs** [comment]
Claro que sí, @arojascastro : 8 de junio, si no es que antes.

**Comment by jamotilla** [comment]
@arojascastro de acuerdo, seré el ombudsperson

**Comment by vgayolrs** [comment]
Hola @jenniferisasi y @arojascastro : 

He hecho una primera lectura. En general, no le veo problema a la traducción. Solamente algunos pequeños errores y lo demás son sugerencias para buscar una redacción más fluida.
 
## Sugerencias y correcciones.

§1.l1. "...sustancial cantidad..." | "...cantidad considerable..."
§1.l4-l5. "...independientes ofrecen [...] programación ofrece... | **evitar repetir**
§2.l2 "Discursos del Estado de la Unión de los Estados Unidos" | "discursos del Estado de la Unión del presidente de los Estados Unidos"
§23.l4. "...ordenar en orden descendente." | "...arreglar (clasificar, acomodar) en orden descendente."
§26.l2. "...Las palabras en dicha lista se denominan “stopwords”... | "Las palabras en dicha lista se denominan "palabras vacías"... 
§37.l4. "...permitirá su modificado fácil..." | "...permitirá su fácil modificación..."
§38.l1. "vamos a realizar una segmentación del texto..." |"vamos a segmentar el texto..."
§54.l10. "discursos del Estado de la Unión de los Estados Unidos." | "discursos del Estado de la Unión."
§55.l1. "corpus de Estados de la Unión es cargar todos los discursos en R." | "corpus de discursos sobre el Estado de la Unión es cargarlos todos en R."
§68.l3. "rompío" | "rompió"
§70.l1. "hace un uso extendido de los métodos..." | "utiliza ampliamente los métodos"
§74.l3. "percentil 50..." | "percentil 50º..." (ojo: los percentiles se expresan como ordinales)
§77.l6. "...han cambiado y sido adaptados..." | "...han cambiado y han sido adaptados..." (me parece que, irremediablemente, dicha conjunción de **ser** pide su forma compuesta aunque el auxiliar ya se encuentre presente antes de la conjunción. Para evitar repetir el auxiliar y no dejar coja la conjugación del verbo **ser**, sería mejor buscar otra conjugación o forma, quizá: "han cambiado adaptándose..."
§80.l1. "Las líneas facilitadoras son un gran añadido a los diagramas" | "Las líneas facilitadoras son un gran añadido a los diagramas..."
§81.l3. "...el código interior es mayormente el mismo..." | "...el código interior sigue siendo casi el mismo..."
§83.l2. "...las líneas de las presidencias Bill..." | "...las líneas de las presidencias de Bill..."
§84.l8. "...ataques terrositas del 11..." | "...ataques terroristas del 11..."

## Corrección de código
Detecté un pequeño problema con respecto a las imágenes y me pregunto si es que, en mi ausencia, el código de inserción de imágenes ha cambiado con todas las transformaciones que ha habido en la estructura de los directorios del [repositorio](https://github.com/programminghistorian/jekyll). Si es así, haced caso omiso de lo que sigue. Va.

Los párrafos §64, §68, §76 y §79 de la [traducción](http://programminghistorian.github.io/ph-submissions/es/traducciones/procesado-basico-de-textos-en-r) corresponden a cuatro imágenes. Al ver el [borrador directamente](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/procesado-basico-de-textos-en-r.md), en cada una de las líneas correspondientes (l.470, l.483, l.525 y l.536) los códigos son:
* `![numero-de-palabras](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/procesado-basico-de-textos-en-r/numero-de-palabras.jpg`
* `![numero-de-palabras-y-tipo](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/procesado-basico-de-textos-en-r/numero-de-palabras-y-tipo.jpg`
* `![longitud-de-oraciones](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/procesado-basico-de-textos-en-r/longitud-de-oraciones.jpg`
* `![longitud-de-palabras-linea](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/procesado-basico-de-textos-en-r/longitud-de-oraciones.jpg`.

Me parece que estos deberían tener el siguiente modelo de código `{% include figure.html filename="NOMBRE-DEL-ARCHIVO-DE-IMAGEN" caption="Pie de la ilustración" %}` según la [guía para autores y traductores](https://programminghistorian.org/es/guia-para-autores#escribir-y-dar-formato).

## Dudas sobre normas en general

1. Por lo general, la mayoría de las lecciones no lleva notas a pie de página. Sin embargo, ésta es una de las excepciones. La pregunta es si tendríamos que acordar un estilo para acomodar la llamada a nota a pie respecto a los signos de puntuación. En este caso se lleva según la tradición de llamada antes de signo, en otros [casos](https://programminghistorian.org/es/lecciones/escritura-sostenible-usando-pandoc-y-markdown) se ha optado por llamada después de signo. ¿Lo dejamos a su aire o uniformamos? Esto es más bien para @arojascastro 
2. En esta traducción se han incluido notas a pie de página donde la traductora aclara o enfatiza algunas cosas. Para diferenciarlas de las notas de la lección original sugiero que se incluya la leyenda "nota de la traductora" `[N. de la T.]` como se suele hacer de manera tradicional.

Sería todo por el momento. Quedo atento para aclaraciones y la segunda lectura.

**Comment by jenniferisasi** [comment]
¡Muchas gracias @vgayolrs! He realizado los cambios que has sugerido excepto el del signo para las notas - con lo que decidamos lo edito. Las imágenes, por cierto, no están todavía en la carpeta que corresponden. @arojascastro ¿las pongo ya?

**Comment by arojascastro** [comment]
Gracias @vgayolrs por la revisión y a @jenniferisasi por realizar los cambios.

Me parece bien añadir `[N. de la T.]` a las notas de la traductora para distinguirlas de las del autor. Creo que es un tema que deberíamos discutir. Por ejemplo, en esta lección no había notas del autor y en lugar de añadir eso a cada nota pusimos una sección al final con el epígrafe **Notas de traducción**: https://programminghistorian.org/es/lecciones/analisis-de-corpus-con-antconc

En una traducción mía, en lugar de notas al final, añadí destacados en el cuerpo del texto y puse Nota del traductor... Hay varias formas de intervenir: quizás deberíamos unificarlas.

Quedamos a la espera del cambio, pues, @jenniferisasi y de la revisión de @rivaquiroga. 

Gracias.

**Comment by arojascastro** [comment]
Me olvidé de decir que las imágenes @jenniferisasi puedes subirlas aquí: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images

(en la carpeta correspondiente; si no hay una, se puede crear, o bien ponerlas directamente en ese directorio)

**Comment by rivaquiroga** [comment]
Yo estoy casi lista. Hoy en la tarde de acá (GMT -4:00) o mañana temprano publico mis comentarios.

**Comment by arojascastro** [comment]
Gracias @rivaquiroga, ten en cuenta que Jennifer hizo unos cambios tras la revisión de Víctor...

**Comment by rivaquiroga** [comment]
Sí, estoy actualizando mis comentarios para no repetir lo que ya indicó Víctor

**Comment by rivaquiroga** [comment]
¡Hola!
Muchas gracias por la traducción. Sin duda que va a ser un aporte para el ámbito hispanohablante. 
A continuación dejo algunos comentarios que, en la mayoría de los casos, apuntan a hacer la lectura más fluida. En otros, a detalles del código o a propuesta de cambio por versiones en español más extendidas de ciertos términos técnicos. 

¶3_L5: 
"operativo del The Comprehensive..." > "operativo desde The Comprehensive..."

¶6_L2
"que elijas un sitio espejo del que realizar la descarga" | como es un término técnico, pondría _(mirror)_ después de espejo, ya que lo más probable es que ese cuadro de diálogo aparezca en inglés. 

¶7_L3
"se cargan otros acoplamientos" > "se cargan otras dependencias"

¶11_L1
"hacienco" > "haciendo"

¶12_L2
(análisis léxico) > (segmentar de palabras)

¶15_L1
"¿Cómo ha cambiado la función de R el texto cargado?" > "¿Cómo ha cambiado el texto cargado luego de ejecutar la función tokenize_words?" o "¿Cómo ha cambiado el texto cargado luego de ejecutar esa función de R?"

¶19_L4
Sugiero que la primera vez que se mencione "marco de datos" se ofrezca el original en inglés entre paréntesis (data frame), ya que es probable que quien lea lo haya escuchado antes.

¶21_L2
En el código se utilizó la función `data.frame` en vez de `data_frame`. Como consecuencia, el objeto creado no es una _tibble_ (por eso no sale la dimensión al principio ni el tipo de datos de cada columna)

¶21_L5
Sé que en el original está así, pero el nombre del paquete no es _tidydata_ (no existe un paquete con ese nombre). _Tidy Data_ es el título del artículo que explica el enfoque detrás del conjunto de paquetes que se conoce como "tidyverse" (http://vita.had.co.nz/papers/tidy-data.html). Una opción para resolverlo podría ser: "es una variedad específica de marco de datos creado bajo el enfoque Tidy Data".

¶22_imagen
La imagen que se muestra no es la de una tibble (se creó con `data.frame` en vez de `data_frame`). Como consecuencia, no aparece su dimensión al inicio, que es algo a lo que se alude justo en la línea siguiente. 

¶22_L2
"se imprimen las 10 primeras filas del marco de datos" > "se imprimen las 10 primeras filas del conjunto de datos" (en este caso el original utiliza _dataset_, no _data frame_, por lo que pienso que sería mejor hacer esa distinción).

¶23_L2
"marco de datos" > "conjunto de datos" 

¶25_imagen
Una vez que se convierta en una tibble, habría que cambiar esta imagen también.

¶25_L1
"palabras estructurales" > "palabras de función"

¶41_L5
"proporciene" > "proporcione"

¶54_L7
"cuáles fueron los temas principales que fueron discutidos" > "cuáles fueron los temas principales discutidos en él"

¶54_L8
"de alta escala "> "de gran escala"

¶62_L2
"usando `gplot`" > "usando `qplot`"

¶65_L2
"despúes" > "después"

¶70_L5
"análisis de componente principal" > "análisis de componentes principales" (en español se suele utilizar la forma plural como nombre de este tipo de análisis estadístico)

¶7_L7
"seguimos" > "seguiremos"

¶74_L3
"La función `median`, que encuentra el percentil 50º de sus ingresos" > "La función `median`, que encuentra el percentil 50º de los datos ingresados"

¶74_L4
"es una buena opción para resumir estos puesto que no se verá demasiado" > "es una buena opción para resumirlos, puesto que no se verá demasiado"

¶75_L2
`gplot` > `qplot`

¶86_L1
"procesar un cauce completo de anotación" > "procesar un flujo completo de anotación"

¶86_L2
"partes del discurso" > "categorías gramaticales"

¶86_L4
"filtrar modelos temáticos" > "ajustar modelos temáticos" (en el original es "fitting")

¶86_L8
"a lo largo del tiempo y sobre autores múltiples" > "a lo largo del tiempo o entre múltiples autores" (en el original es "or").

__Duda general__: No sé si sea un tema de variedad dialectal, pero me parece que lo más cercano a _plot_ sería _gráfico_, más que _diagrama_. 


Eso es todo por ahora. Quedo atenta a cualquier duda o consulta.
¡Saludos!

**Comment by vgayolrs** [comment]
@rivaquiroga : sobre tu **duda general**, pensé lo mismo.

**Comment by arojascastro** [comment]
Muchas gracias @rivaquiroga por tus estupendos comentarios. Me parece que son todos razonables, pero queda a discreción de la traductora incorporar los que ella crea necesarios para mejorar el texto. En cuanto a diagrama / gráfico, creo que son casi sinónimos; yo creo que se pueden utilizar ambos términos. Si le parece bien a @jenniferisasi podemos incoporar *diagrama* en algunas partes. Por otro lado, en referencia a ¶21_L5, si créeis que hay un error en el original, se puede enmendar creando un *issue* para que los editores ingleses lo corrijan. 

Cuando la traductora haga los cambios, haré una última lectura y publicaremos la lección lo antes posible. Gracias de nuevo.

**Comment by rivaquiroga** [comment]
Perfecto, crearé un _issue_ para lo que comento en ¶21_L5.

Otra duda general que tuve, pero no la puse porque aún no tengo una propuesta de solución, se relaciona con la traducción de "high-level" como "alto nivel" (en el resumen inicial, ¶2_L1 y 3, ¶54_L3 y ¶84_L3). En español, "alto nivel" tiene una connotación asociada a calidad. En la lección, en cambio, "high-level" se está  refiriendo más bien a que se trata de un tipo de análisis que permite identificar patrones generales/globales, más que aspectos detallados o locales de los textos (como, por ejemplo, sería hacer el etiquetado de categorías gramaticales).
Estoy revisando otros textos sobre el tema para ver si encuentro alguna opción de modificación.

**Comment by arojascastro** [comment]
Genial, por favor, proporciona el enlace al turorial y menciona que el problema ha sido identificado en esta revisión. El issue debe crearse, sin embargo, en otro repositorio diferente: https://github.com/programminghistorian/jekyll/issues

En cuanto a "high level", quizás la expresión puede ser "general" o "abstracto" y para aclarar se podría poner entre paréntesis (*high-level*) en la primera aparición. No sé.

**Comment by rivaquiroga** [comment]
Perfecto, lo haré en ese repositorio e indico que el problema lo identificamos acá.

Sí, esa podría ser una opción. Por ejemplo:
"... utilizar análisis exploratorios para verificar errores y detectar patrones a nivel general (_high-level patterns_)..."

**Comment by jenniferisasi** [comment]
@rivaquiroga ¡muchas gracias por tus comentarios! En particular agradezco las propuestas para cambios en la terminología técnica en español ya que no estoy tan familiarizada con ellos. 

¶21_L2 En cuanto al error en data_frame o data.frame ¡ha sido mío! Lo siento. Haciendo el tutorial con el código en español en RStudio me equivoqué y usé el punto en vez de la barra baja. Es decir, en el original no hay un error.

@arojascastro voy a intentar realizar los cambios durante el fin de semana para, si se puede, publicar la traducción la semana que viene.

**Comment by arojascastro** [comment]
Cool! Gracias a todos :)

**Comment by jenniferisasi** [comment]
@arojascastro ya he hecho los cambios que sugeríais y he subido las imágenes a gh-pages/images/procesado-basico-de-textos-en-r Por favor, mira a ver qué te parecen con la traducción a medias que tienen (he podido cambiar a español el nombre de las variables pero no el nombre de las columnas en el archivo original).

@vgayolrs y @rivaquiroga muchas gracias por revisar mi traducción y sugerir cambios generales que podré utilizar en próximas traducciones.

**Comment by rivaquiroga** [comment]
@jenniferisasi, ¿lo que quieres, por ejemplo, es que diga metadatos$año? ¿O ponerle un nombre a los ejes (por ejemplo "Extensión en palabras")? 
Para lo último se podría agregar una línea de código con la opción `labs` de `ggplot2`, así no hay que alterar los datos originales. 

`qplot(metadatos$year, sapply(palabras, length), color = metadatos$sotu_type) + labs(x = "Año", y = "Extensión en palabras", color = "Modalidad del discurso")`

![labs](https://user-images.githubusercontent.com/31421616/41210128-c10cdf9e-6cfd-11e8-831d-630b539904c4.png)

**Comment by jenniferisasi** [comment]
Hola @rivaquiroga. Para guardar el estilo del original, solo cambié lo posible (medatados$year) y, como ves, aunque pongamos títulos a los ejes, lo original queda en inglés (speech y written). Veo que @arojascastro aprueba tu sugerencia, ¿no hay problema en añadir títulos a los ejes y, con ello, más código? Yo no lo hice porque sería añadir al original pero no tendría problema en ampliar el tutorial para ello. Gracias

**Comment by arojascastro** [comment]
Como prefieras @jenniferisasi - pero no me parece mal dejarlo como está, sin modificar el código.

**Comment by rivaquiroga** [comment]
Claro, es un punto complejo, porque hay elegir entre mantener el original, pero asumiendo que algunas cosas estarán en inglés, o modificar levemente el código para que esté todo en español. 

Para cambiar lo de speech y written habría que modificar el objeto "metadatos"  ¶50. Y ahí el código ya no es solo agregar los nombres de los ejes (que es más comprensible para alguien que no haya ocupado mucho R antes, sino que hay que recodificar la variable (`metadatos <- metadatos %>%     mutate(sotu_type = fct_recode(sotu_type, escrito = "written", oral = "speech")`). 

Como lo que se está haciendo es analizar texto en inglés, tampoco me parece mal que las variables estén todas en inglés. Se entiende que es así por la naturaleza del corpus que se está estudiando.

**Comment by arojascastro** [comment]
¿Se puede poner una aclaración en forma de destacado o nota? @jenniferisasi es tu decisión, haz lo que consideres más coherente con el conjunto y lo que hayas hecho hasta ahora (es decir, lo que te suponga menos modificaciones).

**Comment by jenniferisasi** [comment]
He modificado el código de las cuatro imágenes (así como la captura de pantalla de cada una) pues Riva tiene razón, se leen más fácil (sobre todo en español o alguien que no sepa demasiado de metadatos y/o gráficos). He añadido una nota simple debajo del primer gráfico para indicar cómo se añaden los títulos a los ejes. Creo que ahora está listo.

**Comment by ajspadial** [comment]
El enlace a la lección original en inglés no funciona, a mí me ha funcionado https://programminghistorian.org/en/lessons/basic-text-processing-in-r  
#### Párrafo 1
*"el uso de lenguajes de programación"* creo que es más natural en español ibérico "el uso de un lenguaje de programación"
*"guiamos a los usuarios a través de lo básico"* suena demasiado literal al inglés, sugiero "se introduce a los usuarios en los fundamentos/las bases"
 *"involucra"* también me suena raro, sugiero "Nuestro acercamiento solo requiere el uso ..."
#### Párrafo 7
*biblioteca*. Es bien sabido que biblioteca es la traducción correcta de *library*, pero los *informáticos* venimos utilizando *librería* . La segunda me suena mejor, y facilita el acceso a literatura técnica a los profanos. La propuesta *biblitoeca* será más comprensible a los neófitos con conocimientos de inglés. 
#### Párrafo 23
*"... para la ordenación." Sugerencia "para ordenarlo"
#### Párrafo 37
*" ... para otras direcciones"*, aunque el contexto parece claro a mí me ha liado un poco . Yo añadiría "... direcciones web"
#### Párrafo 39
*".... advierte lo fácil  ..."*. Advierte suena un poco pedante en español ibérico. Sugerencia "Mientras haces esto notarás lo fácil ..."
#### Párrafo 48. 
dividio --> dividido
#### Párrafo 49
En español ibérico, "añadir información contextual al conjunto de datos que estamos ..."
#### Párrafos 78, 79, 80
Línea facilitadora suena raro en español ibérico. Creo que en estadística lo llaman *tendencia* y eso quedaría más claro, creo. "... añadir una línea de tendencia ..." etc.
#### Párrafo 86
Creo que en español ibérico traducimo NLP en singular genérico, procesamiento del lenguaje natural


*"...; esto es uno ...". Me suena mejor "este es uno ..."

**Comment by ajspadial** [comment]
Estos comentarios los he hecho antes de leer los vuestros, para así intentar hacer una revisión neutral.

La traducción **me ha gustado mucho**, y solo he apuntado algunas traducciones que a mí me suenan raras (pero casi siempre se entienden), como lector de español ibérico, pero puede que para otros lectores no se trate de expresiones extrañas.

Entre hoy y mañana voy a hacer yo el tutorial, aunque imagino que en eso no va a haber ningún problema porque ya estará bastante revisado.

Un saludo.

**Comment by ajspadial** [comment]
He ejecutado el código correctamente en RStudio v1.0.44 para Windows 10, con R v3.3.2

No he encontrado ninguna dificultad, salvo el tiempo que ha tardado en instalar `tidyverse`. No sé si es algo que me ocurre sólo a mí. Sugerencia: dar una advertencia al lector.

Por otro lado, dejo un comentario sobre el uso de inglés y/o español en el código:

En el código del párrafo 20 se crea una tabla con las columnas `palabra` y `recuento`. Más adelante, entre el párrafo 39 y el 40, se repite la operación pero se opta por llamar a las columnas `word` y `count`. Entiendo que eso ocurre para facilitar el `inner_join` que viene a continuación.
Sin embargo aquí ocurre lo siguiente. Como lector hispanohablante, hasta ese punto voy distinguiendo lo que es R de lo que es el tutorial porque está en castellano o en inglés. Y en ese punto aparecen `word` y `count` y alguien puede pensar que sea obligatorio usar esas palabras.
Se me ocurren tres opciones:
1. añadir una explicación o nota en el párrafo 39, explicando que se va a usar el inglés para hacer la tabla interoperable con otro conjunto de datos que introducimos más adelante.
2. renombrar las columnas de la tabla `palabras_frecuentes`
```R
palabras_frecuentes <- data_frame(palabra = palabras_frecuentes$word, recuento = palabras_frecuentes$count)`
```
3. añadir una cláusula `by` al `inner_join`, aunque creo que este sería un cambio más importante en la estructura del tutorial
```R
tabla <- inner_join(tabla, palabras_frecuentes, by = "palabra = word")

Mis opciones preferidas serían la 1 y la 2, aunque en ambos casos se requiere una nota o explicación adicional.

**Comment by arojascastro** [comment]
¿Qué opinas @jenniferisasi ?

**Comment by jenniferisasi** [comment]
Gracias @ajspadial por tus comentarios y sugerencias. He editado algunas cosas y, respecto al nombre de las columnas en el párrafo 39, he optado por añadir una nota (tu opción 1) indicando que se dejan en inglés para que sea interoperable con la función iner_join más adelante. Las opciones 2 y 3, aunque más adaptadas al español, supondrían añadir explicaciones de tipo técnico.

**Comment by arojascastro** [comment]
Gracias @jenniferisasi - espero publicar la lección este fin de semana. Gracias a los tres revisores.

**Comment by arojascastro** [comment]
Lección publicada: https://programminghistorian.org/es/lecciones/procesamiento-basico-de-textos-en-r

Gracias a todos. Por favor, difundid en redes sociales y entre amigos y estudiantes/interesados.
