### ISSUE TITLE
Ticket de revisión: "Instalando QGIS 2.0 y añadiendo capas"

### ISSUE THREAD

**Issue by jamotilla** [programminghistorian/ph-submissions#173]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Instalando QGIS 2.0 y añadiendo capas* de la lección *Installing QGIS 2.0 and Adding Layers* por parte de @jamotilla . Esta traducción se encuentra en estos momentos en fase de revisión por   @BrisaMartinezS puede leerse en:

### Texto 

http://programminghistorian.github.io/ph-submissions/es/traducciones/instalando-QGIS

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

**Política contra el acoso**

> El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by vgayolrs** [comment]
@jamotilla y @arojascastro : en el ticket dice que la traducción es de un/a tal "mcorjuela", pero en realidad es de María José. Habría que editar el dato y quitarla de su papel de ombudsperson.

**Comment by arojascastro** [comment]
Gracias @vgayolrs - corregido. 

Estaría bien tener una fecha para la revisión y buscar un segundo revisor.

**Comment by jamotilla** [comment]
Hola @vgayolrs y @arojascastro, creo que no es un error, la traducción la hizo Maria Carolina Orjuela Castillo "mcorjuela" y no María José. Justo ayer conseguí a la segunda revisora. Saludos

**Comment by vgayolrs** [comment]
@jamotilla entonces hay que corregir los metadatos de la traducción a la que lleva el enlace...

**Comment by jamotilla** [comment]
@vgayolrs Ahora mismo lo reviso y hago los cambios

**Comment by vgayolrs** [comment]
@jamotilla perdón por la lata, mi estimado, pero ahora hay que retirar tu nombre y el mío de "translation-reviewer" en los metadatos del YAML...

**Comment by jamotilla** [comment]
Listo @vgayolrs no retiré mi nombre porque también fungiré como revisor.

**Comment by mariajoafana** [comment]
@jairomelo está revisando el tutorial Georeferenciar con QGIS aquí #163 y utilizó QGIS 2.18.16 . En este tutorial de Instalación de QGIS se sugiere QGIS 2.0.1, no estoy segura porqué si en el tutorial original se trabajó con QGIS 2.18.13. Hay que evaluar si actualizamos los tutoriales para trabajr con QGIS 2.18.16 y así mismo sugerir un actualización de los tutoriales de QGIS en inglés para actualizar las versiones. El problema sería si hay muchos cambios en la interface de QGIS entre versiones que requiera hacer nuevas capturas de pantallas y modificar sustancialmente partes del tutorial. Jairo dice que hizo la prueba de reinstalar la versión 2.0.1 "Dufour" para corroborar que las indicaciones fueran correctas, y que en general coinciden tanto en los nombres como en la estructura de la interfaz en Windows. Así que parece que no sería mucho problema.

**Comment by vgayolrs** [comment]
@mariajoafana , parece un error de la traducción. En la [lección original](https://programminghistorian.org/en/lessons/qgis-layers), (actualizada el 16/05/2018), se sugiere la versión 2.18.13, aunque la imagen no está actualizada.

**Comment by BrisaMartinezS** [comment]
En seguida expongo algunas propuestas de cambio en la sintaxis y ortografía del tutorial _Instalando QGIS 2.0 y añadiendo capas_. 
Lo señalado entre comillas es la cita textual de las instrucciones en el tutorial, lo escrito enseguida de dicha cita y sin comillas es la propuesta de cambio.

Número 6. 
“Revisa el contenido de las carpetas. Notarás cuatro archivos con el mismo nombre, pero diferent tipo.”
Cambiar a:
Revisa el contenido de las carpetas, notaras cuatro archivos con el mismo nombre, pero diferente contenido. 

 “Recuerda en que carpeta guardaste las versiones descromprimidas de los shapefiles, ya que deberás encontrarlos desde QCIS muy pronto” 
Cambiar: 
QCIS por QGIS 

“Lo primero que debes hacer es confirgurar el [Sistema de Referencia de Coordenadas][] (CRS) correctamente”
Cambiar a: 
Lo primero que debes hacer es configurar el Sistema de Referencia de Coordenadas (CRS por sus siglas en inglés). 

Página 12: 
“Bajo el menu Proyecto, selleciona Guardar Proyecto (es apropriado guardar después de cada paso)”
Cambiar a: 
Bajo el menú Proyecto selecciona Guardar Proyecto (es apropiado guardar después de cada paso.

“Ahora estas preparado para desarrollar este tutorial, pero es posible que tengas dudas con respeto a que CRS utilizar en tus proyectos personales. WGS84 puede funcionar a corto plazo, especialmente si trabajas con escalas amplias, pero es dificil de manejar con precision en mapas locales”.
Cambiar: 
Ahora estás 
dudas con respecto a 
pero es difícil de manejar con precisión  
Construyendo un Mapa Base

Página 13
“Tu proyecto debería empezar con un mapa base, o una selección de información geo-espacial que le permita a tus lectores reconocer características del mundo real en el mapa.”
Cambiar a: 
[…] que les permita a tus lectores reconocer las características […]
“esta tecnología aún está en proceso para plataformas de código abierto como QCIS, asi que este tutorial presentará el proceso de crear un mapa base propio al añadir layers rasterizados y vectoriales”. 

“esta tecnología aún está en proceso para plataformas de código abierto como QGIS, así que en este tutorial se presentará el proceso para crear un mapa base propio al añadir layers rasterizados y vectoriales”. 
“Para quieren quisieran añadir mapas base pre-diseñados a QCIS, puedes intentar instalar el Plugin ‘OpenLayers’ bajo Plugins->Manage e Instalar Plugins. Selecciona “Conseguir Mas” a la izquierda. Haz click en OpenLayers y luego en Instalar plugin. Haz click en Ok y luego en cerrar. Una vez instaltado, encontrarás OpenLayers en la menú de Plugins. Intenta instalar algunos de los diferentes layers de Google y OpenStreetMaps. Al momento de escribir este tutorial, el plugin OpenLayers (v. 1.1.1) puede instalarse en Macs que usan OSX pero no trabaja apropiadamente. Parece trabajar de manera más consistente en Windows 7. De todas maneras, dale un intento, ya que solo mejorará en los meses que vienen. Ten en cuenta, sin embargo, que la proyección de algunos mapas globales no se auto-corrige, asi que las imágenes de satelite pueden no sincronizar apropriadamente con los datos puestos en una CRS diferente”.
Cambiar a: 
Para quienes quieran añadir mapas base prediseñados a QGIS pueden intentarlo al instalar el Plugin […] 
[…] Una vez instalado encontraras OpenLayers en el menú de Plugins […] 
[…] Al momento de escribir este tutorial el plugin OpenLayers (v. 1.1.1) podía instalarse en Macs que usan OSX pero no trabajaba apropiadamente […] 
[…] De todas maneras haz el intento […] 
[…] Sin embargo, ten en cuenta que la proyección de algunos mapas globales no se autocorrige, así que las imágenes de satélite pueden no sincronizarse apropiadamente con los datos puestos en una CRS diferente. 

Abriendo vectores 
“Sin embargo, también es posible aplicar datos históricos a estos lugares geográficos y estudiar como las personas han interactuado y alterado el ambiente físico que los rodea, la población de los pueblos ha cambiado, los ríos han alterado su curso, los lotes han sido dividos y la tierra ha sido plantada con diferentes cultivos”. 
[…] Sin embargo, también es posible aplicar datos históricos a estos lugares geográficos para estudiar cómo las personas han interactuado y alterado el ambiente físico que los rodea. Así también es posible examinar cómo la población ha cambiado, los ríos han alterado su curso, los lotes han sido divididos y la tierra ha sido plantada con diferentes cultivos […] 

“En el Layer de la barra de herramientas, elige Añadir Layer de Vectores (el icono que vez al lado de ‘Añadir Layer de Vectores’ también puede ser seleccionado en la barra de herramientas en la esquina superior izquierda)”
Cambiar a: 
En el recuadro Capa elige Añadir Capa y después haz click en Añadir Capa Vectorial (de manera alternativa el mismo icono que ves al lado de Añadir Capa Vectorial puede ser seleccionado desde la barra de herramientas en la esquina superior izquierda). 

“haz clic derecho en el layer (coastline_polygon) en el menu de Layers y elige Propiedades.\”
“En la ventana resultante, haz clic en Estilo en el panel izquierdo”.
Cambiar a:
Haz click en la capa Coastline_polygon en el menú de Capas y elige Propiedades.
En la ventana resultante, haz click en Simbología en el panel izquierdo.

“Hay un rango de opciones, pero si queremos deshacernos del fondo completamente, hacemos clic en Relleno simple”.
“Luego selecciona ‘‘Sin pincel’ en el menu desplegable de Estilo de relleno. Haz clic en OK”.
Cambiar a: 
Hay un rango de opciones, pero si queremos deshacernos del fondo completamente, hacemos clic en Simple fill, en el campo Estilo de relleno se selecciona “sin relleno”, en seguida se da clic en Aceptar. 

Finalmente considero que si se mantienen las capturas de pantalla del tutorial en inglés es conveniente mantener el nombre de las pestañas en este idioma en la redacción del tutorial en español. Si las capturas de pantalla que se insertaran en el tutorial son del programa en español es necesario adecuar algunas instrucciones con el nombre de los términos en este idioma. Algunas traducciones del nombre de las pestañas no coinciden con el término que se les asignó en español y esto provoca poca claridad en especial en las primeras instrucciones.

**Comment by jamotilla** [comment]
@BrisaMartinezS gracias por tus observaciones, mas tarde subiré las mias para que @mcorjuela pueda incorporarlas a su traducción. Saludos

**Comment by jamotilla** [comment]
Estimados todos, en vista que @mcorjuela  no ha respondido a las observaciones y de acuerdo con los múltiples detalles que presenta la traducción, los cuales ponen en evidencia el uso desmedido de herramientas tales como google translate, considero que se debe asignar la lección a un nuevo revisor. Saludos

**Comment by jamotilla** [comment]
Estimados @mariajoafana y @arojascastro , qué procede en este caso? Cerramos el ticket y buscamos un nuevo traductor?

**Comment by arojascastro** [comment]
Tiene pinta de que lo mejor es asignársela a otro traductor y empezar de nuevo - a menos que consideres que con los cambios ya detectados se podría publicar. A mí me pasó esto una vez, en que el traductor no respondía, y al final hice yo los cambios y la publiqué sin que él intercediera más. Si crees que tú tienes que hacer muchos cambios para mejorarla, para que valga la pena, quizás podrías poner como segundo traductor... es una idea. Si no, cierra aquí, borra el archivo y asegúrate de que está en la lista de traducciones pendientes. Es una pena.

**Comment by jamotilla** [comment]
Muchas gracias @arojascastro, creo que yo mismo haré los cambios sugeridos por @BrisaMartinezS para publicar la lección a la brevedad. Saludos

**Comment by mariajoafana** [comment]
Hola @jamotilla pasaba por acá para preguntar cuándo crees que puedas hacer la revisión. También podemos solciitarle a alguno de los nuevos miembros del equipo ¿qué opinas?

**Comment by mariajoafana** [comment]
Hola @jamotilla, tenemos este tutorial represado desde hace meses. ¿Te parece si les pedimos a  @rivaquiroga o @JoshuaGOB que se encarguen de la traducción?

**Comment by jamotilla** [comment]
Hola @mariajoafana disculpa por responder tan tarde. Sería genial si @rivaquiroga o @JoshuaGOB pueden involucrarse en la traducción.

**Comment by jamotilla** [comment]
Estimados @mariajoafana @rivaquiroga y @JoshuaGOB si les parece ahora mismo me hago cargo de la traducción y en un par de dias les pido si alguno de ustedes puede apoyar con la revisión. Saludos

**Comment by rivaquiroga** [comment]
¡Hola! Sí, yo puedo apoyar con la revisión. Creo que estoy en muchas cosas ahora mismo como para comprometerme con la traducción.

**Comment by JoshuaGOB** [comment]
Saludos. Ahora mismo tampoco puedo comprometerme a la traducción pero pueden contar conmigo para la revisión.

**Comment by jamotilla** [comment]
Estimados, estoy trabajando en la traducción de la lección y me he encontrado con la dificultad de que la versión actual (3.8) es muy diferente a la 2.0 que trabaja el tutorial. Si bien en otros espacios se ha comentado sobre la pertinencia de mantener la traducción de las versiones antiguas de los programas, creo que en este caso nos encotramos a una dificultad mayor, ya que por ejemplo las instrucciones de instalación, algunos aspectos de la interfaz, entre otros, son muy distintos, así que más que una traducción "literal", esta lección necesitaría una adaptación. Qué opinan @mariajoafana @rivaquiroga @JoshuaGOB ?

**Comment by jenniferisasi** [comment]
Antes de decidir nada sobre la traducción creo que habría que dar aviso al equipo en inglés para ver si la propia lección original ha quedado obsoleta, sobre todo por que la versión 2.0 creo que no está en el historial de la web de descargas http://www.kyngchaos.com/category/software/ (normalmente cambiaríamos el link al nuevo lugar de 2.0 y ya, pero no está)

**Comment by JoshuaGOB** [comment]
Hola. Yo no tuve problemas encontrando los archivos originales para hacer la lección como está. De ahí a que logre instalar todo es otra cuestión. Especialmente considerando que para OS X, el tope de 2.0 es 10.9. Entonces tendríamos que verificar, tanto en Windows como en OS X, cuales sistemas serían compatibles y me parece que esto no vale la pena a no ser que la lección original todavía sea bastante popular.

**Comment by mariajoafana** [comment]
Voy a abrir un ticket en Jekyll para discutir esto con todo el equipo

**Comment by jenniferisasi** [comment]
> Voy a abrir un ticket en Jekyll para discutir esto con todo el equipo

Se está hablando más o menos en el [Issue 1400](https://github.com/programminghistorian/jekyll/issues/1400) ya.

**Comment by mariajoafana** [comment]
Desde el punto de vista técnico Matt fue enfático en sugerir utilizar la versión 2.0 en vez de intentar hacer la traducción y adaptarlo a otra versión.

**Comment by mariajoafana** [comment]
Si no hay problema encontrando los archivos originales sugiero que prosigamos con la traducción

**Comment by mariajoafana** [comment]
Pasaba por acá para ver si desempolvamos este tutorial. Estos de QGIS han sido un gran reto, ¿cómo lo ven @jamotilla y @JoshuaGOB  ?

**Comment by rivaquiroga** [comment]
@jamotilla, ¿finalmente vas a querer traducir esta lección? ¿O mejor cerramos el ticket? No fue una lección que elegiste tú, sino que decidiste asumirla luego de los problemas detectados en la traducción propuesta. Así que si prefieres no seguir con ella, podemos cerrar el ticket.

**Comment by jamotilla** [comment]
Hola @rivaquiroga y @mariajoafana  he estado revisando el tema y creo que es posible no solo traducirla sino actualizarla, creo que eso implicaría prácticamente escribir un nuevo tutorial basado en el texto original en inglés no?  Me encantaría encargarme de eso, te parece?

**Comment by rivaquiroga** [comment]
@jamotilla, si son tantos los cambios que quisieras proponer, entonces quizás convendría escribir una nueva lección distinta, con otro caso de estudio y usando la versión actualizada de la herramienta. Es decir, o es una traducción de esta lección adaptada al público hispanoablante, o es una lección original distinta. Pero algo intermedio puede hacer medio confuso el tema de la autoría. ¿Te animas a proponer una lección nueva?

**Comment by jamotilla** [comment]
Si @rivaquiroga me animo! Creo que lo mejor es trabajar con la nueva lección, además de que urge un tutorial de esta herramienta. Me pondré a trabajar de inmediato en la propuesta

**Comment by rivaquiroga** [comment]
Perfecto. Cerraré este ticket, entonces. ¡Quedamos atentos a tu propuesta, @jamotilla!
