### ISSUE TITLE
Missing line of code - Stylometric Lesson

### ISSUE THREAD

**Issue by rrkelley1225** [programminghistorian/ph-submissions#177]
Thanks for the tutorial. I think there is a line of code missing in the Burrows' Delta Method section on the website. The following code fails because the features list is never created:

# The main data structure
feature_freqs = {}

for author in authors:
    # A dictionary for each candidate's features
    feature_freqs[author] = {} 
    
    # A helper value containing the number of tokens in the author's subcorpus
    overall = len(federalist_by_author_tokens[author])
    
    # Calculate each feature's presence in the subcorpus
    for feature in features:
        presence = federalist_by_author_tokens[author].count(feature)
        feature_freqs[author][feature] = presence / overall

To fix, I had to add: **features = [f[0] for f in whole_corpus_freq_dist]**
Rob

**Comment by acrymble** [comment]
@fdlaramee can you confirm this?

**Comment by fdlaramee** [comment]
@acrymble Indeed there is a line missing, right before feature_freqs = {}

The missing line is: features = [word for word,freq in whole_corpus_freq_dist]
(The one your correspondent has written performs the same work but isn't as clear to the reader, I think.)

Thanks,
FDL

**Comment by acrymble** [comment]
I've put a pull request in to correct this as per the suggestion.

https://github.com/programminghistorian/jekyll/pull/903

Thanks @rrkelley1225 for telling us about the problem.
