### ISSUE TITLE
Ticket de revisión de traducción: Descarga aplicada de archivos con Wget

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#181]
The Programming Historian en español ha recibido la siguiente propuesta de traducción "Descarga aplicada de archivos con Wget" por parte de @leonardobareno . Esta traducción se encuentra en estos momentos en fase de revisión por parte de @vgayolrs . Puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/descarga-archivos-wget
 
Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

Política contra el acoso

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by mariajoafana** [comment]
@leonardobareno disculpa lo lento del proceso, estoy buscando alguien que haga la primera revisión de la traducción, si hay alguien que quieres sugerir me cuentas

**Comment by vgayolrs** [comment]
Hola @mariajoafana , si aún no tienes revisores puedo hacer la primera. Saludos.

**Comment by mdlincoln** [comment]
Please note that the section on Australia is no longer working and we are adding a warning to the English lesson: https://github.com/programminghistorian/jekyll/pull/1048#issuecomment-428951906

**Comment by jenniferisasi** [comment]
Hi! Since this lesson is part of a series, will it also affect [automated-downloading-with-wget](https://programminghistorian.org/en/lessons/automated-downloading-with-wget)? We are editing it on #201

**Comment by vgayolrs** [comment]
@jenniferisasi It does not affect #201  in any way because it works with another website. @mariajoafana , ¿sería posible pedirle a @leonardobareno que incluya el "alert bar" al principio de la lección?

**Comment by jenniferisasi** [comment]
Thanks for the clarification @vgayolrs!

**Comment by mariajoafana** [comment]
@leonardobareno Hubo una actualización en el tutorial original en inglés y hay un mensaje de alerta que hay que añadir. Ya lo añadí (después del título "Segundo ejemplo") y te quiero pedir el favor de traducirlo antes de proceder a la primera revisión del tutorial.

**Comment by leonardobareno** [comment]
Buen día, la traducción solicitada fue efectuada y acabo de actualizar el artículo. Saludos

**Comment by arojascastro** [comment]
¿Necesitáis algún revisor?

**Comment by mariajoafana** [comment]
Hola @arojascastro Si ¿te interesa, o tienes a alguien en mente?

**Comment by arojascastro** [comment]
No sé mucho del tema, quizá @vgayolrs sabe más. En cualquier caso, la podría leer para así acelerar un poco el proceso.

**Comment by vgayolrs** [comment]
Gracias @arojascastro , ya me había ofrecido. Así que comienzo.

**Comment by vgayolrs** [comment]
Por favor, @mariajoafana , ¿podrías checar el enlace a la lección? Hace días pude acceder pero ahora no.

**Comment by mariajoafana** [comment]
Qué raro, no se qué se hizo el tutorial. Ya mismo investigo

**Comment by mariajoafana** [comment]
Ya está accesible. Parece que la última actualización quedó en un "tree" y en ningún "branch"

**Comment by vgayolrs** [comment]
Muchas gracias @mariajoafana , procedo a la revisión. Espero tenerla lista el fin de semana.

**Comment by vgayolrs** [comment]
Hola @mariajoafana , bastante correcta la traducción de @leonardobareno  (gracias), van algunas observaciones (uso la referencia de párrafos en esta [visualización](http://programminghistorian.github.io/ph-submissions/es/traducciones/descarga-archivos-wget) de la traducción, y de líneas en el [archivo](https://github.com/programminghistorian/ph-submissions/blame/gh-pages/es/traducciones/descarga-archivos-wget.md) para una mejor localización).

1) En general, la traducción es bastante clara. Sin embargo, a veces es muy literal respecto al original y falta hacer una corrección de estilo para adaptarla mejor al español, que se lea más natural, por así decirlo. Esto es necesario desde el título mismo de la lección. En "Descarga aplicada de archivos con Wget", "aplicada" no tiene sentido. En inglés "applied" tiene diversos sentidos: put to use, to make a request, to make use of. Incluso, en el título original me parece un poco redundante. Sugiero dejarlo simplemente como "Descarga de archivos con Wget."  

En otros puntos y para la revisión por parte del traductor, sugiero, por ejemplo:

* §2-l.54 "Las páginas web archivísticas..." -> "Las páginas web de archivos..."
* §2-l.55-6 "pero su elevada accesibilidad no siempre se refleja en utilidad incrementada" (se puede decir de manera más clara y sencilla que el que la información esté más accesible no implica que tenga mayor utilidad)
* §2-l.59-60: "la manera en la que el contenido está siendo presentado y organizado..." -> "la manera en la que se presenta y organiza el contenido..."
* §8-l.148: "porción de `00151` fue dejada intacta" -> "porción de `00151` quedó intacta"
* §10-l.163: "*Utilities -> Terminal*" -> "*Utilidades -> Terminal*"
* §10-l.164: "un utilitario de línea de comandos" -> "un intérprete de línea de comandos"
... etcétera (no están puestas todas las frases perfectibles pues considero que con una revisión de estilo a fondo deben arreglarse).

2) Asimismo, hay que tener cuidado con los nombres correctos en español de las declaraciones que forman parte de los lenguajes de programación, por ejemplo, la declaración `for` que en Python es una de las dos funciones de bucle que tiene dicho lenguaje. Por otro lado, hay que tener presente que las funciones y nombres de archivos no deben ir marcadas en cursivas sino marcados como código entre dos signos de acento grave: \`for\` [ver Instrucciones para autores...](https://programminghistorian.org/es/guia-para-autores#escribir-y-dar-formato):

* § -l.80-1 "El primer paso tiene que ver con construir un script para generar URLs secuenciales usando los *bucles For* de Python." -> "El primer paso es escribir un script para generar URls secuenciales usando la función de bucle `for` de Python."

3) Es mejor ofrecer enlaces a páginas en español de los ejemplos que se ponen en el original y, en caso de no existir, incluir una nota de traducción al pie.

* §1-l.49, el vínculo para explicar qué es [curl](chronicle.com/blogs/profhacker/download-a-sequential-range-of-urls-with-curl/41055), podría sustituirse por la explicación en [Wikipedia](https://es.wikipedia.org/wiki/CURL).
* §4-l.102: el vínculo en la lección original dirige a una página de Wikipedia [Leading zero](https://en.wikipedia.org/wiki/Leading_zero) que no tiene traducción directa al español, pero puede sustituirse por la página de Wikipedia dedicada al [cero](https://es.wikipedia.org/wiki/Cero) o explicar la dificultad de computar los ceros a la izquierda en la cadenas numéricas mediante una nota de traducción al pie.

4) Es conveniente traducir los nombres de las variables en los códigos y sus referencias en el texto.

* §4-l.94-5  "En donde dice ‘integer1’ reemplázalo por ‘8029’, y en donde dice ‘integer2’ reemplázalo por ‘8110’" -> "En donde dice ‘entero1’ reemplázalo por ‘8029’, y en donde dice ‘entero2’ reemplázalo por ‘8110’"
* l.114: 
```python
for x in range('integer1', 'integer2'):
```
reemplazar por ->
```Python
for x in range('entero1', 'entero2'):
```
* l.120: "Reemplaza 'integer1' e 'integer2' con los valores..." -> "Reemplaza 'entero1' y 'entero2' con los valores..."

5) Corregir enlaces:

* § -l.184: debe dirigir a la [lección en español](https://programminghistorian.org/es/lecciones/descarga-automatizada-con-wget). 

6) Es muy importante mantener e incentivar el lenguaje inclusivo en traducciones y lecciones originales:

* §8 "que estés interesado en modificar" -> "que te interese modificar" (lenguaje inclusivo)
* §13 "Ahora estás ubicado en el directorio seleccionado y estás listo para empezar la descarga." (modificar a lenguaje inclusivo)

Quedo al pendiente para aclarar cualquier duda.

**Comment by leonardobareno** [comment]
Buen día, acabo de enviar edición con las revisiones sugeridas por Víctor. Algunos ítems que dejo pendientes:
- Numeral 5: No estoy pudiendo realizar la corrección debido a que la traducción todavía no existe (o al menos, que fuera definida la URL en español para dicha traducción, pero sería un condicionamiento indebido hacia quien vaya a abordarla).
- Numeral 3: Dejo pendiente el enlace para referirse a los ceros a la izquierda. La explicación libre que yo colocaría ahí es que según las reglas de Python y de varios otros lenguajes de programación los enteros no se escriben de esa manera con ceros a la izquierda, y que por eso se generaría una situación de error.

Quedo al pendiente de cualquier otra cosa que se requiera. Saludos.

**Comment by mariajoafana** [comment]
Muchas gracias @leonardobareno Estoy buscando un segundo revisor

**Comment by vgayolrs** [comment]
Hola @mariajoafana y @leonardobareno : sobre el numeral 5, la lección ya está traducida:
https://programminghistorian.org/es/lecciones/descarga-automatizada-con-wget
Saludos

**Comment by leonardobareno** [comment]
Subí edición con el enlace actualizado. Saludos
