### ISSUE TITLE
Proposal - Extracting Illustrations from HathiTrust

### ISSUE THREAD

**Issue by alsalin** [programminghistorian/ph-submissions#183]
The Programming Historian has received the following proposal for a lesson on 'Extracting Illustrations from HathiTrust' by @StephenKrewson. The proposed learning outcomes of the lesson are:
     
- Download/update Anaconda installation of Python 3; discuss best practices for environments
- Make a HathiTrust account and save the API keys
- Connect to the API and identify pages with the IMG_ON_PAGE feature for a sample volume (practice Python list and dictionary comprehensions)
- Create a Collection on HathiTrust and download it in JSON format
- Iterate over JSON file and download all candidate pages for a collection
- Discuss ways to visualize and cluster the resulting collection of illustrated page JPEGs
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than August 15, 2018. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by August 15, 2018, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @alsalin. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

**Comment by alsalin** [comment]
Been in touch with @StephenKrewson and the submission should be in shortly.

**Comment by StephenKrewson** [comment]
Yes, my apologies! Did not give a clear enough timeline to @alsalin, thought we were going through email, and missed this proposal. Have changed GitHub notification settings and will have it in by no later than the weekend. Thanks, all.

**Comment by alsalin** [comment]
@StephenKrewson So far things are looking good! I would recommend just a few things as you are finishing up the lesson: 

- Move up the goals and suggested prior experience sections. You have a robust intro and it would be easy to get lost in that before jumping back out to those high level sections. I'm a fan of the following layout: "abstract"-level intro, goals, suggested prior experience, software requirements/dependencies all up front before jumping into the larger text. A good example of this can be found here: https://programminghistorian.org/en/lessons/creating-mobile-augmented-reality-experiences-in-unity
- The above suggestion would require you adding a sw requirements/dependencies section which can be super helpful for sustainability purposes.

Let me know when you've filled out the final sections and I'll close this ticket out and move us over the review ticket. At that point, I'll read through the entire lesson and take it for a test drive and then provide any initial comments to clarify the lesson. After that, we'll invite some peer reviewers to take a look at the lesson. Let me know if you have any questions!

**Comment by StephenKrewson** [comment]
Thank you @alsalin--great suggestions. I'll reorganize things by Thursday (9/14)

**Comment by StephenKrewson** [comment]
@alsalin edits have been made!

**Comment by alsalin** [comment]
@StephenKrewson Looks great! I'll go ahead and close this out and create a review ticket. Once over there I should be able to try out the lesson in the next week or so to give initial feedback.
