### ISSUE TITLE
Ticket de revisión "Fichas de lectura HTML en Zotero"

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#185]
The Programming Historian en español ha recibido la siguiente propuesta de tutorial "Fichas de lectura HTML en Zotero" por parte de @cmvaronc. Este tutorial se encuentra en estos momentos en fase de revisión por parte de @jamotilla y @vgayolrs . Puede leerse en:

## Texto

http://programminghistorian.github.io/ph-submissions/es/lecciones/fichas-lectura-cod-imagenes

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/fichas-lectura-cod-imagenes.md

## Imágenes

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/fichas-zotero

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jamotilla** [comment]
Gracias, comenzaré a la brevedad con el proceso de revisión

**Comment by mariajoafana** [comment]
@jamotilla ¿cuándo creees que puedes hacer la primera ronda de revisión?

**Comment by jamotilla** [comment]
Hola @mariajoafana te parece si envío mis comentarios a más tardar el jueves? 

Saludos

**Comment by mariajoafana** [comment]
Listo, quedo pendiente.

**Comment by mariajoafana** [comment]
@jamotilla Ponemos una nueva fecha para recibir tus comentarios?

**Comment by jamotilla** [comment]
Una disculpa @mariajoafana , mañana mismo envío mis comentarios. Saludos

**Comment by jamotilla** [comment]
Estimada @mariajoafana , estos son mis comentarios:

1, línea 8, “.doc”

3, línea 1,  “estarás en capacidad de" / serás capaz de 

4, línea 3, "cualquiera sea su naturaleza" / cualquiera que sea su naturaleza

4, línea 6, "a lo que se denominaría lectura crítica de las fuentes"/ a lo que se denomina lectura crítica de fuentes

5, línea 1, "En un trabajo previo (Varón Castañeda 2017) nos cuestionábamos respecto "/ nota: no se qué tan pertinente es referir de esta manera a un trabajo previo del autor. Podría ser pertinente si dicho trabajo fuera otro tutorial de programming historian, para que el lector lo pueda encontrar en la misma plataforma. Considero que se puede hacer referencia al trabajo como nota al pie.

17, Es importante señalar que el lector debe de tener instalado el conector zotero en su navegador. También especificar que “impórtalo en Zotero mediante el botón que se encuentra en la esquina superior derecha de la ventana” es el conector de zotero, porque de lo contario no queda claro si se refiere a un botón que el navegador tiene por defecto.

19, ## integración como archivo independiente HTML
1.- “Ahora consigna la información de la referencia que hayas importado a Zotero en los espacios correspondientes del código”/ Es necesario ofrecer mayor información al lector respecto a los “espacios correspondientes”, es decir, se le puede indicar “en los espacios correspondientes (entre los elementos <td></td>, es decir tu información se colocará de la siguiente manera <td> “tu información”</td>) 

19, Falta indicar “figura 8”


28, línea 1, estrategia que encontramos válida / estrategia que consideramos pertinente o de utilidad

**Comment by mariajoafana** [comment]
Muchas gracias @jamotilla Sobre la referencia a un trabajo previo, estoy de acuerdo, no es usual en los tutoriales de PH hacer referencias a manera de citación en el texto. Mi sugerencia, siguiendo lo que se hace en otros tutoriales, es hacer la referencia con un enlace al artículo que se referencia. Algo así: " En un [trabajo previo sobre x, y z](http://jasolutions.com.co/wp-content/uploads/2017/04/GetoresBibliograficos.pdf), ... " y ahí enlazar el artículo

**Comment by mariajoafana** [comment]
@cmvaronc Acá van los comentarios de @jamotilla Todo tuyo para que incorpores las sugerencias y que discutamos algunas si es el caso. Una vez incorporadas las sugerencias asignaremos un segundo revisor.

**Comment by cmvaronc** [comment]
@mariajoafana y @jamotilla, gracias por sus observaciones y comentarios. Voy a hacer las modificaciones lo más pronto posible.

**Comment by cmvaronc** [comment]
@mariajoafana y @jamotilla, ya realicé los ajustes en el documento de acuerdo con las observaciones, a mi juicio muy pertinentes. En el caso de la inserción de la información de las fuentes en la ficha HTML (19), modifiqué un poco la instrucción y, para que esta fuera más explícita y comprensible, juzgué apropiado repetir el código de la tabla, incluyendo la información señalada. Quedo atento, gracias de antemano.

**Comment by mariajoafana** [comment]
Gracias @cmvaronc El segundo revisor del tutorial va a ser @vgayolrs Queda a tu disposición Víctor, cuéntanos en cuánto tiempo puedes tener lista la revisión

**Comment by vgayolrs** [comment]
@mariajoafana , justo estoy comenzando a leer, espero tener evaluación la próxima semana.

**Comment by vgayolrs** [comment]
¡Hola @cmvaronc ! Antes de seguir con una revisión más detallada de tu propuesta, quisiera hacer notar que existen algunos errores de sintaxis en Markdown que hacen que haya un formato de "cuadro de código" en párrafos que no deben tenerlo lo cual impide, por ejemplo, que se generen las dos llamadas a notas al pie. Me parece que el problema es haber puesto los códigos de inserción de imágenes entre códigos de inserción de cuadro de código (\```). ¿Qué opinas?

**Comment by cmvaronc** [comment]
@vgayolrs, muchas gracias por la observación; no había caído en cuenta de ese detalle. Yo creo que podrían eliminarse esas etiquetas de código en las insserciones de imágenes, aunque acudo también en este sentido a la opinión de @mariajoafana: ¿corresponde hacerlo? Quedo atento para proceder, un saludo cordial.

**Comment by vgayolrs** [comment]
Hola @cmvaronc . Si no es ahora, después, porque si no resulta que tu texto no se va a desplegar bien. Míralo tú mismo [aquí](http://programminghistorian.github.io/ph-submissions/es/lecciones/fichas-lectura-cod-imagenes)

**Comment by vgayolrs** [comment]
Hola @cmvaronc ! van mis comentarios.

He leído y seguido con atención los pasos de la lección que propones. Sin embargo, aunque me parece interesante la integración de etiquetas `html` a las notas en Zotero, tengo algunas dudas y observaciones respecto al objetivo general de la lección y otros puntos particulares.

### Observación general

En primer lugar, la información que se despliega mediante la inclusión de la ficha de lectura en una sola nota resulta redundante pues repite información que se puede encontrar en el registro de Zotero por defecto y desplegar como ficha de lectura con los recursos propios de la aplicación. La cosa es conocer más a fondo el [funcionamiento de Zotero](https://www.zotero.org/support/). Asimismo, la obtención e integración de la información para la ficha en `html` implica pasos extra, toda vez que la información que se introduce entre las etiquetas "a mano" se puede obtener de manera automatizada con la aplicación. Es posible crear una ficha de lectura desde Zotero utilizando solamente las notas y la función reporte de la aplicación, seleccionando múltiples ítems del registro en Zotero en los que se incluyan cosas que no están integradas por defecto.

Si consideramos que los tutoriales publicados en PH presentan métodos y herramientas que sirven para hackear recursos y ahorrarnos tiempo con el manejo de datos, la manera en la que está planteado este tutorial va para otro lado. La propuesta de ficha de lectura en `html` implica duplicar (a mano) datos que ya están en la información del registro como "Tipo de ítem", "resumen", las "palabras clave" o los textos relacionados. La referencia bibliográfica –además, con estilos de citación– se puede generar con la propia aplicación y copiar en una nota. Nos quedan entonces dos campos más ("propósito..." y "aportes...") que pueden ser completados en una o dos notas, según se quiera organizar el trabajo. El resultado del reporte sería según se ve en la imagen 01. Tienes, entonces, un archivo `html`que puedes utilizar para insertar en donde quieras. En la imagen 02 he incluido la ficha de lectura que propones en `html` para mostrar la redundancia de información (puedes hacer clic en las imágenes para abrirlas en el navegador).

<img width="442" alt="imagen01" src="https://user-images.githubusercontent.com/17665201/46158745-28085700-c244-11e8-8f5b-46d180aac80f.png">

<img width="249" alt="imagen02" src="https://user-images.githubusercontent.com/17665201/46158767-35254600-c244-11e8-806c-f1acf6d7ed8c.png">

Llegados a este punto considero que sería necesario discutir con tu editora, @mariajoafana  qué es lo que se puede rescatar y reformular para obtener un tutorial que sea realmente una propuesta de hacking. Con mucho gusto quedo en toda la disposición para discutir cualquier posible reorientación de tu propuesta.

### Observaciones particulares

Sigo los números de línea del [original](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/fichas-lectura-cod-imagenes.md)

l.44 = Ojo, Zotero descontinuó el soporte del conector para Safari, actualmente los usuarios de Safari deben utilizar el [Bookmarlet](https://www.zotero.org/downloadbookmarklet)

l. 56 = "esto permitirá que todos los elementos tipográficos (tales como las tildes en español..." | En sentido estricto, un elemento tipográfico es cualquiera de las partes que componen el diseño de una caja tipográfica; aquí te refieres a los caracteres y demás signos diacríticos: "esto permitirá que todos los caracteres, (incluídos los signos diacríticos tales como las tildes en español...". Sería conveniente indicar dónde se verifica en Sublime que el archivo tiene codificación UTF-8 

l.101 = En el código de inserción de la imagen falta poner después de `caption="` el término `Figura 3.`

l.110 a l.124 = Se pierde la serie de los incisos (1, 2, 3, 4) por un problema de sintaxis de Markdown. Se puede arreglar evitando escribir desde el margen `1.`, `2.`, etc. ya que eso le indica a Markdown que haces una lista y, como existe otro elemento entre uno y otro párrafo, interpreta que estás comenzando la lista. 

l.120 = "impórtalo en Zotero" | "impórtalo a Zotero"

l.130 a 175 = "#Integración como archivo independiente... " No le veo mucha utilidad a todo este proceso de insertar datos a mano y luego adjuntar el archivo `html` al registro de Zotero. Si quiero consultarla, no puedo abrirla en Zotero sino que se despliega como una página `html`estática en el navegador que esté usando. Si quiero modificar el archivo no lo puedo abrir desde Zotero (como sí puedo modificar si el etiquetado `html` está dentro de una nota, como explicas adelante). Entonces tengo que descargarlo, abrirlo con un editor de texto y volverlo a cargar. ¡Muy engorroso! ¿es realmente útil?

l.177 a 210 = Es interesante mostrar la manera de insertar etiquetas `html` en el cuerpo de las notas de Zotero. Quizá esto se pueda retomar para pensar en un hack más útil.

l.232 a 234 = No es necesario integrar los datos del autor en el cuerpo de texto del tutorial ya que estos se generan automáticamente una vez insertando los datos en la página correspondiente. De esto se encarga tu editora.

Espero que mis comentarios sean de utilidad. ¡Muchos saludos!

**Comment by mariajoafana** [comment]
@vgayolrs gracias por las observaciones. @cmvaronc Te parece si desempolvamos la discusión para ver si hay opciones para reformular el tutorial. Hay una cuestión interesante de explorar que tiene que ver la posibilidad de añadir apuntes escritos en markdown a Zotero, o inclusive editar en markdown directamente en Zotero. No se si haya documentación al respecto pero creo que vale la pena revisar y "cacharrear"

**Comment by mariajoafana** [comment]
@cmvaronc y @cmvaronc Por el momento voy a cerrar este ticket, pero @cmvaronc en el momento en que quieres revisitar el asunto estaremos pendientes para reabrirlo

**Comment by mariajoafana** [comment]
@rivaquiroga Retomar posible idea de tutorial
