### ISSUE TITLE
Ticket de revisión - Topic Modeling y Mallet

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#191]
The *Programming Historian en español* ha recibido la propuesta de traducción titulada *Topic modeling y Mallet* basada en la lección [Getting Started with Topic Modelling](https://programminghistorian.org/en/lessons/topic-modeling-and-mallet) por parte de @hennyu . 

Esta traducción se encuentra en estos momentos en fase de revisión por @rivaquiroga y @JoshuaOB . Puede leerse en:

### Texto

http://programminghistorian.github.io/ph-submissions/es/traducciones/topic-modeling-y-mallet

### Imágenes

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/topic-modeling-y-mallet

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](https://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

### Política contra el acoso

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o José Motilla - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by JoshuaGOB** [comment]
Estoy empezando con el texto esta semana.

**Comment by arojascastro** [comment]
Muchas gracias @hennyu por la traducción y tu adaptación al español. ¡Felicidades! Aquí van mis comentarios como editor.

## Comentario general

Creo que la traducción es un ejemplo modélico de lo que queremos y buscamos: has añadido bibliografía en español, has usado un corpus de textos en español, has explicado cómo usar una stop list en español, has aclarado el tema de codificación de caracteres. En este sentido, es un trabajo modélico. El estilo y la redacción también me parecen muy adecuados.

Tengo, no obstante, dos pequeñas dudas: no sé si deberíaa añadir cursivas a topic modeling (--> *topic modeling*) y si, quizás, se podría añadir una nota explicando por qué no has traducido la expresión "topic modeling" al español.

Ahora, seguidamente, mis sugerencias de cambio en relación con algunas erratas o expresiones que creo que se pueden mejorar.

## Sugerencias de cambio

- 1: Si no tienes experiencia previa en utilizarla podría ser de ayuda consultar --> Si no tienes experiencia previa en utilizarla, consulta (para hacer la redacción más simple)
- 3: output  --> *output* (añadir cursiva) o cambiar por "resultado" o expresión similar
- 4: remítate --> remítete
- 7: Herramientas --> herramientas (minúscula)
- 8: Modelos de tópicos son una familia  --> Los modelos de tópicos son una familia (añadir artículo?)
- 9: Programas de modelización  --> Los programas de modelización (añadir artículo?)
- 13:  innumberables --> innumerables
- En instrucciones para Windows, punto 1: Va --> Ve
- 17: continua --> continúa
- 23: presione --> presiona
- 24: compruebe --> comprueba
- 27: escoje --> escoge
- 27: cd --> `cd` (creo que se debería resaltar como código)
- 41: Recibes un mensaje de error. Tendrás que volver al directorio principal de MALLET para poder ejecutar los comandos (por ejemplo con cd C:\mallet\).  --> Si recibes un mensaje de error, tendrás que volver al directorio principal de MALLET para poder ejecutar los comandos (por ejemplo con cd C:\mallet\). (redacción más fluida, creo)
- stop words --> *stop words* (añadir cursiva?)
- 44: que escribiste y checar si hay erratas). --> falta o sobra un paréntesis
- 55: en ello --> (eliminar?)
- 57: imprive --> imprime
- 58: Observe --> Observa
- 59: utilize  --> utilice
- 60: dicimos --> decimos
- 70: continuan --> continúan
- 73: Finding scientific topics. Proceedings of the National Academy of Science --> ¿añadir cursiva al título?
- 77: creo que los títulos debieran ir en cursiva

Si te parece bien, @hennyu, haz los cambios que consideres apropiados y avísanos cuando esté listo. 

Creo que es mejor que @rivaquiroga y @JoshuaGOB esperen a leer la versión actualizada, así se evitarán señalar esas erratas. ¿Os parece bien?

**Comment by JoshuaGOB** [comment]
Me parecen bien todos los cambios. Quedo pendiente de @hennyu y @rivaquiroga para volver a mirarlos.

**Comment by hennyu** [comment]
Muchas gracias, @arojascastro, por tus comentarios y sugerencias de cambio! 

Hice todos los cambios y añadí una nota (que ahora es la primera nota) en la que explico porque no he traducido la expresión *topic modeling*, pero sí algunas otras palabras relacionadas al método.

Noté que no funciona poner topic modeling en cursiva en el título y el abstract de la lección (en los metadatos).

**Comment by arojascastro** [comment]
Muchas gracias @hennyu por los cambios. Sí, en el abstract y título la cursiva no funciona... preguntaré si se puede arreglar, no te preocupes.

Queda vuestra lectura @JoshuaGOB  y @rivaquiroga - me gustaría publicar esta lección antes del día 20 de octubre. Gracias.

**Comment by JoshuaGOB** [comment]
Hola @hennyu Gracias por tu trabajo. Me animó mucho verlo tan bien hecho porque la versión en inglés de esta lección fue mi introducción a topic modeling y a Programming Historian. 

Por aquí te dejo algunos de los cambios. Mantuve el formato de @arojascastro para marcar los cambios. Cualquier clarificación que necesites me puedes dejar saber. Principalmente son cambios menores, pero estaría encantado de discutirlos o los más sustanciales (9 o 13, por ejemplo). 

## Sugerencias de cambio

2: apropiado para topic modeling --> apropiada para topic modeling
4: Por favor --> Por favor,
6: Estados Unidos --> de los Estados Unidos
7: procedientes --> procedentes 
8: tópicos de textos --> tópicos de los textos (artículo para más claridad)
9: (por un(a) autor(a)) --> Sobra el primer paréntesis

resulta posible descomponer un texto a canastas probables desde donde las palabras vinieron inicialmente.--> entonces es posible descomponer matemáticamente un texto para poner sus palabras en las canastas más probables a ser aquellas de las que vinieron las palabras por primera vez. 

13: implementarlos que puede ser desconcertante o agobiante para los no iniciados en la materia; no nos detendremos en ellos por ahora. --> implementarlas, lo cual puede ser desconcertante o agobiante para los no iniciados en la materia y por esto no nos detendremos en ellos por ahora.

Todos trabajan casi del mismo modo. MALLET utiliza LDA. --> Todos los algoritmos trabajan casi del mismo modo y Mallet en particular utiliza LDA. 

14: repitidamente --> repetidamente 

16: las componentes necesarias --> los componentes necesarios
a la casilla --> en la casilla

21: experimento --> experimentado

24: y estás --> y estarás 
comando MALLET --> comando de Mallet 
se dice a la computadora de tomar sus instrucciones desde la carpeta bin --> se le especifica a la computadora que tiene que tomar sus instrucciones de la carpeta bin

27: y instala MALLET. --> e instala MALLET.
esa lección --> esta lección

28-29: (La información sobre el punto no es correcta)

31: Ejecutar comandos MALLET --> Ejecutar comandos de MALLET

35: simple es simplemente parte --> simple es 
nombre; sustituye un espacio (por ejemplo, import-dir en vez de import dir), ya que espacios--> nombre y sustituye un espacio (por ejemplo, import-dir en vez de import dir), porque los espacios 

36: llevará a --> producirá 
esté --> está 
los seguiste --> las seguiste

38: y se te muestra una --> para que se muestre la 

46: los directorios te --> los directorios, te

47: Mismo punto que 28-29

48: grandes datos --> datos a gran escala 
muy grandes archivos --> archivos muy grandes
puedes entrar en --> puedes enfrentar

53: tendría que ser posible --> se debe evitar

59: comandos --> comandos:

60: Aquí, decimos a MALLET que creara --> Aquí le decimos a Mallet que cree

62: que se puedan ajustar --> que se pueden ajustar

73: Hay una cantidad --> ¿Hay una cantidad 
está dominada --> están dominados 
para la necesidad de aumentar --> de necesitar aumentar

*Utilizas ordenador 4 veces y computadora 12 veces. A pesar de que no tiene importancia, no sé si quieras mantenerlas todas iguales*

**Comment by rivaquiroga** [comment]
¡Hola! ¿Espero a que @hennyu incorpore los cambios sugeridos por @JoshuaGOB para hacer mi revisión?

**Comment by arojascastro** [comment]
Normalmente, lo ideal es que los/las dos revisores externos lean el mismo texto y luego la traductora haga los cambios, pero quizás, puesto que son erratas en su mayoría, conviene que @hennyu haga los cambios y así tú @rivaquiroga lees un texto más "limpio" y no tienes que señalar las mismas erratas. ¿Os parece bien? En tal caso, @hennyu esperamos las correcciones para que Riva lea por última vez antes de publicar.

**Comment by rivaquiroga** [comment]
Perfecto, quedo atenta a que @hennyu haga los cambios :)

**Comment by hennyu** [comment]
¡Muchas gracias también a ti, @JoshuaGOB por las sugerencias de cambio! Incorporé casi todos directamente. Aquí vienen mis comentarios y preguntas:

8: tópicos de textos --> tópicos de los textos (artículo para más claridad) => yo lo dejaría sin artículo porque todavía no se han determinado los textos con los que se trabaja y se mencionan posibles tipos de textos en las siguientes frases

9: Me parece muy bien tu sugerencia para la reformulación de la frase. Leyendo la frase en su contexto otra vez, creo que queda todavía más claro sin la última parte porque lo de las canastas potenciales ya se explica en la frase anterior:
"Si eso es cierto, entonces es posible descomponer matemáticamente un texto para poner sus palabras en las canastas más probables."

28-29 y 47: ¿Cómo estarían correctos esos ejemplos? ¿Sin el ./? En casa tengo Linux y Windows, pero no tengo ningún Mac. Por eso copié los ejemplos de Mac del original de la lección en inglés. Si no es cierto que se necesita el punto, tal vez se podría cambiar esto en la lección original también.

@rivaquiroga @arojascastro ¿La última revisión ya se puede hacer mientras clarificamos estos últimos puntos?

**Comment by rivaquiroga** [comment]
¡ok! Si quieres puedo revisar que todo el código funcione bien en Mac.

**Comment by arojascastro** [comment]
Sí, creo que ya puedes @rivaquiroga. En cuanto al cambio de 8, estoy de acuerdo con Ulrike: "tópico de textos" me suena bien.

**Comment by hennyu** [comment]
@rivaquiroga esto sería estupendo, gracias!!

**Comment by rivaquiroga** [comment]
¡Hola Ulrike!
Muchas gracias por la traducción y por todo el esfuerzo puesto en que los datos estén también en español. Además, es muy útil la bibliografía adicional en este idioma que agregaste.
A continuación están mis sugerencias, que apuntan principalmente a hacer la redacción más clara cuando es posible, a resolver algunas erratas y a hacer algunas propuestas sobre cómo traducir (o no) ciertos términos.
Quedo atenta a cualquier comentario o consulta.

***

¶1
Si no tienes experiencia previa en utilizarla consulta la lección > Si no tienes experiencia previa utilizándola, consulta la lección

¶2 (y abstract)
y por qué querrás utilizarlo en tus investigaciones > y por qué podrías querer utilizarlo en tus investigaciones
(pienso que correspondería mantener el uso del verbo modal en inglés _might_ como forma de atenuación)

¶2
apropiada para topic modeling > que sirve para realizar este tipo de análisis

¶2
(básicamente, configurar... > (esto es, configurar...)

¶3
"Aplicaremos el modelo de tópicos a algunos archivos de ejemplo". En el original se usa "topic modeller"... ¿modelador de tópicos?

¶3
con el programa > con este programa

¶3
Creo que la opción de poner output en cursiva sugerida por @joshuaGOB es la más apropiada. Output e input son palabras lo suficientemente extendidas como para que estén recogidas en el DRAE, por lo que no veo problema con mantenerlas tal cual. Además, ese es el nombre de los comandos en MALLET, así que resulta más claro mantenerlos en inglés, sobre todo para quienes están utilizando el programa por primera vez.
Con las cursivas se puede enfatizar que es un anglicismo.

¶6
"es un intento de inyectar significado semántico a un vocabulario". Sé que esto tiene que ver con la versión original, pero me parece que es poco claro. Una opción podría ser "es un intento de extraer patrones semánticos a partir del vocabulario de ese texto/corpus"

¶6
Antes de empezar con topic modeling deberías preguntarte si probablemente será o no será útil para tu proyecto > Antes de empezar con topic modeling deberías preguntarte si es o no útil para tu proyecto

¶6
una técnica como ésta > una técnica como esta
(asumo que estamos utilizando la última versión de la Ortografía de la RAE)

¶7
el hecho de que se pueda utilizar no significa que se debería hacerlo > el hecho de que se pueda utilizar no significa que deberías hacerlo

¶9
canastas potenciales de palabras > posibles canastas de palabras

¶9
Si eso es cierto, entonces es posible descomponer matemáticamente un texto para poner sus palabras en las canastas más probables > Si eso es cierto, entonces es posible descomponer matemáticamente un texto en las canastas desde las que con mayor probabilidad provienen las palabras que lo componen.

¶10
las palabras clave que las constituyen > las palabras clave que los constituyen

¶11
a la economía, empleos > a la economía, al empleo / a los empleos
(así todos los elementos de la enumeración tienen artículo)

¶11
hay muchos peligros para los que utilizan topic modeling sin entenderlo completamente > quienes utilizan topic modeling sin entenderlo completamente enfrentan muchos peligros

¶14
modelos de tópicos pero al momento > modelos de tópicos, pero al momento...

¶16
Descomprime MALLET a tu directorio > Descomprime MALLET en tu directorio

¶21
la línea de comandos, conocido también >  la línea de comandos, conocida también

¶21
En la línea de comandos, puedes >  En la línea de comandos puedes

¶24
Sé que en el original está así, pero ¿por qué la numeración de los puntos no es correlativa, sino que 1-2-1-2?. ¿No sería mejor que fuera del 1 al 4?

¶24
Entonces escribe `cd mallet` y estarás en el directorio de MALLET > Luego escribe `cd mallet` y estarás en el directorio de MALLET

¶24
se le especifica a la computadora qe tiene > se le especifica a la computadora que tiene

¶27
para facilitar que sigues esta lección > para seguir esta lección con facilidad

¶27
tu directorio `/User/` pero otro lugar funcionará igualmente > tu directorio `/User/`, aunque otro lugar funcionará igualmente

¶27
Descomprime MALLET a un directorio en tu sistema > Descomprime MALLET en un directorio de tu sistema

¶27
Si descomprimiste MALLET a tu directorio > Si descomprimiste MALLET en tu directorio

¶28/¶29
Lo probé y en Mac funciona con o sin el punto y la barra antes. Por simplicidad, sugiero eliminar esa parte, es decir, solo indicar que lo que cambia es la dirección de las barras.

¶32
no se reconoce como comando interno o externo, programa o archivo por lotes ejecutable > no se reconoce como orden o comando
(probé en Mac, Windows y Linux y el mensaje de error aparece así, más breve)

¶32
olvidamos de decir a la computadora de buscar el comando dentro de MALLET > olvidamos decir a la computadora que buscara el comando dentro de MALLET

¶33
A través de teclear > Al teclear

¶33
Luego hicimos el error con > Luego generamos el error

¶33
conseguimos llamar el archivo de ayuda > conseguimos llamar al archivo de ayuda

¶35
`import-dir` en vez de import dir > `import-dir` en vez de `import dir`
(en el original no está así, pero queda más claro si aparece también como código)

¶36
puede ser porque instalaste > puede deberse a que instalaste

¶37
No sé si es por un tema de variante lingüística, pero al menos en Latinoamérica es más habitual hablar de _texto plano_ que de _texto llano_.

¶37
Normalmente cada texto se guarda en un archivo .txt y el conjunto de esos archivos constituye el corpus > Para ello, cada texto debe guardarse en un archivo .txt. El conjunto de esos archivos conformará el corpus.

¶42
en este caso el texto de un ensayo >  en este caso, el texto de un ensayo

¶42
Los comandos abajo > Los comandos de más abajo

¶42
Si bien la traducción de _stop words_ como "palabras vacías" se suele usar en SEO, no es una traducción que resulte adecuada en todos los contextos ya que la idea de "vacío" es poco precisa o se presta para malos entendidos respecto de lo que son realmente las _stop words_ (palabras de función y de alta frecuencia; no palabras que estén vacías de significado). Como el término _stop words_ está extendido en español y tanto la función como el archivo que se provee tienen también ese nombre, sugiero mantener el término en inglés (en cursiva). Una opción de traducción para ese fragmento, entonces, podría ser la siguiente:

"y eliminan _stop words_ (esto es, palabras de función como _y_, _el_, _la_, _pero_ o _si_, que ocurren en frecuencias tan altas que obstruyen el análisis)."

¶42
En el caso de la versión en español, si uno intenta ejecutar estos comando al llegar a esta parte de la lección recibirá un error, porque aún no se ha descargado la lista de _stop words_. Para evitar eso, se poría indicar explícitamente que no se ejecute todavía y luego al final de la sección indicar que ya está todo listo para ejecutar esos comandos. Otra opción sería mover el código hacia abajo, para que quede después de que uno ha descargado la lista de stop words.

¶53
Ahora se debe evitar el error > Ahora no debería aparecer el error / Ahora deberías poder evitar el error

¶57
La computadora imprime las palabras clave, las palabras que > La computadora imprime las palabras clave, es decir, las palabras que

¶58
Éste y supuestamente algunos otros documentos del corpus contribuyeron > Es de suponer que este y algunos otros documentos del corpus contribuyeron

¶58
elementos aleatorios así que las listas > elementos aleatorios, así que las listas

¶58
revisar coherencia de la construcción temporal en este fragmento: _las listas de palabras clave son diferentes cada vez que el programa se ejecute, incluso cuando se utilice el mismo conjunto de datos._

opción 1. _las listas de palabras clave son diferentes cada vez que el programa se ejecuta, incluso cuando se utiliza el mismo conjunto de datos._
opción 2. _las listas de palabras clave serán diferentes cada vez que el programa se ejecute, incluso cuando se utilice el mismo conjunto de datos._

¶59
archivo de salida > _output_

¶62
que muestra cuales son las palabras > que muestra cuáles son las palabras

¶62
archivos de salida > outputs

¶62
En la salida, > En el output

¶62
así que con 10 tópicos, la lista va desde 0 a 19 > así que con 10 tópicos, la lista va desde 0 a 9

¶66
la salida pudiera haber sido > la salida podría haber sido

¶68
Para mantenerte organizado > Para mantener todo organizado
(así evitamos la marca de género)

¶69
Figure > Figura

¶71
Eliminar el espacio entre la cifra y el símbolo de porcentaje

¶73
probablemente es más rápido recorrer algunas iteraciones > probablemente es más rápido realizar algunas iteraciones

74
puedes crearlos en Notepad, por ejemplo, o en otro procesador de textos > puedes crearlos en un procesador de textos como Notepad, [Sublime Text](https://www.sublimetext.com/) o [Atom](https://atom.io/), por ejemplo

¶74
¿Quiéres explorar > ¿Quieres explorar

¶74
sólo > solo

¶74
puedes utilizar informaciones > puedes agregar información

¶75
Para ver un ejemplo completamente elaborado de topic modeling > Para ver un ejemplo desarrollado de topic modeling

¶83
éstos sólo > estos solo

¶89
Para introducciones a topic modeling escritos en español > Para introducciones a topic modeling escritas en español

¶ ACERCA DE LOS AUTORES
Solo está consignado uno de los autores. Faltan los otros dos.

¶ SUGGESTED CITATION
¿Esa sección del original se agrega después? ¿O es necesario incorporarla ahora?

**Comment by arojascastro** [comment]
Gracias @rivaquiroga. Por favor, @hennyu introduce las sugerencias de cambio que creas que mejoran tu texto. 

En cuanto a la biografía del segundo autor, ya me encargo. Lo mismo con la citación (en realidad, se genera automáticamente).

Por cierto, @hennyu ya puedes añadir cursivas al resumen; ese problema ya ha sido resuelto.

Me gustaría publicar antes de que acabe el mes. 

Gracias a todos.

**Comment by hennyu** [comment]
¡Muchas gracias a @rivaquiroga y todos por mejorar el texto! Estoy lista con los cambios, pero al hacer el comit en GitHub, recibí este mensaje:

The page build failed for the `gh-pages` branch with the following error:

There was a YAML syntax error on line 2 column 8 in `<unknown>`: `found a tab character where an indentation space is expected while scanning a block scalar`. For more information, see https://help.github.com/articles/page-build-failed-invalid-yaml-in-data-file/. 

Me parece que tiene que ver con el proceso de transformación del archivo markdown a HTML, pero no sé si causé el error con los cambios en este archivo https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/topic-modeling-y-mallet.md o si tiene otro origen. Les parece conocido este tipo de error? @arojascastro

**Comment by arojascastro** [comment]
Muchas gracias; me miro el error, no lo habíamos tenido hasta ahora. 

Una pregunta @JoshuaGOB qué nombre quieres que figure como revisor? Cuáles son tus apellidos?

**Comment by JoshuaGOB** [comment]
Hola a todos. Volví a mirar el tutorial y se ve muy bien. Para nombre utilizo Joshua G. Ortiz Baco 
Gracias.

**Comment by arojascastro** [comment]
Muy bien, gracias, a todos.

Una última cosa, @hennyu, veo que la fuente de los textos de José Martí es Wikisource. Genial. Pero podrías descargar el corpus, subirlo a la carpeta de [assets](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets) y enlazar para que se descargue desde ahí? Es para evitar problemas futuros, imagina que desaparece el corpus, etc. Luego me encargo yo de mover todos las imágenes y archivos a Jekyll.

**Comment by hennyu** [comment]
Hola @arojascastro ,
el download del ZIP-file se hacía desde mis páginas en GitHub (porque ya fue una adaptación de los textos fuente en Wikisource). Ahora lo subí a assets y cambié el enlace en el texto de la lección.

**Comment by arojascastro** [comment]
Lección publicada: https://programminghistorian.org/es/lecciones/topic-modeling-y-mallet

Si encontráis algún error, podéis reabrir este ticket y reportar. 

Por favor, difundid la lección en redes sociales o entre conocidos. 

Gracias a todos por el trabajo tan bien hecho.
