### ISSUE TITLE
Ticket de revisión "Creación de corpus paralelo con LF Aligner"

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#197]
The Programming Historian en español ha recibido la siguiente propuesta de tutorial "Creación de corpus paralelo con LF Aligner" por parte de @aluzam. Este tutorial se encuentra en estos momentos en fase de revisión por parte de @arojascastro y @igrodsan. Puede leerse en:

## Texto

http://programminghistorian.github.io/ph-submissions/es/lecciones/corpus-paralelo-lfaligner

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/corpus-paralelo-lfaligner.md

## Imágenes

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/corpus-paralelo-lfaligner

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by mariajoafana** [comment]
Antes de remitir el tutorial a revisión recomiendo añadir lo siguiente:
- Explicar cómo se instala y ejecuta LF Aligner

**Comment by aluzam** [comment]
Añadí instrucciones de instalación, ejecución y uso para Windows y sistemas basados en Linux.

**Comment by mariajoafana** [comment]
Gracias Armando, creo que habría que aclarar que la ejecución y uso de LF Aligner en Mac se hace desde la terminal . Por otro lado, de manera que el lector pueda seguir el paso a paso del tutorial es importante dar acceso a los documentos que estás utilizando. En la carperta [Assets](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets) puedes crear una carpeta del tutorial en la que guardes los documentos .txt que se utilizan en el mismo

**Comment by arojascastro** [comment]
Hola:

He leído el tutorial porque me interesa el tema. En general, me parece interesante; aquí van algunas observaciones con el propósito de mejorar el tutorial:

- software --> programa? programario? no veo la necesidad de mantener el término inglés
- a los titulillos de apartado normalmente no les ponemos dos puntos (consultad otras lecciones ya publicadas)
- ¿el programa funciona en Mac? Si es que sí, deberíamos decirlo y cubrir el proceso en Mac, si es que no, también hace falta decirlo y aclararlo, yo soy usuario de Mac y me interesa saberlo antes de descargarlo
- creo que se abusa de términos técnicos en inglés como *enter*, *next*, *Browse*... y otros. Se puede usar el término inglés, pero no podemos dar por sentado que todo el mundo sabe el significado, de lo contrario, no haría falta traducir lecciones. En general, cuando dejamos un término en inglés ofrecemos la traducción entre paréntesis.
- las instrucciones para Linux están introducidas de manera un poco forzada, sin narrativa, solo diciendo **En Linux**; creo que el estilo de PH es más expositivo / narrativo, no ofrecemos documentación técnica (escueta y seca) sino un tutorial o lección para humanistas (con explicaciones detalladas)
- duda: ¿la interfaz del programa está solo disponible en inglés? Me parece raro siendo un programa de traducción... si solo está en inglés, habría que explicitarlo. Si está disponible en varios idiomas, una instrucción sobre cómo cambiar la lengua de la interfaz sería necesaria (y cambiar todas las capturas de imágenes al español).
- como dice María José, los textos deberían alojarse en nuestro servidor, y por tanto enlazar a nuestra copia; no estaría de más explicar algo sobre el dataset (fecha de publicación, quién publica, etc.); no todo el mundo conoce la Declaración (aunque parezca mentira).
- quizás estaría bien comparar este programa con Omega, que hace algo similar. ¿Qué diferencias hay entre los dos? 

Gracias por escribir el tutorial.

**Comment by mariajoafana** [comment]
Muchas gracias por los comentarios @arojascastro 
@aluzam , déjanos saber cuándo podrás revisar e incorporar las observaciones en el tutorial. Ojalá podamos avanzar en el proceso editorial este mes y publicarlo. Déjanos saber si tienes alguna duda

**Comment by mariajoafana** [comment]
@aluzam ha incorporado los comentarios y subido los documentos del tutorial. He cambiado el nombre de la carpeta donde se encuentran los textos con los que trabaja el tutorial  en[ assets/corpus-paralelo-lfaligner](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/corpus-paralelo-lfaligner)
Estamos buscando un segundo revisor. Alguna idea? @arojascastro @vgayolrs @jamotilla @jenniferisasi @JoshuaGOB  @rivaquiroga

**Comment by mariajoafana** [comment]
¡Bienvenido a The Programming Historian @igrodsan ! Este es el hilo en el que estamos revisando el tutorial de Creación de coprus paralelo con LF Aligner. Puedes echar un vistazo a la [guía para revisores](https://programminghistorian.org/es/guia-para-revisores#lecciones-nuevas) que tenemos y recomiendo que realices la lección como un usuario más.
Puedes dejar aquí tus comentarios indicando el número de párrafo al que te refieres. Y cualquier duda que tengas no dudes en contactar conmigo. ¡Gracias!

**Comment by igrodsan** [comment]
Estimados compañeros: 

Estas son mis sugerencias para corregir.

Párrafo 1. Dice:   "Un corpus paralelo o bitexto consiste en la recopilación de   varias versiones de un texto de partida.". Sugerencia: "Un corpus   paralelo o bitexto consiste en la recopilación de varias versiones   de un texto."

Párrafo 6. Dice: "Como resultado,   obtendrás algo así:". Sugerencia: "Como resultado final del   procesamiento de los textos con LF Aligner obtendrás algo así:"
Párrafo 13. Dice: "y los párrafos   por una cantidad de espacios regular.". Sugerencia: "y los párrafos   por una cantidad de espacios y/o marcas de párrafo regular."
Párrafo 17.2. Dice: "nuestro lector   de documentos pdf". Sugerencia: "nuestro editor de documentos   pdf"
Párrafo 19. Sugerencia:  poner una línea para cada opción: 
t. txt (UTF-8), rtf, doc o docx. 
p. pdf o pdf exportado a txt.      
h. Archivo HTML almacenado en nuestro equipo.      
w. Página web.      
c. Legislación de la UE según número CELEX.      
com. Propuestas de la Comisión Europea.      
epr. Informes del Parlamento Europeo.

Párrafo 38. Dice: "Esta ligera  disimilitud entre las distintas versiones". Sugerencia: "Esta   ligera diferencia entre las distintas versiones"
Párrafo 42. Dice: "Para tomar esta  desición,". Sugerencia: "Para tomar esta decisión,"
Párrafo 47. Dice: "Para este  proyecto utilizaremos la herramienta de LF Alinger". Sugerencia:   "Para este proyecto utilizaremos la herramienta de LF Aligner"
Párrafo 49. Dice: "Lamentablemente,  las versiones de Linux (3.11) y Mac (3.12)". Sugerencia: "Las   versiones de Linux (3.11) y Mac (3.12) "
Párrafo 49. Dice: "editarlo con un  procesador de hojas de cálculo.". Sugerencia: "editarlo en una hoja   de cálculo"
Párrafo 57. Dice: "Parte del texto   que debería de estar en el segmento 11". Sugerencia: "En la columna   de la traducción portuguesa (a la derecha, resaltada), parte del texto que   debería de estar en el segmento 11"
Párrafo 64. Dice: "Gracias a nuestra  gestión,". Sugerencia: "Gracias a nuestra edición,"
Párrafo 75. Dice: "las traducciones  del término son decidoras". Sugerencia: "las traducciones del   término son reveladoras."

También añadiría esta frase: 
"Puedes  descargar un visualizador sencillo de traducciones paralelas gratuito en   http://www.laurenceanthony.net/software/antpconc/"

Felicito a los colegas que elaboraron el tutorial: muy claro y detallado, adecuado para la web de programming historian. Un gusto poder colaborar con ustedes.

**Comment by mariajoafana** [comment]
@igrod

**Comment by mariajoafana** [comment]
Muchas gracias por tus comentarios @igrodsan Le pediremos ahora a @aluzam que revise tus comentarios y haga las revisiones del caso.

**Comment by mariajoafana** [comment]
De terminar pronto, este sería el primer tutorial original en español que se publique en PH!

**Comment by aluzam** [comment]
He terminado de editar el texto. Además de acoger cada una de las observaciones anteriores, he redactado explicaciones más detalladas sobre las instrucciones para Mac y Linux. Esto hace que la lectura sea más fluida y que el texto no se base tanto en la versión de Windows. Muchas gracias a @mariajoafana y a @arojascastro por los comentarios y sugerencias.

Añadí enlaces para los documentos alojados en GitHub (assets); esto permitirá que el lector se familiarice más con los pasos a seguir.

@igrodsan  Muchas gracias por los comentarios y sugerencias. Revisé y rectifiqué varias cosas gracias a ellos. Respecto a la sugerencia del párrafo 17.2., me parece que queda mejor lector de documentos pdf, ya que editor también alude a software más difícil de conseguir como Adobe Acrobat (en oposición a Adobe Acrobat Reader).

**Comment by mariajoafana** [comment]
Excelente! Gracias a todos. Voy a hacer la revisión final del tutorial para asegurarme que no falte nada. Y de ahí la paso al repositorio de Jekyll para su publicación

**Comment by mariajoafana** [comment]
Con mucha alegría les cuento que ya está publicado el tutorial, el primer tutorial original en español que publicamos! Este es en enlace: https://programminghistorian.org/es/lecciones/corpus-paralelo-lfaligner Si surgieran nuevas cosas para arreglar lo haremos ya sobre el tutorial publicado @jenniferisasi podrías por favor publicar la noticia en la cuenta de twitter de PH. Este es el tweet que puse en el excel: ¡Primer tutorial original en español! Aprende crear corpus con traducciones a distintas lenguas, de forma que queden perfectamente alineados para una mejor visualización y consulta. Gracias al autor Armado Luza, participante de #PHBogotá y a los revisores @RojasCastroA @igrodrisan

**Comment by arojascastro** [comment]
Yay! Bravo


De: mariajoafana <notifications@github.com> <notifications@github.com>
Responder: programminghistorian/ph-submissions
<reply@reply.github.com>
<reply@reply.github.com>
Filtrar por fecha: 1 de abril de 2019 at 19:03:50
Para: programminghistorian/ph-submissions
<ph-submissions@noreply.github.com> <ph-submissions@noreply.github.com>
CC: Antonio Rojas Castro <rojas.castro.antonio@gmail.com>
<rojas.castro.antonio@gmail.com>, Mention <mention@noreply.github.com>
<mention@noreply.github.com>
Asunto:  Re: [programminghistorian/ph-submissions] Ticket de revisión
"Creación de corpus paralelo con LF Aligner" (#197)

Con mucha alegría les cuento que ya está publicado el tutorial, el primer
tutorial original en español que publicamos! Este es en enlace:
https://programminghistorian.org/es/lecciones/corpus-paralelo-lfaligner Si
surgieran nuevas cosas para arreglar lo haremos ya sobre el tutorial
publicado @jenniferisasi <https://github.com/jenniferisasi> podrías por
favor publicar la noticia en la cuenta de twitter de PH. Este es el tweet
que puse en el excel: ¡Primer tutorial original en español! Aprende crear
corpus con traducciones a distintas lenguas, de forma que queden
perfectamente alineados para una mejor visualización y consulta. Gracias al
autor Armado Luza, participante de #PHBogotá y a los revisores
@RojasCastroA @igrodrisan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/programminghistorian/ph-submissions/issues/197#issuecomment-478662166>,
or mute the thread
