### ISSUE TITLE
Ticket de revisión de traducción Administración de datos en R

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/ph-submissions#199]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Administración de datos en R* de la lección [Data Wrangling and Management in R](https://programminghistorian.org/en/lessons/data_wrangling_and_management_in_R) por parte de @jenniferisasi . Esta traducción se encuentra en estos momentos en fase de revisión. Yo haré una primera evaluación mientras que @rivaquiroga empezará la revisión externa a partir del 2018-10-25 (¡muchas gracias!). Eventualmente yo podría solicitar una tercera revisión. 

La traducción puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/administracion-de-datos-en-R

### Texto
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/traducciones/administracion-de-datos-en-R.md

### Imágenes
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/administracion-de-datos-en-R

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros *ombudpersons*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudspersons* [María José Afanador-Llach o Víctor Gayol](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jenniferisasi** [comment]
@vgayolrs ya puse las 4 imágenes en una carpeta nueva. Hice un new branch con pull request pero creo que eso no subió las imágenes así que las arrastré y committed again.

**Comment by vgayolrs** [comment]
@jenniferisasi : en general, es una excelente traducción que además aporta notas para su comprensión en el ámbito hispanohablante. ¡Felicidades!
Por el momento detecté solamente un error de concordancia:
línea 46 (§4): "cada variables" -> "cada variable"
Por otro lado, hay algunos problemas de sintaxis de MD que hacen que no se implementen algunas funciones como llamadas a pie de página o hipervínculos.
Si te parece, como editor los puedo resolver a menos que quieras agregar o modificar algo después de la revisión de @rivaquiroga , que esperamos ansiosamente pues ella está más comprometida con el uso de R que yo.
Saludos y muchas gracias por la traducción!!!!!

**Comment by jenniferisasi** [comment]
¡Gracias @vgayolrs! Como es poco lo que dices que hay que arreglar, espero a los comentarios de @rivaquiroga y de ahí hago todos los cambios de una, ¿qué te parece?

**Comment by vgayolrs** [comment]
@rivaquiroga , ¿has comenzado la revisión de esta traducción?

**Comment by rivaquiroga** [comment]
¡Hola! Sí, estoy en eso. Calculo que a mediados de la próxima semana tendré lista la revisión.
¡Saludos!

**Comment by arojascastro** [comment]
Hola, ¿queréis que me lea esta traducción? Lleva desde octubre en barbecho...

**Comment by vgayolrs** [comment]
@rivaquiroga , ¿tendrás tu revisión sobre esta traducción? 
De todas maneras, @arojascastro, te agradecería que le eches un ojo para ya destrabar este pendiente.

**Comment by rivaquiroga** [comment]
¡Hola! Me he demorado más de lo esperado, principalmente porque hay algunos términos que faltaba acordar en la traducción "oficial" al español que estamos haciendo del libro "R for Data Science" [acá](https://github.com/cienciadedatos/descripcion-y-orientaciones),  y pienso que es una buena idea que esta traducción también esté alineada con esa. 
Esta semana estoy un poco complicada de tiempo, pero para la próxima podría tener la revisión lista.

**Comment by rivaquiroga** [comment]
¡Hola Jennifer!
Muchas gracias por la traducción. Está muy buena y  será de mucha utilidad para quienes quieren aprender a utilizar R para el análisis de datos.
Antes de entrar a las sugerencias específicas, quisiera señalar que muchas de ellas derivan de la traducción colaborativa del libro "R for Data Science" (R4DS) de Hadley Wickham y Garrett Grolemund que hemos estado haciendo con un grupo de usuarios de R de distintos países hispanohablantes. Específicamente, hemos discutido y acordado [cómo traducir ciertos términos técnicos](https://github.com/cienciadedatos/descripcion-y-orientaciones/blob/master/orientaciones-traduccion.md) asociados al trabajo con R, y definido qué términos no traduciremos porque su uso ya está extendido en inglés. 


__comentarios generales__

_tidy data_

La traducción "datos ordenados" está más extendida.
Una de las razones para no traducirlos como "limpios" es que esa filosofía de tidy data es una de las posibles formas de ordenar los datos. Otras (por ejemplo, una matriz), no implica datos "sucios", sino solo que tienen una organización distinta.

_línea de operaciones_

En el proyecto de traducción de "R for Data Science" decidimos finalmente no traducir el nombre del operador `%>%` ("pipe"). La traducción en español ("tubería") nos sigue pareciendo un poco extraña.
La dificultad que podría surgir con utilizar "línea de operaciones", es que ese no es el único operador que existe en R. En la traducción de R4DS nos referimos a `%>%` como "el operador _pipe_", o "el operador `%>%`.

__comentarios locales__

¶2 punto 2
En otros tutoriales los nombres de los paquetes se han puesto en formato de código: `dplyr`. Quizás se podría aplicar eso acá, aunque no esté en el original. 

¶2  punto 4
Para evitar la repetición de "manipulación", una opción podría ser:
"aprenderás a manipular datos para sentar las bases de un análisis exploratorio a través de unos ejemplos básicos de manipulación de datos" > "aprenderás las bases del análisis exploratorio de datos a través de algunos ejemplos básicos de manipulación de datos"

¶5
"en que un conjunto de datos puede volverse complicado" > "en que un conjunto de datos puede estar "desordenado""

¶5
"hay variables múltiples en una columna" > "hay múltiples variables en una columna"

¶7 (y más adelante también)
"de tidyverse" > "del tidyverse" 

¶8
"operador de ejecución frontal"
En este caso, el sentido de "forward" está asociado a la idea de que el operador `%>%` funciona hacia adelante (toma un conjunto de datos y lo hace pasar por el "ducto" de funciones que aparecen más adelante). Como no se da mayor explicación sobre esto en el original, quizás se podría dejar así: 
"the forward pipe operator" > "el operador `%>%`"

¶8
"una matriz rectangular de datos" > "datos rectangulares"
(mejor no utilizar _matriz_ porque también podría ser un _data frame_)

¶8
En el proyecto de traducción de R4DS decidimos no traducir _data frame_. La principal razón es que existen funciones en R para generar ese tipo de formato que tienen ese nombre (por ejemplo, `as_data_frame()`) y es el nombre que aparece cuando se imprimen en la consola. Así que es importante conocerlo en inglés. 

Mi sugerencia sería:
"nos permite reconceptualizar los marcos de datos" > "nos permite reconceptualizar el formato _data frame_ (marco o tabla de datos)"

¶9
"la versión más reciente de R y la plataforma R Studio correspondientes a tu sistema" > "la versión más reciente de R y de la plataforma R Studio correspondientes a tu sistema operativo"

¶20
Entre el [] y el () quedó un espacio, por lo que no se genera el enlace en Markdown

¶32
Sugeriría no utilizar "modelar" como traducción de "shape", porque es la traducción que se suele usar para "modelling", que implica un proceso distinto. Podría ser "formatear" o "moldear".

¶33
"solamente necesitamos un conjunto pequeño de herramientas para explorar nuestro conjunto" > "solamente necesitamos un conjunto pequeño de herramientas para explorarlo"

¶33
La traducción que suele utilizarse para "base R" es "R Base".

¶33
"resumir (summarise - con ortografía británica)"

Sé que en el original dice que es solo ortografía británica, pero `dplyr` acepta ambas ortografías (o sea, `summarise` y `summarize`)


¶41
Faltó traducir la última línea: "We will use it to calculate the average year that colleges before 1848 were founded." 

¶43
¡Excelente la nota de la traductora para explicar lo que hace el código! Será de mucha utilidad para quienes utilicen la lección :)

¶50
"chuleta" > esta expresión es más propia del español peninsular (en muchas partes de Latinoamérica se utiliza solo para el pedazo de carne). Sugiero mantener la noción más neutra de "Hoja de referencia" que se usa en otras _cheatsheets_ en español que ha publicado RStudio.


Nuevamente, felicitaciones por la traducción y muchas gracias :rocket:

**Comment by vgayolrs** [comment]
muchas gracias @rivaquiroga por tu minuciosa revisión y propuestas. @jenniferisasi , queda en tus manos.

**Comment by jenniferisasi** [comment]
Gracias @rivaquiroga. Veo que la mayoría de indicaciones tienen que ver con el vocabulario técnico que, como siempre comentamos, es algo complicado de adaptar. Revisaré los términos que habéis acordado utilizar en la traducción oficial de *R4DS* y haré los cambios pertinentes (y los memorizaré, de paso). 

@vgayolrs realizaré los cambios en algún momento durante esta semana.

**Comment by vgayolrs** [comment]
@jenniferisasi , solamente habrá que preguntarle a @arojascastro si inició una revisión como ofreció en enero 16 para saber si hay que esperar sus comentarios o puedes proceder.

**Comment by arojascastro** [comment]
No, aún no empecé. Si queréis me espero a que @jenniferisasi haga los cambios. Lemme know.

**Comment by jenniferisasi** [comment]
Hola a todos. He hecho ya los cambios sugeridos por @rivaquiroga. Creo que lo único que habrá que comprobar es si al publicarlo las notas están bien enlazadas porque es algo que 99.9% de las veces no me funciona.

**Comment by vgayolrs** [comment]
¡Muchas gracias @jenniferisasi ! @arojascastro , ¿le darías una última revisada antes de proceder a la publicación o vamos directo? La traducción tiene dos revisiones hechas.

**Comment by arojascastro** [comment]
Por mí, podéis tirar adelante; solo me ofrecí en caso de que Riva no pudiera, seguro que ha quedado genial :)

**Comment by vgayolrs** [comment]
Perfecto @arojascastro . Procedo.

**Comment by vgayolrs** [comment]
Hola @jenniferisasi , estoy un poco oxidado con el proceso de traslado de la traducción para publicación en jekyll , perdón por la demora. Espero este fin de semana poder hacerlo y cerrar el ticket.

**Comment by vgayolrs** [comment]
Hola @jenniferisasi , fíjate que me hace falta el archivo de valores separados por comas `ejemplo_introductorio_estados.csv`. ¿Podrías indicarme dónde los incluiste o, en su defecto, incluirlo? Mil gracias.

**Comment by vgayolrs** [comment]
Reabro porque aun no no se publica la lección. Hace falta un archivo `.csv` Gracias.

**Comment by vgayolrs** [comment]
¡Traducción publicada! Puede verse ya en el sitio:
https://programminghistorian.org/es/lecciones/administracion-de-datos-en-r
¡¡¡Muchas gracias a @jenniferisasi por la traducción, a @rivaquiroga por la meticulosa revisión y a @arojascastro por el interés y paciencia!!!
Ahora, a difundir la publicación.
