### ISSUE TITLE
markdown: redcarpet vs kramdown

### ISSUE THREAD

**Issue by shawngraham** [programminghistorian/ph-submissions#2]
Hi folks,

I keep getting errors that the build failed, and a cryptic email from github saying that markdown has to be changed to kramdown. I checked your _config.yml per that email, and found:

```
name: Programming Historian
description: Introductory and intermediate programming lessons for humanists
url: http://programminghistorian.github.io/ph-submissions
permalink: :categories/:title
exclude: [deprecated, vendor, Gemfile, Procfile]
safe: true
highlighter: pygments
markdown: redcarpet
```

So I guess that last item needs to be changed to kramdown. I'm not going to touch that! But I'm assuming that once that's changed, the changes I've been making to my lesson to take into account Ian's feedback will start showing up on the github.io version of the page.

**Comment by ianmilligan1** [comment]
Nah, that isn't it. It's still breaking after trying this. Something's happened w/ your lesson, or something in our repo, since it built last night and stopped building. Can you let me know when you got your first build error, Shawn? Thanks!

**Comment by wcaleb** [comment]
Yes, I've opened an issue about kramdown over on the other repo. Will adjust both repos once I figure out what will happen. 

https://github.com/programminghistorian/jekyll/issues/185

That issue shouldn't be crashing the build though. I'm not at my computer right now but easiest way to tell is to try to run Jekyll locally and see what the error messages say.

**Comment by shawngraham** [comment]
At 9.31 last night, this:

```
The page build completed successfully, but returned the following warning:

You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.
```

At 9.35 this morning, the error:

```
The page build failed with the following error:

Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-build-failures.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

 https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
```

**Comment by ianmilligan1** [comment]
Fixed - there was a minor error in `authors.yml` from commit #2a8cc24. I've made a similar oops before, so should have twigged to this error earlier. Fixed and building properly now. @shawngraham all look good on your end?
