### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jacobwgreene** [programminghistorian/ph-submissions#20]
@fredgibbs I think there may have been a build error when I committed my second round of revisions. Possibly due to the addition of the table at the beginning or the .gif files. Let me know if there's anything I should do. Thanks.

-Jake

**Comment by wcaleb** [comment]
@jacobwgreene The problem was with one of your "figure" lines; you had some double quotation marks inside other double quotation marks; replacing one set with single quotes fixes the problem.
