### ISSUE TITLE
Ticket de revisión de traducción: descarga-automatizada-con-wget 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#201]
The Programming Historian en español ha recibido la siguiente propuesta de traducción *Descarga automatizada con Wget* de la lección *Automated Downloading with Wget* por parte de @vgayolrs. Esta traducción se encuentra en estos momentos en fase de revisión por @jenniferisasi y @JoshuaGOB  y puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/descarga-automatizada-con-wget

Texto

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/descarga-automatizada-con-wget.md

Imágenes

[link a la carpeta que contiene las imágenes si han sido adaptadas]

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros ombudpersons.

Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros ombudspersons María José Afanador-Llach o Víctor Gayol.

**Comment by jenniferisasi** [comment]
¡Muchas gracias por la traducción Víctor! He tomado la iniciativa de darle una primera lectura yo misma aprovechando que quiero probar el programa. Sin embargo, primero he hecho solo la lectura del texto. Más adelante pruebo los comandos para asegurarme de que funciona todo. 

Comentarios generales: 
He leído el texto y se ve bien. Está todo bastante claro. ¿Sabes si existe algún manual de wget en español o algo que se le parezca? Para contextualizar un poco más el asunto, ¿crees que podrías usar una página en español como ejemplo en vez de ActiveHistory? Si no, sería bueno poner en una nota de qué se trata dicha página...el tutorial se publicó en 2012 y lo de dar contexto es algo que no se había hablado imagino. Yo suelo usar una [Nota de la T.] cuando introduzco esos añadidos. 

Ahora indico algunos de los errores y sugerencias de estilo: 
p3 dos puntos al final de la oración 
entre p12 y p13: el título: "Instrucciones para OS X" 
p14 requiere > se require 
p15 para descargar > para la descarga o para descargar XCode
p16 escribe xcode > escribe "xcode" (creo que siempre es bueno marcar de alguna forma
p16 Esto puede tomar algunos clics para encontrar la versión correcta para ti > Encontrar la versión correcta para ti puede tomar algunos clics. 
p21 Hombrew > *Homebrew*
p21 ruby > Ruby 
p39 debe usar ... puede haber > debes usar ... puedes haber (para que todo esté en "tú")
p53 -r > ```-r```
p56  Aquì > aquí (la tilde) 
p62 no desea > no deseas 
p62 podríoamos > podríamos 
p65 asegurarse > asegurarte
p67 irá  > hará 
p68 desdetsu > desde tu 
nota 2: reeciente > reciente 

Cuando realices estos cambios pido a un revisor externo otra lectura y creo que podremos publicar esto muy pronto.

**Comment by jenniferisasi** [comment]
Voy haciendo la instalación... no me funcionó el comando 
```ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)" ```
Luego, como he visto que *Homebrew* está en español [yay!] pongamos el cambiemos el link: p19 http://mxcl.github.io/homebrew/ a https://brew.sh/index_es

**Comment by vgayolrs** [comment]
Hola @jenniferisasi , ¡mil gracias por tu primera revisión! Corregidos los [detalles particulares](https://github.com/programminghistorian/ph-submissions/commit/c66ab20eeb5982287e5c06d64486058c740b54f6).

### Sobre los comentarios generales:

> ¿Sabes si existe algún manual de wget en español o algo que se le parezca?

El manual de GNU sobre [wget](https://www.gnu.org/software/wget/) en otros idiomas se puede encontrar en esa misma página seleccionando `set language` en el menú superior. Los demás manuales que conozco en español están enfocados a sistemas operativos concretos (sobre todo Linux) y suelen ser bastante confusos.

> Para contextualizar un poco más el asunto, ¿crees que podrías usar una página en español como ejemplo en vez de ActiveHistory?

No he encontrado una página con archivos organizados de la misma manera que los de [ActiveHistory](http://activehistory.ca/papers/) que utilizó @ianmilligan1 para escribir su tutorial. Y si hubiese, en todo caso, la política de PH-es al principio fue la de respetar la propuesta metodológica original del autor. Un *hack* sobre otra página significaría una adaptación que en sí misma podría ser una lección nueva. Pero, claro, sería bueno poner la nota a pie acerca de lo que contiene ActiveHistory y seguir tu propuesta que me parece excelente.

### Sobre el comando de descarga de Homebrew

En efecto, la sintaxis del comando como está en la lección no funciona.
 
```bash
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

El comando está copiado *ad verbatim*  de la [lección original](https://programminghistorian.org/en/lessons/automated-downloading-with-wget).

Como yo ya lo tenía instalado no hice caso de la sintaxis de líneas de comandos en este caso, pero en realidad debería ser:

```bash
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```
Si te parece, se puede poner una nota a pie de página... pero una de las cosas que me gustan de PH es que te plantea retos (como es a veces la sintaxis de comandos), así que tienes que buscar y completar por tu propia cuenta. Finalmente, si quieres convertirte en *hacker* humanista digital, tendrás que buscar muchos recursos por tu cuenta a partir de estos tutoriales. 

Y sí, ahora cambio el enlace a *Homebrew* en español, pero si te parece mejor en una nota de traducción para no modificar demasiado la idea original.

**Comment by jenniferisasi** [comment]
¡Gracias @vgayolrs!

## Sobre Homebrew
1. El enlace a *Homebrew* es mejor que vaya directamente a español, es decir, sustituir los enlaces (el usuario puede volver a inglés con el menú de idiomas). Es lo que hacemos cuando se trata de una entrada en Wikipedia o documentación en español. 
2. ¿Tienes idea de por qué no funciona el comando original? Si bien es cierto que meterse en usar la terminal, programar, etc. es estar dispuesto a arremangarse para buscar recursos y soluciones por nuestra cuenta, esto ¿puede ser causa de algún *update*? En tal caso habría que actualizar ambas lecciones como tal para que sean funcionales. 

## Comentarios generales: Contextualización 
Sobre el cambio a un repositorio en español, qué pena que no encontremos nada. De todas formas, puesto que este tutorial no reporta unos resultados a una pregunta de investigación, creo que no pasaría nada por poner una web de otra cosa y luego una nota como "el original se realizó con ActiveHistory como ejemplo." Este es al acuerdo al que llegamos sobre el acercamiento a una audiencia global. Por ejemplo, [el tutorial de Topic Modeling](https://github.com/programminghistorian/ph-submissions/issues/191) ha hecho un añadido -muy bueno- a nuestro idioma, con textos de José Martí. Es decir, usar ejemplos que queden más cercanos a nuestros contextos y/o en español.

**Comment by JoshuaGOB** [comment]
Hola @vgayolrs y @jenniferisasi,

Gracias por la traducción. Todas las instrucciones funcionaron y las sugerencias son mínimas. Espero ver esto publicado pronto para compartirlo. 

¡Éxito! 

## Sugerencias 

20 abre tu la ventana --> abre una ventana
29 HTTP debería tener el enlace detrás apuntando a http://ftp.gnu.org/gnu/wget/ 
44 Puede ---> Puedes
67 irá tantas capas --> irá por tantas

**Comment by vgayolrs** [comment]
Muchas gracias por tu revisión @JoshuaGOB !!! Si @jenniferisasi no tiene alguna otra observación, procedo a editar para dejar lista la traducción. Saludos!

**Comment by jenniferisasi** [comment]
¡Gracias @JoshuaGOB por la revisión! Sí por favor, @vgayolrs, procede a hacer estos pequeños cambios y así podemos publicar el tutorial dentro de poco.

**Comment by vgayolrs** [comment]
Listo @jenniferisasi , falta que incluyas a Joshua como revisor de la traducción y a ti como editora y revisora de la traducción en los metadatos.

**Comment by jenniferisasi** [comment]
It was published, but I failed to close the issue.
