### ISSUE TITLE
Proposal: Introduction to MySQL with R using DH Box as a companion to the existing lesson.

### ISSUE THREAD

**Issue by jeffblackadar** [programminghistorian/ph-submissions#202]
This is a proposal for a lesson entitled 'Introduction to MySQL with R using DH Box' by Jeff Blackadar. The proposed learning outcomes of the lesson are the same as Introduction to MySQL with R:

Set up a database in MySQL
Connect to the database
Create a table for data
Store records to the table using SQL and R
Query the table using SQL and R

The new companion lesson would be written specifically for DH Box which has R, RStudio and MySQL installed already. This would allow learners to skip most of the installation steps in the main lesson if they are using DH Box.  This lesson could also be used in a class if it was using DH Box.

The start of a draft is [here](https://github.com/jeffblackadar/getting-started-with-mysql/blob/master/getting-started-with-mysql-using-r-using-dh-box.md).

End of edits - I have left the rest of the template in case it needs to be modified.
--
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than [90 DAYS BY DEFAULT BY LONGER IF AGREED WITH EDITOR]. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by [THE AGREED DATE], the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is [EDITOR USERNAME]. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

---

[**Submission Template**]

The Programming Historian has received the following tutorial on 'Editing Audio with Audacity' by INSERT GITHUB HANDLE OF AUTHOR HERE. This lesson is now under review and can be read at:

http://programminghistorian.github.io/ph-submissions/lessons/LESSON-SLUG-HERE

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by mdlincoln** [comment]
@jeffblackadar while we thank you for your idea, new lesson proposals must follow our author guidelines listed here: https://programminghistorian.org/en/author-guidelines#proposing-a-new-lesson, first going through a preliminary review by our managing editor and the board before advancing to a formal draft that gets posted to this repository.
