### ISSUE TITLE
Ticket de revisión de traducción: descarga de múltiples registros mediante cadenas de consultas

### ISSUE THREAD

**Issue by jamotilla** [programminghistorian/ph-submissions#205]
The Programming Historian en español ha recibido la siguiente propuesta de traducción Descarga de múltiples registros mediante cadenas de consultas de la lección [Downloading Multiple Records Using Query Strings](https://programminghistorian.org/en/lessons/downloading-multiple-records-using-query-strings) por parte de @vgayolrs. Esta traducción se encuentra en estos momentos en fase de revisión por @jamotilla y puede leerse en:

**Texto**

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/descarga-multiples-registros-usando-cadenas-de-consulta.md

**Imágenes**

 https://github.com/programminghistorian/jekyll/tree/gh-pages/images/downloading-multiple-records-using-query-strings

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros ombudpersons.

Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros ombudspersons María José Afanador-Llach o Víctor Gayol.

**Comment by jamotilla** [comment]
Estimado @vgayolrs , comenzaré la revisión a la brevedad y me daré a la tarea de buscar un segundo revisor.

**Comment by jamotilla** [comment]
Estimado @vgayolrs revisé tu lección, me parece que haz hecho un trabajo muy limpio y cuidado. Sólo tengo unas cuantas observaciones:

40/3 "un puñado"/ creo que funciona, no se si valdría la pena considerar otra expresión tal como "unos cuantos". Lo dejo a tu consideración. 
48/7 me parece adecuada la manera de resolver el asunto del "n-word"
58/3 "La investigación histórica prudente" / "prudent historical researchers"/ No lo veo mal, pero sería pertinente considerar "los historiadores prudentes..."
Revisar dicho párrafo, tal vez es más comprensible agregando una coma después de "los cuadros de búsqueda".
Como la función de búsqueda de cada sitio web es diferente [insertar coma] siempre vale la pena...
358 "Tambnién"/ También

Saludos, J A

**Comment by jenniferisasi** [comment]
Hola @vgayolrs, gracias por la traducción y perdón la intromisión. Quería hacer una puntualización respecto a la palabra n-word. Estimo que merece dejarla como tal en inglés con un, si acaso, (palabra-n) y escribir una nota breve al pie explicando su significado/contexto. La traducción propuesta es inadecuada por dos motivos: hay que estar enterado de su existencia como tal para entender el vacío entre la n y la r. Fuera del contexto de los EEUU y pensando en una audiencia global, es muy probable que 1) no comprendan qué quieras decir, 2) pueden no estar enterados de que es una palabra peyorativa (aunque digas infame). Por otro lado, hay un problema de accesibilidad de lectura de pantalla puesto que dice "ene" (silencio) "erre", lo cual imagino puede dificultar su asociación con la palabra completa.

No sé qué te parece mi sugerencia.

**Comment by vgayolrs** [comment]
Muchas gracias @jamotilla y @jenniferisasi por las observaciones. Una pregunta al editor, ¿podemos considerar a Jennifer como segunda revisora o hay que esperar a alguien más para proceder?

**Comment by jamotilla** [comment]
Hola @vgayolrs , si @jenniferisasi lo tiene a bien sería genial.

**Comment by vgayolrs** [comment]
¡Mil gracias! Listas las correcciones @jamotilla . No se si @jenniferisasi tendrá alguna otra observación para seguir con el proceso de publicación de esta traducción.

**Comment by jenniferisasi** [comment]
Hola @vgayolrs. Le dije a @jamotilla que, por desgracia, no tengo ahora el tiempo para realizar una revisión completa de esta traducción - el comentario lo hice porque me llegó el email del [comentario](https://github.com/programminghistorian/ph-submissions/issues/205#issuecomment-466508362). Creo que tenemos alguna traducción publicada con un sólo revisor...

**Comment by jamotilla** [comment]
Estimados a falta de un segundo revisor, ¿les parece prudente si publicamos la traducción de @vgayolrs solo con mis observaciones? Considero que la traducción es muy buena, por lo que no veo mayor problema.

**Comment by jamotilla** [comment]
Estimados @jenniferisasi @mariajoafana @arojascastro @rivaquiroga @JoshuaGOB, a falta de un segundo revisor, ¿les parece prudente si publicamos la traducción de @vgayolrs solo con mis observaciones? Considero que la traducción es muy buena, por lo que no veo mayor problema.

**Comment by arojascastro** [comment]
Hola, dale, es Victor, él sabe y tú sabes, además lleva desde septiembre... así que por mí sí

**Comment by mariajoafana** [comment]
Si, de acuerdo

**Comment by jamotilla** [comment]
Estimado @vgayolrs me dispongo a publicar tu traducción de "descarga de múltiples registros mediante cadenas de consultas", solo que estoy revisando los hipervínculos y algunos tienen problemas. ¿Te gustaría echarles un ojo? Si te parece yo mismo los puedo arreglar. Saludos, J A

**Comment by rivaquiroga** [comment]
¡Hola @jamotilla y @vgayolrs! ¿Cómo van con esta traducción? Estaba casi lista y quedó parada por lo de los hipervínculos. Si necesitan ayuda para resolver eso, avisen.

**Comment by vgayolrs** [comment]
@jamotilla y @rivaquiroga : revisé los hipervínculos y están bien (en teoría). El problema es que la sintaxis corta no funciona bien mientras no esté en jekyll.
Por otro lado, dado que se hizo una actualización a Python 3.x.x en otras lecciones, ésta se debería revisar y actualizar (supongo).

**Comment by jamotilla** [comment]
Gracias @vgayolrs gracias por revisar los vínculos! Respecto a Python, creo que efectivamente valdría la pena actualizarlo. Qué opinas @rivaquiroga ?

**Comment by rivaquiroga** [comment]
Sí, es necesario actualizarlo. Hicimos eso con todas las lecciones de Python, ya que desde el 1 de enero que la versión 2.7 no tiene soporte.

**Comment by vgayolrs** [comment]
Perfecto @rivaquiroga y @jamotilla . Denme unos días para actualizar el código.

**Comment by rivaquiroga** [comment]
¡Hola! ¿Han podido avanzar en esta lección? Ya falta muy poco para que podamos publicarla.

**Comment by vgayolrs** [comment]
Hola @rivaquiroga : espero tener terminada la adaptación del código este fin de semana.

**Comment by vgayolrs** [comment]
Una disculpa por la demora, pero algo no me está funcionando con el código cuando intento probarlo. Encima, se me juntaron dos tesis para leer.

**Comment by jamotilla** [comment]
Quedamos al pendiente @vgayolrs saludos

**Comment by jamotilla** [comment]
Hola @vgayolrs cómo vas con el código? Podemos ayudarte en algo?

**Comment by vgayolrs** [comment]
@jamotilla , en cuanto termine de leer las tesis pendientes regreso al código. Gracias.

**Comment by rivaquiroga** [comment]
¡Hola! ¿Cómo van con esta lección @vgayolrs, @jamotilla? Por lo que veo solo falta chequear que el código esté actualizado a Python 3 para poder publicar. ¿Hay algo en lo que pueda ayudar?

**Comment by vgayolrs** [comment]
En efecto, @rivaquiroga : hice una actualización pero en algún punto no funcionó y tengo que verlo con calma. Voy a ver cómo hago para recuperar los archivos que están en la computadora del trabajo pues seguimos en confinamiento.

**Comment by rivaquiroga** [comment]
Quizás @JoshuaGOB, que estuvo a cargo de actualizar todas las lecciones de Python que estaban traducidas, podría dar una mano. ¿Qué les parece @jamotilla y @vgayolrs?

**Comment by jamotilla** [comment]
Genial! Me parece muy bien! En efecto, tal vez @JoshuaGOB pueda echar una mano

**Comment by JoshuaGOB** [comment]
Hola. Empecé a mirar y también a revisar algunos detalles que surgieron por eso de no dejar para mañana. Paré en la sección "Descargar las entradas individuales de los juicios", linea 423. Me dejan saber si nos podemos turnar el resto:

124 - import urllib.request
141 - respuesta = urllib.request.urlopen(url)
144 - f = open(nombreArchivo + ".html", 'wb')   (Esto se tiene que verificar en Windows porque puede generar un error.)
163-165 - (Esto puede llegar a confundir un poco porque entradas no está definida todavía. Puedes añadir una nota o quitarlo. No me parece que aporta. )
168 - Sin embargo, en casos en que la cantidad de resultados no sean múltiples de 10 tendremos un sobrante. 
(Ahora Python3 no tiene este problema. Puedes borrar la primera oración de 168 y reemplazarla con la que puse arriba. Entonces el código de 171-176)

``` python
entradas = 13
contarPaginas = entradas / 10
print(contarPaginas)
-> 1.3
```
178 - Sabemos que la cantidad de páginas debería ser dos. Una página con las entradas de 1-10 y otra con las entradas de 11-13. Ya que queremos el número entero mayor, podemos redondear el resultado de la división. Para esto podemos utilizar el módulo llamado math.  

``` python
# determina la cantidad de archivos a descargar.
import math
contarPaginas = entradas / 10
contarPaginas = math.ceil(contarPaginas)
```
189 - (inserta entre la primera y la segunda oración) Añade `math` justo después de `import urllib.request` para que importe ambos módulos ( `import urllib.request, math`) 
219 - (Tanto en la versión original como en esta no hay un paso anterior para este cambio. Puede ir algo después de 177)
231 - import urllib.request, math
237 - contarPaginas = math.ceil(contarPaginas) 
238-239 (eliminar)
257 - respuesta = urllib.request.urlopen(url)
260 - f = open(nombreArchivo + ".html", 'wb')   (Esto se tiene que verificar en Windows porque puede generar un error.)
268 - (Me parece que se debe decir explícitamente que se añade 13 como argumento).
302 - `urllib2` -> `urllib.request` y `math` 
308 - urllib.request
358 - Tambnién -> También
358 - Debe verificarse con los cambios sugeridos arriba en una computadora Windows. 
362 - urllib.request
375 - gurda -> guarda
378 - urllib.request, math, os, re
390 - contarPaginas = math.ceil(contarPaginas)
391-392 - (eliminar)
409 - respuesta = urllib.request.urlopen(url)
414 - f = open(nombreArchivo + ".html", 'wb')   (Esto se tiene que verificar en Windows porque puede generar un error.)

**Comment by rivaquiroga** [comment]
@vgayolrs, ¿finalmente podrás terminar la traducción de esta lección? Si no, para cerrar el ticket y abrirlo cuando te sea posible retomar esto.

**Comment by rivaquiroga** [comment]
De acuerdo a lo conversado en la última reunión de proyecto (https://github.com/programminghistorian/jekyll/issues/1729), los tickets sin actividad los cerraremos hasta que haya disponibilidad por parte del equipo para retomar el trabajo. María José se encuentra trabajando en la mejor forma de tener un registro de estos tickets en https://github.com/programminghistorian/jekyll/issues/1857

**Comment by rivaquiroga** [comment]
Estamos en condiciones de reactivar la edición de esta lección, que había sido archivada por inactividad. 
@nivaca asumirá el rol de editor en esta fase final. Hará una última revisión de la traducción, en la que también actualizará el código utilizado en el tutorial (originalmente escrito en Python 2.7). 

- Archivo de la lección: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/descarga-multiples-registros-usando-cadenas-de-consulta.md
- Vista preliminar: https://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/descarga-multiples-registros-usando-cadenas-de-consulta.html
- Imágenes (son las mismas del original): https://github.com/programminghistorian/jekyll/tree/gh-pages/images/downloading-multiple-records-using-query-strings

**Comment by nivaca** [comment]
@rivaquiroga Ya terminé la edición y corrección de la lección. Tuve que cambiar bastantes cosas para adaptar el código correctamente a Python 3.
Ya hice el `push` desde mi computador al repositorio de `ph-submissions`. No sé muy bien cómo proceder ahora. ¿Me puedes contar, por favor?

**Comment by rivaquiroga** [comment]
¡Muchas gracias, @nivaca! :tada:
Una vez que el editor de la lección considera que esta está lista para ser publicada, hace precisamente lo que hiciste: anunciarlo por acá. Lo que sigue ahora son una serie de acciones que me tocan a mí: hacer una última lectura, solicitar el DOI, mover los archivos al repositorio jekyll y abrir el PR para publicar la lección. Cuando el PR esté listo, te agregaré como revisor para que chequees la previsualización y apruebes el PR si te parece que está todo bien. 
La solicitud del DOI puede demorar uno o dos día hábiles, así que probablemente mañaba abra el PR. 
Nuevamente, muchas gracias por tu trabajo!

**Comment by nivaca** [comment]
Gracias por la aclaración, @rivaquiroga! Pensé que habría un proofreading adicional.
Por otro lado, detecté errores en el código de la lección original en inglés. Yo creo que habría que revisarla eventualmente.

**Comment by rivaquiroga** [comment]
Si quieres puedes abrir un issue en el repositorio jekyll indicando los errores. Así Anisa puede encargarse de actualizar esa lección.
Antes de publicar la lección haré una última lectura para ver si no hay algun error de tipeo o alguna corrección de estilo que hacer. Por temas de presupuesto, solo hay copyediting para las lecciones originales.

**Comment by nivaca** [comment]
@rivaquiroga Ah, muy bien, entiendo. Gracias.

**Comment by rivaquiroga** [comment]
¡Hola, @nivaca! No he abierto el PR porque parece que el sitio de Old Bailey Online está en mantención. Así que esperaré a que vuelva a estar en línea para publicar.

**Comment by rivaquiroga** [comment]
¡Hola, @nivaca!
Ya estamos casi listos para publicar. Los pasos que nos quedan son los siguientes:

**1.** Cuando tengas tiempo, dale una mirada al pull request que abrí en el repositorio jekyll: https://github.com/programminghistorian/jekyll/pull/2644
En la parte de los checks encontrarás la opciónn de ver la previsualización del sitio con la lección publicada. La idea es que revises que todo se ve como se espera. Si te parece que está bien, entonces solo tendrías que aprobar el PR.

![preview-netlify](https://user-images.githubusercontent.com/31421616/182164089-befcc4e6-9e3d-4648-8cc5-e4f1a8755b4a.png)

**2.** Una vez que apruebes el pull request y yo le haga merge, tenemos que esperar a que se actualice el sitio y la lección aparezca publicada. En ese momento avisaré a nuestro proveedor de DOIs (la Universidad de Sussex) que está todo listo para que activen el enlace correspondiente (https://doi.org/10.46430/phes0059). 

**3.** Cuando el DOI esté activo, ya es posible agregar la lección a nuestro bot de Twitter. En esta parte de la Guía para Editores están las indicaciones: https://programminghistorian.org/es/guia-editor#6-incorpora-tu-lecci%C3%B3n-en-nuestro-twitter-bot. Si tienes problemas para acceder, me avisas. En el documento encontrarás ejemplos de tuits que se han escrito para promocionar otras lecciones, que pueden servir de inspiración. En general se menciona a las personas: autor, traductor, editor y revisores de la lección, si es que tienen cuenta en Twitter. Si no caben todos, dejamos a los revisores fuera, pero los mencionamos sí o sí en el punto que sigue. El nombre de usuario del autor en esa plataforma es `@adam_crymble`, el del traductor `@Victor_Gayol` y el del revisor `@jamotilla`. Si no usas Twitter y no te acomoda mucho esta tarea, no es problema. En ese caso puedo encargarme yo. 

**4.** Anunciar la nueva lección en Twitter. El bot de Twitter servirá para promocionar la lección en el futuro. El anuncio de publicación de ahora hay que hacerlo manual. Si tienes cuenta en Twitter, deberías tener acceso a través de TweetDeck a la cuenta de Programming Historian (es algo que se hace cuando se incorpora un nuevo miembro al equipo). Si no tienes, entonces este paso lo completo yo.

**5.** ¡Listo! Con el tuit anterior publicado ya podemos agradecer a todas las personas involucradas en el proceso acá y cerrar este issue.

Cualquier duda que tengas, me avisas.

**Comment by nivaca** [comment]
Hola @rivaquiroga Gracias!
Dos preguntas:

- ¿Cómo puedo ver el preview de la lección? El [enlace](https://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/descarga-multiples-registros-usando-cadenas-de-consulta.html) no sirve.
- ¿Cómo apruebo el pull request?

¡Saludos!

**Comment by rivaquiroga** [comment]
Acá está el enlace directo al pull request: https://github.com/programminghistorian/jekyll/pull/2644
El enlace al preview está en el mismo pull request, en los checks que hace GitHub. Es el que puse en la captura de pantalla, el último de todos los checks. De todos modos, el enlace directo es este: https://deploy-preview-2644--ph-preview.netlify.app/

En la misma página del pull request te aparecerá la opción para aprobarlo. En la parte superior deberías ver esto:
![Screenshot from 2022-08-01 11-51-10](https://user-images.githubusercontent.com/31421616/182189467-3349657e-e232-4acf-8c19-cc01cfbef94a.png)

Si haces click en "Add your review" GitHub te mostrará la vista general de los archivos. En la esquina superior derecha aparecerá un botón que dice "Review changes". Si le haces clic te mostrará la opción "Approve". Basta con que la selecciones y hagas clic en "Submit review". No es necesario escribir nada en el recuadro.

![Screenshot from 2022-08-01 11-54-45](https://user-images.githubusercontent.com/31421616/182189833-17a8eb85-ba56-417a-bf52-23541ee5a4e2.png)


Cualquier duda, me avisas.

**Comment by nivaca** [comment]
@rivaquiroga ¡Perfecto, mil gracias! Ya lo hice. ¿El merge lo haces tú?

**Comment by rivaquiroga** [comment]
Muchas gracias! Ya hice el merge. Ahora hay que esperar un rato hay que la página se actualice para poder gestionar la activación del DOI, que también me corresponde a mí. Cuando tenga la confirmación de que está activo vuelvo por acá y vemos lo de Twitter.

**Comment by rivaquiroga** [comment]
@nivaca, me acabo de dar cuenta que puse mal un número en el DOI. Voy a tener que hacer un nuevo pull request para que apruebes :grimacing:

**Comment by nivaca** [comment]
@rivaquiroga Hecho. 👍

**Comment by rivaquiroga** [comment]
@nivaca, el DOI ya está activo: https://doi.org/10.46430/phes0059 :tada:
Cuéntame si usas Twitter y te acomoda hacer los pasos que siguen (incluir la lección en el bot de Twitter y anunciar la lección en esa plataforma) o si prefieres que los haga yo.

**Comment by nivaca** [comment]
@rivaquiroga Perdón por la demora, estaba fuera de casa. No tengo cuenta de Twitter, lo siento. Por favor haz el anuncio tú. ¡Gracias!

**Comment by rivaquiroga** [comment]
¡Listo! La lección ya está publicada y anunciada en Twitter.
Muchas gracias a todas las personas que participaron en el proceso. En especial a @vgayolrs por la traducción, a @jamotilla por la revisión y a ti @nivaca por completar la edición y hacer las actualizaciones necesarias.
Con esto damos por completado el proceso, así que cerraré este ticket.

**Comment by nivaca** [comment]
Muchas gracias a ti, @rivaquiroga!
