### ISSUE TITLE
Ticket de revisión "Análisis de corpus con Voyant Tools"

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#211]
The Programming Historian en español ha recibido la siguiente propuesta de tutorial "Análisis de corpus con Voyant Tools" por parte de @silviaegt. Este tutorial se encuentra en estos momentos en fase de revisión por parte de @danavido . Puede leerse en:

## Texto

http://programminghistorian.github.io/ph-submissions/es/lecciones/analisis-voyant-tools

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/analisis-voyant-tools.md

## Imágenes

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/analisis-voyant-tools

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by silviaegt** [comment]
Hola @jenniferisasi, ¡muchas gracias por revisar este tutorial! Quedo atenta a cualquier duda 😄

**Comment by jenniferisasi** [comment]
@silviaegt gracias a ti por escribir el tutorial. Me pongo ya con la búsqueda de revisores para comenzar el proceso.

**Comment by jenniferisasi** [comment]
La primera en realizar una revisión del tutorial será @danavido, notando cualquier cuestión que necesite aclaración y/o corrección. ¡Gracias!

**Comment by danavido** [comment]
Estimadas @silviaegt  y @jenniferisasi, en breve enviaré los comentarios al texto que estoy revisando. Gracias por considerarme para la tarea.

**Comment by danavido** [comment]
Habiendo culminado la lectura (_y la puesta en práctica_) del tutorial, detallo a continuación algunas observaciones. Al realizar las actividades propuestas pude aprender algunas herramientas que no conocía aún y comprender el potencial de otras, gracias a que el lenguaje es apropiado a un nivel introductorio. Sugiero mencionar, en la introducción o cuando aparece la primera de las actividades, que las respuestas se encuentran al final del tutorial. 

Quisiera mencionar que es posible que haya malinterpratado los saltos de párrafos, en cuyo caso se les debe aumentar en una unidad al número de párrafo referido. 

#### párrafo 1: 
- el enlace a Voyant tools sugiero cambiarlo por `https://voyant-tools.org/?lang=es` 
- hacia el final del párrafo, donde dice "y el tercero 'Análisis de corpus con R'" creo que debería decir "y el tercero 'Procesamiento básico de textos en R'" (enlace a la lección: `https://programminghistorian.org/es/lecciones/procesamiento-basico-de-textos-en-r`), a menos que refiera a otra lección que aún no está publicada. 

#### párrafo 18: 
- donde dice "el código del país (ISO 3166-1 alfa-2)" sugiero cambiar el enlace por `<https://es.wikipedia.org/wiki/ISO_3166-1#Tabla_de_c%C3%B3digos_alfa-2_asignados_o_reservados` ya que el incluido resulta difícil de navegar. 

#### párrafo 21: 
- creo que se puede remover la advertencia, probé el enlace y funciona bien. También puede agregarse el enlace a la descarga desde zenodo, como se hizo en el párrafo 8. 

#### a partir del párrafo 24 hasta el párrafo 29: 
- la lista de herramientas (cirrus, lector, etc) utiliza siempre el mismo número de ítem, en lugar de números consecutivos. Es decir, debería ser 1. Cirrus, 2. Lector, 3. Tendencias, etc, o bien listar sin números. 

#### párrafo 35: 
- la actividad 1 consiste en contar las palabras únicas; creo que, si bien puede parecer algo demasiado obvio para ser explicado puede ser necesario hacerlo. Lo menciono ya que es la primera vez que me enfrento a este herramienta y mi respuesta inmediata a la actividad fue que las palabras únicas son 2 (hambre y sueño, ya que 'tengo' no es única sino que se repite); luego, pensándolo mejor y entendiendo a las palabras como las unidades del análisis, creo que la respuesta correcta sería 3 palabras únicas (tengo, hambre, sueño). _Actualización_: Al terminar la lectura pude ver las respuestas a las actividades al final del tutorial y por cierto mi respuesta inicial estaba equivocada. 

#### párrafo 37:
- sugiero cambiar "se mide dividiendo el número de palabras distintas entre el número de palabras totales" por "se mide dividiendo el número de palabras únicas entre el número de palabras totales" 

#### párrafos 39 y 40:
- respecto del cálculo de "palabras por oración", faltaría mencionar dónde encontrar esta información (solapa "Sumario" y también en la solapa "Documentos")

#### párrafo 55:
- respecto de la frecuencia de palabras, en el ensayo no me dan los mismos resultados después de filtrar las palabras sugeridas. Posiblemente esto no sea importante, ya que la actividad invita a reflexionar sobre los motivos que conducen a diferentes resultados en esta herramienta. 

#### párrafos 59 y 60: 
- la lista numerada utiliza el mismo número en ambos ítems (1), en lugar de números consecutivos (1, 2).
- al final del segundo ítem, donde dice "Para más información, consulta la documentación en inglés.1", hay una nota en superíndice cuya referencia no ha sido agregada al final. 

#### párrafo 64: 
- sugiero reemplazar ` ;` por `,` donde dice "Una de las medidas más usadas se llama tf-idf (term frequency, inverse document frequency); la cual busca expresar numéricamente qué tan relevante es un documento en una colección determinada". 

#### párrafo 69:
El apartado inicia con la oración "El proyecto con el que algunas historias (...) iniciada por el filólogo y religioso Roberto Busa." que luego no es relacionada con el texto que continúa "En la esquina inferior derecha Voyant, es posible hacer consultas de términos específicos". Creo que ayudaría a la lectura que se agregara una oración de trancisión entre ambas. 

#### párrafo 75: 
- realizando los pasos sugeridos por el tutorial, al intentar exportar los datos de la tabla de la solapa "Contextos" la opción que me sale en pantalla no se llama "[ExportGridAllTsv]" sino "export all available data as tab separated values (text)grid". 

_No hay más comentarios_. He disfrutado aportar mi grano de arena en este proyecto, espero estar haciéndolo de manera correcta y respetuosa. Gracias @silviaegt por escribir tremendo tutorial.

**Comment by silviaegt** [comment]
@danavido te agredezco muchísimo tu cuidadosa lectura y las recomendaciones que me has hecho, las leeré con cuidado y mañana me pondré a ello.

**Comment by jenniferisasi** [comment]
Gracias @danavido por tu revisión. @silviaegt si quieres, como dices, puedes hacer los cambios que te sugiere y así evitamos que se repitan los comentarios por parte de la segunda revisora. Yo le daré también una lectura para ver que todo funciona, sobre todo el estilo markdown. 

¡Gracias!

**Comment by silviaegt** [comment]
Queridas, ya integré las observaciones de @danavido que me ayudaron muchísimo. Quedo atenta @jenniferisasi por si falta algo :)

**Comment by jenniferisasi** [comment]
¡Gracias @silviaegt! Le vamos a dar una segunda lectura, por parte de Nicte (pronto la conectaré al issue) y yo me aseguraré de que las imágenes funcionan. Quizás vamos a tener que añadir algún tipo de información textual en los gifs que has puesto al comienzo para aquellos que usan lector de pantalla. Seguimos

**Comment by jenniferisasi** [comment]
¡Bienvenida a The Programming Historian @NFM2019! Este es el hilo en el que estamos revisando el tutorial de Voyant-Tools [link arriba]. Puedes echar un vistazo a la [guía para revisores](https://programminghistorian.org/es/guia-para-revisores#lecciones-nuevas) que tenemos y recomiendo que realices la lección como una usuaria más. 
Puedes dejar aquí tus comentarios indicando el número de párrafo al que te refieres. Y cualquier duda que tengas no dudes en contactar conmigo. ¡Gracias!

**Comment by silviaegt** [comment]
Ustedes me dicen si hay algo que deba hacer @jenniferisasi @NFM2019 :)

**Comment by jenniferisasi** [comment]
@NFM2019, ¿cómo vas con la revisión? Por favor, avísame si tienes algún problema o responsabilidad que vaya a retrasar la entrega de comentarios para poder adaptar el calendario o buscar otra revisor/a. ¡Gracias!

**Comment by jenniferisasi** [comment]
@silviaegt para no retrasar más su publicación, dejo aquí mis revisiones en lo que realizo el tutorial como usuaria. Las cuestiones de estilo que apunto son a considerar para la comprensión lectora, pero no 100% necesarias: 

Nota a mí misma: ver cómo están en otros tutoriales los titulitos pues creo que sobra el primero que dice "Contenidos" y editar el markdown final 

párrafo 2: 
- se aprenderán los básicos -> se aprenderán los pasos básicos
- "una plataforma que no requiere instalación:" -> ¿qué te parece añadir aquí que aunque no requiere instalación en la compu, sí requiere conexión continuada a Internet para su acceso y utilización? [veo que está en el párrafo 5º, así que lo dejo a tu consideración]
- Siguiendo las consideraciones que suelo leer del equipo en inglés, no debemos añadir menciones a tutoriales todavía no publicados (aunque @rivaquiroga ya lo haya propuesto) porque no hay "garantía" de su publicación. Además, puesto que no se trata de la misma herramienta en los 3 tutoriales y el número de tutoriales con el mismo propósito podría ser ampliado, en vez de "el primero...en una serie de tres" cambiaría el mensaje a algo como "una de las opciones para el análisis de corpus que puedes encontrar en PH" ¿Qué te parece? 

párrafo 4: 
- sugerencia de estilo: (es decir tablas con los contextos izquierdos y derechos de un término). -> (es decir, tablas con los contextos a la izquierda y a la derecha de un término) 

párrafo 8: 
-  MS Word); -> MS Word), 

párrafos (gifs) 14, 15 y 16: 
-  necesitamos incluir en los gifs el mínimo de las instrucciones para aquellos que no puedan seguir/ver el gif/video con una etiqueta de texto alternativo 

párrafo 21:
- el formato para nota nº2 cambia el formato del resto del párrafo. 

párrafo 35: 
- Aquí y antes de la *actividad 1* añadiría una frase que indique que desde ese momento se introducen unos ejercicios, uniéndolo con la nota sobre las respuestas (y así el aviso noes necesario)

párrafo 39-40: 
- en la actividad 2: considerando los metadatos del título -> considerando los metadatos del nombre del archivo 

párrafos 47, 50, 53: 
- separar la cuestión nº2 de la nº1 

párrafo 54: 
- creo que falta algo aquí: "Colocamos nuestro cursor enor superior derecha de la ventana de Cirrus"

párrafo 62: 
- En este caso, si dejasta -> En este caso, si dejaste

párrafo 68: 
- en vez de Excel -> en un programa de hojas de cálculo 

párrafo 73: 
-  (term frequency, inverse document frequency) -> añadir en español 

párrafo 83: 
- Izquerda -> Izquierda 

párrafo 87: 
- (¡no olvides la codificación UTF-8) -> falta el signo de exclamación final 

Respuesta actividad 3:
- quitar el primer pues en: "Debemos tener cuidado, pues, al interpretar estos números pues sólo"  

¡Excelente tutorial! Cuando realices los cambios creo que está listo para publicar. Como siempre, quedo a disposición para cualquier cuestión que surja por el camino de, en este caso, la edición.

**Comment by danavido** [comment]
Hola Silvia, Jennifer y María José. ¿hay algo más en lo que pueda ayudar?

**Comment by silviaegt** [comment]
Muchísimas gracias @jenniferisasi @danavido he terminado con las correcciones. Quedo atenta para lo que siga

**Comment by jenniferisasi** [comment]
¡Excelente, @silviaegt! Gracias por añadir las instrucciones escritas en los gifs.  
Le voy a dar una última lectura y lo migro al repositorio para su publicación. Creo que lo tendré listo hoy mismo.

**Comment by mariajoafana** [comment]
Felicitaciones a todas por la publicación! Voy a cerrar el ticket, si hay algo más por revisar lo podemos reabrir.
