### ISSUE TITLE
Ticket de revisión "Introducción a Map Warper"

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#212]
The Programming Historian en español ha recibido la siguiente propuesta de tutorial "Instroducción a Map Warper" por parte de @mdcs87 y @apicon . Este tutorial se encuentra en estos momentos en fase de revisión por parte de @arojascastro @rivaquiroga @editio. Puede leerse en:

## Texto
http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-map-warper

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-map-warper.md

## Imágenes
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/introduccion-map-warper

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

# Política contra el acoso

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by mariajoafana** [comment]
La primera ronda de revisión del tutorial la voy a hacer yo

**Comment by mariajoafana** [comment]
@mdcs87 y @apicon estoy revisando el tutorial pero el enlace donde se encuentra el Mapa cafetero en la Biblioteca Nacional no está funcionando. Por otro lado, les pido que suban la imagen del mapa a esta capeta: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/introduccion-map-warper
Voy a esperar a tener acceso al mapa para poder adelantar la revisión

**Comment by mariajoafana** [comment]
Un primer comentario sobre el tutorial es añadir una sección donde se explique qué se va a aprender en el tutorial, es decir, enunciar claramente, qué tendrá la capacidad de hacer el usuario al finalizar el tutorial. Ver por ejemplo esto para el caso del tutorial de Voyant Tools.

**Comment by mdcs87** [comment]
Recibido María José, que pena por la tardía respuesta. Vamos a revisar esto para proporcionarles esa sección.

**Comment by mariajoafana** [comment]
Ok, quedo pendiente para continuar con el proceso de revisión

**Comment by mdcs87** [comment]
Hola María José. Nuevamente perdón por la tardanza. Como te habrás dado cuenta actualizamos el archivo del mapa utilizado, pusimos la versión en español. 
Ya tenemos el texto que nos solicitas. Pero no sabemos si es necesario pasarlo en markdown o si lo podemos enviar a tu correo como archivo .doc. Mientras tanto lo pongo acá:
"En el tutorial se aprenderá a georreferenciar materiales cartográficos (mapas, planos, fotografías aéreas y otros), mediante la plataforma libre Map Warper, misma que no requiere instalación. En ese sentido, la lección es un complemento a otras lecciones de Programming Historian, referentes a la utilización de Sistema de Información Geográfica para el análisis espacial (Georeferencing in QGIS e Introducción a Google Maps y Google Earth). En esta ocasión, además de conocer las pautas técnicas esenciales para la georeferenciación de mapas antiguos, el usuario se familiarizará con el patrimonio cartográfico y su potencialidad en la investigación histórica."

Quedamos atentos y gracias por toda la comprensión.

**Comment by mariajoafana** [comment]
Hola Miguel, yo misma actualizo el archivo en md con la adición

**Comment by mariajoafana** [comment]
@mdcs87 y @apicon acá les dejo algunos comentarios, la P indica el párrafo donde se hace la sugerencia [acá]:(http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-map-warper)

P 3: incluir el enlace a los tutoriales que ahí se citan
P 6: Sugiero que las instrucciones para utilizar Map Warper comiencen de una vez con el material con el que se va a trabajar. Es decir, en upload map dar la instrucciones para comenzar con ese mapa y dar la información para llenar algunos de los campos de la sección Edit y de ahí dar las instrucciones precisas de cómo trabajar con el mapa con las otras herramientas para la georreferenciación. Es deseable que el mapa con el que se va a trabajar esté dispoible ya en el repositorio de PH, en la sección assets y así garantizar el acceso al material y la sostenibilidad del tutorial. Si me envían el archivo del mapa me puedo encargar de subirlo. 
P 9: El enlace al Mapa Cafetero de Colombia está roto. ¿Es este? [http://babel.banrepcultural.org/cdm/ref/collection/p17054coll13/id/100](http://babel.banrepcultural.org/cdm/ref/collection/p17054coll13/id/100)
Si es así habría que indicar en qué resolución se debe descargar el mapa, aunque como lo mencioné es preferible que el archivo del mapa quede guardado en nuestro repositorio y que el usuario lo descargue de ahí para fines de hacer el tutorial.
Descargué una versión de este mapa en la mejor resolución y lo subí a MapWarper y luego le di clic a "create" y me sale: "Incomplete response received from application". No se si estoy haciendo algo mal o la aplicación está fallando.

Antes de seguir revisando el tutorial les pido por favor que revisen ese error para yo poder seguir haciendo el tutorial.

**Comment by mdcs87** [comment]
Frente al P3, aquí van los enlaces: 
Georeferencing in QGIS https://programminghistorian.org/en/lessons/georeferencing-qgis 
Introducción a Google Maps y Google Earth https://programminghistorian.org/es/lecciones/intro-a-google-maps-y-google-earth
Ya seguimos con los otros puntos.

**Comment by apicon** [comment]
P6: 
Para cargar un material cartográfico en Map Warper, selecciona la pestaña “Upload Map”. Ahí podrás vincular la cartografía directamente desde un archivo local o anclarla desde un repositorio web por medio de la URL correspondiente. Para el ejercicio cargará el Mapa Cafetero de Colombia (fmapoteca_984_figac_16.jpg: http://catalogoenlinea.bibliotecanacional.gov.co/custom/web/content/mapoteca/fmapoteca_984_figac_16/fmapoteca_984_figac_16.jpg) o la cartografía de su preferencia. En este paso también puedes ir agregando los metadatos correspondientes del material cartográfico a georreferenciar. Para terminar el proceso de carga da click en la opción “Create”.

P9: El enlace es correcto, es el permalink del mapa proporcionado por la Biblioteca Nacional de Colombia. Sin embargo estamos esperando que ellos terminen la carga en la Mapoteca Digital (final de agosto). 

Nota: La versión de Mapwarper.net,  según Tim Waters, se encuentra en actualización debido a problemas técnicos con el almacenamiento en el servidor. Entonces propongo utilizar la versión japonesa para el desarrollo del tutorial, esto no cambiará la metodología, estética y propósito del tutorial.  Para ello el link: http://mapwarper.net/ debe cambiar por https://mapwarper.h-gis.jp/?locale=en.

**Comment by mariajoafana** [comment]
@apicon y @mdcs87 gracias. La idea es que ustedes hagan las ediciones directamente en el archivo .md : https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-map-warper.md
Les recomiendo que cuando entren a hacer la edición antes de darle clic al botón de "edit" seleccionen el branch "edicion-map-warper" . Esto se selecciona al lado izquierdo de: ph-submissions/es/lecciones/introduccion-map-warper.md
Cuando terminen le dan clic a "Commit changes" y asegúrense que diga:  Commit directly to the edicion-map-warper branch.
De esta manera estarán haciendo las ediciones al tutorial en un "branch" o rama del original y no directamente. Me cuentan si tienen alguna duda

**Comment by apicon** [comment]
@mariajoafana 
Ya realizamos los cambios correspondientes, según la indicación, respecto al párrafo 3 y 9.
Frente al párrafo 6 en la Biblioteca quedaron de subir la visualización prontamente. Igual eso no modifica el buen desarrollo del tutorial.
Quedamos atentos de las próximas indicaciones.

**Comment by rivaquiroga** [comment]
@mariajoafana, ¿esta lección está lista ya para que la mire un segundo revisor?

**Comment by rivaquiroga** [comment]
@programminghistorian/spanish-team, María José no podrá seguir haciéndose cargo de la edición de esta lección, por lo que necesitamos que alguien asuma ese rol. @arojascastro, ¿podrías tú finalizar el proceso? Los autores ya incorporaron las sugerencias que ella les hizo.

**Comment by mariajoafana** [comment]
P 2: Sugiero utilizar "conjunto de datos" en vez de "datasets"
¿El archivo que se debe descargar se llama "tutorial.sql!? Si es este el archivo especificarlo en las instrucciones
P 6: sugieron cambiar ";lo que representa..." por ". Esto representa una ..."
P 7: sugiero editar así: "La arquitectura de Omeka está basada en PHP-MySQL. Esto significa que la información que se agrega, modifica y lee desde el entorno de la plataforma escrito en PHP. Esta queda almacenada en una base de datos MySQL y se procesa mediante un servidor Apache." 
P 16: En Mac OS X es un poco diferente. Se debe dar clic a la pestaña "services" y ahí  "start". No es posible dar instrucciones para todos los sistemas operativos por lo cual sugiero incluir una nota que diga que la interfaz se verá en poco diferente para cada OS. 
P 18: En Mac OS X las direcciones http://localhost/ o http://127.0.0.1 no me funcionan pero en la pestaña "general" haciendo clic en "Go to application" si lo lleva a uno a la pantalla de inicio
P 24: En Mac OSX hay que habilitar el acceso remoto a phpMyAdmin. Estas son las instrucciones: http://192.168.64.2/dashboard/docs/access-phpmyadmin-remotely.html 

No podido habilitar el acceso, voy a seguir cacharreándole para poder hacer el tutorial efectivamente en Mac. Retomaré los comentarios al tutorial cuando resuelva esto.

**Comment by mdcs87** [comment]
Hola recibimos un mensaje al parecer relacionado con Omeka. Quedamos atentos.

**Comment by mariajoafana** [comment]
Perdón, puse el mensaje acá y era para otro ticket!

**Comment by arojascastro** [comment]
> 
> 
> @programminghistorian/spanish-team, María José no podrá seguir haciéndose cargo de la edición de esta lección, por lo que necesitamos que alguien asuma ese rol. @arojascastro, ¿podrías tú finalizar el proceso? Los autores ya incorporaron las sugerencias que ella les hizo.

sí, pero necesito unos días

**Comment by arojascastro** [comment]
Hola, 

Entiendo entonces que la revisión de los dos revisores se realizó y que el autor o autora ya hizo los cambios, ¿cierto? Si es así (por favor, confirmad) me leeré la lección y completaré el proceso editorial para publicarla en breve. 

Quedo a la espera de una confirmación. Gracias.

**Comment by arojascastro** [comment]
Ah no, perdón, aún hay que buscar dos revisores. Vale. Pues me la leo y voy pensando en dos revisores externos. Perdón por la confusión.

**Comment by arojascastro** [comment]
Gracias por la paciencia y por escribir el tutorial. 

Voy a hacer yo una primera revisión del tutorial.

Como revisor mi punto de vista es el siguiente:

## Generalidades
- En la sección "¿Qué es Map Warper?" creo que se debería cambiar a "¿Qué es Map Warper y por qué utilizar esta herraminienta?" y añadiría un tercer párrafo explicando *por qué* utilizar esta herramienta y no otra. También creo que se podría hacer esta sección un poco más crítica o analítica y situar la herramienta dentro de los estudios espaciales o visuales y el mapeado; hay mucha investigación sobre el tema en las Humanidades Digitales. En fin, creo que hace falta un poco de contenido intelectual para convencer al lector de que vale la pena aprender a usar este programa.
- En la sección "Lo que aprenderás en este tutorial" creo que falta una lista de los principales "outputs" o bien de los pasos principales.
- En todo el tutorial: los títulos de apartado mejor en español o bien en inglés y traducción entre paréntesis
- Falta una conclusión en el que se haga un resumen de los principales pasos y se sugiera qué se podría en el futuro con los datos o el mapa creado. Es decir, ampliar la mirada a otras actividades. Aquí también se podrían dar referencias bibliográficas que discuten proyectos de mapeado o mencionar proyectos de HD que usan la herramienta.

## Mis comentarios específicos por párrafo

- 1: software --> programa informático?
- 3: Programming Historian --> en cursiva. Además, creo que se debería aclarar aquí o en el párrafo 3 en qué idiomas está disponible la interfaz web. También habría que aclarar si es una herramienta open source y grauita o no.
- 11: ¿Qué lugar está representando en el material cartográfico? ¿cuáles fueron los cambios a lo largo del tiempo del espacio representado? ¿reconoces algún punto de referencia geográfica vigente?  --> faltan comas separadoras o bien empezar con mayúscula.
- 14: falta un vídeo? En principio no aceptamos vídeos... solo imagen para ilustrar el texto. Por favor, aclarad esta cuestión.
- 15: sustituir guiones largos por paréntesis para poner la traducción
- 24: en lugar de nota, poner ese comentario en un destacado con >
- 26: como dije antes, creo que el tutorial termina de manera abrupta. Necesitamos una conclusión con un resumen de los principales pasos y por qué vale la pena usar esta herramienta.
 
En mi rol de editor: ahora buscaré otro revisor externo; no hace falta que hagáis ningún cambio aún  @mdcs87 y @apicon. Esperaremos al segundo revisor y luego podréis hacer los cambios que consideremos oportunos.

**Comment by arojascastro** [comment]
Pregunta extra para @mdcs87 @apicon : el tutorial es individual, solo queréis escribir uno sobre esta herramienta, o este tutorial forma parte de una serie tutoriales sobre el mismo programa? Pregunto porque veo que la herramienta puede hacer más cosas.

**Comment by rivaquiroga** [comment]
@arojascastro, si te parece, puedo hacer de segunda revisora de esta lección.

**Comment by arojascastro** [comment]
Adelante @rivaquiroga ! Gracias

**Comment by editio** [comment]
Hola a todos los participantes:

Muchas gracias @arojascastro por la invitación a colaborar con una revisión. Paso a referir algunas cuestiones de forma separada. Me sirvo de los epígrafes de la lección y de los párrafos para estructurar los comentarios (separo las cuestiones de redacción de las de contenido).

Elaborar materiales didácticos, como sabéis aquí muy bien, no es fácil, así que mucho ánimo a los creadores. Espero que los comentarios sirvan de algo.

## Contenidos

- ¿Otro título?: "Introducción a la georreferenciación con Map Warper".

- Quizá sería mejor introducir una estructura más acorde a las de PH: Introducción, Objetivos de la lección, etc. 

- No pondría preguntas en los epígrafes. Mejor, p. ej., El servicio web / la aplicación Map Warper.

- Los epígrafes siguen el menú de la aplicación en inglés. Quizá poner mejor una traducción explicativa con el término exacto del menú en inglés:

	-- Visualización del mapa (_show_)

	-- Georrectificación (_rectify_)

	-- Recorte (_crop_)

- Registrarse] Registrar; otra opción: Registro] Registrar; Abrirse una cuenta] Registrar

- Sustitúyase cartografía por mapas/mapa. Cartografía se refiere a la disciplina. Por otro lado, creo que se trata de cargar el mapa, no de enlazarlo (aunque se pueda cargar a través de un enlace): cargar un mapa] vincular cartografía.

- Qué aprenderás...] Lo que aprenderás... (cuestión de preferencia propia).

## ¿Qué es Map Warper?

### Redacción

¶ 1

- "Map Warper, desarrollado por Tim Waters, es una herramienta"
- "imágenes ráster"
- "QGIS, (Java) OpenStreetMap, ArcGIS, Google Earth, World Map–, catálogos".

### Contenido:

- Tengo la impresión de que (Java) OpenStreetMap se conoce más como JOSM. OpenStreetMap Editor.
- Me parece muy clara la descripción de la herramienta que llega cuando uno se registra; quizá se podría poner al inicio y luego completar con lo ya escrito.

>  MapWarper is a participatory site where you can discover, georeference and upload your own maps and imagery. You can georectify or warp the map to base map to be able to use the map in new ways. You can download the georeferenced image in a number of formats including KML, WMS, and Tiles.

- Mencionaría otras herramientas con las que se puede tambien georrectificar usando una plataforma en línea: _Georeferencer_ <https://www.georeferencer.com>

- Tendría en cuenta que en general estas herramientas permiten georrefenciar cualquier imagen (un mapa hecho a mano por nosotros mismos).

## Lo que aprenderás en este tutorial

### Redacción

¶ 3

- "libre Map Warper. La lección"
- georreferenciación] georeferenciación 

### Contenido
 
- Añádase el enlace a los otros tutoriales de PH mencionados.


## Registrar

### Redacción

- ingresa en] ingresa a
- correspondiente] correspondientes


## Vincular cartografía

### Redacción

¶ 6

- Sustitúyase cartografía por mapas/mapa
- haga clic] da click 

¶ 7

- "Si bien este paso es opcional...": El lector todavía no sabe qué se hace en este paso. Propongo comenzar con algo así como: "En este paso se añaden los metadatos a la imagen cargada. Si bien este paso..."

### Contenido

- Llegado a este paso el lector no tiene información sobre qué mapa o imagen subir, qué formato, de dónde obtenerla. 
- Creo que antes de este punto, se debería presentar el mapa con el que se va a trabajar (que se menciona en el punto siguiente, el mapa cafetero de Colombia): ¿se debe descargar?, ¿se debe enlazar? (la herramienta ofrece la posibilidad de introducir una URL, pero la que se da más adelante no es la de descarga/enlace). Por lo que veo, parece que es un mapa ya georreferenciado, pues ofrece la posibilidad de descarga en GeoTiff.

- Es importante abordar las cuestiones de los derechos: ¿puedo subir a mi cuenta ese mapa? ¿Qué derechos tiene? La aplicación lo destaca explícitamente.


## Georreferenciar cartografía

¶ 9
- _Vide supra_ sobre el mapa cafetero de Colombia.

¶ 11

- Es muy interesante la reflexión sobre la exploración del mapa. Como muy bien se indica "Estas consideraciones son fundamentales para desarrollar el siguiente paso". Añadiría al final algo más concreto, pues desde luego es importante conocer el mapa porque necesitamos como mínimo tres puntos en el geoespacio para poder georrectificarlo. 

¶ 13 

- _Rectify_: esta es la parte más importante y se limita a un video, que no está presente. Incluiría una descripción de los pasos, como sí se hace en otros casos.

¶ 15

- La herramienta ofrece la posibilidad de recortar la imagen o de formar un mosaico de varias imágenes, pero la imagen elegida no es un buen ejemplo, sobre todo para el mosaico (no parece ser el caso del mapa cafetero). Explicaría por qué se debe recortar (por ejemplo, elementos en la imagen inecesarios, que dificultan la superposición).


## Descargar cartografía

- Denominaría este epígrafe, p. ej., Usos del mapa georrectificado. Está muy bien la explicación de los distintos formatos, que no son todos para descargar. La aplicación también ofrece la posibilidad de alojar el mapa para servirlo en otra aplicación usando, p. ej., el formato XYZ de teselas. También se puede destacar su uso compartido, su anotación compartida, etc.

¶ 24
- Ampliaría un poco esa "nota", sobre todo para destacar que no todos los mapas son cien por cien georrectificables, sobre todo los históricos, cuáles son los problemas de proyección, las deformaciones en las partes más al norte y al sur, etc.

**Comment by arojascastro** [comment]
Muchas gracias @editio por tu profunda revisión. Esperamos la lectura de @rivaquiroga - por favor, @apicon @mdcs87 no hagáis cambios aún, pero sí os agradecería que respondierais a nuestras dudas pronto.

**Comment by mdcs87** [comment]
Hola @arojascastro y @editio. Gracias por los comentarios y perdón por la demora en responder. Con Anthony estamos revisando sus comentarios para responder. Esperemos poder hacerlo antes del fin de esta semana. De todo modos, me parece que todos los comentarios planteados son validos y estamos esperando la segunda revisión para hacer la modificiación definitiva.

**Comment by rivaquiroga** [comment]
¡Hola! Tendré mis comentarios antes del próximo martes 18 de febrero.

**Comment by arojascastro** [comment]
Gracias @mdcs87 ! Esperamos la lectura de @rivaquiroga

**Comment by rivaquiroga** [comment]
¡Muchas gracias por escribir el tutorial! Sin duda será un aporte para The Programming Historian en Español.

Haré primero comentarios generales y mañana publicaré algunas sugerencias vinculadas a aspectos de forma/escritura. 

### Comentarios generales

Concuerdo con Antonio en que sería importante desarrollar un poco más la sección introductoria con el fin de convencer a quien lee de la relevancia/utilidad de utilizar esta herramienta. Asimismo, resultaría más claro que se introduzca el caso de estudio que se va a considerar en la lección. Por ejemplo, adelantando lo que se menciona en el ¶10. 

Concuerdo también en que es necesario algún tipo de cierre, de lo contrario es muy abrupto el fin de la lección. Por ejemplo, plantear preguntas de investigación que podrían abordarse ahora que el mapa está georreferenciado. 

Modificar los subtítulos como sugieren ambos revisores ayudaría a entender mejor el contenido de la lección. Si uno llega a ella y ve la lista de contenidos tal como está, es difícil inferir de qué va a tratar.

**Comment by arojascastro** [comment]
Hola @rivaquiroga ya sé que tienes muchas tareas, pero cuándo crees que podrás terminar la revisión? Gracias.

**Comment by arojascastro** [comment]
Es posible que, debido al Coronavirus, la revisión de este tutorial se demore un poco más. Quedamos a la espera de la revisión de Riva para que los autores empiecen a hacer los cambios sugeridos. Gracias.

**Comment by rivaquiroga** [comment]
@arojascastro, @mdcs87 y @apicon, gracias por la paciencia. Aquí están los otros comentarios, que complementan los aspectos de redacción mencionados por el primer revisor.

______

**Redacción**


¶ 2
Sugiero dividir el párrafo en dos, ya que se abordan dos temas diferentes. El corte habría que hacerlo en "Por su parte,".

¶ 2
"Por su parte" > "En este contexto,"

¶ 3
En vez de hablar de "el usuario", sugiero seguir tuteando a los destinatarios. 

¶ 4
"Desde tu navegador favorito ingresa a www.mapwarper.net, ve a la pestaña..." > "Desde tu navegador favorito ingresa a www.mapwarper.net y ve a la pestaña..."


¶ 6
"En este paso también puedes ir agregando los metadatos correspondientes del material" > "En este paso también puedes ir agregando los metadatos del material"

¶ 7
"Debido a la naturaleza colaborativa y colectiva de Map Warper recomendamos" > "Debido a la naturaleza colaborativa y colectiva de Map Warper, recomendamos"

¶ 8
Punto 1: Title
¿Hay que agregar número de registro y título? Si es una numeración de dos elemento, sugiero cambiar la coma por una "y".

¶ 8
Punto 4: Tags
Como todas las descripciones parten con un sustantivo, sugiero mantener eso en este punto también. Por ejemplo "tres a cinco etiquetas que describan el material"

¶ 8
"En ese sentido, se recomienda vincular la mayor información del recurso compartido, ayudando a los usuarios de la herramienta contar con la mayor información del contenido." > "Se recomienda vincular la mayor cantidad de información del recurso compartido, con el fin de que los usuarios de la herramienta cuenten con datos sobre el contenido."

¶ 11
"Esta pestaña nos presenta la visualización del documento cartográfico vinculado, entre las herramientas..." > "Esta pestaña nos presenta la visualización del documento cartográfico vinculado. Entre las herramientas..."

¶ 11
Respecto de las preguntas, pueden elegir entre ponerlas todas con mayúscula inicial o dejarlas en minúscula y agregar coma para separarlas. 

¶ 12
"no solo en el aspecto técnico, también en función del uso interpretativo que se hará del material." > "no solo en el aspecto técnico, sino también en función del uso interpretativo que se hará del material."

¶ 13
"La ventana principal nos presentará dos recuadros, el recuadro de la izquierda contiene al mapa vinculado, el recuadro de la derecha contiene el mapa base, predeterminadamente aparece asociado a la capa base de OpenStreetMap." > "La ventana principal nos presentará dos recuadros: el recuadro de la izquierda contiene al mapa vinculado y el recuadro de la derecha contiene el mapa base, que de forma predeterminada aparece asociado a la capa base de OpenStreetMap."

¶ 15
"La pestaña “Crop” permite recortar el área de interés de la cartografía trabajada, de acuerdo con esto, la opción es útil para dividir mapas compuesto." > "La pestaña “Crop” permite recortar el área de interés de la cartografía trabajada, por lo que resulta útil para dividir mapas compuestos."

¶ 15 
"Por último, después de demarcar el área a mantener, damos click en..." > "Una vez que hayamos demarcado el área a mantener, hacemos clic en..."

¶ 17 
"La pestaña “Aling” permite organizar como mosaico un conjunto de cartografías, es una herramienta..." > "La pestaña “Aling” permite organizar como mosaico un conjunto de cartografías. Es una herramienta..."


¶ 17
"fragmentados, fotografías aérea, y demás" > eliminar coma antes de _y_

¶ 19
"Esta pestaña permite visualizar los resultados ejecutados del paso “Rectify”, es útil para hacer seguimiento al proceso de georreferenciación llevado en curso." > "Esta pestaña permite visualizar los resultados ejecutados del paso “Rectify”. Es útil para hacer seguimiento al proceso de georreferenciación llevado en curso." (también podría ser un punto seguido)

¶ 20
"La pestaña “Export” permite descargar la imagen georreferenciada en diferentes formatos, archivos estándar en distintos Sistemas de Información Geográfica (SIG)." > No me queda muy clara la coma acá. ¿Es equivalente a "o" en este caso? 

¶ 21
"utilizar estos formato" > "utilizar estos formatos"

¶ 22
"... Images, sin embargo, solo se pueden" > "... Images; sin embargo, solo se pueden"

¶ 23
"en el paso “Rectify”, la tabla agrupa los puntos de control entre la imagen raster (mapa antiguo) con el mapa vectorial de OpenStreetMap , es decir que asocia x,y a la longitud y la latitud." > "en el paso “Rectify”. La tabla agrupa los puntos de control entre la imagen ráster (mapa antiguo) con el mapa vectorial de OpenStreetMap, es decir, que asocia _x,y_ a la longitud y la latitud, respectivamente.

¶ 25
"los campos de: “Time”..." > "los campos: “Time”..."

¶ 25
"en archivo .rss." > "en formato .rss."
Sugiero rodear .rss entre tildes graves para que quede formateado así: `.rss`.

¶ 26
"No olvides dar click" > "No olvides hacer clic"

**Comment by arojascastro** [comment]
Muchas gracias @rivaquiroga ! Creo que todos los cambios propuestos los dos revisores externos y los míos son razonables. El tutorial es una buena contribución, pero se proponen cambios en la redacción, el contenido, la estructura y una ampliación de algunos apartados. 

@mdcs87 y @apicon ya pueden hacer los cambios propuestos en el mismo archivo publicado con Github: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-map-warper.md

Aquí encontraréis más instrucciones: https://programminghistorian.org/es/guia-para-autores#contesta

Si durante la reescritura, encontráis alguna contradicción entre las tres revisiones, por favor, escribidnos por aquí y tomaremos una decisión consensuada.

¿Creéis que podéis tener listo el tutorial antes del 12 de abril? Una vez tengáis el tutorial terminado, por favor, escribidnos por aquí para que se inicie el proceso de publicación. Gracias.

**Comment by apicon** [comment]
@rivaquiroga, @arojascastro y @editio agradecemos sus valiosas revisiones.
Junto a @mdcs87 no encontramos retomando el tutorial.
Seguro lo resolveremos antes del 12 de abril. 
Saludos!

**Comment by apicon** [comment]
Hola, @arojascastro y @rivaquiroga  
Junto a @mdcs87 , tenemos un duda.
Al realizar la correspondiente actualización, desde el editor de Github, solo me da la opción de "Propose file change" y no logro ver los cambio realizados. Por el contrario, el perfil de Miguel tiene otra opción y muestra los cambios al instantes.
Quedamos atentos.

**Comment by arojascastro** [comment]
No acabo de entender el problema... os referís a estos cambios? https://github.com/programminghistorian/ph-submissions/commits/gh-pages/es/lecciones/introduccion-map-warper.md V

Veo que hicisteis modificaciones hace seis horas...

**Comment by mdcs87** [comment]
@arojascastro Gracias por tu respuesta. En efecto, nos confirmas que sólo los cambios que yo realizó están siendo incorporados. En ese caso, te pregunto es posible revisar los persimos de edición para que @apicon pueda hacer cambios que queden incorporados. Nuevamente gracias.

**Comment by rivaquiroga** [comment]
Como por la diferencia horaria Antonio probablemente no les pueda responder hasta mañana, trataré de ayudar yo por ahora. 
@apicon, revisé los permisos y en el repositorio aparece que la invitación a editar te fue enviada, pero que aún no la aceptas. La reenvié nuevamente. Sugiero que chequees tu carpeta de _spam_ en caso de que se haya ido para allá.

**Comment by apicon** [comment]
@rivaquiroga, encontré en _spam_ una invitación pasada, la acepté, pero al editar me sigue registrado el siguiente mensaje: "You’re editing a file in a project you don’t have write access to. Submitting a change to this file will write it to a new branch in your fork apicon/ph-submissions, so you can send a pull request."

**Comment by rivaquiroga** [comment]
¡Ahora ni siquiera me apareces en la lista de miembros!
Te acabo de agregar de nuevo, así que deberías haber recibido una nueva invitación. Esperemos que esta vez resulte :crossed_fingers:. ¡Estaré atenta!

**Comment by apicon** [comment]
¡Hecho!
Gracias @rivaquiroga.

**Comment by arojascastro** [comment]
¡Gracias @rivaquiroga ! Quedamos a la espera de los cambios para publicar lo antes posible.

**Comment by arojascastro** [comment]
Hola, alguna novedad? Me gustaría publicar pronto :) 

Además de los cambios, necesitaré un breve texto biográfico de ambos autores. 

Gracias

**Comment by arojascastro** [comment]
Por mi parte, cuando tenga los cambios de los autores, seguiré con:
 
- [x] Crea una biografía para el autor
- [x] Agrega una tabla de contenidos a la lección
- [x] Agrega metadatos YAML al archivo de la lección
- [ ] Busca una imagen que represente la lección
- [ ] Informa al jefe de redacción para publicar
- [ ] Incorpora tu lección en nuestro Twitter bot
- [ ] Da las gracias a todo el mundo y difunde el tutorial

**Comment by arojascastro** [comment]
Hola @apicon @mdcs87 nos podéis dar una fecha aproximada de cuándo estará lista la lección? Ya queda muy poco, solo un último esfuerzo. Muchas gracias.

**Comment by mdcs87** [comment]
Hola @arojascastro, te presentamos nuestras excusas por lo tardío de la respuesta. @apicon y yo hemos estado bastante ocupados con la transición a la docencia virtual acá en Colombia. Tras discutirlo, acordamos que una fecha realista para enviar nuestra versión final sería Junio 16. Quedamos atentos.

**Comment by arojascastro** [comment]
Muy bien. Muchas gracias. Quedamos a la espera hasta el 16 de junio.

**Comment by arojascastro** [comment]
Hola @apicon y @mdcs87 alguna novedad? os recuerdo que necesito vuestras bios también. Gracias.

**Comment by apicon** [comment]
Hola @arojascastro , ya estamos por cerrarlo, en el transcurso de la semana lo confirmamos y enviamos las bios. Saludos.

**Comment by apicon** [comment]
Hola @arojascastro @rivaquiroga @mariajoafana @editio 
Después de tanto confirmamos el cierre de la edición. Agradecemos mucho el tiempo y el trabajo de ustedes.
Quedamos atentos a todo.

Bios:
Anthony Picón Rodríguez, investigador del Laboratorio Digital de Arquitectura y Urbanismo de la Universidad Nacional de Colombia, bibliotecario de la Mapoteca Digital en la Biblioteca Nacional de Colombia y gestor de la red Razón Cartográfica.  
https://orcid.org/0000-0001-6765-4146

Miguel Cuadros, Historiador, Universidad Industrial de de Santander. Master of Arts in History, State University of New York (Estados Unidos). Cuento con experiencia docente e investigativa en temas relacionados con la cartografía y el conocimiento geográfico. Docente cátedra en la Universidad Industrial de Santander,

**Comment by mdcs87** [comment]
Gracias por sus aportes y por la paciencia con los tiempos.

**Comment by arojascastro** [comment]
Muchas gracias a todos! Completo mis tareas y aviso a @rivaquiroga cuando esté listo! Prometo hacerlo esta semana.

**Comment by arojascastro** [comment]
Hola @rivaquiroga creo que ya podemos intentar incorporar la lección a Jekyll en https://github.com/programminghistorian/jekyll/pull/1845

**Comment by rivaquiroga** [comment]
¡Muchas gracias a todos por su trabajo! Inciaré ahora el proceso de solicitud del DOI para la lección. Esto toma entre 1 y 2 días hábiles, así que lo más probable es que el martes por la tarde esté lista la publicación

**Comment by rivaquiroga** [comment]
La lección ya está publicada: https://doi.org/10.46430/phes0048

¡Muchas gracias a todos por su trabajo!

**Comment by arojascastro** [comment]
Muchas gracias a todos! @rivaquiroga una duda: quién incluye la lección al Twitter bot?

**Comment by rivaquiroga** [comment]
Tú como editor. Luego de eso, solo queda que lo anuncies por Twitter y celebrar.

**Comment by rivaquiroga** [comment]
Miguel en Twitter es @mdcs87 (igual que acá).
No estoy segura si Anthony tiene una cuenta.

**Comment by arojascastro** [comment]
Añadido al Bot y difundido en Twitter! Gracias todos <3

**Comment by rivaquiroga** [comment]
@mdcs87, @apicon, uno de los enlaces que incluyeron en su lección no se encuentra ya disponible: https://cienciassociales.uniandes.edu.co/historia-geografia/mapa-paisajes-coloniales. ¿Saben qué pasó con ese recurso o si está disponible en otra url?
Por el momento cambiamos el enlace al de la versión que estaba en Web Archive para que el sitio web de PH siguiera funcionando sin problemas.

**Comment by mariajoafana** [comment]
Recién se republicó actualizado acá: https://paisajescoloniales.com/
Ya lo corrijo en el tutorial
