### ISSUE TITLE
Ticket de revisión - "Análisis de red temporal con R"

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#218]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción "Análisis de red temporal con R" por parte de @jenniferisasi  . Esta traducción se encuentra en estos momentos en fase de revisión por parte de @ajspadial y @SirRoderickUsher puede leerse en:

## Texto

http://programminghistorian.github.io/ph-submissions/es/traducciones/analisis_temporal_red

## CSV e imágenes

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/analisis_temporal_red

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](https://programminghistorian.org/es/guia-para-revisores#traducciones) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Hola @jenniferisasi no he encontrado las imágenes de esta traducción. ¿Has modificado alguna? En tal caso, ¿dónde las has puesto?

**Comment by jenniferisasi** [comment]
¡Gracias @arojascastro! He "cambiado" los nombres de los ejes en los gráficos 2 y 3. Y voy a revisar los CSV porque creo que también los modifiqué algo (ya en noviembre). Los subo a la carpeta correspondiente en cuanto pueda. 

Update: Listo. Están en la carpeta de assets.

**Comment by arojascastro** [comment]
Gracias @jenniferisasi y perdona la demora; voy buscando dos revisores externos.

**Comment by arojascastro** [comment]
He enviado un email hoy a Gabriela Elgarrista proponiéndole la revisión de este tutorial; estamos a la espera.

**Comment by ajspadial** [comment]
Pero ¿es revisión por pares, verdad? O sea, lo revisamos los dos ¿Cierto?

El 25 de febrero de 2019 14:05:21 CET, Antonio Rojas Castro <notifications@github.com> escribió:
>He enviado un email hoy a Gabriela Elgarrista proponiéndole la revisión
>de este tutorial; estamos a la espera.>
>>
>-- >
>You are receiving this because you were mentioned.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/programminghistorian/ph-submissions/issues/218#issuecomment-467003727

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by arojascastro** [comment]
Sí, sí, si es posible sí. Así que adelante tú y Gabriela (I hope).

**Comment by arojascastro** [comment]
Ya tenemos segunda revisora - Gabriela Elgarrista (@SirRoderickUsher).

Por favor, leed la lección y publicad vuestros comentarios aquí mismo. Tened en cuenta nuestra [guía para revisores](https://programminghistorian.org/es/guia-para-revisores). 

Sería genial si pudiéramos tener la revisión lista a finales de marzo. Si es antes, mejor :)

**Comment by ghost** [comment]
Hola @arojascastro,
Estoy mirando la traducción, ya empiezo a corregirlo. Trataré de terminarlo lo antes posible.

**Comment by arojascastro** [comment]
Gracias @SirRoderickUsher - solo recordar que el autor introducirá los cambios y sugerencias o aclaraciones; el trabajo del revisor consiste en comentar aquí lo que crea oportuno para mejorar la lección. Por favor, enviad vuestros comentarios antes de abril.

**Comment by ajspadial** [comment]
Párrafo 1. 
- Mejor "Sociedad Religiosa de **los** Amigos".
- En el mismo párrafo dice "diseñadores de impresión". No sé suficiente, pero me suena raro. Yo creo que debe haber otra palabra en castellano para esa profesión.  

Párrafo 2.
- " un papel central alto", creo que es mejor "un protagonismo alto"  

Párrafo 3.
- "Análisis de redes temporal" o "Análsis temporal de redes". La misma propuesta en "Análisis de redes sociales temporal" o "Análisis temporal de redes sociales". Con la decisión que se tome comprobar en el resto del texto  

Párrafo 4
- Al final dice "un área en que nuestra disciplina puede en realidad sugerir nuevas direcciones de análisis". Me resulta un poco confuso. Propongo "un área en la que nuestra disciplina puede aportar nuevas aproximaciones en el análisis temporal de redes"  

Párrafo 6
- Es más literal "Los tipos datos necesarios para el modelado de una red temporal"  

Párrafo 9
- Dice "o sna", pondría "(sna)" sin más. O ", sna, " como en el párrafo siguiente

Estos son mis comentarios hasta el Párrafo 13. Mañana sigo otro rato.

**Comment by ajspadial** [comment]
Y aquí va el resto de mi revisión

Párrafo 16
* A partir de este párrafo se utiliza el término _vínculo_ (casi siempre por _edge_). Creo que en _enlace_ es un término más adecuado

Párrafo 18
* "Origen" y "destino" es preferible a "emisor" y "receptor". 

Párrafo 19
* Introduce el término "arista". Yo mantendría "enlace" (o "vínculo" si se opta por esa opción).

Párrafo 20
* Debería decir "censuraremos", no "censoraremos"

Párrafo 31
* No se ve la imagen.

Párrafo 61
* Debería decir "epidemiológico", no "epidemológico"

Párrafo 83
* En español, creo, Interfaz Gráfica de Usuario es un término muy técnico. Yo usaría "interfaz gráfica" en minúscula para ese caso.

Por último, como nota general, se ha traducido _you_ como segunda persona del singular, y yo creo que en español es más frecuente usar la segunda persona del plural en este tipo de textos: "espero que os haya gustado", etc. De todos modos, el texto se entiende perfectamente y no recomendo cambiarlo por el esfuerzo que supondría.

**Comment by ajspadial** [comment]
Esta tarde o mañana echaré un vistazo a la parte técnica, ejecutando los _scripts_ y os comento si veo cualquier cosa.

**Comment by jenniferisasi** [comment]
Gracias @ajspadial. Iré mirando las sugerencias de cambio y editando el texto durante estos días.

**Comment by jenniferisasi** [comment]
Por párrafos:
1: He cambiado diseñadores de impresión por diseñadores de medios impresos.
16 y 19: Los términos enlace, vínculo y arista son sinónimos para la traducción de *edge* y se utilizan aquí los tres por varios motivos: primero, evitar repetición y, segundo, familiarizar al usuario con la terminología que se usa en general. 
83: Le quito las mayúsculas (se me ha pegado la normal del inglés) pero lo dejo completo porque es su nombre completo. 

He incorporado todo lo demás. Gracias por ver los errores @ajspadial. Y la verdad que esta traducción fue complicada

**Comment by arojascastro** [comment]
Ok, muchas gracias a los dos. Esperamos la revisión de @SirRoderickUsher pronto; luego yo haré una revisión final y publicaremos lo antes posible.

**Comment by ghost** [comment]
Hola,
aquí van mis correcciones y sugerencias. Excelente tutorial.
[Editado para corregir la numeración de los párrafos].

Cualquier cosa no dudéis en preguntarme.

*Introducción*

¶1
- modelar datos humanísticos : ¿datos de ciencias humanas/datos de humanidades? 
- Religión : religión
- Sociedad Religiosa de Amigos : ¿cuáqueros? Este nombre me resulta más familiar.
- historiador/a de Arte : historiador del arte (de +el ) minúscula

¶2
- disminuir : ¿encogerse?
- alto : destacado
- - un día, un año o una década - carácter incorrecto : usar rayas al comienzo y al final, no guiones

¶3
- ¿desarrollar todas las abreviaturas en inglés?

¶4
- epidemología falta una i : epidemiología 
- frase “Por estas razones...” repetición de tres palabras homónimas : el primer y el último cómo/como son necesarios, el segundo no. Sugerencia : como en la técnica particular que permite alcanzar ….
- resalta : ¿subraya?
- infelices simplificaciones : ¿simplificaciones poco afortunadas?

¶6
- El tipo : ¿Los tipos?
- a nivel de red y de nodos : ¿a nivel de la red y a nivel de los nodos?

*Prerequisitos*
- Título: falta una r Prerrequisitos. Ej: vicerrector.

¶7
- conocimiento básico con : se tiene conocimiento de algo. Cambiar la preposición 

¶10
- Como visualizaciones dinámicas de redes temporales : Acrónimo de visualizaciones dinámicas de redes …

¶15
- Una lista de nodos, la cual contiene cada nodo : Una lista que contiene todos los nodos (o vértices …
- Cambiar los guiones por rayas en la frase  “o vértice - términos que vamos a usar de forma indistinta en este tutorial”
- la cual contiene cada conexión : que contiene cada una de las conexiones

¶16
- Las dos últimas frases son poco claras.
Se establecieron los vínculos por la contribución de dos o más talleres a un manuscrito o un grupo de manuscritos
Mi proposición (no me satisface demasiado): Cada vínculo conecta uno o varios manuscritos con uno o varios talleres participantes.
- aparecer como : ¿aparecer en? ¿traducirse como?

¶17
- red estática y una temporal: ¿temporal dinámica?

¶19
- una lista de aristas : está perfecto, pero es la primera vez que se designan los vínculos como aristas. La palabra “aristas” no aparece antes y puede confundir al lector menos familiarizado con las redes sociales.
- esperan que tus datos incluyan: ¿presuponen que tus datos incluyen?
- La anteúltima frase está un poco confusa, propongo esta otra solución (no me satisface demasiado). Proposición: Dependiendo de cómo conceptualices tu red, puede que el inicio y el término del intervalo de tiempo que conecta dos nodos sea o relativamente breve o prolongado, en este último caso el comienzo y el final implican una serie de eventos en la relación.

¶20
- duró por un año : duró un año
- no censoraremos nada: no censuraremos nada. La palabra “cesurar” ya apareció al comienzo del párrafo.

¶21
- En la mayoría de análisis de redes estáticas: ¿de los análisis?
- una lista de nodos es una lista simple : ¿es simplemente una lista?

¶22
- el segundo taller abre alrededor : el segundo taller está activo alrededor... “abre” no me parece que sea la palabra correcta. El taller existe independientemente de la colaboración. 
- dándole una “vida” de unos 22,5 años : dándoles un período de vida de unos 22,5 años

¶24
- implica hacer muchas aproximaciones: ¿implica adentrarse en el terreno de la aproximación?
- En este sentido, en realidad es bastante típico: En este sentido, es bastante frecuente... suprimir “en realidad”. Un poco pesado a la lectura, dos expresiones que empiezan por en: En este sentido, en realidad.

¶27
- historiadores de arte : historiadores del arte

¶35
- La función networkDynamic() toma como su primera entrada : ¿argumento en vez de entrada?

¶ 37
- Ahora que hemos creado una red dinámica, ¡podemos convertirla en un gráfico para ver como se ve! : dos puntuaciones seguidas "," y "¡",  eliminar la coma.

¶ 44
- demasiado escasa : demasiado exigua
 
¶46
- cuando empezar : cuándo empezar
- Dependiendo de cómo de grande : Dependiendo de cuán grande

¶47
- hemos dedicido : hemos decidido
- algoritmo de fuerza dirigida conocico :  algoritmo de fuerza dirigida conocido

¶49
- Falta un si en la frase y cambiar “más atrás” por “primer”: Puede que la consola de R Studio muestre algunos mensajes de aviso, pero estos solo especifican que hay valores múltiples en los atributos de los vértices, la función render.d3movie() utiliza el atributo más atrás en el tiempo para cada vértice. 

Proposición : Puede que la consola de R Studio muestre algunos mensajes de aviso, pero estos solo especifican que si hay valores múltiples en los atributos de los vértices, la función render.d3movie() utiliza el primer atributo en el tiempo para cada vértice. 

*Más allá de la bola de pelo*
- Título : después de los dos puntos ¿no debería ir minúscula? Más allá de la bola de pelo: la métrica de redes dinámicas

¶56
- ído: ¿período?

*Pensar en términos temporales: Conjuntos alcanzables*
- Título : después de los dos puntos ¿minúsculas? conjuntos alcanzables

¶60
- analizar propiedas que soloocurren : analizar propiedades que solo ocurren

¶62
- reemplazar los guiones por rayas :  cálculos de centralidad - dependiendo de si un taller
- términos epidemológicos :  términos epidemiológicos

¶70
se debió no solo : se debió no sólo (falta el acento en sólo)

¶78
- trasmisión:  transmisión

*Lecturas complementarias*
¶84 
- En la lista de bibliografía falta un espacio entre el hipervínculo y el paréntesis de "(en inglés)". Se repite en la primera y segunda línea.

*Referencias*
Faltan la referencias 1 a 5.

*Nota*: ¿no hay traducción de “About the author”?

**Comment by arojascastro** [comment]
Muchas gracias @SirRoderickUsher por tus comentarios. Me parece todo muy adecuado; aclaro que la biografía del autor la añadimos los editores más tarde cuando publicamos. Todo tuyo @jenniferisasi -- avísanos cuando estés lista para que le dé un último repaso antes de publicar.

**Comment by jenniferisasi** [comment]
@arojascastro se me había olvidado completamente el aviso de hace 20 días con el resto de cosas por hacer. Me pongo a ello ahora mismo y te aviso en cuanto esté acabada la edición. ¡Gracias! 

Listo. Debo tener una pelea secreta con las notas porque siempre me dan problemas?!?

**Comment by arojascastro** [comment]
Ok, gracias, me lo miro esta semana para publicar pronto.

**Comment by arojascastro** [comment]
Muchas gracias por la excelente traducción. Aquí van algunos comentarios finales:

- 14:  -términos que vamos a usar de forma indistinta en este tutorial) --> falta guion de cierre
- 15: - esto es, que todos los nodos son el mismo tipo de cosa, y lo mismo ocurre con las conexiones. --> falta guion de cierre
- 19: [Nota de la T.: para no censurar se indica con la palabra FALSE, y para censurar con la palabra TRUE]. --> ¿la nota no la pones al final? 
- titulillo de sección: Tomar decisiones complicadas: Convertir datos históricos en un conjunto de datos TNA --> minúscula después de dos puntos
- 37: Esto produce…algo que, de manera decepcionante, se parece a la red estática de más arriba. --> falta espacio tras los puntos suspensivos
- 41: [Nota de la T: Aquí indicamos que no muestre las etiquetas displaylabels]. --> ¿no usas las notas al final? 
- 44: - 10 años, o 1 año, o 1 día. --> falta guion de cierre
- 57: Añadimos xlab= para cambiar la etiqueta del eje-x o eje horizontal [N. de la T.]. --> falta tu nota?
- 62: -dependiendo de si un taller vino a ocupar una posición central en la red cerca del comienzo o del final del período que estamos observando, el impacto real que podría haber tenido en la comunidad es totalmente diferente.  --> falta guion de cierre, pero quizás sería mejor usar una coma, por ejemplo: El tamaño de estos conjuntos añade información importante a los cálculos de centralidad, dependiendo de si un taller vino a ocupar una posición central en la red cerca del comienzo o del final del período que estamos observando, el impacto real que podría haber tenido en la comunidad es totalmente diferente.
- revisión general: hay varias notas, pero al final de la lección solo aparece la nota número 6

Lamento la demora :)

**Comment by jenniferisasi** [comment]
Gracias @arojascastro por notar, por lo que veo, errores de puntuación (debido a mi entrenamiento en escribir en inglés, tal cual). Ahora, lo de las notas sí que es un misterio... ¿a dónde se han ido? Lo arreglo hoy mismo.

**Comment by jenniferisasi** [comment]
Dejo un comentario antes de terminar: Las notas de traducción que dejo en el texto mismo son, por lo general, notas aclaratorias sobre la terminología que se va usando y creo que merece que estén ahí mismo; cuando añado una nota de traducción sobre el contexto (histórico) de un conjunto de datos la añado como nota a pie de página, pues no es 100% necesaria para continuar. No sé si me explico, ¿qué opinas tú @arojascastro?

**Comment by arojascastro** [comment]
Vale, me parece bien. Me lo miro en breve y publicamos.

**Comment by arojascastro** [comment]
Perdona, @SirRoderickUsher me podrías confirmar qué nombre quieres usar como revisor? Ya estoy preparando la publicación. Gracias.

**Comment by arojascastro** [comment]
Y @ajspadial veo que a veces sales como Antonio Jesús Sánchez Padial y otras como Antonio Sánchez-Padial - ¿qué prefieres?

**Comment by ajspadial** [comment]
La segunda Sánchez-Padial. Revisaré las incoherencias y haré un pull request. Gracias, Antonio.




Obtener Outlook para Android







On Tue, Apr 23, 2019 at 6:24 PM +0200, "Antonio Rojas Castro" <notifications@github.com> wrote:












Y @ajspadial veo que a veces sales como Antonio Jesús Sánchez Padial y otras como Antonio Sánchez-Padial - ¿qué prefieres?

**Comment by arojascastro** [comment]
Muchas gracias @ajspadial, espero ese pull request - ahora solo necesito saber el nombre de @SirRoderickUsher

**Comment by arojascastro** [comment]
Hola, @SirRoderickUsher - *Isabelle Gribomont* te va bien?

**Comment by ghost** [comment]
Perdonad la tardanza, tuve problemas con el disco ordenador.
G. Elgarrista me conviene.

**Comment by arojascastro** [comment]
Gracias. Normalmente ponemos el nombre completo... ¿Te importaría compartirlo? Gracias.

**Comment by ghost** [comment]
Entonces el nombre completo.

**Comment by arojascastro** [comment]
De acuerdo, pero, ¿cuál es? Gracias.

**Comment by ghost** [comment]
Gabriela Elgarrista

**Comment by arojascastro** [comment]
¡Gracias!

**Comment by arojascastro** [comment]
Publicado: https://programminghistorian.org/es/lecciones/analisis-temporal-red

Gracias a todos.
