### ISSUE TITLE
Proposed Lesson - Evaluating Topic Models

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/ph-submissions#220]
The Programming Historian has received the following proposal for a lesson on 'Evaluating Topic Models' by @akhenrichs  The proposed learning outcomes of the lesson are:
     
- explore why scholars choose to make topic models.
- explain the logic behind two popular methods for making topic models.
- enable readers identify and evaluate the results of those methods.
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 22 April 2019. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 22 May 2019, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @drjwbaker @spapastamkou is shadowing the editorial process. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

**Comment by akhenrichs** [comment]
I have drafted the full lesson on topic modeling thus far, and believe the review process could be brought forward by at least 1 month (if that works with schedules for reviewers and editors). My main concerns are:
1. The completeness of the lesson (is everything included that will help novice topic modelers?)
2. Does the explanation of the logic behind topic modeling contribute to the goals of the lesson?
3. Is the balance between "explanation of process" and "evaluation of product" adequate?
4. Finally, the explanation uses English as a touchstone; is this too exclusionary for a global audience?

**Comment by drjwbaker** [comment]
@akhenrichs Thanks for commenting on the ticket. Let's keep our discussion here for now (unless something emerges that we'd rather not discuss in public).

1. I've amended the date to 22 April. Which is a Monday. I hope that works. We can always push back to later if needs be, but I'd rather not bring this forward any further because of the time it takes to complete 2 (though if this is quicker than expected, we can).
2. Based on that date, I'll line up some reviewers middle of next month (when I have some time to dedicate to the task).
3. I'll take a look at your draft next week and comment on your concerns.

**Comment by drjwbaker** [comment]
Some comments:

- line 50: "Topic modeling is a popular method for scholars who deal with textual data." I feel that this sentence needs to be an indication of what they are doing with topic models.
- line 72: I have normalised this line to better fit our internationalisation guidelines. Please scan the essay for other example of phrasing that might be made more approachable for international audiences.
- line 82: missing reference to Jockers

On your concerns:

1. Fine with me.
2. It does.
3. Yes, though the prose drifts between a narrative of "you the reader evaluating a topic model" and "you the reader doing topic modelling". I'd like to see this made more consistent, perhaps focusing on the latter, with clear indicating when the lesson is moving to directly advising readers when they are doing topic models.
4. I think we are fine here.

**Comment by akhenrichs** [comment]
Thanks! I can address your comments next week (assuming they should be done before going out to reviewers?). And April 22nd works just fine.

**Comment by drjwbaker** [comment]
@akhenrichs Yes, if you work through gradually now then the lesson will be in a better state to send for review by 22 April. I'll start lining up reviewers mid/late March, so it may will be we can move to review slightly sooner if you are ready. But if you aren't that isn't a problem.

**Comment by akhenrichs** [comment]
Great, I'll get started!

**Comment by drjwbaker** [comment]
With apologies, I neglected to include this important information on the ticket.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by drjwbaker** [comment]
@akhenrichs I have two reviewers lined up for late April. How are the revisions coming along? Anything we can help with?

**Comment by akhenrichs** [comment]
@drjwbaker Going well! In fact, I think I have addressed your comments and am ready for the next step. Because I spent a fair amount of time before the Git ticket was opened, I didn't make any other major changes; the most substantial was clarifying the moments when I was discussing *evaluating* the topic models vs *doing* topic modeling. I'm happy to submit the revision now, or wait until closer to the review date. Thanks!

**Comment by drjwbaker** [comment]
@akhenrichs Great job! If you want to merge the revisions when you are ready and tell me when you are ready for review (there is no hurry on this!) I can bring things forward, but not that the reviewers may not be ready as I've indicated to them a mid- to late- April date based on our original timeline.

**Comment by akhenrichs** [comment]
@drjwbaker I have finally merged revisions; apologies for the delay!

**Comment by drjwbaker** [comment]
Okay. Thanks for the revisions. No delay at all. 22 April was our deadline.

**Comment by drjwbaker** [comment]
Closing submission ticket. Open review ticket https://github.com/programminghistorian/ph-submissions/issues/234
