### ISSUE TITLE
Bug in Submission Template

### ISSUE THREAD

**Issue by drjwbaker** [programminghistorian/ph-submissions#221]
The Submission Template still has Ian..

> If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

..whereas the proposal one only has Amanda:

> You can always turn to @amandavisconti if you feel there's a need for an ombudsperson to step in.

If someone can tell me where to look, I can fix this.

**Comment by ZoeLeBlanc** [comment]
You can edit the [ISSUE_TEMPLATE.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/ISSUE_TEMPLATE.md) directly in Github by clicking the pencil button and changing the edits to the template. Both the submission and proposal templates are generated from that markdown file.

**Comment by drjwbaker** [comment]
Thanks @ZoeLeBlanc. Done.
