### ISSUE TITLE
Ticket de relecture de traduction: Comprendre les pages web et le HTML

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#228]
Le Programming Historian en français a reçu la traduction du tutoriel "Understanding Web Pages and HTML" sous le titre "Comprendre les pages web et le HTML" préparée par les soins de @symac. Cette traduction est en cours de relecture et elle est accessible en suivant ce lien:   

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/comprendre-les-pages-web.md

Vous pouvez utiliser la numérotation des lignes fournie dans l'aperçu pour insérer vos commentaires, si cela vous convient. Toutefois, sentez-vous libre de présenter votre relecture comme vous le jugez mieux. 

Le tutoriel original en anglais est accessible ici: https://programminghistorian.org/en/lessons/viewing-html-files

J'assume le rôle de rédactrice en charge du suivi de la procédure de relecture. Dans ce cadre, j'ai  sollicité deux relectures auprès de @inactinique et @peccadille et coordonnerai les échanges qui auront lieu dans cet espace. 

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour l'auteur(e) puisse travailler sur la révision de son texte. Je l'annoncerai sur ce fil quand cette étape aura été atteinte.

Je ferai de mon mieux pour garder la discussion ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers @mpuren et @fdlaramee, si vous avez le sentiment qu'une médiation est nécessaire.        

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (Marie Puren et François Dominic Laramée - http://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by inactinique** [comment]
Bonjour à tous,

Cette première leçon, traduite de l'une des toutes premières écrites notamment par Bill Turkel, est très simple quoique nécessaire pour beaucoup de choses ensuite. Elle s'inscrit dans un ensemble de leçons d'introduction à python, qui formaient l'essentiel de la toute première édition du *programming historian* il y a une dizaine d'année (je crois). Je l'ai évaluée dans ce contexte: elle n'a de sens que si toute la série est traduite.

En conséquence, je n'ai pas grand chose à dire, si ce n'est que nous pourrions adapter les exemples (ici l'Old Bailey Online) à un public francophone. Par exemple, en utilisant Gallica plutôt que l'Old Bailey Online. En expliquant aussi comment indiquer que la page est en Français (attribut lang).

Si seulement une partie de la série est traduite ou si nous voulons en faire quelque chose vraiment centré sur le HTML (plus que sur python), il faudra très largement l'approfondir (parler de CSS, des différentes générations du HTML, des langages de script complémentaires comme javascript) pour en faire une leçon autonome.

Frédéric

**Comment by spapastamkou** [comment]
Merci beaucoup, @inactinique, pour la relecture et tes remarques. Etant actuellement en déplacement, je reviendrai à ce sujet très prochainement.

**Comment by spapastamkou** [comment]
Merci infiniment à toi, @inactinique, pour ta relecture et tes suggestions. Nous attendons également la deuxième, prévue d'arriver après la fin de ce mois-ci, et nous ferons ensuite le point avec @symac pour finaliser le texte.

**Comment by spapastamkou** [comment]
Bonjour @peccadille, avez-vous pu avancer un peu avec la relecture de la traduction? Merci à vous.

**Comment by symac** [comment]
Je ne reprends que maintenant mes tickets en retard. Merci @inactinique pour cette première relecture. Concernant l'exemple utilisé, j'étais parti sur le principe de faire une traduction qui reste le plus fidèle possible au texte original mais si la politique de PH^fr est d'adapter les leçons dans le cadre des traductions je m'y collerai pas de soucis.

Pour le contenu de la leçon, la structure de PH permet de mettre en place des séries, peut-être que ce serait la solution pour éviter de faire une leçon interminable tout en couvrant les différents sujets que tu évoques.

**Comment by spapastamkou** [comment]
Chère @peccadille, pensez-vous pouvoir nous faire parvenir votre relecture sous forme de commentaire ici afin d'aller en avant avec les modifications finales et la publication de la leçon? Un grand merci d'avance!

**Comment by spapastamkou** [comment]
Chère @peccadille, je me permets de revenir au sujet de la relecture de la leçon. Je vous remercie par avance. si vous êtes en mesure de nous donner des indications sur l'état de son avancement.  En absence de réponse d'ici à la fin du mois en cours, je serai obligée de solliciter une troisième relecture afin d'avancer avec la publication du tutoriel. Merci pour votre compréhension.

**Comment by fdlaramee** [comment]
@spapastamkou Y a-t-il du nouveau dans ce dossier? Je peux aisément effectuer une troisième relecture si tu en as besoin.

**Comment by spapastamkou** [comment]
J'avais pris, plus ou moins, la décision de publier avec une seule
relecture, seulement j'attendais en finir avec la publication de deux
autres leçons, qui sont en cours. SI tu as la possibilité, je te saurais
gré, merci, François Dominic.

**Comment by fdlaramee** [comment]
@spapastamkou D'accord, je m'en charge dès demain.

**Comment by fdlaramee** [comment]
Merci @symac pour cette traduction d'excellente qualité. Je n'ai que quelques très brèves suggestions à formuler, dont certaines s'adressent surtout à @spapastamkou pour les paramètres d'édition:

Ligne 20: L’année de la traduction dans l’en-tête de l’article devrait être 2019 plutôt que 2018!

Lignes 36-37: Hypertext Markup Language devrait-il apparaître en italique?

Ligne 41: L’entrée de menu sous Firefox s’intitule maintenant « Développement web » plutôt que « Développement ». 

Ligne 42: Il vaut peut-être la peine d’ajouter que la combinaison de touches sur Mac est CMD-U plutôt que CTRL-U.

Ligne 69: Le bout de texte sur l’ouvrage de Cohen et Rosenzweig est à moitié traduit, ce qui est un peu bizarre. J’irais plutôt avec « … dans l’ouvrage <em> Digital History </em> de Cohen et Rosenzweig, par exemple… » 

Voilà!

**Comment by spapastamkou** [comment]
Merci @fdlaramee pour la relecture et les suggestions utiles. Portant essentiellement sur la forme, plutôt que sur le fond du travail de traduction effectué par @symac, j'intégrerai les modifications moi-même dans la version finale avant publication. Pour l'histoire, la traduction initiale a bel et bien été effectuée en 2018 sur une initiative de @symac, bien avant qu'une version FR du PH soit lancée, qu'il a mis à la disposition de l'équipe tout de suite. Mais il est vrai que pour la publication il faudra signaler une date plus récente, qui sera celle du dépôt ici. Merci à vous tous, @symac, @inactinique et @fdlaramee pour votre contribution.

**Comment by symac** [comment]
Merci @fdlaramee pour la relecture et merci @spapastamkou pour l'intégration des modifications suggérées !
