### ISSUE TITLE
create directory for FR non-finished translated lessons

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#230]
This question is for @mdlincoln and concerns all @programminghistorian/french-team  
I am looking for a place to stock (students) translations that have been provided to the @programminghistorian/french-team but are not completely ready for review: these texts are either not finished or need previous corrections to be done by one of the members of the team who will decide then to be their editor. To assure common access to these docs, is it possible for us to create a subdirectory in https://github.com/programminghistorian/ph-submissions/tree/gh-pages/fr/traductions to upload them? 
In this new subdirectory, we would stock the texts as we received them; each of us could thus have access to them and once the text is ready for reviews, it would be transferred to the main directory for translated lessons under review. How does that sound?

**Comment by acrymble** [comment]
I think the appropriate place is just to add them as submissions as normal. There are a lot of lessons in progress in those folders. I don't think it needs new infrastructure.

**Comment by spapastamkou** [comment]
Ok, this allows to keep things simple. I will upload the files once properly renamed. Thank you @acrymble !
