### ISSUE TITLE
Ticket de relecture de traduction: Introduction à la stylométrie avec Python

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#231]
Le Programming Historian en français a reçu la traduction du tutoriel "Introduction to Stylometry with Python" sous le titre "Introduction à la stylométrie avec Python" préparée par les soins de @fdlaramee . Cette traduction est en cours de relecture et elle est accessible en suivant ce lien:   

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/introduction-a-la-stylometrie-avec-python.md

Vous pouvez utiliser la numérotation des lignes fournie dans l'aperçu pour insérer vos commentaires, si cela vous convient. Toutefois, sentez-vous libre de présenter votre relecture comme vous le jugez mieux. 

Le tutoriel original en anglais est accessible ici: https://programminghistorian.org/en/lessons/introduction-to-stylometry-with-python

J'assume le rôle de rédactrice en charge du suivi de la procédure de relecture. Dans ce cadre, j'ai  sollicité deux relectures auprès de @isag91 et @FMezard et coordonnerai les échanges qui auront lieu dans cet espace. 

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour l'auteur(e) puisse travailler sur la révision de son texte. Je l'annoncerai sur ce fil quand cette étape aura été atteinte.

Je ferai de mon mieux pour garder la discussion ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers @mpuren, si vous avez le sentiment qu'une médiation est nécessaire.        

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (Marie Puren et François Dominic Laramée - http://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by isag91** [comment]
J’ai beaucoup aimé ce tutoriel. Je l’ai trouvé clair et intéressant, et je n'ai rien à suggérer au niveau du coutenu ou de la structure. J’ai simplement quelques suggestions pour améliorer la formulation. Il s’agit souvent de rendre la phrase plus légère ou plus courte et d’éviter les répétitions ou les anglicismes. Je liste aussi quelques erreurs typographiques.

**Formulation**

36: ‘reconnu’ -> ‘célèbre’
37: ‘les longs blocs de texte à multiples clauses’ -> ‘les phrases complexes comportant plusieurs propositions’
’38: ‘et les autres signes de ponctuation’ ->  ‘et autres signes de ponctuation’
40: ", par les auteurs": supprimer
‘indépendante du sujet à l'étude’ -> ‘indépendante du sujet abordé’
‘sont très avantageuses pour’ -> ‘favorable à’
‘Les mots-outils ont aussi’ -> ‘les mots-outils ont également’ (répétition)
42: ‘Par exemple, de nombreuses recherches ont étudié’ -> ‘Par exemple, on a beaucoup étudié’
‘des chansons composées’ -> ‘écrites’
(ajout d’une virgule après 1960).
44: ‘ll est parfois possible de découvrir l'identité de l'auteur d'un texte en mesurant certaines caractéristiques de ce texte, comme la longueur moyenne des phrases ou le rapport entre le nombre d'articles définis et indéfinis, et en comparant ces mesures avec celles observées dans des textes dont les auteurs sont connus.’ -> ‘ll est parfois possible de découvrir l'identité de l'auteur d'un texte en mesurant certaines caractéristiques de ce texte, comme la longueur moyenne des phrases ou le rapport entre le nombre d'articles définis et indéfinis. Ces mesures sont ensuite comparées avec celles observées dans des textes dont les auteurs sont connus.’ 
51: ‘en langage de programmation’ -> ‘dans le langage de programmation’
52: ‘un populaire module Python’ -> ‘un module Python populaire’
56: ‘Veuillez aussi noter’ -> ‘Notez aussi’
‘dans le présent tutoriel’ -> ‘dans ce tutoriel’ (répétition)
87: ‘au domaine’ -> ‘dans le domaine’
91: ‘Secrétaire du Trésor des États-Unis’ -> ‘Secrétaire du Trésor (ministre des finances) des États-Unis’
92: ‘qui est parfois surnommé’ -> ‘parfois surnommé’
99: ‘soit révélée’ -> ‘soit révélée,’
101: ‘Troisièmement’ -> ‘Troisièmement,’
‘Et selon le quolibet de Mosteller,’ -> ‘Enfin, comme ironise Mosteller,’
‘ni l'un, ni l'autre’ -> ‘ni l’un ni l’autre’
‘quand un mot long ferait l'affaire’ -> ‘quand un mot long faisait l'affaire’
103: ‘_his_ (son)’ -> ‘_his_ (son, sa)’
‘les chances que Madison ait été l'auteur’ -> ‘les chances que Madison en ait été l'auteur’
105: ‘la répartition du Fédéraliste’ -> ‘la répartition des articles du Fédéraliste en fonction de leur(s) auteur(s)’
‘Certains des résultats’ -> ‘Certains résultats’
‘et que Hamilton et Madison’ -> ‘. En effet, Hamilton et Madison’
109: ‘démontrer’ -> ‘expliquer’/’décrire’ (anglicisme)
‘différentes.’  -> ‘différentes:’
117, 118 et 119: ‘qui ont certainement été écrits par X’ -> ‘dont l'attribution à X est certaine’
(certainement peut signifier ‘très probablement’, plutôt que ‘avec certitude’).
150: ‘pour créer une longue liste des mots’ -> ‘pour créer la longue liste des mots ’
165: ‘emmagasiner’ -> ‘stocker’/’enregistrer’
‘ dont les clés seront formées par les noms des auteurs tandis que les valeurs contiendront tout le texte des articles de ces auteurs. ->
‘dont les six clés sont celles du dictionnaire 'articles' ci-dessus et dont les valeurs sont les six corpus correspondants. 
190: ‘et que l'on traçait les résultats sur un graphe, les courbes devraient être
similaires peu importe les parties du roman que l'on avait choisies.’
-> ‘et que l'on traçait les graphes des résultats, les courbes seraient similaires quelles que soient les parties du roman choisies.’
249: ‘(À condition que’ -> ‘(Cela suppose que’
264: ‘peu importe la méthode stylométrique que l'on emploie’ -> ‘quelle que soit la méthode stylométrique employée’
‘ont suggéré des valeurs allant de 100 à 1000 des mots les plus fréquents dans le corpus à l'étude;’ -> ‘ont suggéré pour n des valeurs allant de 100 à 1000;’
372: ‘Aucune intention néfaste’ -> ‘Aucune intention frauduleuse’
374: ‘Puisque Delta fonctionne’ -> ‘Puisque la méthode Delta fonctionne’
‘et ceux qui sont contestés par ces deux derniers’ -> ‘et ceux qui sont revendiqués par ces deux derniers’ OU ‘et ceux qui sont contestés entre ces deux derniers’
‘Nous nous attendons à ce que Delta affirme’ -> ‘Nous nous attendons à ce que la méthode Delta affirme’
564: ‘la reconnaissance des formes’ -> ‘la reconnaissance des motifs’
566: ‘était beaucoup plus régulière’ -> ‘était beaucoup moins imprévisible’ (peut-être? ‘Régulière’ m’a fait pensé que la structure elle-même était régulière, ce qui n’est pas ce qui est dit dans la version anglaise).
567: ‘techniques d'apprentissage automatique supervisées’ -> ‘techniques d'apprentissage automatique supervisé’
575 et 577: ‘sommaire’ -> ‘résumé’/’étude sommaire’
581: ‘disposer d'une installation de R’ -> ‘avoir installé R’
585: ‘données d'océrisation’ -> ‘données obtenues par reconnaissance optique de caractères’.

**Typos**

56: ‘tutorial’ -> ‘tutoriel’
97: ‘pseudodyme’ -> ‘pseudonyme’
99: ‘Hamitlon’ -> ‘Hamilton’
105: ‘résole’ -> ‘résolue’
‘co-rédiré’ -> ‘co-rédigé’ 
152: supprimer cette phrase (j’imagine que c’est une erreur)
192: ‘utiliseront’ -> ‘utiliserons’
228: ‘fitre’ -> ‘filtre’
243: ‘Hamlton’ -> ‘Hamilton’
258: ‘divisé par les nombres d'occurrences attendus’ -> ‘divisés par les nombres d'occurrences attendus’
264: siignificatives -> significatives
294: ‘Calculons maintenant’ -> ‘Comparons maintenant’
301: ’deux échantillons aléatoires tirées’ -> ’deux échantillons aléatoires tirés’ 
332: losqu'un -> ‘lorsqu'un’
339: ‘Une note au sujet de l'étiquetage grammaticalement’ -> ‘Une note au sujet de l'étiquetage grammatical’

- Un détail, mais partout où le mot “équation” est utilisé, je le remplacerais par “formule de calcul”. Une équation est une égalité contenant une (parfois plusieurs) inconnue(s) dont il faut trouver la ou les valeur(s), appelées solution(s) de l'équation. Une formule de calcul est une égalité dont le membre de gauche est l'objet à calculer et dont le membre de droite est l'expression décrivant le calcul nécessaire.
- Je remplacerais également “pointage Delta” par “cote Delta”. Mais peut-être il y a-t'il une raison à laquelle je n’ai pas pensé pour avoir choisi le mot “pointage”.
- La notation de la figure 8 ne me semble pas tout à fait correcte. Je pense que “c,i” et "t,i" devraient remplacer "c(i)" et "t(i)". Si on écrit A avec c,i en souscrit, on suggère que A dépend de c (corpus) et de i (trait). En prenant toutes les valeurs possibles pour c et i, les différents A forment un 'nested' dictionary, ou tableau à deux dimensions. La notation c(i) désignerait plutôt une valeur qu'une fonction (ou loi) c associe à une valeur i. 

J’ai remarqué deux petites coquilles dans la version anglaise:
the author or a famous -> the author of a famous
whose mentorship in always invaluable -> whose mentorship is always invaluable.

**Comment by spapastamkou** [comment]
Concernant le #235 et les suggestions de @FMezard, je viens de répondre directement dans le ticket du PR. 

Concernant les suggestions de @isag91, tout d'abord un grand merci pour la relecture détaillée et les suggestions pointues. Pour les propositions qui portent sur la formulation, même commentaire de ma part que dans #235: pour ce qui relève des différences entre le français métropolitain et le québécois, il me semble judicieux de laisser le choix à @fdlaramee pour décider quelles suggestions il souhaite suivre et faire, au cas où, des modifications. Merci d'avoir signalé les typos! @fdlaramee, pour ton information, @isag ne sera pas disponible dans l'immédiat, au cas où des échanges seraient nécessaires. Si besoin d'échanger entre vous, on peut revoir cela dans quelques semaines. Merci beaucoup!

**Comment by spapastamkou** [comment]
Note pour moi-même: la leçon [évoque](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/introduction-a-la-stylometrie-avec-python.md#lectures-pr%C3%A9alables) une autre leçon dont la traduction est en cours d'évaluation: "Working with Text Files in Python" (Travailler avec des fichiers texte en python), cf. #232. Si jamais cette 2e leçon est publiée à temps, il faudra mettre à jour le texte et le lien de ce tutoriel-ci.

**Comment by fdlaramee** [comment]
@isag91 Merci beaucoup; je lirai vos recommandations avec beaucoup d'intérêt le plus rapidement possible. 

@spapastamkou Si tout se passe bien, je devrais pouvoir compléter les révisions d'ici 7 à 10 jours.

**Comment by fdlaramee** [comment]
@spapastamkou Les révisions sont faites et intégrées dans le fichier https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/introduction-a-la-stylometrie-avec-python.md

J'ai accepté presque toutes les recommandations des deux lectrices. Lorsque certaines recommandations étaient contradictoires, j'ai tranché. 

Je n'ai cependant pas changé la formule du Delta de Burrows à la figure 8, dont la formulation est une adaptation (il me semble) de ce qui se trouvait dans l'article original. Cette formule est également celle qui se trouve dans le tutoriel en anglais depuis l'année dernière.

Merci,
FDL

**Comment by spapastamkou** [comment]
Merci beaucoup, @fdlaramee! Et merci bien pour votre travail de relecture, @isag91 et @FMezard. Je ferai le nécessaire pour publier la leçon au début de la semaine prochaine et je vous tiens au courant.

**Comment by spapastamkou** [comment]
Je viens d'effectuer quelques modifications dans le fichier, notamment pour fermer trois parenthèses de liens et corriger une petite faute d'orthographe https://github.com/programminghistorian/ph-submissions/commit/cebf39515e8f181419a73a7fc37bab9baea1d356

**Comment by fdlaramee** [comment]
Parfait, merci @spapastamkou !  À la longue, on ne voit plus clair dans ces damnés fichiers! 😀

**Comment by spapastamkou** [comment]
@fdlaramee avec plaisir:)

**Comment by spapastamkou** [comment]
Ce tutoriel étant en cours de publication, je ferme ce ticket.

**Comment by acrymble** [comment]
it's a good idea to leave the ticket open until the lesson is fully published. That way it won't get accidentally forgotten.
