### ISSUE TITLE
Proposed Lesson: Jupyter Notebooks as Argument

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#233]
The Programming Historian has received the following proposal for a lesson on 'Jupyter Notebooks as Historical Argument' by Quinn Dombrowski (@quinnanya). The proposed learning outcomes of the lesson are:
     
- Introduce Jupyter Notebooks and their value as a historical argumentation tool
- Introduce some of the practicalities of starting with Jupyter Notebooks
- Highlight the pedagogical value of Jupyter Notebooks
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 15 June 2019. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 15 June 2019, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @acrymble . If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

**Comment by acrymble** [comment]
Just a note that @quinnanya has been in touch and is still working on the text, but hopes to be ready soon.

**Comment by quinnanya** [comment]
Apologies -- looking at this again, I'm seeing the deadline was June 15th, not 30th (as I had filed away in my head, and thought I was getting this in a couple days early)!
I didn't have access to the ph-submissions folder, so I tried to create a pull request here: https://github.com/programminghistorian/ph-submissions/pull/250

**Comment by acrymble** [comment]
I've added you to the submissions repository so you can just upload the files yourself. You should have received an email invite. Let me know if you need help.

**Comment by quinnanya** [comment]
Yup! I just uploaded everything.

**Comment by acrymble** [comment]
I've opened a review ticket: https://github.com/programminghistorian/ph-submissions/issues/251

The discussion will continue there.
