### ISSUE TITLE
Spanish Team: Update Lista de traducción 

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#238]
As per[ #1273](https://github.com/programminghistorian/jekyll/issues/1273) (on jekyll) @arojascastro agreed to update the list of translations for our team. Opening this ticket as a placeholder for the task. 

Antonio, let me know if you already updated the file or if you need help with this task.

**Comment by arojascastro** [comment]
Gracias por el recordatorio. Espero poder hacer esta tarea en los próximos días.

**Comment by arojascastro** [comment]
Hi! I was thinking that @mdlincoln created this concordance table: https://programminghistorian.org/translation-concordance

Maybe we could link to it instead? It is automatically generated. Perhaps there is a way to visualize only lessons (rather than pages) and clean the table a bit. What is your view on this Matthew?

However, we decided not to translate some lessons that are English dependant and this table would not take into account our decision so far. Is there any way to improve it?

**Comment by jenniferisasi** [comment]
I'm reading the code to generate this list and, though I don't know how to write it myself (maybe we could have this as one "challenge" to learn on the technical-team), here is my understanding:
- I believe it's a matter of looking for not all pages but those that have "lesson" on the layout on the YAML, right? 
- We could create two separate tables (in the same page to keep things organized), one for lessons, and another one for the other pages (about, guidelines, etc.), same, by looking in this case only for those that have "blank" in the layout. 

Would it be a workaround for translations we are not doing to include another YAML field, "translation: yes / no" in the original lessons to do something like: 


> if translation = no, print "not to translate" 
> else look for translated version or leave blank.

**Comment by mdlincoln** [comment]
@jenniferisasi I haven't looked in detail at this yet, but this could be a good assignment for the tech team to take on as practice! Let's talk about formalizing a list on the next call (fwiw the code to generate that table is a bit weird... so we might rethink even having that in a table format...)

**Comment by jenniferisasi** [comment]
Nota: He actualizado el listado con una nueva traducción a recibir en marzo.

**Comment by arojascastro** [comment]
Can  we close this issue? Is this going to be made using your technical super powers? :)

**Comment by mdlincoln** [comment]
@jenniferisasi want to try out a PR that changes the code in the concordance? If you use the `where` liquid filter you can isolate the pages that are lessons, and use those with the existing code.

**Comment by mdlincoln** [comment]
If so, please open this as a separate issue on the main repo and use the technical tag.

**Comment by jenniferisasi** [comment]
[Oops & embarrassment emojis] It's been almost a year since we started discussing this. 

I can't take it on right away, but yes, I would still like to try at least to improve that concordance. Let me open a new issue and set a timeline for myself (within my job transition schedule)
