### ISSUE TITLE
Proposed Lesson: Working with Many PDFs

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#242]
The Programming Historian has received the following proposal for a lesson on 'Working with Many PDFs' by Moritz Mähr. The proposed learning outcomes of the lesson are:
     
- Learn how to OCR, crop, split, convert or edit PDF files in batches.
- able to use command line tools like ghostscript, poppler and ocrmypdf
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 26 August 2019. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 26 August 2019, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @acrymble. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

**Comment by acrymble** [comment]
This is a note to say that @alsalin has returned to her position as Managing Editor and will now be the main contact for this lesson.

**Comment by alsalin** [comment]
Provided new author guidelines, some light copy edits, and some general lesson feedback to the author today. Nothing major. I imagine next steps will be to bring in the submission and create a review ticket.

**Comment by alsalin** [comment]
@amsichani will be taking on this lesson with @maehr! Anna-Maria - when you've checked that everything is in place, please go ahead and close out this issue and continue the discussion in the review ticket.

**Comment by amsichani** [comment]
I've opened a review ticket: #258 
The discussion will continue there.
