### ISSUE TITLE
Proposition de traduction en français: Preserving Your Research Data 

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#243]
Le Programming Historian en français a reçu une proposition de traduction du tutoriel "Preserving Your Research Data" par @ati95. Le suivi éditorial sera assuré par @mpuren.

La date envisagée de dépôt de la version traduite est le 30/06/2019, mais celle-ci peut être revue si la traductrice le demande explicitement. Si à cette date la traduction n'est pas déposée, nous tenterons de recontacter la traductrice. Si aucune suite n'est donnée, nous fermerons ce ticket. Nous pouvons cependant l'ouvrir à nouveau sur demande de la traductrice dans l'avenir.
Si besoin, lla traductrice est libre de contacter notre dispositif de médiation (en l'occurrence François Dominic Laramée - http://programminghistorian.org/fr/equipe-projet).

**Comment by ati95** [comment]
Bonsoir,
J'ai tenté de déposer la traduction mais j'ai créé un nouveau fichier. Je ne maîtrise pas très bien GitHub. Désolée.
Anne-Sophie

**Comment by spapastamkou** [comment]
Merci beaucoup pour votre travail, @ati95. J'ai vu qu'il existe désormais un seul fichier, donc tout va bien! @mpuren, nous pouvons peut-être fermer ce ticket quand les relectures seront sur le point de commencer?

**Comment by spapastamkou** [comment]
Bonjour @mpuren, serait-il possible de faire une mise à jour pour savoir si tu as pu trouver des relecteurs pour cette traduction? Si tu as besoin de l'aide du reste de @programminghistorian/french-team, n'hésite pas à nous solliciter. Merci.

**Comment by acrymble** [comment]
@spapastamkou can you please make sure someone takes over the editorial duties on this please?

**Comment by spapastamkou** [comment]
Bonjour @ati95, une réorganisation en interne de l'équipe a quelque peu retardé la gestion éditoriale de votre traduction. Je vous prie de bien vouloir nous en excuser. Nous ferons de notre mieux pour qu'on puisse lancer la relecture de la traduction au plus vite. Merci pour votre compréhension.

**Comment by spapastamkou** [comment]
La discussion autour de cette traduction sera poursuivi dans le ticket de relecture #263.
