### ISSUE TITLE
Proposed Lesson: Introduction to Geospatial Percent Change Analysis Using R

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#246]
The Programming Historian has received the following proposal for a lesson on 'Introduction to Geospatial Percent Change Analysis Using R' by Cameron Riopelle & Jorge Quintela Fernandez. The proposed learning outcomes of the lesson are:
     
1. Learning how to conduct geospatial analysis using R
2. Mapping socioeconomic data by census tracts
3. Visualizing percent change across time
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 31 July 2019. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 31 July 2019, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @acrymble. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

**Comment by acrymble** [comment]
This is a note to say that @alsalin has returned to her position as Managing Editor and will now be the main contact for this lesson.

**Comment by alsalin** [comment]
In touch with the author and preparing the submission for review.

**Comment by alsalin** [comment]
@ZoeLeBlanc will be working with @criopelle on this lesson! Zoe - once you've ensured things are up and running, you can go ahead and close out this issue and start getting things moving in a review ticket.

**Comment by ZoeLeBlanc** [comment]
Review ticket #260 now setup for moving forward
