### ISSUE TITLE
Proposition de traduction en français: Comprendre les expressions régulières

### ISSUE THREAD

**Issue by mpuren** [programminghistorian/ph-submissions#249]
Le Programming Historian en français a reçu une proposition de traduction du tutoriel "Understanding Regular Expressions" sous le titre "Comprendre les expressions régulières" par @alix-tz. Le suivi éditorial de la traduction sera assuré par moi-même.
La date envisagée de dépôt de la version traduite est le 30/08/2019, mais celle-ci pourrait être déposée à la fin du mois de juillet. 
Si besoin, la traductrice est libre de contacter notre dispositif de médiation (François Dominic Laramée http://programminghistorian.org/fr/equipe-projet).

**Comment by acrymble** [comment]
@spapastamkou can you please make sure someone takes over the editorial duties on this please?

**Comment by spapastamkou** [comment]
@acrymble no worries, it was in my mind for all 3 tickets. Thanks for working on them:-)

**Comment by spapastamkou** [comment]
Bonjour @alix-tz, êtes-vous en mesure de nous dire où vous en êtes avec la traduction du tutoriel, s'il vous plaît? Si vous prévoyez de la finir prochainement, nous pouvons maintenir ce ticket ouvert. Si, en revanche, cela prendra plus de temps que prévu, merci de nous dire pour que nous fermions ce ticket (et l'ouvrir à nouveau lorsque vous serez prête). Merci!

**Comment by alix-tz** [comment]
Bonjour,

La traduction est terminée, je dois simplement faire une dernière relecture. Je verserai les visuels plus tard.
On peut laisser le ticket ouvert car ça devrait être prêt d'ici une semaine.

**Comment by spapastamkou** [comment]
C'est noté, merci beaucoup @alix-tz

**Comment by spapastamkou** [comment]
La traduction du tutoriel est maintenant achevée. Le fichier, que j'ai reçu par e-mail, sera bientôt dans le dépôt ```ph-submissions``` (dès que l'accès pour les membres de l'équipe sera rétabli). Lorsque nous aurons défini qui pourra assurer le suivi de la traduction, nous ouvrirons un ticket dédié. Encore merci @alix-tz pour votre travail.

**Comment by spapastamkou** [comment]
La discussion autour de cette traduction sera poursuivie dans le ticket de relecture #264.
