### ISSUE TITLE
Error in Introduction to stylometry with Python lesson

### ISSUE THREAD

**Issue by lmrhody** [programminghistorian/ph-submissions#252]
The lesson specifies that the user should be in the "data" directory as the working directory (see "The Dataset"); however, the f-string construct statement assumes that the working directory is one level up:
` with open(f'data/federalist_{filename}.txt') as f:`

suggestion: either change suggested working directory to one level up or change line to read: 
` with open(f'federalist_{filename}.txt') as f:`

**Comment by lmrhody** [comment]
In the "Second Stylometric Text: Kilgariff's Chi-Squared Method," I needed to add a for loop to get it to print out both authors, otherwise it only printed out Madison. 

`for author in authors: 
       print("The Chi-squared statistic for candidate", author, "is", chisquared) `

**Comment by acrymble** [comment]
Thanks @lmrhody .  @fdlaramee can you look at these points?

**Comment by acrymble** [comment]
I've moved this to our main site discussion area where we will look into it. https://github.com/programminghistorian/jekyll/issues/1388

**Comment by fdlaramee** [comment]
Thanks @lmrhody -- A fix is underway.
