### ISSUE TITLE
Ticket de revisión "Introducción a ImagePlot y la visualización de metadatos de colecciones de imágenes"

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#254]
The Programming Historian en español ha recibido el siguiente tutorial "Introducción a ImagePlot y la visualización de metadatos de colecciones de imágenes" por parte de @JoshuaGOB. Este tutorial se encuentra en estos momentos en fase de edición por @jenniferisasi y en revisión por parte de  . Puede leerse en:

Texto
http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-imageplot-y-la-visualizacion-de-metadatos

Imágenes: Disponibles en Texas Data Repository: 
https://dataverse.tdl.org/dataset.xhtml?persistentId=doi:10.18738/T8/AE3DP2 

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

Política contra el acoso
El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (Maria José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by mariajoafana** [comment]
Hemos recibido este tutorial por parte de @JoshuaGOB 
¿Alguien del equipo en español está interesado en actuar como editor y/o revisor?
@arojascastro @jamotilla @jenniferisasi @rivaquiroga @vgayolrs

**Comment by jenniferisasi** [comment]
@mariajoafana perdón por la tardanza. Yo podría ser la editora pero necesito primero aclarar que fui parte del proceso de escritura en cierta forma: Si todos estamos de acuerdo en que no hay conflicto de interés, doy inicio a la edición. ¿Qué opináis?

**Comment by mariajoafana** [comment]
No le veo problema

**Comment by mariajoafana** [comment]
Tengo un posible revisor para el tutorial, le voy a consultar a ver si se anima

**Comment by jenniferisasi** [comment]
> Tengo un posible revisor para el tutorial, le voy a consultar a ver si se anima

¡Genial! Cuando sepas algo me avisas y nos ponemos a ello. 

@JoshuaGOB creo que te faltó poner una nota sobre LADI y Mellon en la sección de "La colección y los metadatos" o en forma de nota a pie de página como agradecimiento

**Comment by jenniferisasi** [comment]
Inicio el proceso de edición de este tutorial. Me comprometo a dar una primera lectura al tutorial, antes de sacarlo a revisión por pares, antes del 14 de septiembre.

**Comment by jenniferisasi** [comment]
Apunte general: el nombre de archivo MD original contenía tildes y, como consecuencia, no era posible abrirlo desde el enlace en el primer post de @mariajoafana. Algo que todos tenemos que tener en cuenta para próximas lecciones @programminghistorian/spanish-team

**Comment by jenniferisasi** [comment]
Marco sugerencias por párrafos: 

20 - "Como paso final, utilizarás metadatos ampliados por las medidas de ImagePlot para realizar una representación gráfica y para aprender cómo este tipo de visualizaciones pueden ser útiles para explorar colecciones." -- > Explicar más claro que se van a utilizar metadatos de la colección de imágenes a los que se va a añadir el resultado del análisis de ImagePlot. 
29 - Quitar: (dar más lecturas al final). 
35 - "Para este taller" -- > "Para esta lección"
35 - "organizaciones y de por" -- > "organizaciones de por" 
35 -  creo que te faltó poner una nota sobre LADI y Mellon en la sección de "La colección y los metadatos" o en forma de nota a pie de página como agradecimiento
38 - "distant viewing" en cursiva 
70 - "y otros que, por la naturaleza de la colección, no se pueden saber." -- > "y otros que no contienen datos porque se desconocen debido a la naturaleza de la colección"
82 - "Lo cual mide" -- >  "Esto mide"
87 - "X range specified?" y “Y range specified” -- > añadir traducción entre paréntesis; el signo de interrogación aparece en el programa? 
91 - "problemas la guardar" -- >  "problemas para guardar"
93 - "Segundo, el límite superior del valor del eje y parece tener imágenes en las que predomina el rojo y tenemos cinco columnas más altas que el resto." -- > ¿Falta un verbo? 
96 - "podemos mirar también mirar el lenguaje" -- > "podemos mirar también el lenguaje"

@JoshuaGOB la lección es muy clara en general y puede ser revisada por pares pronto. Por favor, introduce los cambios que indico en este comentario, además de los archivos que faltan, para proceder a su evaluación (los revisores necesitan los archivos para probar la lección).

**Comment by JoshuaGOB** [comment]
Hola. Estoy trabajando con achicar los archivos de las imágenes pero todavía no he tenido tiempo para experimentar. Si alguien tiene alguna sugerencia, será más que agradecida. Sobre el resto de los cambios, espero tenerlos todos incorporados la semana siguiente. Gracias por la ayuda.

**Comment by JoshuaGOB** [comment]
Solamente para dejar una actualización. Tuve que trabajar en algunos asunto urgentes durante el mes pasado y no he podido terminar con estas correcciones. He pedido tiempo en el trabajo para editar y lo han puesto como parte de mis responsabilidades. Espero tener la segunda versión la semana siguiente

**Comment by JoshuaGOB** [comment]
@jenniferisasi Ya trabajé el texto y solamente estoy a la espera de las imágenes.

**Comment by jenniferisasi** [comment]
Comienzo a buscar revisores.

**Comment by jenniferisasi** [comment]
Voy a realizar yo misma la primera revisión. Estoy teniendo problemas para encontrar revisores así que por lo menos para avanzar un paso.

**Comment by jenniferisasi** [comment]
El texto se ve bien, @JoshuaGOB pudiste encontrar solución para las imágenes?

**Comment by JoshuaGOB** [comment]
Trataré de darle más promoción para conseguir otro revisor. Ya las imágenes y los enlaces a los archivos están incluidas.

**Comment by jenniferisasi** [comment]
@JoshuaGOB buenísima lección de una herramienta para la que hay que estar muy familiarizada para poder realizar cualquier tipo de acción. He realizado parte de la lección siguiendo todos los pasos y he notado lo siguiente por párrafos de `edit file:`  

General: Las imágenes deben ir con las etiquetas HTML `<img src= "..." alt= "..." >` para que aparezcan 
35. Añadir la fecha de los 12 años de la Guerra Civil de El Salvador entre paréntesis (pues no todos van a saber cuándo fue)
40. Indicar que las imágenes se descargan con un nombre `dataverse_files` y lo que contiene dicha carpeta. 
47. Al ejecutar esta primera instrucción me da error "file is not a supported format, a reader plugin is not available, or it was not found" Es necesario indicar que se debe navegar a la carpeta `xs` de la que se descarga en `dataverse_files`.
49. Los resultados proveen los valores de luminosidad --> los resultados de este proceso van a proveer los valores (si no queda uno esperando a los resultados inmediatos)
70. Abre `mupi_afiches_datos.txt` de la carpeta `imageplot-master` - Primero, los metadatos quedaron dentro de la carpeta de `dataverse_file`puesto que no se indica que se extraigan. Luego, si has añadido tú manualmente los datos de `measurements.txt` a los metadatos de MUPI es importante apuntarlo. Indicar al usuario que ha de unir los documentos.
81. En este paso "Luego aparecerá otra caja para seleccionar las imágenes de la colección que descargamos anteriormente." nos pide escoger la carpeta para las miniaturas y me parece que te lo has saltado. 
84. `id(Column)` me sale como `id(Column0)` en el menú
84. `country-id(Column 7)` está como `country-id(Column 13)` en el menú
87. En opciones, ¿qué ha de hacer el usuario? Creo que hay que marcar todas las cajas y dar OK, cierto? Añadirlo. Por ejemplo, al darle como aparece por default, no muestra la caja de `Elements` que señalas a continuación. 
87. Utiliza cname1 (Column8) la cual corresponde a la organización -- ¿dónde? 
87. `cname1 (Column8)` me aparece como `cname1 (Column7)` en el menú

En este punto me da error: 

<img width="297" alt="Screen Shot 2020-01-24 at 12 11 54 PM" src="https://user-images.githubusercontent.com/11022533/73094841-099d8480-3ea7-11ea-97cb-95979a669fad.png">

[He tardado 25 minutos en completar la lección hasta aquí]

Se me ocurre también que sería bueno apuntar al usuario en la dirección de algún tutorial de descargas de imágenes con API y/u otros mecanismos.

**Comment by JoshuaGOB** [comment]
Hola, ya incorporé las correcciones pero no estoy entendiendo bien cómo va el código de markdown para incluir las imágenes.

**Comment by jenniferisasi** [comment]
En la guía de autores tenemos este formato como el standard: 
```
### Imágenes:

<figure>
<a href="/NOMBRE-DE-IMAGEN">
    <img src="/NOMBRE-DE-IMAGEN" alt="Leyenda o pie de imagen">
	</a>
<figcaption>
    <p>Leyenda o pie de imagen</p>
</figcaption>
</figure>
```

Pero como las has puesto deberían de verse una vez que el tutorial esté en jekyll.

**Comment by jenniferisasi** [comment]
89. country-id(Column 7) está como country-id(Column 13) en el menú
92. Utiliza cname1 (Column8) la cual corresponde a la organización -- ¿dónde?
92. cname1 (Column8) me aparece como cname1 (Column7) en el menú

Me sigue saliendo el mismo error en vez de el gráfico.

**Comment by jenniferisasi** [comment]
Gracias @aycasarez por ofrecerte a ser la segunda revisora de esta lección escrita por @JoshuaGOB . 

Por lo general, pedimos dos tipos de comentario: 
1) Tu impresión general del tutorial, respecto a accesibilidad, interés, etc. 
2) Comentarios concretos en oraciones o secciones que no están claras, si falta alguna instrucción o explicación, ideas, etc. Pedimos que esto se haga por el número de párrafo de la [preview del texto](http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-imageplot-y-la-visualizacion-de-metadatos). 

Por favor, revisa la [guía para revisores](https://programminghistorian.org/en/reviewer-guidelines) que tenemos y si tienes cualquier pregunta no dudes en dejar un comentario por aquí. 

Agradecería también si me puedes decir para cuándo crees que tendrás la revisión hecha y así podernos organizar. ¡Gracias!

**Comment by aycasarez** [comment]
@JoshuaGOB Lo siento mucho pero voy a escribir en ingles:

After I ran the imageMeasure.txt macro, I got a memory error so I followed your troubleshooting steps but I was not able to edit the memory allowed in the Maximum Memory box. I googled it and found out that can be an issue if you aren't using ImageJ64. So I did, and the Memory in ImageJ64 is automatically set at 658 MB. When I tried to run the same macro again, I got a different error: 

![Screen Shot 2020-03-03 at 5 03 28 PM](https://user-images.githubusercontent.com/29212442/75828728-219fd800-5d72-11ea-93d8-da1bdee65574.png)

I tried Googling this error but haven't found anything. Any ideas?

**Comment by aycasarez** [comment]
Another problem unfortunately. I tried restarting it, re-running it twice. I googled it and saw that maybe it was a memory problem but the ImageJ status shows it using just 2% of the memory in the "Exception" window. I'm going to give my brain a rest and try it again tonight with a fresh install. If that doesn't work, then I will send you screenshots of each option I am changing that were instructed in paragraphs 23-28. Maybe that will help narrow down what is very likely user error...

![Screen Shot 2020-03-06 at 5 33 17 PM](https://user-images.githubusercontent.com/29212442/76130654-244c3880-5fd1-11ea-87a2-333cf51cf963.png)

**Comment by jenniferisasi** [comment]
@aycasarez gracias por hacer la revisión que, en este caso, es más sobre la herramienta que el texto de Joshua. 

I appreciate you taking the time to find the bug; I had a couple too but solved it with the memory thing. Let us know what happens, @JoshuaGOB is also keeping an eye on this.

**Comment by aycasarez** [comment]
Ay, lo siento mucho- me enfoqué en lo indebido. Ya nunca podría arreglar el error pero no importa. Aquí es un enlace to my comments using the PH Reviewer checklist. They are in a Google Doc but I made it viewable to anyone for transparancy. Let me know if you'd rather me put them here directly. 

https://docs.google.com/document/d/1G6tP3rFkd3N6c9tdm0fnYrhlEmY58VYzQGb9nG6PhuU/edit?usp=sharing

**Comment by jenniferisasi** [comment]
Estimados,
En Programming Historian hemos adoptado la política de la calma y la solidaridad en estos momentos tan extraños y peligrosos. Quedan las tareas al ritmo de lo que pueda hacer cada uno. Seguimos en comunicación y cuidaos.

**Comment by jenniferisasi** [comment]
@aycasarez gracias por tus comentarios. Los copio aquí tus comentarios para que queden guardados en GitHub para el sistema de peer-review para "la posteridad".

## Audience
- Does the author address a consistent model reader throughout the lesson? Yes
- Are some concepts or steps over-explained while other are under-explained? Yes
- Does the audience seem to match at least vaguely with other Programming Historian lessons? Yes 
## Getting Ready
- What software / programming languages are required?  None
- What prerequisite skills are needed? Appreciate that you discuss possible memory issues(mem and thread); could you address that a lack of memory on your machine might be an issue at the beginning of the tutorial? Or is that discouraging?  
- What familiarity or experience is needed? I don’t remember this being addressed but to be honest, I’m not sure what kind of familiarity or experience is needed either. 
- What data are needed? Is the dataset readily available? Yes, data is provided through TDR with a DOI link. However, can you explain how to download the whole dataset with more detail? It took me a minute to figure it out. Just a thought. I think “Metadata file…” in Paragraph 9 needs to be changed to the txt file “mupi_afiches_datos” 
## Skimmability
- Are there clearly defined learning objectives or sets of skills to be learned listed near the top of the lesson?
- Are there useful secondary skills to be gained / practiced from the lesson?
- Do screenshots and other diagrams illustrate crucial steps / points of the lesson?
I am hoping they will! I was fine without them but I’m sure when they are published in the final version they will add some clarity. 
- Do sections and section headings provide clear signage to the reader?

## Payoff
- Does the tutorial suggest why the explained tools or techniques are useful in a general way? (P6)
- Does the tutorial suggest how a reader could apply the concepts (if not concrete steps) of the lesson to their own work? (P5)

## Workflow
- Should a long lesson be divided into smaller lessons? No
- Are there logical stopping points throughout the lesson? If datasets are required, are they available to download at various points throughout the lesson (or different versions of them as the tutorial may require)?
 
## Sustainability
- What are the data sources for the submission? Are they included in a way that does not heavily on third-party hosting? What kinds of other external links does the submission use? Are these current or are there other, more recent or appropriate, resources that could be linked to? I would love to see other links to other projects/tutorials that discuss ImageJ. I know there is the one that comes with the download but that might even be worth mentioning. 

Paragraph 12: De los macros disponibles, selecciona imageMeasure.txt. Se abrirá una caja nueva para seleccionar la carpeta de tus imágenes (xs) y luego otra para seleccionar la carpeta en la que se guardará el archivo con las medidas. Puedes guardar este último archivo en la carpeta de imageplot-master seleccionando tu escritorio en el menú despegable.

Paragraph 20: Abre mupi_afiches_datos.txt de la carpeta imageplot-master y verás los metadatos de las imágenes combinados con las medidas.

Paragraph 21: 

Paragraph 23: Los valores son el resultado de experimentar con estos ajustes para esta colección y muy probablemente tengan que ser modificados al trabajar con otros materiales.

Paragraph 26: Por alguna razón, ImagePlot tiene problemas para guardar en otros formatos que no sean TIF.

**Comment by JoshuaGOB** [comment]
Saludos @jenniferisasi y @aycasarez 

Acabo de añadir una nota sobre los requisitos mínimos de memoria y un enlace a los otros proyectos relacionados a Imageplot como sugirió @aycasarez. También encontré la errata del nombre del archivo de metadatos (lo había dejado de comodín sin querer).

**Comment by jenniferisasi** [comment]
Voy a proceder a darle un último vistazo a la lección y si todo es correcto, publicarla.

**Comment by jenniferisasi** [comment]
@JoshuaGOB porfa pon un alt-text más descriptivo en tus imágenes en el .md. Cuando se hagan esos cambios puedo dar el siguiente paso. 

Procedo a las últimas tareas según las guías del editor: 

- [x]  Crea una biografía para el autor [Joshua ya tenía una, qué bien]
- [x] Agrega una tabla de contenidos a la lección
- [x] Agrega metadatos YAML al archivo de la lección
- [x] Busca una imagen que represente la lección [la puse en la misma carpeta de imágenes para facilitar la descarga desde este repo, aunque en jekyll irá en otra carpeta]
- [x] Informa al jefe de redacción para publicar
- [ ] Incorpora tu lección en nuestro Twitter bot
- [x] Da las gracias a todo el mundo y difunde el tutorial

**Comment by jenniferisasi** [comment]
@mariajoafana esta lección queda lista para publicar. En principio, todo funciona pero si hubiera que cambiar algo al pasarlo al repo Jekyll nos avisas. No estoy segura de si tienes que incorporar tú los tweets o yo. La última vez que publiqué algo lo hacían todo los editores. 

Gracias @JoshuaGOB por escribir esta lección de una herramienta no muy intuitiva pero muy útil, y gracias @aycasarez por tu revisión.

**Comment by mariajoafana** [comment]
Buenísimo, me encargo de la publicación y de incorporar los tweets

**Comment by rivaquiroga** [comment]
@mariajoafana, entonces ¿tú te encargarás de publicar la lección? Pensaba que tenía que hacerlo yo 🤔

**Comment by mariajoafana** [comment]
mmm, ya me confundí, creo que cuando me fui de sabático tu quedaste encargada de esta?

**Comment by rivaquiroga** [comment]
@mariajoafana, la lección está a cargo de Jennifer. Ella es la editora. Según el flujo de trabajo de la guía del editor, una vez que está lista la lección, el/la ME de turno se encarga de mover todo a Jekyll

**Comment by mariajoafana** [comment]
Listo Riva, toda tuya!

**Comment by rivaquiroga** [comment]
Perfecto. Durante la tarde hago el PR para que lo revisen

**Comment by rivaquiroga** [comment]
@jenniferisasi, en la carpeta de imágenes no encontré la versión original de la imagen de la lección, solo la de 200x200. Si me mandas el enlace desde donde la obtuviste, la puedo descargar directamente.

@JoshuaGOB, tengo problemas para ver la imagen `visualizacion.jpg` porque es demasiado grande. Probé en dos computadores y el programa se cierra al tratar de abrirla. Y directamente en Github tampoco me resulta. ¿Es posible remplazarla por una un poco más pequeña?

**Comment by JoshuaGOB** [comment]
Listo @rivaquiroga Gracias por verificar esto.

**Comment by jenniferisasi** [comment]
perdón, @rivaquiroga pensaba que solo había que subir una pequeña, por eso puse únicamente esa. Ahora, claro, no encuentro esa pero igual le va mejor esta que encontré de un optical instrument https://www.flickr.com/photos/internetarchivebookimages/14801823673/

**Comment by rivaquiroga** [comment]
¡Muchas gracias! Entre hoy en la tarde y mañana en la mañana queda hecho el PR para publicar la lección

**Comment by rivaquiroga** [comment]
@jenniferisasi, @JoshuaGOB, el PR está listo. ¡Muchas gracias por el trabajo!
El build de Travis aparece fallando porque la lección no tiene DOI todavía (y desde ahora es un campo obligatorio). Como se va a estar probando el flujo de trabajo para asignarlo, puede que tome un tiempo más de lo esperado en aparecer publicada. 
Los puse como revisores del PR, pero por ahora no hay mucho que podamos hacer, más que estar atentos a las indicaciones de Matt sobre el DOI. Una vez que esté eso resuelto, le podemos dar una última mirada a la lección para chequear que todo se ve bien.

**Comment by rivaquiroga** [comment]
¡Lección publicada! @jenniferisasi, solo faltaría que la agregaras al bot de Twitter y ya podemos difundir :rocket: 
¡Mucha gracias por todo el trabajo!

**Comment by jenniferisasi** [comment]
Listo. Añadí los tweets y cierro ticket. ¡Felicidades a todos!
