### ISSUE TITLE
Relecture de traduction: Introduction aux bots Twitter avec Tracery

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#256]
Le Programming Historian en français a reçu la traduction du tutoriel "An introduction to Twitterbots with Tracery" sous le titre "Introduction aux bots Twitter" par @Satsuma007. Le texte est déposé ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-aux-bots-twitter.md
Je vais assurer le suivi éditorial de cette traduction. J'ai sollicité deux relectures auprès de @symac et @antoinecourtin et je coordonnerai les échanges qui auront lieu dans cet espace. Les relecteurs pourront utiliser la numérotation des lignes fournie dans l'aperçu pour insérer leurs commentaires, si cela leur convient. Toutefois, ils seront libres de présenter leurs commentaires comme ils jugeront mieux. Les relecteurs peuvent aussi s'appuyer sur les [consignes aux traducteurs et aux traductrices](https://programminghistorian.org/fr/consignes-traducteurs#traduire-une-le%C3%A7on-et-la-mettre-en-page). Nous pouvons prévoir un délai de 30 jours environ, qui peut néanmoins être adapté si besoin. 

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour l'auteur(e) puisse travailler sur la révision de son texte. Je l'annoncerai sur ce fil quand cette étape aura été atteinte.

Je ferai de mon mieux pour garder la discussion ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers @fdlaramee , si vous avez le sentiment qu'une médiation est nécessaire.        

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (https://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by spapastamkou** [comment]
A-t-on des nouvelles du front des relectures ici? :-)

**Comment by antoinecourtin** [comment]
Bonjour @spapastamkou, 
Je vais être en vacance la semaine prochaine, je m'en occupe à ce moment là. Désolé, j'étais un peu sous l'eau.

**Comment by spapastamkou** [comment]
Merci @antoinecourtin, pas de souci, on comprend.

**Comment by spapastamkou** [comment]
Chers @antoinecourtin et @symac, avez-vous eu la possibilité d'avancer dans vos relectures? Je reste à votre disposition s'il y a des soucis. Merci!

**Comment by spapastamkou** [comment]
Bonsoir messieurs @antoinecourtin et @symac, je viens faire le ménage dans ce ticket:-) 
Plus sérieusement, êtes vous en mesure d'indiquer une date réaliste à laquelle on peut attendre vos commentaires pour travailler sur la version finale du texte et le publier? Merci beaucoup pour votre aide

**Comment by spapastamkou** [comment]
Chers @antoinecourtin et @symac, je sais que vous êtes sûrement débordés et il faut dire que je déteste mettre la pression, surtout que vous vous êtes gentiment offerts pour nous aider sur votre temps libre. Si vous ne pouvez pas vous occuper de cette relecture, seulement merci de me le faire savoir, pour m'organiser en fonction et ne pas laisser la traductrice dans l'attente ni les tickets s'accumuler. Meilleures salutations à tous les deux:)

**Comment by antoinecourtin** [comment]
J'ai relu le texte et je n'ai pas grand chose à dire, à part : 

- présence d'un libelle anglais dans un titre de section (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-aux-bots-twitter.md#bonnes-pratiques-en-mati%C3%A8re-de-botsgood-bot-citizenship)
- certains exemples json n'ont pas été traduits (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-aux-bots-twitter.md#bonnes-pratiques-en-mati%C3%A8re-de-botsgood-bot-citizenship)
- pour la section, voir la "ma[propre expérience" (]https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-aux-bots-twitter.md#bonnes-pratiques-en-mati%C3%A8re-de-botsgood-bot-citizenship).

**Comment by spapastamkou** [comment]
Merci @antoinecourtin pour votre relecture, nous allons donc revoir le texte pour tenir compte de vos remarques et l'améliorer.

**Comment by spapastamkou** [comment]
@programminghistorian/french-team J'aimerais bien votre avis: j'envisage la publication de cette traduction avec une seule relecture, après bien sûr que le travail des corrections aura été achevé. Vous en pensez quoi? Merci!

**Comment by fdlaramee** [comment]
@spapastamkou À toi de juger, mais si tu veux une deuxième lecture je pourrais m'en charger rapidement.

**Comment by symac** [comment]
@spapastamkou je retombe juste sur cette issue, il me semble avoir une copie annotée de la relecture que j'avais faite il y a quelques temps sur mon ordi pro, je regarder cela dans la journée, désolé pour le retard, j'ai laissé passer pas mal de notifs PH ...

**Comment by spapastamkou** [comment]
Merci beaucoup, @fdlaramee et @symac pour vos réactions. Sylvain, si tu as déjà la relecture prête, c'est super! Si ce n'est pas le cas, je vais sans doute embêter un peu François Dominic, comme il est toujours mieux d'en avoir deux, plutôt qu'une.

**Comment by symac** [comment]
@spapastamkou je pensais être sur un fork mais je m'aperçois que j'ai fait le commit ici ( 60c0dca68f5d234646ef046254ecabfe4e42a2f5 ), j'espère que ça ira comme ça. 

Les modifications sont principalement liées à la forme et à quelques formulations. 

Il me reste deux commentaires : 

- ligne 247 & paragraphe explicatif suivant : est-ce pertinent de traduire le modificateur .capitalize en .majuscule ? 
- de la même manière, dans les exemples autour des lignes 294, est-ce que tout traduire y-compris des noms comme creature en créature ne vont pas poser problème avec l'outil, en particulier avec l'introduction d'accents ? Je ne l'ai pas testé mais je me pose la question.

Désolé pour le délai dans le retour ! 

S.

**Comment by spapastamkou** [comment]
@symac Je vais travailler avec le commit, pas de pb, merci beaucoup, vraiment! 
Sur le fond des remarques, je vais me pencher sur le texte et sur le code dès que possible et je vais revenir ici en commentaire pour revoir les parties concernées avec la traductrice. 

Dans tous les cas, une nouvelle fois un grand merci à vous @symac et @antoinecourtin, surtout que je vous sais occupés tous les deux.

**Comment by spapastamkou** [comment]
J'ai achevé de travailler sur le suivi de cette traduction après avoir tenu compte des commentaires des deux relecteurs; j'ai également tenu la traductrice informée par message électronique du 6 mai dernier sur les modifications que j'ai apportées de manière détaillée. Je tiens à la remercier à nouveau pour sa traduction de ce tutoriel: les défis pour l'adapter au français étaient de taille et elle a su garder le ton convivial de l'original, mais aussi se repérer en dépit de certains termes techniques qui n'étaient pas toujours clairs. 
Mes propres interventions ont consisté notamment:  
1) sur la forme: 
- uniformiser le texte (ponctuation etc.); 
- reprendre le markdown lorsque cela était nécessaire; 
- ajouter certaines ressources en français à l'intérieur du texte sous forme de liens et dans les notes. 
2) sur le fond:
- j'ai repris toutes les parties avec du code en JSON pour le tester, ce qui a entraîné des modification s car par rapport à l'original et à la première version de la traduction pour les faire fonctionner en français. J'ai dû inventer qqs exemples, peut-être ils sont simplistes, mais globalement ils marchent.  Je dois remercier @Satsuma007 à nouveau: elle avait attaqué le code déjà, tout en précisant qu'elle n'avait pas pu le tester, mais son travail initial a permis que je prenne le relais, pour que j'adapte ou modifier par la suite. 
- j'ai produit des fichiers jpg avec des exemples en français lorsque cela était possible (grammaire Tracery etc); j'ai créé aussi en bot PlanteEnPot, en profitant de mes semis du printemps pour illustrer cette leçon (pas de problèmes de droits pour les photos:))
- certaines parties du code traduit en français, je les ai restituées comme dans l'original en anglais et ai ajouté des notes explicatives. Il s'agit notamment d'exemples de la partie "[Aller plus loin avec Tracery](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-aux-bots-twitter.md#aller-plus-loin-avec-tracery)". C'est que l'adaptation de la grammaire Tracery (avec les modificateurs etc) était faite pour les règles de la grammaire et la syntaxe de l'anglais; pour le français ou une autre langue, cela ne marchait pas avec ces modificateurs-là; mais et il était impossible d'aller plus loin dans le cadre de la traduction et du suivi éditorial de cette leçon. Idéalement, dans l'avenir on devrait avoir une leçon rédigée par des francophones car les déclinaisons des noms et des verbes du français me semblent poser des défis intéressants pour développer des grammaires utilisables par les bots. 

En espérant avoir résumé l'essentiel de mes interventions, je renouvelle mes remerciements pour la traduction et les relectures de ce tutoriel. A priori le texte est prêt pour être publié, mais comme j'ai pris du retard pour le finaliser, je préfère laisser ce ticket ouvert aux commentaires des contributeurs et contributrices pendant deux semaines encore, le cas échéant. La leçon sera publiée avant la fin de ce mois-ci.

**Comment by spapastamkou** [comment]
@symac concernant ton commentaire ci-dessous copié: 
pou le premier c'est non, de ce que j'ai pu voir; pour le 2e, on peut nommer les règles de Tracery avec des mots français ET accentués, ça marche et produit des phrases; en revanche, `origin` il faut le garder tel quel si on veut avoir un résultat, sinon cela ne génère rien.  

> Il me reste deux commentaires :
> 
> * ligne 247 & paragraphe explicatif suivant : est-ce pertinent de traduire le modificateur .capitalize en .majuscule ?
> * de la même manière, dans les exemples autour des lignes 294, est-ce que tout traduire y-compris des noms comme creature en créature ne vont pas poser problème avec l'outil, en particulier avec l'introduction d'accents ? Je ne l'ai pas testé mais je me pose la question.
>

@antoinecourtin J'ai ajouté dans les notes en bas votre post de blog sur Medium.

**Comment by spapastamkou** [comment]
Ce tutoriel est maintenant en cours de publication. 

Par ailleurs, @alix-tz a fourni plusieurs exemples de bots en français que j'ai intégré dans des notes à la fin du texte. Pour que sa contribution soit visible, elle figure comme relectrice de ce tutoriel.

**Comment by spapastamkou** [comment]
Le tutoriel est publié! Il est consultable ici: https://programminghistorian.org/fr/lecons/intro-aux-bots-twitter
Merci beaucoup @Satsuma007 pour la traduction et @symac @antoinecourtin @alix-tz pour vos relectures et conseils.
