### ISSUE TITLE
Traduction en français : De l'herméneutique aux réseaux

### ISSUE THREAD

**Issue by grandjeanmartin** [programminghistorian/ph-submissions#262]
Je propose au Programming Historian en français une traduction du tutoriel "From Hermeneutics to Data to Networks: Data Extraction and Network Visualization of Historical Sources" (Marten Düring) sous le titre "De l'herméneutique aux réseaux, en passant par les données: extraction de données et visualisation de réseaux de sources historiques". Le suivi éditorial de la traduction sera assuré par @spapastamkou.

La date envisagée de dépôt de la version traduite est le 30/11/2019.

**Comment by spapastamkou** [comment]
Cher @grandjeanmartin, serait-il possible de faire une mise à jour sur l'évolution de ce travail-ci? Merci!
