### ISSUE TITLE
Jack Pay Review: The Programming Historian - Working with batches of PDF files

### ISSUE THREAD

**Issue by jackpay** [programminghistorian/ph-submissions#271]

**Comment by amsichani** [comment]
Hi @jackpay , thanks for this! please place your review under the submission's ticket https://github.com/programminghistorian/ph-submissions/issues/258 and delete this ticket. Thanks!

**Comment by jackpay** [comment]
- [ ]

**Comment by jackpay** [comment]
Hello @amsichani. Apologies for the error. I have closed the issue as I don't have admin rights to delete fully.
