### ISSUE TITLE
Proposition de traduction en français: Introduction aux carnets Jupyter Notebooks

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#276]
Je propose de traduire en français la leçon intitulée: "Introduction to Jupyter Notebooks" et rédigée par Quinn Dombrowski et al. 

Je propose le 31 janvier comme date de livraison.

@spapastamkou @grandjeanmartin @programminghistorian/french-team

**Comment by jenniferisasi** [comment]
Je voulais juste dire: c'était rapide!

**Comment by fdlaramee** [comment]
@jenniferisasi C'est une demande spéciale qui nous est parvenue sur Twitter 😀

**Comment by spapastamkou** [comment]
@jenniferisasi You see that? He is our Precious :-)

**Comment by fdlaramee** [comment]
J'avais bêtement oublié de le documenter ici, mais la traduction est complétée depuis le 24 janvier et déposée au https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/introduction-aux-carnets-jupyter-notebooks.md 

Le processus de révision débutera dès qu'un(e) membre de l'équipe sera en mesure de prendre le suivi en charge.

**Comment by spapastamkou** [comment]
@mariechristineb Je me lance dans la recherche de potentiels relecteurs pour ce tutoriel, aurais-tu la possibilité d'être des nôtres?

**Comment by mariechristineb** [comment]
@spapastamkou Oui, pas de problème. Je suis en vacances jusqu’au 10 septembre, mais je peux m’y mettre ensuite

**Comment by mariechristineb** [comment]
@spapastamkou tu peux ouvrir le ticket de révision dès que tu auras le temps, ma révision est prête

**Comment by spapastamkou** [comment]
Merci @mariechristineb, je fais cela dès que possible!

**Comment by spapastamkou** [comment]
Un ticket de relecture a été ouvert #309 et je ferme celui-ci.
