### ISSUE TITLE
Proposition de traduction en français: "Generating an order dataset from an OCR text file"

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#280]
Le Programming Historian en français a reçu une proposition de traduction de la leçon intitulée "Generating an order dataset from an OCR text file" de la part de @Gourlak. 
Nous pouvons viser la fin du mois de février pour que le texte soit achevé et nous pouvons bien sûr revoir la date avec le traducteur. 
@Gourlak, quand vous aurez fini, vous pouvez déposer le fichier du texte dans ce dépôt: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/fr/traductions Vous pouvez le déposer directement, sans pull request. 
Alternativement, vous pouvez me l'envoyer pour que je le dépose pour vous. 

Voici à nouveau les consignes destinées aux traducteurs et traductrices: https://programminghistorian.org/fr/consignes-traducteurs

Je reste à disposition si nécessaire! Merci à vous.

**Comment by Gourlak** [comment]
Ca marche merci à bientôt!

**Comment by spapastamkou** [comment]
La traduction est maintenant achevée et déposée ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/generer-jeu-donnees-texte-ocr.md 
Nous désignerons dès que possible un des membres de la @programminghistorian/french-team pour prendre en charge le suivi des relectures. Jusqu'alors ce ticket restera ouvert.

**Comment by ati95** [comment]
Si vous le souhaitez je veux bien prendre en charge une relecture, dès que le ticket #263 est clos.

**Comment by spapastamkou** [comment]
Chère @ati95, oui, avec plaisir. On vous fera signe quand l'un de nous pourra lancer les relectures, en espérant que vous aurez la disponibilité. Merci à vous

**Comment by mariechristineb** [comment]
Chère @ati95, seriez-vous disponible pour faire cette relecture dans les prochaines semaines?

**Comment by spapastamkou** [comment]
Si besoin, je peux aider pour retrouver des relecteurs/relectrices afin de lancer la relecture de la traduction et la publier.

**Comment by InesSalome** [comment]
Pour information : je suis en charge du suivi éditorial de cette traduction et je vais ouvrir une nouvelle issue pour la relance de relecteurs/relectrices.
