### ISSUE TITLE
Relecture de traduction: Débuter avec Markdown

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#283]
Le Programming Historian en français a reçu la traduction du tutoriel "Getting Started with Markdown" de Sarah Simpkin sous le titre "Débuter avec Markdown". Cette traduction a été réalisée par @spapastamkou . Le texte est déposé ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/debuter-avec-markdown.md

Je vais assurer le suivi éditorial de cette traduction et coordonner les échanges qui auront lieu dans cet espace. Deux relectures ont été sollicitées auprès de Catherine Paulin (@catp22) et de Déborah Dubald (@deoah). Les relectrices pourront utiliser la numérotation des lignes fournie dans l'aperçu pour étiquter leurs commentaires, si cela leur convient. Toutefois, elles seront libres de présenter leurs commentaires comme elles le jugeront approprié. Les relectrices peuvent aussi s'appuyer sur les **[consignes aux traducteurs et aux traductrices](https://programminghistorian.org/fr/consignes-traducteurs)**. 

Les rapports de relecture sont attendus, en commentaires à ce ticket, pour le **10 mars 2020**. Si ce délai ne peut pas être observé, veuillez m'en prévenir le plus rapidement possible.

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour que la traductrice puisse travailler sur la révision de son texte. L'annonce sera faite sur ce fil quand cette étape aura été atteinte.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique (@fdlaramee). Vous avez toujours la possibilité de vous tourner vers notre dispositif de médiation, si vous avez le sentiment qu'une médiation est nécessaire.

**Politique contre le harcèlement**

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (https://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by fdlaramee** [comment]
@deoah @catp22 @spapastamkou Le processus d'édition de cette traduction est maintenant en cours. Les rapports de lecture sont attendus pour le 10 mars. Merci d'avance!

**Comment by fdlaramee** [comment]
J'ai reçu les commentaires de @catp22 que je copie dans ce message. Nous attendons ceux de @deoah avant de procéder aux révisions; à quel moment pensez-vous pouvoir nous les livrer? Merci!

--------------

Commentaires :

« Cette leçon propose une introduction à Markdown »
 Cette leçon servira à vous initier à Markdown, (…) 

En lisant cette leçon, vous serez initié à Markdown (…)
Cette leçon sert d’initiation à Markdown (…) 
Ou une autre variante, pour plus de clarté et un meilleur ‘flow’.

« J'espère que ce quide vous sera utile si vous envisagez de rédiger un tutoriel en tant qu'auteur(e).”
Erreur de frappe : guide et non quide

En tant qu’auteure pour? (La version en anglais spécifie : ce site. Je crois que ce serait intéressant de l’utiliser aussi pour que ce soit plus claire.)

« Développé en 2004 par John Gruber, Markdown est à la fois un langage de balisage de fichiers textes et une fonctionnalité du langage Perl permettant de convertir des fichiers Markdown en HTML. »
Serait-ce possible d’intégrer un lien web vers ce qu’est le Perl? Pour ceux que ça intéresse. Ou considérer une explication rapide. 

« L'utilisation de la syntaxe Markdown vous permettra de produire des fichiers à la fois lisibles en texte brut et prêts à recevoir davantage de traitement sur une autre plateforme. Plusieurs systèmes de gestion de blogs, des générateurs de sites web statiques ou encore des plateformes comme GitHub prennent en charge des fichiers Markdown pour les convertir en HTML et les publier sur le web. De plus, des outils comme Pandoc peuvent convertir des fichiers depuis et vers Markdown. Pour apprendre plus sur Pandoc, vous pouvez faire un tour sur cette leçon de Dennis Tenen et Grant Wythoff. »
Ce paragraphe est à la fois très clair et concis, ce qui est vraiment important pour la leçon. En tant que personne qui n’a jamais travaillé avec Markdown, je commence à bien saisir rendu ici.

« Dans ce tutoriel, nous allons pratiquer la syntaxe Markdown à partir du navigateur en utilisant »
À partir de votre navigateur? Pour une invitation claire à participer et essayer.

« coller l'URL suivante pour faire apparaître la leçon "Introduction to the Bash Command Line" (Introduction au langage de commande Bash): »
Est-ce possible d’utiliser une leçon déjà traduite pour l’exercice? Ou faut-il que ce soit une traduction directe de la version anglophone?

Au sujet de la N.D.L.R pour la traduction en français – il s’agit d’une bonne initiative. Note hors sujet : Il faudrait possiblement l’indiquer aussi dans la version en anglais éventuellement?

« (…) et Cette phrase pour vous rendre compte comment ça marche »
Je ne sais pas si cette formulation serait considérée trop familière par PH. Si oui, il y a toujours la possibilité de le remplacer par « fonctionnement » ou un autre mot?

Parfois, certaines configurations nécessitent de signaler les simples sauts de ligne avec en plus deux espaces vides à la fin de chaque ligne (qui précède).
J’ai relu cette phrase à plusieurs reprises pour être certaine d’avoir bien saisi. Serait-ce possible de la simplifier ou la diviser en deux pour que ce soit plus clair? Ex. : après le premier « ligne ». Et ensuite expliquer.

La section sur la liste de courses et comment créer des listes ordonnées est vraiment très claire.

“Cella s'affiche comme suit:”
Faute de frappe: “Cela”

« Ces liens s'écrivent entre une paire de crochets supplémentaire pour leur créer essentiellement un identifiant unique. »
Essentiellement entre deux virgules? 

« Les images peuvent être référencées en utilisant un point d'exclamation ! suivi par du texte supplémentaire entre crochets et, entre parenthèses, l'URL de l'image et éventuellement un titre entre guillemets. »
Éventuellement entre deux virgules? 

“GitHub Flavored Markdown est une de ces variantes, principalement utilisée pour afficher des fichiers .md dans le navigateur sur le site web de Github. is one of these variants, and is used to render .md files in the browser on the GitHub site. »
La ligne en anglais est restée après sa traduction.

« Les barres verticales sont strictement nécessaires seulement entre les colonnes, vous pouvez néanmoins les utiliser des deux côtés de votre table pour obtenir un résultat plus soigné. »
Utilisation d’un ; à la place de la virgule

«  Pour savoir plus sur Pandoc, merci de consulter la leçon du Programming Historian intitulé Sustainable authorship in plain text using Pandoc and Markdown (en anglais). »
Pour en savoir plus?

Autre ces petits commentaires, la traduction me semble très bien. Elle est facile à suivre et, après vérification, demeure fidèle à la version anglophone.

**Comment by deoah** [comment]
Toutes mes excuses, j'ignore pourquoi (certainement car je ne suis pas habituée à la plateforme) mais je n'avais pas vu le message contenant la date du 10 mars. Je fais de mon mieux pour finir cette semaine!

**Comment by fdlaramee** [comment]
Chers collègues et amis,

Les événements se précipitent en ce qui concerne la pandémie de COVID-19. Il est entendu que nous aurons tous et toutes à composer avec des circonstances difficiles et changeantes au cours des prochaines semaines. N'hésitez donc pas à prendre le temps supplémentaire dont vous avez besoin pour compléter les tâches en cours; je vous demande seulement de nous tenir au courant, dans la mesure du possible.

Solidairement,
FDL

**Comment by deoah** [comment]
Pour les commentaires, j'ai ouvert le code de la page sur Atom. J'utilise donc la numérotation des lignes telle qu'elle apparait dans le texte brut de la page.
Je me considère moi-même comme débutante en code et j'ai lu le tutoriel comme débutante. Mes commentaires se comprennent donc dans une lecture qui doit permettre à un public qui n'est pas du tout familier de ces questions de comprendre les enjeux de l'utilisation de MD.
__________________
l22 : abstract clair et concis. Je me demande si le terme "formatage" est clair pour quelqu'un qui n'y connait rien. Y'a-t-il un renvoi possible vers la définition du terme ? (un lexique ?) En réalité, je pense que le public de PH comprendra.

36 : même commentaire, mais le renvoi (si une telle chose était possible) vers une définition serait plus pertinente ici que dans l'abstract.
38 : <s>examples</s> = exemples
Je pense que le tutoriel serait utile à d'autre situations que celles rencontrées par les auteur·ices de PH, comme par exemple la publication web en général ? (je ne suis pas spécialiste, je pense qu'il faudrait préciser ma proposition).

43 : "aux autres formats" : c'est à dire ? Serait-il possible de préciser ? (toujours dans un souci de lecture par un public débutant).
"un format de traitement de texte hérité" : je ne suis pas sûre de comprendre.
La suite de la phrase est également ambigue : "vous devez sans doute saisir facilement les problèmes de compatibilité que cela peut impliquer". Même si cela parait simple, l'expression comprend un certain niveau d'implicite. Je propose quelque chose comme "vous pourriez vous trouver dans l'impossibilité d'ouvrir un tel fichier en raison de l'incompatibilité avec des versions ultérieures de tel programme / en raison de la non pérennité de tel programme"?

45 : impeccable car donne des perspectives qui répondent bien à la question "mais en fait ca me sert à quoi de m'initier à cette technique". Je trouve que les liens vers d'autres leçons pour visualiser rapidement les perspectives de développement sont bien également. Ajouter quelque chose (= un lien) sur la publi en HTML  ?

50 : possibilité d'ajouter une capture d'écran pour visualiser "la gauche" et "la droite"? Même si le lien permet de visualiser _après_, mais ici ce serait déjà plus engageant (=_engaging_), je trouve.

64 : "attaquons" = démarrons ?

96 : Peut-être remplacer par "vous voyez que le _sens_ du contenu rédigé avec la syntaxe md reste compréhensible" ? Car en effet, ce qui est en jeu, c'est le sens du texte, et par forcément la syntaxe md elle-même ? (je peux me tromper par mauvaise compréhension des termes).

161 : Je ne vois pas de lien ici entre la réalisation de listes et les enjeux de lisibilité de md, présentés dans la phrase suivant. Pourrait-on peut-être la déplacer pour la mettre en exergue dans un endroit du texte qui n'est pas spécifiqueent associé à un aspect de la mise en forme? Je pense à souligner la question des enjeux de lisibilité dans l'introduction (je me rends compte que c'est peut-être faiblement mis en valeur?) ou alors dans la conclusion ?

243/245 : c'est certainement un commentaire plus technique mais, stack edit affiche qqch de différent que les deux lignes annoncées. 
En effet, si l'on saisit
```
Le site web du [Programming Historian][1] fournit un exemple.

[1]: http://programminghistorian.org/ "The Programming Historian"
```
Stackedit affiche : 
"Le site web du Programming Historian* fournit un exemple."
_* hyperlié à URL du site_

C'est certainement moi qui n'ai pas tout compris !

276 : je crois que la ligne est un reste du texte original :)

317 : serait-il possible de créer un lien vers un outil qui permette de comprendre comment convertir en HTML ? 

_____________________

Je crois que le texte est très clair, dans l'ensemble. En dépit de mes commentaires, je crois que le tutoriel permet à quiconque de se saisir de l'outil et que la traduction est efficace - notamment car elle reste proche de la structuration des informations en anglais, et reste très concise, ce qui n'est pas toujours le propre de l'anglais. D'aucun trouveront peut-être cela aride ; pour ma part je trouve cela très bien.

J'espère que ces commentaires ne sont pas déplacés et vous seront utiles. 
Je vous renouveler mes excuses pour le terrible retard avec lequel j'ai effectué cette évaluation.

Je reste à votre disposition si besoin !

Deborah

**Comment by fdlaramee** [comment]
Merci @deoah; je relirai les recommandations contenues dans les deux relectures très bientôt et nous pourrons procéder aux révisions finales.

**Comment by fdlaramee** [comment]
Merci encore une fois @deoah et @catp22. Nous pouvons maintenant passer aux révisions finales. 

@deoah: le comportement que vous signalez à la ligne 243-245 est probablement un artefact du comportement de votre éditeur de texte, qui diffère de celui du système de rendu du Markdown Github employé par notre infrastructure. L'affichage sur notre site de prévisualisation est correct. Il n'y a donc pas de changement à apporter à la traduction.

@spapastamkou : l'ensemble des commentaires sont judicieux et assez faciles à intégrer; lorsqu'il s'agit de questions de jugement, je te laisse le soin de choisir ceux que tu souhaites implanter. Je suggère cependant de ne **pas** ajouter de capture d'écran, comme le propose @deoah à la ligne 50, pour ne pas trop s'éloigner de l'original. En vertu des consignes habituelles, la date de remise de la version finale corrigée devrait être le 30 avril mais il est bien entendu que les circonstances actuelles remettent tout en question alors vas-y comme tu peux.

À très bientôt,
FDL

**Comment by spapastamkou** [comment]
Merci aux relectrices pour ces commentaires, merci François Dominic pour tes instructions et pour le suivi. J’en tiendrai compte et ferai de mon mieux pour ne pas aller au-delà de la date indiquée. Portez-vous bien et bon courage!

**Comment by spapastamkou** [comment]
J'ai déposé une version mise à jour dans laquelle j'ai fait de mon mieux pour tenir compte de la plupart des suggestions faites par @CatP22  et @deoah. Outre les modifications d'expressions, j'ai ajouté quelques liens vers des notices wikipédia pour fournir davantage d'infos sur des termes qui n'étaient peut-être pas clairs pour tout le monde. Une prévisualisation de cette version est disponible ici: http://programminghistorian.github.io/ph-submissions/fr/traductions/debuter-avec-markdown

@fdlaramee Merci de vérifier si tout est conforme et n'hésite pas à apporter des corrections, si tu constates des pbms, ou me solliciter pour les faire. 

@deoah Merci encore pour la relecture, j'ai suivi/adapté la plupart de tes suggestions; ci-dessous des précisions sur certains points:    
> 96 : Peut-être remplacer par "vous voyez que le _sens_ du contenu rédigé avec la syntaxe md reste compréhensible" ? Car en effet, ce qui est en jeu, c'est le sens du texte, et par forcément la syntaxe md elle-même ? (je peux me tromper par mauvaise compréhension des termes).
> 
J'ai un peu reformulé la phrase en espérant qu'elle est plus facile à comprendre. Mais il me semble bien qu'il est question de la syntaxe ici (le fait que Markdown dispose d'une syntaxe qui est destinée à être comprise par les machines, sans pour autant qu'un formatage lourd en balises gène l’œil humain et la compréhension de ce qui est écrit). 

Pour les commentaires sur les lignes 161 et 317: à vrai dire, je préfère ne pas prendre trop de libertés vis-à-vis de la v.o. 
Pour les lignes 243/245: j'ai vérifié en répétant la manip dans StackEdit et tout va dans le sens de la démonstration faite dans le texte, pas de souci.  

Merci bien à tous les trois! Je reste à disposition si besoin.

**Comment by fdlaramee** [comment]
Merci @spapastamkou ; j'effectuerai une dernière relecture le plus rapidement possible.

**Comment by fdlaramee** [comment]
@spapastamkou J'ai apporté quelques corrections de forme et ajouté les noms des relectrices au fichier. Je crois qu'il est maintenant prêt pour la phase finale.

**Comment by spapastamkou** [comment]
Merci, c'est noté! Je travaillerai sur la publication à la fin de la semaine pour espacer un peu avec la mise en ligne d'aujourd'hui.
