### ISSUE TITLE
Relecture de traduction: Manipuler les chaînes de caractères en Python

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#284]
Le Programming Historian en français a reçu la traduction du tutoriel "Manipulating Strings in Python" de William J. Turkel et Adam Crymble sous le titre "Manipuler les chaînes de caractères en Python". Cette traduction a été réalisée par Camille Carette. Le texte est déposé ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/manipuler-chaines-caracteres-python.md

Je vais assurer le suivi éditorial de cette traduction et coordonner les échanges qui auront lieu dans cet espace. Les deux relectures seront réalisées par @mariechristineb et @floriancafiero, qui pourront utiliser la numérotation des lignes fournie dans l'aperçu pour identifier leurs commentaires, si cela leur convient. Toutefois, ils seront libres de présenter leurs commentaires comme ils jugeront mieux. Les relecteurs peuvent aussi s'appuyer sur les [consignes aux traducteurs et aux traductrices](https://programminghistorian.org/fr/consignes-traducteurs). 

Les résultats des relectures sont attendus, en commentaires à ce ticket, **d'ici le 10 mars 2020.** Si ce délai ne peut pas être respecté, veuillez m'en informer le plus rapidement possible.

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour que le traducteur ou la traductrice puisse travailler sur la révision de son texte. L'annonce sera faite sur ce fil quand cette étape aura été atteinte.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique (@fdlaramee). Vous avez toujours la possibilité de vous tourner vers notre dispositif de médiation, si vous avez le sentiment qu'une médiation est nécessaire.

**Politique contre le harcèlement**

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (https://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by spapastamkou** [comment]
@fdlaramee j'oubliais: j'ai renommé le fichier pour qu'il ait un slug habituel pour pas qu'il y ait des pb après (manipuler-chaines-caracteres-python.md) et ai modifié le lien fourni ci-dessus. Je laisse les deux autres fichiers avec les noms des traducteurs pour qu'on repère facilement les tutoriels qui ne sont pas encore dans le pipeline.

**Comment by fdlaramee** [comment]
@mariechristineb @floriancafiero @spapastamkou Le processus de relecture de cette traduction est officiellement enclenché. Je n'ai cependant pas réussi à rejoindre la personne qui a réalisé la traduction initiale; il se peut donc que je me charge moi-même des révisions après relecture.

**Comment by mariechristineb** [comment]
@fdlaramee je confirme que j‘ai bien reçu ton message et que je reçois les notifications. J‘ai fait une première relecture il y a quelques jours, je devrais être en mesure de déposer mes commentaires très bientôt.

**Comment by mariechristineb** [comment]
@fdlaramee, voici mes commentaires pour la traductrice:

#### Commentaires généraux

Il s'agit en général d'une bonne traduction, mais je relèverais les points suivants: 

- Il y a un certain manque de cohésion entre différentes parties du texte (ex : différence de terminologie entre le sommaire et le corps du texte).

- Certains termes utilisés ne semblent pas être d’usage courant dans le domaine.

- Certaines formulations qui ne sont pas fautives ou mauvaises gagneraient tout de même à être remplacées par de formulations plus idiomatiques en français. 

#### Suggestions spécifiques

- Ligne 38 : École avec ‘É’

- Ligne 46: ‘Opérateurs de chaînes’

- Ligne 46-55: J’ai l’impression qu’il serait plus uniforme de mettre soit une virgule, soit ‘et’, sur les lignes 46 et 50, et qu’il y ait une certaine unité grammaticale dans les listes (au lieu d’un mélange de verbes et de noms) - je sais que la version anglaise combine les deux, puisqu’il s’agit dans ce cas du nom des méthodes, mais comme en français on peut considérer qu’il s’agit plutôt d’une description de ce que fait la méthode, il n’est peut-être pas nécessaire de suivre l’exemple de la version anglaise dans ce cas. (Peut-être serait-il intéressant d’ajouter le nom anglais de la méthode entre parenthèses, comme à la ligne 152?)

- Ligne 56: ‘d’échappement’

- Ligne 67 : ‘quoi que ce soit’, j’aurais tendance à suggérer de commencer la phrase suivante avec ‘On’ au lieu de ‘L’on’ - ce n’est pas vraiment nécessaire en début de phrase et ça éviterait la répétition, puisque ‘l’on’ apparaît déjà dans la phrase juste avant

- Ligne 73 : astérisque pour l’italique en .md est au mauvais endroit

- Ligne 87 : une grande partie de phrase est en italique alors qu’elle ne devrait pas l’être

- Ligne 96 : espace superflu entre ‘Il’ et ‘y’

- Ligne 106 : ‘manipuler ces chaînes’ au lieu de ‘faire des choses à ces chaînes’?, ‘manière combinée’

- Ligne 118 : remplacer ‘Vous pouvez rechercher une chaîne de caractères pour *une sous-chaîne*’ par quelque chose comme ‘Vous pouvez rechercher une sous-chaîne dans une chaîne de caractères’

- Ligne 145 : ‘une sous-chaîne à travers une chaîne’ → ‘à l’intérieur d’une’?

- Ligne 152: voir ligne 55, garder la même dénomination

- Ligne 175 : ‘Il y a beaucoup d'autres méthodes de chaînes, mais celles vues ci-dessus sont un bon début.’ (l’utilisation du ‘en’ sans référent me semble peu intuitive en français)

- Ligne 179 : ajouter virgule devant ‘puis’

- Ligne 188 : ‘Si vous concevez une chaîne de’ (au lieu de ‘pensez’)? ‘signaler à Python’?

- Ligne 192 : remplacer ‘se fasse une fausse idée’ → ‘que Python se méprenne’?

- Ligne 200 : je pense que ‘tabs’ fait référence à ‘tabulation’ dans ce cas, ‘newline’ semble être traduit par ‘fin de ligne’ (https://fr.wikipedia.org/wiki/Fin_de_ligne)

- Ligne 215 : ‘À la fin’ avec ‘À’

- Ligne 219 : le crochet commence un espace trop tôt, donc l’espace entre les deux mots se trouve souligné aussi

**Comment by fdlaramee** [comment]
Merci @mariechristineb !

**Comment by fdlaramee** [comment]
Bonjour @floriancafiero -- Croyez-vous être bientôt en mesure de compléter cette relecture? Merci de me tenir au courant!

**Comment by fdlaramee** [comment]
Chers collègues et amis,

Les événements se précipitent en ce qui concerne la pandémie de COVID-19. Il est entendu que nous aurons tous et toutes à composer avec des circonstances difficiles et changeantes au cours des prochaines semaines. N'hésitez donc pas à prendre le temps supplémentaire dont vous avez besoin pour compléter les tâches en cours; je vous demande seulement de nous tenir au courant, dans la mesure du possible. 

Solidairement,
FDL

**Comment by floriancafiero** [comment]
Bonjour! 

Et pardon du retard - en effet, l'actualité a été un peu compliquée gérer, toutes mes excuses encore.

Pour @fdlaramee, voici donc mes quelques commentaires.

**Commentaires généraux**

Même jugement global que @mariechristineb sur la traduction, que je trouve très majoritairement correcte, et très lisible malgré quelques anglicismes. 

**Suggestions spécifiques**

Je vois que la plupart des points que j'avais relevé ont déjà été notés par @mariechristineb plus haut. J'en ajoute seulement quelques uns, relativement mineurs:

- l.73 “une chaîne de caractère” ->  “une chaîne de caractères”
- l.77 peut-être ajouter une virgule, la proposition est très longue… Insérer une virgule devant “apparaissent”.
- l.106 "Pour vous assurer que vous avez une connaissance de base des méthodes de chaînes de caractères, **ce qui suit est** un bref aperçu de quelques-unes des méthodes les plus couramment utilisées" lourd, anglicisme ; --> "voici un bref aperçu" ?
- l.169 même observation; insérer une virgule devant “bout”  
- l.169 “Et n'oubliez pas que les positions de l'indice commencent à compter à partir de 0 plutôt que de 1.” anglicisme ? -> “Et n’oubliez que l’on commence à compter les positions de l’indice à partir de  0 plutôt que de 1
- l.187 Insérer une virgule après "message7"
- l.192: "**Que faites-vous** lorsque vous devez inclure des guillemets dans une chaîne de caractères ?" sonne comme un anglicisme --> peut-être plutôt "Que faire lorsque vous devez inclure des guillemets dans une chaîne de caractères ?"

En espérant que tout aille bien pour vous tous,

FC

**Comment by fdlaramee** [comment]
Merci @floriancafiero; je relirai les recommandations contenues dans les deux relectures très bientôt et nous pourrons procéder aux révisions finales.

**Comment by fdlaramee** [comment]
Merci encore @mariechristineb et @floriancafiero pour ce travail de relecture. N'ayant pas été en mesure de reprendre contact avec la traductrice, j'assumerai moi-même dès aujourd'hui les révisions au texte. @spapastamkou je te tiendrai au courant dès que j'aurai terminé pour que nous puissions passer aux dernières étapes de publication. 

À très bientôt,
FDL

**Comment by fdlaramee** [comment]
@spapastamkou J'ai complété les révisions à la traduction moi-même et le fichier est vraisemblablement prêt à publier. Quelques notes:

* Les métadonnées YAML incluent des liens vers la leçon suivante et la leçon précédente dans la liste initiale de Bill Turkel et d'Adam Crymble. Je crois, sans en être certain, qu'il s'agit d'un artéfact à enlever?

* Toujours dans le YAML, la manière d'inclure l'abstract est différente dans les leçons publiées et dans les consignes aux éditeurs. Ces dernières utilisent le caractère pipe ('|') qui n'apparaît pas dans les leçons traduites publiées dont je me suis servi comme modèle. 

* J'ai pris sur moi de traduire les exemples de code pour remplacer Hello World par Bonjour le monde, etc. Je n'ai cependant rien changé au fichier de code téléchargeable.

* La section qui commence autour de la ligne 188 dépend de la présence de la leçon au sein de la série de Turkel et Crymble. Est-ce qu'on la garde? Si oui, il faudra probablement traduire le reste de la série au plus vite parce que le premier élément de la liste, sur les fichiers, est déjà en ligne depuis un bout de temps et que le passage d'une langue à l'autre pourrait finir par être gênant. Qu'en penses-tu?

Voilà, je crois avoir complété mes tâches d'éditeur. S'il en manque, préviens-moi!

Merci,
FDL

**Comment by spapastamkou** [comment]
Merci, @fdlaramee, désolée pour le retard de réagir. Je m'en occupe asap et reviens vers toi.

**Comment by spapastamkou** [comment]
Pour garder une trace, après vérification:
J'ai effectué des modifications mineures sur la forme de md, notamment pour signaler les passages où il y a du code. 
Par ailleurs, j'ai remplacé un lien qui renvoyait à la doc de la version 2 avec un nouveau qui renvoie à celle de la 3.8 concernant la liste des méthodes pour les chaînes de caractère. Je vais demander ta review au PR @fdlaramee, tu me diras si tout est ok pour toi?

@fdlaramee Peux-tu préparer deux tweets pour qu'on les intègre dans le bot Twiter quand le PR sera fait? Sinon, je le ferai, pas de souci. 

Pour tes commentaires: 
No 1: Je vais essayer de les mettre en commentaire pour pas qu'on oublie de les restituer une fois qu'on aura toute la série.
No 2: Pas de souci, normalement cela devrait marcher, le pipe est recommandé surtout quand il y a des guillemets, parenthèses etc dans le résumé
No 3: Je te suis, si tu as jugé que c'est mieux
No 4: Je dirais qu'on garde la leçon telle quelle. Mais pour avoir travaillé sur la série des tutoriels de Python moi-même récemment (pour les recommander à nos étudiants à la fac), il me semble aussi qu'il faut établir comme priorité de les traduire tous. Je peux ouvrir un ticket pour qu'on en discute et le mettre dans le programme.  
Merci!

**Comment by spapastamkou** [comment]
Pull request ici: https://github.com/programminghistorian/jekyll/pull/1736

**Comment by fdlaramee** [comment]
@spapastamkou Tel que mentionné sur le PR et pour en garder la trace: J'ai effectué deux petites corrections: la section Minuscules ne s'affichait pas correctement car il manquait le triple apostrophe pour fermer la section de code précédente; et une paire de parenthèses vides s'affichait lorsque l'on mentionnait la barre oblique inversée. PR approuvé.

**Comment by fdlaramee** [comment]
@spapastamkou Pour ce qui est des tweets, que dirais-tu de:

1. Apprenez à manipuler les chaînes de caractères en Python grâce à cette leçon de William J. Turkel et Adam Crymble, traduite par Camille Carette. 

2. "Manipuler les chaînes de caractères en Python": une leçon de William J. Turkel et @acrymble traduite par Camille Carette.

Pas très original, je sais, mais il est difficile de faire autrement compte tenu du sujet.

**Comment by spapastamkou** [comment]
@fdlaramee Merci beaucoup, j'intègre dans le bot Twitter

**Comment by spapastamkou** [comment]
Cette leçon est maintenant en ligne: https://programminghistorian.org/fr/lecons/manipuler-chaines-caracteres-python
