### ISSUE TITLE
Ticket de revisión: Análisis de sentimientos en R

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#286]
The Programming Historian en español ha recibido la siguiente propuesta de tutorial "Análisis de sentimientos en R con 'syuzhet'" por parte de @jenniferisasi . Este tutorial se encuentra en estos momentos en fase de revisión por parte de @rivaquiroga. Puede leerse en:

## Texto
http://programminghistorian.github.io/ph-submissions/es/lecciones/analisis-de-sentimientos-r

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/analisis-de-sentimientos-r.md

## Imágenes
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/analisis-de-sentimientos-r

Puedes utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra 'ombudperson' (Silvia Gutiérrez
- http://programminghistorian.org/es/equipo-de-proyecto)

# Política contra el acoso

El objetivo de 'The Programming Historian en español' es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestra 'ombudsperson' (Silvia Gutiérrez - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by rivaquiroga** [comment]
¡Hola Jennifer!
Muchas gracias por tu propuesta de lección. Aborda un tema de interés para las humanidades y para el que no hay tantos recursos disponibles que discutan cómo realizarlo en español. Sin duda que será un gran aporte para The Programming Historian. Es una muy buena idea, además, haber escrito la lección usando recursos que faciliten luego su traducción (por ejemplo, usando un diccionario de sentimientos/emociones multilingüe). 

Voy a dividir la revisión en dos. En esta primera parte me concentraré en el contenido de la lección, sobre todo en el código. En la segunda parte, que espero tener lista la próxima semana, me referiré a aspectos de estilo y formato. 

---
### Revisión: primera parte

- [x]  ¶2
La lección funciona con la última versión de R disponible (3.6.2 o 3.6.3, dependiendo del sistema operativo). Creo que sería mejor decir que funciona con esa versión, más que con la 3.5.2, que es de 2018. De todos modos, sería bueno probarla de nuevo cuando salga la próxima (4.0.0), que estará disponible a partir de la próxima semana.

- [ ] ¶3
Agregaría Linux a los comentarios sobre sistemas operativos. Las indicaciones para Linux suelen ser las mismas que para Mac. Probé en Ubuntu 18.04 y funciona todo bien. 

- [x]  ¶7
Aclararía que NRC no es el único diccionario de sentimientos incluído en `syuzhet`. También está bing, afinn y stanford. Pero en esta lección se usa NRC porque tiene versión en español (y no implica instalar paquetes adicionales, como el diccionario stanford).

- [x]  ¶16
Trataría de evitar el uso de "lista(do)" para hacer referencia a un vector de caracteres, ya que la lista es un tipo distinto de estructura de datos. 

- [x] ¶15
Me gusta mucho esta sección. Es una muy buena idea mostrar brevemente el panorama general y en el último párrafo enfatizar las posibilidades que existen y el valor de una buena pregunta de investigación.

- [x]  ¶24-25
No es necesario instalar el paquete `NLP` ni cargarlo con `library(NLP)`. Es una dependencia de `syuzhet` y de `tm`, por lo que al instalar estos paquetes se instala también. Y cuando se ejecuta `library(tm)` `NLP` queda también disponible. Como no se ocupa ninguna función de él directamente, sería mejor no incorporarlo en el script ni mencionarlo en la lección.

- [x]  ¶25-30
Sería mejor no poner toda la ruta del archivo, sino solo `"galdos_miau.txt"`. Si asumimos que las personas que usarán la lección saben cómo importar un archivo, sea cual sea el sistema que prefieran para gestionar su directorio de trabajo, tener que copiar el código con una ruta de una máquina distinta no resulta útil. 
Si están trabajando en un proyecto de RStudio, si determinaron su directorio de trabajo con `setwd()` o si ocupan `here::here()`, lo más práctico es tener solo el nombre.

Algo que también se podría considerar es que en la lección se entregue el código para descargar el archivo directamente al directorio en que está abierto R actualmente:

```r
download.file("https://raw.githubusercontent.com/programminghistorian/ph-submissions/gh-pages/assets/galdos_miau.txt", "galdos_miau.txt", mode = "wb")
```

Eso haría funcionar el código utilizando solo el nombre del archivo, incluso si uno no sabe en qué directorio está actualmente R, ya que la descarga se hace por defecto hacia el directorio activo. 

Otra opción sería leer directamente el archivo desde el repositorio de Github. Tanto `get_text_as_string()` como `scan()` pueden leer una url como ruta del archivo. Es decir, se podría modificar el código así:

```r
texto_cadena <- get_text_as_string("https://raw.githubusercontent.com/programminghistorian/ph-submissions/gh-pages/assets/galdos_miau.txt")
```

Y para Windows:

```r
texto_cadena <- scan(file = "https://raw.githubusercontent.com/programminghistorian/ph-submissions/gh-pages/assets/galdos_miau.txt", fileEncoding = "UTF-8", what = character(), sep = "\n", allowEscapes = T)
```

(Ejemplifico con la url en la que está actualmente el archivo; luego habría que cambiarla por la definitiva).

- [x] ¶31
A lo largo de la lección se usa de manera consistente `"` para los argumentos de las funciones y espacio antes y después de `=`, excepto en el código de `scan()`. Se podría ajustar para que quede con el mismo estilo que el resto del código del tutorial. 

- [x]  ¶31-33 
Resulta un poco confusa la forma en que se nombraron estos objetos. `texto_cadena` es un vector, al igual que `texto_vector`. Quizás se podría llamar `texto_tokens` o `texto_palabras`.

- [ ]  ¶35
En Windows el resultado de la extensión en oraciones es diferente (poco más de 13000). Quizás se podría ajustar el código para que se obtenga la misma extensión, o bien explicar por qué el resultado es distinto para que quienes sigan la lección no piensen que hubo algún error. O al menos solo advertir que el resultado puede no ser el mismo. 

- [x]  ¶35-37
No me queda tan claro por qué sería mejor guardar "spanish" como un objeto independiente, si puedo indicarlo directamente en el argumento de la función. Es decir, esto:

```r
leng_espanol <- "spanish"  
sentimientos_df <- get_nrc_sentiment(texto_vector, lang=leng_espanol)
```

es lo mismo que esto:

```r
sentimientos_df <- get_nrc_sentiment(texto_vector, lang = "spanish")
```

- [x]  ¶35
Se podría señalar que al ejecutar el código aparecerá una advertencia. Para convertir el vector de texto en un data frame, `get_nrc_sentiment()` utiliza una función que está deprecada, por eso sale esto:

```
Warning message:
`data_frame()` is deprecated as of tibble 1.1.0.
Please use `tibble()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
```

Además, sugiero poner una estimación del tiempo que toma ese código en ejecutarse. En las computadoras en que probé tomó entre 15 y 30 minutos. Eso permite ajustar expectativas sobre cuánto esperar. 

- [x]  ¶39
Sería interesante decir algo sobre la mediana. La mitad de los datos está en valor 0; incluso hasta el tercer cuartil está en ese valor. Eso, por ejemplo, indicaría que son pocas las palabras para las que existe asignación de sentimiento/emoción.

- [x] ¶42 - 44
Es muy buena la idea de mostrar qué pasa si edito o no el gráfico. 
Advertiría que puede que no se vean todos los nombres de columnas en el panel Plots, pero que si se agranda o se hace zoom aparecen.
Actualmente las columnas se visualizan en orden alfabético. Quizás se podrían ordenar por tamaño para que sea más fácil la comparación.

- [x]  ¶46 (nota 2)
Me parece que esta nota no es necesaria. Si no tienen nombre igual es posible acceder a las columnas. En ese caso se hace por posición. Es decir, 

```r
palabras_tristeza <- texto_vector[sentimientos_df$sadness > 0]
```

es lo mismo que

```r
palabras_tristeza <- texto_vector[sentimientos_df[,6]> 0]
```

(de hecho, en ¶64 se usa esta última forma. Más adelante hay un comentario al respecto).

- [x] ¶48 
Si solo se ejecuta `palabras_tristeza_orden` en la consola se imprimen todas las palabras, las 349. Quizás se podría imprimir solo las 12 primeras, tal como aparece en la lección. Es decir, cambiar esa línea por `head(palabras_tristeza_orden, n = 12)`

- [x] ¶54, 56 y 57

Se sugiere utilizar `<-` en vez de `=` para la asignación. Así hay consistencia con el código escrito antes.

- [x]  ¶57
matriz de términos: sería más preciso decir matriz término documento.

- [x]  ¶59
Sugeriría  volver a ejecutar `head(nube_tdm)`  para asegurarse de que los nombres de columna quedaron puestos. Así las personas pueden ver cuál fue el cambio que se hizo:

```
> head(nube_tdm)
              Docs
Terms          tristeza felicidad enfado confianza
  abandonado          4         0      4         4
  abandonar           1         0      0         1
  abandonará          2         0      0         2
  abandonaré          1         0      0         1
  abandonarías        1         0      0         1
  abandono            3         0      3         3
```
  

- [ ] ¶60
Para generar la nube sugiero utilizar una semilla para que sea replicable. Así, a quienes sigan la lección les aparecerá en su computadora la misma nube que la publicada:

```
set.seed(777) # puede ser cualquier número, puse este como ejemplo
comparison.cloud(nube_tdm, random.order = FALSE,
                 colors = c("green", "red", "orange", "blue"),
                 title.size = 1, max.words = 50, scale = c(2.5, 1), rot.per = 0.4)
```
Esto implicaría cambiar la imagen que está en `/images` por la versión con semilla. 

- [x] ¶62
Sería interesante que se pudiera comentar algo sobre el resultado de la nube. Por ejemplo, retomar algunas de la advertencias que se dan al inicio de la lección sobre el etiquetado de emociones, sobre todo porque hay palabras en las que llama la atención la emoción que les fue asignada. ¿Por qué "caballero" aparecerá en enfado? ¿O "muy" en tristeza?

- [x] ¶64
Como las columnas tienen nombre, sería más claro si se alude a ellas por él, más que por la posición. Es decir, el código se podría reescribir así:

```r
sentimientos_valencia <- (sentimientos_df$negative *-1) + sentimientos_df$positive
```


- [ ] ¶65
Respecto de `simple_plot(sentimientos_valencia)`, sería bueno dar dos advertencias. La primera, que dependiendo de la máquina en la que uno esté trabajando, puede tomar hasta 20-30 minutos en generarse. La segunda, que es posible que aparezca este error si es que el panel para gráficos no es lo suficientemente grande (por ejemplo, cuando está en el tamaño por defecto de RStudio en una computadora con una pantalla no muy grande):

```r
Error in plot.new() : figure margins too large
```
 
Si están en RStudio, antes de ejecutar el código se puede maximizar el panel Plots para que ocupe todo el lado derecho y no solo la mitad de abajo.

Sería ideal si el eje `x` de la primera imagen no estuviese con notación científica. Así quedaría más claro que va de 0 a 100000 porque la extensión del texto es 97254 palabras.


- [ ] _Otros_
Hay un archivo que se llama "ejemplo" dentro de `/images`, pero no se usa en la lección y tampoco es posible visualizarlo.

**Comment by jenniferisasi** [comment]
Muchas gracias @rivaquiroga por esta tan detallada revisión. Por un lado, se comprueba que sabes más R que yo y, por otro, se confirma que una cosa es usar el código y otra explicarlo. Voy a esperar a la segunda parte para hacer modificaciones, ¿te parece? Bueno, y si le parece también a @mariajoafana, y así no hacemos tantos pasos intermedios.

**Comment by mariajoafana** [comment]
Mientras Riva termina la segunda parte de la revisión, vamos a buscar un segundo revisor. Cuéntenme si tiene alguna sugerencia

**Comment by jenniferisasi** [comment]
Tendré que cambiar el formato de poner las imágenes y añadir la "alt" tag porque se me olvidó.

**Comment by mariajoafana** [comment]
Ya tengo a un revisor interesado en hacer la segunda revisión, dice que podría tenerla entre las dos primeras semanas de junio, así nos da tiempo para que Riva termine su revisión y Jennifer incorpore la primera ronda de comentarios

**Comment by mariajoafana** [comment]
@rivaquiroga ¿cuándo crees que puedes terminar la revisión?

**Comment by jenniferisasi** [comment]
Pasando por aquí para que no se me olvide que tengo esto pendiente... y ya es septiembre [emoji con la mano en la cara]. @rivaquiroga si todavía no puedes hacer la segunda vuelta, puedo ir introduciendo los cambios de tu primera revisión.

**Comment by rivaquiroga** [comment]
La segunda parte de revisión iba a ser la revisión de estilo. Pero ahora que con @mariajoafana tenemos casi lista la nueva versión de la guía de autores (hoy en la tarde enviaré un correo al equipo al respecto) está lección podría ser la primera en que usemos el servicio de copyediting. ¿Qué les parece?

**Comment by jenniferisasi** [comment]
A mí me parece bien, y entonces puedo integrar ya los cambios que me pedías para una segunda revisión. Y gracias por trabajar en la guía :) 

He puesto unas checkboxes en el comentario/revisión de Riva para asegurar de que hago todos los cambios.

**Comment by mariajoafana** [comment]
Si, me parece!

**Comment by jenniferisasi** [comment]
Riva, sobre el comentario del párrafo 3 re Linux. Yo no tengo acceso a dicho sistema, ¿te referías a ponerlo en todas las partes donde añado alguna diferencia en el código para Windows?

**Comment by jenniferisasi** [comment]
- [ ] Pendiente cambiar la URL de descarga del texto
- [ ] 
- [ ] Sobre esto: 
  ¶35
En Windows el resultado de la extensión en oraciones es diferente (poco más de 13000). Quizás se podría ajustar el código para que se obtenga la misma extensión, o bien explicar por qué el resultado es distinto para que quienes sigan la lección no piensen que hubo algún error. O al menos solo advertir que el resultado puede no ser el mismo.

En Windows salen 13000 oraciones? Pues aquí sí que me atasco porque no tengo como comprobar dónde es que se parten las oraciones a que sean así el doble que con Mac. 

- [ ] Esto es nuevo para mí, y al hacerlo me siguen saliendo diferentes nubes

set.seed(777) # puede ser cualquier número, puse este como ejemplo
comparison.cloud(nube_tdm, random.order = FALSE,
                 colors = c("green", "red", "orange", "blue"),
                 title.size = 1, max.words = 50, scale = c(2.5, 1), rot.per = 0.4)

**Comment by rivaquiroga** [comment]
> Riva, sobre el comentario del párrafo 3 re Linux. Yo no tengo acceso a dicho sistema, ¿te referías a ponerlo en todas las partes donde añado alguna diferencia en el código para Windows?

Sí. Es decir, cada vez que aparezca "En Mac", indicar "En Mac y Linux". En general se comportan igual. Y en este caso en particular lo probé en los dos.

**Comment by rivaquiroga** [comment]
> * [ ]  Pendiente cambiar la URL de descarga del texto
> * [ ]
> * [ ]  Sobre esto:
>   ¶35
>   En Windows el resultado de la extensión en oraciones es diferente (poco más de 13000). Quizás se podría ajustar el código para que se obtenga la misma extensión, o bien explicar por qué el resultado es distinto para que quienes sigan la lección no piensen que hubo algún error. O al menos solo advertir que el resultado puede no ser el mismo.
> 
> En Windows salen 13000 oraciones? Pues aquí sí que me atasco porque no tengo como comprobar dónde es que se parten las oraciones a que sean así el doble que con Mac.
> 
> * [ ]  Esto es nuevo para mí, y al hacerlo me siguen saliendo diferentes nubes
> 
> set.seed(777) # puede ser cualquier número, puse este como ejemplo
> comparison.cloud(nube_tdm, random.order = FALSE,
> colors = c("green", "red", "orange", "blue"),
> title.size = 1, max.words = 50, scale = c(2.5, 1), rot.per = 0.4)

Sobre Windows, sí, el resultado que aparece es diferente. Voy a volver a probarlo para ver cómo se podría ajustar el código o qué se podría poner como explicación.

**Comment by jenniferisasi** [comment]
> > * [ ]   Pendiente cambiar la URL de descarga del texto
> > * [ ]
> > * [ ]   Sobre esto:
> >   ¶35
> >   En Windows el resultado de la extensión en oraciones es diferente (poco más de 13000). Quizás se podría ajustar el código para que se obtenga la misma extensión, o bien explicar por qué el resultado es distinto para que quienes sigan la lección no piensen que hubo algún error. O al menos solo advertir que el resultado puede no ser el mismo.
> > 
> > En Windows salen 13000 oraciones? Pues aquí sí que me atasco porque no tengo como comprobar dónde es que se parten las oraciones a que sean así el doble que con Mac.
> > 
> > * [ ]   Esto es nuevo para mí, y al hacerlo me siguen saliendo diferentes nubes
> > 
> > set.seed(777) # puede ser cualquier número, puse este como ejemplo
> > comparison.cloud(nube_tdm, random.order = FALSE,
> > colors = c("green", "red", "orange", "blue"),
> > title.size = 1, max.words = 50, scale = c(2.5, 1), rot.per = 0.4)
> 
> Sobre Windows, sí, el resultado que aparece es diferente. Voy a volver a probarlo para ver cómo se podría ajustar el código o qué se podría poner como explicación.

He mirado la guía de _syuzhet_ y _tokenizer_ y no dice nada de la diferencia de Windows, pero Jockers sí añade algo sobre las comillas que marcan el diálogo en inglés ... me pregunto si tendrá algo que ver con el guión de diálogo en español?

**Comment by rivaquiroga** [comment]
¡Hola! Probé en otro computador con Windows y resultó todo bien. En el que había probado la primera vez había un problema con la codificación de caracteres, así que una vez que arreglé eso anduvo todo bien.

Con relación a:
```
set.seed(777) # puede ser cualquier número, puse este como ejemplo
comparison.cloud(nube_tdm, random.order = FALSE, colors = c("green", "red", "orange", "blue"),
title.size = 1, max.words = 50, scale = c(2.5, 1), rot.per = 0.4)
```
Si ejecutas `set.seed()` + ` comparison.cloud()` te debería salir la misma nube siempre que ejecutes las dos líneas seguidas. Si ejecutas las dos y luego vuelves a ejecutar solo ` comparison.cloud()`  va a mostrar una distinta. 
`set.seed()` se suele utilizar para hacer reproducible el resultado de las funciones que incluyan algún componente de aleatoridad (en este caso, cómo se ordenan las palabras). Sugiero incluirlo para que a quienes sigan la lección les aparezca la misma nube que verán en ella.

**Comment by jenniferisasi** [comment]
Qué bueno @rivaquiroga, gracias por comprobar que funciona en Windows. 

Voy a hacer el cambio de `set.seed` que me enseñas - pues no lo sabía usar - ya que, sí, me parece buena idea que aparezca la misma nube para evitar confusión por parte de los usuarios. Me pongo a ello.

**Comment by jenniferisasi** [comment]
Pues queda lista para otra revisión o publicación según veáis @mariajoafana y @rivaquiroga

**Comment by rivaquiroga** [comment]
@mariajoafana, la decisión sobre si es necesaria otra revisión te corresponde a ti como editora. ¿Te parece que la publiquemos así? ¿O buscamos a otra persona que pueda revisarla?

**Comment by rivaquiroga** [comment]
¡Hola, @mariajoafana! Solo pasaba por acá para saber qué habías decidido respecto de la revisión de la lección. ¿Buscamos a alguien más? ¿O publicamos la lección?

**Comment by rivaquiroga** [comment]
¡Hola, @mariajoafana! ¿Qué has pensado sobre cómo seguir con esta lección? ¿Quieres que busquemos a otra persona para revisar? ¿O te parece que ya la podríamos publicar?

**Comment by mariajoafana** [comment]
Hola! Poniéndome al día. Estuve revisando y me parece que es sólida y que ya tuvo un proceso de revisión juicioso y con pruebas tanto en Mac como en Windows. Yo digo, adelante.

**Comment by rivaquiroga** [comment]
Muchas gracias, @mariajoafana. Voy a mover, entonces, la lección y las imágenes al otro repositorio. @jenniferisasi, ¿publicamos la lección ahora? ¿O la dejamos para la semana de la charla de INTELE?

**Comment by jenniferisasi** [comment]
@rivaquiroga espera si quieres unos días, coincidiendo o no con INTELE, más que nada para que no choque con la publicación de Jekyll :) así nos repartimos los anuncios.

**Comment by rivaquiroga** [comment]
De acuerdo! Esta semana publicamos la de Jekyll y también estará el evento del Día de los Datos Abiertos, así que mejor esperar hasta fines de la próxima para darle el protagonismo que merece

**Comment by jenniferisasi** [comment]
@mariajoafana voy a hacer unos cambios mínimos (hablados con @rivaquiroga) en la lección por un update reciente en el paquete que uso y que es importante anunciar aunque no lo use en la lección. Aviso cuando esté preparado bien.

**Comment by rivaquiroga** [comment]
Buenísmo. Aprovecho de contarles que ya tenemos el presupuesto aprobado para que esta sea la primera lección en pasar por copyediting. @jamotilla estará a cargo :rocket:

**Comment by jenniferisasi** [comment]
> Buenísmo. Aprovecho de contarles que ya tenemos el presupuesto aprobado para que esta sea la primera lección en pasar por copyediting. @jamotilla estará a cargo 🚀

Voy a añadir entonces hoy mismo un parrafito al final sobre el uso de un vocabulario personalizado para poder iniciar el _copy-editing_ y publicarla para el evento.

**Comment by jenniferisasi** [comment]
He modificado un poco el cuadro de advertencia entre los párrafos 11 y 14. 

Me he puesto a añadir una sección al final de la lección y aquí es que me topo con la piedra, como siempre que utilizo las instrucciones de Syuzhet u otros... @rivaquiroga la sección de custom lexicons no añade nombres para las columnas, y solo aparece el sentimiento (las emociones, no). Con ello, no se puede hacer todo lo que hago en el tutorial (la nube, las barras de las emociones). Y puesto que el gráfico en "Visualizar la evolución de sentimientos en el texto" se hace con un cálculo de dos columnas ... ahora no sé cómo proceder 😬🤔 

update: se puede hacer un plot básico con plot(x, type = "l")

Voy a tratar unos trucos que se me ocurren, pero puede que este se atore más de lo que pensaba.

**Comment by rivaquiroga** [comment]
@jenniferisasi, quizás podrías explicar esas limitaciones. La idea tampoco es que te compliques demasiado. El objetivo del tutorial es mostrar cómo usar el diccionario que viene incorporado en syuzhet. Lo del final sería una sugerencias sobre cómo seguir profundizando, así que no creo que sea imprescindible que muestres todo el proceso de análisis con un diccionario propio.

**Comment by jenniferisasi** [comment]
Así lo haré entonces @rivaquiroga. Pensaba que sería más sencillo pero nada.

**Comment by jenniferisasi** [comment]
Creo que entonces la lección queda ya lista para el copyediting @rivaquiroga y @jamotilla

**Comment by jamotilla** [comment]
Perfecto, entonces comienzo con el proceso @rivaquiroga ?

**Comment by rivaquiroga** [comment]
@jamotilla, sí! Muchas gracias :rocket:

**Comment by jamotilla** [comment]
Estimadas, he hecho la primer revisión y edición al texto. @jenniferisasi te pido por favor lo revises y me indiques si estás de acuerdo con los cambios sugeridos. He trabajado en el siguiente branch: https://github.com/programminghistorian/ph-submissions/blob/Copyedit-analisis-de-sentimientos-r/es/lecciones/analisis-de-sentimientos-r.md

Saludos!

**Comment by rivaquiroga** [comment]
Muchas gracias, @jamotilla!
@jenniferisasi, @mariajoafana en este enlace se pueden visualizar los cambios: https://github.com/programminghistorian/ph-submissions/compare/gh-pages...Copyedit-analisis-de-sentimientos-r

Si están de acuerdo con las modificaciones, estaríamos listas para publicar.

**Comment by jenniferisasi** [comment]
¡Gracias @jamotilla por tan detallada edición! Algunas instrucciones quedaron así más claras. En general, todo me parece bien pero sí me gustaría regresar al original en un par de cosas, porque los cambios realizados cambian el sentido del mensaje. Como creo que no se puedo comentar ahí en la comparación misma, dejo aquí por número de línea: 

**En el texto**
- [ ] 50: saber por hablar; puse 'saber' porque para mí 'hablar' implica comunicación (normalmente oral) y hay gente que se defiende leyendo inglés (u otros idiomas) pero no lo hablan. [esto es uno de esas cosas que no son cruciales]
- [ ] 54: los verbos están originalmente en el tiempo presente porque Jockers sigue a ello; entonces dentro de un mes puede que añada algo... [otra cosa no crucial]
- [ ] 56: Aquí sí, me gustaría dejar mi oración original. Aunque 'por descontado' y 'por defecto' implican más o menos lo mismo, el paquete podría haber sido desarrollado en/para otro idioma porque no es un requisito hacerlo en inglés (que entonces sí sería 'por defecto'), pero quiero apuntillar un "obviamente" (irónico) con el 'por descontado'. ¿Los demás lo entendéis así? 
- [ ] 56: Mismo lugar, "traducidos al inglés y no sin debate sobre " es una oración compuesta con dos elementos que no son consecuencia la segunda de la primera; al cambiarlo a "al inglés, lo cual ha suscitado debates"  implica que el debate es consecuencia del inglés, pero en realidad es por querer cuantificar algo tan subjetivo como las emociones.
- [ ] 323: ambos nos hemos comido la tilde en "fácilmente" 

**En las referencias**
- [ ]  @rivaquiroga Antonio añadió un (blog) ahí pero no se trata de un blog, yo lo había puesto la referencia de R como me enseñaste. Jockers, Matthew L. "Introduction to the Syuzhet Package", 2017 (blog). https://mran.microsoft.com/snapshot/2017-12-31/web/packages/syuzhet/vignettes/syuzhet-vignette.html 


Lo dejo así en mano de la editora jefa, no siendo que falte algo que no haya visto.

**Comment by rivaquiroga** [comment]
@jamotilla, lo de cómo citar software todavía no aparece en la guía actual así que no tenías cómo saberlo (está en este PR: https://github.com/programminghistorian/jekyll/pull/2077). Una de las indicaciones ahí es citarlo como los autores sugieran (que es lo que hizo Jennifer), así que sugiero dejarlo como ella lo había puesto (además, porque más que un blog es una "vignette", un tipo de documentación de los paquetes de R). 
El fácilmente se nos pasó a todos :flushed:
Respecto de la línea 56, en la nueva redacción se pierde un poco el tono que quería darle Jennifer. Tanto ahí como en la línea 50 sugeriría revertir el cambio.
Respecto de 54, sospecho que tenemos una interpretación distinta por la variedad de español. El "ha introducido cambios" de José Antonio no me suena a acción terminada en el pasado (en ese caso usaría "introdujo cambios"), sino como algo que ha estado haciendo continuamente desde 2015. Así que en ese sentido transmite la idea de que podría introducir cambios en el futuro. 
@jamotilla, ¿puedes actualizar tu branch según esto?

**Comment by jamotilla** [comment]
Genial @jenniferisasi y @rivaquiroga ! Voy a actualizar el branch con sus observaciones. Mañana por la mañana queda listo. Saludos

**Comment by jamotilla** [comment]
Hola @jenniferisasi, ¿Te parece que agregue la dirección web al recurso que refieres de Jockers? Quedaría así:

471: Jockers, Matthew L. "Introduction to the Syuzhet Package", CRAN R Project, 2017. https://mran.microsoft.com/snapshot/2017-12-31/web/packages/syuzhet/vignettes/syuzhet-vignette.html

**Comment by jenniferisasi** [comment]
Sí @jamotilla la puedes añadir. No sé por qué yo no la puse.

**Comment by jamotilla** [comment]
Perfecto! @rivaquiroga he actualizado el branch

**Comment by rivaquiroga** [comment]
¡Muchas gracias @jamotilla! Comenzaré el proceso de publicación, entonces

**Comment by rivaquiroga** [comment]
@mariajoafana, como estamos medias apuradas porque queremos tener publicado el tutorial para el taller que haremos el jueves con @jenniferisasi, te salté y elegí yo la imagen de la lección para poder mover todo al otro repositorio :grimacing:. 

Ya pueden ver la previsualización acá: https://deploy-preview-2088--ph-preview.netlify.app/es/lecciones/analisis-de-sentimientos-r. Apenas aprueben el PR publicamos :rocket:

@mariajoafana, lo único que faltaría hacer es que agregues la lección al bot de twitter.

**Comment by rivaquiroga** [comment]
¡Lección publicada! Muchas gracias por su trabajo. Ahora tenemos la sexta lección original en español :tada: 
El DOI debería quedar activo mañana en la mañana, cuando sea horario hábil en UK
Apenas @mariajoafana confirme que la lección quedó en el bot, cerramos el ticket

**Comment by jenniferisasi** [comment]
Yo vengo a decir: @rivaquiroga me encanta la imagen que le pusiste a la lección 🎉

**Comment by rivaquiroga** [comment]
DOI activo: https://doi.org/10.46430/phes0051 :tada:

**Comment by rivaquiroga** [comment]
@mariajoafana, esta lección nunca fue agregada al bot de Twitter. ¿Cuándo crees que podrías incorporarla? Si necesitas apoyo con eso, me avisas.

**Comment by rdas1lva** [comment]
Olá! Obrigado pela excelente lição, usei o código com os meus dados e funcionou muito bem . Contudo necessito de ajudar num pormenor, como consigo ver os valores do barplot da análise de sentimento? já tentei vários códigos mas não consegui visualizar os dados. Obrigado!

Hi! thanks for the excellent lesson! I already use it with my dada, and it worked perfectly. However, can how you can see the data from the sentiment analysis barplot? I have tried different codes but have yet to succeed; I always get an error message. Obrigado!
