### ISSUE TITLE
Proposition de traduction en français: Rédaction durable avec Pandoc et Markdown

### ISSUE THREAD

**Issue by mariechristineb** [programminghistorian/ph-submissions#289]
Je propose la traduction en français de la leçon "Sustainable Authorship in Plain Text using Pandoc and Markdown", sous le titre "Rédaction durable avec Pandoc et Markdown." 

La traduction est complète et disponible au https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/redaction-durable-avec-pandoc-et-markdown.md.

Le processus de révision débutera dès qu'un(e) membre de l'équipe sera disponible pour se charger de la rédaction.

**Comment by spapastamkou** [comment]
@mariechristineb Serais-tu en mesure de faire une estimation de date à peu près? C'est notamment pour mettre à jour le ticket https://github.com/programminghistorian/jekyll/issues/1642 avant de le fermer et prévoir le prochain. merci!

**Comment by mariechristineb** [comment]
@spapastamkou fin mai, ça irait?

**Comment by spapastamkou** [comment]
@mariechristineb Merci, c'est pour mieux renseigner les tickets et savoir où on en est.

**Comment by spapastamkou** [comment]
Je prends en charge le suivi éditorial de cette traduction et je me lance dans la recherche de relecteurs. Je fermerai ce ticket une fois le processus de relecture entamé.

**Comment by spapastamkou** [comment]
Le tutoriel est maintenant en cours de relecture (cf. #307).
