### ISSUE TITLE
Cambio de dataset en Procesamiento básico en R

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#290]
@programminghistorian/spanish-team propongo, durante el verano, editar mi propia traducción de [Procesamiento básico de textos en R](https://programminghistorian.org/es/lecciones/procesamiento-basico-de-textos-en-r) para que contenga un dataset en español y, por tanto, sea más útil a nuestra audiencia. 

Creo que fue lo primero que traduje y todavía no teníamos muy claro lo de cambiar datasets y ahora es una espinita que tengo clavada. 

Este ticket permanecerá abierto bastante tiempo, pero quería abrirlo para: 

1) ¿Os parece bien? 
2) Problema: el dataset en inglés tiene 236 discursos, un número excelente para este tipo de trabajo...¿alguien sabe de algún país con tanto discurso en su historia y de fácil acceso? Voy a ver is encuentro tantos de España, pero me parece que no serán tantos (14 discursos de investidura)

**Comment by arojascastro** [comment]
A mí me parece muy bien, siempre y cuando tengas tiempo y ganas de hacerlo :) 

Como editor de la lección, puedo documentar el proceso en el ticket antiguo y ayudarte a publicar la lección. Sería como una "actualización".

En cuanto al dataset, pues, creo que en la lección de Voyant hay un dataset de discursos latinoamericanos que se podría reutilizar aquí. De hecho, sería cool comparar los resultados con distintos métodos...

**Comment by jenniferisasi** [comment]
Lo pensé @arojascastro pero el tipo de dataset no es el mismo. En el original tenemos uno por año (o algo así) y todos del mismo país (se repiten o no presidentes). En el de Voyant tenemos 25 documentos que abarcan 5 años, con varios presidentes por año. Esto significaría cambiar las preguntas y, por tanto, el código, la estructura de la lección cuya idea iría más por localización. 

Tengo por algún sitio empezado un corpus con los discursos de la RAE, pero necesitaría tiempo para crearlo bien; y he encontrado unos de los dos reyes... de 1975 a 2018, y dice "Todos los textos reproducidos provienen de: http://www.casareal.es/ES/ actividades/Paginas/actividades_discursos.aspx" pero la página va lenta...para comprobar si los puedo usar o no. A ver si tengo suerte.

Esto me lo voy a tomar con calma.

**Comment by jenniferisasi** [comment]
PS: me he dado cuenta que hay una imagen mal (duplicada). y sería más fácil de seguir si todas las líneas de código estuvieran en una "cajita"

**Comment by arojascastro** [comment]
Vaya editor más malo te ha tocado. ¿Cómo lo solucionamos?

**Comment by jenniferisasi** [comment]
Sigo dándole vueltas a esto... he encontrado un [listado de 10,000 palabras más frecuentes de RAE](http://corpus.rae.es/frec/10000_formas.TXT?fbclid=IwAR1ECKY_UzT8drFP0xlfXUtCy_yv_r8aSD3i-M1e5W7NUSpuEN0aApEPhu4) que tiene las frecuencias diferentes así que tendría que ajustar... o traducir automáticamente el listado de 1/3 millón de palabras frecuentes de Google que se usa en la lección. Pero todavía sigo a la búsqueda de un corpus similar ... nada más para decir que de vez en cuando me acuerdo que tengo este ticket abierto.

```
language,word,frequency
en,the,3.933837507090547
en,of,2.2362525338300485
en,and,2.2100157619537026
en,to,2.063676420967823
en,a,1.5440912627459127
en,in,1.4400707674149293
en,for,1.0088551882990706
en,is,0.8001275333472513
en,on,0.6376923565241907
en,that,0.5781144503654221
en,by,0.5696158661744654
en,this,0.5489435157037872
en,with,0.5412310130652157
en,i,0.5247573847611146
en,you,0.509446970921778
en,it,0.47832817922470977
en,not,0.44777736583653305
en,or,0.4405089635955221
en,be,0.4078601220057391
en,are,0.40699137832462096
en,from,0.38692427175953603
en,at,0.3863593258032305
en,as,0.3821355528064133
en,your,0.3506175185821025
en,all,0.3438831081224539
en,have,0.2659646884637137
en,new,0.2637637746846681
en,more,0.2626607815112298
en,an,0.2581540824006962
en,was,0.25223050285674836
```

**Comment by jenniferisasi** [comment]
Cierro esto de momento por falta de solución.
