### ISSUE TITLE
Proposition de traduction: Downloading Multiple Records Using Query Strings

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#292]
Je propose la traduction en français de la leçon suivante: [Downloading Multiple Records Using Query Strings](https://programminghistorian.org/en/lessons/downloading-multiple-records-using-query-strings).  

La date envisagée pour finaliser cette traduction est le 3 juillet 2020. 

A noter que cette traduction se fera via le dispositif [GitLocalize](https://gitlocalize.com/) que je teste à cette occasion pour le compte de l'équipe technique du PH @programminghistorian/technical-team  (selon https://github.com/programminghistorian/jekyll/issues/1571).

**Comment by spapastamkou** [comment]
(je t'assigne aussi @mariechristineb pour me contrôler:-))

**Comment by mariechristineb** [comment]
@spapastamkou as-tu des nouvelles à propos de ce ticket?

**Comment by spapastamkou** [comment]
Merci pour le rappel! Cela n'a malheureusement pas beaucoup avancé, mais je reviendrai sous peu avec plus de nouvelles ou un planning plus précis.

**Comment by spapastamkou** [comment]
Je vais fermer ce ticket parce que depuis un an je n'arrive pas à dégager du temps pour avancer. J'espère être en mesure de l'ouvrir à nouveau.
