### ISSUE TITLE
Proposition de traduction: Installing Python Modules with pip

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#293]
Le Programming Historian en français a reçu une proposition de traduction de la leçon suivante: [Installing Python Modules with pip](https://programminghistorian.org/en/lessons/installing-python-modules-pip) de la part de @Lucaterre. 

La date envisagée pour recevoir cette traduction est le 12 juillet 2020 sachant que celle peut être revue en fonction des possibilités du traducteur.

**Comment by Lucaterre** [comment]
Bonjour, 

La traduction est terminée, je l'ai versé dans `ph-submissions/fr/traductions`

**Comment by spapastamkou** [comment]
Merci beaucoup, @Lucaterre ! 
La traduction est donc dans le [repository des soumissions](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/installation-modules-python-pip.md). Nous garderons ce ticket ouvert le temps qu'un membre de @programminghistorian/french-team puisse en assurer le suivi éditorial et organiser la relecture.

**Comment by spapastamkou** [comment]
Le lien de cette leçon, une fois celle-ci publié, doit figurer dans la leçon sur Jupyter Notebooks qui est en cours d'être publiée (ticket de relecture ici: https://github.com/programminghistorian/ph-submissions/issues/309). 
Je mets cette note ici pour 1) considérer cette traduction comme prioritaire pour être publiée et 2) avoir une sorte de rappel pour remplacer le lien vers la leçon EN avec la leçon en FR une fois publiée.

**Comment by spapastamkou** [comment]
Cette traduction est maintenant en cours de relecture: #320
