### ISSUE TITLE
Detecting Text Reuse with Passim

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/ph-submissions#294]
The Programming Historian has received the following proposal for a lesson on "Detecting Text Reuse with Passim" by Simon Hengchen and Matteo Romanello. The proposed learning outcomes of the lesson are:
     
- provide a brief introduction to Text Reuse
- cover the installation of passim in different settings
- walk the reader through how to prepare data into a format passim can process
- show how the output generated can be further processed to create visualizations
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than August 15. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by August 15, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @walshbr. If there are any concerns from the authors they can contact the Ombudsperson @amandavisconti.

**Comment by walshbr** [comment]
Just a quick note to say that @amsichani will be serving as editor for this lesson instead of me!

**Comment by walshbr** [comment]
Also a note that the authors wanted to conduct an informal review with some interested colleagues prior to sending it out for formal reviewers. I suggested to them that the best protocol would be to upload the lesson here and do an initial quick pass to make sure the markdown all renders properly. Once they have finished discussing and making revisions based on those conversations and by August 15, they'll upload the text here for the first editorial pass by @amsichani and then on to reviews.

**Comment by amsichani** [comment]
Hi there! Looking forward to this submission! Do let me know if you need any clarification.

**Comment by drvenabili** [comment]
Thanks all. Please note that the original submission is in English but being a native French speaker (🇧🇪🇱🇺) I am happy to also submit a translation in French when the English version is finalised and published.

**Comment by mromanello** [comment]
@amsichani @faustusdotbe After merging, the draft of our lesson can be read at http://programminghistorian.github.io/ph-submissions/lessons/detecting-text-reuse-with-passim – I've checked briefly, and all seems to render OK on our side.
