### ISSUE TITLE
Proposition de traduction: Téléchargement de pages Web avec Python

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#295]
Je propose la traduction en français de la leçon "Downloading Web Pages with Python" sous le titre "Téléchargement de pages Web avec Python". Je prévois que le travail sera terminé d'ici le 15 juin 2020.

Une fois le travail achevé, je déposerai le fichier dans le dépôt ph-submissions et maintiendrai ce ticket ouvert jusqu'à ce qu'un membre de @programminghistorian/french-team ait la possibilité d'effectuer le suivi éditorial.

**Comment by fdlaramee** [comment]
La traduction est complétée et disponible ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/telecharger-des-pages-web-avec-python.md 

cc: @programminghistorian/french-team

**Comment by mariechristineb** [comment]
Cette leçon est maintenant en relecture: #364
