### ISSUE TITLE
Relecture de traduction: Introduction à Python et installation

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#296]
Le Programming Historian en français a reçu la traduction du tutoriel "Python Introduction and Installation" sous le titre "Introduction à Python et installation" par Anastasiia Zadykhina @anzadykhina. Le texte est déposé ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/introduction-et-installation.md

Je vais assurer le suivi éditorial de cette traduction. Compte tenu de la simplicité de la leçon, j'ai sollicité une relecture auprès de @spapastamkou; @mpuren a déjà réalisé un travail d'édition partiel de ce texte dans le passé. Je coordonnerai les échanges qui auront lieu dans cet espace. Les relectrices pourront utiliser la numérotation des lignes fournie dans l'aperçu pour insérer leurs commentaires, si cela leur convient. Toutefois, elles seront libres de présenter leurs commentaires comme elles le jugeront approprié. Les relectrices peuvent aussi s'appuyer sur les consignes aux traducteurs et aux traductrices. Nous pouvons prévoir un délai de 30 jours environ, ce qui nous mènerait au **19 juin 2020**. Ce délai peut néanmoins être adapté si besoin.

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour l'auteur(e) puisse travailler sur la révision de son texte. Je l'annoncerai sur ce fil quand cette étape aura été atteinte.

Je ferai de mon mieux pour garder la discussion ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers notre mécanisme de médiation si vous avez le sentiment qu'une médiation est nécessaire.

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (https://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by fdlaramee** [comment]
@anzadykhina Souhaitez-vous être impliquée dans le (vraisemblablement très court et très simple) processus de révision avant publication de cette leçon? Quoi qu'il en soit, nous apprécierions que vous ajoutiez à ce ticket un commentaire contenant le texte suivant: "Je, <votre nom>, traductrice, accorde à ProgHist Ltd une licence non-exclusive afin de permettre au Programming Historian en français de publier la traduction discutée dans ce ticket (y compris tous réseaux, tableaux, figures, données et matériaux supplémentaires) sous licence [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.en)."

Merci,
FDL

**Comment by spapastamkou** [comment]
Merci pour cette traduction à @AnZadykhina. 
Mes commentaires portent essentiellement sur la forme; je m'inspire notamment d'une traduction que j'avais préparé moi-même pour cette leçon avant de me rendre compte que nous disposions de celle-ci:-)  
La numérotation des lignes ci-dessous correspond à l'affichage obtenu en ligne sur Github (`ph-submissions`) une fois que nous avons cliqué sur "Edit this file". Je copie la partie de la phrase à laquelle le commentaire se réfère et je mets en gras la partie à laquelle j'attire l'attention. 

l. 32: 
- "[...] a pour but de vous **- et votre ordinateur -** faire commencer à [...]": la syntaxe me paraît un peu compliquée ici. Peut-être préférer une formule plus simple comme "a pour but de préparer vous et votre ordinateur" en adaptant le reste de la phrase? Ou omettre "- et votre ordinateur -"? (Attention, tout changement ici, implique aussi la modification du résumé de la leçon dans yaml qui reprend cette phrase).  
- ""sur l'installation du **logiciel** adéquat": peut-être "environnement" à la place de "logiciel"? 
l. 33
- Normalement cette ligne inaugure un nouveau paragraphe qui semble perdu, peut-être faire une petite correction du markdown? 
- "Dans ce module **d'ouverture**": "d'introduction"? 
- "Voici une liste d'autres options **: Éditeurs Python**": pas de majuscule après ":" mais surtout je crois que la phrase serait mieux sans ce ":". Par exemple, "voici une liste d'autres éditeurs pour Python" ou quelque chose de la sorte? 

l. 35-37: Toute cette deuxième partie a été modifiée dans l'original en anglais pour se conformer à la version 3 de Python. Si cela peut faciliter la vie du rédacteur, il peut reprendre la traduction que j'ai fait ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-installation-py.md#le-langage-de-programmation-python en la modifiant à sa guise (je supprimerai ce fichier une fois les relectures et corrections finies pour éviter la confusion). 

l. 49: "passez à **'[Afficher des fichiers HTML](https://programminghistorian.org/en/lessons/viewing-html-files)'**": consultez la leçon «Comprendre les pages web et le HTML» (avec comme lien: /fr/lecons/comprendre-les-pages-web)

Voilà, je pense que c'est tout et je reste à la disposition de @fdlaramee  si besoin. Encore merci à la traductrice pour son travail.

**Comment by fdlaramee** [comment]
@spapastamkou Merci Sofia; il semble bien y avoir un problème avec les notifications puisque je n'ai rien reçu pour ce ticket non plus. 

N'ayant pas de nouvelles de  @AnZadykhina je procéderai aux ajustements moi-même dans les meilleurs délais.

**Comment by fdlaramee** [comment]
Merci encore @spapastamkou. J'ai procédé aux ajustements au texte en suivant tes instructions et en ajoutant quelques précisions de mon cru. Le texte est maintenant prêt pour la mise en ligne; si celle-ci se fait en même temps que celle de la leçon sur l'installation de l'environnement de développement pour Windows, il faudra remplacer le lien vers la version anglaise à la ligne 48.

@programminghistorian/french-team

**Comment by spapastamkou** [comment]
C'est noté @fdlaramee, je m'occupe de la publication.
