### ISSUE TITLE
Relecture de traduction: Installer un environnement de développement pour Python (Windows)

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#297]
Le Programming Historian en français a reçu la traduction du tutoriel "Setting Up an Integrated Development Environment for Python (Windows)" sous le titre "Installer un environnement de développement pour Python (Windows)" par @spapastamkou. Le texte est déposé ici: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/installation-windows-py.md

Je vais assurer le suivi éditorial de cette traduction. J'ai sollicité une relecture auprès de @mariechristineb; une seconde s'ajoutera sous peu. Je coordonnerai les échanges qui auront lieu dans cet espace. Les relecteurs et relectrices pourront utiliser la numérotation des lignes fournie dans l'aperçu pour insérer leurs commentaires, si cela leur convient. Toutefois, ils et elles seront libres de présenter leurs commentaires à leur guise. Il est aussi possible de s'appuyer sur les consignes aux traducteurs et aux traductrices. Nous pouvons prévoir un délai de 30 jours environ, ce qui nous mènerait au **19 juin 2020**. Ce délai peut néanmoins être adapté si besoin.

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour l'auteur(e) puisse travailler sur la révision de son texte. Je l'annoncerai sur ce fil quand cette étape aura été atteinte.

Je ferai de mon mieux pour garder la discussion ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers notre mécanisme de médiation si vous avez le sentiment qu'une médiation est nécessaire.

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation (https://programminghistorian.org/fr/equipe-projet). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by mariechristineb** [comment]
Bonjour @fdlaramee et @spapastamkou! La traduction me semble très bien dans l'ensemble, voici mes notes ponctuelles (en italique lorsqu'il s'agit d'un mot ou d'un extrait en particulier): 

Ligne 35
Je reformulerais la fin de la deuxième phrase pour quelque chose d’un peu moins ‘direct’, du genre ’il serait avisé d’en faire une habitude’

Ligne 39
avec Windows XP, _ni_ avec les versions […]

Ligne 43
Éviter la répétition de ‘disque dur’ - ‘sur votre disque dur, à l'emplacement de votre choix, pour y ranger […]’ ferait l’affaire

Ligne 47
Quel est le terme d’usage sur PH-FR? ‘open source’, ‘code source ouvert’, ‘code source libre’?

Ligne 51
[…] qui ressemble à _ceci_ (au lieu de ‘cela’)

Ligne 55
J’aurais tendance à utiliser le terme ‘volet’, surtout si c’est le terme qui est utilisé par l’interface française du logiciel
‘Prenez le temps’ (‘donc’ donne l’impression qu’on fait référence à la phrase précédente, ce qui n’est pas tant le cas ici)

Ligne 61 
‘qui ressemble à _ceci_’

Ligne 66 
‘il se peut que vous n’_arriviez_ pas’
‘_tapez_ […] puis _cliquez_’

Ligne 79
Revoir la traduction de la deuxième partie de la phrase, elle ne correspond pas tout à fait à la version anglaise.

Ligne 85
‘Si vous obtenez _ceci_’

Ligne 90
Voir commentaire ligne 55
‘avant de _pouvoir / d’être en mesure de_ travailler avec Python’
 
Ligne 97
‘gravé dans votre mémoire’? (me semble plus idiomatique)

Ligne 109 
coquille: ‘come’ -> ‘comme’

Ligne 115
syntaxe: ‘pour faire réagir la console à votre commande’

**Comment by spapastamkou** [comment]
Bonjour @fdlaramee, y aura-t-il une 2e relecture de cette traduction? Aussi, je peux modifier la traduction suivant les suggestions de la première, mais je ne bouge pas sans avoir ton avis. Merci!

**Comment by fdlaramee** [comment]
Bonjour @spapastamkou -- Je n'ai toujours pas de deuxième volontaire alors je crois que nous pourrons procéder avec les commentaires de @mariechristineb après ton sabbatique.

BTW: je n'ai pas reçu de notification des commentaires de Marie-Christine, ni du tien. Je suis passé pour vérifier l'état des travaux par hasard. À surveiller au cas où ce serait un problème récurrent.

**Comment by spapastamkou** [comment]
Merci @fdlaramee ! (Je pensais que tu étais juste très occupé, on fera attention pour les notifs).

Je viens d'intégrer toutes les suggestions de @mariechristineb, que je remercie infiniment pour ses commentaires extrêmement utiles. Ci-dessous qqs précisions: 

l. 47: pour répondre à la question, on utilise "à code source ouvert" mais de manière auxiliaire à "open source":  https://programminghistorian.org/fr/apropos#open-source-code-source-ouvert Si vous êtes d'accord, on peut généraliser l'utilisation du terme en français directement (en tout cas j'ai corrigé le texte du tutoriel en fonction). 

l. 55 L'interface n'est pas traduite en français, en fait; là où j'ai mis "volet" une fois, je me suis appuyée sur la documentation en fr de Libre Office (par analogie). J'hésitais un peu sur le bon terme à appliquer, du coup je suis ta suggestion @mariechristineb . 

l. 79: J'ai reformulé, mais je suis toujours dans la paraphrase par rapport à l'original. Je trouve ce passage assez difficile: je vous  laisse carte blanche pour améliorer la traduction de cette partie comme bon vous semble.  

l. 97: cela m'a beaucoup fait rire quand j'ai relu le passage; j'ai mis bien sûr "mémoire":)

@fdlaramee J'ai aussi corrigé la date de traduction dans yaml parce qu'elle était antérieure à celle du dernier tuto publié (pour éviter des problèmes d'affichage).

**Comment by spapastamkou** [comment]
J'aimerais néanmoins vos avis sur le titre: "Installer un environnement..." OU "Installation d'un environnement..."?

**Comment by fdlaramee** [comment]
@spapastamkou J'ai procédé à une dernière relecture, corrigé quelques coquilles et formulations, et sauvegardé le résultat. Le fichier me semble maintenant prêt à mettre en ligne.

Pour le titre: les deux options me semblent valables. Aucune préférence.

**Comment by mariechristineb** [comment]
@spapastamkou Je n'ai pas nécessairement de préférence pour un ou l'autre, par contre, la plupart de tutoriels jusqu'à maintenant ont un titre qui commence par un verbe (comprendre, conserver, préserver, manipuler), devrait-on essayer de conserver une certaine uniformité?

**Comment by spapastamkou** [comment]
Merci bcp, @fdlaramee et @mariechristineb. A la suite de vos commentaires, on alors maintient le titre tel quel. Peux-tu assurer la mise en ligne @mariechristineb ? 
Encore merci à vous deux.

**Comment by mariechristineb** [comment]
Oui @spapastamkou, je m'en occupe - j'ai copié les fichiers et fait la demande de DOI, j'essaierai de lancer la pull request demain

**Comment by mariechristineb** [comment]
La leçon a été publiée le 16 juillet avec la pull request #1847
