### ISSUE TITLE
Proposition de traduction: Décomptes de fréquences de mots en Python

### ISSUE THREAD

**Issue by fdlaramee** [programminghistorian/ph-submissions#298]
Je propose la traduction en français de la leçon "Counting Word Frequencies with Python" sous le titre "Décomptes de fréquences de mots en Python". Je prévois que le travail sera terminé d'ici le 30 juin 2020.

Une fois le travail achevé, je déposerai le fichier dans le dépôt ph-submissions et maintiendrai ce ticket ouvert jusqu'à ce qu'un membre de @programminghistorian/french-team ait la possibilité d'effectuer le suivi éditorial.

**Comment by fdlaramee** [comment]
Le fichier est maintenant disponible dans le dépôt ph-submissions, sous le nom decomptes-de-frequences-de-mots-en-python.md. Il est au https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/decomptes-de-frequences-de-mots-en-python.md

@spapastamkou @programminghistorian/french-team

**Comment by acrymble** [comment]
@spapastamkou this submission has been open for several years. Can you please action this in some way?

**Comment by anisa-hawes** [comment]
Hello all, 

Please note that this lesson's .md file has been moved to a new location within our Submissions Repository. It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/inactives

A consequence is that this lesson's preview link has changed. It is now: [http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/decomptes-de-frequences-de-mots-en-python](http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/decomptes-de-frequences-de-mots-en-python)

Please let me know if you encounter any difficulties or have any questions.

Very best,
Anisa

**Comment by spapastamkou** [comment]
@datalogism prend en charge le suivi éditorial qu'il pourra organiser à sa convenance sur la base de ce ticket-ci ou en ouvrant un nouveau pour l'évaluation de la traduction - à toi de voir comme tu le préfères, Célian. Merci beaucoup!

**Comment by spapastamkou** [comment]
La relecture est organisée sur #526.
