### ISSUE TITLE
Ticket de revisión de traducción: Introducción a la transcodificación, edición y visualización de datos audiovisuales con FFmpeg

### ISSUE THREAD

**Issue by JoshuaGOB** [programminghistorian/ph-submissions#302]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción Introducción a Transcodifar, Editar, y Visualización de Datos Audivisual con FFmpeg de la lección Introduction to Audiovisual Transcoding, Editing, and Color Analysis with FFmpegpor parte de @drodz11. El mismo autor original de la lección estará realizando la traducción. Esta traducción se encuentra en estos momentos en fase de revisión por @arojascastro y @jamotilla  y puede leerse en:

### Texto
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/introduccion-a-ffmpeg.md

### Previsualización de la lección
http://programminghistorian.github.io/ph-submissions/es/traducciones/introduccion-a-ffmpeg

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros *ombudpersons*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by rivaquiroga** [comment]
@drodz11, muchas gracias por la paciencia. Finalmente @arojascastro  será el editor de la traducción de tu lección. En los próximos días empezaremos con el proceso de edición.

**Comment by arojascastro** [comment]
Gracias @rivaquiroga ! Haré una primera lectura en los próximos días y luego buscaré a dos revisores.

**Comment by drodz11** [comment]
Gracias ambos por su trajabo!

**Comment by jamotilla** [comment]
Estimado @arojascastro me apunto como revisor.

**Comment by arojascastro** [comment]
Hola @drodz11 he leído tu traducción como editor. Muchas gracias! 

Aquí van unos breves comentarios y sugerencias de cambio:

## General

- [x] Título: propongo cambiar a "Introducción a la transcodificación, edición y visualización de datos audiovisuales con FFmpeg". Además falta una "o" en audiovisuales. El nombre del archivo quizás se podría dejar tal cual porque es más breve.
- [x] Tabla de contenidos: propongo homogenizar el uso de la mayúscula. Por ejemplo: "Probando La Instalación" sería mejor "la instalación" o bien "Usando FFmpeg en El Navegador de Internet" sería mejor "el navegador de internet", etc. Ocurre en todos los encabezados. Estos cambios se hacen directamente en los encabezados de cada sección, no en la tabla de contenidos, que se genera automáticamente.
- [x] Duda general: se usa "marco" como traducción de "framework"? Propongo usar "framework" en inglés y en cursiva.

## Introducción

-  [x] valorosas --> valiosas
-  [x] (por ejemplo, el tutorial de Programming Historian Editar Audio con Audacity, y este tutorial presentará otro: FFmpeg. --> falta o sobra un paréntesis; esta frase se deber revisar. 
-  [x] comúnes --> comunes.
-  [x] Como tal, conocimiento del marco permite --> Como tal, el conocimiento del marco permite (falta artículo)

## Requisitos previos

-  [x] yo recomiendo --> se recomienda

## Cómo instalar...

-  [x] Felizmente, --> Afortunadamente,
- [x] En el destacado, " en [Twitter o en el sitio web" --> sobra el paréntesis cuadrado, o bien hay que incluir uno de cierre. No solemos usar claudators... 

## Para usuarios Mac

- [x] es recomendado --> se recomienda
- [x] accesso --> acceso (sobra una s)

## Para usuarios de Windows

- [x] Usarios de Windows --> Los usarios de Windows (falta artículo)
- [x] todo la información --> toda la información

## Otros recursos

- [x] Paquetas --> Paquetes
- [x] Los usarios --> Los usuarios

## Probando la instalación

- [x] inprobable --> improbable

## Para empezar

- [x] ha sido hecha disponible por --> está publicada por... o bien se publica gracias a... 
- [x] época Guerra Fría  --> época de la Guerra Fría 
- [x] Para este tutorial, necesitarás hacer --> En este tutorial se llevarán a cabo los siguientes pasos:
- [x] Navegue --> Navegar
- [x] Descargue --> Descargar
- [x] Guarde --> Guardar

## Ejemplos de comandos

- [x] a iluminar --> a comprender
- [x] de el informe --> del informe

## Cambiar el contenedor

- [x] el concepto "envolver"... prpongo incluir en la primera aparición en paréntesis el término en inglés para dejar bien claro qué significa y luego escribir solo la traducción en adelante

## Creación de extractos

- [x] Pie de foto: La abundancia de Tierra --> La abundancia de la Tierra (falta un artículo o bien "Tierra", si te refieres al fragmento de la película)
-  [x] Puedes probar -->Puede probar 

# Análisis de datos de color

- [x] este artículo --> esta lección
- [x] una herramienta poderosa --> una herramienta útil
- [x] Nosotros hemos agregado --> Hemos agreagado (no hace falta el nosotros)
- [x] Nosotros hemos especificado  --> Hemos especificado 
- [x] Nosotros hemos especificado --> Hemos definido

## Extracción de datos

- [x] respectivamente . -->  respectivamente. (quitar espacio antes del punto)
- [x] son []áreas --> son [áreas (error al enlazar)

## Graficando datos de color

- [x] Graficando --> Visualizando (no me acaba de gustar el término "graficar" pero si es usado generalmente se podría dejar...)

## Modoficando

- [x] Modoficando -->Modificando
- [x] el en bucle --> en el bucle

# Acerca del autor

- [x] cienasta --> cineasta

Esto es todo de momento. @drodz11 podrías por favor hacer tú mismo los cambios sugeridos antes de que @jamotilla lea el tutorial? Por favor, avísanos con un mensaje en este ticket cuando los cambios se hayan realizado. 

Muchas gracias por tu trabajo!

**Comment by jamotilla** [comment]
En cuanto @drodz11 haga los cambios me pondré a leer de inmediato. Saludos

**Comment by drodz11** [comment]
@arojascastro y @jamotilla muchas gracias ambos! Yo revisará sus comentarios y sugerencias el viernes y la semana entrante.

**Comment by drodz11** [comment]
@jamotilla y @arojascastro -- He hecho los cambios y correcciones. Todavia no estoy seguro que el término "en bucle" esta funcionando para traducir "for loop," pero me gustaria saber que piensan. Otra vez, muchas gracias.

**Comment by jamotilla** [comment]
Muchas gracias @drodz11 a más tardar el domingo te hago llegar mis observaciones. Saludos

**Comment by rivaquiroga** [comment]
@drodz11, respecto de "for loop", lo he visto traducido como  "bucle _for_" (así con cursiva). Por ejemplo, acá: https://es.r4ds.hadley.nz/iteraci%C3%B3n.html#bucles-for-vs.funcionales
Este pareciera ser uno de los caso en que tiene sentido mantener el nombre de la función en inglés porque es la forma en que las personas tendrán que escribirla en el programa que utilicen.

**Comment by arojascastro** [comment]
Me parece estupenda tu propuesta @rivaquiroga y gracias al traductor por hacer los cambios tan rápido. Esperamos los comentarios de @jamotilla

**Comment by drodz11** [comment]
Estoy de acuerdo con @arojascastro que es una sugerencia estupenda, @rivaquiroga! He cambiado la última sección con los "bucles for."

**Comment by jamotilla** [comment]
Estimado @drodz11 estos son mis comentarios. Cualquier duda o ayuda, me dices y con mucho gusto.

16. Sugiero eliminar "como disciplina", escribir humanidades digitales en bajas e incorporar la siguiente redacción /Históricamente, las humanidades digitales se han enfocado casi exclusivamente...
16. "de herencia cultural"/ conveniente buscar un sinónimo, considero que no queda claro.
16. "investigaciones más nuevas [...] también" eliminar también/Investigaciones recientes tal como [distant viewing], indican un cambio en el campo...
16 "La audiencia "/ "la audiencia"
16 "La audiencia de Humanidades Digitales no siempre está enfocada en la literatura o está interesada en las formas tradicionales de alfabetización" y / agregar coma despues de la cita textual
"y la aplicación de metodologías digitales para estudiar cultura audiovisual" / agregar coma después de audiovisual.
16. es una emocionante y emergente faceta de las Humanidades Digitales (Champion, 2017)./ es una faceta emergente y emocionante de las humanidades digitales.
18. (El sitio web de...)/ (el sitio web de...)
18. en la interfaz de línea de comandos / en la interfaz de la línea de comandos.
18.tareas comunes, complejas, e importantes / tareas comunes, complejas e importantes, 
18.  Este tutorial proporcionará una introducción / Este tutorial ofrece una introducción a la lectura y escritura de comandos de FFmpeg y a su vez, consiste en una guía a partir de un caso práctico para aprender a utilizar el _framework_ en un trabajo específico para los humanistas digitales, en este caso, para aprender a utilizar FFmpeg para extraer y analizar datos de color en un video archivístico. 
21. en su computadora / en tú computadora
21. navegador de internet / navegador web
33. Antes de comenzar con este tutorial, es necesario que localices la terminal de tu computadora u otra interfaz de línea de comandos ´[en la versión original computadora está mal escrito]
21. Adicionalmente, un entendimiento básico / Adicionalmente se recomienda tener conocimientos básicos de codecs audiovisuales para entender con mayor detalle el funcionamiento de FFmpeg.
21.  Proporcionaremos información adicional y discutiremos códecs y contenedores en más detalle en la sección Ejemplos de Comandos Preliminares de este tutorial. / Proporcionaremos información adicional y revisaremos con mayor detalle sobre codecs y contenedores en la sección ejemplos de comandos preliminares de este tutorial.
36. Afortunadamente, hay algunas guías útiles y recursos disponibles para instalar el _framework_ para cada tipo de sistema operativo. / Afortunadamente existen algunas guías y recursos disponibles para instalar el _framework_ para cada sistema operativo. 
39. Para mantenerse al tanto de las nuevas versiones, siga FFmpeg en / para mantenerse al tanto de ellas, es recomendable seguir a FFmpeg en 
39.  Nuevo versiones de FFmpeg generalmente contienen características tales como filtros nuevos y actualizados, compatibilidades de códecs, y corrección de errores. / Las nuevas versiones de FFmpeg...
39. Puede aprender más sobre estas actualizaciones / Puedes 
43. siga estos pasos: / sigue 
44. Instale / Instala
45.  Ejecute `brew install ffmpeg` en su Terminal para comenzar una instalación básica / Para comenzar con una instalación básica, ejecuta...
46. Note:  **Note**: Generalmente, se recomienda instalar FFmpeg con opciones adicionales a las incluidas en la instalación básica. Incluir opciones adicionales proporcionará acceso a más herramientas y funcionalidades de FFmpeg./ Nota: generalmente se recomiuenda instalar FFmpeg con opciones adicionales a la incluidas en la instalación básica; esto proporcionará acceso a más herramientas y funciones. 
52. Para una explicación de estas opciones adicionales, revise / revisa
53. Además, puede ejecutar `brew options ffmpeg` para ver qué características están o han estado disponibles con la versión actual de FFmpeg / Además, puedes ejecutar.... en la versión...
Para actualizar su instalación a la versión más reciente, ejecute / tu instalación 
60. revise / revisa
63. paquetas / paquetes
63. Chocolately / separar
66. un programa similar a Homebrew, se puede usar para instalar y mantener FFmepg en Linux. / es un programa similar a Homebrew que se puede utilizar para ...
66. esté utilizando. / estés utilizando
71. estáticos / estáticas
73. en su  / en tu
76. ejecute / ejecuta
82. Si ve una producción  / ves la producción...
98. si ve algo como / si el sistema arroja "bash...."
98. [de aquí en adelante es importante cuidar dirigirse de tú al lector]
104. navegador de Internet / navegador
104. versión más vieja / versión antigua o anterior
114. Los archivos de entrada / entradas
115. los archivos de entradas./ entrada
129.  Estrenada en 1956 y producida por [El American Petroleum Institute](https://es.wikipedia.org/wiki/American_Petroleum_Institute) y [John Sutherland Productions](https://en.wikipedia.org/wiki/John_Sutherland_(producer)), la película es un excelente ejemplo de la propaganda de la época de la Guerra Fría que exalta las virtudes del capitalismo y el estilo de vida americano. / Esta película, estrenada en 1956, y producida por..., es un excelente ejemplo de la propaganda...
129. Utilizando el proceso de [Technicolor] / Utiliza el proceso 
[Es recomendable no utilizar gerundios (ando, iendo)]
129. Usaremos / utilizaremos
153 compatibilidades con varios programas./ compatibilidad con diversos programas.
169. vienen en muchos / se presentan en múltiples
176. Para propósitos de demostración, / para efectos de demostracion 
198. Si ejecute este comando  / si ejecutas
198. tutorial; / tutorial, 
201. ¿a qué se refieren con "examinaremos dos secciones discretas" ?
209.  una secuencia cerca del comienzo / una secuencia correspondiente al comienzo de la película
251. Primero, veamos otra manera estandarizada de representar la información de color que informa este enfoque cuantitativo, basado en datos, para el análisis de color. / ...que es parte de este enfoque cuantitativo, basado en datos.
254. "el tamaño de una parcela dada" ¿es un termino técnico específico del análisis de video?
254. A continuación se muestra un ejemplo de un vectorscopio que muestra los valores de color de las barras SMPTE, que también se muestran / suprimir "que también se muestran"
301. "Note" o nota?
311. para crear informes / Creo que sería pertinente utilizar un sinónimo tal como reportes para evitar que la oración diga "informes de información"
346.  sobre cómo usar su plataforma / acerca del uso de su plataforma
351.  que sirve un mensaje propagandístico. / que sirve como mensaje...
351. colores relativamente opacos de rojos y amarillos. / de tonos relativamente opacos de rojo y amarillo
351. prejuicios preconcebidos/ es redundante, sería mejor dejarlo solo en prejuicios/ El uso del color aprovehca los prejuicios y asociaciones que están presentes en el imaginario de la audiencia, y por lo tanto, está ligado estrechamente al argumento central de la película, el cual sostiene que el comunismo no es un sistema político viable.
353. la explotación de petróleo y productos derivados del petróleo. / la explotación de petroleo y de productos derivados de este. 
373. coincidan con sus correspondientes informes  / con sus informes correspondientes.
386. Cómo ver metadatos técnicos básicos / cómo visualizar

**Comment by drodz11** [comment]
@jamotilla muchas gracias! Debería poder revisar esta semana o la semana entrante.

**Comment by arojascastro** [comment]
Estupendo @drodz11 - @jenniferisasi hará una última lectura cuando hayas hecho los cambios. Por favor, avísanos @drodz11 para que ella empiece. Ojalá podamos publicar esta lección antes de diciembre :)

**Comment by drodz11** [comment]
@jamotilla -- He revisado y impleado los correciones. Tengo unos preguntas para usted:

- Re: "de herencia cultural" ---> he cambiado a "de patrimonio cultural" como aqui: https://www.wordreference.com/es/translation.asp?tranword=cultural%20heritage. Cree que esto funciona? Alternativamente, creo que podemos usar "el analisis de materiales audiovisuales como se indica por la creación...." sin herencia/patrimonio cultural.

- Re: "Chocolately / separar" ---> no estoy seguro que cambio sugiere?

- Re: ¿a qué se refieren con "examinaremos dos secciones discretas" ? ---> he cambiado a "examinaremos dos secciones separadas"

- Re: "el tamaño de una parcela dada" ¿es un termino técnico específico del análisis de video? ----> he cambiado a "el tamaño de un gráfico." Creo que es mas cerca a "plot" (en ingles) y en el contexto del vectorscopio.

Gracias!

**Comment by jamotilla** [comment]
Hola Dave, te respondo por puntos:
1.- Me parece más adecuado el término "patrimonio cultural".
2.- En este punto no me hagas caso, creo que lo señalé por erro.
3.-De acuerdo con el cambio
4.- Estoy de acuerdo con el cambio, creo que el tamaño del gráfico es adecuado 
Saludos

**Comment by drodz11** [comment]
@arojascastro creo que estamos listos para @jenniferisasi a leer y revisar la leccion.

**Comment by jenniferisasi** [comment]
Gracias @drodz11 me pongo a ello. 

@arojascastro y @rivaquiroga esta lección se va a enviar a copy-editing? Voy notando alguna cosilla que entra en dicha labor más que en la revisión de pares.

**Comment by jenniferisasi** [comment]
Comentario general: 
Excelente tutorial que se puede seguir muy fácilmente y construye los pasos en relación a una pregunta de investigación clara y sencilla. Lo necesario para esta publicación. Sin saber nada del tema he podido seguir las instrucciones y su razón de ser sin ningún problema. Creo que será de gran utilidad para la comunidad hispanohablante porque si en general hay pocos recursos, de análisis audiovisual hay menos todavía. Gracias @drodz11 por traducir tu propio tutorial. Dejo varios comentarios y sugerencias que son más que nada apuntes de estilo y algún error que he encontrado. Esto no debería suponer ningún cambio mayor a la lección. 

En el índice (para @arojascastro): 
- Aparecen la información sobre el autor y la nota sobre el apoyo a la lección en el índice y no iría ahí. 

**Introducción**: 
Párrafo 1:
- [x] estilo: "como se indica por la creación" -- como atestigua la creación; como refleja la creación
- [ ] cita: hay que indicar se ha traducido la cita de Champion 
- [x] eliminar el punto delante de (Champion 2017) 
Párrafo 2: 
- [x] Programming Historian ha de ir en cursiva (en la original también) a lo largo de la lección
- [x] "incluso" -- por ejemplo
- [x] "herramienta de software y desarrollo de Internet" -- desarrollo web
- [x] sugerencia para audiencia global: "Para más opciones de instalación ... " indicar entre paréntesis que la guía solo está disponible en inglés; en este caso y en cualquier otro. 

**Objetivos de aprendizaje**
- [x] "útiles tal como" -- útiles tales como

**Requisitos previos**
- [x] el link a Terminal (en wikipedia) está mal, es https://es.wikipedia.org/wiki/Terminal_(macOS) 
- [x] estilo: la primera oración utiliza tú y las siguientes usted, hay que normalizarlo a la misma persona a lo largo de la lección
- [x] typo: AAdicionalmente

**Para usuarios de Mac OS**
- [x] typo: recomiuenda
- al instalar lo extra, me da error por `--with-sdl2`

**Otros recursos para instalar**
- [x] "Otros recursos para instalar" -- Otros recursos de instalación

**Probando la instalación**
- [x] "Ves una producción" -- Si ves una lista larga con información 

**Usando FFmepg en el navegador**
- [x] el link en  vídeoconverter.js  está roto, sospecho que por la tilde, aunque puede ser otra cosa
- Añadir una nota de que el interfaz está en inglés

**La estructura básica y sintaxis de los comandos FFmpeg**
- [x] en el comando de ejemplo "algo_acción" -- alguna_acción

**Para empezar**
- [x] concordancia: por el Archivos 
- [x] "estilo de vida americano" -- es más adecuado decir en español "estilo de vida estadounidense" 
- [x] "Utiliza el proceso" -- utilizando o mediante
- [x] orden: "el “MPEG4” (extensión de archivo .m4v) y el “OGG” (extensión de archivo .ogv) versiones de la película" -- "las versiones MPEG5...

**Ejemplos de comandos preliminares**
párrafo 20
- [x] utiliza -- utilizando
párrafo 26
- [x] "un otro commando de" -- otro comando de

**Creación de extractos y “demuxing” de audio y vídeo**
párrafo 37
- [x] "análisis utiliza un comando" -- utilizando
párrafo 38
- [x] duplicación "de la película de la película"

**Análisis de datos de color**
- [x] "una otra manera" -- otra manera

**Visualizando datos de color**
- [x] plot.ly no me aparece como herramienta en el navegador, hay que darle datos, habría otra más accesible?

**Wrap up**
- [x] cambiaría "redondear" por "en resumen"

**Comment by drodz11** [comment]
@jenniferisasi muchas, muchas gracias para sus comentarios rigurosos. Para responder a uno punto:

- Re: plot.ly -- apraece que plot.ly ya no existe como un servicio gratuito. También tendré que actualizar la versión en inglés. He cambiado párrafo 64 para indicar esto.

Creo que todo lo demas esta bien y listo!

**Comment by drodz11** [comment]
Recibí un mensaje de Github despues de enviar los cambios nuevos:

There was a YAML syntax error on line 2 column 42 in `<unknown>`: `mapping values are not allowed in this context`. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#invalid-yaml-in-data-file.

No se que es el problema, no he cambiado nada en el YAML.

**Comment by arojascastro** [comment]
Muchas gracias a todos! 💯 

Entiendo que los cambios que sugería Jennifer ya están introducidos. En tal caso, procederé a publicar la lección en los próximos días. 

En cuanto al error que te aparece, Dave... prometo mirármelo pronto, pero no te preocupes, seguramente el error esté en otro fichero...

**Comment by rivaquiroga** [comment]
¡Hola! Por si acaso, **plotly** sigue existiendo, solo que cambió su sitio web a plotly.com. Y sigue teniendo una versión gratuita y abierta, así que no habría que sacar esa mención, solo cambiar la url. Quizás se podría poner la url directa a la sección sobre visualización de datos: https://plotly.com/graphing-libraries/

**Comment by drodz11** [comment]
Muchas gracias por investigar eso, @rivaquiroga ! He cambiado la url y la formulación del párrafo 64 un poco.

**Comment by arojascastro** [comment]
Hola de nuevo:

He hecho una última lectura rápida.
 
Aquí van algunas sugerencias generales:

- [x] en todo el tutorial, creo que software debería ir con cursiva: *software*; o bien se puede usar el término "programa", sin cursiva.
- [x] Navegue hasta --> Navega hasta. Convendría revisar si utilizas tú o bien usted, hay cierta variación en todo el tutorial... 

Aquí van algunas sugerencias específicas:

- [x] la aplicación de metodologías digitales para estudiar cultura audiovisual, es una faceta emergente y emocionante de las humanidades digitales --> quitar coma entre sujeto y predicado
- [x] que estés utiliza. --> que utilices ???
- [x] # La estructura básica y sintaxis de los comandos FFmpeg El comando básico tiene cuatro partes: --> hay un problema de markdown aquí? O bien sobra el # inicial?
- [x] A continuación, examinaremos --> creo que hay un problema con el Markdown porque no hay una separación con el párrafo anterior
- [x] esta tutorial --> este tutorial
- [x] utilizaremos el vídeo --> Utilizaremos el vídeo (mayúscula inicial)
- [x] ejecuta otro comando  --> Ejecuta otro comando (mayúscula inicial)
- [x] Como un ejercicio --> creo que hay un problema con el Markdown porque no se separa del párrafo anterior
- [x] Ahora hemos creado nuestro --> creo que hay un problema con el Markdown porque no se separa del párrafo anterior
- [x] Ahora debería tener --> creo que hay un problema con el Markdown porque no se separa del párrafo anterior
- [x] En Resumen --> En resumen (sin mayúscula)
- [x] No hace falta traducir e incluir aquí la biografía del autor ni la nota sobre la financiación, de eso se encarga @rivaquiroga --> sugiero eliminar

Os prometo que estos serán los últimos cambios. Muchas gracias!

**Comment by drodz11** [comment]
Muchas, muchas gracias @arojascastro! Lo siento por el poco retraso, estaba de vacaciones la semana pasada. He revisado y impleado los correciones.

**Comment by arojascastro** [comment]
Muchas gracias a ti. Espero poder ocuparme de los metadatos este fin de semana; cuando esté listo, avisaré a @rivaquiroga cuando esté listo para que inicie el proceso de publicación.

**Comment by arojascastro** [comment]
Hola, ya introduje los metadatos. Falta el DOI y publicar la lección en Jekyll! @rivaquiroga - todo tuyo! Gracias a todos!

**Comment by rivaquiroga** [comment]
¡Qué buena noticia! Aproximadamente a mediados de la próxima semana debería estar ya publicada la lección.

**Comment by rivaquiroga** [comment]
@arojascastro y @drodz11: solo nos queda esperar la asignación del DOI para publicar esta lección Si tenemos suerte, mañana lunes o más tardar el martes debería llegarnos esa información.

**Comment by rivaquiroga** [comment]
@drodz11, ¿tienes a mano las dos imágenes que tradujiste para la lección? Son `ffprobe_mp4_es.png` y `ffprobe_ogg_es.png`. Sospecho que hay una copia en mi correo, pero Google está caído así que no puedo revisar :woman_shrugging:

**Comment by rivaquiroga** [comment]
:ballot_box_with_check: lección publicada
¡Felicitaciones todos por su trabajo! :tada:

**Comment by arojascastro** [comment]
Gracias a todos! https://programminghistorian.org/es/lecciones/introduccion-a-ffmpeg

Por favor, difundid por Twitter si podéis.
