### ISSUE TITLE
Ticket de revisión de traducción: Introducción a los Jupyter Notebooks

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/ph-submissions#306]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción: "Introducción a los Jupyter Notebooks"  de la lección "Introduction to Jupyter Notebooks" por parte de @santiagojeda. Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

**[vista previa]**
http://programminghistorian.github.io/ph-submissions/es/traducciones/introduccion-jupyter-notebooks
**[archivo]**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/traducciones/introduccion-jupyter-notebooks.md

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editora durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra *ombudperson*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by rivaquiroga** [comment]
¡Hola, @santiagojeda! Aún no aceptas la invitación que te enviamos para poder editar tu lección en este repositorio. Debería haberte llegado al correo al que tienes asociada tu cuenta de GitHub.

**Comment by acrymble** [comment]
@rivaquiroga is this still active? We wouldn't normally have a submission open this long.

**Comment by rivaquiroga** [comment]
No, it was archived (https://github.com/programminghistorian/jekyll/projects/4). We forgot to close the ticket.
