### ISSUE TITLE
Proposition de leçon: Calibrer des datations obtenues par le radiocarbone avec R

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#308]
*The Programming Historian en français* a reçu la proposition suivante pour une leçon intitulée "Calibrer des datations obtenues par le radiocarbone avec R" en archéologie de la part de @nfrerebeau. Les principaux objectifs pédagogiques du tutoriel sont:
     
- comprendre pourquoi le radiocarbone possède son propre référentiel temporel;
- comprendre l'étape de calibration d'un âge et savoir présenter ses résultats;
- apprendre à réaliser la calibration d'un ou plusieurs ages radiocarbones avec R.
La date estimée de dépôt de ce tutoriel est le 14 décembre, elle peut néanmoins être revue sur demande de l'auteur. 
 
Si le tutoriel n'est pas soumis à la date convenue, la rédactrice en charge du suivi éditorial sollicitera à nouveau l'auteur. En cas d'absence de réponse, ce ticket sera fermé, il pourra toutefois être réactivé sur demande de l'auteur. 
 
La rédactrice en charge de l'éditorial suivi de cette leçon est @spapastamkou. Si l'auteur le souhaite, pour quelque raison que ce soit, il lui est possible de contacter notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu).

**Comment by fdlaramee** [comment]
@spapastamkou Hourra!! Mais je ne suis plus le médiateur!

**Comment by spapastamkou** [comment]
@fdlaramee I can't get over you:-) Je corrige de ce pas et je fais pareil pour les autres tickets en cours.

**Comment by nfrerebeau** [comment]
@spapastamkou Je viens de soumettre la leçon. Serait-il possible d'avoir un dossier pour déposer les images ? @blebrun est également co-auteur de la leçon.

**Comment by spapastamkou** [comment]
Merci beaucoup @nfrerebeau et @blebrun, c'est la tout première leçon originale en français du PH! 
Je vous ai créé un répertoire pour les images ici: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/calibration-radiocarbone-avec-r Merci de ne pas tenir compte de l'image que j'ai mis dedans, c'est qu'il était impossible de créer un répertoire vide sinon.

**Comment by nfrerebeau** [comment]
Merci @spapastamkou, les figures sont ajoutées.

**Comment by spapastamkou** [comment]
La leçon entre la phase de l'évaluation qui peut être suivie dans #329.
