### ISSUE TITLE
Relecture de traduction: Introduction aux carnets Jupyter Notebooks

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#309]
Le Programming Historian en français a reçu la traduction du tutoriel "Introduction to Jupyter Notebooks" sous le titre "Introduction aux carnets Jupyter Notebooks" par @fdlaramee. Une prévisualisation du texte  est disponible ici: http://programminghistorian.github.io/ph-submissions//fr/traductions/introduction-aux-carnets-jupyter-notebooks

J'ai sollicité une relecture auprès de @mariechristineb ; je vais assurer le suivi éditorial de cette traduction et coordonner les échanges qui auront lieu dans cet espace. La relectrice pourra utiliser la numérotation des paragraphes fournie dans l'aperçu pour signaler ses commentaires, si cela lui convient, mais elle a la liberté de faire comme elle jugera mieux. Nos relecteurs peuvent aussi s'appuyer sur les [consignes aux traducteurs et aux traductrices](https://programminghistorian.org/fr/consignes-traducteurs#traduire-une-le%C3%A7on-et-la-mettre-en-page). Nous pouvons prévoir un délai de 30 jours environ, qui peut néanmoins être adapté si besoin. 

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de l'évaluation formelle, pour que le traducteur puisse travailler sur la révision de son texte. L'annonce sera faite sur ce fil quand cette étape aura été atteinte.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu), si vous avez le sentiment qu'une médiation est nécessaire.        

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu). Cette prise de contact n'aura aucun impact négatif sur le résultat de l'évaluation. Merci de nous aider à créer un espace d’échange et de discussion sûr.

@fdlaramee  Merci de confirmer par commentaire que, en tant que traducteur du tutoriel dont il est question dans ce ticket, tu cèdes à  ProgHist Ltd le droit de le publier sous licence [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.fr).

**Comment by mariechristineb** [comment]
@fdlaramee, la traduction dans son ensemble me semble d'une très bonne qualité, voici donc mes commentaires ponctuels:

- Ligne 41: ‘Dans l'état actuel de l'édition savante, la séparation du code et de l'argument écrit peut être inévitable et leur réunification impossible, du moins sans franchir de nombreux obstacles.’ Phrase un peu maladroite, j’ai dû la relire pour être bien sûre d’avoir compris. 

- Ligne 41: ‘carnets Jupyter Notebooks’ vs ‘carnets Jupyter’ au début du texte (ou devrait-on lire ‘carnets Jupyter Notebook’?)

- Ligne 47: Petite redondance ici: ’qui s'appliquent surtout dans des contextes qui ne s'appliquent pas à vous’ 

- Lignes 53 à 63: Est-ce qu’on a des lignes directrices en ce qui a trait aux listes? J’aurais tendance à utiliser des minuscules au début des éléments de l’énumération, mais les instructions pour la mise en forme en anglais demandent plutôt d’utiliser les majuscules et d’omettre la ponctuation à la fin des éléments.  

- Ligne 71: « interface utilisateur » me semble avoir un usage nettement plus répandu 

- Ligne 77: faute de frappe dans ‘expression’

- Ligne 95: Il semble y avoir une coquille dans le markdown (dans la preview du moins?), je vois seulement ‘section portant sur Binder’, alors que dans le fichier, je vois le reste du paragraphe, sauf qu’il manque un saut de ligne avant le prochain paragraphe. 

- Ligne 97: Y a-t-il un coquille dans le Markdown? Une des paires d’astérisques n’est pas fermée.

- Ligne 113: J’ajouterais une virgule devant ‘puis’.

- Ligne 123: ‘/Utilisateurs/‘ au lieu de ’Users’? J’imagine qu’on peut prendre pour acquis que les lecteurs utilisent l’interface en français.

- Ligne 125: Il manque un mot: ’puisque, comme Google Drive, Notebook (*fournit*?) sa propre barre d'outils’. 

- Ligne 150: ‘Getting started with Markdown’ a depuis été traduite et publiée en français.
 
- Ligne 213: faute de frappe, ‘au *lieu* d’un nombre’

- Lignes 286, 289, 331: Coquille dans le nom du nouveau fichier: ‘example’.

- Ligne 392: Coquille à la fin du paragraphe: ‘plus plus de détails’.

- Ligne 394: ‘il vaut la peine de contacter le personnel des services informatiques de votre institution pour connaître la *marche* à suivre’; 
‘communiquent parfois plus brusquement que ce à quoi vous êtes habitués mais ne vous laissez pas abattre’ - j’aurais tendance à mettre une virgule devant ‘mais’.

- Ligne 376: ‘sachez tout de même que n’importe *quel* passage’

- Lignes 349 & 398: J’ai sursauté un peu à l’usage du surnom dans le texte, commun dans le contexte anglo-saxon, mais qui pourrait passer pour une erreur dans un texte en français.

- Ligne 400: ‘étroitement couplé avec son sujet’, ‘couplé’ me semble un peu maladroit, peut-être ‘rattaché/intimement lié’ à son sujet’?

**Comment by fdlaramee** [comment]
Merci @mariechristineb ! 

@spapastamkou : Si je n'ai pas de tuiles qui me tombent sur la tête d'ici là, je devrais pouvoir compléter les révisions vendredi le 9; sinon, ce sera durant la semaine du 19.

**Comment by fdlaramee** [comment]
En tant que traducteur de ce tutoriel, je cède à ProgHist Ltd le droit de publier ma traduction sous licence CC-BY.

**Comment by spapastamkou** [comment]
@mariechristineb Merci beaucoup pour la relecture. Je te laisse @fdlaramee le soin d'apporter les modification que tu trouves les plus pertinentes selon tes disponibilités et à ta convenance. Je peux me charger d'ajouter les liens et les titres des tutoriels entretemps traduits à l'intérieur du texte, pas de souci. 
Merci à vous deux pour ce travail.

**Comment by fdlaramee** [comment]
Bonjour @mariechristineb @spapastamkou ! Voilà, j'ai enfin trouvé le temps d'apporter les correctifs suggérés. (Je les ai tous intégrés sans exception, sauf erreur.)

Prévenez-moi s'il manque autre chose à faire avant la publication.

**Comment by spapastamkou** [comment]
Merci @fdlaramee! Je pourrai travailler sur ce tutoriel le weekend qui nous vient, en ce qui me concerne en espérant d'en assurer la mise en ligne par la suite. Je vous tiens au courant et je reste à la disposition de vous deux.

**Comment by spapastamkou** [comment]
@fdlaramee J'ai fait le contrôle éditorial et ai intégré certaines modifications mineures notamment pour faciliter la lecture ( par exemple, remplacer les guillemets par des italiques pour les termes utilisas dans l'interface - afin d'alléger le texte - et remplacer les guillemets anglais avec des guillemets français). Tu peux vérifier ces modifications dans les commits: 
https://github.com/programminghistorian/ph-submissions/commit/d4960ddd6bc11d220e8c8ab55d5ab102c39dfbd2
https://github.com/programminghistorian/ph-submissions/commit/258a86a8d3d8fba8aa991831aaa42d0de8fb198f
https://github.com/programminghistorian/ph-submissions/commit/8857dc1de0501d0670c730126735237627cc7eac
https://github.com/programminghistorian/ph-submissions/commit/bf0a69093d5beb1208826f02a272f533fb4fac56
https://github.com/programminghistorian/ph-submissions/commit/790124a5b4f2999424a3d66573c98075423f53e9

Dis-mois ce que tu en penses, sachant que tu peux toujours réagir lors de la pull request, je solliciterai ta review. 

Merci pour ce travail, et merci une nouvelle fois à @mariechristineb pour la relecture.

**Comment by spapastamkou** [comment]
Le tutoriel est en ligne, merci pour tout votre travail @fdlaramee et @mariechristineb !
