### ISSUE TITLE
Proposta de tradução: Preservar os dados de investigação

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#311]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Preserving Your Research Data' [Preservar os dados de investigação] por @MarciaCavalcanti.
 	
Para promover uma publicação rápida desta lição traduzida, eu @joanacvp irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
@joanacvp obrigado por ter dado início ao processo. Nestas submissões para o "nosso" PH podemos trabalhar em português ;-)
