### ISSUE TITLE
Proposta de tradução: Noções básicas de páginas web e HTML

### ISSUE THREAD

**Issue by daniellesanchesDH** [programminghistorian/ph-submissions#318]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Noções básicas de páginas web e HTML' pela @aracele . 

Para promover uma publicação rápida desta lição traduzida, eu @daniellesanchesDH  irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

O contato editorial principal desta lição é @daniellesanchesDH . Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by daniellesanchesDH** [comment]
@bgmartins essa também é uma das nossas lições para revisão. Obrigada, Danielle.

**Comment by daniellesanchesDH** [comment]
@romulopredes essa seria a lição para revisão. Desde já agradeço, Danielle.

**Comment by romulopredes** [comment]
Estou à disposição!

**Comment by bgmartins** [comment]
Olá @daniellesanchesDH, @romulopredes.

Deixei algumas revisões sobre o texto da lição "Noções básicas de páginas web e HTML"

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/visualizando-arquivos-html.md

**Comment by romulopredes** [comment]
Excelente, @bgmartins! 

Por inexperiência com o GitHub e o Visual Studio Code, eu ainda não havia encontrado a lição traduzida (anterior a sua revisão) - cheguei a acreditar que a mesma ainda não havia sido submetida. 

Consegui agora, enfim, visualizar como foi traduzida a lição original e estou de acordo com as revisões propostas!

**Comment by daniellesanchesDH** [comment]
Muito obrigada @bgmartins e @romulopredes !! @aracele você poderia rever as indicações realizadas pelo @bgmartins ? Qualquer dúvida entre em contato comigo.

**Comment by aracele** [comment]
Olá @daniellesanchesDH, pra mim me parecem ótimas! Agradeço a paciência, só consegui realizar a revisão agora. Obrigada também @romulopredes  e @bgmartins pela revisão!

**Comment by daniellesanchesDH** [comment]
Perfeito @aracele ! Obrigada a todos pela colaboração!

**Comment by daniellesanchesDH** [comment]
@DanielAlvesLABDH revisão fechada, pronta para incorporação no site!

**Comment by DanielAlvesLABDH** [comment]
Olá @aracele e @daniellesanchesDH. Estive a rever e é necessário introduzir algumas correcções. Deixo abaixo as indicações para a Aracele.
No cabeçalho YAML do ficheiro (linhas 1 a 26) têm de ser incluídas as linhas relativas à tradução, edição da tradução e revisão da tradução. Veja esta lição para comparação: https://github.com/programminghistorian/jekyll/blob/gh-pages/pt/licoes/preservar-os-seus-dados-de-investigacao.md
falta o slug na linha 4 - sugiro que fique nocoes-basicas-paginas-web-html
linha 25 - O DOI tem de ser apagado. No final da revisão será solicitado um novo DOI
linha 34 - incluir ## antes do título
linha 35 - apagar ------
linha 56 - falta link para o "tutorial de HTML"
linha 75 - onde está "definida como inglês americano" não poderíamos colocar "definida como português brasileiro" ou "português europeu" e mudar o código correspondente na linha 80?
linha 110 - onde está "Abrir menu -> Abrir arquivo..." deve ficar "Abrir menu -> Abrir ficheiro..."
linhas 115 a 119 - a formatação dos links parece duplicada ou estranha

Obrigado a ambas!

**Comment by aracele** [comment]
> Olá @aracele e @daniellesanchesDH. Estive a rever e é necessário introduzir algumas correcções. Deixo abaixo as indicações para a Aracele.
> No cabeçalho YAML do ficheiro (linhas 1 a 26) têm de ser incluídas as linhas relativas à tradução, edição da tradução e revisão da tradução. Veja esta lição para comparação: https://github.com/programminghistorian/jekyll/blob/gh-pages/pt/licoes/preservar-os-seus-dados-de-investigacao.md
> falta o slug na linha 4 - sugiro que fique nocoes-basicas-paginas-web-html
> linha 25 - O DOI tem de ser apagado. No final da revisão será solicitado um novo DOI
> linha 34 - incluir ## antes do título
> linha 35 - apagar ------
> linha 56 - falta link para o "tutorial de HTML"

Não, é assim mesmo, é o modo como o Markdown faz referência interna (in-line)

> linha 75 - onde está "definida como inglês americano" não poderíamos colocar "definida como português brasileiro" ou "português europeu" e mudar o código correspondente na linha 80?

coloquei "pt" porque corresponde a ambas as linguas.

> linha 110 - onde está "Abrir menu -> Abrir arquivo..." deve ficar "Abrir menu -> Abrir ficheiro..."
> linhas 115 a 119 - a formatação dos links parece duplicada ou estranha

Tá correta, essa é a forma que o Markdown faz referência in-line e também mostra os links externos.

> 
> Obrigado a ambas!

Fiz as alterações sugeridas. Confiram, por gentileza, se está tudo ok mesmo! Brigada!

**Comment by DanielAlvesLABDH** [comment]
Obrigado @aracele , ficou óptimo. Alterei apenas as linhas 32 e 33 para traduzir o "avatar-alt" (algo que é necessário fazer a partir de agora) e acrescentar a linha do "doi", bem como a linha 23 para incluir o link para o ticket de revisão. Parabéns! Primeira lição traduzida! @daniellesanchesDH vou pedir o DOI e depois publicar esta lição.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @aracele, @bgmartins e @romulopredes, pela tradução e revisão desta lição! Muito obrigado @daniellesanchesDH pela edição! Já está publicada. Danielle, pode fechar este ticket.

**Comment by daniellesanchesDH** [comment]
Muito obrigada @aracele, @bgmartins e @romulopredes pela tradução e revisão da lição!! Obrigada também  @DanielAlvesLABDH pela gestão de tudo e publicação!!
