### ISSUE TITLE
Relecture de traduction: Installing Python Modules with pip

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#320]
Le Programming Historian en français a reçu la traduction du tutoriel "Installing Python Modules with pip" sous le titre "Installation des modules Python avec pip" par @Lucaterre (ticket de proposition: #293). Une prévisualisation du texte est disponible ici: http://programminghistorian.github.io/ph-submissions//fr/traductions/installation-modules-python-pip

J'ai sollicité une relecture auprès de @fdlaramee ; je vais assurer le suivi éditorial de cette traduction et coordonner les échanges qui auront lieu dans cet espace. La relectrice pourra utiliser la numérotation des paragraphes fournie dans l'aperçu pour signaler ses commentaires, si cela lui convient, mais elle a la liberté de faire comme elle jugera mieux. Nos relecteurs peuvent aussi s'appuyer sur les [consignes aux traducteurs et aux traductrices](https://programminghistorian.org/fr/consignes-traducteurs#traduire-une-le%C3%A7on-et-la-mettre-en-page). Nous pouvons prévoir un délai de 30 jours environ, qui peut néanmoins être adapté si besoin. 

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de l'évaluation formelle, pour que le traducteur puisse travailler sur la révision de son texte. L'annonce sera faite sur ce fil quand cette étape aura été atteinte.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu), si vous avez le sentiment qu'une médiation est nécessaire.        

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu). Cette prise de contact n'aura aucun impact négatif sur le résultat de l'évaluation. Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by spapastamkou** [comment]
@Lucaterre Merci de confirmer par commentaire que, en tant que traducteur du tutoriel dont il est question dans ce ticket, vous cédez à ProgHist Ltd le droit de publier cette traduction sous licence [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.fr).

**Comment by spapastamkou** [comment]
@Lucaterre Je vous copie ci-dessous le gabarit concernant les droits. Vous pouvez le soumettre en commentaire au moment de votre préférence, avant ou après finalisation de la relecture.  

Je [prénom, nom OU nom d'utilisateur]traducteur cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier la traduction du tutoriel dont il est question dans ce ticket (y compris le résumé, les tables, les illustrations, les données, et des ressources supplémentaires) sous licence [CC-BY](https://creativecommons.org/licenses/by/4.0/deed.fr).

**Comment by Lucaterre** [comment]
Je, Lucas TERRIEL, traducteur cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier la traduction du tutoriel dont il est question dans ce ticket (y compris le résumé, les tables, les illustrations, les données, et des ressources supplémentaires) sous licence CC-BY.

**Comment by fdlaramee** [comment]
Bonjour @spapastamkou @Lucaterre !

J'ai procédé à la relecture de la traduction. Voici mes commentaires. 

D'abord, merci @Lucaterre pour ce travail! Veuillez considérer les commentaires suivants comme des suggestions qui visent à alléger le texte; libre à vous et à Sofia de choisir, parmi ces suggestions, celles qui vous conviennent.

**A) Considérations générales**

La traduction utilise "module" et "librairie" de façon interchangeable. Nous n'avons pas encore défini clairement nos règles d'édition, mais y aurait-il lieu de choisir un terme et de s'y tenir?

Même question pour l'espace avant le point-virgule et les deux points. La règle d'usage n'est pas la même au Québec (pas d'espace) qu'en Europe, je crois.

Enfin, nous utilisons habituellement "leçon" comme traduction de "tutorial", plutôt que "tutoriel". 

**B) Notes spécifiques**

Les notes ci-dessous sont marquées du numéro de paragraphe tel qu'il apparaît dans la version de prévisionnement.

Paragraphe 2: Les version de Python qui datent d'avant 2.7 sont loin d'être encore fréquentes; en fait, Python a officiellement abandonné 2.x il y a un an ou deux. Il vaudrait peut-être mieux couper les deux dernières phrases de ce paragraphe, même si elles apparaissent encore dans le (vieux) texte anglais, d'autant plus qu'elles sont contredites par la remarque en retrait du paragraphe 5. Si on les garde, il faudrait changer "reste" par "restent" dans la dernière phrase.

Paragraphe 3: "largement et aisément disponible" me semble une traduction trop littérale. "... mises à la disposition des programmeurs" est plus élégant.

Paragraphe 3: remplacer "telles que:" par "par exemple:"

Paragraphe 4: remplacer "ajoutant" par "ce qui ajoute"

Paragraphe 4: utilisé --> utilisées

Paragraphe 5: changer la dernière phrase pour quelque chose comme: "Ce programme s'appelle pip." 

Remarque au paragraphe 5: Résoudre le conflit de message avec le paragraphe 2. Remplacer "dans le cas contraire" par "si c'est votre cas"

Paragraphe 9: Remplacer "scripts aléatoires" par "scripts de provenance inconnue"

Paragraphe 10: Il y a désaccord entre deux phrases; pour le régler, je remplacerais la seconde par "Je vous en pris, n'ayez crainte." 

Paragraphe 11: Couper la première phrase en deux après "exécuter".

Paragraphe 12: remplacer "se situe" par "se trouvent" 

Bloc de code entre les paragraphes 12 et 13: La traduction est correcte mais je crois qu'il y a une erreur dans le texte anglais. Il me semble bizarre que ce bout de code intègre la phrase "to install pip". À vérifier avec Sarah, peut-être?

Paragraphe 14: Dans "car il fait tout le travail", remplacer "il" par "pip" pour éviter un problème de résolution de pronom.

Voilà; merci encore!

**Comment by Lucaterre** [comment]
Bonjour @spapastamkou @fdlaramee !

Je vous remercie @fdlaramee pour vos conseils et corrections ! 

Je note juste qu'une librairie (= _package_ en anglais) est une collection de modules en Python. Ici l’auteur parle donc de librairies (comme requests, ppprint etc.) par exemple  : 

```from bs4 (librairie ou package) import Beautifulsoup (module de la librairie bs4)```  

De fait j’ai harmonisé "modules" en "librairie" et j’ai conservé l’appellation « librairies externes » car je présume que l’auteur distingue les librairies _Built-in_ de Python de celles qui sont installées avec `pip`.

J'ai procédé à la correction générale de la leçon dans le dossier`ph-submissions/fr/traductions/`, cependant les remarques suivantes restent en suspens : 

- **Paragraphe 2** : Concernant Python 2.x je suis d’accord @fdlaramee  pour dire que cette version n’a plus cours; le support de la dernière version 2.7 a pris fin le 1er janvier 2020 et sa prise en charge n’est plus disponible. Je serai d'avis pour supprimer les deux dernières phrases du paragraphe 2 qu’en pensez-vous ? Sauf si certains lecteurs de PH utilisent Python 2.x dans ce cas...  (Toujours dans le texte pour l'instant…)

- **Bloc de code entre les paragraphes 12 et 13** : c’est très étrange par ce que l’instruction 
```$ python get-pip.py``` (Cf. [Install pip on Windows](https://ehmatthes.github.io/pcc/chapter_12/installing_pip.html)) suffit a installer `pip` sur Windows ```$ python get-pip.py to install pip``` est une erreur de l'auteur ou une commande erronée (je ne trouve nulle part de référence ```$ python get-pip.py install pip``` et encore moins à ```$ python get-pip.py to install pip```). Peut-être peut-on la remplacer ? 

bonne réception, merci 👍

**Comment by spapastamkou** [comment]
Merci à vous @fdlaramee et @Lucaterre. Je regarde les questions qui restent en suspension asap et reviens vers vous au plus vite.

**Comment by icolab** [comment]
Bonjour, 
je me permets de réagir comme j'ai participé à l'installation d'environnement Python il y a peu auprès d'étudiants. Attention à un cas particulier (par exemple sur certains Linux ou parfois sur MacOs), pip est déjà installé avec Python 2.x, il faut alors installer pip3 et la commande pour lancer pip devient alors `pip3 install`. 
Et juste j'ai un doute mais sur WIndows, `cd` ne fonctionne pas sauf dans le PowerShell

**Comment by Lucaterre** [comment]
Bonjour, 

merci pour ces précisions @icolab ! Il me semble que `pip` créé des liens logiques vers les versions de Python, si Python 2.x existe de base dans la machine et que Python 3 est installé : `pip install` pointera vers la version 2.x et `pip3 install` vers la version 3.x; en revanche, si Python 3.x est installé seul alors `pip`est un lien vers `pip3`, on peut alors utilisé l'un ou l'autre indistinctement pour installer des _packages_ dans la version 3.x. On peut vérifier ces chemins dans la machine avec les commandes : 
```
$ ls -l `which pip` 
$ ls -l `which pip3` 
```
Après concernant l'article la question était de savoir si `python get-pip.py to install pip` était une commande correcte et de savoir si le "to" était en trop dans le bloc de code entre les paragraphes 12 et 13.

Je suis sur Mac, mais il me semble que `cd` fonctionne maintenant dans l'interface de commande Windows, en sus du PowerShell, et à remplacer ou fait la même chose que `chdir` ([doc cd Windows](https://docs.microsoft.com/fr-fr/windows-server/administration/windows-commands/cd))... à vérifier

bien à vous !

**Comment by icolab** [comment]
Bonjour @Lucaterre 
Exactement. Le cas décrit vaut pour certains environnements (par exemple sur ubuntu tu as directement le paquet `apt python-pip3` comme le pip est configuré avec Python 2.x). Il est important de s'assurer que c'est la bonne version de pip pour certaines extensions. Par exemple Django avec Python 2.x est en version 1.x alors qu'avec Python 3.x tu as la version 3.1.2
Pour le paragraphe 12-13 je ne sais pas trop. Je n'utilise plus Windows (et configurer un environnement de dev avec est une catastrophe), je faisais installer avec Anaconda python et pip.
Par contre, je confirme que `cd` ne fonctionne pas dans le terminal standard mais qu'il va fonctionner dans le PowerShell.
Bonne journée

**Comment by spapastamkou** [comment]
Je viens d'intégrer directement [quelques modifications pour fixer le markdown et ajouter des métadonnées yaml](https://github.com/programminghistorian/ph-submissions/commit/3974327c9ab45a15724aae13a06945aa0d2aae76) - ce qui fait partie du travail qu'un rédacteur ou une rédactrice effectue lors de la finalisation d'une leçon. 

Au reste, en ce qui concerne le fond et aussi tenant compte des questions qui émergent dans les commentaires (merci pour ces échanges fertiles!) voici quelques commentaires et propositions de mon coté: 

*Questions d'harmonisation*  
1. Remplacer le terme "**librairies**" par "**bibliothèques**" pour éviter d'avoir un faux ami dans la traduction et être en conformité avec la documentation de Python qui mobilise ce 2e terme (et c'est le cas aussi pour R, même s'il est vrai que librairie est utilisé couramment par les utilisateurs).  

2. Harmoniser les occurrences "**Python**" et "**python**" (la confusion vient de l'original EN) en tranchant pour "Python" partout. 

3. Harmoniser "script" et "*script*" en italiques en tranchant pour script sans italiques. 

*Questions de traduction/modifications fond/forme (selon aussi vos commentaires ci-dessus): je copie d'abord la phrase telle qu'elle est actuellement et à la suite de '=>' il y a la suggestion que je fais.*  

§ 2
Cette leçon vous présente la manière de télécharger et d’installer des librairies Python. 
=> Cette leçon vous présente la manière de télécharger et d’installer des bibliothèques Python en plus de *(ou autres que??)* la bibliothèque standard distribuée avec le programme.

Depuis Python 2.7.9 et ses versions plus récentes, pip est installé par défaut. Cette leçon sera également utile pour les utilisateurs d’anciennes versions de Python (qui restent encore assez courantes).
=> Depuis Python 3.4, pip est inclus dans l’installation par défaut. Si pour quelque raison que ce soit vous avez besoin d'installer ou mettre à jour vous-même pip, ces instructions devraient vous aider 

*Avec suppression parallèle du paragraphe 6*

§ 3
fichier CSV => ajouter lien: https://fr.wikipedia.org/wiki/Comma-separated_values 

§ 4
Il existe de nombreuses façons de le faire (ce qui ajoute ainsi de la confusion) 
=>
Il existe de nombreuses façons de le faire, ce qui ajoute ainsi de la confusion

§ 5
Le but ici est d’installer un logiciel (software) 
=> Le but ici est d’installer un gestionnaire

§ 8 
Le script échouera très probablement =>
le script échouera très probablement

§ 10
Comme pour les distributions ci-dessus => 
Comme pour les distributions précédentes

§ 12-13 
*Il existe en effet un problème dans le code, la partie ```to install pip``` s'est manifestement incrustée par erreur dans le bloc, alors qu'elle continue la phrase (péjorative, hors code) qui précède le code dans l'original en anglais. On va le corriger ici et je veillerai avec les autres ME à ce que les versions EN et ES le soient aussi lorsque je ferai la pull request pour cette leçon.*

Au reste, concernant pip/pip3, il me semble intéressant d'insérer sous forme de note de la traduction FR une petite mise en garde par rapport aux problèmes qui peuvent surgir et attirer l'attention sur les vérifications à faire le cas échéant (@Lucaterre, résumer en fait l'essentiel de vos échanges avec @icolab comme c'est plus ou moins le cas dans vos commentaires: exposer brièvement le pb qui peut surgir et expliquer comment vérifier, avec les requêtes que vous avez dans votre commentaire). Vous en pensez quoi? 

Merci de me dire ce que vous en pensez et je me charge par la suite pour insérer les dernières modifications dans le texte/code. 

Un grand merci à tous pour ce travail et pour ces échanges!

**Comment by Lucaterre** [comment]
Bonjour @spapastamkou,

Tout d'abord merci pour ces remarques et ces suggestions, je reprends dans l'ordre : 

**1 - *Questions d'harmonisation*** 

Je suis d'accord dans l'ensemble, j'ai moi même effectué les modifications dans le markdown de l'article (voir l'historique des commits)

**2- *Questions fond/forme***

§ 2
Cette leçon vous présente la manière de télécharger et d’installer des librairies Python.
=> (autre proposition : ) Cette leçon vous présente la manière de télécharger et d’installer des bibliothèques Python en plus des bibliothèques standards distribuées (*built-in*) avec le langage de base.

Depuis Python 2.7.9 et ses versions plus récentes, pip est installé par défaut. Cette leçon sera également utile pour les utilisateurs d’anciennes versions de Python (qui restent encore assez courantes).
=> Je suis d'accord pour la proposition et la suppression du § 6

§ 3
Ok pour l'intégration du lien CSV

§ 4
Ok pour la correction

§ 5
idem

§ 8
En effet, la phrase continue après l'exemple donc pas de lettre capitale

§ 10
Ok pour la correction 

§ 12-13
Ok pour la correction du code

**3- *Note de traduction FR/Mise en garde***

Je propose une première ébauche de note (peut-être à insérer au niveau du §14):

*Le gestionnaire pip crééé des liens logiques vers les versions de Python. En effet, si votre ordinateur inclut initialement la version 2.x de Python, la commande `pip` pointera alors sur cette version de Python. En revanche, si vous décidez d'installer Python en version 3.x en plus de Python 2.x, il vous faudra très certainnement utiliser la  commande `pip3` dans votre terminal et non plus `pip` pour installer des bibliothèques pour Python 3.x. Afin de connaitre quelle version de Python vous utilisez avec la commande `pip`, lancer dans le terminal la commande `pip -V` ou `pip --version`*

Dans l'attente de vos retours,

Bonne année 2021 :fireworks: et bonne journée :)

**Comment by spapastamkou** [comment]
Super, merci beaucoup pour ce retour @Lucaterre. J'intégrerai donc les modifications finales en tenant compte des suggestions les plus récentes et ferai le nécessaire pour publier la leçon dans les jours qui viennent. Merci aussi pour vos précédentes modifications en vue de l'harmonisation de la forme. Et une excellente année 2021 de mon côté aussi:-)

**Comment by spapastamkou** [comment]
La leçon est maintenant [en ligne](https://programminghistorian.org/fr/lecons/installation-modules-python-pip). Je vous remercie tous pour vos contributions, traduction, relecture, et échanges y compris.
