### ISSUE TITLE
Proposta de tradução: "Instalação e Introdução ao Python"

### ISSUE THREAD

**Issue by daniellesanchesDH** [programminghistorian/ph-submissions#321]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Instalação e Introdução ao Python' pelo @josircg . 

Para promover uma publicação rápida desta lição traduzida, eu @daniellesanchesDH irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

O contato editorial principal desta lição é @daniellesanchesDH . Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Esta lição já foi publicada, podemos fechar isto!
