### ISSUE TITLE
Revisão de "Proposta de tradução: Instalação e Introdução ao Python"

### ISSUE THREAD

**Issue by daniellesanchesDH** [programminghistorian/ph-submissions#323]
O Programming Historian em português recebeu a proposta sobre 'Instalação e Introdução ao Python' do autor @aracele . Esta lição está agora em revisão por @rsouza e @bgmartins e pode ser lida em:

Eu (@daniellesanchesDH ) serei a editora no processo de revisão. O meu papel é solicitar duas revisões da comunidade e gerir as discussões, que devem ser realizadas aqui neste fórum. Eu já li a lição e forneci feedback, ao qual o autor respondeu.

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso ombudsperson Luís Ferla se achar necessário.

Política anti-assédio

Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso ombudsperson Luís Ferla. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by rsouza** [comment]
Cara @daniellesanchesDH,

Obrigado pelo convite. Vou trabalhar na revisao a partir deste fds.

Um abraco,
Renato

**Comment by daniellesanchesDH** [comment]
@bgmartins precisamos de feedback em relação a esta lição. Muito obrigada.

**Comment by bgmartins** [comment]
Olá @daniellesanchesDH 

Neste momento já fiz uma revisão sobre os ficheiros da lição "Instalação e Introdução ao Python."

**Comment by DanielAlvesLABDH** [comment]
Olá @daniellesanchesDH, @bgmartins e @rsouza!, como está este processo? Podemos avançar no processo de revisão? Era bom concluir estas lições de Python, pois temos outras em tradução que têm links para estas. Se for necessário alguma ajuda, é só dizer!

**Comment by bgmartins** [comment]
Penso que podemos avançar, não sei se existiram mais revisões sobre a última minha (na qual não fiz muitas alterações, o conteúdo estava já bastante polido).

**Comment by DanielAlvesLABDH** [comment]
Obrigado @bgmartins ! Vou proceder à verificação final destes ficheiros introduzindo pequenos ajustes no cabeçalho, no texto e nos links. Os ficheiros originais estão aqui:
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/introducao-instalacao-python.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/instalacao-mac.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/instalacao-windows.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/instalacao-linux.md

**Comment by DanielAlvesLABDH** [comment]
Foram feitas adaptações do português, correcção de gralhas, correcção do posicionamento das imagens, actualização de links e configuração do cabeçalho nos quatro ficheiros. Vou agora requisitar os DOI e publicar

**Comment by DanielAlvesLABDH** [comment]
@daniellesanchesDH este também já está concluído e publicado. Obrigado a todos!

**Comment by DanielAlvesLABDH** [comment]
Já publicada, podemos fechar!
