### ISSUE TITLE
Proposition de traduction: Introduction à Beautiful Soup

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#324]
Le Programming Historian en français a reçu la proposition de traduction de la leçon "[Introduction to Beautiful Soup](https://programminghistorian.org/en/lessons/intro-to-beautiful-soup)" de la part de @Lucaterre. 
Nous prévoyons un délai de deux mois pour achever cette traduction (4 février 2021) avec la possibilité de réajustement si besoin. Par la suite, une fois la traduction déposée, un membre @programminghistorian/french-team assurera le suivi éditorial pour publier cette traduction. Avec nos remerciements pour cette proposition.

**Comment by Lucaterre** [comment]
Bonjour,

Tout d'abord je voulais m'excuser pour le retard...

La traduction de la leçon "Intro à beautifulsoup" (`intro-a-beautifulsoup.md`) est terminé et a été déposé dans le dossier `ph-submissions/fr/traductions`.

Quelques remarques sur la traduction (à intégrer au ticket de relecture ?) :

Sur le contenu :

- L'exemple de la base du donnée du Congrès (BioGuide) utilisé par l'auteur a subit depuis la rédaction de l'article une mise à jour majeure; de fait la stratégie de *scraping* HTML envisagé par l'auteur dans la leçon ne fonctionne plus aujourd'hui pour le même lien, cependant le code reste fonctionnel au regard de l'ancien HTML (peut-être faut-il intégré un avertissement ou une note du traducteur aux lecteurs ?);
- J'ai conservé le terme de *scraping* (je n'ai pas trouvé d'équivalent français) et de *parseur* (au lieu d'"analyseur syntaxique" qui peut prêter à confusion) dans l'article;
- J'ai conservé le terme anglais "pretty" avec "jolie" qui fait référence au paramètre `pretty_print` de la méthode `.to_string()`et à la méthode `.prettify()` de BS4;
- L'auteur désigne `href` comme un élément dans le texte, alors qu'il s'agit d'un attribut HTML;
- De même, l'auteur désigne `.contents` et `.get()` comme deux méthodes ("...commonly used Beautiful Soup methods: contents and get..."), or dans le premier cas il s'agit d'un attribut de classe et dans l'autre d'une méthode de classe (lien vers la doc BS4 : https://www.crummy.com/software/BeautifulSoup/bs4/doc/#descendants), même s'il peut s'agir d'un détail.
- hésitation dans l'utilisation des termes "langages à balises" ou "langages de balisage" pour traduire "markup language".

Sur la forme :

- Je ne sais pas quelle est la pratique de PH pour intégrer les images dans la leçon, j'ai utilisé des balises HTML dans le doute...

Je vous remercie d'avance pour les remarques et les corrections que vous pourrai apporter;

**Comment by spapastamkou** [comment]
Cher @Lucaterre, merci à nouveau pour ce travail! Nous allons en effet intégrer le commentaire ci-dessus au ticket de la relecture, en plus de vérifier de notre côté la syntaxe de la leçon. Je maintiens ce ticket ouvert le temps de voir qui d'entre nous peut assurer le suivi éditorial de la traduction. Encore merci.

**Comment by spapastamkou** [comment]
Note pour l'équipe FR: j'ai mis à jour la partie métadonnées du fichier, notamment pour avoir le nom du traducteur explicitement dedans: c'est plus sage, vu qu'il y a pas mal de fichiers qui sont ajoutés en ce moment dans le dépôt. Je n'ai rien touché d'autre, il reste donc à tenir compte des [commentaires ci-dessus formulés](https://github.com/programminghistorian/ph-submissions/issues/324#issuecomment-811800370) lors de la première lecture de contrôle qu'effectuera le membre de l'équipe qui assurera le suivi éditorial de la traduction.

**Comment by spapastamkou** [comment]
traduction en cours de relecture #400
