### ISSUE TITLE
Ticket de revisión de traducción: Análisis de correspondencia en R

### ISSUE THREAD

**Issue by jamotilla** [programminghistorian/ph-submissions#331]
The Programming Historian en español ha recibido la siguiente propuesta de traducción: "Análisis de correspondencia en R" de la lección "Correspondence analysis for historical research with R" por parte de @rivaquiroga y @bmmedinac. Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

**[Vista previa]**
http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/analisis-de-correspondencia-en-r

**[Archivo]**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/analisis-de-correspondencia-en-r

**[Imágenes]**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/analisis-de-correspondencia-en-r

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra *ombudperson*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jamotilla** [comment]
Estimados @rivaquiroga y @bmmedinac en los próximos días tendré lista mi lectura de su traducción. Los mantendré al tanto. Saludos

**Comment by rivaquiroga** [comment]
@jamotilla, ¿pudiste darle una mirada inicial a la lección?

**Comment by jamotilla** [comment]
Listo @rivaquiroga van mis observaciones: 

- [x] P1. puede se puede
- [x] P2. El análisis de correspondencias mide las correspondencias más fuertes / arreglar la oración para evitar la repetición de palabras
- [x] P3. Particularmente, es una herramienta poderosa para entender / Sugiero utilizar : Es una herramienta particularmente poderosa para entender…
- [x] P.4. Después de leer este tutorial deberías / sugiero: Después de leer este tutorial sabrás: 
- [x] P.6. El tutorial de Taryn Dewar…tiene información / ofrece o contiene información 
- [x] P.6. El tutorial de Taylor Arnold… puede servir también / también puede servir
- [x] P.7  …no sería malo / vale la pena / es recomendable 
- [x] P.9. periodo de tiempo / periodo (creo que periodo implica el elemento temporal, por lo tanto es redundante)
- [x] P. 10. Los con orientación al pacífico / los países orientados hacia el pacífico
- [x] P. 12. Se ubican en las afueras / se ubican en la parte externa
- [x] P. 13. Un punto más sustancial / (es necesario expresarlo de otra manera, por ejemplo eliminar el “más”)
- [x] P. 13. O actitudes generales / o debido a actitudes generales
- [x] P.15 a la legislación en Canadá/ a la legislación canadiense. 
- [x] P. 36. A el/ al 
- [ ] P.36. ¡de un total… / ¡De un total
- [x] P. 36. Revisar el párrafo para evitar la repetición de la palabra “esto”
- [x] P. 37. Revisar el párrafo para evitar la repetición de la palabra “inercia”
- [x] P. 41. Este resultado es muy sorprendente / (sugiero eliminar “muy)
- [x] P. 55. Dicho eso, hay menos MP compartiendo las posiciones también / (sugiero eliminar “también”).
- [ ] P. 56. entre asuntos sociales, como Salud y Justicia, y asuntos económicos, como Finanzas y Relaciones Exteriores, que da cuenta del 35% de la varianza / (si bien en algunas partes del texto el uso de altas es indispensable para designar las abreviaturas, considero que en la sección de análisis no lo es, por lo tanto sugiero utilizar bajas) 
- [x] P. 58. Tal vez otras fuentes de evidencia / (sugiero suprimir evidencia)
- [x] P. 62. están distribuidas demasiado uniformemente / suprimir demasiado
- [x] P.66. ara / para
- [x] P.66. Apéndice/ apéndice
- [x] P.66. detalle/detalles

**Comment by rivaquiroga** [comment]
¡Muchas gracias @jamotilla! En los próximos días incorporamos los cambios :writing_hand:

**Comment by rivaquiroga** [comment]
@jamotilla, ya incorporamos los cambios. En el caso de la sugerencia del párrafo 26, dejamos ese fragmento tal como estaba porque la exclamación está dentro de la misma oración, así que corresponde que esté con mayúscula (otra opción sería reformular todo ese fragmento). En el caso del párrafo 56, mantuvimos el uso de mayúsculas ya que se trata de los nombres propios de los comités.
Quedamos a la espera de los comentarios de los revisores.

**Comment by jamotilla** [comment]
Hola @rivaquiroga, tengo muy buenas noticias! @silviaegt será la revisora de éste tutorial! Muchas gracias Silvia!!

**Comment by silviaegt** [comment]
¡Hola  @rivaquiroga y @bmmedinac! ¡Muchísimas gracias por la traducción de este material del que hay poquísima información en español! He aprendido mucho al replicarlo/leerlo y les estoy muy agradecida.
Como ésta es una traducción no estoy muy segura de qué tanto puede cambiarse de la redacción original, así que hay comentarios que haga que no vengan al caso, ya me dirán...

## Comentarios de contenido

- [x] ¶1 tal vez pondría la nota 1 al final del párrafo y no después de la primera frase para que, ya con el contexto, quien lea tenga más posibilidades de entender qué son las categorías en el contexto del AC
- [x] ¶9 en una nota o en el párrafo mismo vería conveniente añadir una nota sobre los datos que se han usado para el gráfico y su fuente
- [x] ¶23 En este párrafo se dice que con una tabla como la que se muestra se pueden "[1] ver que los comités tienen muchos MP y que [2] algunos MP son miembros de múltiples comités"; el primer ejemplo, el de Carolyn Bennett, deja claro lo segundo [2]; pero no estoy segura que lo dicho sobre el “SLUD” sea buen ejemplo de lo segundo? Es decir: por qué se elige a un comité que tiene solo a dos MP, cuando hay otros comités, como el de violencia en contra de las mujeres (IWFA) que tiene 10? Tal vez no estoy entendiendo el punto que quiere hacer el autor
- [x] ¶27 "rowSums puede utilizarse para sumar las filas si fuese necesario (no es nuestro caso, porque todos los comités tienen más de un MP)." --> a mí me aparece que FINA tiene un sólo miembro, me perdí de algo?
- [x] ¶36 "Nuestra primera pista es mirar las dimensiones" -> Nuestra primera pista es mirar las dimensiones (ver Dim 1 y Dim 2 en los ejes horizontales y verticales del gráfico) | sé que no está en el original pero, al ser esta la primera vez que se habla de dimensiones en este sentido, creo que vale la pena explicitarlo tan pronto aparece este concepto. En esa misma línea creo que refrasearía un poco este párrafo:

> En los datos de Harper*, solo un once y diez por ciento de valor explicativo [^explanatory] aparece en los ejes horizontal y vertical, ¡de un total de 21 por ciento! Eso no suena muy prometedor para nuestro análisis. Si recordamos que el total del número de dimensiones es igual al número de filas o columnas (la que sea más pequeña), esto puede ser preocupante.

Propuesta:

> En el AC de Harper, las dos dimensiones que estamos visualizando, explican un 21.3% del total de la varianza en los datos, es decir, un 10.3%, en el eje vertical y 11%, en el horizontal, tienen un valor explicativo. Si recordamos que el total del número de dimensiones es igual al número de filas o columnas (la que sea más pequeña), esto puede ser preocupante.

*creo que no es tanto "en los datos de Harper" como en el AC

- [x] ¶40 "rechazar la hipótesis de que son categorías independientes" | tal vez este señalamiento no corresponde aquí, pero a mí no me queda claro qué significa que las categorías sean o no independientes. Líneas más tarde pareciera que esto significa que esto quiere decir que  "los MP estén distribuidos equitativamente entre comités" pero creo que no es tan claro. ¿Será que se podría explicar con unas líneas como ésta?:

> Dado que este valor p no es menor que 0.05, no puede rechazarse la hipótesis nula. Es decir, que no tenemos evidencia suficiente para decir que existe una asociación entre que dado un cierto MP, estará en un cierto Comité

- [ ] ¶56 este párrafo del análisis me parece conflictivo en diferentes puntos, no es una cosa de la traducción si no del contenido original, pero me gustaría exponerlo aquí con la esperanza de que se pueda discutir y buscar formas de matizar ciertas aseveraciones:

  * _no obtuvimos una respuesta unívoca a nuestra pregunta sobre el poder para las mujeres en los gobiernos parlamentario_ | la pregunta que se hace en el texto es sobre el grado en el que las mujeres MP están conectadas con más o menos CP en un gobierno y otro, siento que la pregunta no es sobre el "poder para las mujeres"
  *  _En el caso de Harper, vemos una división entre asuntos sociales, como Salud y Justicia, y asuntos económicos, como Finanzas y Relaciones Exteriores, que da cuenta del 35% de la varianza._ | como yo entiendo los resultados, del AC no puede derivarse que hay una división entre asuntos sociales y económicos, sino simplemente que los MP de los CP económicos, no participaron en los CP sociales.
    *  _La separación de los comités sugiere que la filosofía de gobierno de Harper separaba las preocupaciones económicas de las sociales, y que los derechos de las mujeres eran principalmente una preocupación de tipo social._ | un poco como en el comentario anterior, me parece difícil sostener la hipótesis de que, por la "no co-ocurrencia de MP" entre los CP sociales y económicos, se pueda sugerir una filosofía distinta de gobierno
    * Haría comentarios en la misma línea para lo que se dice en ¶57 pero no quiero ser redundante

- [ ] ¶58 _El comité de Situación de las Mujeres, en este contexto, parece poseer un posición más central (cercana al origen) en el gobierno de Trudeau que en el gobierno de Harper_ | estaría bien consultar con alguien con un conocimiento más profundo del AC, pero hasta donde yo recuerdo la cercanía al origen (el punto en que se cruzan _x_ y _y_) poco tiene que ver con "centralidad", y más con que ese elemento probablemente no se diferencia en función de ninguno de los datos del estudio. Es decir, entiendo por lo que se aclara al final, que "[q]uienes son miembros de múltiples comités y/o quienes pertenecen a comités con muchos miembros tenderán a tener puntajes normalizados más bajos [...] Es decir, estos miembros serán puestos más hacia el centro de la matriz". Y aunque esto *podría* ser caracterizado como *centralidad* pero no es una medida estándar hasta donde yo entiendo
- [ ] ¶58 _En cierto grado, pareciera que Harper le dió un rol bastante central a la Violencia contra Mujeres Indígenas an la planificación de los comités parlamentarios. Esta evidencia es un contrapunto a las críticas de que Harper no se tomó con seriedad el problema de las mujeres indígenas desaparecidas y asesinadas._ | Si la evidencia es el número de MP que coinciden en este CP me parece que no es tan contundente como para considerarla como tal
- [ ] ¶58 _Como una herramientas exploratoria, el AC ayuda a identificar tales temas a través de observaciones empíricas._ | En línea con los comentarios anteriores, creo que esta última sección es confusa en tanto parece sugerir una equivalencia entre comités con miembros comunes y la importancia de los temas tratados en estos comités.
- [x] ¶58 a mí me parece más claro [esta entrada](https://www.displayr.com/singular-value-decomposition-in-r/) sobre SVD y tiene la ventaja de que está conectado con su programación en R y con este [otro post sobre las matemáticas del AC](https://www.displayr.com/math-correspondence-analysis/) y aún más con esta [serie de videos](https://www.youtube.com/watch?v=gXbThCXjZFM&list=PLMrJAkhIeNNRpsRhXTMt8uJdIGz9-X_1-&index=1)
- [ ] ¶71 no sé si es posible contactar a alguna experta en matemáticas que pudiera revisar a partir de este parágrafo, o sea, en una lectura superficial, me parece que sí es fiel al original pero no tengo las mejores herramientas para evaluarlo.


## Observaciones sobre la redacción

- [x] ¶2 distribuídos -> [distribuidos ](https://www.rae.es/dpd/distribuir)
- [x] ¶2  Usualmente, se muestran las dos primeras dimensiones al mismo tiempo, aunque es posible mostrar tres dimensiones en una visualización en 3D -> Usualmente, se crean gráficos con las dos primeras dimensiones aunque es posible mostrar tres con visualizaciones en 3D | para evitar cacofonía en la repetición de "dimensiones" y "en"
- [x] ¶3 Debido a que el análisis de correspondencia visualiza relaciones entre elementos de los datos como distancias en un gráfico, es posible descubrir patrones basados en qué elementos de una categoría aparecen cerca de elementos de otra -> En el AC, las relaciones entre los elementos se visualizan como distancias en un gráfico. Gracias a esto es posible descubrir patrones de relación/vínculo basados en qué elementos de una categoría aparecen cercanos a los elementos de otra. | siento que estas frases largas y subordinadas se dejan leer mejor separándolas
- [x] ¶6 El tutorial de Taryn Dewar sobre Datos tabulares en R ofrece información sobre cómo instalar y configurar R. El tutorial de Taylor Arnold y Lauren Tilton Procesamiento básico de textos en R también puede servir como preparación. -> Como preparación, se pueden revisar los siguientes tutoriales: el de Taryn Dewar sobre Datos tabulares en R, el cual ofrece información sobre cómo instalar y configurar R; el de Taylor Arnold y Lauren Tilton que da una introducción al Procesamiento básico de textos en R; y por último, como el análisis de correspondencia es un tipo de análisis de redes sociales, vale la pena darle una mirada al tutorial de Marte Düring: De la hermenéutica a las redes de datos: Extracción de datos y visualización de redes en fuentes históricas que también contiene información útil sobre cómo estructurar datos para el análisis de redes. . | me parece que puede ser buena guía para quien lee que se introduzca la idea de que a continuación verá tres tutoriales distintos que le pueden servir de preparación
- [x] ¶10 (TLCAN & EEE) -> (AECG y EEE) | creo [según la imagen ](https://raw.githubusercontent.com/programminghistorian/ph-submissions/gh-pages/images/analisis-de-correspondencia-en-r/figura1.png)
- [x] ¶13 un/a historiador/a | había leído que para los lectores de pantalla, es más amable hacer uso de los dobletes (historiadores e historiadoras)
- [x] ¶13  [^tratado] | no me queda muy clara la función de esto (ver también ¶36 [^explanatory])
- [x] ¶15 los ciudadanos -> la ciudadanía | para seguir con alternativas de lenguaje incluyente
- [x] ¶16 son un largos -> son muy largos
- [x] (tabla) en francés, Agri-food es [Agroalimentaire](https://www.agr.gc.ca/fra/agriculture-et-agroalimentaire-canada/?id=1395690825741) por lo que creo que se podría traducir como agroalimentario en lugar de agri-comida?
- [ ]  ¶17 Como historiador, mi sospecha es que los MP | ¿se mantiene el uso de la primera persona en la traducción?
- [x]  ¶17 para para proteger -> para proteger
- [x] ¶18 que pueda realizar álgebra lineal por nosotros -> que nos pueda hacer álgebra lineal | así se mantiene el leng. incluyente
- [x] ¶18 se incluye un apéndice | añadiría el vínculo a la sección
- [x] ¶19 Pero primero, así es como se instalan y llaman los paquetes de R, y cómo luego los datos se asignan a un objeto de R para trabajar sobre ellos. -> cómo se instalan* [...] para trabajar sobre ellos: 
- [x] (bloque de código- post ¶19) ¿se tendrá que corregir la URL o ahí vivirá el archivo una vez que se publique la lección?, en todo caso creo que la liga tendrá que empezar con "raw" ([ejemplo](https://raw.githubusercontent.com/programminghistorian/ph-submissions/gh-pages/assets/analisis-de-correspondencia-en-r/HarperCP-es.csv)), ¿no? + creo que el nombre de la última columna debería ser 'abreviatura' y no 'abreviación'
- [x] (bloque de código - post ¶22) se muestra una tabla que no se ha generado aún, creo que valdría la pena mostrar cómo se llega a ella, en la lección original se llama al objeto "harper_df" como si ese contuviera esa tabla, pero según lo hecho en el bloque de código anterior, ese objeto contiene la lectura del csv sin ningún otro procesamiento
- [x] ¶23 (el comité parlamentario de salud) -> sugiero altas para mantener consistencia
- [x]  ¶24 es la primera vez que aparece dataframe, tal vez conviene añadir nota al pie si no se va a traducir? Y ser consistente con la forma de llamarlo (ver ¶25 en el que aparece como _data frame_)
- [x] ¶27 La función CA (de la iniciales en inglés de correspondence analysis, es decir, análisis de correspondencia) -> La función CA ( análisis de correspondencia, por las siglas en inglés de Correspondence Analysis) 
- [x] (bloque de código - post ¶33)  fviz_ca_biplot(AC_harper, repel = TRUE) -> fviz_ca_biplot(AC_harper, repel = TRUE, title = "Mapa de factores AC - Harper") | para ser consistentes con el cambio de títulos a español
- [x] ¶37  "Lo puntos con mayor inercia" -> Los puntos
- [x]  ¶40 / ¶47 chi cuadrado -> chi cuadrada | aparece tres veces en total
- [x]  ¶41 Como ya discutió -> como ya se discutió 
- [x] ¶43 un moción -> una moción
- [x]  (bloque de código - post ¶44) si se sigue la recomendación de cambiar la variable  'abreviación' por 'abreviatura' habría que cambiar los siguientes pedazos del código:

```
harper_df2 <- harper_df[which(harper_df$abreviacion %in% c("SLUD", "JUST", "SMUJ", "INDN", "FINA", "EXTR", "VCMI")),]
harper_tabla2 <- table(harper_df2$abreviacion, harper_df2$miembro)

```
(bloque de código - post ¶49)

```
trudeau_df2 <- trudeau_df[which(trudeau_df$abreviacion %in% c("SLUD", "JUST", "SMUJ", "INDN", "FINA", "EXTR", "EQUI")),]
trudeau_tabla2 <- table(trudeau_df2$abreviacion, trudeau_df2$miembro)
```

- [x] ¶56 intepretativa -> interpretativa
- [x] ¶56 pudemos -> podemos
- [x] ¶59 an la planificación -> en* la planificación
- [x] ¶67 _FEWO (Status of Women), HESA (Health), INAN (Indigenous and Northern Affairs), IWFA (Violence Against Indigenous Women) y JUST (Justice)._ Creo que deberían usarse las siglas traducidas que se usaron en el tutorial, ej. FEWO -> SMUJ
- [x] ¶68  FEWO y S Ambler -> ver comentario anterior 
- [x] ¶70 a tener puntajes normalizados más bajo. -> más bajos*
- [x] ¶70/75 IWFA -> VCMI

**Comment by rivaquiroga** [comment]
¡Muchas gracias, @silviaegt! 
Respecto de las sugerencias sobre el contenido de la lección, si son pequeñas aclaraciones, como algunas de las frases explicativas que sugieres agregar, no creo que sea problema incorporarlas. Miraremos eso con detalle, en caso de que alguna sugerencia vaya más allá de lo que es posible hacer en una traducción. 
¡Gracias!

**Comment by rivaquiroga** [comment]
¡Hola, @jamotilla! Retomamos esta traducción después de tenerla abandonada un tiempo. Ya incorporamos los cambios sugeridos por Silvia. 

### Observaciones sobre el contenido
Solo consideramos los que podían resolverse con una frase explicativa o nota al pie breve. Los que apuntan a aspectos de cómo el autor interpreta los datos y propone conclusiones, quedan fuera del ámbito que cubre una traducción. En ese caso lo que correspondería sería que alguien abriera un _issue_ planteando esos cuestionamientos para que el autor los resuelva. Y solo entonces actualizar la traducción si es que hace modificaciones en el original.

A propósito de este comentario:
> ¶58 a mí me parece más claro [esta entrada](https://www.displayr.com/singular-value-decomposition-in-r/) sobre SVD y tiene la ventaja de que está conectado con su programación en R y con este [otro post sobre las matemáticas del AC](https://www.displayr.com/math-correspondence-analysis/) y aún más con esta [serie de videos](https://www.youtube.com/watch?v=gXbThCXjZFM&list=PLMrJAkhIeNNRpsRhXTMt8uJdIGz9-X_1-&index=1)

Agregamos los enlaces como nota al pie para complementar los propuestos por el autor.

### Observaciones sobre la redacción

No incorporamos esta sugerencia:

>  ¶17 Como historiador, mi sospecha es que los MP | ¿se mantiene el uso de la primera persona en la traducción?

En general hemos mantenido la voz de quienes escribieron la lección en las traducciones. En este caso en particular, como propondrá una explicación hipotética, pareciera que es mejor mantener la primera persona y no impersonalizar.

**Comment by jenniferisasi** [comment]
@jamotilla ahora tenemos un topic para R, por favor, incluye "r" en la sección de topics de los metadatos de la lección. Gracias.

**Comment by anisa-hawes** [comment]
Hello all, 

Please note that this lesson's .md file has been moved to a new location within our Submissions Repository. It is now found here: [https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/)

A consequence is that this lesson's preview link has changed. It is now: [http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/analisis-de-correspondencia-en-r](http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/analisis-de-correspondencia-en-r)

Please let me know if you encounter any difficulties or have any questions.

Very best,
Anisa

**Comment by jamotilla** [comment]
Hola @rivaquiroga revisé la lección y creo que ya estamos listos para publicarla.

**Comment by rivaquiroga** [comment]
Perfecto. Iniciaré el proceso de publicación. Muchas gracias :tada:

**Comment by anisa-hawes** [comment]
Dear @rivaquiroga, 

Would you like me to contribute by typesetting this lesson (checking Markdown layout and structure) and generating perma.cc hyperlinks?

Very best,
Anisa

**Comment by rivaquiroga** [comment]
Yes, that would be great. Thank you!

**Comment by rivaquiroga** [comment]
@anisa-hawes, BTW, [the PT team is also translating this lesson](https://github.com/programminghistorian/ph-submissions/issues/422), so the perma.cc hyperlinks will be useful there too. We kept all the links from the original EN version  and we added a couple more. Let me know when you are done, so I can start the publication process. Thank you!

**Comment by anisa-hawes** [comment]
Dear Riva, Apologies for the delay. 

- [x]  I've added in the toc
- [x]  I've adjusted the relative link to assets, §63
- [x]  I've integrated perma.cc links throughout, except relative links, dois and YouTube*, §483. 

*Unfortunately, perma.cc cannot capture video. _When I am not working with PH, I am a web archivist and I use [Webrecorder](https://archiveweb.page/) which can very successfully capture video, but we would need to set up a system so that we can serve the files (`.warc` or `.wacz`). This something we can think about for the future! Happy to chat more about this._

- [ ] I've adjusted the `{% include figure.html ...` code, so that =filename precedes =caption. The images are still not showing up in the Preview though.... I need to take another look at this, I am not certain what the problem is.... The build is successful (green tick) but the images do not display.

- [x]  I noticed that the Figure captions do not include numbers. Looking at some recently published ES lessons, I can see that numbers are sometimes included and sometimes not. Let me know if you'd like me to integrate these?

- [x] I also noticed that in the "## Notas finales" §467 "[^factoextra]: Alboukadel Kassambara and Fabian Mundt (2017). factoextra: Extract and Visualize the Results of Multivariate Data Analyses. R package version 1.0.4. <https://CRAN.R-project.org/package=factoextra>." is not shown in the preview, because the key "[^factoextra]" does not appear in the text. Is this a mistake, or a choice? 

Very best,
Anisa

**Comment by rivaquiroga** [comment]
Thanks, @anisa-hawes. Don't worry about images. They'll show up once we move everything to Jekyll. Regarding numbers in figures caption, they were not included in the original EN version. So we kept it that way. 
I'll check the factoextra note. But if the key is not in the text, the same might be happening in the original version. I'll take a look.

**Comment by anisa-hawes** [comment]
Thank you for fixing the [^factoextra] end note @rivaquiroga! I'll update `/en/lessons/correspondence-analysis-in-R` as it seems this was missed at the time the original was published. 

You're right about the original version not including figure numbers in the image captions. I think it makes sense to leave it as is, because the text doesn't reference the figures by their numbers. 

This also reminds me of [Issue #2360](https://github.com/programminghistorian/jekyll/issues/2360) that you opened in Jekyll to agree a naming convention for translated lesson images. I really appreciate the clear way José Antonio @jamotilla has named images here, e.g., `analisis-de-correspondencia-en-r1.png`.

**Comment by rivaquiroga** [comment]
La lección ya está publicada en https://doi.org/10.46430/phes0058, así que podemos cerrar este ticket. ¡Muchas gracias a todas las personas que participaron en el proceso! :tada:
