### ISSUE TITLE
Mac Catalina bug for "Building a static website with Jekyll and GitHub Pages"

### ISSUE THREAD

**Issue by quinnanya** [programminghistorian/ph-submissions#332]
I love the "Building a static website with Jekyll and GitHub Pages" tutorial and have it bookmarked in my toolbar for easy reference! Today I tried to follow the instructions on a new laptop running Catalina, and ran into permissions problems that couldn't be solved with any of the tips. What worked for me was, after `brew install ruby`, running `export GEM_HOME="$HOME/.gem"`. Thought I'd pass it along as an update suggestion!

**Comment by walshbr** [comment]
Thanks, @quinnanya! would you mind posting this over on our other repository? https://github.com/programminghistorian/jekyll/issues?q=is%3Aopen. This one is only really meant for the peer review pipeline, and it's liable to get left unnoticed over here. The other repository is where we have bug tracking and the like.

**Comment by quinnanya** [comment]
Oops, sorry! Thanks for the pointer to the other repo. Will go post over there!

**Comment by acrymble** [comment]
No good deed goes unpunished :) Thanks for contributing extra information.

**Comment by walshbr** [comment]
Thanks for posting! Just wanted to make sure you were still tied to the issue in case we had follow-up questions. Would otherwise post it myself.
