### ISSUE TITLE
Proposition de traduction: Detecting Text Reuse with Passim

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#334]
Le Programming Historian en français a reçu une proposition de traduction de la leçon "Detecting Text Reuse with Passim" (actuellement en phase finale d'évaluation cf. #305) de la part de ses auteurs @faustusdotbe et @mromanello. 

Nous prévoyons un délai de 90 jours à partir de la finalisation de la leçon pour préparer sa traduction, délai qui peut être réajusté sur demande des traducteurs. Si la traduction n'est pas soumise d'ici là, je recontacterai les traducteurs. Si aucune mise à jour ne survient, ce ticket sera fermé, il peut néanmoins être réouvert dans l'avenir sur demande des traducteurs. 

J'assure le suivi de cette proposition. Si, pour quelque raison que ce soit, les traducteurs ont le sentiment qu'une médiation est nécessaire, notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu) reste à disposition.

**Comment by drvenabili** [comment]
Bonjour @spapastamkou ,

Malgré que la leçon originale en anglais soit finalisée, je suis malheureusement officiellement (fort) en retard avec cette traduction, sans vraie solution pour les prochaines semaines. Cela reste un projet que je veux (et vais) faire, mais pas tout de suite. 

(cc @mromanello , FYI)

**Comment by spapastamkou** [comment]
@faustusdotbe Merci beaucoup de me tenir informée. Il n'y a aucun inconvénient bien sûr, j'aimerais seulement vous demander si vous pensez pouvoir estimer un délai (pour garder ce ticket ouvert) ou si, en revanche, vous préférez que nous le fermions temporairement et le rouvrir lorsque vous serez prêts.

**Comment by drvenabili** [comment]
Pour être honnête je ne me vois pas pouvoir le faire avant la mi-juin.

**Comment by spapastamkou** [comment]
Merci @faustusdotbe. Nous allons dans ce cas laisser ce ticket ouvert, et je vais vous faire un rappel en juin: si vous en avez la possibilité d'aller plus loin en ce moment-là, nous continuerons ici, si ce n'est pas le cas nous fermerons le ticket pour le rouvrir lorsque vous serez prêt de votre côté. Cela vous convient-il?

**Comment by drvenabili** [comment]
> Cela vous convient-il?
 
Parfait !

J'ai pushé ce que j'ai déjà traduit (pas grand chose..) sur notre fork (https://github.com/mromanello/ph-submissions/blob/gh-pages/fr/traductions/D%C3%A9tecter-la-r%C3%A9utilisation-de-texte-avec-Passim.md). @mromanello a un/une étudiant/étudiante de langue française qui pourrait reprendre ce travail (avec supervision de notre part évidemment), nous vous tenons donc au courant.

**Comment by spapastamkou** [comment]
Merci, c'est noté, nous en reparlons sans faute!

**Comment by mromanello** [comment]
Bonjour @spapastamkou,

Juste pour vous dire que Madame Carla Amaya (@camaya28) (qui travaille avec moi comme assistante étudiante ce semestre) vient d'ouvrir une Pull Request (#369 👆) avec une première traduction française de la leçon. Au même temps, la version anglaise a été aussi finalisé (voir #367) et est en attente d'être validée.

(cc @faustusdotbe)

**Comment by spapastamkou** [comment]
Merci beaucoup! J'attends que le fichier soit renommé et après on pourra intégrer le dépôt.

**Comment by mromanello** [comment]
Bonjour @spapastamkou 

> Merci beaucoup! J'attends que le fichier soit renommé et après on pourra intégrer le dépôt.

Je voulais juste confirmer que le fichier à été renommé par @camaya28 dans la PR #369.

**Comment by datalogism** [comment]
Bonjour @mromanello, 
j'aurai besoin d'un retour de la part de @camaya28  sur le ticket #372 , afin de pouvoir lancer la procédure de relecture.
