### ISSUE TITLE
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/manipulando-arquivos-texto.md

### ISSUE THREAD

**Issue by rsouza** [programminghistorian/ph-submissions#347]
I have revised the lesson and didn' t find anything worth changing. Congrats for all the work!

**Comment by DanielAlvesLABDH** [comment]
Caro @rsouza obrigado pela análise. Peço só que coloque o seu comentário nesta issue de revisão: https://github.com/programminghistorian/ph-submissions/issues/317 A #347 pode ser apagada @daniellesanchesDH

**Comment by daniellesanchesDH** [comment]
@rsouza muito obrigada!
