### ISSUE TITLE
Review Ticker for 'Introducción a Python e instalación' - Spanish translation

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#35]
I am not sure this is the right place to put all this. However, here we go. I just read two lessons today and I took the following notes: 

1) Introducción a Python  e instalación
1. [x] El lenguaje de programación Python. —> El lenguaje de programación Python [without full stop]
2. [x] Paso 1.- Instalar el software. —> Paso 1.- Instalar el software [without full stop]
3. [x] Programming Historian —> cursiva
4. [x] software —> cursiva
5. [x] Para entender páginas Web y HTML —> Falta link a la página 

2) Instalación en Mac
1. [x] Haz respaldo (copia de seguridad) de toda tu computadora. —> Haz respaldo (copia de seguridad) de toda tu computadora [without full stop]
2. [x] mantenlo  —> manténlo
3. [x] software —> cursiva
4. [x] shell —> cursiva 

They are not suggested changes concerning language but typograhy and italics, but of course you can ignore them.

There is also a funny effect with accents when showing commands but I am not sure if this is a visualization problem or it's ok -- sorry for asking.

I'll keep reading tomorrow probably.

**Comment by acrymble** [comment]
perfect place to put it! The question really is who is in 'charge' of the process. Not to be bossy but to make sure everything goes smoothly. Normally if @vgayolrs was the author/translator, we'd ask someone else to act as the editor. I can do that for one lesson to show you what the experience is like, if you want me to (I don't want to get in the way, but I know this is all new for everyone!).

**Comment by arojascastro** [comment]
I think it's a great idea. Maybe @mariajoafana can join us here and add her suggestions in the same issue?

**Comment by acrymble** [comment]
Ok, let's keep to one ticket per file. That way we have a clear record of which files are done and what was said about each. I'll try the new template I posted to see how it works. We will call this a trial of the workflow.

**Comment by arojascastro** [comment]
Thank you @acrymble ! One ticket per lesson, I will stick to this. How should I reference the canges: using the line or as a check list? In your experience what is easier for the author/translator?

**Comment by acrymble** [comment]
The Programming Historian has received the following translation on 'Introducción a Python e instalación' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/introduccion-e-instalacion

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti  - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by acrymble** [comment]
@arojascastro has already put his review above. @mariajoafana did you want to add anything?

(In future I'll suggest we use line numbers, but these are small changes here so let's not worry this time).

**Comment by vgayolrs** [comment]
Love the process. Just, please, notice that the lesson files are in /Jekyll and this ticket was open in /ph-submissions, so when I attended the recommendations of @arojascastro (thank you) I could not refer the commit changes with this ticket number to be reflected here. Any thoughts?

**Comment by mariajoafana** [comment]
Yes. I'll leave my comments/suggestions for  for the "Introducción a Python e instalación" and "Instalación Mac" here:

Intro. Python:
Línea 33: revisar "hacerlo lo más frecuente". Debe ser "con más frecuencia". Cambiar "pues, en el caso..." por para que en caso...". 

Instalación Mac:
Línea 29: cambiar "todos tus programas..." por "todos los programas..."

**Comment by vgayolrs** [comment]
Thank you @mariajoafana . Done.

**Comment by acrymble** [comment]
Yea @vgayolrs you'll just have to do your best and let us know when it's done. We'll make a note of any problems with this workflow and adjust in future.

**Comment by vgayolrs** [comment]
@acrymble @mariajoafana @arojascastro : thank you very much to all. Every correction has been attended.

**Comment by acrymble** [comment]
Ok I've added you both as translation reviewers. This is now finished.

**Comment by mariajoafana** [comment]
;) 
Thanks @acrymble for your the support today and @arojascastro and @vgayolrs for the hard work. 
I'll keep revising the Python lessons between tonight and tomorrow.
