### ISSUE TITLE
Ticket de revisión: "Introducción a la codificación de textos en TEI"

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/ph-submissions#351]
Programming Historian en español ha recibido la siguiente propuesta de lección: "Introducción a la codificación de textos en TEI" por parte de Nicolás Vaughan (@nivaca). La editora de esta lección será @jenniferisasi. Esta lección se encuentra en estos momentos en fase de revisión y puede leerse en:

**Vista previa**
http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei-1
http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei-2

Original: http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei

**Archivo**

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-a-tei-1.md
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-a-tei-2.md

**Imágenes**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/introduccion-a-tei

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra *ombudperson*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by rivaquiroga** [comment]
@jenniferisasi, esta es la lección que necesitamos dividir porque excede con creces el número máximo de palabras. Y porque al ser demasiado larga puede ser difícil de seguir.
También te quería pedir ayuda con el _build_, porque hay algo que lo está haciendo fallar.  No pareciera ser algo en el encabezado (aunque puede que sea algo demasiado evidente, pero que a estas alturas del día simplemente no veo)

**Comment by jenniferisasi** [comment]
¡Recibido! La apunto para leer y ver dónde sería un buen lugar para "cortarla" en dos con su correspondiente aviso. 

Qué extraño el _build_...pero creo que sí, puede ser algo del encabezado o que como hemos cambiado el sistema de build algo haya cambiado. Voy a tratar de ver si lo arreglo.

**Comment by jenniferisasi** [comment]
@rivaquiroga lo intenté pero no veía nada mal... le pedí ayuda a Zoe y ella dio con el error (¡menudo ojo tiene!): 

It looks like Riva included html tags in the figure captions but markdownify read those as actual tags. My workaround was to enclose them in ticks and that seems to work...

**Comment by rivaquiroga** [comment]
¡Genia! :gem: Toda la razón

**Comment by jenniferisasi** [comment]
Hola @nivaca, he leído con gran interés tu lección y va a ser de gran utilidad a nuestra comunidad HD. Puesto que la longitud del texto excede al doble de las palabras máximas que consideramos adecuadas para un tutorial, consideramos que es necesario partir la lección en dos. Además, habrá que reorganizar un poquito la primera parte, para dar mayor peso a TEI desde el principio.

Nuestras sugerencias son 

- [x] crear una primera lección, digamos, teórica, y luego una más práctica con los ejemplos. Se podría hacer el corte, por ejemplo, después de la sección "¿Qué es TEI, al fin y al cabo?"; ahora bien, esa sección debería ir más arriba en la lección. 
- [x] Te pedimos también que reduzcas la sección sobre el software, ya que valdría con enfocarse en VSCode y nombrar las otras posibilidades. Esta sección sobre el software podría ir casi al final de la primera parte, aunque habría que ver cómo queda una vez reorganizada esa parte. 
- [ ] Puesto que cada vez más la edición de TEI se usa con fines de publicación digital online, sugerimos que la extracción final sea a HTML en vez de PDF, o al menos hacer una mención a la posibilidad y algún ejemplo. 
- [ ] Falta algún tipo de conclusión en la lección. 
- [x] Por descontado, al final de la primera lección habrá que añadir un mensaje que indique que ahora se podrá poner en práctica lo aprendido, y al comienzo de la segunda añadir que para completarla es recomendable haber leído la primera lección. 
- [ ] En las referencias faltan recursos para la audiencia principal de la lección, que va a ser hispanohablante y no podemos asumir conocimientos de inglés. Sugerimos incluir en la bibliografía y, si es adecuado, en algún punto dentro del texto el proyecto [_Text Technologies Hub. Recursos sobre tecnologías del texto y edición digital_](https://tthub.io) de Susanna Allés Torrent, Gimena del Rio Riande y Gabriel Calarco. 

Quedamos a la espera de saber qué te parece la sugerencia y si podrías hacerlo. Nos gustaría mucho tener estas lecciones en _Programming Historian_ así que quedamos pendientes a cualquier pregunta que pueda surgir en el proceso y, por supuesto, si lo que he puesto no ha quedado lo suficientemente claro. 

¡Gracias!

**Comment by nivaca** [comment]
Gracias, @jenniferisasi. Me pondré a trabajar en esto. Saludos.

**Comment by nivaca** [comment]
Ya hice las correcciones y las subí al repositorio. Son ahora dos archivos (`introduccion-a-tei-1.md` y `introduccion-a-tei-1.md`).

**Comment by jenniferisasi** [comment]
Gracias @nivaca por editar tu lección. Voy a leerlas de nuevo para comprobar cómo quedaron y a la vez me pongo a buscar ya revisores. 

Aprovecho para preguntar a la jefa de redacción. @rivaquiroga, primera vez que esto nos ocurre, hacemos dos tickets y 4 revisores? O dos tickets y 2 revisores? ¿Cómo te parece que funcione mejor, sobre todo para ti a la hora de migrar la lección al otro repo?

**Comment by rivaquiroga** [comment]
Buena pregunta. Creo que sería mejor tener dos tickets y desarrollar el proceso editorial de manera secuencial, no paralela. Es decir, hacer la revisión de la primera parte y cuando ese tutorial esté listo (o al menos haya pasado por una revisión inicial), partimos con el segundo, para poder tener en cuenta la retroalimentación de esa primera parte y asegurar consistencia. Sería ideal si pudiéramos mantener a los mismos revisores, pero no creo que sea problema si cambian en caso de que trabajemos de manera secuencial.

**Comment by jenniferisasi** [comment]
Voy a cerrar el ticket para dar inicio a la revisión de la primera parte.
