### ISSUE TITLE
Tradução da lição "Introdução ao Markdown"

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#353]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Introdução ao Markdown' por **@0jonjo**. A lição a traduzir está no link [(https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/introducao-ao-markdown.md)].

Para promover uma publicação rápida desta lição traduzida, eu **@joanacvp** irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Bem-vindo João Gilberto (@0jonjo)! Qualquer dúvida ou ajuda necessária, não hesite em perguntar. Muito obrigado pela sua contribuição para o Programming Historian em português! Obrigado também @joanacvp por editar esta tradução! Abraço

**Comment by 0jonjo** [comment]
Olá, fiz uma primeira versão da tradução da lição. Faço um pull request que substitua o que está atualmente no diretório? Ou faço upload dela com outro título para termos a versão inglês e a em português juntas para compararmos?
