### ISSUE TITLE
Tradução da lição "Criar novas camadas vetoriais no QGIS 2.0"

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#358]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Criar novas camadas vetoriais no QGIS 2.0' por @rafaellaguardia1. A lição a traduzir está no link [(https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/camadas-vetoriais-qgis.md)].

Para promover uma publicação rápida desta lição traduzida, eu @joanacvp irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Bem-vindo Rafael (@rafaellaguardia1)! Qualquer dúvida ou ajuda necessária, não hesite em perguntar. Muito obrigado pela sua contribuição para o Programming Historian em português! Obrigado também @joanacvp por editar mais esta tradução! Estamos em movimento ;-) Abraço
