### ISSUE TITLE
Revisão da Tradução da lição "Downloading Web Pages with Python"

### ISSUE THREAD

**Issue by josircg** [programminghistorian/ph-submissions#360]
Programming Historian em Português recebeu a proposta de tradução da página:

https://programminghistorian.org/en/lessons/working-with-web-pages

Prévia:

http://programminghistorian.github.io/ph-submissions/lessons/portuguese/propostas/download-de-paginas-web-com-python

A tradução ficou muito boa @bruno-ponne !

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/download-de-paginas-web-com-python.md

Vou fazer pequenas alterações e te informo

**Comment by bruno-ponne** [comment]
Obrigado pela atualização.
Fico à disposição para demais ajustes na tradução.

**Comment by josircg** [comment]
https://github.com/programminghistorian/ph-submissions/commit/f336b0be70e35d729e911213b2666f34e034b297

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg, você está como editor desta tradução. Para seguir as directrizes (https://programminghistorian.org/pt/directrizes-editor) você deve solicitar a revisão da tradução a dois colegas e ir acompanhando e documentando todo o processo neste ticket. Depois, as revisões serão implementadas pelo @bruno-ponne. No final você faz uma revisão e eu também. É importante seguirmos as directrizes. Abraço

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg , como está este processo? Já temos revisores? Precisamos avançar com estas lições de Python, pois temos outras em tradução que têm links para estas e era bom concluir. Se for necessário alguma ajuda, é só dizer!

**Comment by josircg** [comment]
Não encontrei nenhum revisor. Procurei na comunidade Python, entre nós aqui mas ninguém se prontificou para fazer a revisão.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @josircg. Olá @JimmyMedeiros82, @luisferla e @daniellesanchesDH, será que vocês conhecem algum colega que possa dar uma ajuda aqui? Eu e a @joanacvp podemos procurar do lado de Portugal... Abraço

**Comment by JimmyMedeiros82** [comment]
Olá @DanielAlvesLABDH  e @josircg , sugiro um colega que está colaborando conosco já no esforço de tradução de novas lições. 
O Felipe Lamarca tem um bom conhecimento em python e está disponível para fazer a revisão. 

O perfil dele é felipelmc. Convidamos ele?

**Comment by DanielAlvesLABDH** [comment]
Obrigado @JimmyMedeiros82! @josircg você avança com esse convite? Eu posso fazer a revisão do lado pt-pt.

**Comment by josircg** [comment]
Sem problemas. @JimmyMedeiros82 vc poderia me passar o email dele? Pelo github eu não tenho como fazer contato se ele não estiver me seguindo.

**Comment by JimmyMedeiros82** [comment]
@josircg o contato do Felipe Lamarca é felipe.lamarca@hotmail.com

**Comment by felipelmc** [comment]
Olá @bruno-ponne! Agradeço de antemão pela excelente tradução. Participo da equipe de tradução do The Programming Historian para o português e deixo aqui algumas sugestões de modificação. A maioria vai na linha de manter um padrão de tradução que seja o mais próximo daquilo que é comum entre o português brasileiro e o português de Portugal:

- [x] Linha 42: substituir "é um arquivo" por "é um ficheiro";
- [x] Linha 42: substituir "nome do arquivo" por "nome do ficheiro";
- [x] Linha 42: substituir "em outro computador" por "noutro computador" (esse tipo de contração é muito comum no português de Portugal);
- [x] Linha 54: substituir "em um determinado" por "num determinado";
- [x] Linha 62: substituir "em um determinado" por "num determinado";
- [x] Linha 74: a palavra "representa" saiu com um erro ("reresenta");
- [x] Linha 74: faltou adicionar o link da lição "Downloading Multiple Records Using Query Strings";
- [x] Linha 78: substituir "os conteúdos em um arquivo de texto" por "os conteúdos num ficheiro de texto";
- [x] Linha 78: substituir "você poderia abrir" por "seria possível abrir";
- [x] Linha 78: substituir "você pode utilizar" por "é possível utilizar";
- [x] Linha 80: substituir "tipo de arquivo" por "tipo de ficheiro";
- [x] Linha 90: substituir "um arquivo HTML" por "um ficheiro HTML";
- [x] Linha 90: a palavra "encaminhará" saiu com um erro ("ecaminhará");
- [x] Linha 90: substituir "salve o arquivo como" por "salve o ficheiro como";
- [x] Linha 96: substituir "Quando você executar" por "quando executar";
- [x] Linha 96: substituir "em uma string" por "numa string";
- [x] Linha 117: substituir "em uma variável" por "numa variável";
- [x] Linha 119: substituir "em uma variável" por "numa variável";
- [x] Linha 137: substituir "a um arquivo" por "a um ficheiro"; 
- [x] Linha 137: substituir "em um arquivo" por "num ficheiro";
- [x] Linha 137: há um espaço a mais entre a palavra "Firefox" e a vírgula;
- [x] Linha 137: substituir "abra o arquivo" por "abra o ficheiro";
- [x] Linha 154: substituir "salvar um único arquivo" por "salvar um único ficheiro";
- [x] Linha 154: substituir "um conjunto de arquivos" por "um conjunto de ficheiros";
- [x] Linha 164: substituir "tenha os arquivos" por "tenha os ficheiros";
- [x] Linha 164: substituir "baixar o arquivo zip" por "baixar o ficheiro zip".

Costumamos sugerir que o tradutor, sempre que possível, opte por um discurso mais impessoal usando o infinitivo e evitando a utilização do “tu” ou do “você”. Ex.: optar por “Se não encontrar…” em vez de “Se você não encontrar…” ou “Se não encontrares…”. Nesse caso, como o "você" aparece algumas vezes, sugeri algumas substituições e deixo as outras a seu critério. Faça as modificações que achar convenientes. 

Mais uma vez agradeço a contribuição e parabenizo pela tradução, que está muito boa! Qualquer dúvida é só perguntar.

**Comment by DanielAlvesLABDH** [comment]
Caro @felipelmc, muito obrigado pela revisão. Sugiro apenas uma alteração. Na adequação entre as duas versões do português, temos optado por "ficheiro" em vez de "arquivo". Abraço

**Comment by felipelmc** [comment]
Obrigado pela lembrança, @DanielAlvesLABDH! Havia me esquecido deste detalhe. Acabei de editar a revisão para apontar também esses casos. Abraços!

**Comment by bruno-ponne** [comment]
Olá @felipelmc e @DanielAlvesLABDH. Muito obrigado pelas valiosas recomendações, vou ajustar o texto nos próximos dias e entro em contato caso haja dúvidas. Fico à disposição. Abraço! : )

**Comment by felipelmc** [comment]
Olá @bruno-ponne, tudo bem? Conversei com o @josircg há pouco porque percebi uma questão dessa lição e queria sugerir mais uma pequena alteração: no caso do bloco de lições ao qual essa lição pertence, os autores da lição original em inglês mantêm um arquivo zip com os arquivos necessários ao leitor. Portanto, sugiro que você retorne o nome dos arquivos de "salvar-webpage.py" e "abrir-webpage.py" para "save-webpage.py" e "open-webpage.py", que é como esses arquivos aparecem no zip. Assim fica viável manter o link do zip da lição original. Abraços!

**Comment by bruno-ponne** [comment]
oi Felipe! Obrigado por mais essa sugestão. Vou implementá-la.

**Comment by bruno-ponne** [comment]
@felipelmc, eu estou ajustando o texto. Fiz todas as alterações que você sugeriu acima e alterei as seguintes passagens. Gostaria da sua opinião. Caso tenha mais sugestões, serão bem-vindas.

- [ ] linha 54: substituir "esse URL" por "essa URL";
- [ ] linha 62: substituir "Como você deve saber, geralmente há muitas páginas" por "Geralmente há muitas páginas";
- [ ] linha 62: substituir "e você pode especificar" por "e é possível especificar";
- [ ] linha 62: substituir "Geralmente há muitas páginas *Web* num determinado *site*" por "Geralmente há diversas páginas *Web* num determinado *site*."
- [ ] linha 74: substituir "Você pode aprender mais" por "Aprenda mais";
- [ ] linha 80: substituir "Suponhamos que você esteja interessado" por "Suponhamos que haja interesse":
- [ ] linha 90: substituir "Caso você troque as duas ocorrências de `33` por `34` no link acima" por "Caso as duas ocorrências de `33`  sejam trocadas por `34` no link acima";
- [ ] linha 111: substituir "e que você consegue" por "e que é possível";
- [ ] linha 121: substituir "Assegure-se de que você consegue" por "Assegure-se de ser capaz de";
- [ ] linha 123: substituir "você perceberá alguns marcadores da linguagem HTML" por "alguns marcadores da linguagem HTML poderão ser identificados";
- [ ] linha 133: substituir "você vai aprender em breve a eliminar o excesso" por "aprenderemos em breve a eliminar o excesso";
- [ ] linha 137: substituir "Considerando o que você já sabe sobre" por "Considerando o que foi visto sobre";
- [ ] linha 154: substituir "que recomendamos depois que você tenha terminado as lições" por "que recomendamos depois que tenha terminado as lições";
- [ ] linha 164: substituir "é importante que você tenha" por "é importante ter";
- [ ] linha 164: substituir "para ter certeza que você está utilizando o código correto" por "para ter certeza de que o ficheiro correto está sendo utilizado";

Obrigado pela revisão e vamos nos falando. Abraço!

**Comment by felipelmc** [comment]
Ótimo, @bruno-ponne! Gostei das suas sugestões. Falta somente alterar o abrir-webpage.py e o salvar-webpage.py na parte da documentação do código. Vi que fez as alterações no corpo do texto, mas faltou na hashtag que comenta o código do Python. Após esse pequeno ajuste, acredito que não haverá mais sugestões de alteração da minha parte. Para facilitar:

- [x] Linha 99: trocar `abrir-webpage.py` por `open-webpage.py`
- [x] Linha 140: trocar `salvar-webpage.py` por `save-webpage.py`

> @felipelmc, eu estou ajustando o texto. Fiz todas as alterações que você sugeriu acima e alterei as seguintes passagens. Gostaria da sua opinião. Caso tenha mais sugestões, serão bem-vindas.
> 
> * [x]  linha 54: substituir "esse URL" por "essa URL";
> * [x]  linha 62: substituir "Como você deve saber, geralmente há muitas páginas" por "Geralmente há muitas páginas";
> * [x]  linha 62: substituir "e você pode especificar" por "e é possível especificar";
> * [x]  linha 62: substituir "Geralmente há muitas páginas _Web_ num determinado _site_" por "Geralmente há diversas páginas _Web_ num determinado _site_."
> * [x]  linha 74: substituir "Você pode aprender mais" por "Aprenda mais";
> * [x]  linha 80: substituir "Suponhamos que você esteja interessado" por "Suponhamos que haja interesse":
> * [x]  linha 90: substituir "Caso você troque as duas ocorrências de `33` por `34` no link acima" por "Caso as duas ocorrências de `33`  sejam trocadas por `34` no link acima";
> * [x]  linha 111: substituir "e que você consegue" por "e que é possível";
> * [x]  linha 121: substituir "Assegure-se de que você consegue" por "Assegure-se de ser capaz de";
> * [x]  linha 123: substituir "você perceberá alguns marcadores da linguagem HTML" por "alguns marcadores da linguagem HTML poderão ser identificados";
> * [x]  linha 133: substituir "você vai aprender em breve a eliminar o excesso" por "aprenderemos em breve a eliminar o excesso";
> * [x]  linha 137: substituir "Considerando o que você já sabe sobre" por "Considerando o que foi visto sobre";
> * [x]  linha 154: substituir "que recomendamos depois que você tenha terminado as lições" por "que recomendamos depois que tenha terminado as lições";
> * [x]  linha 164: substituir "é importante que você tenha" por "é importante ter";
> * [x]  linha 164: substituir "para ter certeza que você está utilizando o código correto" por "para ter certeza de que o ficheiro correto está sendo utilizado";
> 
> Obrigado pela revisão e vamos nos falando. Abraço!

**Comment by bruno-ponne** [comment]
oi @felipelmc, obrigado por lembrar. Fiz essas duas alterações. Qualquer coisa a mais, só avisar. Abraço!

**Comment by felipelmc** [comment]
Ótimo @bruno-ponne! @josircg, me parece que já está tudo ok com a lição. Abraços!

**Comment by DanielAlvesLABDH** [comment]
Olá @bruno-ponne! As minhas desculpas pelo atraso na revisão, mas aqui vão algumas notas para ajudar a corrigir a tradução.
No geral acho que a tradução está óptima, bem adaptada para o português e depois das revisões do @felipelmc ficou ainda melhor! Indico apenas alguns detalhes.
Ao utilizar a palavra "site", em vários pontos do texto, eu retiraria as aspas ou o itálico. Hoje em dia é uma expressão já plenamente integrada no português comum. Se o @josircg concordar, acho que o Bruno poderia fazer essa alteração em todos os pontos do texto, como por exemplo na linha 42 "Quando um *site* é acessado"
- [x] linha 42: onde está "o servidor, diretório e nome ficheiro a ser recuperado" deve ficar "o servidor, o diretório e o nome do ficheiro a ser recuperado"
- [x] linha 62: eliminar a vírgula "no servidor, e é possível "
- [x] linha 80: eliminar espaço a mais "do século XVIII ."
- [x] linha 90: sugiro que se mude este texto ", e é possível acessar" para "Segundo, é possível acessar", tendo em conta o início da frase.
- [x] linha 90: onde está "acima, seu navegador" deve ficar "acima, o seu navegador"
- [x] linha 96 confirmar se estas instruções de acesso ao código fonte da página ("Utilize `Ferramentas -> Ferramentas de Programação -> Ver Código Fonte` no navegador Firefox") ainda estão válidas para as versões mais recentes do Firefox.
- [x] linha 133 onde está "O conteúdo do teste fica na parte inferior da página." deve estar "O conteúdo do julgamento fica na parte inferior da página."
- [x] linha 159 Na leitura sugerida é indica uma obra de 1999. Será que não encontramos uma referência mais recente e em português? Se fosse possível era uma boa actualização da lição. Por exemplo, poderá este (https://python.nilo.pro.br/) ser uma boa opção? Ou este (https://www.fnac.pt/mp8617047/Introducao-A-Linguagem-De-Programacao-Python)? Confesso que não conheço estes livros. Talvez o @josircg possa ajudar...
Para já parece-me que estas são as notas da minha revisão. Obrigado pela sua colaboração Bruno e qualquer dúvida estou ao dispor! Abraço

**Comment by josircg** [comment]
@DanielAlvesLABDH com certeza existem outras obras bem mais recentes que essa indicada. Mas nós temos a prerrogativa de alterar ou incluir outras bibliografias sem que elas estejam na tradução original?

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg! Sim, podemos fazer alterações pontuais. No limite poderíamos até mudar o site que serve de exemplo aos exercícios Python. Em algumas lições as outras equipas têm feito isso, para adaptar aos casos particulares dos respectivos meios académicos.

**Comment by bruno-ponne** [comment]
Olá @DanielAlvesLABDH ! Obrigado pela revisão.
Vou consultar as suas sugestões para atualização da bibliografia e ajustar o texto nos próximos dias.
Se eu encontrar alguma obra boa sobre webscraping em português vou sugerir aqui também para ver o que vocês acham. Abraços.

**Comment by bruno-ponne** [comment]
Bom dia, eu encontrei esse livro especificamente sobre webscraping. Seria para um usuário mais intermediário que gostaria de se aprofundar no tema: "Web Scraping com Python: Coletando Mais Dados da web Moderna" - https://www.amazon.com.br/Web-Scraping-Com-Python-Coletando/dp/8575227300

O que acham?

**Comment by bruno-ponne** [comment]
Oi @DanielAlvesLABDH, ajustei os trechos do texto que você sugeriu. Obrigado pelas correções. De fato, o caminho para verificar o código fonte da página no Firefox mudou. Uma pergunta: como ficam as figuras nessa etapa de revisão? Elas serão adicionadas apenas na publicação final ou já há uma pasta de imagens? 

Acredito que "Introducao A Linguagem De Programacao Python" (https://www.fnac.pt/mp8617047/Introducao-A-Linguagem-De-Programacao-Python) seria uma boa atualização para a leitura sugerida assim como a que sugeri acima. A diferença é que uma é mais básica e geral e a outra é mais específica para webscraping. Aguardo a opinião de vocês. Abraços.

**Comment by DanielAlvesLABDH** [comment]
Olá @bruno-ponne ! Muito obrigado pela revisão final e pela indicação dessa referência sobre Python. Como o especialista é o @josircg vou deixar que seja ele a indicar qual a melhor opção. Quanto às imagens para associar ao ficheiro, peço que as envie ao Josir. É ele como editor que terá de criar uma pasta com o nome da lição "download-de-paginas-web-com-python" aqui (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/lessons/portuguese/Imagens) e fazer o upload dos ficheiros. Se tiver dúvidas sobre isso veja o ponto 4 destas directrizes para tradutores: https://programminghistorian.org/pt/directrizes-tradutor#submeter-uma-li%C3%A7%C3%A3o-traduzida

**Comment by josircg** [comment]
Oi @DanielAlvesLABDH fiquei em dúvida se a pasta correta é essa. Veja o item (4) de

https://programminghistorian.org/pt/directrizes-tradutor#submeter-uma-li%C3%A7%C3%A3o-traduzida

Acredito que o correto seria jogar as imagens na pasta de images, não é?

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg! Sim, tem razão, é essa a pasta, mas dentro dela tem de criar uma outra com o nome da lição e foi aqui que eu baralhei as coisas. Portanto, não é uma pasta genérica de imagens PT, mas uma pasta para cada lição que vamos traduzindo. Em alguns casos não é necessário, pois usamos os ficheiros das versões originais. Obrigado pelo aviso

**Comment by josircg** [comment]
Excelente. Fiz dessa forma assim e já fiz o commit para que o @bruno-ponne possa utilizar a pasta. Qualquer dúvida é só falar Bruno:

https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/download-de-paginas-web-com-python

Sobre a bibliografia: esse livro sobre o web scrapying é o mais conhecido. Só temos que utilizar um outro link pois não podemos fazer propaganda gratuita para a Amazon :)

Segue o link da editora:

https://novatec.com.br/livros/web-scraping-com-python-2ed/

**Comment by DanielAlvesLABDH** [comment]
E se for um link para sebos? https://www.estantevirtual.com.br/livros/ryan-mitchell/web-scraping-com-python/1768559994

**Comment by josircg** [comment]
Também é uma ideia. Mas eu não sei qual a política de PH sobre incluir diretamente um site de comércio eletrônico. Talvez eles até tenham uma parceria com a Amazon para recomendar livros!

O da Editora pode parecer mais "neutro".

**Comment by DanielAlvesLABDH** [comment]
Fui olhar com mais atenção a lição original e o que lá está é apenas a referência bibliográfica, não um link para o livro. Acho que devíamos manter assim, apenas referenciar este livro em português, Mas não incluir um link.

**Comment by bruno-ponne** [comment]
Olá, obrigado pelas orientações @josircg e @DanielAlvesLABDH . Eu alterei a leitura sugerida sem incluir o link para página externa. Além disso, adicionei as duas imagens da lição (as imagens são as mesmas da versão original). Fico à disposição para demais ajustes. Um bom final de semana : )

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @bruno-ponne ! Vou agora fazer uma leitura final e preparar o ficheiro para publicação.

**Comment by DanielAlvesLABDH** [comment]
A tradução e revisão foram concluídas, já pedi o DOI e estou a finalizar a publicação da lição. Agradeço ao @bruno-ponne pela excelente tradução e pela óptima colaboração com a equipe do Programming Historian em português. Agradeço também ao @felipelmc pela revisão atenta (e ao @JimmyMedeiros82 por nos ter colocado em contacto com o Felipe). Por fim, obrigado ao @josircg pelo trabalho de edição de mais esta lição. É a décima (10ª) que publicamos!!!

**Comment by bruno-ponne** [comment]
Que bom! Agradeço também a vocês pelo apoio ao longo da tradução! Um abraço.

**Comment by DanielAlvesLABDH** [comment]
@josircg a lição já foi publicada. Falta incluir a sua referência no bot do Twitter. Veja aqui como fazer: https://programminghistorian.org/pt/directrizes-editor#6-incorporar-a-li%C3%A7%C3%A3o-ao-nosso-bot-do-twitter. A planilha tem uma folha para PT. Já lá estão as lições anteriores, é só seguir o modelo. Depois podemos fechar isto. Obrigado por tudo!

**Comment by joanacvp** [comment]
Boa tarde a todos!
@josircg e @DanielAlvesLABDH estive hoje a fazer esta lição. O código de save-webpage.py dá erro no Windows. Pelo que percebi de issues que li aqui trata-se de substituir o 'wb' por apenas 'w' no final deste trecho (linha 10):
f = open('obo-t17800628-33.html', 'w')

Fazendo essa mudança consegui gerar o código e o resultado obtido foi o pretendido.

**Comment by josircg** [comment]
Está errado realmente. Nesse caso, o correto é criar uma issue nova de ajuste, não é?

**Comment by DanielAlvesLABDH** [comment]
Já abri um PR para corrigir isto. Obrigado pelo reporte do erro @joanacvp
