### ISSUE TITLE
Créer sa base de données (avec Heurist)

### ISSUE THREAD

**Issue by wiztigers** [programminghistorian/ph-submissions#361]
Bonjour,

J'ai écrit il y a quelques semaines ce tutoriel : « [**Créer sa base de données** (avec Heurist)](https://uncoded.gitlab.io/BDD/) ».
Les principaux objectifs pédagogiques du tutoriel sont :

1. d'introduire les débutant·e·s aux principaux concepts de modélisation de base de données
2. de rappeler / faire réfléchir celles et ceux qui en ont besoin certains concepts de la science ouverte (FAIRness, logiciels ouverts et/ou libres, ...)
3. de permettre aux différents publics en SHS de gérer leurs données de manière autonome, sans forcément recourir aux services d'un informaticien
4. (ouverture, non encore rédigé) d'illustrer des techniques d'organisation d'équipe (rôles, droits d'accès, ...) 
5. (ouverture, non encore rédigé) de montrer les possibilités d'auto-publication de site web basique à partir d'une base de donnée

Heurist sert à utiliser ces concepts, pour les raisons décrites dans le tutoriel, mais j'ai essayé de [proposer des alternatives](https://uncoded.gitlab.io/BDD/#_alternatives) chaque fois que c'est pertinent (j'y rajouterai peut-être Omeka si j'ai un jour le temps de développer le point 5.). Pour être plus robuste aux futures évolutions de l'interface graphique d'Heurist, j'ai aussi essayé de mettre le moins de screenshots possible, mais il y a clairement des points pour lesquels c'est plus pédagogique de _montrer_ les choses.

Si cela intéresse _The Programming Historian en français_, nous pouvons discuter comment (facilement) l'intégrer à vos leçons. Je peux aussi en proposer sans trop de problèmes une traduction en anglais, si vous le souhaitez.

Dans le cadre de mon travail, je continuerai probablement à enrichir ce tutoriel [depuis mon dépôt actuel GitLab](https://gitlab.com/uncoded/BDD), au cours des prochaines années. Si mon tutoriel intéresse _The Programming Historian_, je devrais pouvoir sans trop de problème customiser mon script d'intégration continue pour qu'elle mette à jour un fork GitHub avec un fichier markdown généré pour que _The Programming Historian_ profite automatiquement des modifications que j'apporterai (via des pulls requests soumises à votre comité de lecture évidemment). Au final, vous profiteriez du même contenu, mais adapté évidemment au style (et notamment à la charte graphique de) _The Programming Historian_.

Si mon tuto vous intéresse, j'ai besoin de savoir : 
- est-ce que c'est okay si je publie ce tutoriel chez vous sous licence [CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr) ? Je ne suis pas parvenu à trouver la licence sous laquelle vous publiez (j'ai juste vu la référence à CC-BY dans votre template d'issues), et je tiens à ce que la connaissance que je produis circule librement sans réappropriation commerciale. Au pire, on peut discuter d'un changement de licence, tout dépend de ce que vous proposez ... ¯\_(ツ)_/¯
- où est-ce que je commite le futur fichier markdown que je vous génèrerai ? dans `ph-submissions/fr/lecons`, `ph-submissions/fr/published`, `ph-submissions/lessons/french`, ou à un autre endroit ?
- quel délai vous arrangerait pour la publication finale ? Comme je l'ai précisé, la base de la leçon elle-même est largement déjà écrite (mais je suis évidemment preneur de toutes vos remarques qui pourraient contribuer à l'améliorer), mais il faut quand même que je prenne le temps de mettre à jour la pipeline de publication.
- quel est le statut de #300 ? Si vous avez déjà quelque chose de prévu, je veux pas créer de conflit, hein.

Vous pouvez utiliser cette issue pour discuter avec moi.
À défaut, mes coordonnées sont dans le tutoriel, et si vous voulez mieux me connaître, je suis [ce type-là](https://www.misha.fr/plateformes/phun#regis-witz).

À vous lire. ( ▀¯▀)

**Comment by spapastamkou** [comment]
Merci pour votre proposition @wiztigers et de nous avoir signalé votre travail, très détaillé et soigné. Pour info, la procédure pour proposer une leçon est décrite [ici](https://programminghistorian.org/fr/consignes-auteurs#proposer-une-nouvelle-le%C3%A7on). Mais nous avons déjà une proposition en cours, qui a mis plus que prévu surtout parce que nous avons attendu que Heurist passe à la version 6. Je me permets de mettre en copie l'auteur @vpaillusson pour qu'il prenne connaissance de votre travail.
