### ISSUE TITLE
Revisão da tradução da lição "Introdução ao Markdown"

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#363]
Seguimento do ticket #353 

O Programming Historian em português recebeu a proposta sobre 'Introdução ao Markdown' do autor @0jonjo . Esta lição está agora em revisão por @josircg e @bgmartins e pode ser lida em: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/lessons/portuguese/propostas/introducao-ao-markdown.md

Eu (@joanacvp) serei a editora no processo de revisão. O meu papel é solicitar duas revisões da comunidade e gerir as discussões, que devem ser realizadas aqui neste fórum. Eu já li a lição e forneci feedback, ao qual o autor respondeu. Solicito que a revisão seja feita no prazo de um mês.

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso ombudsperson Luís Ferla se achar necessário.

Política anti-assédio

Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso ombudsperson Luís Ferla. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by josircg** [comment]
Olá João, veja se vc concorda com as modificações:

https://github.com/programminghistorian/ph-submissions/commit/f507b1a52188e1caeeda77d3043e40f4301c5606

**Comment by 0jonjo** [comment]
> [f507b1a](https://github.com/programminghistorian/ph-submissions/commit/f507b1a52188e1caeeda77d3043e40f4301c5606)

Ótimos ajustes e correções!

**Comment by josircg** [comment]
Olá @bgmartins - você quer fazer alguma consideração extra ou podemos encerrar a revisão?

**Comment by 0jonjo** [comment]
> Olá @bgmartins - você quer fazer alguma consideração extra ou podemos encerrar a revisão?

Creio que realmente não haverão novas contribuições. Fiquei satisfeito com as suas correções @josircg.

**Comment by joanacvp** [comment]
Boa tarde @0jonjo. As correções já tão todas introduzidas? Obrigada

**Comment by 0jonjo** [comment]
> Boa tarde @0jonjo. As correções já tão todas introduzidas? Obrigada

Boa tarde, sim. Já foram introduzidas no arquivo. Tudo pronto.

**Comment by joanacvp** [comment]
Muito obrigada @0jonjo. Pergunto ao @josircg e ao @bgmartins se estão satisfeitos com as introduções e se têm mais alguma sugestão a fazer. Em caso negativo farei uma última leitura da lição.

Obrigada a todos pelo contributo

**Comment by josircg** [comment]
Por mim está tudo ok.

**Comment by joanacvp** [comment]
@bgmartins também lhe parece tudo ok? Gostaria de fazer mais alguma sugestão? Obrigada

**Comment by joanacvp** [comment]
@0jonjo muito obrigada pelo seu trabalho. Estive a reler a lição e deixo abaixo algumas sugestões:

- [x] linha 41: substituir "inclui" por "incluí"
- [x] linha 45: substituir "se refere:" por "se refere a:"
- [x] linha 47: substituir "salvo em um formato" por "salvo num formato"
- [x] linha 52: substituir "abertos em um editor" por "abertos num editor"
- [x] linha 75: substituir "nível" por "níveis"
- [x] linha 124: substituir "a" por "à"
- [x] linha 163: substituir "transformados em outros formatos" por "transformados noutros formatos"
- [x] linha 242: falta um ponto final no final da frase
- [x] linha 257: existe um asterisco a mais no final da frase
- [x] linha 281: substituir "com os outros" por "com as outras"
- [x] linha 316: substituir "linha de comando" por "linha de comandos"


Qualquer dúvida disponha

**Comment by 0jonjo** [comment]
> @0jonjo muito obrigada pelo seu trabalho. Estive a reler a lição e deixo abaixo algumas sugestões:
> 
>     * [x]  linha 41: substituir "inclui" por "incluí"
> 
>     * [x]  linha 45: substituir "se refere:" por "se refere a:"
> 
>     * [x]  linha 47: substituir "salvo em um formato" por "salvo num formato"
> 
>     * [x]  linha 52: substituir "abertos em um editor" por "abertos num editor"
> 
>     * [x]  linha 75: substituir "nível" por "níveis"
> 
>     * [x]  linha 124: substituir "a" por "à"
> 
>     * [x]  linha 163: substituir "transformados em outros formatos" por "transformados noutros formatos"
> 
>     * [x]  linha 242: falta um ponto final no final da frase
> 
>     * [x]  linha 257: existe um asterisco a mais no final da frase
> 
>     * [x]  linha 281: substituir "com os outros" por "com as outras"
> 
>     * [x]  linha 316: substituir "linha de comando" por "linha de comandos"
> 
> 
> Qualquer dúvida disponha

Ajustes feitos, muito obrigado pela revisão.

**Comment by joanacvp** [comment]
Muito obrigada @0jonjo. 
O processo de tradução e revisão está concluído. Penso que podemos avançar depois do @DanielAlvesLABDH dar uma última revisão na lição, como costuma ser o procedimento habitual.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos, obrigado @joanacvp! Assim que possível faço uma revisão final

**Comment by DanielAlvesLABDH** [comment]
Actualizei o cabeçalho da lição (https://github.com/programminghistorian/ph-submissions/commit/4c09c36a6e5556b52d20ac402d12606ef40d1969). É ainda necessário fazer uma revisão geral no texto e na forma como está indicado o funcionamento do StackEdit. Deixarei algumas notas de revisão aqui.

**Comment by DanielAlvesLABDH** [comment]
Notas de revisão:
- Na compatibilização entre o português de Portugal e o do Brasil, a equipe fez algumas escolhas de palavras que devem ser usadas em todas as traduções. Nesta tradução talvez a alteração mais frequente é da palavra "arquivo" / "arquivos" que deve ser mudada para "ficheiro" / "ficheiros". São muitos os pontos do texto onde isso acorre, por isso não vou indicar aqui todos, mas veja-se, por exemplo, a linha 37. Onde está "como formatar arquivos Markdown" deve ficar "como formatar ficheiros Markdown". A @joanacvp poderá ajudar com outros aspectos.
- Na linha 43 há uma referência a uma "ferramenta Perl". Tendo em conta o público-alvo do Programming Historian, talvez fosse útil incluir um link para uma página que explicasse o que é o "Perl". Pergunto ao @josircg e ao @bgmartins se consideram que esta página da Wikipedia (https://pt.wikipedia.org/wiki/Perl) poderia ser usada como boa referência?
- No final da linha 47, onde está "Dennis Tenen and Grant Wythoff" deve ficar "Dennis Tenen e Grant Wythoff"
- A partir da linha 54 é apresentada uma explicação do funcionamento do StackEdit, mas algumas das instruções não correspondem exactamente ao que o futuro utilizador da lição vai encontrar (estou a usar o Firefox, num Windows 10).
- A abertura do menu é indicada como clicando no # no "canto superior esquerdo". Esse botão aparece no "canto superior direito". Essa diferença resulta da utilização de diferentes navegadores ou da utilização de Mac vs. Windows? Ou é falha na tradução?
- Depois de se indicar como abrir o menu no StackEdit (usando o #) é referido que se deve escolher a opão `Import from URL` e depois colar a URL da lição "Preservar seus dados de investigação". Acontece que no menu do StackEdit aprece apenas uma função "Import/Export" e só depois desta seleccionada é que surgem duas opções de importação. Mas nenhuma delas é "Import from URL". Uma diz "Import MarkDown" e a outra diz "Import HTML". Temos de escolher a primeira para obter o resultado apresentado na linha 59.
- Ainda na linha 54, onde está "para abri o menu" deve ficar "para abrir o menu"
- Ainda na linha 54, onde está "Preservar seus dados de investigação" deve ficar "Preservar os seus dados de investigação"
- Na linha 61, para criar um novo documento é referido o "ícone de pasta no canto superior direito". Esse ícone aparece no "canto superior esquerdo". Confirmar! É ainda referido "escolha a opção `New document`", mas o que aparece é "New file". Confirmar!
- Na linha 184, a inclusão da palavra "html" a seguir às crases ou parece estar a mais ou não é explicada a sua função ali, pois se o utilizador copiar exactamente o texto que é indicado e o colar no StackEdit, o resultado no painel da direita não é exactamente o mostrado nas linhas 196 a 204.
- Na linha 226 são referidos "colchetes" quer para designar parênteses rectos, quer para parênteses curvos, na escrita dos links. Em Portugal é mais frequente usar "parênteses" rectos ou curvos do que colchetes. A manter o uso de "colchetes" esse uso só pode ser feito no caso dos parênteses rectos, pois os curvos são parênteses e não colchetes. Entre outras referências veja-se aqui: https://www.portugues.com.br/gramatica/parenteses.html (corrigir os usos seguintes no texto...)
- Na linha 277 há um espaço a mais entre [GitHub] e o respectivo URL. No final da mesma linha tem de ser revisto o texto "no navegador a partir GitHub." pois parece errado ou incompleto. A frase perde sentido.
Parece-me que é tudo.
Agradeço ao João Gilberto (@0jonjo) a tradução e a colaboração com o Programming Historian em português e peço ao @josircg e ao @bgmartins que façam uma última revisão (até para ver se não cometi algum erro aqui). Peço-vos que coloquem os vossos comentários e possíveis sugestões de revisão aqui no ticket para que fiquem documentadas. Obrigado!

**Comment by 0jonjo** [comment]
Obrigado pelas correções e sugestões @DanielAlvesLABDH. Já fiz as alterações sugeridas.

**Comment by josircg** [comment]
Por mim está tudo ok agora.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a ambos. Falta apenas mudar "New document" para "New file" na linha 61. Pelo menos para mim é como aparece. Se confirmar que é assim no StackEdit, @0jonjo, então altere, por favor. Se for diferente, veja se vale a pena colocar uma nota para diferenças consoante navegador e/ou sistema operativo.

**Comment by 0jonjo** [comment]
> Obrigado a ambos. Falta apenas mudar "New document" para "New file" na linha 61. Pelo menos para mim é como aparece. Se confirmar que é assim no StackEdit, @0jonjo, então altere, por favor. Se for diferente, veja se vale a pena colocar uma nota para diferenças consoante navegador e/ou sistema operativo.

É New File mesmo, tens razão. A maior parte das alterações foi por conta de mudanças recentes - depois que eu fiz a tradução - na organização dos menus e na importação de links e documentos do StackEdit. Agora está correto.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado. Sendo assim, vou dar por fechada a revisão, pedir o DOI e publicar! Obrigado a todos, obrigado à Joana pela edição!

**Comment by DanielAlvesLABDH** [comment]
Introduzi pequenas correcções e vou agora tratar do pedido do DOI!

**Comment by DanielAlvesLABDH** [comment]
Mais uma lição publicada! Muito obrigado ao João Gilberto (@0jonjo) pela tradução, à Joana (@joanacvp) pela edição e ao Bruno (@bgmartins) e Josir (@josircg) pelas revisões! https://programminghistorian.org/pt/licoes/introducao-ao-markdown

**Comment by DanielAlvesLABDH** [comment]
@joanacvp depois actualize o bot do Twitter, por favor. Obrigado

**Comment by joanacvp** [comment]
@DanielAlvesLABDH tweets introduzidos. Obrigada
