### ISSUE TITLE
Ticket de revisión: "Introducción a la codificación de textos en TEI - Parte 1"

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#366]
_Programming Historian en español_ ha recibido la siguiente propuesta de lección: "Introducción a la codificación de textos en TEI - Parte 1" por parte de Nicolás Vaughan (@nivaca). La editora de esta lección será @jenniferisasi. Esta lección es la primera parte de una secuencia de dos, y se encuentra en estos momentos en fase de revisión y puede leerse en:

**Vista previa**
http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei-1

**Archivo**
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-a-tei-1.md

**Imágenes**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/introduccion-a-tei

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra *ombudperson*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

-- 

Con este ticket se cierra el preliminar #351 y en el que se decidió partir en dos una lección completa demasiado larga.

**Comment by jenniferisasi** [comment]
@RocioLMendez ha accedido a ser la primera revisora de esta lección y siguiendo nuestras [directrices de revisión](https://programminghistorian.org/es/guia-para-revisores) se trata de revisar si: 

- ¿El autor tiene en mente un destinatario ideal a lo largo de la lección?
- ¿Hay pasos explicados en exceso? ¿Hay otros pasos, en cambio, que requieren mayor detalles?
- ¿En qué sentido la lección supone una novedad?
- ¿Los objetivos y las habilidades previas que se necesitan se exponen de manera clara al inicio del tutorial?
- ¿Las habilidades derivadas del tutorial son útiles?
- ¿Las capturas de pantalla y diagramas ilustran los pasos más importantes del tutorial?
- ¿Las secciones y títulos de sección son claros y guían al lector?
- Etc. 

@RocioLMendez puedes indicar tus comentarios de forma general primero y después, si son detalles concretos, puedes servirte de los números de párrafo que aparecen en la vista previa de la lección. En este mismo ticket. Puedes ver este otro si no estás segura de cómo hacemos estas revisiones: https://github.com/programminghistorian/ph-submissions/issues/330 

¡Muchas gracias de antemano por tu colaboración!

**Comment by mendezrocio** [comment]
Hola @nivaca y @jenniferisasi

Quiero felicitarte por el tremendo trabajo que has hecho, @nivaca. Me ha gustado mucho leer la lección que has escrito. Es una lección clara y completa, ideal para un lector que se está iniciando en la materia XML-TEI, contiene explicaciones detalladas de los diferentes formatos y lenguajes, así como el abanico de softwares útiles para XML-TEI. ¡Felicidades! 

Adjunto una lista de correcciones, las cuales son en general estéticas, para que la lectura fluya mejor, mayor claridad y comprensión posible para lectores hispano-hablantes. Aclaro el número de párrafo y la corrección de la palabra o frase correspondiente, con algunas palabras como acompañante para que puedan identificar rápidamente el texto que ha sido editado.

**Comentarios para la lectura:**

1: el término "captura" tal vez sea poco claro para lectores de América Latina, a qué está refiriendo?
2: podría establecerse la distinción entre "texto escaneado" y "texto plano" correspondientes a "texto digitalizado" y "texto digital", a fin de dejar claros ambos términos.
4: "entre otras," --> "entre otras acciones"
"etc.,etc.,etc." -->  "etc."
"que ciertas cadenas de texto plano tienen cierta significación." --> "que ciertas cadenas de texto plano tienen determinada significación." o similar.
6: "numero" --> "número"
"TEI" --> TEI (Text Encoding Initiative)
7: "texto plano" añadir --> "texto plano (formato .txt)" -ya que más arriba se señalan tipos de formato para las imágenes-.
8: "XML" --> "XML (extensible markup language)"
17: el término "piquen" creo que puede ser algo confuso para los lectores, sugiero: hacer clic, clicar y cliquear (RAE).
19: "entre otras," --> "entre otras funciones/acciones"
25 y 29: "procesador de palabras" --> "procesador de texto"
29: "tan será" --> "tal será" 
36: "el sentido el texto" --> "el sentido del texto"
54: tal vez el término "colapsan" resulta poco claro para lectores, a qué está refiriendo?
78: "tenemos ahí el atributo" --> "tenemos expresado el atributo"
83: "y hecho es" --> "y de hecho es"
88: "elemento `<l>` (de _line_)" --> "elemento `<l>` (de _line_, 'linea')"
90: sugiero cambiar `<l met="x/x/x/x/x/x/x/x/x/x/x/" n="1">Cerrar podrá mis ojos la postrera</l>` --> `<l met="11" n="1">Cerrar podrá mis ojos la postrera</l>`, y/o dar la opción de incorporarlo al elemento `<lg>` mostrando así la métrica de la estrofa: `<lg met="11,11,11,11" rhyme="abba">`

Sugiero cambiar las comillas dobles en las traducciones de los diferentes atributos que se describen en la lección por comillas simples, por ejemplo en el párrafo 98: "`<sourceDesc>` (de _source description_, "descripción de la fuente")"  --> "`<sourceDesc>` (de _source description_, 'descripción de la fuente')". Así como cuando se refiere a la traducción de un término en concreto incorporarla al texto entre paréntesis y en comillas simples, como en el párrafo 103: " que contiene el _backmatter_ ('páginas finales') -los apéndices, índices, etc.-. ". 

He disfrutado aportar mi grano de arena en este proyecto, espero estar haciéndolo de manera correcta y respetuosa. Gracias @nivaca por escribir esta lección. Quedo a su disposición para cualquier duda o comentario que surja de mi revisión.

**Comment by nivaca** [comment]
Estimada @RocioLMendez, mil gracias por tus comentarios! Me pondré a corregir lo necesario.

**Comment by nivaca** [comment]
Muchas gracias, @RocioLMendez. Ya hice los cambios que me sugeriste. Aprecio mucho que te hayas tomado el trabajo de leer con cuidado la lección. Quedo pendiente de qué más debo hacer.

**Comment by jenniferisasi** [comment]
Gracias @RocioLMendez por tan detallada revisión y a @nivaca por introducir las correcciones. Voy a conectar con un/a segundo/a revisor/a lo antes posible. Llevamos buen camino para una publicación rápida 👍

**Comment by jenniferisasi** [comment]
Buenas noticias, @icanogar ha aceptado ser el segundo revisor para la lección, siguiendo las directrices de https://programminghistorian.org/es/guia-para-revisores. Más o menos cuestiones como: 
- ¿El autor tiene en mente un destinatario ideal a lo largo de la lección?
- ¿Hay pasos explicados en exceso? ¿Hay otros pasos, en cambio, que requieren mayor detalles?
- ¿En qué sentido la lección supone una novedad?
- ¿Los objetivos y las habilidades previas que se necesitan se exponen de manera clara al inicio del tutorial?
- ¿Las habilidades derivadas del tutorial son útiles?
- ¿Las capturas de pantalla y diagramas ilustran los pasos más importantes del tutorial?
- ¿Las secciones y títulos de sección son claros y guían al lector?
- Etc.

Para comentarios concretos, por favor utiliza el número de párrafo que aparece en la vista previa: http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei-1

¡Gracias @icanogar! Marco el 16 de mayo como plazo, pero si te surge cualquier imprevisto y necesitas más tiempo, basta con dejar aquí una nota o enviarme un email.

**Comment by icanogar** [comment]
Gracias por vuestra confianza! Puedo parecer seco y demasiado riguroso, pero es que vivo en Alemania y se me está pegando. Me ilusiona poder aportar al proyecto y espero también aprender de la experiencia. Un saludo!
https://icanogar.gitlab.io/me/ <- por ahora era de la competencia.

**Comment by jenniferisasi** [comment]
@nivaca no nos hemos olvidado de esta tarea. @icanogar me ha informado por privado de que necesita unos días más para entregar su revisión y quedamos pendientes a ella.

**Comment by icanogar** [comment]
Disculpad el retraso! Allá voy.

Es evidente que @nivaca domina la materia, cuenta con experiencia docente y, sobre todo, que le apasiona lo que está explicando. Desde mi punto de vista, hay dos aspectos (vinculados) que deberían vigilarse para adecuar este texto a PH: la extensión de la lección y su estilo. En un segundo orden, me gustaría plantear si una distribución un tanto más, digamos, informal de los contenidos podría redundar en una lección más atractiva. Pero vamos por partes.

Por lo general, las lecciones de PH son muy ágiles de ritmo y su estilo es muy sencillo. Esto constituye una «marca», y hasta diría que es la clave de su éxito: quien abre PH sabe que va a encontrar algo más profundo y razonado que un tutorial de Youtube, pero aún así sigue buscando resultados, a ser posible de rápida aplicación.

Por eso me preocupa que la extensión de esta lección puede desanimar a los que quieran seguirla (y en buena parte su longitud es debida al estilo elegido). En mi opinión, sería apropiado simplificar su lenguaje y su estilo para armonizarla con las demás lecciones de la revista; esto, además, facilitaría su traducción a los otros idiomas.

Por ejemplo, la idea de los párrafos §3 y §4 queda muy clara desde el principio, pero se corre el peligro de que, precisamente por un exceso de desarrollo, se contribuya a la confusión. De la misma forma, explicar demasiado «de qué no se trata» (§27-29 sobre Markdown) o «cómo no hay que hacer algo» (§35) puede distraer a los lectores. Lo mismo que explorar caminos que al final se descartan o mencionar aspectos que se verán después (en §35 se comentan varias etiquetas, algunas con detalle, cuando todavía no sabemos siquiera qué es una etiqueta). Puliendo este tipo de excursos y anticipaciones, la lección ganaría en claridad y concisión.

Puede defenderse la necesidad de una sección sobre XML tan desarrollada (§37-82), pero a mí me recuerda demasiado a contenidos que se pueden leer en muchos otros sitios web. Atajaría esta sección para llegar al TEI cuanto antes. Podría incluso remitirse a [esta otra lección de PH](
https://programminghistorian.org/es/lecciones/transformacion-datos-xml-xsl) en una de cuyas secciones, aunque de forma rasante, se comentan los fundamentos del marcado XML.

Reconociendo la importancia capital del `<tei-header>` y los metadatos (§96 y ss.), opino que es un aspecto, de entrada, demasiado abstracto para quien empieza. Se podría aprovechar el ejemplo de Quevedo, inmediatamente anterior (aunque incluso más arriba se nos había prometido un ejemplo de Soledad Acosta, ¡muero de ganas!) y construir el documento de abajo arriba, por así decirlo: del nodo terminal `<l>` a su estrofa, luego a su poema, y luego coronar con el `<tei-header>` y todos sus campos. Que los elementos de un documento completo aparezcan de acuerdo a una determinada linealidad no nos obliga a seguirla en su exposición.

Tengo una última propuesta. Aunque el formato de las leccciones no es, por naturaleza, demasiado interactivo, sí que he visto en otras cómo los autores proponen actividades que suponen un pequeño recto al lector (y un descanso de su atención). Volviendo al ejemplo de Quevedo, se le podría presentar el soneto y preguntar qué categorías merecen marcarse. La respuesta indicaría que algunas (rimas, métrica, versos, estrofas) corresponderían a `<text>`, mientras que otras (título, autor, editor, fuente) corresponderían al `<header>`, incluso sugiriendo otras posibilidades de marcado (partes del discurso, lematización, anotación, variantes ortográficas) que obecederían a diferentes intereses (en la línea de §109-111, y que considero la idea más fuerte de esta lección, lo que la distingue del resto de materiales que pululan por la red y que se debería destacar entre los objetivos de aprendizaje).

En resumen: valoro la necesidad de esta lección (o serie de lecciones) en PH, y reconozco la valentía y la competencia de @nivaca en una empresa tan complicada, pero 1) debería armonizarse en extensión y estilo a las lecciones ya existentes y 2) evitar la exposición mecánica de contenidos que pueden encontrarse en otros sitios, precisamente para que las buenas ideas que aporta no pasen desapercibidas.

Quedo a vuestra disposición para debatir estos u otros puntos. Gracias por tenerme en cuenta para esta revisión!

**Comment by nivaca** [comment]
Estimada @icanogar, muchas gracias por tu cuidadosa lectura y tus comentarios.
Ya habíamos discutido con @jenniferisasi el dividir la lección en dos partes (la primera más teórica, la segunda con los casos de estudio).
La verdad no sé muy bien cómo proceder ahora. Según lo que dices, mi texto no cuadra muy bien con el estilo de las lección de PH, y no sé cómo transformarlo sin reescribirlo completamente.

**Comment by jenniferisasi** [comment]
Estimados. Gracias @icanogar por tu lectura y atentos comentarios. @nivaca como la tarea de los revisores es apuntar ideas que les han resultado complicadas de seguir además de valorar la utilidad práctica de la lección, y mi obligación como editora es ayudarte a afinar la lección, trata aquí de ayudarte para darle otra vuelta a la lección.

En general, los comentarios de @icanogar podrían resumirse con una necesidad de simplificar el lenguaje con el fin de lograr una lectura más rápida, por decirlo de algún modo, de la lección, sin caer tampoco en una mera lista de instrucciones a seguir (estamos lejos de esto último, así que no me preocupa), y darle un mayor peso a la(s) sección(es) que tratan de TEI (como ya habíamos comentado antes de dividir la lección en dos). Por partes. 
 

- [ ] Extensión de la lección/detalle en demasía. Podemos pensarlo como ejemplos que no están directamente relacionados con TEI o, dicho de otro modo, que no casan en la lección (el usuario ya debe saberlo, lo puede leer en otro lugar, etc.). Los párrafos 2, 3 y 4 (que @icanogar identifica) me parecen un buen ejemplo de esta solicitud de simplificación. Trato aquí de reducirlo a lo necesario (como propuesta, no imposición): 

~~Un ejemplo puede ayudar a aclarar esta idea. Supongamos que~~ Normalmente tenemos la imagen de un documento que hemos digitalizado previamente ~~digamos, un documento impreso, esto es, uno producido en una prensa o imprenta; no un manuscrito. Tenemos las imágenes de sus páginas (en formato PNG, TIFF, etc.)~~ y, con ayuda de un software de reconocimiento óptico de caracteres (OCR, en inglés), extraemos ~~ahora~~ el texto contenido en ellas. ~~Este paso es absolutamente necesario. Las imágenes escaneadas originalmente no tienen texto alguno: tan solo son “mapas de bits” que representan píxeles en distintos tonos e intensidades. En efecto, no podemos “seleccionar el texto” en una imagen que aún no haya sido procesada por OCR para obtenerlo.~~ Este texto es lo que suele llamarse texto plano (o texto digitalizado), es decir, texto sin formato alguno (sin cursivas, negritas, etc.) ni ninguna otra estructuración semántica.

~~Aunque pueda parecer contraintuitivo,~~ el texto plano carece completamente de estructura y, estrictamente hablando, contenido pues un computador es solo una larga cadena de caracteres ~~(incluyendo puntuación, espacios en blanco y saltos de línea, etc.)~~ en alguna codificación (UTF-8, ASCII, etc.) de algún alfabeto (latino, griego, cirílico, etc.). Somos nosotros quienes, cuando lo leemos, identificamos palabras ~~(en una o varias lenguas)~~, líneas, párrafos, ~~etc. Somos nosotros quienes identificamos asimismo~~ nombres de personas y de lugares, títulos de libros y artículos, fechas, ~~citas, epígrafes, referencias cruzadas (internas y externas),~~ notas a pie de página, etc. ~~y notas al final del texto~~. ~~Pero, de nuevo, el computador es completamente “ignorante” con respecto a dichas estructuras textuales en un texto plano sin procesar o codificar.~~

~~Sin asistencia humana (p. ej. por medio de codificación TEI) el computador no puede “entender” o detectar ninguna estructura semántica en el texto plano. Eso implica, entre otras cosas, que no podemos hacer búsquedas estructuradas sobre ese texto (de nombres de personas, lugares, fechas, etc.), ni podemos extraer y procesar sistemáticamente dicha información, sin antes haberle indicado al computador qué cadenas de caracteres corresponden a qué estructuras semánticas: este es un nombre propio de persona, aquel otro nombre de persona se refiere a la misma persona que este, este es un nombre de lugar, esta es una nota al margen hecha por una tercera persona, este párrafo pertenece a esta sección del texto, etc.~~ Codificar entonces el texto es indicar (por medio de etiquetas u otros recursos) que ciertas cadenas de texto plano tienen determinada significación. ~~Y esa es la diferencia entre texto plano y texto semánticamente estructurado.~~

Como con los tachones queda muy difícil la lectura, se reduce a esto: 

> Normalmente tenemos la imagen de un documento que hemos digitalizado previamente y, con ayuda de un software de [reconocimiento óptico de caracteres (OCR, en inglés)](https://es.wikipedia.org/wiki/Reconocimiento_óptico_de_caracteres), extraemos el texto contenido en ellas. Este texto es lo que suele llamarse [texto plano](https://www.ecured.cu/Texto_plano) (o texto digitalizado), es decir, texto sin formato alguno (sin cursivas, negritas, etc.) ni ninguna otra estructuración semántica.
> 
> El texto plano carece completamente de estructura y, estrictamente hablando, contenido pues un computador es solo una larga cadena de caracteres en alguna [codificación](https://es.wikipedia.org/wiki/Codificación_de_caracteres) ([UTF-8](https://es.wikipedia.org/wiki/UTF-8), [ASCII](https://es.wikipedia.org/wiki/ASCII), etc.) de algún alfabeto (latino, griego, cirílico, etc.). Somos nosotros quienes, cuando lo leemos, identificamos palabras, líneas, párrafos, nombres de personas y de lugares, títulos de libros y artículos, fechas, notas a pie de página, etc. Codificar el texto es, entonces, indicar (por medio de etiquetas u otros recursos) que ciertas cadenas de texto plano tienen determinada significación. 

Voy a por otro comentario.

**Comment by jenniferisasi** [comment]
Estos son las otras sugerencias del revisor. Aquí no puedo ofrecer tanta clarificación pero se reduce, siguiendo sus ejemplos si se quiere o pensando en otros: 

- [x] Reducir la sección de XML (párrafos a 37-82) para llegar antes a TEI. Se puede hacer uso de la estrategia presentada en el comentario anterior para reducir la sección, además de, si se puede, eliminar información indicando la consulta de otro recurso. 
- [x] Aclarar algo más el elemento de `<tei-header>`
- [ ] Esto sí es opcional: crear preguntas para el lector para crear "interactividad"

@nivaca quedo pendiente de tu parecer sobre estas sugerencias y disponible para aclarar alguna otra cuestión.

**Comment by nivaca** [comment]
@jenniferisasi 
Muchas gracias! No me quedó claro el segundo punto que anotas. ¿Puedes clarificarlo, por favor?

**Comment by jenniferisasi** [comment]
Disculpa @nivaca no había añadido la marca necesaria para "escapar" y que se viera el  `<tei-header>`

**Comment by nivaca** [comment]
@jenniferisasi, ¿hay alguna forma simple de ver los números de párrafo? La revisora los señala, pero no logro verlos fácilmente en el texto.... Gracias.

**Comment by jenniferisasi** [comment]
Sí, @nivaca, mira aparecen abajo a la derecha de cada párrafo en la vista previa: [http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei-1](http://programminghistorian.github.io/ph-submissions/es/lecciones/introduccion-a-tei-1)

**Comment by nivaca** [comment]
Gracias, @jenniferisasi, no conocía la vista previa.

**Comment by nivaca** [comment]
@jenniferisasi, ya introduje los cambios solicitados en la parte 1 de la lección. (También inclui una referencia bibliográfica adicional en la parte 2.)
Quedo pendiente de los comentarios. Gracias.

**Comment by jenniferisasi** [comment]
Gracias @nivaca. Yo misma le daré otra lectura a la lección en cuanto pueda, aunque estos días estoy a máxima capacidad de trabajo y puede que tarde un poco.

**Comment by jenniferisasi** [comment]
@nivaca llegué. He dado una vuelta final al [archivo de la lección](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/introduccion-a-tei-1.md) y queda así listo para su _copy editing_ si la editora jefa @rivaquiroga lo considera y si tenemos al editor disponible. ¡Gracias!

**Comment by rivaquiroga** [comment]
@jenniferisasi, @nivaca, ¡muchas gracias por todo el trabajo! Voy a consultar si es posible hacer el copyediting de esta lección. Apenas tenga novedades, les aviso

**Comment by nivaca** [comment]
Gracias @jenniferisasi @rivaquiroga. Quedo a la orden para lo que necesiten.

**Comment by rivaquiroga** [comment]
¡Hola! @jamotilla se encargará del copyediting :memo: 
@nivaca, José Antonio editará la lección en otra rama y luego pondremos aquí el link para compararla con esta. De ese modo con @jenniferisasi pueden ver las modificaciones y aprobarlas. Las sugerencias de cambios se basan en los lineamientos que aparecen en nuestra [Guía para autores](https://programminghistorian.org/es/guia-para-autores).

**Comment by nivaca** [comment]
@rivaquiroga Perfecto. Quedo pendiente.

**Comment by jamotilla** [comment]
Hola @rivaquiroga @jenniferisasi y @nivaca les comparto el link del proceso de copyedit que he realizado a partir de nuestra Guía para autores:
https://github.com/programminghistorian/ph-submissions/blob/copyedit-Introducci%C3%B3n-a-la-codificaci%C3%B3n-de-textos-en-TEI-(parte-1)/es/lecciones/introduccion-a-tei-1.md

@nivaca por favor revisa el vínculo de la línea 74: "así" / el cual hace referencia a "quijote.pdf". También pongo a tu consideración el uso de la expresión "de carne y hueso" (línea 116); es posible que el texto se vea mejor si utilizas un sinónimo. Por último, te pido por favor que revises que la bibliografía que refieres esté asentada mediante el el sistema de “Notas y Bibliografía” que se encuentra en el Manual Chicago 17a edición.
Saludos

**Comment by rivaquiroga** [comment]
@nivaca, aquí se puede ver la comparación de ambas ramas: https://github.com/programminghistorian/ph-submissions/compare/gh-pages...copyedit-Introducci%C3%B3n-a-la-codificaci%C3%B3n-de-textos-en-TEI-(parte-1)

**Comment by nivaca** [comment]
@jamotilla @rivaquiroga 

Gracias por tus correcciones y recomendaciones.

Tengo unas preguntas:

- Con respecto al vínculo a "quijote.pdf", está disponible en el directorio "assets" junto al resto de archivos vinculados: https://github.com/programminghistorian/ph-submissions/raw/gh-pages/assets/introduccion-a-tei/quijote.pdf En ese sentido no entiendo cuál es el problema.
- Con respecto a la línea 116, ya la corregí.
- Finalmente, con respecto a la bibliografía, no estoy muy seguro de cómo proceder. Como es una bibliografía recomendada y no son referencias en el texto principal, no deberían ir como notas al final. ¿Puedes sugerirme qué hacer?

Muchas gracias.
Nicolás

**Comment by jamotilla** [comment]
@nivaca te respondo:
1.- Perfecto, sólo quería que revisaras si "quijote.pdf" está colocado correctamente.
2.- Muy bien!
3.- Coincido, creo que las referencias son correctas

Ahora solo resta que compares ambas ramas para que nos indiques si hay algo que quieras cambiar. Si ya realizaste este proceso estamos listos para que @jenniferisasi de su visto bueno y puedan proceder.

**Comment by nivaca** [comment]
@jamotilla,
Gracias. Estoy de acuerdo con tu revisión, de modo que podemos proceder.
Mil gracias de nuevo.

**Comment by rivaquiroga** [comment]
¡Gracias a ambos! Una vez que @jenniferisasi dé su visto bueno, podemos incorporar los cambios de la rama del copyediting a esta.

**Comment by jenniferisasi** [comment]
¡Gracias por tu labor @jamotilla! Los cambios me parecen adecuados, así que @rivaquiroga cuando quieras puedes hacer ya los pasos para la publicación.

**Comment by rivaquiroga** [comment]
¡Buenísimo!
@nivaca, necesitaríamos dos cosas
1. Un breve abstract de la lección (una oración). Ese resumen es el que se visualiza cuando uno explora las lecciones: https://programminghistorian.org/es/lecciones/ Puedes revisar los de las lecciones publicadas para que te hagas una idea.
2. Una presentación tuya como autor, que es lo que irá en la sección "Acerca del autor" al final del tutorial. Suele ser una oración también. Por ejemplo, el que aparece en la lección que escribió Jennifer es: _Jennifer Isasi es Profesora asistente de investigación digital y Directora de la Iniciativa de Investigación Digital en Artes Liberales en Penn State, y doctora en Estudios Hispánicos._

Mientras tanto iniciaré las gestiones para obtener el DOI.

**Comment by nivaca** [comment]
@rivaquiroga 
¡Listo! Ya añadí lo que me pedías. Gracias.

PD. ¿Empezamos ahora con la parte 2?

**Comment by jenniferisasi** [comment]
Hola @nivaca tan pronto pueda, me pongo a crear el ticket para la segunda lección y buscar revisores.

**Comment by jenniferisasi** [comment]
@rivaquiroga la presentación del autor quedó en el .md de la lección ahora que lo veo. Como se tarda un poco publicar y también iniciar la edición, acabo de abrir ya el ticket para la segunda parte #386 Como hay un tercer tutorial en revisión y que, en nuestras mentes, parece una tercera parte excelente, #373, ¿qué hacemos para que sean serie? Me refiero a las pistas que se van dando en los tutoriales... (más allá de ponerlo 1/3, 2/3, 3/3 en YAML)

**Comment by rivaquiroga** [comment]
@jenniferisasi, buena pregunta. Cuando las tres lecciones estén ya publicadas, podríamos agregar al inicio y el final de ellas la mención a los otros tutoriales de la serie y cómo se relacionan. Por ahora a esta le agregué al final que la segunda parte estará próximamente disponible, en caso de que alguien la utilice antes de que salga la parte 2. 

:heavy_check_mark: Ya moví la presentación del autor a `ph_authors`.

Tres preguntas:
- ¿Los nombres de quienes hicieron la revisión son Rocío Méndez e Iñaki Cano? La cuenta de GitHub de Rocío no me aparece activa, así que estoy infiriendo el nombre de su usuario. 
- ¿Qué actividad y tópicos le quieren asignar a la sección?
- ¿Ya seleccionaste una imagen para la lección? ¿o prefieres que la elija yo?

**Comment by jenniferisasi** [comment]
Gracias @rivaquiroga 
1) te confirmo que los nombres son Rocío Méndez e [Iñaki Cano](https://scholar.google.com/citations?user=E2JmVSkAAAAJ&hl=es). 
2) De actividad yo creo que "transformar" (??? pero igual no) y luego "publicación digital" y "procesamiento de datos"?? Están complicados, no? Deberíamos tener una de "marcado de texto" porque es una palabra bien reconocida. 
3) De imágenes se me ocurre algo "con capas" y encontré esta https://www.flickr.com/photos/britishlibrary/11306417554/ Si te parece muy descabellada, se busca otra :)

**Comment by nivaca** [comment]
Hola @jenniferisasi 
En este caso son solo dos partes (1/2 y 2/2), por si acaso.

**Comment by jenniferisasi** [comment]
Sí, @nivaca, sabemos 😃 pero es que tenemos una lección también en revisión en #373 que va a casar perfecta para que sea la tercera parte.

**Comment by rivaquiroga** [comment]
¡Me gusta mucho la imagen! Hay capas y etiquetado.

**Comment by nivaca** [comment]
@jenniferisasi 
Sí, ya le leí y me pareció buena.

**Comment by rivaquiroga** [comment]
La lección ya se encuentra publicada en https://programminghistorian.org/es/lecciones/introduccion-a-tei-1 :tada: 
Muchas gracias @nivaca, @jenniferisasi, @RocioLMendez, @icanogar y @jamotilla por su trabajo.

Mañana en la mañana debería estar activo el DOI (nuestra activación de DOIs funciona en UTC+1)

@jenniferisasi, solo faltaría agregar la lección al bot de Twitter, una vez que el DOI esté activo

**Comment by rivaquiroga** [comment]
Fueron más rápidos de lo que tenía presupuestado: https://dx.doi.org/10.46430/phes0053 🚀

**Comment by nivaca** [comment]
¡Excelente! ¡Muchas gracias!

**Comment by nivaca** [comment]
¡Genial! Enhorabuena.

**Comment by jenniferisasi** [comment]
@nivaca tienes cuenta en Twitter?

**Comment by nivaca** [comment]
@jenniferisasi No tengo, lo siento.

**Comment by jenniferisasi** [comment]
Listo entonces, quedan añadidos los dos tweets que darán promoción a la lección en el bot de PH.

Queda así finalizada esta revisión y cierro ticket.
