### ISSUE TITLE
Relecture de traduction : Détecter la réutilisation de texte avec Passim

### ISSUE THREAD

**Issue by datalogism** [programminghistorian/ph-submissions#372]
Suite du ticket [#334](https://github.com/programminghistorian/ph-submissions/issues/334)

Le Programming Historian en français a reçu la traduction du tutoriel "[Detecting Text Reuse with Passim](https://programminghistorian.org/en/lessons/detecting-text-reuse-with-passim)" de Matteo Romanello et Simon Hengchen sous le titre de "Détecter la réutilisation de texte avec Passim" préparée par les soins de @faustusdotbe et @camaya28. Cette traduction est en cours de relecture et peut être consultée en preview ici : http://programminghistorian.github.io/ph-submissions//fr/traductions/detecter-la-reutilisation-de-texte-avec-passim.

Vous pouvez utiliser la numérotation des lignes fournie dans l'aperçu pour insérer vos commentaires, ou bien les numéros de paragraphe, si cela vous convient. Toutefois, sentez-vous libre de présenter votre relecture comme vous le jugez le mieux. Vous pouvez vous appuyez sur les consignes suivantes : https://programminghistorian.org/fr/consignes-traducteurs.

Je vais assurer le suivi éditorial de cette traduction et, dans ce cadre, j'ai sollicité une relecture auprès de @csuire01. Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle. J’annoncerai sur ce fil de discussions quand l’étape aura été atteinte puis je transmettrai au traducteur une synthèse des remarques afin qu’il puisse travailler sur la révision de son texte. Je coordonnerai les échanges qui auront lieu dans cet espace. Nous pouvons prévoir un délai d'un mois environ, ce qui nous mènerait au 6 juillet 2021. Ce délai peut néanmoins être adapté si besoin.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers [Hélène Huet](https://github.com/programminghistorian/ph-submissions/issues/hhuet@ufl.edu) si vous avez le sentiment qu'une médiation est nécessaire.
Politique contre le harcèlement

Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.
Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre médiatrice [Hélène Huet](https://github.com/programminghistorian/ph-submissions/issues/hhuet@ufl.edu). Merci de nous aider à créer un espace d’échange et de discussion sûr.
Licence de publication

@faustusdotbe et @camaya28, merci de confirmer par commentaire que, en tant que traducteur du tutoriel dont il est question dans ce ticket, vous cédez à ProgHist Ltd le droit de publier cette traduction sous licence CC-BY

**Comment by datalogism** [comment]
@faustusdotbe et @camaya28, Voici un modèle de texte ci-dessous:

Je [prénom, nom] traducteur cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier la traduction du tutoriel dont il est question dans ce ticket (y compris le résumé et des ressources supplémentaires) sous licence CC-BY.

**Comment by drvenabili** [comment]
Merci ! Je n'ai traduit qu'un paragraphe et le reste a été fait par @camaya28 , dès lors il serait plus juste de laisser cette dernière comme seule autrice de la traduction :-)

**Comment by datalogism** [comment]
C'est noté @faustusdotbe, j'attends donc seulement le retour de @camaya28  pour lancer la machine !
Nous fonctionerons ensuite comme suit:

   - @csuire01 proposera ses corrections
   -  je synthétiserai si besoin
   -  @camaya28 amendera le fichier en fonction des corrections suggérées si elle est d'accord, sachant qu'il aura la possibilité d'engager la discussion sur le fil avec le relecteur, si elle le souhaite
    - enfin, j'effectuerai les vérifications finales et lancerai la publication.

**Comment by camaya28** [comment]
Moi, Carla Amaya, traductrice cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier la traduction du tutoriel dont il est question dans ce ticket (y compris le résumé et des ressources supplémentaires) sous licence CC-BY.

**Comment by datalogism** [comment]
Super merci et échanté @camaya28,
@csuire01  je te laisse donc faire une première relecture, tu pourras ainsi faire part ici de tes remarques et corrections.
Je te rappelles que tu as jusqu'au 6 juillet, delais que l'on peux adapter si besoin.

**Comment by csuire01** [comment]
@datalogism, @camaya28 voici ma relecture de la traduction de ce tutoriel. Merci pour ce travail de traduction, j'ai trouvé l'ensemble clair et facile à suivre. La grande majorité des remarques ci-dessous concernent des coquilles, ou sont à interpréter comme des suggestions visant à faciliter la compréhension de certains passages. J'espère qu'elles seront utiles. 

La seule remarque qui s'applique à plusieurs endroits dans le texte est relative au mot "data" qui n'est pas toujours traduit en "données", je pense qu'il faut uniformiser. 

### Remarques spécifiques 

Voici mes suggestions, qui se fondent sur le numéro de paragraphe (à y repenser, le numéro de ligne aurait peut-être été plus pratique, je ferai mieux la prochaine fois) : 

- 3: "bash scripting" -> "l'usage du terminal bash" ou "programmation bash", ce qui n'est pas tout à fait la même chose, le tutoriel vers lequel sont renvoyés les lecteurs suggère plutôt qu'il s'agit de manipuler le terminal, plus que de "programmer" en bash. 
- 3: "Si vous souhaitez des tutoriels pour scripter en bash" -> "si vous souhaitez suivre des tutoriels sur l'utilisation du terminal bash" par exemple.
- 3: Le Programming Historian est mentionné deux fois dans la même phrase. 
- 3: "la library of current Python lessons", ne faut-il pas traduire ? Par exemple par "à la collection de tutoriels sur Python du Programming Historian" 
- 5: "attribution", en français plutôt "citation" ou "référence" appropriée
- 5: "Un autre exemple" ne parait pas nécessaire en début de phrase. 
- 5: il manque un "N" à synonyme. 
- 6: "comportent" doit être au singulier. Globalement cette phrase peut être améliorée, par exemple : "La liste ci-dessous présente une partie des outils qui permettent de détecter la réutilisation de texte". 
- 6: Le R textreuse package (R) rédigé par" -> Paquet textreuse (R) développé (ou écrit) par ... "Rédigé" s'applique plutôt au texte. 

- 7: La phrase qui commence par "Deuxièmement" me parait être traduite de manière trop littérale. Peut-être quelque chose comme : "Deuxièmement, bien que la documentation de Passim soit exhaustive et adaptée à ses usages avancés, un tutoriel pas-à-pas, centré sur les besoins des utilisateurs, serait bénéfique pour la communauté"
- 7: "Finalement" -> remplacer par "Enfin," et "illustrent de" -> supprimer "de" 

- 8: "Passim devient" -> "Passim est" 
- 8: "telle que mise en place dans Passim" -> "telle qu'elle est est mise en place dans Passim". Par ailleurs cette phrase est un peu longue, peut-être la couper en deux : "et produit ..." -> "Elle produit ..."
- 8: "et dépendra aussi de votre question de recherche" -> "dépendra beaucoup de votre question de recherche" (respecte mieux il me semble l'esprit de la phrase originale). 
- 8: "Par exemple, Passim peut regrouper" -> "Passim peut ainsi regrouper ..."
- 9: Je pense que je remplacerais de nouveau "script bash" par "terminal bash", voire "shell bash" ou "language bash".
- 9: "Pour apprendre" -> "Pour en apprendre"

- 10: Je ne sais pas s'il est d'usage de traduire "Jupyter notebook", je pense que l'on peut laisser notebook. 

- 10: "ou un environnement virtuel" je pense que le terme adapté ici est "machine virtuelle". Environnement virtuel est sujet à confusion avec les environnements virtuels python type virtualenv. 

- 12: `passim` est écrit de cette manière (format code), mais c'est la première fois. Sans doute faut-il harmoniser. 

- 13: "outil de construction", je pense que "outil de compilation interactif" convient mieux.

- 28 (commentaire): "votre temps varie", ici le terme de la version originale traite du chemin d'accès. Il manque également un "a" à "remplacer", un "d" à "ordinateur". 
- 30: "l’Interactive Build Tool" est traduisible par "outil de compilation interactif"
- 41: (Rien à voir avec la traduction mais si d'autres confirment, il faudra investiguer). Le script d'installation `build/sbt package` échoue sur ma machine (Linux), il ne peut pas télécharger sbt. Je n'ai pas eu le temps d'investiguer, la compilation manuelle par sbt fonctionne.
- 51: "der séries" -> "des séries" 

- 52: La légende de la figure n'est pas traduite

- 54: "illustre du" -> "illustre le" ?

- 63: "il se peut que vous désirez" -> "désiriez"

- 66: Je ne sais pas si "deviner" est vraiment un terme adéquat, "déduire" ou "inférer" conviennent mieux. 

- 67: "type de données longues" est une traduction littérale, à mon sens il faudrait traduire "type de données `long`". 

- 70: La description du paramètre `-o` n'est pas claire. 

- 72: "auprès de" -> "à partir de", "sur", ou encore "via Zenodo" ?

- 72: le lien n'est pas cliquable

- 75: "Sublime" -> "Sublime Text", cet excellent éditeur est également disponible pour Windows.

- 78: "Permet" à remplacer par "offre" ? Supprimer "error"

- 82: espace manquant après "expliquerons" 
- 87: "t" manquant à "constitue", cependant je pense que l'on peut remplacer "qui constitue" par "constituée d'une ... (année 1900)".

- 90: "Comme par exemple ..." -> "La chaine de commande ... nous permet par exemple de savoir ..."

- 92: "acheminer" je comprends pourquoi le mot pipe est traduit. Mais ce terme pipe désigne le caractère `|` indispensable à cette commande. Je pense donc qu'il faudrait le laisser en anglais, peut-être sous cette forme : "et ensuite acheminer, à l'aide d'un *pipe* (`|`), ce contenu dans ..."

- 93: Peut-être remplacer "exécuter" par "traiter", exécuter se prête plus à des programmes qu'à des données. 
 
- 100: "spécifier" -> "é"

- 109/110: Même remarque que plus haut sur la traduction de "Jupyter notebook". 

- 110: "l'impresso" -> les données de impresso ? Supprimer "respectives" et modifier "qui montrent" par "qui montrent respectivement".

**Comment by datalogism** [comment]
Merci @csuire01 pour ta relecture détaillée :) 
Je repprends donc tes remarques en y répondant si besoin, j'ajoute moi même les questions que je me suis posé à la lecture de cette traduction avec le symbole  :monocle_face:
Je demanderai ainsi un retour sur certains points à @spapastamkou, @mromanello, symbolisé avec un ❓ 
Je vous invites @csuire01 et @camaya28  à me faire votre retour concernant ce résumé de corrections si vous en avez.
Serai-t-il de te demander @camaya28  de relire ce tutoriel avec le recul de ces questions en tête ? Cela te permettra d'effectuer les corrections nécéssaires par la suite de manière plus efficace.

************************************************************************************************************************
# Remarques générales : 

* :question: Doit-on traduire toutes les citations ? Peut être est-il possible de jouer avec les notes de bas de pages pour traduire celles-ci ? [Comme indiqué ici](https://programminghistorian.org/fr/consignes-auteurs#notes-de-bas-de-page)
* :heavy_check_mark: Harmonisation du terme Data -> préférer l'usage de "données" ?
* :question: Une question personnelle que je me pose concerne la bibliographie, y a t-il une norme définie dans les consignes auteurs ?
@spapastamkou tu aurais quelques réponses à nous apporter sur ce sujet ?

# Corrections d'URL
Afin de liéer cette leçon aux contenus francophone peut-être doit-on envisager changer ces urls : 
*  https://programminghistorian.org/en/lessons/?topic=python >  https://programminghistorian.org/fr/lecons/?topic=python
* https://programminghistorian.org/en/lessons/introduction-and-installation > https://programminghistorian.org/fr/lecons/introduction-et-installation


# Coquilles et reformulations à envisager : 
* § 3 : 
.3.1.  :heavy_check_mark: _"bash scripting" -> "l'usage du terminal bash"_
3.2. :heavy_check_mark: _"Si vous souhaitez des tutoriels pour scripter en bash" -> "si vous souhaitez suivre des tutoriels sur l'utilisation du terminal bash"_
3.3. :heavy_check_mark:  _"Le Programming Historian est mentionné deux fois dans la même phrase. "_
:monocle_face: Je propose : 
 "Si vous souhaitez compléter vos connaissances concernant l'utilisation du bash et de python, référez vous aux tutoriels du Programming Historian suivants :"...
 3.4. :monocle_face: Je propose :  peut-être adapter les urls aux tutoriels français sur python 
 3.5.  :heavy_check_mark:  _"la library of current Python lessons", ne faut-il pas traduire ? Par exemple par "à la collection de tutoriels sur Python du Programming Historian"_
3.6. "Aucune connaissance préalable de la réutilisation de texte n’est requise, toutefois il" -> virgule entre _toutefois_ et _il_

* § 5 :
5.1.   :heavy_check_mark:  _"attribution", en français plutôt "citation" ou "référence" appropriée_
5.2.   :heavy_check_mark:  _"Un autre exemple" ne parait pas nécessaire en début de phrase._
5.3.   :heavy_check_mark: : _il manque un "N" à synonyme._

 * § 6 :
6.1. :heavy_check_mark:  _"comportent" doit être au singulier. Globalement cette phrase peut être améliorée, par exemple : "La liste ci-dessous présente une partie des outils qui permettent de détecter la réutilisation de texte"._
6.2.  :heavy_check_mark:  _Le R textreuse package (R) rédigé par" -> Paquet textreuse (R) développé (ou écrit) par ... "Rédigé" s'applique plutôt au texte._

* § 7 : 
7.1. :heavy_check_mark:  _"Finalement" -> remplacer par "Enfin," et "illustrent de" -> supprimer "de"_

* § 8 :
8.1. :monocle_face: Peut-être typographier : oeuvres -> œuvres
8.2. :monocle_face: Peut-être typographier : 17eme -> 17<sup>e</sup>
8.3. :heavy_check_mark:  _"Passim devient" -> "Passim est" _
8.4.  :heavy_check_mark:  _"telle que mise en place dans Passim" -> "telle qu'elle est est mise en place dans Passim". Par ailleurs cette phrase est un peu longue, peut-être la couper en deux : "et produit ..." -> "Elle produit ..."_
8.5.  :heavy_check_mark:  _"et dépendra aussi de votre question de recherche" -> "dépendra beaucoup de votre question de recherche" (respecte mieux il me semble l'esprit de la phrase originale)._
8.6. :heavy_check_mark:  _"Par exemple, Passim peut regrouper" -> "Passim peut ainsi regrouper ..."_

* §9 :
9.1. :heavy_check_mark:  _Je pense que je remplacerais de nouveau "script bash" par "terminal bash", voire "shell bash" ou "language bash"._
9.2. :heavy_check_mark:  _"Pour apprendre" -> "Pour en apprendre"_

* §10 :
10.1. :heavy_check_mark:  _Je ne sais pas s'il est d'usage de traduire "Jupyter notebook", je pense que l'on peut laisser notebook._
10.2. :heavy_check_mark:  _"ou un environnement virtuel" je pense que le terme adapté ici est "machine virtuelle". Environnement virtuel est sujet à confusion avec les environnements virtuels python type virtualenv._
*§12 : 
12.1. :heavy_check_mark:  _ passim est écrit de cette manière (format code), mais c'est la première fois. Sans doute faut-il harmoniser._

* §13 : 
13.1. :heavy_check_mark:  _"outil de construction", je pense que "outil de compilation interactif" convient mieux._

* §28 :
28.1. :heavy_check_mark:  _"votre temps varie", ici le terme de la version originale traite du chemin d'accès. Il manque également un "a" à "remplacer", un "d" à "ordinateur"._

* §30: 
30.1. :heavy_check_mark:  _"l’Interactive Build Tool" est traduisible par "outil de compilation interactif"_

* §35 : 
35.1. :monocle_face: "tiendra informer" > "tiendra informé"

* §38 : 
38.1. :monocle_face:  Extrayez les données binaires compressés -> "compressées"

* §41 : 
41.1.  :question: _Le script d'installation build/sbt package échoue sur ma machine (Linux), il ne peut pas télécharger sbt. Je n'ai pas eu le temps d'investiguer, la compilation manuelle par sbt fonctionne._
  :monocle_face:  As tu déjà eu vent de ce comportement @mromanello  ?
41.2. :monocle_face:  à reformuler ? "Si vous utilisez un autre type de distribution (Fedora, Gentoo, etc.), remplacez les commandes spécifiques à la distribution (par exemple apt) par celles utilisées par votre distribution spécifique."->"Si vous utilisez un autre type de distribution (Fedora, Gentoo, etc.), remplacez les commandes spécifiques à la distribution (par exemple apt) par celles que votre distribution impose."

* §50 :  
50.1. :monocle_face:  reformuler "La figure 1 donne une représentation schématique des données d’entrée et de sortie pour Passim" -> La figure 1 représente schématiquement les données d’entrée et de sortie fournies à Passim 

* §51: 
51.1.  :heavy_check_mark:  _"der séries" -> "des séries"_
51.2.  :monocle_face:   "ce qui constitue" est répété deux fois dans deuxx phrases qui se suivent, peut être reformuler la seconde occurence
51.3. :monocle_face:  " à un moment donné, qui requiert" >  " à un moment donné, ce qui requiert" 

* §52 : 
52.1. :heavy_check_mark:  _La légende de la figure n'est pas traduite_

* §54:  
54.1. :heavy_check_mark:  _"illustre du" -> "illustre le" ?_

* §63: 
63.1. :heavy_check_mark:  _"il se peut que vous désirez" -> "désiriez"_

* §66: 
66.1. :heavy_check_mark:  _Je ne sais pas si "deviner" est vraiment un terme adéquat, "déduire" ou "inférer" conviennent mieux._

* §67: 
67.1.  :question: "type de données longues" est une traduction littérale, à mon sens il faudrait traduire "type de données long". 
:monocle_face:   Je pense pour ma part qu'il ne faut tout simplement ne pas traduire ce terme et laisser "long" en le mettant en forme par exemple en _italique_

* §70: 
70.1. :heavy_check_mark:  _La description du paramètre -o n'est pas claire._
70.2.  :monocle_face: à reformuler "nous vous illustrerons" > nous illusterons ?
70.3.  :monocle_face: Dans le tableau "très bruyants" à peut-être remplacer par "bruité" /!\ plusieurs occurences à corriger
70.4. :monocle_face:  Dans le tableau petite erreure typographique : "Proportion, mesurée sur le passage le plus long, que deux  passages alignés différents du même document doivent se chevaucher pour  être regroupés,." -> supprimer la virgule à la fin


* §72: 
72.1.  :heavy_check_mark:  _"auprès de" -> "à partir de", "sur", ou encore "via Zenodo" ?_
72.2. : :heavy_check_mark:  _le lien n'est pas cliquable_ 
 :monocle_face: à formater sous la forme :  \[Texte\]\(URL\)
 
* §75: 
75.1.  :heavy_check_mark:  _"Sublime" -> "Sublime Text"_

* §76: 
76.1.  :monocle_face:  "par Passim et qui utilisé pour cette leçon" > "par Passim et qui est utilisé pour cette leçon"

* §78: 
78.1.  :heavy_check_mark:  _"Permet" à remplacer par "offre" _
78.2.  :heavy_check_mark:  _Supprimer "error"_
78.3.  :monocle_face:  "une ordinateur" > "un ordinateur"

* §82 :
82.1. :heavy_check_mark:  _espace manquant après "expliquerons"_

* §87: 
87.1. :heavy_check_mark:  _"t" manquant à "constitue", cependant je pense que l'on peut remplacer "qui constitue" par "constituée d'une ... (année 1900)"._

* §90: 
90.1. :heavy_check_mark:  _"Comme par exemple ..." -> "La chaine de commande ... nous permet par exemple de savoir ..."_

* §92: 
92.1. :heavy_check_mark:  _"acheminer" je comprends pourquoi le mot pipe est traduit. Mais ce terme pipe désigne le caractère | indispensable à cette commande. Je pense donc qu'il faudrait le laisser en anglais, peut-être sous cette forme : "et ensuite acheminer, à l'aide d'un pipe (|), ce contenu dans ..."_

* §93: 
93.1. :heavy_check_mark:  _Peut-être remplacer "exécuter" par "traiter", exécuter se prête plus à des programmes qu'à des données._

* §100: 
100.1. :heavy_check_mark:  _"spécifier" -> "é"_

* §101 : 
101.1. :monocle_face:  Peut-être reformuler "Une fois que Passim a fini de fonctionner" en "Une fois que le processus de Passim est terminé"
* §102 : 
102.1. :monocle_face:  "Dans la sortie JSON, chaque document correspond à un passage de réutilisation de texte. " > Ne devrait-on pas parler de dictionnaire plutot que de document ?

* §107 : 
107.1.  :monocle_face:  "y a plusieurs applications possible" > "y a plusieurs applications possibles"

* §108 : 
108.1.  :question:  Je pense qu'ici la phrase a été mal interprété, il ne s'agit pas du code même de Passim, mais seulement de ses résultats. 
"Le code qui “fait quelque chose” avec les données produites par Passim peut être écrit dans de nombreux langages de programmation différents" -> "Les données issues de Passim peuvent être ensuite réinvesties à travers d'autres langages de programmation, comme par exmple python."
108.2.  :monocle_face:  dédupliquer des documents > "dédoublonner des documents" ou "supprimer des doublons" est peut être plus adapté

* §109/110 : 
109.1. :heavy_check_mark:  _Même remarque que plus haut sur la traduction de "Jupyter notebook"._
109.2. :monocle_face:  "approfondir leur connaissances sur les données" > "approfondir leurs connaissances sur les données" ou "approfondir leur connaissance sur les données"

* §110:  :heavy_check_mark:  _"l'impresso" -> les données de impresso ? Supprimer "respectives" et modifier "qui montrent" par "qui montrent respectivement"._

**Comment by drvenabili** [comment]
Merci pour tout cela ! 

En vitesse pour §41 : en effet, le script télécharge depuis `https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/` (cf https://github.com/dasmiq/passim/blob/master/build/sbt-launch-lib.bash#L41) mais les releases ont été bougées sur Github (eg `https://github.com/sbt/sbt/releases/download/v1.3.13/sbt-1.3.13.zip` pour la 1.3.13 que mon système tente d'installer). Tout semble OK avec ces modifications (https://github.com/faustusdotbe/passim/blob/master/build/sbt-launch-lib.bash#L55), pour l'instant uniquement pour curl et pas wget.

Je vois deux solutions: 
- soit je fais un PR dans le repo original de passim et on attend que David Smith l'accepte, 
- soit nous éditons cette leçon, ainsi que l'originale en anglais, pour linker mon fork plutôt que le repo original. 

Je suis plus partant pour la solution numéro 1, mais celle dernière risque de prendre plus de temps. 

Qu'en pensez-vous ?

**Comment by mromanello** [comment]
Merci @datalogism aussi de mon côté ! 
Je vais regarder tout cela avec @camaya28 lundi prochain, et après on vous fera un retour. 

Concernant la remarque de @faustusdotbe, je serai aussi pour la solution numéro 1, car la 2, à mon avis, pose des soucis de synchronisation entre les repositories (original et son fork).

**Comment by spapastamkou** [comment]
Merci, @datalogism. Comme norme bibliographique, nous utilisons la Chicago Manual, 17e édition: https://www.chicagomanualofstyle.org/tools_citationguide/citation-guide-1.html 
Sinon, pour l'anglais dans le texte, oui, il faut traduire (par exemple, une citation en provenance d'une publication de Matteo dans le paragraphe 5, quitte à sortir le texte des guillemets pour en attribuer le sens en français). 
Pour info, les liens qui renvoient à d'autres pages du Programming Historian doivent être des liens relatifs, mais cela nous pouvons aussi le voir ensemble lorsque nous aurons la version corrigée par les auteurs.

**Comment by csuire01** [comment]
@faustusdotbe, @mromanello pour §41, la solution 1 me semble aussi préférable. Je ne suis pas un spécialiste de Scala, mais dans mon cas, l'installation de sbt et la compilation ont très bien fait l'affaire. Peut-être que ce cela pose des problèmes que j'ignore, mais pour palier, le temps que la PR soit acceptée, il est peut-être possible de mettre le lien vers la doc d'installation de sbt et donner la commande de compilation.

**Comment by drvenabili** [comment]
Entendu, je m'occupe de faire le PR ASAP, probablement avant ce lundi.

**Comment by drvenabili** [comment]
@csuire01 @datalogism @spapastamkou 

Le PR est merged, donc le problème du §41 est résolu. 🥳

**Comment by datalogism** [comment]
Super merci beaucoup  @faustusdotbe pour cette mise à jour bien arrangeante !
@mromanello et @camaya28 j'attends donc vos retours et on passera aux corrections.

**Comment by mromanello** [comment]
Bonjour @datalogism (et cc @faustusdotbe),

Je viens d'ouvrir une PR avec toutes les corrections faites par @camaya28, selon vos suggestions, sauf la suivante 
> 70.1. ✔️ La description du paramètre -o n'est pas claire.

En fait, je n'arrivais pas à voir comment pouvoir améliorer la clarté de cette description.

**Comment by datalogism** [comment]
Bonjour @mromanello  ! J'ai mergé le tout :) 
Derniers points de détails pour ma part :
- bien vérifier que les urls pointent vers les tutoriels rattachés en français si cela est possible
- typographier : oeuvres -> œuvres
- 17e -> 17e (cf. syntaxe Markdown ou copier/coller directement cela)
- j'ai un doute : Jupyter notebook ou notebook Jupyter ?
- "il se peut que vous désirez" -> "désiriez"

Vous avez du surement être face à ces corrections et avez peut être fait le choix de ne pas les appliquer pour une raison spécifique, si c'est le cas dites m'en plus à ce sujet !

Enfin @csuire01 n'hésites pas à nous faire part de tes éclairages concernant ta correction vis à vis de ce fameux paramètre -o :)

On en voit le bout ! 
Merci à tous pour vos travails et bel été à vous !

**Comment by mromanello** [comment]
Merci @datalogism !

- ✅ bien vérifier que les urls pointent vers les tutoriels rattachés en français si cela est possible
- ✅ typographier : oeuvres -> œuvres
- ✅ "il se peut que vous désirez" -> "désiriez

> j'ai un doute : Jupyter notebook ou notebook Jupyter ?

Pour coherence avec des autres leçons déjà publiées (p.e. cet [ici](https://programminghistorian.org/fr/lecons/introduction-aux-carnets-jupyter-notebooks)), j'ai préféré _carnet Jupyter_ (ça nous permet aussi de distinguer le carnet du logiciel "Jupyter Notebook"). 

> 17e -> 17e (cf. syntaxe Markdown ou copier/coller directement cela)

Je ne vois pas la difference entre les deux... Mais peut-être vouliez-vous dire "17e -> 17<sup>e</sup>" ?

**Comment by datalogism** [comment]
Merci, pour ma part je suis d'accord avec cette appellation "carnet Jupyter".
@mromanello  autant pour moi le copier/coller ne garde donc pas en mémoire la typographie pour 17e
On arrive donc à la fin de la revue de cette article, je serai absent les deux prochaines semaines, nous publierons le tout début septembre, si cela est ok @spapastamkou.
Belle fin d'été et merci à tous pour ce beau travail !

**Comment by spapastamkou** [comment]
Bien sûr, @datalogism, un grand merci pour tout ton travail avec les auteurs et la traductrice, que je remercie aussi de la part de toute l'équipe! Nous reprendrons le fil après les vacances et publierons à la rentrée. Encore merci à tous!

**Comment by mromanello** [comment]
Un grand merci à @camaya28 pour le travail de traduction, et à @datalogism @csuire01 pour les relectures et la coordination. Bonne vacances, et à la rentrée !

**Comment by csuire01** [comment]
Bonjour à tous et merci pour tout ce travail de correction et désolé de répondre tardivement. Je viens de relire le passage sur le paramètre -o et effectivement, difficile de faire mieux, avec l'explication on comprend très bien ce dont il s'agit. 
Bonne rentrée !

**Comment by spapastamkou** [comment]
@datalogism m'a fait savoir qu'il a terminé les vérifications éditoriales, je vais donc faire les dernières vérifications et lancer la mise en ligne de la traduction très prochainement. Il se peut que je pose des questions ponctuelles sur ce fil, si besoin de précisions. Merci à tous et toutes.

**Comment by spapastamkou** [comment]
Cher @mromanello, j'ai une question à propos d'une portion de texte dans la partie "Pour aller plus loin" (ici la prévisualisation: http://programminghistorian.github.io/ph-submissions//fr/traductions/detecter-la-reutilisation-de-texte-avec-passim#pour-aller-plus-loin). Je colle ci-dessous la portion de texte en question avec en gras une partie que je ne comprends pas trop s'il s'agit d'un oubli ou autre chose? Cela apparaît aussi dans la version en anglais du tutoriel, mais je préférerais être sûre avant de lancer le pull request pour la publication. Merci d'avance pour votre aide!  


textreuse

Vogler et al. (2020) utilisent le paquetage R textreuse **\cite{mullen2016}** pour étudier le phénomène de concentration des médias dans le journalisme contemporain

**Comment by mromanello** [comment]
Chère @spapastamkou,

Merci beaucoup ! C'était un typo que j'ai corrigé dans les deux versions (voir PR #392). La PR contient encore quelques petites modifications (surtout quelques problèmes d'installation signalés part un lecteur). Elle est maintenant en ligne (merged) avec les corrections que vous avez faites dans le branch principal ici. Mais c'est important de faire l'intégrer cette PR avant la publication de la traduction.

**Comment by spapastamkou** [comment]
Jai fini les dernières vérifications et ai intégré quelques corrections. 
@datalogism rdv au pull request sur jekyll:) 

@faustusdotbe @mromanello j'ai indexé ici le commit de modification de deux liens morts pour que vous soyez au courant et j'attendrai votre avis avant de fusionner le pull request:  
- dans l'introduction, dans la liste d'outils qui permettent de détecter la réutilisation de texte, il y avait cette phrase:  
"[MatchMaker](https://github.com/JSTOR-Labs/matchmaker) (Python) développé par les JSTOR Labs" 
**MAIS** => le repository n'existe plus et le lien renvoyait une erreur 404. 
J'ai trouvé néanmoins sur pypi.org cette page pour MatchMaker https://pypi.org/project/matchmaker/ (qui en outre contient un lien qui renvoie vers le repository matchmaker de l'utilisateur txels, alias Carles Barrobés basé à Barcelone). J'ai donc intégré ce lien-ci et, en plus, j'ai enlevé de votre texte la référence aux labs de JSTOR car il y a peut-être un souci d'attribution?     
- sinon, dans la partie "Installation de Passim", il y avait une erreur 404 pour le lien à télécharger Java 8 ( le lien était: https://www.oracle.com/ch-de/java/technologies/javase/javase-jdk8-downloads.html). Je l'ai remplacé avec le lien de la page de téléchargements du site web de Java, soit celui-ci: https://www.java.com/fr/download/ 

D'avance merci!

**Comment by datalogism** [comment]
Bonjour à tous !


La revue de cette traduction touche à sa fin, et celle-ci a été marquée par de nombreux en échanges à l'image de la richesse du contenu de ce tutoriel !


Il est coutume d'attendre que les derniers merges soient réalisés, mais nous avons de notre côté pris un peu (trop) d'avance, ce qui bon gré, mal gré a pour effet de rendre la leçon déjà disponible : https://programminghistorian.org/fr/lecons/detecter-la-reutilisation-de-texte-avec-passim.

Ne soyez donc pas surpris si vous voyez déjà passer sur Twitter un premier post du Programming Historian à ce sujet.


Ce n'est en soit pas très grave, car il ne s'agit là que de petits détails, @mromanello et @faustusdotbe n'oubliez cependant pas de nous faire part de vos retours concernant ce qu'a mentionné @spapastamkou, une fois votre retour fait, cela sera automatiquement intégré à la leçon.


La conversation n'est de part ce que j'ai mentionné plus haut pas clause, mais il, je tiens à tous vous remercier au nom de PH pour votre travail minitieux et consciencieux qui nous aura amené à travaillé 3 mois durant ensemble.


Un grand merci donc à @mromanello et @faustusdotbe pour votre réactivité et bien entendu pour votre contenu,

un tout aussi grand merci à @camaya28 pour cette traduction, qui par la longueur de son texte a dû s'avérer fastidieuse,

bien entendu, je remercie aussi sincèrement @csuire01 qui a accepté de m'aider pour réaliser cette relecture, j'espère que l'expérience ne t'as pas déplu !


Enfin, je remercie bien évidement @spapastamkou qui depuis les coulisses et pas que, a su prendre le temps de répondre aux nombreuses intérrogations ainsi que gérer l'intégration de cette leçon.


Belle semaine à tous !

**Comment by spapastamkou** [comment]
Je me permets juste d'apporter une petite précision: une petite confusion entre moi et @datalogism a fait que le pull request a été fusionné et la leçon mise en ligne avant d'avoir eu votre sentiment sur les questions des liens (et du texte) modifiés, @mromanello et @faustusdotbe. En revanche, il n'y aura pas dans l'immédiat de tweet signalant la parution, pour vous laisser le temps de prendre connaissance des modifications en question et donner votre aval ou sinon proposer des corrections. (Par la suite, il y aura régulièrement des tweets via notre bot, puisque @datalogism a bien fait son boulot et intégré les tweets, mais cela devrait démarrer plusieurs jours après la mise en ligne). Merci!

**Comment by csuire01** [comment]
@datalogism, ce fut un plaisir, merci à tous pour tout ce travail !

**Comment by mromanello** [comment]
Bonjour @csuire01 et @spapastamkou, 

Merci beaucoup pour votre travail éditorial sur cette traduction !

Pour ce qui concerne les liens : 
- tout bon pour le lien de la page de téléchargements du site web de Java ;
- par contre, la bibliothèque Python que vous avez trouvée, c'est pas le même logiciel que le MatchMaker de JSTOR Labs, qui a l'aire d'avoir bel et bien disparu de GH. Du coup, je vous propose d'enlever l'entrée du MatchMaker dès la liste, vu qu'il est non plus dispo en ligne. Si vous êtes d'accord (et bien sûr aussi @faustusdotbe) je vous laisserai faire cette petite modification dans les deux  versions, FR et EN.

**Comment by drvenabili** [comment]
Bonjour tout le monde,

Un grand merci à tout le monde ! Je suis 100% d'accord avec Matteo -- feu vert pour moi, pending le point 2.

**Comment by spapastamkou** [comment]
Tout est bon maintenant. @datalogism, merci pour ton travail!
