### ISSUE TITLE
Ticket de revisión: "Introducción a la publicación web de archivos TEI con CETEIcean"

### ISSUE THREAD

**Issue by JoshuaGOB** [programminghistorian/ph-submissions#373]
_Programming Historian en español_ ha recibido la siguiente propuesta de lección: "Introducción a la publicación web de archivos TEI con CETEIcean" por parte de Gabriel Calarco (@gabrielcalarco) y Gimena del Río Riande (@gimena). El editor de esta lección será @JoshuaGOB. Esta lección se encuentra en estos momentos en fase de revisión y puede leerse en:

**Vista previa**
https://programminghistorian.github.io/ph-submissions/es/lecciones/publicar-archivos-tei-ceteicean

**Archivo**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/lecciones/publicar-archivos-tei-ceteicean.md

**Imágenes**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/publicar-archivos-tei-ceteicean

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra *ombudperson*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamiento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by JoshuaGOB** [comment]
Saludos @gabrielcalarco y @Gimena 

Gracias por contribuir nuevamente con PH. Esta lección promete ser un excelente complemento a otras lecciones sobre TEI que se están trabajando ahora mismo. A continuación les envío unas correcciones y sugerencias principalmente sobre formato:

En general recomendaría romper dividir los párrafos para facilitar la lectura. En la mayoría bastaría una línea en blanco. Por favor también revisen el código para las imágenes para que siga el formato:

{% include figure.html filename="NOMBRE-ARCHIVO-IMAGEN" caption="PIE DE FOTO UTILIZANDO \"ESCAPED\" QUOTES" %}

El pie de foto debe describir brevemente el contenido de la imagen, ej. "Captura de pantalla mostrando opciones seleccionadas en Atom"

81 - Facilitaría la lectura organizar la información en una lista.
95 - vusalizar - visualizar
152 - Te en cuenta  - Ten en cuenta
192 - Aquí recomiendo incluir una explicación a modo de resumen, sin necesariamente entrar en la misma cantidad de detalle que en los párrafos anteriores, pero dejando una idea general de lo que cumple cada bloque. Pudieran, por ejemplo, describir los cuatro bloques a grandes rasgos: ej. El primer bloque verifica si hay una nota o no, el segundo bloque le añade un número a cada nota, y así con los siguientes. También se puede hacer directamente en el bloque con los comentarios entre /* y */ dependiendo la preferencia.

Pueden comenzar a hacer estas revisiones. Volveré a revisar la lección en unos días luego de verificar cómo las otras lecciones de TEI se compaginan con esta lección.

**Comment by gabrielcalarco** [comment]
¡Hola @JoshuaGOB!

Gracias por los comentarios. Ya estuvimos haciendo cambios en el archivo teniendo en cuenta lo que nos mencionás, pero no estoy autorizado para subirlos al repositorio. ¿Me pueden autorizar para hacer push desde mi usuario o hago un pull request?

¡Desde ya, muchas gracias!

**Comment by JoshuaGOB** [comment]
Saludos, @gabrielcalarco:

Disculpa la demora en responderte. Ya debes tener acceso para hacer los cambios. Me comentas si necesitas algo más por ahora. Puedo confirmarte que ya tengo una revisora y estoy buscando más.
¡Mil gracias!

**Comment by gabrielcalarco** [comment]
¡Perfecto! Ya pude subir las últimas modificaciones. 
Lo único que me falta es completar los comentarios explicando cada parte del código final para darle estilo a las notas. ¿Qué nos sugerirías poner en los dos últimos bloques?
¡Muchas gracias!
¡Saludos!

**Comment by JoshuaGOB** [comment]
Hola @gabrielcalarco 
Aquí me pillaste con lo poco que entiendo de Javascript. Presumí que por estar divido en bloques se pudiese resumir el propósito de todos por separado. A mí, por ejemplo, me aclararía saber qué se genera a partir de estos últimos dos aunque sea un resumen muy breve. Gracias!

**Comment by gabrielcalarco** [comment]
Hola @JoshuaGOB
Ya consultamos a la persona que escribió el código y nos explicó el funcionamiento de cada parte, así que ya incluí esa explicación (muy brevemente) en la lección.
Seguimos adelante con el proceso de revisión.
¡Muchas gracias!

**Comment by gabrielcalarco** [comment]
Hola @JoshuaGOB 
Te escribo para consultarte si hubo alguna novedad en el proceso de revisión de este tutorial. Si necesitan algo de nosotros, no tienen más que avisarnos.
¡Saludos!

**Comment by JoshuaGOB** [comment]
Saludos @gabrielcalarco 
Gracias por verificar. Estoy pendiente de una persona más para comenzar a hacer las revisiones.

**Comment by JoshuaGOB** [comment]
Hola,
Tengo el placer de presentar a @aldobarriente y @mj17g1, dos revisores que trabajan con PH por primera vez. Muchas gracias por su disposición. En caso de que tengan dudas, pueden escribirme directamente y consultar la [guía para revisores](https://programminghistorian.org/es/guia-para-revisores). La meta es tener ambas revisiones listas en las próximas dos semanas para que @gabrielcalarco tenga tiempo de clarificar si hiciese falta.

@gabrielcalarco Esperaremos los comentarios de ambas revisiones antes de hacer cualquier modificación a la lección.

**Comment by gabrielcalarco** [comment]
¡Hola @aldobarriente y @mj17g1, será un gusto trabajar con ustedes! 
Cualquier cosa que necesiten consultarnos nos escriben por aquí. 
¡Saludos!

**Comment by mj17g1** [comment]
Gracias por la introducción @JoshuaGOB ¡Un gusto conocerte, @gabrielcalarco! Le avisaré si necesito algo.

**Comment by mj17g1** [comment]
¡Hola a todos! 
Aquí está mi revisión, siguiente las pautas. Es mi primera vez revisando una lección en Github. Por favor avísenme si necesito aclarar algo. 

**Destinario**
Todo me parece estar escrito bien, y en forma fácil de leer.

**Traducciones**
•	¿El lenguaje (léxico, sintaxis, ortografía) es adecuado? si
•	¿Se traducen todos los tecnicismos al español? Si, donde se puede y es adecuado 
•	¿Los tecnicismos dudosos van acompañados del original inglés entre paréntesis? Si (ejemplo - CSS)
•	¿El traductor ha añadido notas aclaratorias? La lección incluye explicaciones de temas
•	¿Las capturas de pantalla y trozos de código han sido adaptados? Todas las capturas de pantalla se incluyen de manera adaptable 
•	¿Se han añadido referencias bibliográficas en español? La sección “references” incluye una para TTHub y otra para el programa creado CETEIcean. También está incluida una referencia a una lección para TEI y otra para JavaScript en español, pero se encuentran dentro del texto de la lección y no en la sección de “Referencias”. No se incluyen referencias para ATOM en español, pero no sé si están disponibles o si sería necesario. 

**Lecciones nuevas**
•	¿Hay pasos explicados en exceso? ¿Hay otros pasos, en cambio, que requieren mayor detalles? Si se encuentra en algunos de los pasos 2-4 información en exceso - información que no hizo falta para completar la lección pero que sí proporcionó una explicación y ayudo mejor entender cómo trabaja el código.
Paso 1 y 2 - pasos para donde incluir el script no están bien aclarados. Puede ser que no entendí bien como soy usuario novato. Me tomo un tiempo para estar segura de donde agregar el script 

**Preliminares**
•	¿Qué programas o lenguajes son necesarios? GitHub, ATOM
•	¿Qué habilidades se necesita conocer previamente? ¿Qué experiencia previa se necesita? Tener un entendimiento de cómo usar Github y ATOM conjuntamente. Como usuaria por primera vez no sabía que tenía que abrir el programa CETEIcean de Github en ATOM. Pensé que podía usar los documentos de Github en línea sin darme cuenta que tiene que estar abierto en mi computadora local usando ATOM. 
•	¿Qué datos se necesitan? ¿Son accesibles? El script de código y el texto que se usó de ejemplo - fueron proporcionados. 

**Estructura**
•	¿Los objetivos y las habilidades previas que se necesitan se exponen de manera clara al inicio del tutorial? La lección tiene aclarado en una nota que se debe saber XML-TEI para seguir esta lección en forma comprensiva. No tiene mencionado tener habilidades previas de cómo usar ATOM. Me imagino que es porque la lección incluye instrucciones de cómo usar esta función. 
•	¿Las habilidades derivadas del tutorial son útiles? Si 
•	¿Las capturas de pantalla y diagramas ilustran los pasos más importantes del tutorial? Si, pero algunas al principio causaron confusión. Paso 1 y 2 - pasos para donde incluir el script no están bien aclarados, y las capturas de pantalla solo incluyen el script y no enseñan como debe aparecer. También los documentos enlazados (los PNGs) no abren. 
•	¿Las secciones y títulos de sección son claros y guían al lector? Si

**Beneficios**
•	¿Se explica de manera clara por qué la herramienta o los métodos son útiles para investigar? Si 
•	¿Se sugiere cómo los conceptos (o un paso concreto) se pueden aplicar a otros casos concretos? Si

**Flujo de trabajo**
•	Si la lección tiene una extensión larga, ¿debería dividirse en otras más breves? No, se encuentra bien de manera que esta. 
•	Si se requiere un dataset, ¿está disponible en internet para descargar? Si, el texto que se usó como ejemplo está disponible

**Sostenibilidad**
•	¿La metodología o herramientas utilizadas en la lección están a la orden del día? ¿Están actualizadas? Si 
•	¿Qué fuentes o datos se utilizan? ¿Están incluidos de tal manera que no dependan de un alojamiento externo? Si - el texto que se usó está disponible 
•	¿Qué enlaces externos contiene la lección? ¿Estos recursos son actuales o existen otros, más recientes o apropiados, que se podrían vincular?
o	Introducción a la codificación de textos en TEI – tiene un tutorial
o	TEI / TTHub / JavaScript / ATOM y otras previsualizaciones de HTML como Jedit, Visual Studio, Oxygen / CETEIcean- tienen enlaces para páginas en línea 
o	HTML / XSLT / script – tienen enlaces para paginas en Wikipedia 
o	La Argentina manuscript – incluye el texto 

**Integrado a Programming Historian en español**
•	¿Existen enlaces adecuados que conectan la lección con otras semejantes o complementarias? Tienen al principio indicado que el usuario/a debe saber sobre TEI y ofrecen el enlace a la lección de PH para TEI en español incluida.

**Comment by gabrielcalarco** [comment]
¡Hola!
¡Muchas gracias @mj17g1  por la devolución! 
Vamos a revisar los pasos 1 y 2 para asegurarnos de que quede claro donde hay que colocar los scripts.
¡Saludos!

**Comment by aldobarriente** [comment]
Disculpa por la demora todos. Igual, ¡muchas gracias por la introducción @JoshuaGOB! ¡Y mucho gusto, @gabrielcalarco! Espero tener mi revisión lista antes del final del día de hoy.

**Comment by aldobarriente** [comment]
¡Aquí esta mi revisión de la lección! Igual como @mj17g1, es mi primera vez revisando una lección del PH, entonces díganme si necesito aclarar cualquiera cosa.

**Comentarios generales**
Me encanta esta lección. Como humanista digital, me parece que la lección se dirige a humanistas digitales que tienen dificultad con el uso de XSLT (tal como yo). Además, esta lección ayuda a humanistas digitales que tienen más experiencia con idiomas de codificación o back-end (como XML-TEI, Python, etc.) que con idiomas de visualización (como HTML, JavaScript) o intermediarios como XSLT.

Como introducción a mis comentarios, debo notar que mi experiencia es más con back-end y la codificación de textos, y entonces verán que mis comentarios hablan más sobre la interpretación y entendimiento del código para el lector.

Como notó @mj17g1, creo que después de los pasos donde se usan los elementos `<link>` y `<script>`, se debe mostrar cómo se ve el archivo al final. Se me hizo un poco difícil entender si estos elementos se ponen dentro o fuera del elemento `<head>` (párrafos 11 y 12). El archivo se actualiza en la imagen siguiente, pero el código solo aparece en el fondo.

Entonces, en general, creo que las muestras de código se pueden visualizar de otra manera para que el lector entienda mejor la estructura cambiante del código. En vez de sólo explicar que se agrega unas líneas de código entre otras líneas, tal vez puede agregar cómo se ve el archivo después de estos pasos usando la función de comentario en HTML: `<!-- -->`. Por ejemplo, después de los párrafos 11 y 12, se puede agregar: 
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!-- Líneas agregadas -->
<link rel="stylesheet" href="css/tei.css">
<script src="js/CETEI.js"></script>
<!-- Líneas agregadas -->
</head>
<body>
  
</body>
</html>
```
Con un color claro para las líneas que empiezan con `<!--`.

Otro pequeño comentario general: Dado el cambio y actualización constante de los editores, la lección se debe actualizar si Atom cambia la manera de hacer alguno de los pasos en la lección (agregar los plugins, crear un archivo nuevo, etc.).

**Comentarios específicos**
* Párrafo 1 y sección “Introducción y software que usaremos”: El autor debe notar que el lector escribirá un poco de CSS más tarde en la lección (como en el párrafo 23).
* Párrafo 5: Quizás se puede agregar el nombre del autor del plugin `atom-html-preview` (aunque se muestra en la imagen).
* Párrafos 10 y 11: El autor puede mencionar el nombre del archivo `index.html` antes que se muestra el código (porque algunos editores piden el nombre del archivo antes de crearlo).
* Párrafo 18: Se menciona un comando en la consola. Recomiendo usar un ejemplo con el comando `cd`, como `cd Documentos/tutorial_es` para que se aclare la sintaxis del comando.
* Párrafo 20: Cuando menciona los elementos de TEI que aparecen en el documento principal, quizás puede agregar un enlace a cada elemento de la lista hacia su página de TEI como referencia (y además el sitio TEI tiene las páginas en español). Por ejemplo, el elemento `<div>` tiene [su página](https://tei-c.org/release/doc/tei-p5-doc/es/html/ref-div.html).
* Párrafo 26: Quizás se puede agregar que el método `addBehaviors` ya viene incluido o escritó con un objeto CETEI (para aclarar que no es un método escritó en la lección).

**Comentarios pequeños (léxico, sintaxis, ortografía, etc.)**
* Párrafo 7: Jedit --> jEdit
* Párrafo 27: te en cuenta --> ten/tenga en cuenta 

Si tienen alguna duda con cualquier comentario, por favor díganme para aclarar. ¡Fue un placer poder leer y revisar su lección!

**Comment by gabrielcalarco** [comment]
¡Muchas gracias @aldobarriente por la devolución! 
Ya estamos avanzando en el proceso de revisión a partir de las sugerencias que fuimos recibiendo.
¡Saludos!

**Comment by gabrielcalarco** [comment]
Hola @JoshuaGOB , queríamos avisarte que ya terminamos de revisar la lección teniendo en cuenta las sugerencias que nos hicieron. Ya nos dirán como seguimos.
¡Saludos!

**Comment by rivaquiroga** [comment]
¡Hola, @JoshuaGOB! Tengo entendido que las sugerencias de ambos revisores ya fueron incorporadas. ¿Hay algo más que creas que sea necesario revisar? ¿O podemos hacer ya el copyediting de la lección?

**Comment by JoshuaGOB** [comment]
Hola @rivaquiroga. En efecto está todo incorporado y vuelto a revisar por mí. Estoy buscando la imagen y pensé que quizás algunas de las que utilizan @hdcaicyt [aquí](http://hdlab.space/La-Argentina-Manuscrita/pueblos-originarios/) u otras similares pudieran ser buena opción.

**Comment by rivaquiroga** [comment]
Excelente! @jamotilla se encargará del copyediting. Trabajará en otra rama de este repositorio para que puedan revisar sus sugerencias antes de incorporarlas a la versión final de la lección.

**Comment by jamotilla** [comment]
Hola a todas y todos. Les pido por favor revisen las sugerencias sobre el texto. Pueden comparar las dos versiones en el siguiente vínculo:
https://github.com/programminghistorian/ph-submissions/compare/Copyedit-publicar-archivos-tei-ceteicean
Quedo atento a sus comentarios. Saludos, J A

**Comment by gabrielcalarco** [comment]
¡Hola a todxs! Queríamos avisarles que ya revisamos las sugerencias de @jamotilla  y encontramos todo perfecto. 
Seguimos adelante, ¡muchas gracias! 
¡Saludos!

**Comment by rivaquiroga** [comment]
Muchas gracias, @jamotilla! 
@JoshuaGOB, quedo atenta a que me avises si ya está todo listo para publicar.

**Comment by JoshuaGOB** [comment]
¡Gracias @jamotilla!  

@rivaquiroga entiendo que estamos a falta del bio de @gabrielcalarco y @Gimena, la imagen y el doi.

1. [Texto de lección](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/publicar-archivos-tei-ceteicean.md)
2. [Imágenes](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/publicar-archivos-tei-ceteicean)

**Comment by Gimena** [comment]
Algo así? Gimena del Rio Riande es investigadora adjunta del Instituto de Investigaciones Bibliográficas y Crítica Textual (IIBICRIT, CONICET) y directora del laboratorio de Humanidades Digitales de CAICYT (CONICET, Argentina). Es directora de la Diplomatura en Humanidades Digitales (UCES), co-directora del master en Humanidades Digitales (UNED,), directora de la Revista de Humanidades Digitales (RHD) y presidenta de la Asociación Argentina de Humanidades Digitales (AAHD).

**Comment by rivaquiroga** [comment]
Exacto, @JoshuaGOB. Del DOI me encargo yo.

**Comment by gabrielcalarco** [comment]
Aquí les dejo la mía:

Gabriel Calarco es Licenciado en Letras por la Universidad de Buenos Aires (UBA) y se encuentra cursando el doctorado en Literatura en la misma universidad como becario del Instituto de Investigaciones Bibliográficas y Crítica Textual (IIBICRIT-CONICET). También se desempeña como docente en la Diplomatura de Humanidades Digitales (UCES) y como profesor de Literatura en el Nivel Medio.

**Comment by rivaquiroga** [comment]
@JoshuaGOB, creo que solo falta que selecciones la imagen para la lección. Una vez que eso esté listo empiezo el proceso de publicación.

**Comment by JoshuaGOB** [comment]
@rivaquiroga listo

Estoy pendiente al doi para añadir los mensaje en el bot y pedir las traducciones necesarias. 
Aquí la [imagen original](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/gallery/originals/publicar-archivos-tei-ceteicean-original.png) y la [imagen editada](https://github.com/programminghistorian/ph-submissions/blob/821616c5a0c3bdf91b4733748434b73bf7286aec/gallery/publicar-archivos-tei-ceteicean.png)

**Comment by rivaquiroga** [comment]
@JoshuaGOB, gracias! 
El doi queda activo una vez que la lección quede publicada. Avisaré por acá cuando suceda.
No hay nada que traducir aún. La bio de los autores solo se agrega en otros idiomas cuando la lección se traduce.

**Comment by rivaquiroga** [comment]
¡Hola! La lección puede previsualizarse en este enlace: https://deploy-preview-2440--ph-preview.netlify.app/es/lecciones/publicar-archivos-tei-ceteicean
@JoshuaGOB, solo faltaría que apruebes el PR para poder publicar.

**Comment by JoshuaGOB** [comment]
Hola ya está aprobado el pull request, @rivaquiroga 

Estoy viajando ahora mismo pero pendiente al resto. Gracias.

**Comment by rivaquiroga** [comment]
El DOI ya está activo: https://dx.doi.org/10.46430/phes0056
¡Muchas gracias a todas las personas que participaron en el proceso! En un par de meses pasamos de cero a tres lecciones sobre TEI 🎉✨
@JoshuaGOB, solo quedaría anunciar la lección en Twitter y agregarla al bot. 
¡Felicitaciones!

**Comment by JoshuaGOB** [comment]
¡Felicidades y muchísimas gracias a @gabrielcalarco, @Gimena, @aldobarriente, @mj17g1 y @jamotilla por su trabajo!

Como dice @rivaquiroga, esta lección complementa otras dos excelentes lecciones de TEI y será un recurso valiosísimo.

¡Enhorabuena!

**Comment by rivaquiroga** [comment]
Creo que ya estamos en condiciones de cerrar este ticket. ¡Muchas gracias por todo el trabajo!
