### ISSUE TITLE
Tradução da lição "Sentiment Analysis for Exploratory Data Analysis"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#375]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Sentiment Analysis for Exploratory Data Analysis ' por @caiocmello. A lição a traduzir está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/analise-sentimento-exploracao-dados.md).

O editor para esta tradução vai ser o @josircg. Obrigado pela disponibilidade Josir!

Para promover uma publicação rápida desta lição traduzida, o Josir irá procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação do tradutor, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by josircg** [comment]
O primeiro revisor será o Bruno Ponne. Já inclui ele na issue e passei o link das diretrizes para o revisor:

https://programminghistorian.org/pt/directrizes-revisor

**Comment by bruno-ponne** [comment]
Olá Caio! Parabéns pela ótima tradução da lição "Sentiment Analysis for Exploratory Data Analysis". Eu fiz a revisão da tradução e testei o código e consegui entender todas as etapas. Abaixo eu faço algumas sugestões que você pode analisar e decidir se acha conveniente alterar. A recomendação de evitar o pronome "você" e preferir a contração "num (em + um)" eu recebi de colegas e revisores em outra tradução em que trabalhei há alguns meses. Qualquer dúvida, fico à disposição. Um abraço.

- [x] Em vários pontos do texto, é utilizado o pronome “você”. Sempre que possível optar por um discurso mais impessoal usando o infinitivo e evitando a utilização do “você”. Ex.: Linha 37: Substituir “Se você não tem experiência com Python ou programação” por “Caso não tenha experiência com Python ou programação”;
- [x] Linha 46: substituir “em um conjunto de dados” por “num conjunto de dados”;
- [x] Linha 50: substituir “análise de dados exploratória” por “análise exploratória de dados” para manter a consistência com as outras ocorrências da expressão;
- [x] Linha 56: substituir “de que algo pode valer a pena investigar mais a fundo” por “de que pode valer a pena investigar algo mais a fundo.”;
- [x] Linha 58: substituir “da PLN” por “do PLN”;
- [x] Linha 58: substituir “em um texto” por “num texto” (duas ocorrências);
- [x] Linha 58: formatar “grau de positividade” e “grau de negatividade” em itálico na primeira vez em que aparecem, como no original;
- [x] Linha 83: substituir “mas você pode achar interessante revisar outras lições de Python no Programming Historian” por “mas pode ser conveniente revisar outras lições de Python no Programming Historian”;
- [x] Linha 90: substituir “Para continuar, você precisará instalar o seguinte:” por “Para continuar, as seguintes instalações são necessárias:”;
- [x] Linha 97: fechar o parêntese: “(também conhecido como uma biblioteca Python)”;
- [x] Linha 127: substituir “emoções expressas nos e-mail profissionais” por “emoções expressas nos e-mails profissionais”;
- [x] Linha 191: substituir “Isso significa que um dicionário como pontuações pode armazenar muitos `pares de valores-chave`” por “Isso significa que um dicionário como *scores* pode armazenar muitos `pares de valores-chave`.”;
- [x] Linha 198: no código ficou faltando o for loop: “for key in sorted(scores):”;
- [x] Linha 340: no trecho “a mensagem é principalmente neural (neu: 0,765)” eu acredito que o autor quis dizer “neutral”. Pesquisei na Internet e encontrei esse post: https://stackoverflow.com/questions/40325980/how-is-the-vader-compound-polarity-score-calculated-in-python-nltk

**Comment by caiocmello** [comment]
Olá Bruno!

Fantástico. Muito obrigado pela revisão cuidadosa e detalhada. A forma como você organizou os tópicos será muito útil pra que eu possa fazer as modificações necessárias e melhorar este trabalho.

Muito obrigado pela sua contribuição,
Caio

**Comment by DanielAlvesLABDH** [comment]
Caro @bruno-ponne, muito obrigado pela cuidada revisão. Uma excelente ajuda. Se for necessário algo @caiocmello é só dizer!

**Comment by caiocmello** [comment]
@DanielAlvesLABDH Obrigado Daniel. Acabei de fazer as correções sugeridas por Bruno. Eu optei, por enquanto, por não substituir todos os pronomes "você" por formas impessoais. Eu modifiquei alguns, de acordo com as sugestões pra evitar excessos de repetições. Mas acredito que em alguns casos, manter "você" ajuda a dar ao texto o tom informal e de "conversa" que a autora pareceu querer imprimir no original.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @bruno-ponne! Vamos então aguardar pela segunda revisão a indicar pelo @josircg, mas acredito que essa possa ser uma boa solução, um bom equilíbrio.

**Comment by josircg** [comment]
Boa tarde pessoal. Só como feedback: não consegui ainda uma viv'alma que tenha a disponibilidade de realizar a segunda revisão.

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg temos novidades nesta revisão?

**Comment by josircg** [comment]
Oi @DanielAlvesLABDH o segundo revisor (Ian Araujo) já foi incluído na issue e já enviei as diretrizes de revisão para ele por email. Agora é aguardar ele realizar a revisão.

**Comment by DanielAlvesLABDH** [comment]
Obrigado Josir! Seja bem vindo @ianaraujo e muito obrigado por ter aceite fazer esta revisão. Abraço

**Comment by ianaraujo** [comment]
Olá @DanielAlvesLABDH  @josircg, já estou trabalhando na segunda revisão. Uma dúvida: já levo em consideração as sugestões feitas pelo @bruno-ponne ? Obrigado.

**Comment by ianaraujo** [comment]
Olá @DanielAlvesLABDH @josircg , obrigado por me incluírem na revisão da lição. Estou trabalhando nisso e em breve apresento minhas sugestões e meu parecer. Abraço.

**Comment by DanielAlvesLABDH** [comment]
Olá a todos! Já temos novidades sobre a revisão desta tradução? Um abraço

**Comment by ianaraujo** [comment]
@caiocmello, parabéns pelo trabalho feito na tradução da lição. Consegui rodar o código, que está muito bem documentado, sem problemas. Nada na lição compromete a experiência do aluno/leitor. Todos os comentários dizem respeito a questões pequenas. Para além do comentado pelo colega @bruno-ponne, faço algumas sugestões: 

- [x] Linha 37: Substituir "você será capaz de" por "você terá o conhecimento necessário para";
- [x] Linha 40: Talvez " gerar dados de sentimento" confunda o leitor. Eu utilizaria "atribuir medidas de sentimento" ou "gerar medidas de sentimento" mesmo;
- [x] Linha 46: Substituir "As análises exploratórias de dados são estratégias" por "A análise exploratória de dados é um conjunto de estratégias";
- [ ] Linha 58: Substituir "transmita" por "transmite";
- [x] Linha 58: Em vez de "fornece um mecanismo de caracterizar as emoções", eu optaria por uma tradução mais literal como "fornece meios de caracterizar as emoções";
- [x] Linha 64: Adicionar vírgulas antes e depois de "objetos de seu estudo";
- [x] Linha 66: Substituir "permitir que o pesquisador conduza" por "permitir que o pesquisador realize";
- [x] Linha 76: Substituir o primeiro "e" por uma vírgula em "crise organizacional **e** insularidade e formação de comunidade.";
- [x] Linha 76: Substituir "mas não é tão simples" por "mas requer uma discussão metodológica significativa". As duas opções fogem de uma tradução mais literal, no entanto, acredito que a segunda se aproxima mais da ideia que a autora quis expressar;
- [x] Linha 86: Acredito que "medidas de sentimento" ou "indicadores de sentimento" sejam expressões mais compreensíveis do que "pontuações de sentimento". É uma tradução complicada mesmo... Essa sugestão é válida para toda a lição;
- [x] Linha 123: Substituir "ferramenta de intensidade de sentimento" por "ferramenta de atribuição intensidade de sentimento";
- [x] Linha 127: Não sei se a expressão "quebrando a cabeça" é compartilhada entre os demais países de língua portuguesa. Para não restar dúvida, talvez fosse melhor utilizar "encontrando limitações" ou algo nessa linha;
- [x] Linha 147: Substituir "..." por "[...]";
- [ ] Linha 158: Ao definir o que são classes talvez fosse bom utilizar a palavra "elemento" ou "modelo" ao invés de "esquema". A palavra "esquema" me deixou um pouco em dúvida. Ao ler, sem muito contato com linguagem, não ficou claro o que são esses "esquemas". É realmente complicado traduzir blueprint...;
- [x] Linha 191: Neste caso, acredito que a palavra "pontuação", em itálico, fazendo referência à variável *score*, tenha sido bem utilizada;
- [x] Linha 276: "Embora seja útil saber em teoria, como esse método pode ser aplicado aos dados no exemplo da Enron - a saber, uma coleção de dados de e-mail e metadados?". A redação da frase me pareceu confusa. Sugiro substituir "a saber" por "isto é";
- [x] Linha 415: Sugiro aportuguesar a palavra "tokenizer" para "tokenizador" e editar a palavra "english.pickle" colocando-a em itálico;

Reforço a qualidade do trabalho realizado pelo @caiocmello e peço desculpas por atrasar o processo de publicação da tradução pela demora na revisão.

Abraço a todos.

**Comment by caiocmello** [comment]
Caro @ianaraujo,

Agradeço imensamente suas contribuições para a tradução desta lição. Obrigado pelo olhar minucioso com o texto. Todas as modificações sugeridas já foram incorporadas ao texto. Exceto:

- [ ] Linha 58: Substituir "transmita" por "transmite"; (Nesta, estou em dúvida. Achei correto usar a forma do conjuntivo, mas não tenho certeza se deveria usar 'transmite'). PS: Alguem pode ajudar nessa questão de lingua portuguesa? 

- [ ] Linha 158: Ao definir o que são classes talvez fosse bom utilizar a palavra "elemento" ou "modelo" ao invés de "esquema". A palavra "esquema" me deixou um pouco em dúvida. Ao ler, sem muito contato com linguagem, não ficou claro o que são esses "esquemas". É realmente complicado traduzir blueprint...; (Realmente é muio dificil traduzir blueprint. Concordo que 'esquema' não seja uma opção perfeita, mas não acho que 'elemento' ou 'modelo' seja melhor nesse sentido. Caso o editor ou alguem queira sugerir ou mudar, estou aberto). 

Muito obrigado novamente pela excelente revisão.

Atenciosamente,
Caio

**Comment by caiocmello** [comment]
@DanielAlvesLABDH @josircg Todas as modificações sugeridas pelos revisores foram incorporadas ao texto.

**Comment by josircg** [comment]
Meus 2 centavos sobre o "esquema": concordo que "esquema" não seria o melhor termo. "Modelo" seria um termo melhor realmente pois não fica ambigua em relação a outras construções da linguagem.

Sobre o "transmite" realmente não sei qual seria a melhor opção. Talvez "procura transmitir".

**Comment by bruno-ponne** [comment]
@ianaraujo, muito boa revisão! 

@caiocmello, concordo que a tradução de "blueprint" não é simples. Esse material da Unicamp utiliza o termo "gabarito" para descrever uma classe: https://www.dca.fee.unicamp.br/cursos/PooJava/classes/conceito.html. Eu optaria por "modelo", "padrão" ou "gabarito".

Sobre o subjuntivo, eu li essa publicação: https://ciberduvidas.iscte-iul.pt/consultorio/perguntas/tempos-verbais-presente-futuro-e-conjuntivosubjuntivo/5220 mas confesso que não consegui aplicar a regra, pois há várias orações no nosso caso. Em resumo, eu entendi que os dois modos são gramaticalmente corretos, mas o subjuntivo destaca o caráter incerto daquela afirmação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos pelo trabalho de tradução e revisão. Está a ficar muito bom! 
Quanto à questão da linha 58, do uso de "transmite" ou "transmita", a opção correcta no contexto geral da frase é "transmite".
Em relação à linha 158, eu concordo em parte com o Bruno e o Caio. Acho que "esquema" não resolve e "modelo" ou "esboço" ficariam melhor. Talvez assim: "*SentimentIntensityAnalyzer* é uma `classe`, que é um “modelo” que instrui o Python a construir um `objeto` com um conjunto especial de `funções` e `variáveis`. No nosso caso, queremos construir um único `objeto`: nosso analisador de sentimento, que segue este “modelo”." Com "esboço" também não fica mal...

**Comment by caiocmello** [comment]
Obrigado @DanielAlvesLABDH @josircg @bruno-ponne @ianaraujo. Fiz todas as modificações recomendadas diretamente no texto. Se precisar de algo mais, estou à disposição. 
Abraços, 
Caio

**Comment by DanielAlvesLABDH** [comment]
Caros @caiocmello, @josircg, @bruno-ponne e @ianaraujo, as minhas desculpas pelo atraso em finalizar esta revisão. Têm sido muitas coisas e pelo meio acabei por esquecer esta! Estou agora a procurar publicar. Fiz algumas correcções no ficheiro da tradução, mais de formatação no cabeçalho e secção final. Contudo tenho uma dúvida para o Caio e o Josir. Na linha 132 é afirmado "Nas notas do tradutor, ao final dessa lição, você encontra mais dicas de tradução automática utlizando Python." Além de faltar ali um "i", eu procurei no final e não encontrei essas "notas do tradutor". Foi esquecimento? Decidiram não colocar e então devemos apagar esta frase? Obrigado a todos pelo trabalho excelente. Vamos ter mais uma lição publicada brevemente!

**Comment by caiocmello** [comment]
Caro @DanielAlvesLABDH, acho que esqueci de deletar a linha 132. Inicialmente, eu tinha planejado dar dicas de como fazer tradução automática dos textos do português para o inglês ao final da lição. Mas após nossa discussão, decidimos apenas incluir a nota no resumo da lição, informando aos leitores que os exemplos estariam na lingua original. Portanto, essa linha deve ser deletada.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @caiocmello. Sendo assim vou corrigir essa linha e iniciar o processo de publicação!

**Comment by DanielAlvesLABDH** [comment]
Mudei o ficheiro para a pasta correcta e corrigi o link no primeiro comentário do ticket

**Comment by bruno-ponne** [comment]
Parabéns @caiocmello pela ótima tradução! : )

**Comment by DanielAlvesLABDH** [comment]
Olá @caiocmello e @josircg! Na publicação da lição, dá uma mensagem de erro por não constar o ficheiro de imagem: tabelasentimento.jpg
Eu não tinha reparado que o Caio tinha alterado a imagem da lição. Josir, você fez o upload da imagem para o GitHub? Pode fazer isso para a pasta https://github.com/programminghistorian/jekyll/tree/gh-pages/images/sentiment-analysis renomeando a imagem para "analise-sentimento1.jpg" e associando isso ao branch https://github.com/programminghistorian/jekyll/tree/Publicar_analise-sentimento-exploracao-dados ? Obrigado

**Comment by caiocmello** [comment]
![analise-sentimento1](https://user-images.githubusercontent.com/68293475/143072061-0de4e067-928b-43cf-a7a3-e1161a4699c5.png)
 @josircg esta foi minha proposta de tradução para a tabela mencionada por @DanielAlvesLABDH

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @caiocmello. Já fiz o upload da imagem. Espero que agora consiga publicar...

**Comment by DanielAlvesLABDH** [comment]
Caros, a lição já está publicada! Parabéns e obrigado a todos por mais uma tradução excelente! @josircg falta apenas actualizar a planilha do Twitter com o DOI https://doi.org/10.46430/phpt0017 e depois encerrar o ticket. Obrigado

**Comment by josircg** [comment]
Oi Daniel, ainda não aparece no site e o DOI ainda não está registrado. Acho que tem que esperar algumas horas para que seja feito o deploy. Mas pode deixar que eu atualizo a planilha.

**Comment by DanielAlvesLABDH** [comment]
No site aparece https://programminghistorian.org/pt/licoes/analise-sentimento-exploracao-dados, no DOI só daqui a pouco quando os colegas da Biblioteca de Sussex actualizarem o registo no crossref
