### ISSUE TITLE
Tradução da lição "Installing Omeka"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#377]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Installing Omeka' por @GabrielaKucuruza. A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/instalar-omeka.md). Muito obrigado Gabriela!

Aqui pode ser verificada uma visualização prévia da página: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/instalar-omeka

O editor para esta tradução vou ser eu, Daniel Alves.

A @daniellesanchesDH, a @joanacvp e a @Msaguedes aceitaram ficar como revisoras desta tradução.

Peço que além da tradução para português, procurem verificar se a lição precisa de alguma actualização. Por favor, deixem as vossas sugestões na caixa de comentários deste ticket, de forma que a Gabriela possa acompanhar e responder. 

Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.

Política anti-assédio
_

Esta é uma declaração de princípios do *Programming Historian em português* e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.

O *Programming Historian em português* dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque *ad hominem* a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by GabrielaKucuruza** [comment]
Eu quem agradeço, professor Daniel! Qualquer coisa, estou a disposição!

**Comment by joanacvp** [comment]
Olá, boa tarde. Óptimo trabalho @GabrielaKucuruza. Deixo, abaixo, as minhas propostas de alteração: 

- [ ] Linha 35 – em “nessa lição (en)” colocar o nome da lição e acrescentar depois “(em inglês)” em vez de “(EN)”, de forma a ficar igual a outras lições e até ao que tem abaixo nesta
- [ ] Linha 35 – substituir “se iniciando” por “que se estão a iniciar”
- [ ] Linha 35 - substituir “para que se queira” por “para que queira”
- [ ] Linha 35 – substituir “Algumas das razões são:” por “, nomeadamente:”
- [ ] Linha 36 –  substituir “assim que elas são liberadas” por “assim que é disponibilizada”
- [ ] Linha 36 – substituir “sem precisar esperar pelo Omeka.net atualizar o seu sistema” por “sem precisar de esperar que o Omeka.net atualize o sistema”
- [ ] Linha 37 – substituir “ofertados” por “oferecidos”
- [ ] Linhas 38 e 38 – retirar a vírgula antes dos “e”
- [ ] Linha 40 – verificar como vamos fazer relativamente ao valor de 5 dólares. Convertemos @DanielAlvesLABDH ? Falta ainda o ponto final no final da frase
- [ ] Linha 41 – substituir “agora oferecem” por “oferecem agora”.
- [ ] Linha 43 – substituir “linha de comando” por “linha de comandos”. Fazer a mesma substituição noutras partes da lição (por exemplo, aparece mais do que uma vez na linha 43 e não está sempre escrito da mesma forma).
- [ ] Linha 43 – substituir “Esse tutorial não demanda” por “Este tutorial não precisa de”
- [ ] Linha 43 – substituir “(EN)” por “(em inglês)”
- [ ] Linha 43 – “instalações de um-clique” será mesmo o termo certo em português?
- [ ] Linha 43 – substituir “através de seus” por “através dos seus”
- [ ] Linha 43 – substituir “o jeito” por “a maneira”
- [ ] Linha 43 – substituir “mas ele te dará” por “mas ele dar-te-á”
- [ ] Linha 43 – substituir “deve tomar” por “deve demorar”
- [ ] Linha 47 – substituir “cadastre-se em uma” por “cadastre-se numa”
- [ ] Linha 47 – substituir “te dá acesso” por “dá-lhe acesso”
- [ ] Linha 47  substituir “planos de” por “os planos de”
- [ ] Linha 47 – colocar o determinante “o” antes de “HostGator” e “DreamHost”
- [ ] Linha 47 – substituir “econômicas” por “económicas”
- [ ] Linha 49 – tem um espaço a mais entre “a sua”
- [ ] Linha 49 – substituir “da DigitalOcean” por “do DigitalOcean” (aparece duas vezes)
- [ ] Linha 49 – retirar a vírgula em “(gotas), e”
- [ ] Linha 49 – substituir “no seu console” por “na sua consola”
- [ ] Linha 49 – será que não conseguiremos encontrar uma versão portuguesa para o link dos Ocean e para o guia da Amazon?
- [ ] Linha 51 – substituir “Agora que há um servidor rodando” por “Agora que possui um servidor”
- [ ] Linha 51 – substituir “Isso as vezes demanda que apenas se abra o terminal do computador e se escreva” por “Para tal apenas precisa de abrir e escrever”
- [ ] Linha 51 – substituir “como realizar login” por “como realizar o login”
- [ ] Linha 71 – substituir “Os comandos que iremos rodar são um pouco diferentes para VPS e para provedores de hospedagem compartilhada, então se tiver uma VPS, siga os passos 2A abaixo, e se tiver hospedagem compartilhada, pule para o passo 2B.” por “Os comandos que iremos rodar são um pouco diferentes para VPS e para provedores de hospedagem compartilhada. Se tiver uma VPS, siga os passos 2A abaixo. Se tiver hospedagem compartilhada, salte para o passo 2B.”
- [ ] Linha 75 – penso que podemos traduzir “web serving software” por “servidor web”
- [ ] Linha 75 – retirar a vírgula antes de “e PHP”
- [ ] Linha 77 – substituir “Tenha certeza” por “Tenha a certeza”
- [ ] Linha 77 – passar o primeiro para o início da frase ficando “Primeiro, tenha a certeza de que está conectado como usuário root (superusuário) (o usuário root …”. Retirar o ponto final antes de fechar o parenteses do final da frase, depois de comando
- [ ] Linha 90 – substituir “ao final” por “no final”
- [ ] Linha 92 – substituir “em um navegador da web, e ver” por “num navegador da web e ver”
- [ ] Linha 92 – substituir “provavelmente será preciso tomar alguns passos extras para assegurar que as portas estão encaminhando corretamente” por “provavelmente será preciso dar alguns passos extra para assegurar que as portas estão a encaminhar corretamente”
- [ ] Linha 110 – substituir “website, e” por “website e”
- [ ] Linha 110 – substituir “Latin” por “Latim”
- [ ] Linha 18 – substituir “acesse o banco” por “acesse ao banco”
- [ ] Linha 124 – substituir “linha de comando” por “linha de comandos”
- [ ] Linha 130 – substituir “pule” por “salte”
- [ ] Linha 130 – substituir por “parecerá com isso” por “parecer-se-á com isto”
- [ ] Linha 134 – substituir “jonreeve``` ), e” por “jonreeve``` ) e”
- [ ] Linha 136 – substituir “essa” por “esta”
- [ ] Linha 150 – substituir “Baixar e instalar Omeka” por “Fazer o download e instalar o Omeka”
- [ ] Linha 152 – substituir “diretamente no servidor. Isso nos permitirá evitar o processo de baixá-lo” por “diretamente para o servidor. Isso permitir-nos-á evitar o processo de fazer o download”
- [ ] Linha 152 – substituir “vá até o diretório” por “vá até ao diretório”
- [ ] Linha 152 – substituir “se não tiver certeza, cheque com o seu Host sobre qual” por “se não tiver a certeza, verifique com o seu Host qual”
- [ ] Linha 157 –  substituir “tenha certeza de que se está conectado/a” por “tenha a certeza de que se está a conectar”
- [ ] Linha 257 – substituir “vamos baixar o Omeka. O link para baixar o Omeka está” por “vamos fazer o download do Omeka. O link para fazer o download está”
- [ ] Linha 175 – colocar a palavra “provavelmente" entre vírgulas
- [ ] Linha 175 – entre “descompactará” e “o Omeka” está um espaço a mais
- [ ] Linha 175 – substituir “em um subdiretório no” por “num subdiretório do"
- [ ] Linha 175 – retirar o “se” de “não se queira”
- [ ] Linha 181 – substituir “que foi baixada” por “em que foi feito o download”
- [ ] Linha 185 – em “```/var/www/html/omeka ```, e no caso da hospedagem compartilhada,” retirar as duas vírgulas
- [ ] Linha 190 – substituir “tenha certeza” por “tenha a certeza”
- [ ] Linha 190 – Em “A não ser que se esteja” retirar o “se”
- [ ] Linha 200 – existem aspas a mais em ````XXXXXXXX```
- [ ] Linha 200 – existe um espaço a mais entre “`host`” e “deve”
- [ ] Linha 216 – substituir “acessar o” por “aceder ao”
- [ ] Linha 216 – substituir “substituído” por “substituindo”
- [ ] Linha 216 – retirar a vírgula depois de IP
- [ ] Linha 216 – retirar o “lá”

@DanielAlvesLABDH para database iremos usar banco de dados ou base de dados? Este caso ainda não está no nosso glossário. @GabrielaKucuruza no caso de ser a segunda opção é preciso uniformizar em toda a lição.

Muito obrigada!

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela revisão @joanacvp! Quanto a "database", julgo que a única vez que usámos ainda ficou como "banco de dados" (ver aqui: https://programminghistorian.org/pt/licoes/camadas-vetoriais-qgis). Será de incluir no glossário e acho que é melhor então adoptar essa opção: "banco de dados". @GabrielaKucuruza tendo em conta que nesta tradução as revisões estão também a cargo da @daniellesanchesDH e da @Msaguedes, o melhor será aguardar por todos os comentários e depois fazer uma única revisão.

**Comment by GabrielaKucuruza** [comment]
Muito obrigado pela revisão, @joanacvp!! Combinado, professor @DanielAlvesLABDH, fico no aguardo de todos os comentários para depois revisar tudo de uma vez só.

**Comment by DanielAlvesLABDH** [comment]
Olá @daniellesanchesDH e @Msaguedes, será que têm disponibilidade para avançar com esta revisão. A primeira lição da Gabriela sobre Omeka.net acabou de ser publicada e era bom podermos dar um avanço nas outras. Obrigado!

**Comment by Msaguedes** [comment]
Combinado! Submeto as notas amanhã, estou mesmo a terminar

**Comment by Msaguedes** [comment]
Boa noite

desculpem o atraso, a tradução está muito boa @GabrielaKucuruza 🎊 - todas as sugestões são no sentido de "disfarçar" as diferenças de português! 😉 

E já agora aproveito para confirmar para ser uniforme com as restantes, _file_ será para traduzir em arquivo ou ficheiros? - @DanielAlvesLABDH 

Qualquer questão não hesitem!

Seguem em baixo as sugestões:

linha 35
	Alterar de "é um serviço úitla para pessoas se iniciando no Omeka" para "é uma forma fácil de conhecerem o Omeka"

linha 37
	Alterar de " sem as restições daqueles ofertados pelo Omeka.net" para "sem as restrições do Omeka.net."

linha 38
	para não ter tanto "customizados" sugiro alterar "comprar um nome de domínio customizado" para "comprar um nome de domínio próprio"

linha 39
	Na mesma ideia alterar "É possível controlar os seus próprios" para "É possível gerir os backups próprios"

linha 43 
	Alterar "Nesse tutorial não demanda" para "O tutorial não pede"
	Valeria a pena colocar uma explicação do que são ferramentas GUI? Talvez o da wikipedia - https://pt.wikipedia.org/wiki/Construtor_de_interface_gr%C3%A1fica
	Alterar "através de seus painéis de controle" para "através dos painéis de controle"
	Alterar "pode não ser o jeito mais fácil de instalar o Omeka, mas ele te dará uma boa prática usando a linha de comando" para "pode não ser o mais fácil de instalação, mas é uma forma de praticar o uso de linhas de comando"
	Alterar "uma habilidade útil se quiser atualizar manualmente a sua instalação" para "uma habilidade útil para atualizar instalações anteriores"
	Alterar ", e deve tomar aproximadamente uma hora" para "de aproximadamente uma hora"

linha 44 Alterar "Configure o seu" para "Configurar o"

linha 47
	Alterar "cadastre-se em uma conta com um provedor que te dê acesso SSH" para "criar uma conta num provedor de hospedagem com acesso SSH" penso que fica mais neutro em termos de português
	Alterar "Uma hospedagem VPS te dá acesso" para "Uma hospedagem VPS dá acesso"
	Alterar controle para controlo
	Alterar "direcionada para usuários mais avançados" para "com funcionalidades mais avançadas"
	
linha 49
	Alterar " com a sua interface." para "com a interface"
	Alterar "fazendo o login e clicando" para "fazendo login e clicar"
	Alterar "criar uma fazendo login no seu console do EC2 clicando" para "criar uma depois do login na consola com a opção "Lauch Instance""
	Alterar "uma vez que rodaremos comandos para Ubuntu" para "uma vez que usaremos comandos para Ubuntu"
	Alterar "Para mais ajuda detalhada nesses passos" para "Para mais ajuda," ou "Para mais detalhes" ou "Para mais detalhes nesses passos,"
	** existe tutorial da Amazon EC2 em português br se calhar vale a pena colocar https://docs.aws.amazon.com/pt_br/AWSEC2/latest/UserGuide/EC2_GetStarted.html#ec2-launch-instance
	
linha 51
	Alterar "servidor rodando, conecte-se a ele com um cliente SSH" para "servidor pronto, aceda através do protocolo SSH"
	Alterar "Isso as vezes demanda que apenas se abra" para "Para isso às vezes basta abrir"
	Será para colocar (host) a seguir sempre que escrevem hospedagem?

linha 54
	Alterar "através do SSH" para "através do protocolo SSH"
	
linha 61
	Alterar de "Quando estiver conectado/a, deve-se ver um prompt que parecerá com isso" para "Depois de conectado/a deve aparecer um prompt com algo parecido com:"

linha 69 Alterar de "Instalar o seu servidor e banco de dados" para "Instalar o servidor e base de dados"

linha 71
	Remover "que iremos rodar" esta expressão é dificil de manter aplicavel para todos
	Remover "então"
	Alterar "pule" para "siga directo"

linha 75
	Alterar "Linux é o sistema operacional que roda o servidor" para "Linux é o sistema operativo para o servidor"
	Alterar "MySQL é o banco de dados" para "MySQL gere as bases de dados"
	
linha 77
	Alterar "usuário root (superusuário), primeiro. (O usuário root é um usuário de alto nível que possuí permissão para rodar qualquer comando.)." para "ususário root primeiro (o superusuário ou usuário root é aquele que tem permissão para fazer qualquer operação/comando no servidor)."
	
linha 85
	Alterar "vamos instalar a pilha do servidor" para "vamos instalar a pilah de software no servidor"

linha 90
	Alterar "ao final" para "no final"
	Alterar "e pedirá para que se escreva uma senha root do MySQL" para "e irá pedir uma senha root para o MySQL"
	Alterar "pois ela será usada posteriormente." para "pois vamos precisar dela mais à frente."
	
linha 92
	Alterar "o seu servidor web deve estar hospedando páginas da web." para "o servidor deve ter páginas da web hospedadas."
	Alterar "em um navegador da web," para "num navegador web"
	Alterar "então tudo está rodando corretamente" para "então está tudo correto."
	Alterar "pelo seu grupo de segurança atual." para "pelo grupo de segurança atual"
	Alterar "que se está usando" para "que está usando"

linha 94
	Alterar "deixe que se costumize" para "deixe costumizar"

linha 99
	substituir banco de dados por base de dados
	corrigir superusuário
	
linha 104
	substituir banco de dados por banco de dados
	
linha 126
	alaterar "usado com o Omeka" para ser "usado pelo Omeka"

linha 130
	Alterar "parecerá com isso" para "aparecerá algo semelhante a isso"
	
linha 136
	Na linha 130 sugeri colocar aparecerá algo semelhante com, para além de ser português mais neutro também anula a questão das versões/actualizações d esoftware
	
linha 152
	Alterar "Isso nos permitirá" para "Isso permitirá"
	Alterar "o que nos salvará" para "o que poupa"
	Alterar "cheque com o seu Host" para "veja com o serviço de hospedagem (Host)"

linha 157
	Alterar "vamos baixar o Omeka. O link para baixar o Omeka" para "vamos fazer o download do Omeka. O link da última versão"
	
linha 169
	Seguindo o glossário, em vez de arquivo deveria ser ficheiros. Mas podemos simplificar para "vamos descompactar o Omeka". Mas analisar se não seria de alterar todos os arquivos para ficheiros
	
linha 175
	Alterar "primeiramente" para "primeiro"
	Altrar "em um subdiretório no seu website" para "num subdiretório do website"
	Alterar "Supondo que não se queira que o seu website do Omeka tenha a URL" para "Supondo que não quer um URL para o seu website Omeka seja"

linha 190 
	Alterar "erro de permissão" para "erro de permissões"

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela revisão @Msaguedes! "File" deve ser traduzido para "ficheiro".

**Comment by GabrielaKucuruza** [comment]
Muito obrigado pela revisão, @Msaguedes!

**Comment by GabrielaKucuruza** [comment]
Boa noite, acabei de revisar o texto a partir dos apontamentos de @Msaguedes e @joanacvp, muito obrigado pelas revisões! Alguns dos apontamentos das revisões incidiam sobre as mesmas linhas, então tentei contemplar as indicações de forma que o texto ficasse o mais compreensível possível, tanto em PT-BR como PT-PT. Espero que tudo tenha ficado acertado. Abraços!

**Comment by DanielAlvesLABDH** [comment]
Obrigado pelas revisões @GabrielaKucuruza. Falta apenas a revisão da @daniellesanchesDH para dar por concluída a tarefa.

**Comment by daniellesanchesDH** [comment]
Olá @GabrielaKucuruza parabéns pelo trabalho!! Seguem algumas sugestões para alterações:

linha 35 - Alterar de "é um serviço útil para pessoas que estão a se iniciar no Omeka" para "é um serviço útil para iniciantes no uso Omeka"

linha 36 - Alterar de "é possível usar até a última versão do Omeka assim que ela  disponibilizadas" para "é possível usar a  versão mais atualizada do Omeka assim que ela for disponibilizada"

linha 37 - Alterar de "É possível instalar qualquer plugin ou tema que quiser" para "É possível instalar qualquer plugin ou tema"

linha 43 - Alterar de "Nesse tutorial, iremos escrever alguns comandos na linha de comandos" para "Nesse tutorial, iremos escrever alguns códigos na linha de comandos"

linha 47 - Alterar de "mas para arquivos grandes" para "mas para arquivos maiores"

linha 51 - Alterar de "Para isso às vezes basta abrir o terminal do computador e escrever" para "Para isso basta abrir o terminal do computador e escrever"

linha 51 - Alterar "Aqui seguem alguns guias para hospedagens VPS:" para "Aqui seguem alguns manuais para hospedagens VPS:"

linha 56 - Alterar "E aqui seguem alguns guias para hospedagens compartilhadas:" para "E aqui seguem alguns manuais para hospedagens compartilhadas:"

linha 75 - Alterar "Primeiramente, precisamos instalar a pilha de software LAMP" para "Primeiramente, precisamos instalar o conjunto de software LAMP"

linha 85 - Alterar "Agora que o seu sistema está atualizado, vamos instalar a pilha do servidor:" para "Agora que o seu sistema está atualizado, vamos instalar o conjunto no servidor:"

linha 207 - Alterar " O arquivo ficará parecendo, mais ou menos, assim:" para "O arquivo aparecerá, mais ou menos, assim:"

**Comment by daniellesanchesDH** [comment]
@DanielAlvesLABDH revisão concluída!

@GabrielaKucuruza qualquer dúvida estarei por aqui! Bom trabalho!

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela revisão @daniellesanchesDH. @GabrielaKucuruza sendo assim as revisões estão concluídas e agora julgo que poderá implementar as alterações na sua tradução.

**Comment by DanielAlvesLABDH** [comment]
Olá a todas! Alguma novidade em relação a esta revisão? @GabrielaKucuruza precisa de ajuda? Abraço

**Comment by GabrielaKucuruza** [comment]
Muito obrigado pela revisão, @daniellesanchesDH! @DanielAlvesLABDH peço desculpas pela demora, acabei me enrolando com o período de avaliações do CPDOC/FGV. Acabei de fazer um pull request com as revisões adicionadas. Abraços

**Comment by DanielAlvesLABDH** [comment]
Olá @GabrielaKucuruza estive a rever a tradução e a testar a lição. Deixo aqui algumas correcções. Contudo, no final deu-me um erro que não consegui ultrapassar e preciso perceber se no seu caso correu tudo bem com a instalação. Será que falhei algum passo?
- Linha 90: "Esse comando instalará um servidor LAMP, e irá pedir uma senha root do MySQL." Apague a vírgula a seguir a "LAMP".
- Linha 94: onde está "customizazação" deve estar "customização"
- Linha 110: "(Consulta OK, 1 afetada)" Alterar para "(Consulta OK, 1 linha afetada)"
- Linha 155: "cd/var/www/html" Falta um espaço entre "cd" e "/var/www/html"
- Linha 175: "(Se aparecer um erro aqui no VPS, provavelmente, teremos que instalar o comando unzip com apt-get install unzip primeiro. Isso descompactará o Omeka num subdiretório do seu website." Esta instrução não parece fazer sentido porque antes (linhas 163 a 166) dissemos já para instalar o unzip. O que vos parece @Msaguedes @joanacvp e @daniellesanchesDH ?
- Linha 216: "http://seu-domínio/omeka/install/install.php" Usando esta instrução aparece uma página em branco. Julgo que a correcta é "http://seu-domínio/omeka/install/" Quando usei essa, apareceu a página do Omeka.

Agora o erro!
- Quando cheguei ao "install", em vez do "formulário para completar a configuração", o que me aparece é uma mensagem de erro:
"Installation Error
mod_rewrite is not enabled.
Apache's mod_rewrite extension must be enabled for Omeka to work properly. Please enable mod_rewrite and try again."
Fui verificar essa função "mod_rewrite" e já estava activa, aliás como é indicado nas linhas 94 a 97. Repeti esses passos, fiz nova verificação e o erro é o mesmo. Também vos deu o mesmo erro @Msaguedes @joanacvp @daniellesanchesDH ?

De resto @GabrielaKucuruza, e como sempre, o trabalho de tradução está excelente.

**Comment by GabrielaKucuruza** [comment]
Bom dia, @DanielAlvesLABDH. Hoje/nos próximos dias adiciono as suas revisões no arquivo, obrigado! 
Sobre o erro, quando fiz a lição em junho-julho, lembro que correu tudo bem. Como fiz ela em outro dispositivo, os softwares de instalação não estão aqui comigo, mas posso tentar rebaixar tudo na próxima semana para testar de novo se tudo corre bem. Estranho ele dar esse erro e estar indicado que está atualizado. Ocorreu-me que talvez o Apache precisasse ser reiniciado, mas não sei se fez isso. Abraços!

**Comment by DanielAlvesLABDH** [comment]
Obrigado @GabrielaKucuruza. Testei múltiplas soluções, inclusive indicadas pelo Omeka e nada resultou. Vou aguardar então. Bom domingo

**Comment by GabrielaKucuruza** [comment]
Bom dia, professor @DanielAlvesLABDH, lamento pela demora. Peço desculpas, pois receio que me confundi sobre os testes da lição! Havia testado uma outra, e achei que era essa... Fui realizar o teste hoje, mas agora vejo que estou com problemas no primeiro passo, pois todos os servidores oferecidos são pagos (ou demandam informações bancárias para um teste), e não consigo prosseguir. Há alguma indicação de servidor host com SSH gratuito? Pesquisei, mas não achei. Lamento pela confusão, achei que havia testado. Agradeço desde já pela compreensão e orientação. Abraços!

**Comment by GabrielaKucuruza** [comment]
Ih, acho que acabei de encontrar um serviço que funcionou sem pedir informações bancárias. Espero testar ainda hoje e retornar. Desculpas novamente!

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela disponibilidade @GabrielaKucuruza. Não precisa pedir desculpa de nada...
Eu tentei com um serviço de host pago e deu o erro final que indiquei. Fico a aguardar

**Comment by GabrielaKucuruza** [comment]
Não tem de que, @DanielAlvesLABDH! Fui tentar hoje e fiquei de novo com o problema dos dados bancários que são necessários para o uso. Vou ver se encontro um jeito, aviso se conseguir testar!

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg, nós estamos com alguma dificuldade em arranjar um ambiente de testes para esta lição. Será que você consegue ajudar a @GabrielaKucuruza a fazer um teste final à lição de instalação de Omeka? Desde já agradeço. Abraço

**Comment by DanielAlvesLABDH** [comment]
Caros @josircg e @GabrielaKucuruza, temos novidades sobre isto?

**Comment by josircg** [comment]
Oi @DanielAlvesLABDH, perdi essa notificação. Vou verificar aqui se dá para montar um ambiente de teste.

**Comment by josircg** [comment]
Olá @GabrielaKucuruza minha sugestão é que você utilize o VirtualBox e instale o Ubuntu na sua própria máquina. Segue um tutorial para realizar uma instalação.

https://brb.nci.nih.gov/seqtools/installUbuntu.html

Nesse meio tempo, vou tentar utilizar um crédito que eu tenho na AWS para preparar uma máquina caso você tenha dificuldade de instalar o VirtualBox no seu computador.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @josircg

**Comment by JimmyMedeiros82** [comment]
@GabrielaKucuruza conseguimos avançar com este teste?

**Comment by GabrielaKucuruza** [comment]
Oii @JimmyMedeiros82 ainda não consegui me dedicar a isso, mas a partir do fim do período, está como prioridade.

**Comment by josircg** [comment]
Olá @GabrielaKucuruza, eu já configurei uma máquina na AWS para que vc consiga testar o Omeka.
Me envie um email para josir@irdx.com.br que eu envio para vc as credenciais para acessar o servidor e testar a ferramenta.

**Comment by GabrielaKucuruza** [comment]
Agradeço demais @josircg! Logo te envio um email!

**Comment by josircg** [comment]
Olá pessoal, eu tentei seguir a instalação mas realmente o tutorial existente já não funciona mais com a versão do Ubuntu 18.04. Para que funcione, precisa ser a versão 2.7 do omeka e deve-se criar novos passos. 

Nesse caso, temos que pedir a correção da versão em inglês, correto?

A implantação do software pode ser vista aqui: http://omeka.irdx.com.br
Como o custo para mantê-la online é de USD 10, vou deixar apenas essa semana online.

**Comment by josircg** [comment]
Olá pessoas. Tive que tirar o servidor do ar e fiz um pedido de ajuste no artigo original em inglês:

https://github.com/programminghistorian/jekyll/issues/2594

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg, muito obrigado por toda a colaboração. Fui acompanhando, mas só hoje consegui dar atenção a isto. Vamos aguardar pela correção da equipa inglesa ou podemos avançar, incluindo as suas sugestões na tradução da @GabrielaKucuruza ? Você tem essas instruções que possa passar para aqui? Obrigado uma vez mais e um abraço

**Comment by josircg** [comment]
Bom dia @DanielAlvesLABDH, acho que vale a pena aguardar a correção por parte da equipe inglesa.

**Comment by anisa-hawes** [comment]
Hello all,

Please note that as part of a reorganisation of the /pt directory, this lesson's .md file has been moved to a new location within our Submissions Repository. 

It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/instalar-omeka.md

A consequence is that this lesson's preview link has changed. It is now: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/instalar-omeka

Please let me know if you encounter any difficulties or have any questions.
Very best, Anisa

**Comment by josircg** [comment]
Bom dia @GabrielaKucuruza e @JimmyMedeiros82 a correção da lição em inglês entrou em produção hoje. Vocẽs podem seguir na tradução.

**Comment by DanielAlvesLABDH** [comment]
Olá @GabrielaKucuruza. Com a ajuda do Josir e dos colegas da equipe inglesa temos uma nova versão da lição online. Você teria disponibilidade para olhar para a nova versão (https://programminghistorian.org//en/lessons/installing-omeka) e ver se é possível corrigir/adaptar a tradução (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/instalar-omeka.md)? Muito obrigado!

**Comment by DanielAlvesLABDH** [comment]
Olá @GabrielaKucuruza, espero que esteja tudo bem. Acha que podemos avançar com uma revisão da tradução tento em conta as alterações feitas na lição original? Se precisar de ajuda ou conversar sobre isto, é só dizer. Obrigado

**Comment by GabrielaKucuruza** [comment]
Olá @DanielAlvesLABDH, tudo bem? Peço desculpas pela demora em responder. No momento, devido a demandas e obrigações de trabalho e do fim de curso de graduação, não consigo avançar na revisão da tradução, mas assim que for possível, espero me deter na revisão. Aviso assim que começar a mexer na mesma. Abraços e obrigado.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @GabrielaKucuruza e uma excelente conclusão do curso!!!

**Comment by DanielAlvesLABDH** [comment]
Olá de novo @GabrielaKucuruza. Correu bem essa recta final do curso? Espero que sim. Acha que será possível retomarmos isto? Desde já agradeço

**Comment by ericbrasiln** [comment]
Olá, @GabrielaKucuruza Como vai?

Me chamo Eric Brasil e substituí o Daniel na função de editor-chefe da revista em português.

Você poderia nos informar sobre sua disponibilidade de avançar com a tradução das alterações feitas na lição original?

Qualquer dúvida pode entrar em contato comigo por aqui ou pelo email portugues@programminghistorian.org

**Comment by ericbrasiln** [comment]
Oi @DanielAlvesLABDH  
Como vai?

Estamos passando pelas nossas _issues_ que estão paradas há muito tempo. 
Sugerimos que essa issue seja fechada no momento em função de [updates na lição original](https://github.com/programminghistorian/jekyll/pull/2930/files) e novas mudanças na ferramenta desde que a tradução foi realizada. Atualizar a tradução demandaria muito trabalho da equipe.

Agradecemos ao trabalho de todas até e aqui.
