### ISSUE TITLE
Tradução da lição "Creating an Omeka Exhibit"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#378]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Creating an Omeka Exhibit' por @GabrielaKucuruza. A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/criar-exposicao-omeka.md) e as imagens estão nesta pasta (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/criar-exposicao-omeka). Muito obrigado, uma vez mais, Gabriela!

Aqui pode ser verificada uma visualização prévia da página: http://programminghistorian.github.io/ph-submissions/pt/licoes/traducoes/criar-exposicao-omeka

O editor para esta tradução vou ser eu, Daniel Alves.

A @daniellesanchesDH e a @joanacvp aceitaram ficar como revisoras desta tradução.

Peço que além da tradução para português, procurem verificar se a lição precisa de alguma actualização. Por favor, deixem as vossas sugestões na caixa de comentários deste ticket, de forma que a Gabriela possa acompanhar e responder.

Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.

Política anti-assédio
_

Esta é uma declaração de princípios do *Programming Historian em português* e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.

O *Programming Historian em português* dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque *ad hominem* a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by GabrielaKucuruza** [comment]
Eu quem agradeço, de novo, professor Daniel! Qualquer coisa, estou a disposição!

**Comment by joanacvp** [comment]
Boa tarde. Óptimo trabalho @GabrielaKucuruza. Deixo os meus comentários:

- [ ] Onde está “File” deve ficar sempre “ficheiro” e não “arquivo”, de acordo com o mini-glossário da equipa portuguesa
- [ ] Linhas 2 e 3, título - Sugiro que a lição se chame “Criar uma exposição no Omeka”
- [ ] Linha 25, abstract – retirar o “nós”
- [ ] Linha 25, abstract – substituir “no seu site” por “ao seu site”
- [ ] Linha 36 – retirar o “nós”
- [ ] Linha 36 – substituir “no seu site” por “ao seu site”
- [ ] Linha 40 – mantemos “planejar” ou colocamos “planear” @DanielAlvesLABDH?
- [ ] Linha 40 – substituir “os argumentos que queremos fazer, e como pretendemos fazê-los” por “os argumentos que queremos apresentar, e como pretendemos fazê-lo”
- [ ] Linha 40 – retirar o “eu” (repete-se três vezes)
- [ ] Linha 40 – substituir “discutindo” por “a discutir”
- [ ] Linha 40 – substituir “para quem” por “a quem”
- [ ] Linha 42 – substituir “Adicionando” por “Adicionar"
- [ ] Linha 46 – substituir “um tour guiado” por “uma visita guiada” e acrescentar uma vírgula depois de itens
- [ ] Linha 46 – depois de “Para criar uma” acrescentar “exposição”
- [ ] Linha 46 – substituir “**Exposições**” por “**Exhibits** (Exposições)” e “**Adicionar uma exposição**” por “**Add Exhibit** (Adicionar uma exposição)”. Uma vez que a plataforma não está traduzida penso que esta será a melhor opção para possíveis utilizadores que não saibam a que corresponde cada elemento em português. Foi a solução seguida também pela equipa espanhola
- [ ] Linha 46 – substituir “é um nome” por “é o nome”
- [ ] Linha 50 – substituir “Páginas são onde iremos colocar os itens na exposição.” por “É nas páginas que iremos colocar os itens da exposição.”
- [ ] Linha 50 – retirar a vírgula depois de páginas na segunda frase
- [ ] Linha 52 – substituir “Adicionar Página” por “Add Page (adicionar página)”
- [ ] Linha 58 – substituir “**Título da página**” por “**Page Title** (título da página)”
- [ ] Linha 60 – substituir “**Novo Bloco**” por “**New Block** (novo bloco)”
- [ ] Linha 62 – substituir “**Arquivo com Texto**” por “**File with Text** (ficheiro com texto)” e “**Adicionar um novo bloco de conteúdo**” por “**Add new content block** (adicionar um novo bloco de conteúdo)”
- [ ] Linha 68 – substituir “**Bloco 1** (Arquivo com texto)” por “**Block 1** (ficheiro com texto)” e “**Adicionar Item**” por “**Add Item** (adicionar item)”
- [ ] Linha 70 – substituir “**Selecione um Item**” por “**Select Item** (selecione um item)”
- [ ] Linha 70 – Substituir “É possível adicionar uma legenda se quiser” por “Se quiser, é possível adicionar uma legenda”
- [ ] Linha 70 – substituir “**Aplicar**” por “**Apply** (aplicar)”
- [ ] Linha 72 – substituir “**Texto**” por “**Text** (texto)”
- [ ] Linha 74 – retirar o “você”
- [ ] Linha 74 – substituir “**Ver Página Púbica**” por “**View Public Page** (ver página pública)”
- [ ] Linha 78 – na legenda, colocar uma vírgula depois de “cachorro”

Espero que os comentários sejam úteis. Qualquer dúvida disponha

**Comment by GabrielaKucuruza** [comment]
Muito obrigado pela revisão, @joanacvp! 

Sobre a tradução da plataforma, ela atualmente conta com um plug-in que permite e tradução interna, por isso os botões estão referenciados em português. Na tradução dessa lição, https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/introducao-omeka-net.md, adicionei uma seção explicando o passo-a-passo para instalar o plug-in. Fico me perguntando se seria então interessante deixar uma nota referenciando a lição anterior, indicando que a tradução da plataforma para o português está indicada lá. 

Abraços!

**Comment by DanielAlvesLABDH** [comment]
Obrigado pela revisão @joanacvp. @GabrielaKucuruza concordo com essa solução. Uma vez que temos na outra lição a explicação da mudança para português,  é escolher onde colocar essa referência nesta lição. É possível copiar o link directo para essa secção específica. Assim os leitores são logo directamente encaminhados para a parte relevante. Se for necessário ajuda com isso e só dizer. Obrigado

**Comment by DanielAlvesLABDH** [comment]
Olá @daniellesanchesDH, só falta a sua revisão. Quando terá disponibilidade para isto? É uma tradução bem pequena ;-)

**Comment by daniellesanchesDH** [comment]
Olá @GabrielaKucuruza parabéns pelo trabalho! Seguem algumas sugestões:

linha 42 - Alterar "Adicionando uma exposição" para "Adicionar uma exposição" 

linha 46 - Alterar "A coleção é apenas uma lista de objetos" para "A coleção é uma lista de objetos"

linha 46 - Alterar "que fará parte do seu URL." para "que fará parte da sua URL."

linha 50 - Alterar "Páginas são onde iremos colocar os itens na exposição" para "Páginas são onde inserimos os itens na exposição"

linha 50 - Alterar "e é possível arrastar e soltá-las para reorganizar a ordem" para "e é possível arrastar e soltar para reorganizá-las"

**Comment by daniellesanchesDH** [comment]
> Olá @daniellesanchesDH, só falta a sua revisão. Quando terá disponibilidade para isto? É uma tradução bem pequena ;-)

Oi @DanielAlvesLABDH finalmente consegui!! Fechada!!

@GabrielaKucuruza se precisar de algo é só avisar!! Bom trabalho!

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado pela revisão @daniellesanchesDH. @GabrielaKucuruza as revisões estão concluídas, pode passar à implementação das alterações.

**Comment by GabrielaKucuruza** [comment]
Obrigado pela revisão @daniellesanchesDH, acabei de adicioná-la. Inclusive, todas as revisões foram implementadas, @DanielAlvesLABDH. Abraços.

**Comment by DanielAlvesLABDH** [comment]
As alterações foram incluídas no ficheiro. Fiz uma última revisão e ligeiras adaptações. Obrigado uma vez mais @GabrielaKucuruza. Ficou óptimo. E muito obrigado à @joanacvp e à @daniellesanchesDH pelas revisões e sugestões. Vou iniciar o processo de publicação.

**Comment by GabrielaKucuruza** [comment]
Muito obrigado, prof @DanielAlvesLABDH, @joanacvp e @daniellesanchesDH!

**Comment by DanielAlvesLABDH** [comment]
Caríssimas @GabrielaKucuruza, @joanacvp e @daniellesanchesDH a lição já está publicada e podemos começar a divulgar!
https://programminghistorian.org/pt/licoes/criar-exposicao-omeka
Obrigado a todas! Ficou excelente!
