### ISSUE TITLE
Tradução da lição "Up and Running with Omeka.net"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#379]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Up and Running with Omeka.net' por @GabrielaKucuruza. A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/introducao-omeka-net.md) e as imagens estão nesta pasta (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/introducao-omeka-net). Muito obrigado, uma vez mais, Gabriela!

Aqui pode ser verificada uma visualização prévia da página: http://programminghistorian.github.io/ph-submissions/pt/licoes/traducoes/introducao-omeka-net

O editor para esta tradução vou ser eu, Daniel Alves.

A @Angelaimp  e o @romulopredes  aceitaram ficar como revisores desta tradução.

Por favor, deixem as vossas sugestões na caixa de comentários deste ticket, de forma que a Gabriela possa acompanhar e responder. Tendo em conta que a lição tem muitas imagens, pedia a vossa atenção para perceber se estão adequadas para o texto. Para além disso, a Gabriela acrescentou uma secção nova que não constava da lição original em inglês, para levar em conta a utilização de um novo plug-in. Peço que verifiquem também. Obrigado!

Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.

Política anti-assédio
_

Esta é uma declaração de princípios do *Programming Historian em português* e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.

O *Programming Historian em português* dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque *ad hominem* a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by romulopredes** [comment]
Começo por parabenizar a @GabrielaKucuruza pela tradução! Excelente trabalho e iniciativa. 

A lição está bem estruturada e as imagens me parecem estar todas em ordem.

Dito isso, faço abaixo apenas algumas propostas de revisão ortográficas a serem consideradas:

1. Tradução de 'Back'. 
Na seção "Um site vazio no Omeka": 'clique no botão Back (Atrás)' --> Back (Voltar) ou Back (Retornar).

2. Acentuação. 
Na seção "Instale alguns plugins": 'Precisamos ativa-los.' --> Precisamos ativá-los.

3. Erro de digitação. 
Na seção "Configurando o seu site para português (nota da tradução)": 'Escolha Português - Brasil (pt_BR) ou Português - Portgual (pt_PT).' --> (...) ou Português - Portugal (pt PT).

4. Adicionar ponto final. 
Na seção "Adicione um item": 'Adicione um item (Add an item)' --> Adicione um item (Add an item).

5. Corrigir vírgula no lugar de ponto final. 
Na seção "Anexe um ficheiro ao registro do seu item": 'Podemos adicionar múltiplos ficheiros, mas saiba que o plano Básico apenas vem com 500 MB de espaço de armazenamento,' --> (...) com 500 MB de espaço de armazenamento.

Abraços,
Rômulo Predes

**Comment by GabrielaKucuruza** [comment]
Muito obrigado pela revisão, @romulopredes! É um prazer colaborar com o projeto. 
Vou seguir a orientação do professor @DanielAlvesLABDH e aguardar por todas as revisões, de forma a fazer uma única revisão depois. 
Abraços,
Gabriela

**Comment by Angelaimp** [comment]
Olá a todos! 
Também acho que está óptima. Gostei das adições à lição. Fizeram muito sentido. 
Penso que as imagens estão bem organizadas

O Romúlo já tinha de facto "apanhado" algumas gralhas e eu apontei só mais umas, mas também para tentar adaptar um pouco mais para o PT_PT deixei algumas sugestões de adaptações possíveis, tendo sempre que se considerar se será também perceptível do outro lado do Atlântico...

A parte dos textos que podiam ter adaptação para PT_PT estão apenas entre aspas e as poucas "gralhas" estão assinaladas com asteriscos. 
Está organizado por seções, a bold.

Como é explicado como mudar a linguagem do Omeka para português não sei se valerá a pena manter entre parêntesis a versão em inglês... Acrescentei nos casos em que eram diferentes as versões dos menus da Omeka em PT_PT.

Cá vai então: 

**Instale alguns plugins**
* trocar Instalar (Install) por Install (Instalar) 

**Configurando o seu site para português (nota da tradução)** 
* Manage Site (Gerenciar Site) deverá talvez ficar como o anterior (Administre o site)

 - Aqui a única coisa que acho é que uma vez que a imagem é de como o menu fica depois de instalado o plugin podia ser passada para o final da seção e frase ficar "A sua tela ficará parecida com a imagem abaixo."

**Adicione um item**
*Trocar Items por Itens

**Descreva o seu novo item**
A legenda da imagem "Torne o seu item público clicando na caixa circulada acima" não é muito perceptível em PT_PT podendo talvez ficar "Torne o seu item público usando a caixa de seleção assinalada" 

Da mesma forma penso que essas informações possa ficar "estas informações"

E público geral talvez ficar "público em geral"

- Aqui ao ver a edição em inglês vi que havia uma parte que faltava traduzir: 
"To add multiple fields — for example, if you want to add multiple subjects for your item — use the green Add input button to the left of the text boxes."
Deixo assim uma sugestão de tradução que pode ser revista: "Para adicionar múltiplos campos - por exemplo, se você quiser adicionar vários assuntos ao seu item - use o botão verde Adicionar informação à esquerda das caixas de texto."


**Uma questão complexa**
"O que é isso?" -  Acho que também seria mais adaptado em PT_PT se for: "O que é isto?"


Da mesma foma em Eu estou criando um registro de item para o meu cachorro, Boris talvez trocar o gerúndio por" Eu estou a criar..." 

Também em "Mas eu estou descrevendo... " - "Eu estou a descrever..."

* acrescentar "r" em criado - ficar criador

**Anexe um ficheiro ao registro do seu item**

Em Arquivos (Ficheiros "em PT_PT" / Files),

Em "o Omeka irá salvar automaticamente essa informação" não sei se será perceptível em PT_BR se ficar "o Omeka irá guardar automáticamente"...

Em adicionar Tags "(Etiquetas em PT_PT)"... 

Em Também podemos clicar em Metadados ("Meta-dados do Tipo de Item em PT_PT") 
*Em "(Item Type Metadados)" - mantendo o inglês trocar Metadados por Metadata 

Na frase "Se não encontrar um tipo apropriado de item para o seu, não se preocupe." penso que será mais perceptível se ficar ... "um tipo de item apropriado para o seu item,..."

**Você tem um item!**
Na imagem - "Visão dos Itens por Admin" - admin não é perceptível em PT_PT, uma sugestão possível é: "Explorar itens, vista de administrador"

Em "Essa lista..." talvez trocar por "Esta lista..." 

**Essa não é a página pública para o seu item** - Aqui também talvez se possa trocar "Essa" por "Esta" 
Na imagem - "Visão de um Item, por Admin" - talvez possa ficar "Página de Item, vista de administrador"

*Em "botão azul Visualizar a Página Pública (conferir o texto),..." mudar para "botão azul Ver Página Pública,..."

* Na frase "(Ou podemos editar o item clicando em Edite esse item na direita)." ficar "(Ou você pode editar o item clicando em Editar à direita)."

**Essa é a página pública para o seu item** - da mesma forma talvez mudar "Essa" para "Esta"
Na imagem - Exibição do item, por visão pública -  talvez ficar "Página de item, vista pública"


**Insira informações sobre a sua coleção**
Na frase "No Omeka, os metadados são centrais!" não sei se valeria a pena mudar "centrais" por "fundamentais"? 

*Em "clicar no botão Pública" trocar por "clicar no botão Público"Em "Então salve a coleção" não sei se ficaria perceptível "Então guarde a coleção."?

**Adicione itens na sua coleção**
Na imagem - "Clique na caixa seleção para editar" - ficar talvez: "Clique na caixa de seleção de cada item para editar (em grupo)"

- Na frase "Para preencher a coleção que acabamos de criar, clique na aba de..." não sei se seria de ficar "acabámos", ou "acabou"?
 
Em Da sua lista Ver Itens "(Explorar Itens em PT_PT)"
Em "clique nas caixas..." acrescentar "de verificação" (caixas de verificação dos itens)

**Escolha a coleção**
*Em "Na página de Edição" trocar para "Na página Editar Item (Editar Itens em Lote em PT_PT)"

 Na frase "selecione a Coleção na qual gostaria de adicionar os seus itens." talvez trocar "na qual" por "à qual".

Em "(Além disso, note todas as outras coisas que podem ser feitas nessa página)" talvez "Além disso, tenha atenção a todas as outras coisas que podem ser feitas nesta página"

**Olhe a sua nova coleção** - Para PT_PT talvez ficar "Confira" ou "Veja"...
*Em "Se clicarmos na aba de Ver Coleções" ficar " Ver as Coleções (Explorar as Colecções em PT_PT)" 
Em "deve agora haver uma nova coleção" talvez possa se mudar para "deverá"?
Em "Agora que alguns itens foram adicionados e agrupados em uma coleção" talvez mudar para "numa coleção"Em "tome algum tempo para editar ainda mais o seu site." possa ficar "dedique algum tempo..."?
Em "Ele está começando a tomar forma agora que há tanto itens individuais e unidades temáticas,..." talvez possa ficar "tanto itens individuais como unidades temáticas" 
Em "Nós vamos falar sobre isso numa próxima lição." talvez possa ficar "Nós iremos falar..."?

**Recursos Adicionais**
*Na frase "O time do Omeka compilou..." trocar por "A equipe..."

Ficou muito comprido... Espero que se compreenda. Por último só dizer que adorei esta "questão complexa" Este Boris parece mais simpático. :) 


Peço desculpa de tentar adaptar para PT_PT, deixem como considerarem que fica melhor e perceptível, (se acharem que essas alterações não são necessárias).

Desejo então um bom trabalho e fim de semana para todos.
Abraços,
Ângela Pité

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @Angelaimp, revisão muito detalhada. Obrigado também ao @romulopredes pela revisão cuidada. Vão ser excelentes ajudas para a @GabrielaKucuruza melhorar ainda mais a sua tradução. Abraço a todos!

**Comment by GabrielaKucuruza** [comment]
Muito obrigado pela revisão, @Angelaimp, ajudou muito em formas de contemplar o PT-PT!

Abraços,
Gabriela

**Comment by DanielAlvesLABDH** [comment]
Pergunto ao @romulopredes e à @Angelaimp se consideram que as revisões introduzidas pela @GabrielaKucuruza no ficheiro (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/introducao-omeka-net.md) estão de acordo com o que sugeriram e se podemos dar por concluído este processo? Ou se têm mais alguma sugestão?

**Comment by romulopredes** [comment]
De minha parte, eu considero atendidas as revisões! :)

**Comment by Angelaimp** [comment]
Desculpem vir só deixar uns apontamentos e que são apenas uns nomes de menus... (talvez não se percebesse bem de facto no meio do texto):

**Anexe um ficheiro ao registro do seu item**
**Metadados** (Meta-dados do Tipo de Item em PT_PT / Metadata) --> **Metadados** (Meta-dados do Tipo de Item em PT_PT / Item Type Metadata)

**Esta não é a página pública para o seu item**
clicando em **Edite esse item na direita** --> clicando em **Editar** na direita

De resto também considero que está tudo bem!
Obrigada por "acomodarem" o PT_PT!

**Comment by GabrielaKucuruza** [comment]
Obrigado pelos apontamentos, @Angelaimp! Acabei de adicionar esses pontos, peço desculpas por ter os deixado passar! Ainda, obrigado novamente por ter possibilitado uma tradução que contemple PT-PT.  Abraços!

**Comment by DanielAlvesLABDH** [comment]
As alterações foram incluídas no ficheiro. Obrigado @GabrielaKucuruza pelo excelente trabalho. E obrigado ao @romulopredes e à @Angelaimp pela revisão atenta. Vou agora fazer uma última verificação e publicar a lição. Mais uma!

**Comment by Angelaimp** [comment]
Obrigada eu, @GabrielaKucuruza por ter atendido às alterações para o PT-PT! Abraços!

**Comment by DanielAlvesLABDH** [comment]
Olá a todos! A lição já está publicada (https://programminghistorian.org/pt/licoes/introducao-omeka-net). Vou fechar este ticket. Parabéns e obrigado à @GabrielaKucuruza pela sua primeira lição para o PH! Obrigado também ao @romulopredes e à @Angelaimp pela revisão que ajudou a melhorar o resultado final. Obrigado também à @joanacvp pela finalíssima revisão ;-)
