### ISSUE TITLE
 Review Ticket for 'Preparación de un ambiente integrado para Python (Linux)' - Spanish translation 

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#38]
The Programming Historian has received the following translation on 'Preparación de un ambiente integrado para Python (Linux)' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/instalacion-linux

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by mariajoafana** [comment]
Here are my comments/suggestions.

Línea 19:  punto final (.) desués de "sudo
Línea 23: sugiero cambiar "asegurarse que tienes" por "asegurarse de tener" 
Línea 33: espacio de sobre antes de "Guardarás". Corregir "sert". Mínuscula en "Pero". Tilde en "hará". Mayúscula en "Home". 
Línea 42: coma (,) después de "Komodo Edit es un editor de texto libre y de código abierto, ..." Eliminar espacio extra después de "prefieres." Cambiar "Ubunto" por Ubuntu". Mayúscula en Komodo. "Clic" en vez de "click". 
Línea 57: eliminar espacio extra entre "como programa." y "El intérprete".
Línea 66: eliminar espacio extra despues de `Run`
Línea 72: corregior "los que se conocer" por "lo que se conoce"

**Comment by vgayolrs** [comment]
Thank you @mariajoafana , done.

**Comment by arojascastro** [comment]
Doubts: 
- Line 19:  What is "sudo"? A note or a link would suffice.

Suggested changes:
- In all text: use *click* or *clic*
- Line 29: "toma nota" sounds English to me... maybe in Mexico you say it but in Iberian Spanish sounds definitely English. We usually say "Ten en cuenta" or "No olvides", etc. Ignore this if you are sure that that expression is not a literal translation.
- Line 42: package manager --> in italics? 
- Line 67 - 69: the image hello-world1 is missing in the online site
- All document: Shell --> in italics (actually sometimes is already in italics but not always)
- All document: prompt --> in italics?
- Last line: full stop is missing after link

**Comment by acrymble** [comment]
sudo is a unix command.

**Comment by vgayolrs** [comment]
Thank you very much @arojascastro .  Done!

Although it is not explained in the original lesson (because every Linux and OS-X user is familiar with that UNIX command), I have included the link to Wikipedia for `sudo`.

I note that the `hello-world1` image also does not unfold in the [original lesson](http://programminghistorian.org/lessons/linux-installation), and that is because it's missing in the [correspondent folder](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/linux-installation). But I guess when the problem with that image gets fixed, it will appear. Should I open a ticket on that, @acrymble ?

**Comment by acrymble** [comment]
yes please do open a ticket on the main repo if you find problems with existing lessons.

**Comment by acrymble** [comment]
added translation reviewers. this lesson is published.
