### ISSUE TITLE
Tradução da lição "Processamento de Texto em R"

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#381]
O Programming Historian em português recebeu a proposta de tradução da lição 'Processamento Básico de Texto em R' por @dianarebelorodriguez. A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/processamento-basico-texto-r.md). 

E a lição original está em https://programminghistorian.org/en/lessons/basic-text-processing-in-r 

A Diana fez um belo trabalho! Muito obrigado pela contribuição. 
Eu serei o editor da tradução. E junto com a @Msaguedes e o @romulopredes  faremos a revisão da tradução.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo.  Por favor, deixem suas sugestões na caixa de comentários para que a Diana possa acompanhar e responder.

O ideal é a Diana realizar as modificações após as sugestões do Rômulo e da Maria. 

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Política anti-assédio:
_
Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by romulopredes** [comment]
Olá! Jimmy, acredito que o link correto para a tradução seja este: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/processamento-basico-texto-r

Notei que o arquivo não está carregado como .md no GitHub, o que pode nos dificulta a revisão.

Ademais, a leitura do ficheiro fluiu bem e não observei nenhuma grande revisão necessária. Eu estou satisfeito com a tradução! 

Parabéns à Diana pelo trabalho e pela iniciativa!

**Comment by JimmyMedeiros82** [comment]
Oi @romulopredes 

super obrigado pela revisão. Vamos aguardar o retorno da @Msaguedes para dar prosseguimento. Não entendi essa do link cair em um endereço errado. O link que colou está correto.

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82, fiz alguns ajustes necessários no cabeçalho da lição (as primeiras 28 linhas) e acrescentei a extensão ".md" ao ficheiro de modo a que seja possível activar o "Preview" e depois publicar. Era isso que o @romulopredes estava a indicar, acho. Aproveito para agradecer a tradução da @dianarebelorodriguez, bem como ao Rômulo e à @Msaguedes por terem aceite fazer as revisões. Outra coisa Jimmy, é necessário adicionar a Diana ao repositório de submissões do PH para que depois ela possa realizar as correcções directamente no ficheiro através de "commits". Para isso você tem de ir a PH-submissions, clicar em "settings", depois em "Manage access" e por fim no botão verde "Invite teams or people". Procura o user da Diana e atribui como "Write". Depois disso a Diana recebe um email e terá de confirmar o acesso. Se for necessário ajuda é só dizer. Abraço

**Comment by JimmyMedeiros82** [comment]
Oi @DanielAlvesLABDH muito obrigado pela orientação!
Adicionei a Diana no repositório!

**Comment by Msaguedes** [comment]
Olá! Espero que esteja todos bem seguem em baixo as minhas notas. A tradução está bastante boa, com as instruções acessívies. A únicas questões que se calhar precisam de atenção é os nomes das colunas em inglês e os comandos com os mesmos nomes, 
e aquestão da mediana do comprimento das frases. Todas as alterações são apenas formas de equilibrar o português.

Desculpem a demora e qualquer questão não hesitem.

NOTAS

linha 33
	 - Alterar "matérias de jornal", sugiro colocar "artigos de jornal" ou peça de jornal
	 - Alterar "provêm ferramentas" para "incluem ferramentas" ou "têm ferramentas"
	 
	 
linha 39
	- Apenas para ficar mais claro recomando que o fim da frase seja altera para "discursos presidencias dos Estados Unidos da América sobre o Estado da União." Podendo até ser acrescentado o link para a página da wikipedia que explica o que estes são - https://pt.wikipedia.org/wiki/Discurso_sobre_o_Estado_da_Uni%C3%A3o . A página não pareceu muito completa na versão portuguesa, não sei se vale a pena procurar uma enciclopedia ou dicionario online
	

linha 41
	 - Para o link da lição ver se já está traduzida ou no processo porque o ideal era que ficasse com o nome e link para a versão portuguesa 
	- Alterar "assumidos aqui", para "necessários aqui"
	- Alterar "em seus computadores" para "indicado para os seus sistemas operativos"

linha 43
	- não sei se não é de dar indicação à equipa inglesa de que o código corre numa versão superior para actualizarem a sua própria lição
	
linha 56
	- alterar " pode ser que uma caixa de diálogo seja aberta, solicitando" para "pode ser aberta uma caixa de diálogo solicitando"

linha 58 
	- alterar "estão baixados" para "estão"
	
linha 65
	- Remover "Enquanto"
	- Nota 5 e tradução dos comandos - estes nem sempre têm a tradução - será mesmo necessário colocar essa tradução sempre? Se calhar o melhor é remeter para a nota de tradução 5 e fazer dela um glossário/dicionário dos comandos

linha 69
	- alterar "em sua versão em" para "traduzido para"
	
linha 137
	- em protugues o símbolo chama-se parentesis reto, para nós colchete é "{", se calhar o mais fácil será não mencionar o nome mas colocar o simbolo em destaque, terminando a frase e a seguir colocar "Para seleccionar o primeiro elemento da lista o comando é `[[1]]`, e portanto para sabermos quantas palavras existem deverá ser colocado no console:"
	
linha 155
	- alterar "parecer com este em seu" para "aparecer assim no"
	
linha 179
	- não sei se arrange não devia ser traduzido como organizar
	- Alterar "leva o conjunto de dados para ser trabalhado" para "precisa do conjunto de dados a utilizar"
	- Alterar "que ela toma como" para "que serve de referência"

linha 184
	- Alterar "tabla" para "tabela"
	
linha 211
	-  acrescentar no fim: "Qualquer contagem prevê que a palavra possa estar no  início ou no meio da frase."

linha 215
	- alterar "usaremo" para "temos"
	
linha 219
	- sugiro altera para detectar limites de frases
	
linha 253
	- Alterar "se parece com o que se estava esperando; usando a segunda linha" para "é o esperado, a segunda linha de comando serve"
	
linha 287
	- Alterar "Isto pode ser um pouco incomodo" para "Isto pode ser esforçoso" 
	- Alterar "de fazer isto" para "de o fazer"
	
linha 311
	- Recomendo tirar o gerundio e passar para a Analisar
	
linha 319
	- Alterar "Aqui," para "Agora"
	- Alterar "arquivo" para "ficheiro" -- esta é importante porque se prende com as regras de uniformização do PHpt
	- Alterar "se torna" para "é"
	
linha 323
	- Alterar "modificado para outros endereços" para "aproveitado para outros recursos"
	
linha 357
	- Sugiro colocar a nota de tradução 9 no fim da linha 346
	
linha 377
	- estando os dados e exemplo em inglês acho mais intuitivo ter as palavras em inglês - talvez com a tradução a seguir
	- em relação ao ficheiro de contagem de palavras se calhar é conveniente acrescentar uma referência de como o ficheiro foi copiado para o Programming Historian e no repositorio original tem outro nome.

linha 386
	- Alterar porcentagem para percentagem

linha 390
	- Alterar "chamada "palavra"." para "chamada word (palavra)." - para assegurar que conseguem estabelecer a relação com as tabelas do exercício
	
linha 401
	- Acrescentar "- frequency -" a seguir a "segunda nova coioluna"
	- acrescentar "apenas" antes de "aparecem"
	
linha 472
	- tendo em conta o espirito do PH de ter as acções sugiro alterar para "Sumariar o documento"

linha 529
	- Alterar "mas ele ajuda a dar" para "mas ajuda a dar"
	- Alterar "um bom título e resumo para um documento que não os tenha" para "um título ad-hoc ou resumo para um documento que não tenha estas informações"

linha 563
	- Alterar "Uma vez feito isso, pode-se usar" para "Uma vez feito, pode usar"

linha 654
	- colocar a seguir a `median` (mediana)
	- alterar "muito afectada pelo erro de segmentação que pode" por "muito afectada por possíveis erros de segmentação que podem"
	
linha 668
	-alterar media_comprimento para mediana_comprimento
	-alterar "Comprimento médio" para "Mediana do comprimento"

linha 671
	- alterar "Comprimento mediano" para "Mediana do comprimento das frases"
	
linha 673
	- alterar "nos mais de dois séculos" para "nos dois séculos"
	- alterar "não se destaquem em se tratando da média" para "não se destaquem em termos de mediana" --- esta correcção é importante porque estamos a apresentar a mediana
	
linha 680
	- alterar media_comprimento para mediana_comprimento
	- alterar "Comprimento médio" para "Mediana do comprimento"

linha 671
	- alterar "Comprimento mediano " para "Mediana do comprimento das frases"
		
linha 715
	- alterar "pode atrasar em" para "pode demorar"
	
linha 751
	- alterar "Como já observamos" para "Como já foi referido"
	- alterar "entretanto" para "no entanto"
	- alterar "resumo geral do nível" para "resumo geral e de alto nível"
	- alerar "Obama voltou a se preocupar" para "Obama voltou a preocupar-se"
	
linha 765
	-alterar "modelagem de tópicos" para "modelagem por tópicos"

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado @Msaguedes!

**Comment by dianarebelorodriguez** [comment]
Caros e caras, boa tarde!

Primeiramente, muito obrigada pelo envolvimento de @romulopredes e @DanielAlvesLABDH e pela detalhada revisão de @Msaguedes . Peço desculpas pela minha demora em retornar, estava trabalhando em outras traduções. Fiz todas as mudanças sugeridas, tenho apenas uma dúvida em relação a esta correção e gostaria mais uma vez da ajuda de vocês para saber como proceder.

linha 41
- Para o link da lição ver se já está traduzida ou no processo porque o ideal era que ficasse com o nome e link para a versão portuguesa
       --> sim, a lição foi traduzida, mas ainda não foi publicada. Alterei o nome para o traduzido, mas mantive o link da lição original até que essa tradução seja publicada. Deveria fazer diferente?

Obrigada também @JimmyMedeiros82 por organizar essa troca e pela primeira revisão. Abraços!

**Comment by JimmyMedeiros82** [comment]
Muito obrigado a todos pela dedicação ao trabalho de tradução, revisão e publicação da lição! Agradeço à @dianarebelorodriguez @romulopredes @Msaguedes e @DanielAlvesLABDH ppelo trabalho desenvolvido.

Vou fechar esta issue e prosseguir com a publicação da lição.

**Comment by DanielAlvesLABDH** [comment]
Fiz pequenas correcções no cabeçalho da lição e no texto. Julgo que está pronto para seguir. Obrigado a todos e em especial à @dianarebelorodriguez pelo excelente trabalho desenvolvido.

**Comment by DanielAlvesLABDH** [comment]
Caríssimos, temos mais uma lição publicada, já com DOI https://dx.doi.org/10.46430/phpt0013. Obrigado a todos pela colaboração. @JimmyMedeiros82 o bot do Twitter já pode ser actualizado e depois podemos fechar este ticket. 😎

**Comment by JimmyMedeiros82** [comment]
Ótima notícia, Daniel! Muito contente com esta nova publicação. 

Eu ainda não tenho acesso à planilha e acredito que o motivo seja por usar meu e-mail do Yahoo no GitHub e a planilha ser editável com uma conta do Gmail. Elaborei o conteúdo a ser inserido no bot:
1. Analisar corpus textual com o R ficou mais fácil com a tradução da lição ‘Processamento Básico de Texto em R’ feita pela @rebelorodriguez  https://programminghistorian.org/pt/licoes/processamento-basico-texto-r
2. A lição ‘Processamento Básico de Texto em R’ traduzida pela @rebelorodriguez explica como analisar corpus textual no R. https://programminghistorian.org/pt/licoes/processamento-basico-texto-r 

Conseguindo acessar, insiro na planilha.

**Comment by DanielAlvesLABDH** [comment]
É provável que seja isso @JimmyMedeiros82. Quanto às mensagens acho que ficaram óptimas. Mude só o link, usando o DOI https://dx.doi.org/10.46430/phpt0013

**Comment by jenniferisasi** [comment]
Olá @JimmyMedeiros82 e @DanielAlvesLABDH! Acho que apenas os editores principais precisam ter acesso à planilha. No entanto, posso tentar adicionar você também com seu e-mail do Yahoo, pois vejo que Daniel está conectado com sua conta institucional.

**Comment by DanielAlvesLABDH** [comment]
Olá @jenniferisasi , obrigado pela ajuda. Julgo que a Joana, a Danielle e o Josir (editores) têm acesso, e na lista de verificação final das directrizes de editores é referido que cabe a eles editar o bot do Twitter.

**Comment by jenniferisasi** [comment]
Acabei de enviar o convite para @JimmyMedeiros82, vamos ver se funciona.

**Comment by JimmyMedeiros82** [comment]
Conteúdo adicionado no bot! @jenniferisasi  e @DanielAlvesLABDH obrigado pela ajuda!

**Comment by DanielAlvesLABDH** [comment]
Óptimo Jimmy. Podemos fechar isto então... Abraço e obrigado!
