### ISSUE TITLE
Tradução da lição "Using Geospatial Data to Inform Historical Research in R"

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#389]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Using Geospatial Data to Inform Historical Research in R' por @dianarebelorodriguez . A lição a traduzir está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/utilizacao-dados-geoespaciais-r.md).

O editora desta tradução serei eu, @joanacvp . 

Para promover uma publicação rápida desta lição traduzida, irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação do tradutor, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by joanacvp** [comment]
Hello @Anisa-ProgHist! @dianarebelorodriguez just translated this lesson, but she had some problems in running the last code and in opening the file (she had to change it). Is there a problem with this lesson? Who can we talk to to solve the problems Diana reported? Thank you very much for your help!

**Comment by anisa-hawes** [comment]
Thank you for getting in touch @joanacvp and @dianarebelorodriguez ! 

The best way forward will be to open a new Issue in the Jekyll repository and tag it with the Lesson Maintenance Label.  I am working through these Issues. 

When you create a new Issue within Jekyll, you will be asked for the following key information:

- The full title of the lesson: *Using Geospatial Data to Inform Historical Research in R*
- The system you are using (Mac, Linux, Windows)
- Version numbers of the relevant software you are using
- The exact steps you took that caused the problem, with as much detail as possible.

If @dianarebelorodriguez found a solution that enabled her to complete the lesson, the details of that solution will also be very important to include. 

Please let me know if you have any questions.

**Comment by dianarebelorodriguez** [comment]
The full title of the lesson: Using Geospatial Data to Inform Historical Research in R
The system you are using: Windows
Version numbers of the relevant software you are using: R version 4.1.0 (2021-05-18)
The exact steps you took that caused the problem, with as much detail as possible: I had trouble in one of the very first commands, this one: [ `County_Aggregate_Data <- st_read("./data/County1990ussm/")` ]. I solved it by writing the command like this: [ `County_Aggregate_Data <- st_read("Archive/geospatial-data-analysis/County1990ussm")` ]. With the original form, R was not recognizing the files. There was another problem, at the end of the lesson, with the last plot. I was able to do it, but the graphic result was terrible, nothing like the original image. I tried with my translated code first, but then I just copied and pasted the original code and the result was the same. You can find the plot attached in here. Thank you!
![Geoespacial final plot](https://user-images.githubusercontent.com/84020924/128236472-78419990-32b6-4404-bf24-08548b956f0b.jpeg)

**Comment by anisa-hawes** [comment]
Thank you for this information, @dianarebelorodriguez. I will go ahead and create a new Issue in our Jekyll repository. I'll let you know as soon as I have tested this. Are you working to a deadline with your translation?

**Comment by anisa-hawes** [comment]
Thank you @joanacvp and @dianarebelorodriguez. The Lesson Maintenance Issue ticket can be found [here](https://github.com/programminghistorian/jekyll/issues/2222). I will keep you both up to date.
