### ISSUE TITLE
Tradução da lição "Manipulação e transformação de dados em R"

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#397]
O Programming Historian em português recebeu a proposta de tradução da lição 'Manipulação e transformação de dados em R' por @ianaraujo  
A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/manipulacao-transformacao-dados-R.md). E as imagens da lição estão em (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/manipulacao-transformacao-dados-R).

A lição original pode ser encontrada em https://programminghistorian.org/en/lessons/data_wrangling_and_management_in_R

O Ian Araujo fez uma bela contribuição ao Programming Historian em português. Muito grato pela parceria.

A Suemi Higuchi @suemi-higuchi será a editora desta tradução.
A revisão da tradução ficará sob responsabilidade da @daniellesanchesDH e mais uma pessoa a ser indicada. Assim que for definida, a Suemi adicionará a pessoa neste ticket.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões na caixa de comentários para que O Ian possa acompanhar e responder.
O ideal é o Ian realizar as modificações após as sugestões dos revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação do tradutor, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Política anti-assédio:
_
Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by suemi-higuchi** [comment]
Olá @DanielAlvesLABDH e @joanacvp , vocês conseguem pensar em alguém de Portugal para a revisão desta lição? Apesar da dificuldade ser média, ela é bem tranquila. O @ianaraujo utilizou dados do Gapminder para adequar os exemplos existentes e ficou muito bom.

**Comment by JimmyMedeiros82** [comment]
Prezados, faremos uma mudança nos procedimentos para tradução desta lição. 
Eu ficarei como o editor desta tradução feita pelo @ianaraujo
A @daniellesanchesDH  e a @suemi-higuchi ficarão responsáveis pela revisão da tradução.

**Comment by suemi-higuchi** [comment]
Parabéns ao Ian que fez um ótimo trabalho! A lição é bastante longa e a adaptação dos exemplos com uso de dados do Gapminder ficou excelente. Testei todo o código e abaixo estão minhas sugestões.  

* Sobre o título: difícil traduzir wrangling, mas ao invés de "transformação" que tal "organização" ou "controle"? Ficaria algo como "Manipulação e controle de dados no R"  

* Não há ainda a tradução do resumo. Minha sugestão: "Esta lição explora como os investigadores podem tornar seus dados ordenados, entender os pacotes R para manipular dados e conduzir análises básicas de dados."

* É preciso rever as URLs das imagens.

* Como ainda não conhecia o passo-a-passo, eu havia feito a edição da revisão diretamente no arquivo markdown do Ian. Talvez até ajude ver o texto final revisto, principalmente as notas extras de rodapé: https://github.com/suemi-higuchi/programming-historian/blob/main/lesson_revised_1.md

#### Na seção "Premissas":
* Linha 20: substituir "Premissas" por "Requisitos";
* Linha 23: substituir "Esta lição considera premissas básicas acerca do seu" por "Nesta lição assumimos que você possui algum"; "Se você" por "Se ainda"; "eu sugiro que complete-a primeiro" por "sugerimos que o faça primeiro"; "recomendo dar uma olhada nos" por "recomendamos os";

#### Na seção "Objetivos da lição":
* Linha 30: excluir o auxiliar "vai";
* Linha 32: Substituir "Saber manipular dados para organizá-los no formato “tidy” e entender porque" por "Saberá como tornar seus dados bem ordenados (*tidy*) e entenderá por que";
* Linha 33: Substituir "Entender" por "Terá assimilado";
* Linha 34: Substituir "Se familiarizar" por "Estará familiarizado"; "operador pipe" por "operador *pipe* `%>%`";  "obsevar como ele te auxiliará" por "verá como ele pode auxiliar";
* Linha 35: Substituir "Aprender a trabalhar com exemplos básicos de manipulação de dados, a fim de gerar experiência com análise de dados exploratória" por "Terá ganho experiência com análise exploratória de dados através de exemplos básicos de manipulação de dados";

#### Na seção "Introdução":
* Linha 40: Substituir "por aí" por "disponíveis em todo lugar"; excluir "um"; substituir "preferível" por "adequado"; "da forma como foi" por "conforme";
* Linha 45: "registro" por "unidade de observação"; todos os "deve estar" por "está";
* Linha 49: '"permite utilizar uma série de ferramentas padrões para a limpeza dos dados e solução dos" por "fornece um esquema padrão e um conjunto de soluções para lidar com alguns dos"; "bases de dados “bagunçadas”:" por "datasets “mal-arranjados”, como por exemplo:";
* Linha 51: "das" por "de"; "não como" por "ao invés de"; "nome de variável" por "nomes de variáveis";
* Linha 54: "Vários registros de categorias diferentes" por "Unidades de observação de diferentes categorias";
* Linha 57: "O mais importante:" por "Talvez o mais importante seja que"; 'desenhadas especificamente para trabalhar com dados organizados, "tidy"' por 'concebidos para trabalhar especificamente com dados neste formato "tidy"'; 'nossos inputs e outputs são "tidy"' por "os dados de entrada e de saída estão bem organizados"; "ferramental" por "conjunto de ferramentas"; "problema" por "questões"; "bases de dados" por "*datasets*"; "conforme nossa necessidade" por "conforme considerarmos mais adequado";
* Linha 63: Sugiro incluir esta nota explicativa para a Gramática dos Gráficos: "[^1]: A lição original faz referência ao livro “[The Grammar of Graphics](https://www.springer.com/us/book/9780387245447)” (2005) de Wilkinson]";
* Linha 64: "fácil" por "fáceis";
* Linha 66: 'Você deve instalar, se ainda não instalou, e carregar o "tidyverse"' por 'Você deve instalar o "tidyverse", se ainda não o fez, e carregá-lo'; "que você" por "de que"; "em suas respectivas plataformas" por "compatíveis com o seu sistema operacional";
* Linha 69: "rodar" por "executá-lo"; 

#### Na seção "Um exemplo do dplyr em ação"
* Linha 80: "Vejamos um exemplo de como o dplyr pode auxiliar historiadores.  Vamos utilizar o pacote "dados"[^2] e importar alguns indicadores socioeconômicos de países entre 1952 e 2007.";
* Linha 80: Sugiro incluir esta nota explicativa para o pacote *dados*: "[^2]:O pacote "dados" disponibiliza a tradução de conjuntos de dados originalmente em inglês encontrados em outros pacotes de R. Está disponível em https://github.com/cienciadedatos/dados";
* Linha 82: Antes das instruções, sugiro incluir "O pacote "remotes" permite a instalação de pacotes R a partir de repositórios remotos, incluindo o GitHub, como é o caso de "dados".";
* Linha 90: "Para obter a base de dados que vamos utilizar, através do" por "Para termos acesso ao *dataset* "dados_gapminder" que se encontra no";
* Linha 92: "Designa a base de dados" por "Atribui o *dataset*"; 
* Linha 95: Como se trata de um dataset diferente do da lição original, sugiro incluir no início do parágrafo: "Os dados [Gapminder](https://www.gapminder.org/) contêm a progressão de países ao longo do tempo, observando as estatísticas de alguns índices.";
* Linha 97: "Vamos utilizar" por "Para isso utilizaremos'; "afim de analisar informações somente" por "que contenham apenas informação"; "a informação produzida" por "tais dados"; "poder do" por "que é possível fazer com o";
* Linha 99: Excluir "a base de dados para conter apenas";
* Linha 112: "novos questionamentos" por "questões similares"; excluir ", mas";
* Linha 128: "Fazer rápidas mudanças em nosso código e analisar novamente" por "Promover mudanças rápidas no código e reanalisar"; "melhores questionamentos" por "questões sobre eles"; "de saber quando se aprofundar mais em um assunto e quando voltar atrás, e este é um aspecto onde o R se sobressai.";

#### Na seção Operador Pipe
* Linha 133: ""A Traição das Imagens", uma pintura de um cachimbo com a frase em francês: "isto não é um cachimbo"" por "["A Traição das Imagens"](https://www.renemagritte.org/the-treachery-of-images.jsp), que mostra um cachimbo com a frase "isto não é um cachimbo" (*ceci n'est pas une pipe*, em francês);
* Linha 135: Substituir por "permite que você passe o que está à sua esquerda como a primeira variável em uma função especificada à sua direita. Embora possa parecer estranho no início, uma vez que você aprenda a usar o *pipe* descobrirá que ele torna seu código mais legível, evitando instruções aninhadas. Não se preocupe se estiver um pouco confuso por agora. Tudo ficará mais claro à medida que observarmos os exemplos.";
* Linha 137: "admitir hipoteticamente" por "dizer"; "afim de obter uma" por "antes de calcular a"; "medida válida" por "medição útil"; "ilegível rapidamente" por "difícil de ler";
* Linha 143: Substituir por "Veja que com tantos comandos aninhados fica difícil lembrar de quantos parênteses você precisa no final, tornando o código complicado de ler. Para atenuar esse problema, algumas pessoas criam vetores temporários entre cada chamada de função.";
* Linha 163: "pode rapidamente bagunçar" por "pode se tornar confuso";
* Linha 191: Como isso já foi explicado anteriormente, excluir a frase "contendo informações dos avanços dos indicadores socioeconômicos, ao longo dos anos, de vários países. Vamos olhar mais uma vez nossos dados:";
* Linha 212: "base de dados" e "base" por "*dataset*";    

#### Seção O que é dplyr
* Linha 217: Substituir por "também é parte do tidyverse, fornecendo funções para manipulação e tranformação dos dados. Porque estamos mantendo nossos dados bem organizados, precisaremos apenas de um pequeno conjunto de ferramentas para explorá-los. Em comparação com o pacote básico do R, usando o dplyr nosso código fica geralmente mais rápido, e há a garantia de que os dados resultantes (*output*) estarão bem ordenados uma vez que os dados de entrada (*input*) também estarão."; 
* Linha 222: Excluir "o banco de dados"; substituir "durante" por "para"; "base de dados" por "*data frame*";
* Linha 287: "requisitos lógicos" por "um teste de requisito";
* Linha 329: "Na verdade" por "Em vez disso"; "base de dados" por "*data frame*";
* Linha 334: "tibble" por "tabela";
* Linha 354: "base de dados" por "conjunto de dados";
* Linha 376: Substituir por "A última função do dplyr que veremos é a `summarise()`, usada geralmente para criar uma tabela contendo dados estatísticos resumidos que podemos plotar.";

#### Seção Conclusão
* Linha 416: "No futuro" por "Além disso".

**Comment by ianaraujo** [comment]
Obrigado, @suemi-higuchi ! Fico feliz que tenha gostado, pois a lição era muito trabalhada em cima dos dados originais e tive que fazer muitas adaptações. Agradeço as sugestões e a revisão detalhada. Quando atualizar a lição, aviso aqui para que seja feita a segunda revisão. @DanielAlvesLABDH

**Comment by JimmyMedeiros82** [comment]
Obrigado @suemi-higuchi . 
@ianaraujo vamos aguardar a avaliação da @daniellesanchesDH para prosseguir com os ajustes finais na lição.

**Comment by ianaraujo** [comment]
Acabei de fazer um pull request (https://github.com/programminghistorian/ph-submissions/pull/413) adicionando as alterações sugeridas pela revisora @suemi-higuchi. Mais uma vez, Suemi, agradeço pela revisão. Elevou muito o nível da tradução. 

Em relação ao título da lição, optei por manter o mesmo,  usando o termo "transformação" ao invés de "controle". Busquei a tradução de wrangling e - de fato - é um termo difícil. No livro "R para Data Science", versão traduzida do https://r4ds.had.co.nz/, por exemplo, eles não traduzem e usam o termo em inglês. Mas na versão original do livro, os autores usam "transformation" e "wrangling" como sinônimos ou processos semelhantes. Então, optei por manter "transformação" no título, e mantive "controle" em algumas partes do texto.

Sobre as URLs das imagens, me parecem corretas. Criei uma pasta para lição e, dentro dela, outra pasta chamada "img", para facilitar. No entanto. não consigo visualizar as imagens em nenhum dos softwares de edição de markdown que testei. Acredito que o código usado ({% include figure.html filename="img/brasil_argentina_populacao.png" caption="Gráfico da população de Brasil e Argentina, ao longo dos anos" %}) seja visível apenas na web, quando a lição for para o site. @DanielAlvesLABDH pode tirar essa dúvida?

No mais, aguardo o pull request ser aceito e, assim que for, publico aqui o link da nova versão da tradução para encaminhar a segunda revisão.

Abraços

**Comment by ianaraujo** [comment]
A nova versão da tradução, revisada, encontra-se em: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/manipulacao-transformacao-dados-R/manipulacao-transformacao-dados-R.md

**Comment by suemi-higuchi** [comment]
Mais uma vez parabéns, @ianaraujo, é uma lição bastante trabalhosa e você fez uma tradução e adaptação dos dados excelentes! Por mim está ótima a explicação do título q você deu :)

**Comment by JimmyMedeiros82** [comment]
Olá @ianaraujo o trabalho ficou muito bom! 
Agora é aguardar a revisão da @daniellesanchesDH

**Comment by DanielAlvesLABDH** [comment]
Obrigado @ianaraujo e @suemi-higuchi. Quanto à visualização das imagens é mesmo assim, funciona no final. Veja o ponto 4 destas directrizes https://programminghistorian.org/pt/directrizes-tradutor#submeter-uma-li%C3%A7%C3%A3o-traduzida

**Comment by JimmyMedeiros82** [comment]
Oi @daniellesanchesDH você consegue fazer a revisão da lição? 
Prefere sugerir alguém que possa contribuir?

**Comment by JimmyMedeiros82** [comment]
Olá @joanacvp peço mais uma contribuição sua para indicar alguém para ser revisor desta lição em substituição à Danielle Sanches. Você topa ser a revisora? Ou prefere indicar alguém que possa colaborar conosco?

**Comment by joanacvp** [comment]
Olá @JimmyMedeiros82. Eu posso fazer a revisão, sem qualquer problema :)

**Comment by JimmyMedeiros82** [comment]
@joanacvp , muito contente por mais uma colaboração sua!

**Comment by joanacvp** [comment]
Olá a todos! É um gosto colaborar nesta revisão de tradução. Seguem as minhas notas:

- [x] Abstract: “usando a linguagem” = “usando esta linguagem”
- [x] Colocar “(em inglês)” em todos após todos os links que remetem para páginas nessa língua
- [x] Linha 28 – em “Nesta lição consideramos que você já” retirar o “você”
- [x] Linhas 28-29 - traduzir o título da lição para PT e colocar no fim entre parênteses (em inglês)
- [x] Linha 40 – em “Os dados que você encontra” retirar o você
- [x] Linha 40 – “raramente estão em formato” = “raramente estão no formato”
- [x] Linha40 – “e você precisará manipulá-los” retirar o “você”
- [x] Linha 40 – “articulada” = “apresentada”
- [ ] Linha 44 – “está em uma linha” = “está numa linha”
- [ ] Linha 45 – “está em uma coluna” = “está numa coluna”
- [x] “Linha 60 “ - que torna nosso código mais legível” = “que torna o nosso código mais legível”
- [x] Linha 65 – em “Você deve instalar” retirar o “você”
- [x] Linha 66 – “Copie o código a seguir em seu RStudio” = “Copie o código a seguir para o seu RStudio”
- [x] Linha 68 – “Para executá-lo, você precisa selecionar” = “Para executá-lo, precisa de selecionar”
- [ ] Linha 78 - “socioeconômicos” = “socioeconómicos” (penso que estamos a adotar os acentos em português)
- [x] Linha 90 – “dataset "dados_gapminder" que se encontra no pacote "dados", b” – “dataset "dados_gapminder", que se encontra no pacote "dados", b” 
- [ ] Linha 92 – “e atribui a ele os elementos” = “e atribui-lhe os elementos”
- [x] Linha 96 – em “após importar o dataset, você notará” retirar o “você”
- [x] Linha 96 – colocar “per capita” em itálico
- [x] Linha 96 – “Os dados já estão em um formato” = “Os dados já estão num formato”
- [x] Linha 98 – em “não se preocupe se você não” retirar o “você”
- [x] Linha 128 “quando se aprofundar mais em um tema” “quando aprofundar mais um tema”
- [ ] Linha 132 – “precisamos entender” = “precisamos de entender”
- [x] Linha 132 – “Este operador é parte do pacote magrittr, criada por Stefan Milton Bache e Hadley Wickham, e está incluída no tidyverse” - “Este operador é parte do pacote magrittr, criado por Stefan Milton Bache e Hadley Wickham, e está incluído no tidyverse”
- [x] Linha 132 – “Seu nome é” = “O seu nome é”
- [x] Linha 134 – em “permite que você passe” retirar o “você”
- [ ] Linha 134 – “variável em uma função” = “variável numa função”
- [x] Linha 134 – em “uma vez que você aprende a usar” retirar o “você”
- [ ] Linha 134 – em “descobrirá que ele torna seu código mais legível” retirar o “ele” 
- [x] Linha 142 – em “de quantos parênteses você precisa no final” retirar o “você”
- [x] Linha 162 – em “Embora você obtenha o mesmo resultado” retirar o “você”
- [x] Linha 162 – “em se você esquecer” retirar o “você”
- [ ] Linha 162 - em “O operador pipe faz esse trabalho por você” substituir “você” por “si”
- [x] Linha 168 - em “anteriores e você pode torná-lo” retirar o “você”
- [x] Linha 170 – “operador ao final da linha” = “operador no final da linha”
- [x] Linha 179 – em “e você quiser” retirar o “você”:
- [x] Linha 192 – “antes de proceder abaixo” = “antes de proceder conforme abaixo”
- [x] Linha 211 – em “Como você pode observar” retirar o “você” 
- [x] Linha 211 - colocar “per capita” em itálico
- [x] Linha 214 - “usando o dplyr nosso código” =usando o dplyr o nosso código”
- [x] Linha 214 – “o dplyr torna nosso código” = “o dplyr torna o nosso código”
- [x] Linha 214 – “filtrar (filter), selecionar (select), ordenar (arrange), modificar (mutate) e sumarizar (summarise)” – uma vez que se usam os títulos em inglês abaixo, colocaria ao contrário, com destaque do inglês e o português entre parênteses
- [x] Linha 218 – “para nossa análise” = “para a nossa análise”
- [ ] Linha 303 – “colocá-las em uma única coluna”  = “coloca-las numa única coluna”
- [x] Linha 323 – em “Se você deseja manter os dados” retirar o “você”
- [x] Linha 349 – “Atualmente, nosso conjunto” = “Atualmente, o nosso conjunto”
- [x] Linha 371 – “a média da expectativa de vida dos países” = “a média da expectativa de vida nos países”
- [x] Linha 395 – “mudança em nosso código” = “mudança no nosso código”
- [x] Linha 409 - em “Posteriormente, você provavelmente vai querer” retirar o “você”
- [x] Linha 409 - em “Além disso, você deve buscar retirar” o “você”
- [x] Linha 409 - “principais problemas que você irá encontrar” = “principais problemas que poderá encontrar”

Parabéns @ianaraujo! Fez um óptimo trabalho!

**Comment by JimmyMedeiros82** [comment]
@joanacvp e @suemi-higuchi muito agradecido pelas revisões detalhadas. 
Certamente contribuíram para deixar a lição mais adequada ao público. 

@ianaraujo aguardamos os ajustes, em seu tempo. 
Abraços a todos!

**Comment by ianaraujo** [comment]
@joanacvp agradeço pela ótima revisão e pelas sugestões de melhoria. Já incorporei a maioria delas ao texto atualizado, que se encontra [aqui](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/manipulacao-transformacao-dados-R/manipulacao-transformacao-dados-R.md). A tradução dos títulos das seções foi algo que não passou pela minha cabeça e, sem dúvidas, contribui muito para a qualidade da lição.  

Eu traduzi também o título da lição "R Basics with Tabular Data", conforme sugerido, para "R Básico utilizando Dados Tabulares". Acha que ficou bom? Alguma sugestão em relação à essa tradução?

Acredito que, resolvendo esse único ponto, se encerra o processo de revisão. Aguardo intruções do que mais eu puder fazer. Obrigado @suemi-higuchi e @joanacvp pela revisão, mais uma vez.

**Comment by joanacvp** [comment]
@ianaraujo óptimo trabalho! Mais uma vez os meus parabéns pela tradução!
Penso que "R Básico utilizando Dados Tabulares" fica bem.
Em relação à expressão "você", nós em PT não utilizamos da mesma forma, o que se reflectiu nos meus comentários. Junto dos alunos PT optámos por lhes pedir que não usassem. @JimmyMedeiros82 e @DanielAlvesLABDH deixamos ficar?

**Comment by DanielAlvesLABDH** [comment]
Olá a todos e todas. Obrigado pelo trabalho de tradução e revisão. Realmente esta não é uma lição fácil. Quanto ao uso do "você" o ideal seria uniformizar de acordo com o que temos feito com as lições já publicadas.
Faço ainda uma sugestão de alteração. Quando o @ianaraujo fala na tradução do título da lição para "R Básico utilizando Dados Tabulares" e indica "(em inglês)", agora já pode usar a referência da lição que nós já temos publicada com o nome "Noções básicas de R com dados tabulares" (https://programminghistorian.org/pt/licoes/nocoes-basicas-R-dados-tabulares) e eliminar a indicação (em inglês).

**Comment by JimmyMedeiros82** [comment]
@ianaraujo quando possível, por favor, faça este ajuste indicado pelo Daniel e seguiremos para finalizar a lição!

**Comment by ianaraujo** [comment]
Obrigado @DanielAlvesLABDH por mais estes ajustes. Fiz as alterações recomendadas, incluindo a substituição do nome da lição traduzida "R Básico utilizando Dados Tabulares", que não sabia que já tinha sido publicada. Aguardo as demais intruções para finalizarmos a publicação da lição. 

Desejo a todos nós um execelente ano de 2022 !!

**Comment by JimmyMedeiros82** [comment]
@ianaraujo as mudanças estão adequadas. Te peço apenas mais um ajuste. Na linha 64, coloque "Instale o "tidyverse", se ainda não o fez, e carregá-lo antes de começarmos. Além disso, certifique-se de que possui instaladas a". Aí seguimos para publicação.

**Comment by ianaraujo** [comment]
@JimmyMedeiros82, feito!

**Comment by JimmyMedeiros82** [comment]
Ficou ótimo, Ian! Belo trabalho. 

coloco o link para o arquivo .md, pois o informado no início desta conversa está corrompido. https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/manipulacao-transformacao-dados-R/manipulacao-transformacao-dados-R.md 

@DanielAlvesLABDH temos mais uma lição pronta para publicação.

**Comment by DanielAlvesLABDH** [comment]
Excelente trabalho, todos! Obrigado por mais essa colaboração! Vou ver assim que possa

**Comment by DanielAlvesLABDH** [comment]
Caros @ianaraujo e @JimmyMedeiros82, eu fiz um primeiro ajuste no código da tradução, essencialmente para corrigir o cabeçalho. Contudo, ao rever o resto do texto verifiquei que o Ian alterou os dados usados na lição original (acho que há também um erro com o link de acesso a esses dados, parece-me) e isso levou a alterações significativas do texto face ao original em inglês. Essencialmente, a partir da secção "Um exemplo do dplyr em ação".
Por princípio geral, sempre que for possível fazer a adaptação das fontes ou dados usados para exemplos que sejam mais próximos do público que fala português isso é óptimo. Contudo, estamos a fazer uma tradução e essa alteração ao original deve ser mencionada. Temos feito isso noutras lições com a introdução de uma linha antes das alterações começando por "Nota de tradução:...". Acho que seria o caso aqui também, talvez imediatamente a seguir ao título dessa secção.
Outro aspecto a ter em conta é que algumas destas lições têm sequência ou relação com outras, sendo por vezes usados ou mencionados pedaços de código e/ou conjuntos de dados de outras lições.
Nesse sentido, é preciso que o Ian reveja estes aspectos. Peço ajuda também às revisoras, @suemi-higuchi e @joanacvp (a quem agradeço desde já a colaboração), para fazerem uma última revisão a seguir no sentido de evitar inconsistências e de referenciar as mudanças que sejam mais significativas face ao original.
Obrigado a todos/as!

**Comment by DanielAlvesLABDH** [comment]
Já actualizei o DOI da lição também

**Comment by JimmyMedeiros82** [comment]
@ianaraujo vamos fazer esta última revisão e ajuste, se necessário?

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH já incorporei a lição ao bot do Twitter.

**Comment by JimmyMedeiros82** [comment]
E @DanielAlvesLABDH sobre a tradução da lição e a adequação da programação para um tema próximo ao português, penso em duas possibilidades de ajuste. Uma opção é refazer parte do tradução, trazendo a programação original e ambientada aos EUA, precisando ajustar o texto da lição para tornar fidedigna à lição original. 

A outra opção é manter o conteúdo como está, com os dados próximo ao interesse dos brasileiros e portugueses e colocar uma observação no início da lição de que o conteúdo da programação foi alterado e por conta disso temos parte do texto, os exemplos e as interpretações dos dados diferente da lição original. Apesar disso, a estrutura da lição é exatamente igual, como os tipos de dados e as análises desenvolvidas são exatamente iguais. Mudamos, por exemplo comparação Mississipi e Virgínia por Brasil e Argentina. Todo o conteúdo informado é replicado, mas os exemplos são diferentes. 

O @ianaraujo utilizou dados públicos e gratuitos do Gapminder, não restringindo ao Brasil ou Portugal. Talvez, a única diferença seja a ausência de importar dados via csv. Caso seguimos pela segunda opção, sugiro adicionar essa opção, algo  como "se você tiver dados em .csv, o procedimento de importação é...", mantendo os dados do Gapminder, como já estão. 

Qual melhor percurso a seguir? Conforme sua decisão, adequamos para publicar mais uma lição.

**Comment by DanielAlvesLABDH** [comment]
Caros, desculpem o atraso na resposta. Obrigado pelos esclarecimentos @JimmyMedeiros82. Julgo que a opção 2 é a preferível, ficamos com uma lição mais "em português", incluindo nos dados. Mas além da indicação dessa mudança no início, concordo que será melhor incluir também a nota que referes sobre o .csv e outras que o @ianaraujo considerar adequadas para sinalizar alterações significativas. Depois disso peço à @suemi-higuchi e à @joanacvp se podem fazer uma última revisão, por favor.

**Comment by DanielAlvesLABDH** [comment]
> @DanielAlvesLABDH já incorporei a lição ao bot do Twitter.

Apaguei a linha na tabela do bot do Twitter. Só podemos incluir aí depois da lição estar publicada.

**Comment by DanielAlvesLABDH** [comment]
Fiz mais algumas correcções e mudei a localização do ficheiro .md e das imagens. Actualizei os links no comentário inicial do ticket. Relativamente às imagens devemos seguir as directrizes que estão aqui: https://programminghistorian.org/pt/directrizes-editor#d-verifique-as-imagens

**Comment by JimmyMedeiros82** [comment]
@ianaraujo podemos seguir com a opção 2, indicada acima?

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH fiz o acréscimo da nota explicativa da tradução da lição. 
Ela está pronta para ser publicada.

**Comment by DanielAlvesLABDH** [comment]
Desculpem a longa pausa nesta revisão. Vou iniciar o processo de publicação. Obrigado uma vez mais a todos/as!

**Comment by DanielAlvesLABDH** [comment]
Concluí a revisão, fazendo alguns ajustes, essencialmente nas imagens e nas notas. Já tenho o DOI e por isso vou passar para publicação.

**Comment by DanielAlvesLABDH** [comment]
Caros/as a lição já está publicada. Vamos em 35! Muito obrigado ao @ianaraujo por mais um excelente trabalho e à @suemi-higuchi e @joanacvp pelas revisões feitas. @JimmyMedeiros82 um abraço pela fantástica colaboração. O DOI https://doi.org/10.46430/phpt0035 não está ainda activo, deve ficar brevemente, mas podemos actualizar já o bot do Twitter e fechar o ticket.

**Comment by JimmyMedeiros82** [comment]
Ótima notícia! Bot atualizado e parabéns a todos pela colaboração.

**Comment by suemi-higuchi** [comment]
Muito bacana ver a lição no ar! Parabéns novamente ao Ian e a todos os demais!
Abraços
Suemi

De: Jimmy Medeiros ***@***.***>
Enviada em: quarta-feira, 30 de novembro de 2022 11:32
Para: programminghistorian/ph-submissions ***@***.***>
Cc: Suemi Higuchi ***@***.***>; Mention ***@***.***>
Assunto: Re: [programminghistorian/ph-submissions] Tradução da lição "Manipulação e transformação de dados em R" (#397)


Ótima notícia! Bot atualizado e parabéns a todos pela colaboração.

-
