### ISSUE TITLE
Tradução da lição "Noções básicas de R com dados tabulares"

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#398]
O Programming Historian em português recebeu a proposta de tradução da lição 'Noções básicas de R com dados tabulares' por @dianarebelorodriguez. A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/nocoes-basicas-R-dados-tabulares.md).

E a lição original está em https://programminghistorian.org/en/lessons/r-basics-with-tabular-data

Novamente, a Diana fez um belo trabalho! Reforço o agradecimento pela contribuição.
Eu serei o editor da tradução. E junto com o @romulopredes e mais uma pessoa a ser indicada durante esta semana, faremos a revisão da tradução.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões na caixa de comentários para que a Diana possa acompanhar e responder.

O ideal é a Diana realizar as modificações após as sugestões dos revisores.

Importante lembrar, todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Política anti-assédio:
_
Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente acadêmico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do gênero, identidade e expressão de gênero, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by JimmyMedeiros82** [comment]
Olá @DanielAlvesLABDH e @joanacvp vocês poderiam indicar alguém para colaborar com a revisão desta lição? 
É uma lição simples sobre o uso do R.

**Comment by romulopredes** [comment]
Olá! Mais um bom trabalho feito pela @dianarebelorodriguez, parabéns!

Me adiantei e fiz apenas alguns apontamentos a serem revistos. Em ordem no texto:

- (Primeira) Seção Prática, Letra B: 
Original: "Isto significa que mais 302.000 pessoas viajaram em voos internacionais em janeiro de 1960 do que em janeiro de 1950."
Sugestão: Isto significa que, em janeiro de 1960, 302.000 pessoas a mais viajaram em voos internacionais do que em janeiro de 1950.

- (Segunda) Seção Prática, item 3: 
Original: "Qual é o tamanho (lenght) da sequência na pergunta 2?"
Revisão: "lenght" --> length

- (Matrizes) Seção Prática, função apply:
Original: "Este exemplo mostra a função apply utilizada na matriz Crime para calcular a média (mean) de cada fila e, portanto, o número médio de roubos..."
Revisão: "fila" --> linha

- (Matrizes) Seção Soluções:
Original: "O uso de matrizes pode ser útil quando se está trabalhando com pequenas quantidades de dados."
Sugestão: "O uso de matrizes pode ser útil" --> Matrizes podem ser úteis quando...

- (Carregar seu próprio conjunto de dados em R): 
Original: "Agora que já praticou com dados simples, pode-se trabalhar com seus próprios dados."
Sugestão: "(...) pode-se trabalhar com seus próprios dados." --> (...) pode trabalhar com seus próprios dados.

- (Carregar seu próprio conjunto de dados em R): 
Original: "definir o cabeçalho ou header = (el archivo equivale a)"
Sugestão: " (el archivo equivale a)" --> (o arquivo equivale a)

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82. Que boa notícia, mais uma lição em andamento. A Diana não tem conta de GitHub? O ideal era associar o user dela aqui. @joanacvp será que o Ivo Veiga poderia dar uma ajuda aqui? Acho que ele percebe de R...

**Comment by JimmyMedeiros82** [comment]
Oi @DanielAlvesLABDH eu marquei a Diana com o user @dianarebelorodriguez. 

Se o Ivo puder contribuir conosco será ótimo!

**Comment by DanielAlvesLABDH** [comment]
Verdade @JimmyMedeiros82 , não tinha reparado 🙃

**Comment by joanacvp** [comment]
Olá. Eu acho que o Ivo seria uma boa opção. Jimmy o e-mail dele é o ivoveiga06@gmail.com

**Comment by dianarebelorodriguez** [comment]
Caros, bom dia! Peço perdão pela minha demora, estava acompanhando a discussão pelo e-mail e esqueci que precisava responder aqui para que todos vissem. Já fiz as alterações propostas pelo @romulopredes, obrigada pela revisão! Também alterei outros termos que acredito que sejam melhores para os colegas de Portugal, como o uso da palavra "ficheiros". Mais uma vez, agradeço o envolvimento de vocês na tradução! :)

**Comment by JimmyMedeiros82** [comment]
Caros, o @ilv2006 vai colaborar conosco fazendo a segunda revisão da lição. 
Ivo, mais uma vez, agradeço a colaboração conosco e com o PH. Peço para indicar as mudanças necessárias nesta página, assinalando as linhas no ficheiro.

**Comment by ilv2006** [comment]
Parabéns pelo trabalho já realizado. Já está muito “acabado”, o que me dificultou, naturalmente, a revisão. Coloco mais abaixo muitas vezes a palavra “talvez” porque as soluções encontradas já são boas e apenas sugiro outras. Fica aberto à discussão até porque nos dois lados do Atlântico pode haver diferenças. 

Uma nota destacada para tod@s:

Até pela sua constante presença, não apenas neste mas também noutros textos que poderão aparecer, seria muito útil encontrar uma tradução mais rigorosa e que soe bem em português para “data points” – “pontos de dados” não me convence.  É uma grande dificuldade de tradução. Infelizmente, para estas questões ligadas ao mundo das ferramentas digitais estou muito mais familiarizado com a língua inglesa do que com a portuguesa. Talvez até já exista uma tradução mais convincente – mas eu não conheço. Ou até já se tenha tornado prática corrente usar “pontos de dados”! 

Dados tabulares 

**Objectivos da lição**

Eu talvez retiraria uma das palavras “mais”, ou seja “mais rápida e eficaz” e não “mais rápida e mais eficaz” – fica mais ágil a leitura embora seja um pormenor 

Penso que “podem ser replicados” é mais conceptualmente exacto neste contexto do que “podem ser reproduzidos”. Mas lá está, não sei se na academia brasileira e o seu uso no Brasil é a mesma coisa      

“que se redirecionem ou revejam funções para projectos futuros” e não “redirecione ou se revise funções”

“da sua caixa de ferramentas” e não “kit de ferramentas”

Talvez “percorrerá algumas“ e não “passará por algumas”

“que se podem” e não “que se pode”

“pesquisa” (mais Brasil) ou “investigação” mas não me parece que seja plural (“pesquisas”)


**Para quem isto é útil?**
Talvez retirar “conjunto de dados maiores” e colocar “conjunto de dados de grande dimensão”. É de difícil tradução....

Talvez “Depois de entendida a forma como se escrevem algumas funções básicas” e não “Uma vez que se entende como escrever algumas”

**Instalar R**

“executado” e não “rodado”? Acho que convinha usar sempre a mesma palavra e lá acima já tinha sido usado “executar” para “run”  

**Usar o Console de R**

“quando se é inexperiente” e não “se quando se é novo”

**Usar conjunto de dados**

“número de passageiros (em milhares) que voaram”
“pressione enter” e não “aperte”
“pressione enter novamente” e não “aperte” para ficar mais próximo do original neste caso

**Funções Básicas**

“valores mínimos e máximos em um conjunto de dados”. Apagar “em um conjunto de dados” pois em 3 frases seguidas aparece e não fica bem. 

 “Isto dará os pontos de dados mínimo e máximo”-  pontos de dados não me soa bem, talvez “dará o valor máximo e mínimo dos dados”

“dois meses juntos”, penso que aqui o “juntos” em português não soa bem – eu retiraria a palavra “juntos”

“R pode fazer mais do que apenas simplesmente aritmética”, talvez colocar antes “R pode fazer muito mais do que simples aritmética” – não é uma tradução literal mas parece-me mais claro e próximo do português corrente (“apenas simplesmente“ não me parece bem)

“É possível criar objetos” – falta o link em “objetos ”

“o valor de janeiro de 1949 em uma variável como Jan1949” - talvez simplificado fique melhor “o valor de janeiro de 1949 como variável Jan1949”

“Para remover um objeto do console” - no original está “variável” e não “objeto”, penso que que se deve seguir o original embora, claro está, não esteja errado. A mesma questão para o “múltiplos objetos”, talvez seguir original embora perceba o ponto da tradução.

“nomeada X” e não “chamada” para manter a coerência 

“com quais pontos se está trabalhando”...confesso que não sei....talvez “com que dados se está trabalhando”?  “com que valores se está trabalhando”?


**Prática**

Vejo que aqui optou-se novamente por “objetos novos” e não “variáveis”. Percebo o sentido pedagógico, e até talvez concorde, mas depois perde-se um pouco de coerência em relação ao original. É apenas uma nota 

**Soluções**

Atenção: se no ponto anterior optou-se por “objetos” terá de ser mantido aqui novamente. Optar por “variáveis” ou “objeto””

“302.000 pessoas a mais viajaram” talvez prefira “viajaram mais 302.000 pessoas”


“nomeado Air49” e não “chamado” para manter a coerência no texto


**Trabalhar com bases de dados maiores**: Atenção que deixou de se traduzir “sets” por “conjuntos” e usou-se antes “bases”. Tendo em conta o uso generalizada de “bases de dados”....para “bases de dados” penso que seria mais útil manter “conjunto de dados” para “data sets”

“Bases de dados maiores”, talvez mudar para “conjunto de dados de grande dimensão”

“tedioso”, sugiro substituir por “entediante” como já foi mais acima usado na tradução

  “Motor Trend” – colocar nome da revista em itálico, como no original 

Substituir “quantos milhas” por “quantas milhas”

“poderiam ser usados” – penso que neste caso não seguir literalmente o original fará mais sentido – ou seja, acho que “poderão ser usados” soa melhor


**Matrizes**
“durante as décadas entre 1670 e 1710” [juntar entre e durante não me parece bem] penso que poderia ficar melhor deixando cair “durante as décadas”, ou seja “analisar o número total de crimes de roubo e furto violento entre 1670 e 1710”

“matrizes podem ser úteis” e não “matrizes pode ser útil”


**Salvar dados em R**
Mudar “con a extensão” para “com a extensão”
“Finalmente, e, finalmente,” eliminar “e, finalmente,” 

**Resumo e passos seguintes**
“habilidades” ou “competências” para “skills”?

**Comment by dianarebelorodriguez** [comment]
Boa tarde, car@s! 
@ilv2006 , muito obrigada por seu olhar atento e suas contribuições! Incorporei as sugestões à lição e acredito que ela esteja pronta para ser publicada!
Aproveito para agradecer mais uma vez a todos que auxiliaram com a revisão. Ótimo trabalho!

**Comment by JimmyMedeiros82** [comment]
Olá @DanielAlvesLABDH temos mais uma lição traduzida, revisada e ajustada.
Podemos seguir para a finalização dela e avançar para a publicação.

**Comment by DanielAlvesLABDH** [comment]
A revisão da tradução está concluída e vou iniciar a publicação. Parabéns e obrigado à @dianarebelorodriguez! Obrigado também ao @romulopredes e ao @ilv2006 pelas revisões!

**Comment by dianarebelorodriguez** [comment]
Muito obrigada a todos! Parabéns pelo trabalho em conjunto!

**Comment by DanielAlvesLABDH** [comment]
A lição está publicada. Mais uma desta colaboração excelente com a Fundação Getúlio Vargas. Chegámos às 15!
Parabéns e obrigado a todos!
@JimmyMedeiros82 o DOI desta lição é https://doi.org/10.46430/phpt0015. Depois de incluído no bot do Twitter podemos encerrar o ticket. Obrigado pelo trabalho!
