### ISSUE TITLE
Proposition de traduction: From HTML to List of Words (part 1)

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#399]
Le Programming Historian en français a reçu la proposition de traduction de la leçon intitulée "From HTML to List of Words (part 1)" de la part de @datalogism. La traduction sera déposée prochainement dans le répertoire des traductions françaises et un membre de l'équipe sera désigné pour en organiser la relecture.

**Comment by datalogism** [comment]
Hello @spapastamkou je viens à l'instant de déposer la traduction [ici](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/du-html-a-une-liste-de-mots-1.md)

**Comment by anisa-hawes** [comment]
Hello all, 

Please note that this lesson's .md file has been moved to a new location within our Submissions Repository. It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/inactives

A consequence is that this lesson's preview link has changed. It is now: [http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/du-html-a-une-liste-de-mots-1](http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/du-html-a-une-liste-de-mots-1)

Please let me know if you encounter any difficulties or have any questions.

Very best,
Anisa

**Comment by spapastamkou** [comment]
Je ferme ce ticket le temps que nous aurons trouvé un membre de l'équipe qui sera en mesure d'effectuer le suivi éditorial. cc @marie-flesch
