### ISSUE TITLE
Review Ticket for 'Trabajar con archivos de texto en Python' - Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#40]
The Programming Historian has received the following translation on 'Trabajar con archivos de texto en Python' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/trabajar-con-archivos-de-texto

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by arojascastro** [comment]
- Line 33: , (dependiendo del sistema operativo de tu computadora: Mac, Windows, Linux),  --> if you are using commas to add an explanation you dont need to put it into brackets. So you can pick either commas either brackets. 
- Line 33: como se envía  --> cómo se envía
- Line 84: podrias --> podrías 
- Line 92 y 134: Toma en cuenta  --> Ten en cuenta (?)
- Line 96: click  --> clic (?)
- Line 114: i.e.  --> por ejemplo (?)
- Line 118: el archivo texto --> el archivo de texto

**Comment by vgayolrs** [comment]
Thanks a lot @arojascastro

**Comment by mariajoafana** [comment]
L 25: añadir "s" a siguiente
L 73: Revisar "utilizar como data de entrada" --> "utilizarla como dato"?
         Último renglón: sugiero cambiar "sálvalo" por "guárdalo"
L 86: último renglón, cambiar "ese'"por "esa"
L 92: segunda oración, sugiero por consistencia con la primera oración cambiar así "Se te olvidas de incluir..."
L 118: tercer renglón, eliminar espacio extra entre "leerá"y "texto"
L 128: 2ndo renglón: eliminar espacio extra entre "opciones" y "permita"

**Comment by vgayolrs** [comment]
Thank you very much @mariajoafana !!
All corrections done @acrymble

**Comment by mariajoafana** [comment]
I'm closing all review tickets for the Python lessons already reviewed both by Antonio and me

**Comment by acrymble** [comment]
Please let editors close review tickets. The workflow needs to be controlled by one person. Otherwise no one person is responsible for quality control.

I've added the translation reviewers to this. It's now published.
