### ISSUE TITLE
Relecture de traduction : Introduction à Beautiful Soup

### ISSUE THREAD

**Issue by InesSalome** [programminghistorian/ph-submissions#400]
Suite du ticket #324

Le Programming Historian en français a reçu la traduction du tutoriel [Introduction to Beautiful Soup](https://programminghistorian.org/en/lessons/intro-to-beautiful-soup) de Jeri Wieringa sous le titre ["Introduction à Beautiful Soup"](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/traductions/intro-a-beautifulsoup.md)  préparée par les soins de @Lucaterre. Cette traduction peut être consultée en [preview](http://programminghistorian.github.io/ph-submissions//fr/traductions/intro-a-beautifulsoup) pour faciliter la lecture.

Vous pouvez utiliser la numérotation des lignes fournie dans l'aperçu pour insérer vos commentaires, ou bien les numéros de paragraphe, si cela vous convient. Toutefois, sentez-vous libre de présenter votre relecture comme vous le jugez le mieux. Vous pouvez vous appuyez sur les [consignes aux traducteurs](https://programminghistorian.org/fr/consignes-traducteurs) du Programming Historian.

Je vais assurer le suivi éditorial de cette traduction et, dans ce cadre, je vais solliciter au moins deux relectures. Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos [consignes aux évaluateurs et évaluatrices](https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle. J’annoncerai sur ce fil de discussions quand l’étape aura été atteinte puis je transmettrai au traducteur une synthèse des remarques afin qu’il puisse travailler sur la révision de son texte. Je coordonnerai les échanges qui auront lieu dans cet espace. Nous pouvons prévoir un délai d'un mois environ à partir du moment où les deux relectures seront lancées. Ce délai peut néanmoins être adapté si besoin.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers Hélène Huet si vous avez le sentiment qu'une médiation est nécessaire.

## Politique contre le harcèlement
Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.
Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre médiatrice Hélène Huet. Merci de nous aider à créer un espace d’échange et de discussion sûr.

## Licence de publication
@Lucaterre, merci de confirmer par commentaire que, en tant que traducteur du tutoriel dont il est question dans ce ticket, vous cédez à ProgHist Ltd le droit de publier cette traduction sous licence CC-BY en suivant le modèle suivant : Je [prénom, nom] auteur-autrice | traducteur-traductrice cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier le tutoriel | la traduction du tutoriel dont il est question dans ce ticket (y compris le résumé, les tables, les illustrations, les données, et des ressources supplémentaires) sous licence CC-BY.

**Comment by InesSalome** [comment]
Je relaie ici des [commentaires](https://github.com/programminghistorian/ph-submissions/issues/324#issuecomment-811800370) de @Lucaterre suite à sa traduction qui seront utiles à une première relecture.

Sur le contenu :

* L'exemple de la base du donnée du Congrès (BioGuide) utilisé par l'auteur a subit depuis la rédaction de l'article une mise à jour majeure; de fait la stratégie de scraping HTML envisagé par l'auteur dans la leçon ne fonctionne plus aujourd'hui pour le même lien, cependant le code reste fonctionnel au regard de l'ancien HTML (peut-être faut-il intégré un avertissement ou une note du traducteur aux lecteurs ?);
* J'ai conservé le terme de scraping (je n'ai pas trouvé d'équivalent français) et de parseur (au lieu d'"analyseur syntaxique" qui peut prêter à confusion) dans l'article;
* J'ai conservé le terme anglais "pretty" avec "jolie" qui fait référence au paramètre ```python pretty_print ``` de la méthode ```python .to_string()``` et à la méthode ```python .prettify()``` de BS4;
* L'auteur désigne ```python href``` comme un élément dans le texte, alors qu'il s'agit d'un attribut HTML;
* De même, l'auteur désigne ```python .contents``` et ```python .get()``` comme deux méthodes ("...commonly used Beautiful Soup methods: contents and get..."), or dans le premier cas il s'agit d'un attribut de classe et dans l'autre d'une méthode de classe (lien vers la doc BS4 : https://www.crummy.com/software/BeautifulSoup/bs4/doc/#descendants), même s'il peut s'agir d'un détail.
* hésitation dans l'utilisation des termes "langages à balises" ou "langages de balisage" pour traduire "markup language".

Sur la forme :

* Je ne sais pas quelle est la pratique de PH pour intégrer les images dans la leçon, j'ai utilisé des balises HTML dans le doute...

**Comment by InesSalome** [comment]
Pour répondre sur les images, les [consignes aux auteurs](https://programminghistorian.org/fr/consignes-auteurs#inclure-des-images) précise d'utiliser le morceau de code suivant qui permet de produire du HTML automatiquement : 
```{% include figure.html filename="IMAGE-FILENAME" caption="VOTRE TITRE, AVEC \"CODE D'ÉCHAPPEMENT\" POUR LES GUILLEMETS" %}```

**Comment by Lucaterre** [comment]
Je Lucas Terriel traducteur cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier la traduction du tutoriel dont il est question dans ce ticket (y compris le résumé, les tables, les illustrations, les données, et des ressources supplémentaires) sous licence CC-BY.

**Comment by Lucaterre** [comment]
@InesSalome je ne trouve pas de dossier contenant les images de la leçon en anglais afin de récupérer les noms d'images afin  de corriger les balises d'images dans l'article ; faut-il créer un nouveau dossier d'images pour cet article ?

**Comment by InesSalome** [comment]
Voici le lien : https://github.com/programminghistorian/jekyll/tree/gh-pages/images/intro-to-beautiful-soup (elles se trouvent dans le repository jekyll)
Merci à toi ! :)

**Comment by InesSalome** [comment]
Nous sommes contraints de clore cette issue car la leçon originale a été retirée (cf.[ issue #2290](https://github.com/programminghistorian/jekyll/issues/2290)), du fait que le site pris en exemple est devenu obsolète, comme tu l'avais remarqué lors de ta traduction @Lucaterre. Vraiment désolée de ne pas pouvoir donner suite à cette traduction, et encore merci pour le travail accompli.
