### ISSUE TITLE
Tradução da lição "Manipular strings com Python"

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#403]
O Programming Historian em português recebeu a proposta de tradução da lição 'Manipular strings com Python' por @Mariana-Penna . A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/edit/gh-pages/pt/licoes/traducoes/manipular-strings-python.md).

A lição original no PH está em https://programminghistorian.org/en/lessons/manipulating-strings-in-python

A Mariana Penna fez uma tradução bem feita! Agradeço pela contribuição.
Eu serei o editor da tradução. E junto com a @joanacvp e o @ianaraujo faremos a revisão da tradução.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões na caixa de comentários para que a @Mariana-Penna possa acompanhar e responder.

O ideal é a Mariana Penna realizar as modificações após as sugestões da Joana e do Ian.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Política anti-assédio:
_
Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by joanacvp** [comment]
Olá, boa tarde @Mariana-Penna. Antes de mais parabéns pelo ótimo trabalho! Testei todos os códigos e deu tudo certo. Deixo apenas alguns elementos para rever em termos de compatibilização com o português de PT.

- [x] Linha 36 – colocar entre parênteses após “strings” a tradução cadeia de caracteres (Ficando = “(cadeia de caracteres)”)
- [x] Linha 37 – onde está “shell/ terminal” colocar “shell (terminal)”
- [ ] Linha 37 - onde está “linha de comando” colocar “linha de comandos”
- [x] Linha 41 – retirar o “você”
- [x] Linha 49 – onde está “em uma” colocar “numa”
- [x] Linha 50 – colocar a palavra “provavelmente” entre vírgulas
- [ ] Linha 50 - retirar o itálico da frase “Quando usados com strings, eles executam ações semelhantes, mas não iguais, às suas contrapartes matemáticas.”
- [x] Linha 68 – retirar o “você”
- [x] Linha 79 – retirar o “você”
- [x] Linha 79 - substituir “ao final” por “no final”
- [x] Linha 92 – substituir “esses métodos podem fazer praticamente qualquer coisa que você possa imaginar com as strings” por “esses métodos podem fazer praticamente qualquer coisa que possa imaginar com elas.”
- [x] Linha 93 – retirar o “você” (aparece duas vezes)
- [x] Linha 97 – retirar o “você”
- [x] Linha 97 - substituir “em uma” por “numa”
- [x] Linha 107 – retirar o “você”
- [x] Linha 107 - substituir “e seu programa” por “e o seu programa”
- [x] Linha 107 - substituir “Isso é útil para processamento” por “Isto é útil para o processamento”
- [x] Linha 140 – retirar o “você” (aparece duas vezes)
- [x] Linha 140 - substituir “pode fazer isso” por “pode fazê-lo”
- [x] Linha 151 – retirar o “você” (aparece duas vezes)
- [x] Linha 151 - substituir “partes indesejadas de uma string do início ou do fim” por “partes indesejadas do início ou do fim de uma string”
- [x] Linha 151 - substituir “você pode fazer isso” por “você pode fazê-lo”
- [x] Linha 161 – retirar o “você”
- [x] Linha 171 - Substituir “Isso torna” por “Isto torna”
- [x] Linha 171 - substituir “para ir até o fim” por “para ir até ao fim”
- [x] Linha 178 – Substituir “Existem muito mais” por “Existem muitos mais”
- [x] Linha 178 -substituir “colchetes” por “aspas” (nas diretrizes para autores é usada a palavra portuguesa)
- [x] Linha 185 – colocar o “então” entre vírgulas
- [x] Linha 185 -retirar o “você”
- [x] Linha 185 - substituir “geralmente precisa incluir” por “geralmente precisa de incluir”
- [x] Linha 195 – substituir “colchetes” por “aspas” (aparece duas vezes)
- [x] Linha 195 – retirar o “você” (aparece duas vezes)
- [x] Linha 195 – substituir o “em uma” por “numa”
- [x] Linha 200 – substituir “precisa incluir” por “precisa de incluir”
- [x] Linha 200 – retirar o “você” (aparece duas vezes)
- [x] Linha 231 – substituir “lições futuras” por “futuras lições”
- [x] Linha 231 – substituir “Ao final” por “No final”
- [x] Linha 231 – substituir “é possível baixar o” por “é possível fazer o download do”
- [x] Linha 231 – substituir “para ter certeza” por “para ter a certeza”
- [x] Linha 231 – substituir “está sendo utilizado” por “está a ser utilizado”

Bom trabalho!

**Comment by Mariana-Penna** [comment]
Muito obrigada @joanacvp pela revisão super atenta. Busquei efetivar todas as correções sugeridas, porém esbarrei em uma dificuldade na linha 50, quando precisaria retirar o itálico da frase “Quando usados com strings, eles executam ações semelhantes, mas não iguais, às suas contrapartes matemáticas". Em função de mencionar anteriormente o asterisco (*) como símbolo da multiplicação, acabo puxando o itálico pata o texto subsequente. Preciso de ajuda nessa correção, pois não sei ainda como alterar isso.
Muito obrigada!

**Comment by Mariana-Penna** [comment]
Observo, porém, que, quando da visualização final, o trecho em questão não está aparecendo em itálico. Como sou novata aqui, posso estar confusa, mas me pergunto se este erro não apareceria apenas na visualização do github.

**Comment by DanielAlvesLABDH** [comment]
Olá @Mariana-Penna efectivamente é comum essa situação, no código a utilização de um * ou _ aparenta utilizar o itálico a seguir, mas como a frase não é fechada pelos mesmos símbolos, no navegador não vai ser interpretada como itálico.

**Comment by JimmyMedeiros82** [comment]
@joanacvp obrigado pela atenta revisão. 

@Mariana-Penna , vamos aguardar a avaliação do @ianaraujo para seguir com a finalização dos ajustes na tradução.

**Comment by JimmyMedeiros82** [comment]
Meus caros, o @felipelmc vai colaborar conosco em fazer esta segunda revisão da tradução no lugar do @ianaraujo. 
O Felipe Lamarca  já tinha feito uma versão da tradução desta lição, então ele já tem conhecimento do conteúdo. O Ian Araujo vai colaborar em outra atividade. Ficará bom assim para todos!

**Comment by felipelmc** [comment]
Caros, será um prazer enorme contribuir na revisão desta lição. Farei isso no tempo mais breve possível.

**Comment by felipelmc** [comment]
Olá, @Mariana-Penna! Primeiro, parabenizo pelo excelente trabalho. A tradução está bem de acordo com a lição original. No entanto, vale notar: como o professor Jimmy  comentou, trabalhei na tradução dessa lição anteriormente. Minha tradução foi submetida ao professor Flávio Codeço Coelho, da Escola de Matemática Aplicada da FGV, e ele me apontou alguns erros conceituais que o autor da lição original cometeu. Desse modo, a maior parte das modificações que sugiro estão em linha com as recomendações do professor Flávio e dizem respeito a essas inconsistências do texto original. 

Nesse caso, e então estendo minha dúvida aos professores @DanielAlvesLABDH e @JimmyMedeiros82, não sei se o procedimento correto seria (i) abrir uma _issue_ para a lição original reportando as inconsistências e, só quando tudo for consertado, acertamos também no português; ou (ii) podemos fazer alterações já na tradução conforme o necessário. 

De todo modo, seguem os pontos que sugiro revisão:

- [x] Linha 36 - como você inseriu um link da Wikipedia e ele se refere à palavra "strings", esse link deve vir colado à essa palavra para que o redirecionamento funcione na prática. Ou seja, ao invés de "[strings] (cadeia de caracteres) (https://pt.wikipedia.org/wiki/Cadeia_de_caracteres)", basta escrever "[strings](https://pt.wikipedia.org/wiki/Cadeia_de_caracteres) (cadeia de caracteres)";
- [x] Linha 41 - nesse caso, quando o autor diz que é necessário "type variables", ele se refere não ao ato de "digitar", mais sim ao de "tipar", ou seja, especificar os tipos das variáveis. Nesse caso, então, é melhor escrever `especificar os tipos das variáveis` ao invés de `digitar`;
- [x] Linha 49 - há um espaçamento a mais entre as palavras "usar" e "operadores";
- [x] Linha 50 - para resolver o problema do itálico, basta adicionar uma contrabarra ( \\ ) antes do asterisco;
- [x] Linha 58 - o primeiro problema conceitual: "message1" é uma variável, e não uma string. Isto é, o conteúdo da variável "message1" é do tipo string, mas "message1" em si é uma variável;
- [x] Linha 68 - segundo o professor Flávio, seria mais preciso dizer que o operador de multiplicações faz uma concatenação repetida de uma mesma string;
- [x] Linha 80 - remover o espaçamento entre + e =, ou seja, (+=);
- [x] Linha 95 - não sei se @joanacvp concorda, mas acredito que faça sentido adicionar entre parênteses, junto do título Comprimento, a palavra "Length". Afinal, é daí que surge a função `len`, e isso pode situar melhor o leitor no momento de entender o nome da função, que não me parece muito intuitivo para quem teve pouco contato com a língua inglesa. Aliás, o professor Flávio chamou atenção para o fato de que `len` não é um método de string, como afirma a lição original, mas uma função built-in que se aplica a qualquer tipo que possua comprimento...;
- [x] Linha 193 - há um espaçamento a mais entre "message7" e "e";

No mais, o professor Flávio também comentou que, na explicação de Métodos, é errado dizer que métodos são algo que vem pré-instalado. Métodos são parte da implementação de strings e não podem ser instalados ou desinstalados. 

Mais uma vez, agradeço seu excelente trabalho de tradução!

**Comment by joanacvp** [comment]
Olá. Concordo totalmente com a observação do @felipelmc relativa à linha 95 e à função 'len'. Desta forma tornará mais simples o entendimento para um usuário que não saiba inglês fazer a associação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado pela revisão @felipelmc, acho que veio dar um excelente contributo. Relativamente à questão das discrepâncias, eu acho que elas não são muitas e não implicam uma grande alteração face ao texto da lição original. A minha opinião é que devemos prosseguir, talvez colocando uma pequena nota de tradução logo no início a dizer que foram feitas adaptações à lição original para a tornar mais adequada ao público que fala português. O que te parece @JimmyMedeiros82?

**Comment by JimmyMedeiros82** [comment]
Olá a todos! @felipelmc agradeço demais pela contribuição. Tem sido um esforço inestimável. 
Estou em acordo com o encaminhamento sugerido pelo @DanielAlvesLABDH 
Podemos fazer o ajuste apenas na lição em português. Na prática, a mudança é pequena e fica bem adequada ao nosso público. 
Abraços,

**Comment by Mariana-Penna** [comment]
Primeiramente, obrigada @felipelmc pelas correções!
Uma vez que foram propostas alterações de conteúdo, para além da tradução, concordo com a sugestão do @DanielAlvesLABDH de incluir uma nota que explicite que houve adequações da lição original para torná-la mais adequada ao português. 
Se houver acordo geral, darei início aos ajustes. 
Aguardo mais um pouco ou posso iniciar, @JimmyMedeiros82 ?

**Comment by JimmyMedeiros82** [comment]
Olá @Mariana-Penna acho que já pode avançar com os ajustes finais!

**Comment by Mariana-Penna** [comment]
Fiz os ajustes, só fiquei um pouco na dúvida quanto à linha 92 a respeito dos métodos e em relação à inclusão da nota explicativa. Abraços!

**Comment by JimmyMedeiros82** [comment]
Oi @Mariana-Penna sobre a linha 92, me parece ok. Está conforme indicado pela @joanacvp. 

No que concerne à nota, podemos incluir na linha 98 o seguinte conteúdo:
Nota da tradutora: 'len' não é um método de string, como na lição original, mas uma função built-in que se aplica a qualquer tipo de objeto que possua comprimento...

E acrescenta uma linha em branco abaixo da nota da tradutora. O que vocês acham @DanielAlvesLABDH @felipelmc e @joanacvp ?

**Comment by joanacvp** [comment]
@JimmyMedeiros82 totalmente de acordo

**Comment by felipelmc** [comment]
Acho uma ótima ideia, @JimmyMedeiros82!

**Comment by Mariana-Penna** [comment]
Oi colegas! Fiz a alteração nos termos sugeridos. Desta forma, não haveria a necessidade de fazer a nota ao início conforme sugerido pelo @DanielAlvesLABDH, ou é melhor incluir ambas as notas explicativas?

**Comment by JimmyMedeiros82** [comment]
@Mariana-Penna a nota deve aparecer apenas uma vez.
Em qual posição você acha que fica melhor?
Relendo a lição, me parece que fica melhor no ponto em que o assunto é mencionado. Mas acho importante ouvir vocês.

**Comment by felipelmc** [comment]
Concordo com o professor @JimmyMedeiros82!

**Comment by joanacvp** [comment]
De acordo com o @JimmyMedeiros82

**Comment by Mariana-Penna** [comment]
De acordo!

**Comment by JimmyMedeiros82** [comment]
Ótimo! Agradeço a todos pela contribuição nesta lição!
Foi um trabalho coletivo incrível. @DanielAlvesLABDH temos mais uma lição pronta!

**Comment by DanielAlvesLABDH** [comment]
Caros @JimmyMedeiros82, @Mariana-Penna, @joanacvp e @felipelmc muito obrigado pelo excelente trabalho! Fiz apenas ligeiras correcções no ficheiro e julgo que está pronto para publicação. Vou solicitar o DOI e dar início ao processo. Um abraço a todos(as)!

**Comment by Mariana-Penna** [comment]
Muito obrigada a todos: @DanielAlvesLABDH , @JimmyMedeiros82 , @joanacvp , @felipelmc! Foi minha primeira experiência de tradução no Programming Historian e certamente aprendi muito e irei me aprimorar graças a vocês. Que venham as próximas! Abraços e desejo tudo de bom!

**Comment by DanielAlvesLABDH** [comment]
Olá a todos! A lição já está publicada e o DOI activo https://dx.doi.org/10.46430/phpt0016.
Nós é que agradecemos @Mariana-Penna!
@JimmyMedeiros82 já pode actualizar o boot do Twitter e encerrar o ticket. Obrigado!

**Comment by JimmyMedeiros82** [comment]
Olá @DanielAlvesLABDH o bot do Twitter está atualizado. 
Podemos prosseguir com a publicação de mais uma lição. 

Agradeço a todos pela excelente cooperação e contribuição ao longo da revisão.
