### ISSUE TITLE
Tradução da lição "Reutilização de código e modularidade em Python"

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#406]
O Programming Historian em português recebeu a proposta de tradução da lição 'Reutilização de código e modularidade em Python' por @felipelmc .

A lição traduzida está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/reutilizacao-codigo-modularidade-python.md).

Já a lição original está em https://programminghistorian.org/en/lessons/code-reuse-and-modularity

Agradeço pela contribuição feita pelo Felipe Lamarca.
Eu serei o editor da tradução. A revisão da tradução fica a cargo do Ivo Veiga @jilv2006 e da Suemi Higuch @suemi-higuchi . E, desde já, agradeço a cooperação de ambos para esta atividade. 

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação do código, dos dados ou algum conteúdo. Por favor, deixem suas sugestões na caixa de comentários para que o @felipelmc possa acompanhar e responder.

O ideal é o Felipe Lamarca realizar as modificações após as sugestões da Suemi e do Ivo.

Importante lembrar, todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Política anti-assédio:
_
Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by JimmyMedeiros82** [comment]
A revisão da tradução fica a cargo do Ivo Veiga @ilv2006 e da Suemi Higuch @suemi-higuchi . E, desde já, agradeço a cooperação de ambos para esta atividade.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos! Se for necessário algo, alguma dúvida, podem contar comigo!

**Comment by ilv2006** [comment]
Mais uma vez, obrigado pelo convite. É com muito gosto que que contribuirei para este serviço cívico!

**Comment by suemi-higuchi** [comment]
Olá! Parabéns ao Felipe que fez um ótimo trabalho de tradução! Seguem abaixo minhas poucas sugestões, na ordem em que aparecem no texto:

- Na seção Resumo: substituir "consertados" por "depurados"
- Na seção Objetivos da lição: substituir "consertados" por "depurados"

Na seção Funções:
- substituir "perceberá que quer" por "descobrirá que deseja"
- substituir "comandos rotineiros" por "rotinas"
- substituir "Esses comandos" por "Essas rotinas"
- substituir "Suponha que deseja" por "Suponha que você deseja"
- substituir "uma linha" por "uma única linha"
- substituir "Esse exemplo" por "Este exemplo"
- substituir "Depois essa função é" por "Essa função é então"
- substituir "apenas significa que dissemos" por "significa apenas dizer"

Na seção Modularidade:
- substituir "quando os programas forem" por "de teus programas"
- substituir "noutros" por "em outros"
- substituir "Ao separar um programa" por "Quando você divide"
- substituir "se torna possível" por "consegue"
- substituir "Suponha que estejamos" por "Suponha que você esteja"
- substituir "Tenta-se quebrar" por "Você tenta"
- excluir "através do comando import"
- substituir "irá torná-lo utilizável" por "fará uso dele"
- substituir "que ele importasse (carregasse)" por "importar (carregar)" 
- substituir "Leituras sugeridas" por "Leituras recomendadas"

incluir em Citação sugerida:
- William J. Turkel e Adam Crymble, “Reutilização de código e modularidad em Python”, traduzido por Felipe Marques Esteves Lamarca, The Programming Historian em português (2021), https://.

**Comment by ilv2006** [comment]
Caro Jimmy,
não sei o que está a acontecer de errado mas não consigo aceder à lição traduzida, abraça

**Comment by JimmyMedeiros82** [comment]
Oi @ilv2006 veja por este link: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/reutilizacao-de-codigo-e-modularidade-em-python.md

**Comment by DanielAlvesLABDH** [comment]
Olá @ilv2006 já confirmei e tens privilégios de escrita no repositório, logo deves ser capaz de ver e editar o ficheiro no link que o Jimmy aqui colocou. Se tiveres alterações a fazer, não as edites directamente no ficheiro, antes coloca-as aqui num comentário, se possível, com a indicação do número de linha onde é necessário alterar. É essencial deixar registado nestes tickets de forma transparente todo o processo de revisão. Obrigado uma vez mais!

**Comment by ilv2006** [comment]
Já consigo abrir, obrigado! abraços

**Comment by felipelmc** [comment]
Olá a todos! Primeiro, fico muito feliz que a tradução da lição esteja em fase de revisão! @suemi-higuchi, agradeço demais as sugestões. Conforme sugerido pelo professor @JimmyMedeiros82, farei os ajustes assim que @ilv2006 fizer também a sua revisão. Agradeço novamente à equipe editorial do The Programming Historian!

**Comment by ilv2006** [comment]
Entretanto acabei de me aperceber que o link lá de cima continua a não funcionar.  mas não interessa porque entro pelo link que o Jimmy enviou hoje à noite. Obrigado

**Comment by ilv2006** [comment]
Olá a Todos

Antes de mais, devo felicitar o Felipe pois desbravou o texto original com destreza ! 
Na sequência da revisão excelente revisão da Suemi, quero apenas acrescentar algumas sugestões (ou repetir algumas). Mas queria chamar a atenção para um ponto que muito possivelmente já foi levantado por outros: as diferenças entre a língua portuguesa nos dois lados do Atlântico. É natural que algumas das questões que levanto aqui tenham um ângulo e práticas diferentes no Brasil.  As sugestões estão logo aqui abaixo (confirmar nas respectivas secções, por favor)   

**Objectivos da lição**

“módulos” e “funções” - seria bom destacar na mancha do texto como no original. Há alguma prática que estamos a seguir? Recurso ao itálico ou maiúsculas?

 “Easier to debug”- talvez “mais fáceis de depurar” do que “serem consertados”   

**Funções**

“rotinas” deverá simplificar “comandos rotineiros”
“declaração de função” e não “declaração da função”
“neste caso” e não “nesse caso”
“mas neste exemplo” e não “nesse caso” para não repetir
“muito importante” e não “importante”
“cada vez que chamamos a função damos à mesma um parâmetro diferente” e não “informamos”
“deixando apenas a declaração de função” e não “sua declaração” (repete mas deixa claro o contraste entre “function call e function declaration”)

**Modularidade** 

“pois permite identificar” e não “ao ser capaz de identificar”
“se não são os responsáveis pela sua execução” e não “se não são eles”
”para importar” e não “que ele importasse”
“De uma forma clara,” e não “No português claro”

**Comment by felipelmc** [comment]
Deixo aqui meu muito obrigado pelas recomendações, @ilv2006. Farei todos os ajustes o quanto antes.

**Comment by JimmyMedeiros82** [comment]
Excelente tradução, @felipelmc 
Parabéns pelo trabalho feito até aqui. 

Aproveito e agradeço ao @ilv2006 e @suemi-higuchi pela revisão atenciosa! Vão deixar a lição ainda melhor. 

Vamos aguardar as mudança e ajustes a serem feitas pelo @felipelmc

**Comment by felipelmc** [comment]
Caros,

Acabo de fazer um pull request com as alterações sugeridas pelos revisores. Agradeço mais uma vez @suemi-higuchi, @ilv2006, @JimmyMedeiros82 e @DanielAlvesLABDH pelo acompanhamento e espero que as traduções e o The Programming Historian ajudem cada vez mais pessoas.

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH temos mais uma lição traduzida e revisada. 
Vou inserir o conteúdo no bot do twitter.

Mais uma vez agradeço a todos pela colaboração e pelo belo trabalho tanto na tradução, quanto na revisão!

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82. Excelente notícia. Antes disso, contudo, é necessário ir ao pull request do Felipe, ver se está tudo bem e fazer o "merge" para que as alterações do Felipe sejam implementadas no ficheiro da tradução. A seguir eu faço uma revisão geral. Depois de se iniciar o processo de publicação e só depois de recebermos o DOI é que colocamos a informação no bot. Abraço

**Comment by JimmyMedeiros82** [comment]
Perfeito @DanielAlvesLABDH 
O "merge" está concluído! Aguardo a sua avaliação final.

**Comment by DanielAlvesLABDH** [comment]
A revisão da tradução está concluída e vou iniciar a publicação. Parabéns e obrigado ao @felipelmc! Obrigado também à @suemi-higuchi e ao @ilv2006 pelas revisões!

**Comment by felipelmc** [comment]
Eu que agradeço, tanto aos revisores quanto à equipe editorial!

**Comment by DanielAlvesLABDH** [comment]
A lição está publicada. Mais uma desta colaboração excelente com a Fundação Getúlio Vargas. Parabéns e obrigado a todos! @JimmyMedeiros82 o DOI desta lição é https://doi.org/10.46430/phpt0014. Depois de incluído no bot do Twitter podemos encerrar o ticket. Obrigado pelo trabalho!
