### ISSUE TITLE
Tradução da lição "Georeferencing in QGIS 2.0"

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#409]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Georeferencing in QGIS 2.0' por @Angelaimp. A lição a traduzir está no link (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/georreferenciamento-qgis.md) e as imagens no link (https://github.com/programminghistorian/ph-submissions/tree/gh-pages/pt/licoes/traducoes/Imagens_georreferenciar-qgis-pt).

A editora para esta tradução serei eu, @joanacvp.

Para promover uma publicação rápida desta lição traduzida, irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação do tradutor, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by joanacvp** [comment]
Good morning @anisa-hawes. Hope everything is ok with you. When translating this lesson @Angelaimp spotted some incorrections in the english version (she used QGIS 3.0):

- [x] In "Open the Necessary GIS Layers/Download lot_township_polygon", in the link available, there is no longer the need to read and accept the licence and they don't ask for our name and email (http://www.gov.pe.ca/gis/license_agreement.php3?name=lot_town&file_format=SHP)
- [x] In "Open the Georeferencer Tool /Add your historical map" the link to the online repository Island Imagined is not correctly positioned. 
- [x] The same as the later in "Adding control points - Some tips for choosing control point", since in the last point the link in Atlantic Canada is not correctly positioned. 
- [x] In "Determine the transformation settings" the link are incorrect.
- [x] In "world file" the link is incorrect.
- [x] In "Tif" the link is incorrect.
- [x] In "Island Imagined" the link is incorrect and there is no image of a lower resolution map.
- [x] In "Creating New Vector Layers in QGIS" the link is incorrectly positioned.
- [x] In "Geospatial Historian" the link is incorrectly positioned.


Thank you very much for your help!

**Comment by anisa-hawes** [comment]
Dear @joanacvp, hello!

I don't know how I missed this in my notifications! I will create a Lesson Maintenance Issue within Jekyll and set to work on this right away. I'm so sorry for holding up this translation... 

Very best wishes,
Anisa

**Comment by joanacvp** [comment]
Hi Anisa.

No problem at all. I have seen you already made the changes. I will look at
it today :). Thank you so much!

Best,
Joana


*Joana Vieira Paulino*
Laboratório de Humanidades Digitais (dhlab.fcsh.unl.pt), Instituto de
História Contemporânea
Faculdade de Ciências Sociais e Humanas – NOVA FCSH

Colégio Almada Negreiros - Campus de Campolide da NOVA, 1099-085
Lisboa | Portugal

E-mail: ***@***.***

Web: www.fcsh.unl.pt | 40anos.fcsh.unl.pt






Anisa Hawes ***@***.***> escreveu no dia quinta, 4/11/2021
à(s) 17:41:

**Comment by anisa-hawes** [comment]
Thank you for your understanding, @joanacvp!

Frustratingly, there is a problem with the build now... But I will troubleshoot today, and send you a message to confirm when everything is ready.

**Comment by anisa-hawes** [comment]
Hello again @joanacvp,

All solved! Our corrections to the EN lesson will be corrected as soon as [PR #2357](https://github.com/programminghistorian/jekyll/pull/2357) has been merged. 

One additional change which was required, was at line 144, where I changed the URL from `http` to `https`. Look out for this!

Thank you & thank you @Angelaimp for drawing my attention to these problems. Best wishes for finishing off the translation!

**Comment by joanacvp** [comment]
Thank you once again @anisa-hawes. 
@Angelaimp can you check if everything is ok in the PT translation, so I can start the review process? Thank you!

**Comment by anisa-hawes** [comment]
@Angelaimp If you need to work on this before our changes are merged, you can refer to the .md file in the branch [here](https://github.com/programminghistorian/jekyll/tree/Issue-2356).

**Comment by Angelaimp** [comment]
Thank you both very much! 
@joanacvp I made the necessary changes (different link for the online image repository) in the translation file and will send it to you.
