### ISSUE TITLE
Review Ticket for 'Reutilización de código y modularidad en Python' - Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#41]
The Programming Historian has received the following translation on 'Reutilización de código y modularidad en Python' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/reutilizacion-de-codigo-y-modularidad

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by arojascastro** [comment]
- Line 24: disfuncional  --> in this context where you are talking about functions might be misleding and repetitive. What about "con errores". 
- Line 49: Este ejemplo contiene una función: saludoEntidad  --> Este ejemplo contiene una función: saludoEntidad. (missing period)
- Line 64: qu eestamos --> que estamos
- Line 66: un segundo programa, usar-saludo.py que importará --> un segundo programa, usar-saludo.py, que importará (missing a comma after usar-saludo.py
- Line 74-74 the code is in lowercase but the output is uppercase: 

```
saludo.saludoEntidad("todos")
saludo.saludoEntidad("programming historian")
```
- All document: I think in spanish we say Hola **a** todos... but Hola Programming Historian

**Comment by vgayolrs** [comment]
Thank you very much @arojascastro . Everything solved. Please note that I slightly changed your suggestion for line 24. Let me explain: it is not a question of "errors in the code", but that the module is useful or not (works or not) in context with the other modules that make up the program you are designing. That is the idea. Please tell me if you think my proposal makes sense to solve it. Many thanks!

**Comment by arojascastro** [comment]
I think its less repetitive, yes but now the sentence is very long. What about this: "que no resulte útil nos ahorrará tiempo y esfuerzo" (without *llevará a*). Thanks @vgayolrs. I am gonna sleep so I'll continue reviewing tomorrow.

**Comment by vgayolrs** [comment]
Yes! I like it! Thanks @arojascastro

**Comment by mariajoafana** [comment]
L 40: último renglón, eliminar espacio extra entre "función."y "Éste"
L 78: eliminar espacio extra entre "aquí." y "Primero" 
L 80: eliminar espacios de más antes de *saludoEntidad("todos")*

**Comment by vgayolrs** [comment]
¡Gracias @mariajoafana !
done @acrymble

**Comment by acrymble** [comment]
I've added the translation reviewers to this lesson. It's now published.
