### ISSUE TITLE
Lesson proposal: Using word2vec in analyzing London’s Medical Officer of Health documents (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#417]
The Programming Historian has received the following proposal for a lesson on 'Using word2vec in analyzing London’s Medical Officer of Health documents' by Shu Wan. The proposed learning outcomes of the lesson are:
     
- Introducing readers to the use of word2vec in textual analysis.
- Furthering cultural and intellectual historians’ ammunition of textual analysis tools.
 	
In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than 01/01/2022. The author(s) agree to contact the editor in advance if they need to revise the deadline.
 
If the lesson is not submitted by 01/01/2022, the editor will attempt to contact the author(s). If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author(s).
 
The main editorial contact for this lesson is @tiagosousagarcia.

Our dedicated Ombudsperson is (Ian Milligan - http://programminghistorian.org/en/project-team). Please feel free to contact him at any time if you have concerns that you would like addressed by an impartial observer. Contacting the ombudsperson will have no impact on the outcome of any peer review.

**Comment by drjwbaker** [comment]
@svmelton and I discussed potential editors for this article. I will edit this article. I note that the article is now overdue.

**Comment by drjwbaker** [comment]
I have not heard from the author and so per https://github.com/programminghistorian/ph-submissions/issues/417#issue-1042506134 am closing the ticket. Should the author get in touch, the ticket may be reopened.
