### ISSUE TITLE
Tradução da lição "Análise de Correspondência para Pesquisa Histórica com R"

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#422]
O Programming Historian em português recebeu a proposta de tradução da lição 'Análise de Correspondência para Pesquisa Histórica com R' por @dianarebelorodriguez .

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/analise-correspondencia-pesquisa-historica-R.md

Já a lição original está em: https://programminghistorian.org/en/lessons/correspondence-analysis-in-R

Agradeço por mais uma contribuição feita pela Diana Rodriguez.
E temos mais uma tradução bem feita!

Eu serei o editor da tradução. A revisão ficará a cargo do @Yuritpires e mais um colaborador(a) português(a). 
Por favor, @joanacvp você poderia me ajudar e indicar alguém para contribuir com a revisão desta lição? 

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite a @dianarebelorodriguez na realização dos ajustes.

O ideal é a Diana realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by joanacvp** [comment]
Olá Jimmy!
Para R será que o @ilv2006 conseguirá ajudar caso tenha disponibilidade?

**Comment by ilv2006** [comment]
Olá. Por acaso até uso frequentemente análise de correspondência no meu trabalho...no entanto, agora estou mesmo sem tempo nenhum. Não querem perguntar à Andreia Martins Carvalho (penso que a Joana e/ou o Daniel têm o contacto), ela tem um inglês excelente (eu próprio recorro à sua ajuda muitas vezes). Se ela não puder voltem a perguntar-me pois tentarei arranjar tempo.

**Comment by JimmyMedeiros82** [comment]
Olá @joanacvp você poderia consultar a Andreia Martins Carvalho?

**Comment by joanacvp** [comment]
Olá Jimmy, bom dia. Segue o email da Andreia: andreiamartinscarvalho@gmail.com

**Comment by Yuritpires** [comment]
Bom dia, pessoal. É um prazer poder ajudar no que for possível. Já comecei a ler e fazer algumas sugestões, mas estou fazendo num documento a parte. Quando eu terminar, irei postar tudo de uma vez aqui, ok? 

Abs!

**Comment by JimmyMedeiros82** [comment]
Ficamos muito agradecido pela contribuição @Yuritpires

**Comment by JimmyMedeiros82** [comment]
A @islejoyeuse será a segunda revisora da lição em análise. 
Agradeço o aceite da Andreia Martins Carvalho em cooperar conosco nesta atividade.

**Comment by islejoyeuse** [comment]
Olá caros colegas! Estou contente por poder colaborar com o ph. provavelmente foi falha minha, mas não consigo ver um ficheiro com guidelines de tradução e-ou revisão. existe e será que alguém me pode dizer onde, talvez @JimmyMedeiros82? preferem que faça a revisão offline de uma vez só, como @Yuritpires ? obrigada

**Comment by islejoyeuse** [comment]
Olá outra vez, já encontrei as guidelines! :)

**Comment by DanielAlvesLABDH** [comment]
Obrigado e bem-vinda Andreia! Podes ver como fazer as revisões na prática olhando para um dos outros tickets de revisão que estão neste momento activos.

**Comment by JimmyMedeiros82** [comment]
Olá para todos! Estou retomando as lições em revisão para avançarmos para a publicação. 
@Yuritpires e @islejoyeuse podemos contar com a colaboração de vocês? Caso prefiram declinar, por favor, me avisem e convidamos outros colegas para esta lição.

**Comment by Yuritpires** [comment]
Bom dia, pessoal! 
No final do ano passado, o @JimmyMedeiros82 me convidou para ajudar na revisão da tradução da lição 422 do Programming historian, fato que recebi com muito entusiasmo. Contudo, devido a outras obrigações que tenho, venho encontrando dificuldades de conciliar todas as tarefas. Sendo assim, de lá para cá, não consegui terminar a revisão da tradução. Pensando no melhor para o andamento do projeto, venho anunciar que não estarei mais ajudando nessa lição, mas espero um dia poder voltar a ajudar. 
Abaixo segue a revisão da tradução que consegui fazer até aqui. Espero que sirva de ajuda para o melhoramento do trabalho! 

- [ ] linha 27: Eu sugiro uma mudança mais ou menos assim “Por exemplo, um membro de um clube pode ser equivalente a outro membro baseado nos clubes que compartilham”. Nesse contexto, acho que o “correspond” é no sentido “ser igual a” ou “equivalente a”. 
- [ ] linha 27: Eu sugiro “Provavelmente, membros que frequentam os mesmos clubes têm mais em comum do que aqueles que frequentam clubes diferentes. Do mesmo modo, clubes que compartilham membros iguais provavelmente terão mais em comum do que aqueles que compartilham membros diferentes.”
- [ ] Linha 29: Eu sugiro “A CA mede as correspondências mais fortes de um dataset e as projeta num espaço multidimensional, possibilitando sua visualização e interpretação.”. 
Substituir “possível mostrar três dimensões em um” para “possível mostrar três dimensões num” 
- [ ] Linha 31: substituir o “Como” do início por “Uma vez que”. 
Acho que ao invés de falar “como distâncias em uma trama”, ficaria mais compreensivo se fosse “como distâncias num gráfico”. É meio complicado fazer tradução de “plot”, mas acho que o “plot” dessa frase é o plot de gráfico mesmo. 
Tirar o “através” e colocar assim “Assim, a CA pode ser um bom passo inicial para filtrar os principais padrões de um grande dataset”
- [ ] Linha 33: mudar para “Depois de ler este tutorial, você será capaz de:” 
Mudar “da R” para “do R” 
- [ ] Linha 41: Substituir o “assume” por “supõe” ou “pressupõe” 
- [ ] Linha 43: mudar para “O tutorial sobre Dados Tabulares no R” 
Mudar para “tem informações sobre como organizar e configurar o R”
Mudar para “pode ser útil como um treinamento” 
- [ ] Linha 45: Eu manteria o “social network analysis” e colocaria entre parênteses “análise de redes sociais”, porque é um termo muito usado em inglês. Nesse sentido, é bem provável dos nossos leitores, que estão buscando aprender mais sobre isso, encontrarem esse termo em inglês. 
- [ ] Linha 49:  Confesso que não sei qual seria a tradução correta para “two-way graph plot”, mas acredito que uma tradução mais fiel seria “gráfico de dispersão com dois eixos” ou algo assim. De qualquer forma, sugiro que coloque o nome em inglês “two-way graph plot” entre parênteses para dar maior segurança ao leitor. 
- [ ] Linha 51: mudar “trabalha” por “funciona”. 
- [ ] Linha 51: na parte “se quisesse entender o papel...”, eu acrescentaria a palavra “você” antes de “quisesse”. Ficaria assim: “Se você quisesse compreender o papel dos acordos internacionais de livre comércio...”
- [ ] Linha 57: Trocar “relacionamentos” por “relações” ou “correlações”
- [ ] Linha 57: ficou faltando a tradução da seguinte frase “In a CA graph, units with few relationships will find themselves on the outskirts”. Eu sugiro a seguinte tradução de toda esta frase “Em um gráfico de CA, unidades com poucas correlações ficarão nos arreadores, enquanto aquelas unidades com maior quantidade de correlações ficarão mais próximo do centro do gráfico.”
- [ ] Linha 59: trocar “pode” da frase “historiador pode se perguntar se isto ocorre...” por “poderia”
- [ ] Linha 61: tirar o “os” da frase “especificamente, como os representantes políticos são organizados
- [ ] Linha 61: Eu acho que ficaria melhor trocar a “periferia do gráfico” por “nos arredores do gráfico” ou “nos cantos do gráfico”. Me soa mais natural.
- [ ] Linha 162: eu trocaria o “Um grande número de deputados” para “Muitos deputados são membros...” 
- [ ] Linha 209: na frase “high inertia points suggest outliers” a tradução feita foi “pontos de inércia elevados sugerem aberturas”. Eu sugiro tirar a palavra “aberturas”, deixar a palavra “outliers” mesmo e colocar entre parênteses algo como “valores atípicos” ou “valores fora do comum”. Digo isso porque outliers não é muito fácil de traduzir e é um termo muito comumente usado para esse tipo de área do conhecimento.

**Comment by dianarebelorodriguez** [comment]
@Yuritpires obrigada pelo olhar atento e detalhado! Muitas coisas passam por nós durante a tradução... Vou incorporar suas sugestões e acredito que a lição já estará pronta para ser publicada, certo, @JimmyMedeiros82 ? Abs

**Comment by dianarebelorodriguez** [comment]
Alteralções feitas! Tenho apenas uma questão quanto às seguintes sugestões:

- Linha 33: mudar para “Depois de ler este tutorial, você será capaz de:”
- Linha 51: na parte “se quisesse entender o papel...”, eu acrescentaria a palavra “você” antes de “quisesse”. Ficaria assim: “Se você quisesse compreender o papel dos acordos internacionais de livre comércio...”

As diretrizes que me foram passadas limitavam o uso da palavra "você". Também acho que ficaria melhor nesses casos, mas não sei se posso incorporar essas sugestões. Alguém pode me confirmar, por favor? Obrigada!

**Comment by Yuritpires** [comment]
Eu que agradeço @dianarebelorodriguez e parabéns pelo trabalho! Quanto as minhas sugestões das linhas 33 e 51, eu não sei quanto ao uso limitado do "você". Achei que com essa palavra a frase ficava mais clara a frase, mas se tem essa questão então é melhor evitar mesmo!

**Comment by JimmyMedeiros82** [comment]
@dianarebelorodriguez sobre as dúvidas das linhas 33 e 51, por favor, mantenha na forma que traduziu. Assim, segue as orientações de adequação aos leitores brasileiros e portugueses. 

Agradeço ao @Yuritpires pela contribuição valorosa. 

Agora vamos aguardar a colaboração da Andreia @islejoyeuse

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos/as, em especial ao @Yuritpires! Todos andamos com demasiados eventos para uma agenda tão curta! Abraço

**Comment by anisa-hawes** [comment]
Hello @JimmyMedeiros82,

In the course of copyediting https://github.com/programminghistorian/ph-submissions/issues/331 of /en/lessons/correspondence-analysis-in-R, Riva and I noted that an end note key [^factoextra] as well as the table of contents was missing from the original EN lesson. 

I'm in the process of updating the EN version of the lesson, and you can see these changes here: <https://github.com/programminghistorian/jekyll/pull/2546>

**Comment by JimmyMedeiros82** [comment]
caros, farei o ajuste indicado pela Anisa.
Enquanto isso, a @islejoyeuse pode prosseguir com a revisão.

**Comment by JimmyMedeiros82** [comment]
Caro @andresalvolns poderia colaborar conosco e revisar esta lição?

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82 , esta tradução está parada? Falta um revisor/a?

**Comment by JimmyMedeiros82** [comment]
Segue devagar. @andresalvolns você pode concluir a revisão?

**Comment by andresalvolns** [comment]
Claro, Jimmy. Peço perdão pela demora.

Em sáb., 26 de nov. de 2022 às 14:42, Jimmy Medeiros <
***@***.***> escreveu:

**Comment by andresalvolns** [comment]
Boa tarde, pessoal!

A tradução da lição está ótima, só encontrei algumas questões na formatação e vou repassar aqui:

- [x] Linha 42: Verificar o hiperlink de “Noções básicas de R com dados tabulares” e “Processamento Básico de Texto em R”
- [x] Linha 48: Verificar a marcação de rodapé após “opinião política”
- [x] Linha 58: Verificar marcação de rodapé ao final do parágrafo
- [x] Linha 94: Verificar a marcação de rodapé após o hiperlink “Pacote factominer”
- [x] Linha 122: Verificar o hiperlink “CPCs do Harper”
- [x] Linha 123: Verificar o hiperlink “CPCs do Trudeau's”
- [x] Linha 208: Verificar a marcação de rodapé após “inércia”; e o hiperlink em “apêndice”
- [x] Linha 241: Verificar a marcação de rodapé após “p-value”
- [x] Linha 343: Verificar a marcação de rodapé após “melhor abordagem"
- [x] Linha 381: Verificar a marcação de rodapé após “normalizado” e verificar também as fórmulas adicionadas que não foram formatadas corretamente
- [ ] As figuras dispostas nas linhas: 54, 175, 186, 194, 200, 272, 289, 292, 331 e 446 não aparecem na lição formatada

Todas as questões se resumem à dois problemas específicos que se repetiram em toda lição, mas fora isso a tradução está ótima! Parabéns aos envolvidos!

Se precisarem de algo é só me contatar.

**Comment by JimmyMedeiros82** [comment]
Muito obrigado @andresalvolns pela revisão!
@dianarebelorodriguez quando puder, por favor, efetue os ajustes necessários.

**Comment by anisa-hawes** [comment]
Hello all,

Please note that as part of a reorganisation of the /pt directory, this lesson's .md file has been moved to a new location within our Submissions Repository. 

It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/analise-correspondencia-R.md

A consequence is that this lesson's preview link has changed. It is now: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/analise-correspondencia-R

Please let me know if you encounter any difficulties or have any questions.
Very best, Anisa

**Comment by dianarebelorodriguez** [comment]
Bom dia, gente!

Desculpem a demora.  Obrigada @andresalvolns pelos apontamentos. Os ajustes foram feitos, mas, em relação às figuras, não sei como resolver, normalmente é ajustado apenas quando a lição é publicada. @JimmyMedeiros82 , pode verificar isso, por favor? Tenho todas elas em uma pasta no Google Drive e posso reenviá-las caso necessário.

Bom final de ano!

Abs,

**Comment by anisa-hawes** [comment]
Dear @dianarebelorodriguez and @JimmyMedeiros82,

Are you reviewing the Preview here: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/analise-correspondencia-R ?  The images are displaying from my side. 

Is there another problem you are trying to fix? Let me know, and I can try to help.

Anisa

**Comment by anisa-hawes** [comment]
Just to explain: images for translations should be saved in the same /images folder as the original. 

In this case, the original is the English lesson, Correspondence Analysis for Historical Research with R and the images are saved at [/images/correspondence-analysis-in-R](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/correspondence-analysis-in-R).

When I was reorganising the /pt directory earlier this month, I moved the images you'd created for this translation to that folder. 

You will also notice that I re-named the images so that they follow the [format I propose we begin to use](https://github.com/programminghistorian/jekyll/issues/2578#issuecomment-1310658356).

I then updated analise-correspondenciaR.md so that the YAML includes the field `original: correspondence-analysis-in-R` (this instructs the file where to locate the images) and so that the image file names match those I created (tr-pt-analise-correspondenciaR-1.png, tr-pt-analise-correspondenciaR-2.png and so on).

Working in this way will enable reviewers, editors and authors to access an accurate live preview that includes images in ph-submissions as the draft progresses.

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH,

This lesson is **almost ready** for your final review.

- Preview: <http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/analise-correspondencia-R>
- .md file: [/esbocos/traducoes/analise-correspondencia-pesquisa-historica-R.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/analise-correspondencia-pesquisa-historica-R.md)
- images: [/images/correspondence-analysis-in-R](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/correspondence-analysis-in-R) Note: images for translations will be uploaded into the original /images folder on Jekyll
- assets: [already on Jekyll - if I understand correctly, theses assets have not been translated for PT] [assets/correspondence-analysis-in-R](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/correspondence-analysis-in-R) 
- original avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]
- gallery avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]

Sustainability + accessibility actions status:

- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Addition of alt-text for all figures 

Olá @dianarebelorodriguez, Por favor, poderia fornecer texto descritivo alt-text para acompanhar as imagens?
Acrescentei um modelo `alt="Visual description of figure image"`
Muito obrigada!

- [x] Receipt of translator's copyright agreement

@dianarebelorodriguez, O nosso formulário de declaração serve para reconhecer os seus direitos de autor como tradutor e conceder-nos permissão para publicar esta lição. Por favor, pode descarregar [este formulário](https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf), preenchê-lo e enviá-lo por e-mail para mim (admin [@] programminghistorian.org)?

Next steps:
- [x] @JimmyMedeiros82 / @dianarebelorodriguez Prepare a PT translation of the `avatar_alt:` [EN: Diagram of a cube with labeled edges.]
- [x] @JimmyMedeiros82 / @dianarebelorodriguez Prepare a PT translation of the `abstract:` [EN: This tutorial explains how to carry out and interpret a correspondence analysis, which can be used to identify relationships within categorical data.]
- [ ] @anisa-hawes Daniel & I can work together to prepare x1 announcement post, + x2 posts for our Twitter/Mastodon Bot
- [x] @anisa-hawes We already have a PT translation of the original author's (Ryan Deschamps's) bio for `ph_authors.yml`, but I think it would be worth us checking with them whether it needs updating – I can do this.
- [x] I've written to the author to ask if they want us to update their bio. I will confirm here.

**Comment by anisa-hawes** [comment]
A few other small notes, for Diana @dianarebelorodriguez:

- [x]  I noticed in several places, the `# comments` inside codeblocks were still written in English. I've updated to `# remova os singles de novo` because I could see the PT translation somewhere else in the text.
- [x] I notice that at line 298 of the .md (paragraph 51 of the Preview) there was placeholder text for an image of an incomplete graph? The EN original and ES translation do not use an image here*, so I have made a small adjustment.  
- [x] For writing alt-text, [this resource](https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81) may be useful. It advises that the alt-text for graphs and data visualisations should consist of the following:

`alt="Chart type of data type where reason for including chart"`

You can either add the alt-text into the template I've created, or leave a comment and I’ll add it for you.

Muito obrigada,
Anisa

--

*Reference images to show /en/lessons/correspondence-analysis-in-R 

![en](https://user-images.githubusercontent.com/87070441/233834648-4c7eee1d-5086-4ba2-8181-f9571943a10a.png)

and /es/lecciones/analisis-de-correspondencia-en-r at the equivalent points in those lessons: 

![es](https://user-images.githubusercontent.com/87070441/233834651-2670fa04-2044-4693-b31a-2a46621af520.png)

**Comment by DanielAlvesLABDH** [comment]
@anisa-hawes I have made some updates on the translation. Do we need to do something related to the images of the code you left in this last comment? @JimmyMedeiros82 e @dianarebelorodriguez podem esclarecer se já foi enviada a declaração sobre os direitos de autor?

**Comment by anisa-hawes** [comment]
Thank you, @DanielAlvesLABDH.

Apologies for any confusion. The images above were only intended to explain that the EN original and ES translation do not use an image at that point in the lesson.

I would be grateful if you or @JimmyMedeiros82 could double check that you're happy with the adjustment I made https://github.com/programminghistorian/ph-submissions/commit/1ce1f40ec7be250949895fe263710dfae80666f8 at lines 293 and 298 of the .md file. 

Meanwhile, I've contacted the original author and they would like us to update their bio.

```
- name: Ryan Deschamps
  team: false
  bio:
    en: |
      Ryan Deschamps is a Professor in the Applied Computer Science and Information Technology program at Conestoga College in Waterloo, Ontario, Canada.
    es: |
      Ryan Deschamps es profesor del programa de Informática Aplicada y Tecnología de la Información del Conestoga College de Waterloo, Ontario, Canadá.
    fr: |
      Ryan Deschamps est professeur dans le programme d'informatique appliquée et de technologie de l'information au Conestoga College à Waterloo, Ontario, Canada.
    pt: |
      Ryan Deschamps é professor no programa de Informática Aplicada e Tecnologia da Informação no Conestoga College em Waterloo, Ontário, Canadá.
```

*translations not yet checked.

**Comment by JimmyMedeiros82** [comment]
@anisa-hawes the adjustments in lines 293 and 298 are adequate.

@DanielAlvesLABDH vou enviar uma mensagem para a @dianarebelorodriguez para ela preencher o formulário (https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf) e enviar para a @anisa-hawes

**Comment by anisa-hawes** [comment]
Obrigado, @JimmyMedeiros82 🙂

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH encaminhei hoje o formulário da Diana. Avançamos com isso.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @JimmyMedeiros82. @anisa-hawes can we move forward? All the changes are incorporated in the .md file: [/esbocos/traducoes/analise-correspondencia-pesquisa-historica-R.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/analise-correspondencia-pesquisa-historica-R.md)?

**Comment by anisa-hawes** [comment]
Dear @DanielAlvesLABDH,

The sustainability + accessibility actions are all complete and this lesson is ready to move forwards for publication.
- [x] I have requested a DOI

**Comment by anisa-hawes** [comment]
This lesson is now published! 🎉 

https://doi.org/10.46430/phpt0042

https://programminghistorian.org/pt/licoes/analise-correspondencia-pesquisa-historica-R

**Comment by DanielAlvesLABDH** [comment]
Many thanks for all the help, @anisa-hawes. Parabéns a todos/as!
