### ISSUE TITLE
Tradução da lição 'Georreferenciamento com o QGIS 3.20'

### ISSUE THREAD

**Issue by joanacvp** [programminghistorian/ph-submissions#424]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Georreferenciamento com o QGIS 3.2' por @Angelaimp. A lição a traduzir está no link (https://programminghistorian.org/en/lessons/georeferencing-qgis).

Para promover uma publicação rápida desta lição traduzida, eu @joanacvp irei procurar uma revisão da mesma junto de dois revisores o mais breve possível.

Se houver alguma preocupação dos tradutores, eles podem entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by anisa-hawes** [comment]
Hello @joanacvp. May I ask is this an update of the QGIS 2.0 lesson? <https://github.com/programminghistorian/ph-submissions/issues/409>? I noticed that Issue 409 is closed. I'm just updating our Lesson Concordance document.

**Comment by joanacvp** [comment]
Hello @anisa-hawes. I already update our translation file according to the elements @Angelaimp sent me. I am just waiting for the answer from a PT reviewer to proceed with it. Already have a BR one, but still waiting for the PT. Thank you!

**Comment by anisa-hawes** [comment]
I see! I remember that you said that @Angelaimp was working with QGIS v.3.20 when testing the lesson! 

But apart from using a different version of QGIS, this is a translation of https://programminghistorian.org/en/lessons/georeferencing-qgis?

**Comment by joanacvp** [comment]
Hello @anisa-hawes. Yes, the translation of that lesson is in this link: [](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/georreferenciamento-qgis.md ). Still waiting for the answer from the reviewer

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. Shall we close this Issue now that you are working in #434?

As part of a reorganisation of the /pt directory, this lesson's .md file has been moved to: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/georreferenciamento-qgis.md

The lesson preview is available here: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/georreferenciamento-qgis

**Comment by DanielAlvesLABDH** [comment]
I agree @anisa-hawes. I will close the issue. Thanks
