### ISSUE TITLE
Tradução da lição 'Limpar dados com o OpenRefine' #410

### ISSUE THREAD

**Issue by aracele** [programminghistorian/ph-submissions#427]
O Programming Historian em português recebeu a seguinte proposta de tradução da lição 'Limpar dados com o OpenRefine' por @FranciscoNabais. 

A lição traduzida está no link: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/limpar-dados-openrefine.md

Muito obrigada, Francisco Nabais!

Aqui pode ser verificada uma visualização prévia da página: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/limpar-dados-openrefine

A editora para esta tradução vou ser eu, Aracele Torres.

O @ericbrasiln e a @joanacvp  aceitaram ficar como revisores desta tradução. Obrigada a ambos!

Peço que além da tradução para português, procurem verificar se a lição precisa de alguma actualização. Por favor, deixem as sugestões na caixa de comentários deste ticket, de forma que o Francisco possa acompanhar e responder.

Se houver alguma preocupação do tradutor, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.

Política anti-assédio
_

Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.

O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso mediador independente. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by FranciscoNabais** [comment]
Muito obrigado pela ajuda! 

No que eu puder ajudar, estarei disponível.

**Comment by ericbrasiln** [comment]
Boa tarde,
Obrigado pelas informações @aracele e obrigado @FranciscoNabais pela contribuição.
Darei início à revisão no início da próxima semana.
Atenciosamente

**Comment by ericbrasiln** [comment]
Boa tarde, @aracele e @FranciscoNabais 
Primeiramente, parebéns pela tradução @FranciscoNabais . A lição sobre OpenRefine será de grande importância para o Programming Historian em português.

Fiz uma revisão do texto e das etapas da lição. Seguem as minhas sugestões:

*Todas as minhas sugestões referentes à escrita partiram do português do Brasil, então peço que por favor indiquem se faz sentido alterar ou manter de acordo com os padrões utilizados nas demais traduções.*

Aponto a linha do documento Markdown, a versão do original e em seguida minha sugestão. Coloquei minhas dúvidas entre colchetes:

**42.** 
_Nesta lição, o usuário vai perceber os princípios e a prática da limpeza de dados_
Nesta lição, o usuário vai aprender os princípios e a prática da limpeza de dados

**51·**
_## Porque é que os historiadores se devem preocupar com a qualidade dos dados?_
## Porque historiadores devem se preocupar com a qualidade dos dados?

**53.** 
_Registos duplicados_
Registros duplicados

_os historiadores vão ter uma maior necessidade_ 
os historiadores terão uma maior necessidade 

_o usuário vai ser capaz_
o usuário será capaz

**57.**
_o surgimento de Ferramentas Interativas de Transformação de Dados_
o surgimento de Ferramentas Interativas de Transformação de Dados (Interactive Data Transformation tools, ou IDTs em inglês)

**63**
_Reconhecimento de Entidade Mencionada_
Reconhecimento de Entidade Nomeada

_Biblioteca do Congresso_
Biblioteca do Congresso dos Estados Unidos da América

**77.**
[Não sei se há necessidade de continuar utilizando `em inglês` após OpenRefine e outros termos que já foram utilizados antes.]

_que será utilizado ao longo deste tutorial_
[se refere aos arquivos de dados ou ao site FreeYour Metadata?]
que serão utilizados ao longo deste tutorial

**79.** 
[Como estamos traduzindo 'to parse' nas demais lições? 'Analisar', partilhar?]

_planeado_
planejado

**81.**
um link persistente para a página que alberga o objeto dentro do site do museu. 
um link persistente para a página que hospeda o objeto dentro do site do museu. 

**91.**
[Reparei que no meu OpenRefine a opção é '**Remove matching rows**' e não '**Remove all matching rows**' ]

**111.**
[Talvez aqui fosse importante explicitar por escrito a etapa de clicar no botão '**Cluster**'.]

**131.**
[Ao realizar a operação '**Edit cells**' \> '**Split multi-valued cells**' o númermo de registros ficará em 170,158. Apenas após o '*Edit cells*', '*Join multi-valued cells*' (realizado no parágrafo seguinte) teremos o valor de 75,727 linhas.]

**141.**
[No meu caso, apenas 1662 células foram alteradas e não 33.006.
Na lição original em inglês o valor é  33,008. Acho que vale a pena conferir.]

Outra questão que me gerou dúvidas é a escrita de número na casa dos milhares. Em portguês do Brasil utilizamos '.' ao invés de ',' como no Inglês para separar: 33.006 ao invés de 33,006.

Estou à disposição para qualquer outra questão.

**Comment by aracele** [comment]
> 

Olá @ericbrasiln! Muito obrigada pela sua revisão, seu trabalho é de grande importância para mantermos o PH em Português! 

@joanacvp agora estamos aguardando a sua revisão, mas acho que o @FranciscoNabais pode ir conferindo as sugestões do Eric enquanto isso. 

Agradeço mais uma vez ao esforço de todos!

**Comment by joanacvp** [comment]
Boa tarde a todos. Muitos parabéns pela tradução @FranciscoNabais. Peço desde já desculpa pela demora na revisão @aracele.

Seguem as minhas notas:

- [x] O OpenRefine tem uma versão em português, pelo que sugiro que se alterem os comandos de toda a lição para a versão portuguesa, indicando-se no início da abertura do OpenRefine para ir do lado esquerdo a “Language Settings” e selecionar a opção “Português”. Por motivos de acompanhamento na presente revisão seguirei o modelo inglês, o qual sugiro que seja alterado. (utilizei a versão para Mac)
- [x] Ao longo do texto dataset surge várias vezes. Na versão inglesa aparece "data set" e não tudo junto. Como devemos fazer na versão portuguesa @DanielAlvesLABDH. É necessário corrigir o glossário em concordância (lá está tudo junto). No caso de ficar separado é preciso corrigir sempre que esta palavra aparece na lição (linhas 46, 53, 57x2, 73, 153x2; e na figura 2). 
- [x] Linha 46 - Em “3. Analisar a distribuição de valores ao longo do Dataset” colocar dataset em minúsculas. 
- [x] Linha 53 - “o usuário vai ser capaz de facilmente identificar erros sistemáticos” = “o usuário vai ser capaz de identificar facilmente erros sistemáticos”
- [x] Linha 59 - Em “As Ferramentas Interativas de Transformação de Dados, assemelham-se” retirar a vírgula
- [x] Linha 59 - “já que estes se apresentam como uma função secundária” = “já que estes são uma função secundária do software”
- [x] Linha 61 - Em “têm sido desenvolvidas várias ferramentas de uso geral para a transformação de dados interativos” retiraria o “de uso geral”
- [x] Linha 61 - Em “Aqui queremos concentrar-nos, sobretudo, no OpenRefine (em inglês)” retiraria o link, porque já está acima
- [x] Linha 63 - Em “processo denominado por Named-Entity Recognition (NER)” retirar o “por”
- [ ] Linha 67 - Em “disponível no seu website” o link não está a abrir
- [x] Linha 73 -  “O Vocabulário Controlado consiste” = “Um Vocabulário Controlado consiste”
- [x] Linha 77 - “navegador de internet do utilizador” = “navegador de internet do usuário”
- [x] Linha 79 - “Por padrão, a primeira linha será analisada corretamente como o nome de uma coluna” = “A primeira linha será processada como o nome da coluna por defeito”
- [x] Linha 79 - Onde está “'Quotation marks are used to enclose cells containing columnseparators'” no OpenRefine no Mac aparece-me “‘Is character “ to enclose cells containing column separators”. Por outro lado, “columnseparators” escreve-se em separado = “column separators”.
- [x] Linha 79 - Onde está “'Parse cell text into numbers, dates, ...'” no OpenRefine no Mac aparece-me “‘Attempt to parse cell text into numbers’”.
- [ ] Linha 79 - “o Download diretamente do projeto inicial” remete para um formato de ficheiro diferente (é json) pelo que creio que seria necessário explicar o que fazer quando abrir o ficheiro zip cujo download é feito nesse link
- [x] Linha 87 - “A primeira coisa a fazer é olhar ao redor e conhecer os seus dados” = “A primeira coisa a fazer é observar e conhecer os seus dados”
- [x] Linha 87 - “em frente do nome da coluna” = “em frente ao nome da coluna”
- [x] Linha 91 - “Identificação do registo” = “Identificador do registo”
- [x] Linha 91 - “é que três linhas estão vazias” = “é que existem três linhas sem dados”
- [x] Linha 91 - em “Remove all matching rows” no OpenRefine no Mac aparece-me como “Remove matching rows” (sem o “all”). Este comando aparece novamente na linha 97.
- [x] Linha 91 - “Remover todas as filas correspondentes” = “Remover todas as linhas correspondentes”
- [x] Linha 105 - “mais 9 registos dos originais 75,727” = “mais 9 registos do que os originais 75,727”
- [x] Linha 105 - “dos cabeçalhos das colunas” = “do cabeçalho das colunas”
- [x] Linha 109 - em “devidamente atomizado, filtros, facets e clusters” filtros e facets não será redundante?
- [x] Linha 109 - onde diz “​​4,934 diferentes categorias” o total que me aparece são 4935 categorias. Confirmar se está correcto
- [x] Linha 109 - “dos termos mais usados a indexar a coleção” = “dos termos mais usados para indexar a coleção”
- [x] Linha 109 - em “Roupas e vestidos” não será “Roupas e vestuário”?
- [x] Linha 111 - penso que seria necessário referir que é preciso clicar em “Cluster” para se abrir o comando de uniformização dos termos
- [x] Linha 119 - “linhas)) Depois” = “linhas)). Depois”
- [x] Linha 123 - “culpados da nossa discrepância” = “culpados pela nossa discrepância”
- [x] Linha 123 - Grel significa Google Refine Expression Language (e não OpenRefine Expression Language).
- [x] Linha 125 - “documentação do GREL” = “documentação da GREL”
- [x] Linha 134 - “ajuda do GREL” = “ajuda da GREL”
- [x] Linha 134 - “Ao usar o GREL” = “Ao usar a GREL”
- [x] Linha 147 - “Construção sob os dados limpos” = “Construção sobre os dados limpos”
- [x] Linha 153 - “recorrentes tal como” = “recorrentes, tais como”

 
Muito obrigada!

**Comment by aracele** [comment]
> Boa tarde a todos. Muitos parabéns pela tradução @FranciscoNabais. Peço desde já desculpa pela demora na revisão @aracele.
> 
> Seguem as minhas notas:
> 
>     * [ ]  O OpenRefine tem uma versão em português, pelo que sugiro que se alterem os comandos de toda a lição para a versão portuguesa, indicando-se no início da abertura do OpenRefine para ir do lado esquerdo a “Language Settings” e selecionar a opção “Português”. Por motivos de acompanhamento na presente revisão seguirei o modelo inglês, o qual sugiro que seja alterado. (utilizei a versão para Mac)
> 
>     * [ ]  Ao longo do texto dataset surge várias vezes. Na versão inglesa aparece "data set" e não tudo junto. Como devemos fazer na versão portuguesa @DanielAlvesLABDH. É necessário corrigir o glossário em concordância (lá está tudo junto). No caso de ficar separado é preciso corrigir sempre que esta palavra aparece na lição (linhas 46, 53, 57x2, 73, 153x2; e na figura 2).
> 
>     * [ ]  Linha 46 - Em “3. Analisar a distribuição de valores ao longo do Dataset” colocar dataset em minúsculas.
> 
>     * [ ]  Linha 53 - “o usuário vai ser capaz de facilmente identificar erros sistemáticos” = “o usuário vai ser capaz de identificar facilmente erros sistemáticos”
> 
>     * [ ]  Linha 59 - Em “As Ferramentas Interativas de Transformação de Dados, assemelham-se” retirar a vírgula
> 
>     * [ ]  Linha 59 - “já que estes se apresentam como uma função secundária” = “já que estes são uma função secundária do software”
> 
>     * [ ]  Linha 61 - Em “têm sido desenvolvidas várias ferramentas de uso geral para a transformação de dados interativos” retiraria o “de uso geral”
> 
>     * [ ]  Linha 61 - Em “Aqui queremos concentrar-nos, sobretudo, no OpenRefine (em inglês)” retiraria o link, porque já está acima
> 
>     * [ ]  Linha 63 - Em “processo denominado por Named-Entity Recognition (NER)” retirar o “por”
> 
>     * [ ]  Linha 67 - Em “disponível no seu website” o link não está a abrir
> 
>     * [ ]  Linha 73 -  “O Vocabulário Controlado consiste” = “Um Vocabulário Controlado consiste”
> 
>     * [ ]  Linha 77 - “navegador de internet do utilizador” = “navegador de internet do usuário”
> 
>     * [ ]  Linha 79 - “Por padrão, a primeira linha será analisada corretamente como o nome de uma coluna” = “A primeira linha será processada como o nome da coluna por defeito”
> 
>     * [ ]  Linha 79 - Onde está “'Quotation marks are used to enclose cells containing columnseparators'” no OpenRefine no Mac aparece-me “‘Is character “ to enclose cells containing column separators”. Por outro lado, “columnseparators” escreve-se em separado = “column separators”.
> 
>     * [ ]  Linha 79 - Onde está “'Parse cell text into numbers, dates, ...'” no OpenRefine no Mac aparece-me “‘Attempt to parse cell text into numbers’”.
> 
>     * [ ]  Linha 79 - “o Download diretamente do projeto inicial” remete para um formato de ficheiro diferente (é json) pelo que creio que seria necessário explicar o que fazer quando abrir o ficheiro zip cujo download é feito nesse link
> 
>     * [ ]  Linha 87 - “A primeira coisa a fazer é olhar ao redor e conhecer os seus dados” = “A primeira coisa a fazer é observar e conhecer os seus dados”
> 
>     * [ ]  Linha 87 - “em frente do nome da coluna” = “em frente ao nome da coluna”
> 
>     * [ ]  Linha 91 - “Identificação do registo” = “Identificador do registo”
> 
>     * [ ]  Linha 91 - “é que três linhas estão vazias” = “é que existem três linhas sem dados”
> 
>     * [ ]  Linha 91 - em “Remove all matching rows” no OpenRefine no Mac aparece-me como “Remove matching rows” (sem o “all”). Este comando aparece novamente na linha 97.
> 
>     * [ ]  Linha 91 - “Remover todas as filas correspondentes” = “Remover todas as linhas correspondentes”
> 
>     * [ ]  Linha 105 - “mais 9 registos dos originais 75,727” = “mais 9 registos do que os originais 75,727”
> 
>     * [ ]  Linha 105 - “dos cabeçalhos das colunas” = “do cabeçalho das colunas”
> 
>     * [ ]  Linha 109 - em “devidamente atomizado, filtros, facets e clusters” filtros e facets não será redundante?
> 
>     * [ ]  Linha 109 - onde diz “​​4,934 diferentes categorias” o total que me aparece são 4935 categorias. Confirmar se está correcto
> 
>     * [ ]  Linha 109 - “dos termos mais usados a indexar a coleção” = “dos termos mais usados para indexar a coleção”
> 
>     * [ ]  Linha 109 - em “Roupas e vestidos” não será “Roupas e vestuário”?
> 
>     * [ ]  Linha 111 - penso que seria necessário referir que é preciso clicar em “Cluster” para se abrir o comando de uniformização dos termos
> 
>     * [ ]  Linha 119 - “linhas)) Depois” = “linhas)). Depois”
> 
>     * [ ]  Linha 123 - “culpados da nossa discrepância” = “culpados pela nossa discrepância”
> 
>     * [ ]  Linha 123 - Grel significa Google Refine Expression Language (e não OpenRefine Expression Language).
> 
>     * [ ]  Linha 125 - “documentação do GREL” = “documentação da GREL”
> 
>     * [ ]  Linha 134 - “ajuda do GREL” = “ajuda da GREL”
> 
>     * [ ]  Linha 134 - “Ao usar o GREL” = “Ao usar a GREL”
> 
>     * [ ]  Linha 147 - “Construção sob os dados limpos” = “Construção sobre os dados limpos”
> 
>     * [ ]  Linha 153 - “recorrentes tal como” = “recorrentes, tais como”
> 
> 
> Muito obrigada!

Muito obrigada pela sua revisão @joanacvp! 

@FranciscoNabais assim que você conseguir avaliar as sugestões da Joana e do Eric, podemos finalizar e publicar a lição. Estou à disposição se precisar de algo ou tiver alguma dúvida :)

**Comment by FranciscoNabais** [comment]
Boa tarde a todos. 

Muito obrigado por toda a ajuda prestada na revisão da lição a publicar.
Em breve irei começar a avaliar as sugestões e aplicá-las na tradução.

Peço também desculpa pela demora, préviamente justificada perante a @joanacvp e o professor @DanielAlvesLABDH. 
Com o inicio da época de frequências e trabalhos, tenho concentrado o meu desempenho nos estudos, pelo que me ausentei temporáriamente da tradução, regressando nos finais do mês de janeiro / inicios do mês de fevereiro.

Espero que compreendam a minha situação e mais uma vez obrigado pela disponibilidade e colaboração de todos.

**Comment by aracele** [comment]
> Boa tarde a todos.
> 
> Muito obrigado por toda a ajuda prestada na revisão da lição a publicar. Em breve irei começar a avaliar as sugestões e aplicá-las na tradução.
> 
> Peço também desculpa pela demora, préviamente justificada perante a @joanacvp e o professor @DanielAlvesLABDH. Com o inicio da época de frequências e trabalhos, tenho concentrado o meu desempenho nos estudos, pelo que me ausentei temporáriamente da tradução, regressando nos finais do mês de janeiro / inicios do mês de fevereiro.
> 
> Espero que compreendam a minha situação e mais uma vez obrigado pela disponibilidade e colaboração de todos.

Oi @FranciscoNabais! Claro, não precisa se preocupar, compreendemos a situação! Se precisar de ajuda ou tiver alguma dúvida, não hesite em avisar por aqui :)

Obrigada pelo seu empenho!

**Comment by JimmyMedeiros82** [comment]
Caros, podemos seguir com os ajustes finais da tradução para publicarmos uma nova lição?

**Comment by aracele** [comment]
Oi @FranciscoNabais como está o andamento desta tradução? Conseguiu avaliar as sugestões dos revisores?

**Comment by FranciscoNabais** [comment]
Boa tarde a todos.

Antes de mais quero pedir desculpa pela longa demora na tradução desta lição. Nos ultimos meses, apesar de ter feito a maioria da tradução e testes, entre trabalhos e avaliações paraa faculdade e projetos paralelos, tem-me restado muito pouco tempo para a concluir.
Assim, pedindo mais uma vez desculpa, queria confirmar que apenas em finais de junho é que poderei entregar a correção já que me encontro em época de avaliações.

Com os melhores cumprimentos,
Francisco Nabais.

**Comment by joanacvp** [comment]
Hello @anisa-hawes. @FranciscoNabais is translating the lesson Cleaning Data with OpenRefine, and there seems to be a problem on line 160 of the english version. When we click on "initial OpenRefine project" it doesn't download it (or either opens a new window). Can you help us on this please? Thank you

**Comment by FranciscoNabais** [comment]
Boa tarde @aracele. 

Durante a tradução da lição 'Limpar dados com o OpenRefine' surgiu-me um problema, na linha 79 o link enquadrado na seguinte frase "o Download diretamente do projeto inicial OpenRefine", não parece estar a funcionar corretamente, já que não inicia nenhum download nem abre uma nova janela após a tentativa de acesso pelo utilizador.
Conseguiria ajudar-me?

Com os melhores cumprimentos,
Francisco Nabais.

**Comment by FranciscoNabais** [comment]
Boa tarde a todos.

Já submeti as correções ao texto e atualizei uma das imagens.
Penso que após a resolução do problema com o link mencionada anteriormente, a lição estará pronta.

Com os melhores cumprimentos,
Francisco Nabais.

**Comment by anisa-hawes** [comment]
Hello @joanacvp and @FranciscoNabais. Thank you for getting in touch!

Reviewing [the Markdown file for the original EN lesson](https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/cleaning-data-with-openrefine.md), I notice that the links are formatted in a different way than we recommend formatting them today....but they should still work! 

Today we use this format, e.g.:

`A [análise dos sentimentos ou a mineração de opinião](https://myrabr.com/blog/analise-de-sentimento/) é utilizada para extrair automaticamente informações sobre a conotação negativa ou positiva da linguagem de um documento.`

Anyway, you're correct, that the link at line 160 directing to <https://data.freeyourmetadata.org/powerhouse-museum/phm-collection.google-refine.tar.gz> does not work. I notice that the download does initiate when I copy-and-paste the link directly, but not when I click on it. Meanwhile, other links in the lesson appear to function as expected. 

I will investigate what is going wrong, and write you a message here when I have found a solution! One option to consider is uploading the .zip file to our own assets repository.

**Comment by aracele** [comment]
> Boa tarde a todos.
> 
> Já submeti as correções ao texto e atualizei uma das imagens. Penso que após a resolução do problema com o link mencionada anteriormente, a lição estará pronta.
> 
> Com os melhores cumprimentos, Francisco Nabais.

Muito obrigada, @FranciscoNabais!

**Comment by FranciscoNabais** [comment]
> > Boa tarde a todos.
> > Já submeti as correções ao texto e atualizei uma das imagens. Penso que após a resolução do problema com o link mencionada anteriormente, a lição estará pronta.
> > Com os melhores cumprimentos, Francisco Nabais.
> 
> Muito obrigada, @FranciscoNabais!

Eu é que tenho a agradecer pela colaboração e ajuda de todos os intervenientes!
Se for necessário algum coisa, não hesitem em contactar-me.

**Comment by anisa-hawes** [comment]
Hello all,

Please note that as part of a reorganisation of the /pt directory, this lesson's .md file has been moved to a new location within our Submissions Repository. 

It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/limpar-dados-openrefine.md

A consequence is that this lesson's preview link has changed. It is now: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/limpar-dados-openrefine


Please let me know if you encounter any difficulties or have any questions.
Very best, Anisa

I am confused because I note that there are two Issues with the same title: Tradução da lição 'Limpar dados com o OpenRefine'. [This Issue #427](https://github.com/programminghistorian/ph-submissions/issues/427#top) and also #410.

**Comment by DanielAlvesLABDH** [comment]
Caros @FranciscoNabais e @aracele , como está esta revisão? Podemos avançar para publicação ou falta algo?

**Comment by aracele** [comment]
Olá @DanielAlvesLABDH pelo que chequei faltava apenas resolver um link quebrado para finalizar tudo. Você conseguiu ver isso @FranciscoNabais ?

**Comment by FranciscoNabais** [comment]
Olá @DanielAlvesLABDH e @aracele, o problema do link ainda não foi resolvido. Pelo que entendi a Dra. @anisa-hawes iria investigar este problema e enviar-nos uma mensagem assim que tivesse novidades.

**Comment by anisa-hawes** [comment]
> Hello @joanacvp and @FranciscoNabais. Thank you for getting in touch!
> 
> Reviewing [the Markdown file for the original EN lesson](https://github.com/programminghistorian/jekyll/blob/gh-pages/en/lessons/cleaning-data-with-openrefine.md), I notice that the links are formatted in a different way than we recommend formatting them today....but they should still work!
> 
> Today we use this format, e.g.:
> 
> `A [análise dos sentimentos ou a mineração de opinião](https://myrabr.com/blog/analise-de-sentimento/) é utilizada para extrair automaticamente informações sobre a conotação negativa ou positiva da linguagem de um documento.`
> 
> Anyway, you're correct, that the link at line 160 directing to https://data.freeyourmetadata.org/powerhouse-museum/phm-collection.google-refine.tar.gz does not work. I notice that the download does initiate when I copy-and-paste the link directly, but not when I click on it. Meanwhile, other links in the lesson appear to function as expected.
> 
> I will investigate what is going wrong, and write you a message here when I have found a solution! One option to consider is uploading the .zip file to our own assets repository.

Dear @FranciscoNabais and @aracele,

Is the link you are asking about this one: https://data.freeyourmetadata.org/powerhouse-museum/phm-collection.google-refine.tar.gz? 

I'm sorry because I have been unclear. I am able to download the data asset from that link. But I wondered if it would be good to link to the data asset that has been uploaded to our own assets repository: https://programminghistorian.org/assets/phm-collection.tsv. 

I now see that the Powerhouse Museum has changed its name to the Museum of Applied Arts and Sciences and their web address has changed to https://www.maas.museum/. I note that you've updated the screenshot Figure 1.

--

Caros @FranciscoNabais e @aracele,

É a ligação que está a perguntar sobre isto: https://data.freeyourmetadata.org/powerhouse-museum/phm-collection.google-refine.tar.gz? 

Peço desculpa porque não fui claro. Sou capaz de descarregar o bem de dados dessa ligação. Mas pergunto-me se seria bom fazer a ligação ao bem de dados que foi carregado no nosso próprio repositório de bens: https://programminghistorian.org/assets/phm-collection.tsv. Esta é a ligação utilizada na lição EN.

Vejo agora que o Powerhouse Museum mudou o seu nome para Museum of Applied Arts and Sciences e o seu endereço web mudou para https://www.maas.museum/. Imagem de ecrã actualizada Figura 1.

**Comment by FranciscoNabais** [comment]
Boa tarde a todos,

Concluí agora a correção. Penso que esteja tudo pronto para ser publicado.

Thank you very much for your help @anisa-hawes!
E muito obrigado também aos restantes colaboradores nesta lição.

Se for necessário mais alguma correção estarei disponível.

**Comment by anisa-hawes** [comment]
Thank you, @FranciscoNabais!

Hello @aracele. I will make time to typeset and apply perma.cc links to this lesson on Thursday. I will leave a note here in the Issue to let you know when everything is ready.

Anisa

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH ,

This lesson is almost ready for your final review.

- Preview: <http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/limpar-dados-openrefine>
- .md file: [/esbocos/traducoes/limpar-dados-openrefine.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/limpar-dados-openrefine.md)
- images: [/images/cleaning-data-with-openrefine](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/cleaning-data-with-openrefine)
- assets: [already on Jekyll](https://github.com/programminghistorian/jekyll/blob/gh-pages/assets/phm-collection.tsv)

Sustainability + accessibility actions status:

- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Addition of alt-text for all figures
- [x] Receipt of translator's copyright agreement

Olá @FranciscoNabais e @aracele : 
Como parte do nosso compromisso com a acessibilidade, pedimos agora aos autores que forneçam `alt-text` descritivos para acompanhar as imagens das figuras. Por favor, insira o alt-text no modelo que criei ao longo da lição: `alt="Visual description of figure image". Reuni [alguns recursos na nossa Wiki](https://github.com/programminghistorian/jekyll/wiki/Achieving-Accessibility-Alt-text-Colour-Contrast#alt-text) como orientação.

@FranciscoNabais : O nosso formulário de declaração serve para reconhecer os seus direitos de autor e conceder-nos permissão para publicar esta lição. Por favor, pode descarregar [este formulário](https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf), preenchê-lo e enviá-lo por e-mail para mim (admin [@] programminghistorian.org)?

Next steps @aracele  :
- [x] We already have PT translations of the original authors' bios in `ph_authors.yml`
- [ ] Daniel and I can prepare x2 posts for our Twitter/Mastodon Bot  + an initial "announcement" post.

Let me know if you have any questions, or if I can help with anything.

Anisa

**Comment by anisa-hawes** [comment]
Olá @FranciscoNabais. 

Por favor, poderia fornecer texto descritivo alt-text para acompanhar as imagens?
Acrescentei um modelo `alt="Visual description of figure image"`

Por favor, descarregue [este formulário] (https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf), para reconhecer os seus direitos de autor como tradutor e conceder-nos autorização para publicar esta lição. Envie-o por correio electrónico para mim (admin [@] programminghistorian.org).

Muito obrigado ! 

Anisa

cc. @aracele

**Comment by FranciscoNabais** [comment]
> admin [@] programminghistorian.org

Olá, @anisa-hawes 

Concluí agora o texto descritivo para acompanhar as imagens. Muito obrigado pelos recursos disponibilizados!
Penso que esteja tudo correto, no entanto, se forem encontrados erros encontro-me à disposição. 

Com os melhores cumprimentos,
Francisco Nabais.

**Comment by anisa-hawes** [comment]
Óptimo!

Muito obrigado, @FranciscoNabais! ✨

**Comment by anisa-hawes** [comment]
Dear @DanielAlvesLABDH,

Just to confirm that this lesson is ready for your final review now that all sustainability + accessibility checks are complete.

Please find the full list of file locations [above](https://github.com/programminghistorian/ph-submissions/issues/427#issuecomment-1425622354). We already have the authors' bios translated into PT.

Anisa

**Comment by DanielAlvesLABDH** [comment]
Caros/as já inseri o DOI nesta lição e vou passar à publicação. Obrigado a todos!

**Comment by anisa-hawes** [comment]
Dear @DanielAlvesLABDH, @aracele and @FranciscoNabais,

Esta lição foi publicada e o DOI está activo  🎉  This lesson is published and the DOI is live

https://programminghistorian.org/pt/licoes/limpar-dados-openrefine
https://doi.org/10.46430/phpt0038
