### ISSUE TITLE
Revisão da tradução da lição Som dos dados

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#429]
O Programming Historian em português recebeu a proposta de tradução da lição 'Sonificação de dados (uma introdução à sonificação para historiadores)' por @GabrielaKucuruza .

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/som-dados-sonificacao-historiadores.md

Já a lição original está em: https://programminghistorian.org/en/lessons/sonification

Agradeço por mais uma contribuição feita pela Gabriela Kucuruza.

Eu serei o editor da tradução. A revisão ficará a cargo da @Ju-ms e do @Thinksamuel .
@DanielAlvesLABDH o Samuel van ransbeeck é especialista no assunto e fez o doutoramento dele em Portugal. Tenho certeza que poderá colaborar conosco nesta lição e em outras atividades do PH.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes da @GabrielaKucuruza . O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Obrigado @JimmyMedeiros82! Estamos em excelente ritmo na revisão destas lições...
Agradeço ainda a @GabrielaKucuruza, a @Ju-ms e ao @Thinksamuel por esta colaboração.
Uma boa revisão!

**Comment by JimmyMedeiros82** [comment]
Caros @Ju-ms @Thinksamuel e @GabrielaKucuruza , temos alguma atualização para compartilhar?

**Comment by Ju-ms** [comment]
Obrigada, @JimmyMedeiros82, @GabrielaKucuruza e @Thinksamuel! E desculpem-me pela demora. É um prazer participar da revisão; achei o tutorial muito instigante! Na minha opinião, essa lição apresenta vários desafios de tradução e a Gabriela encontrou excelentes soluções para sentidos figurados e “brincadeiras” com a língua que o texto original traz. Espero que os comentários a seguir sejam úteis! 

Linha 16: o sobrenome do Samuel está em letra minúscula.

Linha 31: o trecho “but often we forget what a creative act visualization is” está traduzido  como “mas muitas vezes nós esquecemos o que é um ato criativo de visualização”, mas acho que ficaria mais preciso dizer “muitas vezes nós esquecemos que a visualização é um ato de criatividade” ou “o quanto a visualização é um ato de criatividade”.

Linha 33: tem um problema de digitação; “coisas capturas” em vez de “coisas capturadas”. Uma observação: achei fantástica a maneira como a Gabriela traduziu “I literally perform the past in the present, and so the assumptions, the transformations, I make are foregrounded”.

Linha 37: continuum acabou saindo com acento agudo.

Linha 43: “Na primeira, usaremos um sistema disponível gratuitamente para uso desenvolvido por Jonathan Middleton chamado Musicalgorithms (Algorítmos Musicais), para introduzir algumas das questões e termos-chaves envolvidos.” Pensando nas diferenças de uso da vírgula em PT e EN, eu acho que essa frase ficaria mais fluida da seguinte forma: “um sistema desenvolvido por Jonathan Middleton, disponível gratuitamente para uso, chamado…”. É uma questão de estilo, no entanto. A vírgula antes de “para introduzir algumas” deve ser retirada. Se quisermos evitar a repetição de “para” (finalidade), que aparece no trecho “para uso” e logo depois “para introduzir”, podemos substituir o segundo por “a fim de”. Porém, de novo, é opcional.

Linha 60 (no finalzinho): diferentemente do inglês, a regra do uso de parênteses em PT pede que ele seja colocado dentro da frase anterior, antes do ponto final.
 
Linha 62: “e o som resultante pode ser "confuso" (2015, p.422)”; esse “e” está sobrando na frase e deve sair.

Linha 69: o embedding do vídeo parece não estar funcionando.

Linha 71: Sugiro “Se já conhecia essa música, provavelmente ouviu as 'palavras'”, no lugar de “Se já conhecia essa música, provavelmente ouviu as verdadeiras 'palavras'”. Mais adiante no mesmo parágrafo, tem um trecho com problema: “Se você música não conhecia esse música”. Depois, “um absurdo ilegível” poderia ser “um absurdo inaudível”. Ao final, “Esses exemplos mostram como qualquer representação de dados que podemos ouvir/ver não está lá, estritamente falando” poderia ficar “Este exemplo mostra como em qualquer representação de dados podemos ouvir/ver o que não está, estritamente falando, lá”.

Linha 75: Mover os parênteses para antes do ponto final. Mesma coisa na linha 109, no final da 113, na 119, 144, 209, 239, 390.

Linha 87: Na nota de tradução, não entendi o trecho “então a disponível em 2016, e ainda disponível no site para uso”.

Linhas 111, 117, 139, 146, 153, 176: as imagens não aparecem para mim.

Linha 113: Tem um parêntese onde deveria haver uma vírgula.

Linha 119: “a cerâmica que se tem interesse são mercadorias humildes,” - sugiro colocar tudo no plural, ou no singular. Uma opção de refraseamento, no geral: “Então, se acaso as cerâmicas de interesse forem mercadorias mais despretensiosas, talvez elas possam ser mapeadas em relação à extremidade inferior da escala(...)”. Certamente, é uma opção mais livre em relação ao original, mas pensei nela para deixar o texto mais fácil/claro de ler. 

Linha 121: Ao final, faltou a crase em “e a nossa experiência dos dados”.

Linha 123: que tal “ponto de inflexão” em vez de “ponto de pontuação”?

Linha 178: Para evitar o “você” brasileiro, talvez usar “Quando se tem dados com várias vozes,(...)”.

Linha 182: erro de digitação onde se deve ler “se familiarizando”.

Linha 295: a palavra “script” está repetida.

Linha 364: “escreveu” deveria ser “escrever”.

**Comment by Thinksamuel** [comment]
Oi Pessoal, com muito atraso começei corrigir o texto. Acabei de passar pela introdução e ao invés de anotar linha por linha, mando o texto em inteiro. Amanha mando o resto más queria dar um sinal de vida.
[Introdução-liçãosomdosdados.txt](https://github.com/programminghistorian/ph-submissions/files/8149589/Introducao-licaosomdosdados.txt)

**Comment by Thinksamuel** [comment]
Parte 2: linha 39 -123: essa parte já é muito mais claro. 
Apenas:
linha 67: nos percebemos --> _percebemos_
linha 73: ou pontos fora da curva estranhos --> tira estranhos que fica: _pontos fora da curva_
linha 83: Nos começaremos --> _Começaremos_
linha 113: scale options’ (opções de escala) --> _opções de escala musical_ 
linha 121 e 123: Nos começamos --> _Começamos_

Prefiro de não usar _nos_  quando não há uma necessidade de ênfase. 
Acho bom as sugestões de revisão da Juliana.
Vou continuar agora o resto do texto.

**Comment by Thinksamuel** [comment]
Para finalizar:
Linha 182: Se ainda não usou Python ainda --> Se não usou Python ainda
Linha 220 e 239: **discrepancia entre meuficheiro e meuarquivo**
Linha 239: **O Quicktime não abre mais ficheiros MIDI**
Linha 280: inglês --> inglês estadunidense
Linha 295: o seu final script final --> o seu script final
Linha 308: o número de segundos para representar o ano em que a música --> o número de segundos para representar um ano na música
Linha 310: e como muitas oitavas mapeiam os tons contra. --> o nº de oitavas em que os tons são mapeados
Linha 312: Agora nós passamos --> agora passamos

**Comment by Thinksamuel** [comment]
O tutorial é muito bom para iniciantes. Não encontrei erros de argumentação fora que Quicktime não abre ficheiros MIDI.

**Comment by JimmyMedeiros82** [comment]
Agradeço ao @Thinksamuel e @Ju-ms pelas sugestões de melhorias na tradução.
@GabrielaKucuruza agora é com você! 

Vamos seguir para publicação de mais uma lição traduzida.

**Comment by GabrielaKucuruza** [comment]
@Thinksamuel e @Ju-ms agradeço demais pelas revisões da tradução! Espero conseguir fechar essa tradução essa semana :) 
Vamos que vamos, @JimmyMedeiros82!

**Comment by JimmyMedeiros82** [comment]
@GabrielaKucuruza os ajustes estão ok! 
Agradeço pela sua colaboração na tradução e ajustes, assim como ao cuidadoso trabalho de revisão da @Ju-ms e do @Thinksamuel 

@DanielAlvesLABDH temos outra lição pronta para publicação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos/as pelo excelente trabalho! Dei início à revisão final para publicação. Alterei o link para o ficheiro no comentário inicial.

**Comment by DanielAlvesLABDH** [comment]
Lição revista, DOI requisitado. Amanhã (segunda) julgo que ficará publicada. Obrigado à @GabrielaKucuruza pela tradução de uma lição tão exigente. Excelente trabalho! Obrigado também à @Ju-ms e ao @Thinksamuel pelas revisões, bem como ao @JimmyMedeiros82 por mais uma edição! Abraço a todos

**Comment by DanielAlvesLABDH** [comment]
Caros/as temos mais uma lição publicada. Parabéns e obrigado por todo o vosso trabalho! @JimmyMedeiros82 pode actualizar o bot do Twitter e encerrar o ticket. Obrigado!

**Comment by JimmyMedeiros82** [comment]
Ótima notícia, @DanielAlvesLABDH 
parabéns a todos. Nossa 23ª lição publicada
