### ISSUE TITLE
Análisis de corpus con CorText Manager

### ISSUE THREAD

**Issue by rivaquiroga** [programminghistorian/ph-submissions#433]
_Programming Historian en español_ ha recibido la lección original "Análisis de corpus con CorText Manager" por parte de Yuri Saldarriaga (@yurisago) y Matthieu de Castelbajac. La editora de esta lección será @rivaquiroga. Esta lección se encuentra en estos momentos en fase de revisión y puede leerse en:

**Vista previa**
http://programminghistorian.github.io/ph-submissions/es/borradores/originales/analisis-de-corpus-con-cortext-manager

**Archivo**
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/originales/analisis-de-corpus-con-cortext-manager.md

**Imágenes**
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/analisis-de-corpus-con-cortext-manager

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. 

Otros personas de nuestra comunidad también están invitadas a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el equipo de autores pueda empezar a trabajar en los cambios solicitados. 

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si algún/a participante quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestra *ombudperson*.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Quienes violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta a nuestra *ombudsperson* [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by rivaquiroga** [comment]
¡Hola, Yuri y Matthieu! Muchas gracias por su interés en publicar en _Programming Historian en español_. 
En los próximos días haré una lectura inicial de la lección, con el fin de hacer los últimos ajustes antes de iniciar el proceso de revisión.

**Comment by rivaquiroga** [comment]
¡Hola @yurisago!
Espero que hayan tenido unas felices fiestas y un buen inicio de año.
A continuación encontrarán las sugerencias que sería importante que incorporen a la lección antes de que comience el trabajo de revisión. Cada una tiene una casilla de verificación antes, para que puedan ir marcando los cambios que han ido haciendo.
Los comentarios que se refieren a alguna sección específica indican el párrafo al que aluden, tomando en cuenta la numeración disponible en [la previsualización de la lección](http://programminghistorian.github.io/ph-submissions/es/lecciones/analisis-de-corpus-con-cortext-manager). Los cambios deben hacerlos directamente en el archivo publicado acá en GitHub: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lecciones/analisis-de-corpus-con-cortext-manager.md


## Archivos faltantes
Cuando hicieron el envío no incluyeron los siguientes documentos que son necesarios para poder completar la lección: 

- archivo zip con las demandas a favor
- archivo zip con las demandas en contra
- archivo zip con todas las demandas
- archivo excel o csv con la columna correspondiente a la variable año 
- archivo excel o csv con la columna correspondiente a la variable grupo

- [ ] Estos archivos deben enviármelos por correo electrónico para que pueda subirlos. 


## Contexto sobre el tema
- [ ] Sería relevante dar un poco de contexto sobre la legislación del aborto en Colombia. Esto permitiría entender, por ejemplo, por qué el corpus se inicia con documentos de 1994. ¿Es solo porque esos son los que están disponibles? ¿O porque ese año ocurrió algo en particular? Para interpretar mejor los resultados también sería importante conocer algunos hitos. ¿Está completamente despenalizado el aborto en Colombia? ¿Solo algunas causales? ¿Desde cuándo? No tiene que ser algo largo. Un párrafo que entregue este contexto permitiría luego poder entender los resultados obtenidos. Este párrafo podría ir justo después de los objetivos de aprendizaje.


## Comentarios específicos sobre secciones particulares de la lección


- [ ] Eliminar el header # Contenidos.

¶1
- [ ] En la segunda oración la redacción es confusa. De todos modos, se sugiere revisar esa parte, ya que AntConc no tiene versión en línea. Es necesario descargar el programa para poder utilizarlo.
- [ ] Es necesario hacer alguna mención a VoyantTools, ya que actualmente [existe una lección](https://programminghistorian.org/es/lecciones/analisis-voyant-tools) sobre el uso de esa herramienta disponible en Programming Historian. Sería relevante poder indicar qué cosas permite CorText Manager que esa otra herramienta no, para que así las personas puedan evaluar en el futuro qué herramienta les sirve más dependiendo de los objetivos de su análisis. 

¶2
- [ ] Sugiero redactar el segundo objetivo de forma más general: Comparar corpus que dan cuenta de posiciones divergentes utilizando CorText Manager.  

¶3
- [ ] Sería útil incluir un enlace a IFRIS para quienes quieran conocer más sobre esa institución. En el sitio web aparecen otras instituciones además de esta. Quizás sería bueno incluirlas también.


¶4
- [ ] Cambiar el título de esa sección por “Preparación de los documentos”. Es decir, plantearlo como algo general, no como algo exclusivo del análisis que se muestra como ejemplo. 
- [ ] Agregar un enlace a la frase “archivo de la Corte Constitucional” que lleve a la sección de esa página de la cual descargaron los documentos. 


¶8-¶10
- [ ] Sería relevante incluir capturas de pantalla que muestres dónde crear el proyecto y las opciones que hay que marcar para preparar los documentos para el análisis. Si bien estando dentro de la plataforma es fácil ver dónde está el botón, hay muchas personas que le dan una mirada rápida a la lección antes de seguir todos los pasos. Como en este caso implica crearse una cuenta, es importante incluir capturas de pantalla para que quienes exploren la lección puedan hacerse una idea de cómo se ve la plataforma. 

¶13
- [ ] Sería necesario incluir una captura de pantalla que muestre cómo iniciar un análisis (start script). 

¶17
- [ ] Se señala que hay que preguntar directamente a los creadores sobre la confiabilidad de los resultados para otros idiomas. ¿Tienen certeza de que si alguien los contacta responden este tipo de preguntas? Si es así, entonces se debería agregar un enlace a la información de contacto (¿el foro? ¿correo electrónico?). 

¶21
- [ ] Agregar captura de pantalla sobre esta parte del proceso.

¶23-24
- [ ] Google Sheets también puede agregar elementos de formato, al igual que Excel. ¿Tiene que ser un archivo de extensión .xlsx o .xls el que se debe subir? ¿O puede ser .csv? Si acepta .csv, sería posible utilizar cualquiera de las dos herramientas y guardar el archivo resultante en ese formato para evitar problemas. 
- [ ] Se sugiere incluir un pantallazo del paso de creación del Corpus List Indexer. 

¶26
- [ ] Se sugiere usar términos en español (pro-vida en vez de pro-life).



¶26-27
- [ ] Se sugiere agregar capturas de pantalla que muestren los pasos claves para llegar al resultado que muestran acá.

¶29-30
- [ ] Incluir 20 n-gramas en esta visualización hace que sea muy difícil poder interpretar los resultados. Hay líneas de colores muy similares, por lo que cuesta distinguir cuál corresponde a qué n-grama y, por lo tanto, interpretar los resultados. La sugerencia sería hacer estos mismos gráficos con menos n-gramas. 
- [ ] Sería interesante poder proponer alguna interpretación de los resultados obtenidos. Por ejemplo, por qué algunos n-gramas aparecen más en algunos años que en otros. 

¶31
- [ ] También sería necesario incluir una captura de pantalla sobre este paso del proceso.

¶34
- [ ] Como es difícil identificar los triángulos porque son muy pequeños, quizás se podría indicar que son los que tienen asociados los números. 
- [ ] No logré distinguir cuáles son las palabras en violeta en este gráfico. 
- [ ] ¿Hay alguna razón para que “in favor” y “against” estén en inglés?
- [ ] Sería útil referirse a las burbujas no solo por su color si no por su posición, ya que a algunas personas les puede resultar difícil ver colores tan tenues. Por ejemplo, hablar de “la burbuja verde oscura en la esquina superior izquierda”. 

¶40
- [ ] También sería necesario incluir una captura de pantalla para ilustrar estos pasos del proceso.

¶43
- [ ] Tweeter -> Twitter
- [ ] En vez de poner el enlace directo en el texto, enlazar los términos relevantes. Por ejemplo, que la frase “existen videos tutoriales” tenga el enlace a la página correspondiente. 
- [ ] Sería útil mencionar en la conclusión qué otras opciones de CortextManager no cubiertas en el tutorial podrían ser interesantes de explorar en el futuro. Por ejemplo, la opción “invite a co-worker”. Eso es algo que otras herramientas como Voyant Tools no tienen, así que puede ser algo de interés para quienes quieran realizar algún análisis de forma colaborativa.

**Comment by anisa-hawes** [comment]
Hello all, 

Please note that this lesson's .md file has been moved to a new location within our Submissions Repository. It is now found here: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/es/borradores/originales

A consequence is that this lesson's preview link has changed. It is now: [http://programminghistorian.github.io/ph-submissions/es/borradores/originales/analisis-de-corpus-con-cortext-manager](http://programminghistorian.github.io/ph-submissions/es/borradores/originales/analisis-de-corpus-con-cortext-manager)

Please let me know if you encounter any difficulties or have any questions.

Very best,
Anisa

**Comment by rivaquiroga** [comment]
Esta propuesta de lección será archivada, debido a que los autores no están todavía en condiciones de compartir los datos necesarios para que las personas puedan completar el tutorial. Una vez que el artículo en que presentan los resultados esté publicado y puedan utilizar los datos, retomaremos el proceso de edición.
