### ISSUE TITLE
Revisão da tradução da lição "Introduction to MySQL with R"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#439]
O Programming Historian em português recebeu a proposta de tradução da lição 'Introdução ao MySQL com R' por Jéssica Evelyn Santos.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/introducao-mysql-r.md. As imagens estão na pasta https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/introducao-mysql-r. Os ficheiros de dados estão na pasta https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/introducao-mysql-r

A lição original está em: https://programminghistorian.org/en/lessons/getting-started-with-mysql-using-r

Agradeço à @jessicasantos-hst pela contribuição.

Eu serei o editor da tradução. A revisão ficará a cargo da @DaliaGuerreiro e do @leofn, a quem desde já agradeço a colaboração.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linhas do ficheiro de maneira que facilite os ajustes da Jéssica. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by leofn** [comment]
Olá @DanielAlvesLABDH e colegas, saudações. Estou lendo as diretrizes e já estou começando a revisar. Eu estou imaginando que em 20 dias conseguirei concluir. @DaliaGuerreiro você está fazendo também? Se quiser podemos dividir. Abs

**Comment by DanielAlvesLABDH** [comment]
Obrigado a ambos, uma vez mais. Abraço

**Comment by leofn** [comment]
Pessoal, bom dia, concluindo esta semana.
Abs

**Comment by leofn** [comment]
Cara Jessica (@jessicasantos-hst ), em primeiro lugar gostaria de agradecer pelo seu interesse em contribuir para o Programming Historian em português! Também aproveito a oportunidade para parabenizar pelo trabalho: é uma tradução excelente. 

Peço desculpas pela demora, eu estava tentando me localizar no _workflow_ de vocês!

Seguem os pontos que sugiro revisão, alguns tentando aproximar a linguagem do leitor brasileiro:

- [ ] linha 37: eu traduziria _Handling_ por **Manipular** ao invés de Tratar;
- [ ] linhas 55, 59, 61, 494 e outras: eu traduziria _query_ por **consultar** ao invés de solicitar. Como este termo apareceu muitas vezes seria ideal, se a autora concordar com a sugestão, uma revisão geral no texto com essa adequação (Após escrever esta sugestão eu vi que na linha 85 encontramos o trecho _SQL significa Structured Query Language_ (Linguagem estruturada de consulta) essa tradução parece reforçar a ideia de mantermos um padrão em todo o texto de _query_ como consulta. Na linha 754 _query_ foi traduzida por consulta; 
- [ ] linha 73: eu substituiria _Podes_ por "Você pode..."
- [ ] linhas 237, 254, 462, 503: eu sugiro colocar os dois termos "relâmpago/raio" apenas para facilitar para o leitor;
- [ ] linha 254: eu traduziria _keyboard command_  por **tecla de atalho** ao invés de comando de teclado;
- [ ] linha 277: estilo, eu inverteria a frase e colocaria "**Se preferir,** todas as etapas acima podem ser realizadas com um comando." 
- [ ] linhas 348 e 374: eu substituiria _Se tem curiosidade_ por **Se tiver curiosidade**;
- [ ] linha 356: eu substituiria _Adicione a declaração seguinte_ ao programa por **Adicione o seguinte comando ao programa**. Outro detalhe sobre isso: costumamos chamar os códigos em R de scripts, não de programa. Talvez isso possa ser considerada uma alteração para toda a lição.
- [ ] linha 446: eu substituiria _depois o faremos no R_ por **depois faremos isso no R**.
- [ ] linha 655: eu fiquei na dúvida se não seria melhor falarmos em **aspas** ao invés de _dois apóstrofos_ para facilitar a compreensão;
- [ ] linhas 673 e 675:  falta um "s", _valores separados por vírgula_**s**;
- [ ] linha 675: por questão de estilo eu sugiro substituir _iremos_ por **vamos;**;
- [ ] linha 702: eu tive duas dúvidas aqui pensando no cientista social brasileiro. Traduzir _looping through each row of the data frame_ por _iterar cada linha de dado do data frame_ seria causar mais dúvidas que explicar? Uma saída possível seria, ou explicar o que é iterar para o leitor, ou fazer uma tradução literal de _looping_ por exemplo, "repetir para cada linha do data frame";
- [ ] linha 861: substituir _Aqui abaixo está o que o gráfico deve corresponder:_ por **Aqui abaixo está o gráfico que deveria aparecer:**;
- [ ] linha 893: incluir **em R** para que linha fique: **O programa em R usado** 
Por favor, me avise caso haja algum problema ou dúvida. 
Fico à disposição. Bom trabalho 👍

**Comment by DanielAlvesLABDH** [comment]
Obrigado pela revisão @leofn. @jessicasantos-hst vamos aguardar pelos comentários da @DaliaGuerreiro e depois você revê o ficheiro de uma vez só, pode ser?

**Comment by jessicasantos-hst** [comment]
Muito obrigada pela excelente revisão, @leofn! 

Farei como @DanielAlvesLABDH sugeriu, aguardarei as sugestões de @DaliaGuerreiro para a submeter a tradução revisada.

**Comment by DaliaGuerreiro** [comment]
Alterações sugeridas:

Substituiria:
­	ícone -> imagem
­	em um -> num

41 - Uma breve discussão mais detalhada -> Uma breve discussão
47 - instalar programas como o R e o RStudio ->instalar os programas R e RStudio, entre outros,
85 - … e possui uma versão gratuita que pode ser baixada. -> e possui uma versão gratuita que pode ser utilizada
89 - MySQL Workbench em razão de ser uma *GUI* -> MySQL Workbench porque é uma *GUI*
216- container -> contentor, recetáculo
676 - É possível checar -> é possível verificar
865 [Selecte] tem um espaço a mais antes do ponto nomeado .

**Comment by jessicasantos-hst** [comment]
Muito obrigada pelas sugestões @DaliaGuerreiro!

Professor @DanielAlvesLABDH, alterei o texto com as sugestões de revisão apontadas acima. Devo abrir um pull request em https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/introducao-mysql-r.md para submeter o arquivo atualizado?

**Comment by DanielAlvesLABDH** [comment]
Obrigado @jessicasantos-hst, pode submeter o commit directamente não precisa abrir um pull request

**Comment by jenniferisasi** [comment]
@DanielAlvesLABDH agora temos um "tópico" para R ([#2523](https://github.com/programminghistorian/jekyll/pull/2524)), inclua-o com "r" nos metadados da lição. Obrigada

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH a lição me parece pronta para publicação. Estou correto?

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todas/os e uma vez mais as minhas desculpas pelo enorme atraso. Já requisitei o DOI, fiz as últimas verificações no ficheiro e assim que possível darei início ao processo de publicação. Uma vez mais obrigado à @jessicasantos-hst pela tradução, ao @leofn e @DaliaGuerreiro pelas revisões. Obrigado também à @jenniferisasi pela indicação do novo tópico e ao @JimmyMedeiros82 pela lembrança ;-)

**Comment by DanielAlvesLABDH** [comment]
A lição já está publicada. Faltava resolver um problema técnico que foi ultrapassado com a ajuda da Anisa e da Zoe. Obrigado a todos/as uma vez mais. Assim que puder irei actualizar o bot do Twitter e encerrar o ticket.

**Comment by anisa-hawes** [comment]
Hooray! Thanks all for your patience! ✨

**Comment by DanielAlvesLABDH** [comment]
Bot do Twitter actualizado. Já são 25!
