### ISSUE TITLE
Revisão da tradução Contagem e coleta de dados de investigação com Unix

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#440]
O Programming Historian em português recebeu a proposta de tradução da lição 'Contagem e coleta de dados de investigação com Unix' feita pela Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/contagem-mineracao-dados-investigacao-unix.md

Já a lição original está em: https://programminghistorian.org/en/lessons/research-data-with-unix

Agradeço pela contribuição feita pelo @felipelmc .

Eu serei o editor da tradução. A revisão ficará a cargo do @danielbonattoseco e @ianaraujo .
@DanielAlvesLABDH indiquei dois revisores do lado brasileiro pela simplicidade da lição. Pode ser? Caso prefira seguir com o planejamento inicial, faço o ajuste da equipe. 

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes da Vânia Rosa . O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82, parece-me bem. No final, eu e a Joana fazemos uma revisão geral e ajustamos se for o caso. Obrigado por mais uma lição. Parceria excelente!

**Comment by JimmyMedeiros82** [comment]
Perfeito, @DanielAlvesLABDH

**Comment by danielbonattoseco** [comment]
@felipelmc Estou realizando a revisão e a lição original utiliza Git Bash 1.9.0 e Windows 7, ambos sem suporte atualmente. A própria [documentação do Git Bash][(https://github.com/msysgit/msysgit/releases) orienta a utilização do Git for Windows 2.x. A tradução, no entanto, foi realizada utilizando os mesmos recursos. Você chegou a testar os recursos? Se sim, utilizando as mesmas configurações ou recursos mais atualizados?

**Comment by danielbonattoseco** [comment]
@felipelmc Estou realizando a revisão e a lição original utiliza Git Bash 1.9.0 e Windows 7, ambos sem suporte atualmente. A própria [documentação do Git Bash](https://github.com/msysgit/msysgit/releases) orienta a utilização do Git for Windows 2.x. A tradução, no entanto, foi realizada utilizando os mesmos recursos. Você chegou a testar os recursos? Se sim, utilizando as mesmas configurações ou recursos mais atualizados?

**Comment by felipelmc** [comment]
Obrigado pela observação, @danielbonattoseco. De fato, não havia me atentado às versões com relação ao Windows. Uso Linux, então não pude testar esses recursos. Acredito que valha a pena uma atualização.

**Comment by JimmyMedeiros82** [comment]
Será que a atualização da versão na lição sem o teste pode acarretar problemas aos usuários?
Neste caso, sem testar, sugiro manter as versões indicadas na lição original.

**Comment by felipelmc** [comment]
De fato, acredito que alterar sem testar seja um problema. Mas acredito que a alteração nesse caso seja importante justamente para que a lição seja realmente útil aos usuários de Windows (supondo que os recursos estejam outdated de fato). @danielbonattoseco, você conseguiria fazer o teste? Caso não possa, acredito que eu consiga encontrar algum modo de abrir o Windows dentro do Linux e testar.

**Comment by danielbonattoseco** [comment]
@felipelmc @JimmyMedeiros82 testei todos os comandos utilizando Windows 10 e Git Bash 2.34.1 (ultima _release_ estável) e todos os comandos funcionaram de acordo. Podemos apenas modificar os recursos na lição e manter o restante, adicionarei isto à revisão ok?

**Comment by danielbonattoseco** [comment]
Excelente tradução, parabéns @felipelmc e obrigado pela contribuição. Seguem abaixo algumas sugestões, muitas delas opcionais.

- [x] Linha 43 et.al. - Manter o padrão "Unix shell" durante o corpo da lição, evitando a inversão "shell Unix";
- [x] Linha 51 - As instruções de instalação disponíveis na lição original através do Open Hatch, além de estarem em um servidor já desativado e acessado apenas pelo Internet Archive, possui instruções para o Git Bash 1.x, descontinuado. A [própria documentação do Git for Windows](https://github.com/git-for-windows/git/wiki/Technical-overview) possui instruções de instalação e personalização, sendo uma fonte mais atualizada e segura das etapas;
- [x] Linha 55 - Substituir "escrita utilizando o Git Bash 1.9.0 e o sistema operacional Windows 7" por "revista utilizando o Git Bash 2.34.1 e o sistema operacional Windows 10";
- [x] Linha 65 - O termo "suítes padrão de escritório", embora correto, ficou bem difícil de entender. Acho que seria bom colocar ao menos um exemplo adicionando "(como o pacote Office, por exemplo)" ao final;
- [x] Linha 67 - Esta linha parece estar um pouco "perdida" neste ponto da lição. Podemos substituir o trecho "O comando Unix para contagem é `wc`." na linha 83 pelo conteúdo da linha 67, eliminando-a.
- [x] Linha 69 - Corrigir "mara" por "para";
- [x] Linha 71 - O [Mini-Glossário](https://docs.google.com/document/d/1o2rw7Rf_bOZkhHzAw18PfQUzBCCGbbq7dKsAjei8tTo/edit) orienta a tradução de "print" para "exibir/apresentar"; neste caso, podemos substituir "Isso imprime, ou exibe, uma lista" por "Isso exibe uma lista";
- [x] Linha 77 - Substituir o recurso da Wikipedia para Comma-separated values em inglês pela sua versão [em português](https://pt.wikipedia.org/wiki/Comma-separated_values);
- [x] Linha 77 - As [diretrizes do PH](https://programminghistorian.org/pt/directrizes-autor#alertas-e-avisos) orientam um padrão de alert para notas (não obrigatório);
- [x] Linha 77 - Substituir "cada unidade de dado (ou células) são separados" por "as unidades de dados (ou células) são separadas";
- [x] Linha 83 - Substituir "imprimir" por "exibir";
- [x] Linha 87 - Substituir "imprime" por "exibe";
- [x] Linha 89 - Substituir "imprimir" por "exibir";
- [x] Linha 91 - Mesma issue da linha 77 sobre padrão de notas;
- [x] Linha 93 - O [Mini-Glossário](https://docs.google.com/document/d/1o2rw7Rf_bOZkhHzAw18PfQUzBCCGbbq7dKsAjei8tTo/edit) orienta a não tradução do termo "query" em "a combination of wildcards and flags to build more complex queries.";
- [x] Linha 93 - Substituir "imprime" por "exibe";
- [x] Linha 93 - Inserir "além da soma das linhas destes ficheiros." após "Isso imprime a contagem de linhas para 2014-01-31_JA_africa.tsv e 2014-01-31_JA_america.tsv".
- [x] Linha 95 - Substituir "*prints*" por "capturas";
- [x] Linha 95 - Substituir "*cópia e cola" por "copiar e colar";
- [x] Linha 95 - Alterar o ordenamento "`>` operador de redirecionamento" por "operador de redirecionamento `>`";
- [x] Linha 95 - Mesma issue da linha 93 sobre a tradução do termo query em "you can export your query results to a new file" e "This runs the same query as before";
- [x] Linha 95 - Substituir "imprimir" por "exibir";
- [x] Linha 99 - Aplicar markdown em itálico para "global regular expression print";
- [x] Linha 101 - Mesma issue da linha 93 sobre a tradução do termo query em "This query looks across all files";
- [x] Linha 101 - Substituir "imprime" por "exibe";
- [x] Linha 103 - Mesma issue da linha 77 sobre padrão de notas;
- [x] Linha 103 - Substituir "imprimidos" por "exibidos";
- [x] Linha 105 - Substituir "imprimir" por "exibir";
- [x] Linha 105 - Inserir aspas simples em "1999" em "O shell agora irá imprimir o número de vezes que a string 1999 apareceu em cada um dos ficheiros .tsv.":
- [x] Linha 105 - Mesma issue da linha 93 sobre a tradução do termo query em "This query looks for instances of the string ‘1999’";
- [x] Linha 107 - Mesma issue da linha 93 sobre a tradução do termo query em "This repeats the query,";
- [x] Linha 107 - Substituir "imprime" por "exibe";
- [x] Linha 111 - Mesma issue da linha 77 sobre padrão de notas;
- [x] Linha 113 - Mesma issue da linha 93 sobre a tradução do termo query em "This query looks in the defined files";
- [x] Linha 125 - Mesma issue da linha 93 sobre a tradução do termo query em "to build complex queries in a way that suggests";
- [x] Linha 131 - Mesma issue da linha 93 sobre a tradução do termo query em "to query across research data";
- [x] Linha 138 - Remover a vírgula em "Uma vez que a sua investigação cresce, e"

Grande abraço.

**Comment by felipelmc** [comment]
Muito obrigado, @danielbonattoseco, pelos testes e pela revisão da tradução. Certamente seu trabalho atento será primoroso na sua otimização. Aguardarei a segunda revisão para dar prosseguimento aos ajustes.

**Comment by JimmyMedeiros82** [comment]
@danielbonattoseco obrigado pela revisão atenta e pelos testes de versões! Excelente colaboração!

**Comment by felipelmc** [comment]
Caro @danielbonattoseco, acabo de fazer o commit atualizando a lição conforme as suas sugestões. Mais uma vez, muito obrigado pela revisão. Aproveitei, inclusive, para alterar os casos em que eu havia traduzido "flag" para "sinalizador", conforme a sua indicação em outra ocasião.

**Comment by JimmyMedeiros82** [comment]
@ianaraujo quando puder, por favor, dê uma atenção à revisão da lição. 
No seu ritmo.

**Comment by ianaraujo** [comment]
Complementando a tradução do colega @danielbonattoseco, faço aqui algumas sugestões:

- [x] Linha 39 - Ao longo do texto, em diversos pontos, é usado "Unix shell" assim como na lição original. No entando, acredito que seja melhor se referir como "shell do Unix", embora "Unix shell" deixe o texto mais fluído. Veja aqui como é feita a tradução na Wikipedia em português: https://pt.wikipedia.org/wiki/Shell_do_Unix.
- [x] Linha 41 - Substituir "dados tabulados" por "dados tabulares", nessa linha e em outros momentos do texto. Sinto que a expressão "dados tabulares" é mais usada no universo de tecnologia e dados. [Exemplo](https://cloud.google.com/vertex-ai/docs/datasets/data-types-tabular?hl=pt-br#:~:text=Os%20dados%20tabulares%20s%C3%A3o%20compostos,arquivo%20CSV%20no%20Cloud%20Storage).
- [x] Linha 41 - Remover a vírgula após "coleção de imagens -".
- [x] Linha 43 - Caso decida adotar a sugestão em relação a tradução de "Unix shell", eu começaria este parágrafo da seguinte forma: "O shell do Unix oferece...".
- [x] Linha 43 - Substituir "dados não tabulados" por "dados não-estruturados" ou "dados não-tabulares".
- [x] Linha 45 - Substituir "dependem na" por "dependem da".
- [x] Linha 59 - Substituir "unidade c:" por "unidade C:".
- [x] Linha 76 - Por algum motivo, o hyper link não funcionou aqui: "\[CSV](https://pt.wikipedia.org/wiki/Comma-separated_values)".
- [x] Linha 87 - Substituir "utilizara" por "utilizar a".
- [x] Linha 106 - Colocar "string" em itálico.
- [x] Linha 118 - O hyperlink yambém não funcionou aqui: "\[Introduction to the Bash Command Line](https://programminghistorian.org/en/lessons/intro-to-bash)"
- [x] Linha 144 - Substituir "a presente lição apenas arranha a superfície do que o ambiente" por "a presente lição apenas aborda superficialmente o que o ambiente".

Ademais, gostaria de pontuar que estou usando um sistema Linux e não encontrei nenhum problema ao seguir os passos da lição.

Parabés @felipelmc por mais uma excelente tradução! :clap:

**Comment by JimmyMedeiros82** [comment]
@ianaraujo agradeço por mais uma contribuição! 
Vamos seguir com os ajustes necessários para finalizar a tradução de mais uma lição.

**Comment by felipelmc** [comment]
@ianaraujo muito obrigado pela revisão! Acabei de fazer os ajustes conforme as suas sugestões. A respeito dos hyperlinks que não funcionam, acredito que isso se deva ao fato de eles estarem sendo adicionados dentro de uma div... Essa foi uma modificação que fiz na lição original, que coloca as notas e alertas em itálico (mas a recomendação é que sejam adicionadas a uma div de alert-warning). Não sei se isso implicaria algum problema no momento da publicação. Talvez o @JimmyMedeiros82 possa tirar a dúvida, mas, na pior das hipóteses, posso voltar ao formato de itálico ou simplesmente remover os hyperlinks.

**Comment by JimmyMedeiros82** [comment]
@felipelmc os hiperlinks estão funcionando corretamente, agora. 
Agradeço mais uma vez aos três participantes do processo de tradução e revisão desta lição. Mais uma bela contribuição!

Da minha parte, temos mais uma lição concluída para publicação @DanielAlvesLABDH

**Comment by DanielAlvesLABDH** [comment]
Óptimas notícias! Vou fazer uma verificação final e dar início ao processo de publicação. Obrigado a todos!

**Comment by DanielAlvesLABDH** [comment]
Corrigi o link para a tradução no comentário inicial

**Comment by DanielAlvesLABDH** [comment]
Fiz todas as verificações e corrigi detalhes na tradução. Os meus parabéns ao @felipelmc pela tradução, ao @JimmyMedeiros82 por mais uma lição editada e ao @danielbonattoseco e @ianaraujo por terem ajudado a rever. Ficou excelente e até eu fiquei a saber como usar comandos no shell do Unix! ;-) Vou passar o ficheiro para publicação.

**Comment by DanielAlvesLABDH** [comment]
Caros, a lição já está publicada! Parabéns e obrigado a todos! Estamos quase nas 20...
@JimmyMedeiros82 entre hoje e amanhã o DOI deve ficar activo. Nessa altura pode actualizar o bot do Twitter e fechar o ticket. Obrigado e abraço

**Comment by JimmyMedeiros82** [comment]
Bot do Twitter atualizado. Parabéns a todos pela 19ª lição traduzida e publicada.
