### ISSUE TITLE
Revisão da tradução da lição Instalação de Módulos de Python com pip

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#441]
O Programming Historian em português recebeu a proposta de tradução da lição 'Instalação de Módulos de Python com pip' feita pela Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/instalacao-modulos-python-pip.md

Já a lição original está em: https://programminghistorian.org/en/lessons/installing-python-modules-pip

Agradeço pela contribuição feita pelo @felipelmc .

Eu serei o editor da tradução. A revisão ficará a cargo do @ianaraujo e @danielbonattoseco .

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes da Vânia Rosa . O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by ianaraujo** [comment]
Olá todos! Parabés @felipelmc pela excelente tradução da lição! A maioria dos problemas que encontrei dizem respeito a modificações na lição original, que podem melhorar a qualidade da lição em português, e não na tradução em si. 

No meu computador estou utilizando um sistema Linux e consegui executar todos os códigos sem nenhum problema. Talvez fosse interessante outro revisor tentar executar em algum sistema Windows para verificar.

Deixo aqui algumas sugestões: 

- [x] Linha 35 - Substituir "mac/linux" e "windows" por "Mac/Linux" e "Windows". Embora na lição original esteja em letras minúsculas, acredito que seria mais correto usar letras maiúsculas para se refeir ao nome dos sistemas operacionais;
- [x]  Linha 41 - Substituir "bibliotecas fantásticas de codificação" por "bibliotecas de código fantásticas";
- [x] Linha 41 - Substituir "bibliotecas quais" por "bibliotecas nas quais";
- [x] Linha 41 - Adcionar dois pontos ao final da linha, "por exemplo: ";
- [x] Linha 50 - Substituir "python" por "Python". Em outros momentos da lição o autor também usa python com letra minúscula, mas se referindo ao comando python na linha de comando. Acredito que seja bom padronizar e, sempre que se referir a linguagem Python, utilizar letra maiúscula;
- [x] Linha 50 - Substituir "perl" por "Perl". Afim de melhorar a lição também sugiro adicionar um link (https://www.perl.org/), pois na lição não fica claro o que é script perl;
- [x] Linha 64 - Adicionar dois pontos ao fim da linha, "tente executar o script python dessa forma: ";
- [x]  Linha 70 - Substituir "o script provavelmente falhará" por "O script provavelmente falhará";
- [x] Linha 80 - Usar "em" ao invés de "por";
- [x] Linha 82 - Substituir "navete até o diretório" por "navegue até o diretório";
- [ ] Linha 82 - Não é uma sugestão, mas um comentário acerca da lição original. Acredito que para um usuário iniciante a ideia de onde "armazenou o python" não seja clara. Para mim a lição confunde o que é linguaguem Python, comando python e interpretador da linguagem. Talvez pudesse ser feita uma melhoria nesse trecho, e em alguns outros, para tornar mais simples de entender e menos confuso para o aluno;
- [x] Linha 93 - Adicionar dois pontos ao final da linha, "incluirão o comando pip necessário, por exemplo: ";
- [x] Linha 101 - Adicionar dois pontos ao final da linha, "você deve ter que executar o pip com sudo, como: ";
- [x] Linha 108 - Adicionar dois pontos ao final da linha, "pode ser útil usar a sinalização -m (para ajudar o python a encontrar o módulo pip), como: ";

Reitero que a maioria dos pontos dizem respeito a lição original e alguns ajustes que considero serem benéficos para melhoria da lição em portugês. Novamente, parabés @felipelmc pela excelente tradução!

**Comment by felipelmc** [comment]
Obrigado @ianaraujo pela revisão atenta. Concordo com todos os seus comentários a respeito da lição original. Farei os ajustes assim que a outra revisão for feita.

**Comment by danielbonattoseco** [comment]
Olá a todes! Agradeço a colaboração feita por @felipelmc e a revisão atenta feita por @ianaraujo. As revisões a seguir são uma complementação de pontos de melhoria sobre a lição original e algumas pequenas correções na tradução.

- [x] Linha 35 - Como a lição foi originalmente redigida em 2013, a utilização de Python 2.x ainda era bastante recorrente. Atualmente, mesmo com patches ainda sendo lançados para a versão, a utilização de Python 3.x (que possui o pip pré-instalado em todas as suas releases a partir da versão 3.4) já é predominante, logo creio que possa ser suprimido o trecho "(que ainda são bastante comuns)";
- [x] Linha 52 - Substituir "módulos de Python" por "módulos Python";
- [x] Linha 52 - O recurso externo utilizado para referenciar o termo pip está em inglês. Recomenda-se, quando possível, a utilização de recursos na língua da lição. A [Wikipedia](https://pt.wikipedia.org/wiki/Pip_(gerenciador_de_pacotes)) possui um artigo introdutório em português;
- [x] Linha 54 - As [diretrizes do PH](https://programminghistorian.org/pt/directrizes-autor#alertas-e-avisos) possuem uma formatação específica para notas e avisos, creio que seja o caso; esta nota poderia ser suprimida caso na linha 35 substituíssemos "No caso de Python 2.7.9 ou mais recente" por "No caso de versões mais recentes do Python (a partir das versões 2.7.9 para Python 2 ou 3.4 para Python 3)". Neste caso, mantém-se a nota "(que ainda são bastante comuns)" suprimida no primeiro item desta revisão;
- [x] Linha 64 - As [diretrizes do PH](https://programminghistorian.org/pt/directrizes-autor#exemplos-de-c%C3%B3digo) orientam que nomes de ficheiros (incluindo sua extensão) devem estar entre acentos graves (padrão Markdown - aplicável a "get-pip.py");
- [x] Linha 64 - Acredito que, tratando-se de um tutorial nível 1, podemos colocar uma referência a "interpretador Python" pois pode não ficar claro (recomenda-se a [documentação oficial do Python](https://docs.python.org/pt-br/3/tutorial/interpreter.html);
- [x] Linha 78 - Mesma issue da Linha 64 referente a padrão de markdown para nomes de ficheiros;
- [x] Linha 80 - Mesma issue da Linha 64 referente a padrão de markdown para nomes de ficheiros;
- [x] Linha 82 - Mesma issue da Linha 64 referente a padrão de markdown para nomes de ficheiros
- [x] Linha 82 - O comando "C:\>cd python27" deve, assim como os demais, seguir os padrões de Markdown para trechos de código/comandos através do uso de "``` bash ```;
- [x] Linha 82 - Substituir "usando a linha de comando do windows" por "usando o [Prompt de Comando](https://pt.wikipedia.org/wiki/Cmd.exe) do Windows";
- [x] Linha 82 - Substituir "navete" por "navegue";
- [x] Linha 93 - Substituir "módulos de Python" por "módulos Python";
- [x] Linha 101 - Substituir "deve ter" por "pode ter";
- [x] Linha 108 - Acredito que o termo "flag" não possa ser traduzido, uma vez que se utiliza como termo técnico mesmo em português. Temos [um artigo na Wikipedia](https://pt.wikipedia.org/wiki/Flag) que descreve o mesmo. Talvez utilizamos assim?

Grande abraço!!

**Comment by felipelmc** [comment]
Caros, em primeiro lugar gostaria de agradecer mais uma vez pelas revisões de @danielbonattoseco e @ianaraujo. Acabo de fazer o commit incorporando as sugestões, todas muito bem colocadas. A única que ainda não foi incorporada diz respeito ao comentário do @ianaraujo quanto às confusões da lição original relacionadas ao que é linguagem Python, interpretador da linguagem e comando python. Alguma sugestão para que possam ser melhorados os trechos desse tipo?

**Comment by JimmyMedeiros82** [comment]
Caros, confesso que não tenho sugestão para tentar algum ajuste e atender a recomendação do Ian.
talvez na linha 80 em vez de "navegue até o diretório no qual armazenou o python e o" colocar "navegue até o diretório do seu computador no qual armazenou o python e o". Que acham?

**Comment by JimmyMedeiros82** [comment]
@felipelmc chegamos a uma solução?
Podemos prosseguir para a publicação desta lição?

**Comment by felipelmc** [comment]
@JimmyMedeiros82 na verdade acabamos não chegando a uma decisão final quando à mudança, mas na prática não seria nada substantivo. Estou de acordo com seguirmos para publicação.

**Comment by JimmyMedeiros82** [comment]
ok @felipelmc. Ficamos assim e prosseguimos para publicação. 
Agradeço demais pela dedicação de todos para a tradução desta lição @ianaraujo e @danielbonattoseco ! Vocês contribuíram demais!

@DanielAlvesLABDH temos mais uma lição pronta para seguir para a publicação.

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH finalizamos a revisão desta lição. 
Assim que tivermos o DOI, insiro as mensagens no bot do Twitter. Estou passando por todas as lições que estou como editor para prosseguirmos para novas publicações.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos @JimmyMedeiros82, @felipelmc, @ianaraujo e @danielbonattoseco! Vou fazer uma revisão final e preparar para a publicação.

**Comment by DanielAlvesLABDH** [comment]
Caros, temos mais uma lição publicada! Agradeço ao @felipelmc, @ianaraujo e @danielbonattoseco pelo óptimo trabalho de tradução e revisão. E ao @JimmyMedeiros82 pela edição! Na segunda-feira, quando o endereço DOI já estiver a funcionar, o bot do Twitter pode ser actualizado e podemos fechar o ticket.

**Comment by JimmyMedeiros82** [comment]
O Bot do twitter está atualizado, @DanielAlvesLABDH . 
Agradeço a todos pela contribuição generosa. Caros @felipelmc, @ianaraujo e @danielbonattoseco muito grato pela contribuição!

**Comment by JimmyMedeiros82** [comment]
O Bot do twitter está atualizado, @DanielAlvesLABDH .
Agradeço a todos pela contribuição generosa. Caros @felipelmc, @ianaraujo e @danielbonattoseco muito grato pela contribuição!
