### ISSUE TITLE
Revisão da tradução da lição De HTML para Lista de Palavras (parte 2)

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#443]
O Programming Historian em português recebeu a proposta de tradução da lição 'De HTML para Lista de Palavras (parte 1)' feita pelo Felipe Lamarca. Iniciativa excelente, pois mantêm a continuidade com outra lição!

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/HTML-lista-palavras-2.md

Já a lição original está em: https://programminghistorian.org/en/lessons/from-html-to-list-of-words-2

Agradeço pela contribuição feita pelo @felipelmc .

Eu serei o editor da tradução. A revisão ficará a cargo do @danielbonattoseco e o segundo avaliador ainda será indicado.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
O mesmo aqui... Que tal @bgmartins?

**Comment by JimmyMedeiros82** [comment]
Caro @bgmartins ficaremos contentes com sua dupla colaboração. Faz todo sentido você revisar esta lição, pois é uma continuidade da anterior.

**Comment by danielbonattoseco** [comment]
Olá, pessoal. Dando continuidade à revisão. Algumas notas que realizei na [revisão da parte 1](https://github.com/programminghistorian/ph-submissions/issues/442) (como padrões de markdown para nomes de arquivos e palavras restritas, por exemplo) não serão repetidas nessa revisão, mas, se tiverem sido ajustadas, precisarão ser igualmente ajustadas nessa segunda parte.

- [x] Linha 36 - Substituir "entre a primeira `<p>` e a última `<br/>` tags" por "entre a primeira tag `<p>` e a última tag `<br/>`";
- [x] Linha 40 - Substituir "esquerdo" por "direito";
- [x] Linha 57 - Substituir "Nós demos um nome a *char*" por "Nós demos à variável o nome *char*";
- [x] Linha 66 - Substituir "dependendo do teste" por "de acordo com este teste";
- [x] Linha 66 - Inserir "o" antes de "Python";
- [x] Linha 66 et.al. - As [diretrizes do PH](https://programminghistorian.org/pt/directrizes-autor#exemplos-de-c%C3%B3digo) orientam que palavras restritas de programação estejam entre acentos graves de acordo com o padrão Markdown (aplicável a "if", "elif", "for", "True", "False", "continue" e "return" durante toda esta lição - apenas para os casos em que os termos ocorram fora dos blocos de código);
- [x] Linha 68 - Inserir "o" antes de "Python";
- [x] Linha 102 - Substituir "esquerdo" por "direito";
- [x] Linha 105 - Substituir "loop" por "`for` loop";
- [x] Linha 105 - Aplicar o padrão Markdown itálico para "statements";
- [x] Linha 147 - Em outras partes da lição o termo "statement" não foi traduzido, aqui foi traduzido para "instrução". Importante definir uma consistência na tradução/não tradução do termo durante toda a lição;
- [x] Linha 171 - Não é recomendada a tradução do termo técnico "file handle"; ao invés disso, mantenha o termo original e adicione [este recurso da Wikipedia sobre o recurso](https://pt.wikipedia.org/wiki/Handle_(inform%C3%A1tica));
- [x] Linha 179 - Corrigir "portencialmente" por "potencialmente";
- [x] Linha 179 - A frase "Save the file as string-to-list.py and execute it.", presente na lição original, foi omitida na tradução; inserir "Salve o ficheiro como `string-para-lista.py` e execute-o." após "duas formas de atingir esse objetivo.";
- [x] Linha 179 - O [mini-glossário](https://docs.google.com/document/d/1o2rw7Rf_bOZkhHzAw18PfQUzBCCGbbq7dKsAjei8tTo/edit) orienta a tradução de "print" para "exibir". Substituir "impressas" por "exibidas";
- [x] Linha 199 - Acho importante adicionar o [recurso da Wikipedia](https://pt.wikipedia.org/wiki/Retorno_de_carro) ao termo "retornos de carro" (nunca sequer tinha ouvido falar no termo);
- [x] Linha 199 - Aplicar o padrão Markdown itálico para "Run Python";

Mais uma vez parabéns pela excelente tradução, @felipelmc !!! Grande abraço!

**Comment by felipelmc** [comment]
@danielbonattoseco, muito obrigado pela revisão. Fiz o commit implementando todas as suas sugestões, inclusive aquelas que dependiam de alteração na parte 1. Não foram traduzidos os nomes dos arquivos, já que a melhor ação nesse caso ainda está em discussão. Grande abraço!

**Comment by JimmyMedeiros82** [comment]
Agradeço ao @danielbonattoseco pela revisão atenta!
Peço ao @felipelmc aguardar a contribuição do @bgmartins para finalizar os ajustes na lição.

**Comment by DanielAlvesLABDH** [comment]
E aqui também @bgmartins... quando puderes. Obrigado

**Comment by JimmyMedeiros82** [comment]
Olá @bgmartins consegue colaborar conosco? Se for o caso, faço uma substituição e, futuramente, você coopera em outra oportunidade. Que acha?

**Comment by JimmyMedeiros82** [comment]
@dianarebelorodriguez a segunda lição a ser revisada é esta. É uma sequência da anterior. 
Se puder realizar ambas as revisões ficaremos muito gratos

**Comment by dianarebelorodriguez** [comment]
Bom dia @JimmyMedeiros82 e obrigada pela confiança! Até amanhã estarei enviando meus comentários e sugestões, peço desculpas pela demora em responder aqui. Abraços!

**Comment by dianarebelorodriguez** [comment]
Boa noite, pessoal! 

@felipelmc seguem meus comentários e sugestões. Por favor, fique à vontade para desconsiderar aqueles que não fizerem sentido, uma vez que não tenho muito contato com o Phyton.

linha 40: "estamos deixando a tag; deve-se ignorar este caractere" trocar o ";" por "e", para ficar como na linha de cima

linha 57: "O que você deseja usar nesse caso é chamado `for` *loop*." acho que eu colocaria "o que desejamos usar", soa melhor

linha 57: "A versão abaixo solicita que o interpretador execute algo a cada caractere na string" acho que a tradução mais literal seria "faça algo". Se for para usar o "executar", acho que seria melhor "execute um código" para a frase não ficar meio solta

linha 66: "O que você deseja usar" é o mesmo caso da linha 57, me parece estranho, eu colocaria na primeira pessoa do plural ou mudaria o verbo "desejar"

linha 66: "identação é importante em Python. Se o código está identado" duas coisas: 1) acho que seria indentação/indentado, certo?; 2) eu estranhei a palavra a primeira vez que vi, não sei se é um termo que apareceu nas outras lições, mas talvez eu colocasse uma nota de tradução ou um parênteses com um sinônimo, como (recuo)

linha 68: "para definir uma coisa igual a outra" eu colocaria "para definir que uma coisa é igual a outra"

linha 105: "ou parte do conteúdo, e finalmente irá inserir" --> "ou parte do conteúdo, e, finalmente irá inserir" (faltou uma vírgula)

linha 109: "está mantendo a identação como foi mostrada" duas coisas: 1) acho que faz mais sentido "estará" ou "você estará"; 2) confirmar se é "indentação"

linha 111: "Sua função pode parecer um pouco diferente e, contanto que funcione" --> "Sua função pode parecer um pouco diferente, mas, contanto que funcione" (trocar a conjunção)

linha 156: "usando código adicional" talvez fique melhor "usando um código adicional", só porque estranhei quando li, mas é bem superficial, não se preocupa

linha 164: "você desejará obter esse texto em um formato que seja fácil de processar. Até agora, quando precisou armazenar informações em programas Python, geralmente usou strings" duas coisas: 1) acho que seria melhor ter um "provavelmente" antes do "desejará"; 2) eu colocaria outro "você" depois do "quando" para ficar mais natural a frase ("quando você precisou... geralmente usou...")

linha 179: "Digite ou copie o programa a seguir" eu não entendo de Phyton, mas aqui não faria mais sentido usar "código" no lugar de "programa"?

linha 199: "é um pouco simplificado" talvez seja melhor "é uma certa simplificação"

Qualquer questão, sigo à disposição! @JimmyMedeiros82 agradeço, mais uma vez, o convite e a paciência!

**Comment by JimmyMedeiros82** [comment]
Obrigado @dianarebelorodriguez 
Mais uma bela colaboração!

**Comment by felipelmc** [comment]
@dianarebelorodriguez Muito obrigado pelas sugestões! Acabei de fazer o commit das modificações. Agradeço também ao @danielbonattoseco, que fez a primeira revisão. @JimmyMedeiros82, caso esteja tudo de acordo, podemos seguir para o próximo passo com esta lição também.

Um abraço!

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH temos uma nova lição pronta para seguir para publicação. 
Agradeço a todos pela colaboração. Trabalho incrível!

**Comment by DanielAlvesLABDH** [comment]
Actualizei o nome do ficheiro md e o link para o mesmo no primeiro comentário

**Comment by DanielAlvesLABDH** [comment]
Caros @JimmyMedeiros82, @felipelmc, @dianarebelorodriguez e @danielbonattoseco esta lição já está pronta a ser publicada. Agradeço uma vez mais todo o vosso trabalho. Abraço

**Comment by DanielAlvesLABDH** [comment]
Caros/as a lição está publicada. @JimmyMedeiros82 podes usar o https://doi.org/10.46430/phpt0028 para actualizar o bot do Twitter e encerrar o ticket. Obrigado!

**Comment by JimmyMedeiros82** [comment]
Atualização feita @DanielAlvesLABDH
