### ISSUE TITLE
Review Ticket for 'De HTML a lista de palabras (parte 2)' - Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#45]
The Programming Historian has received the following translation on 'De HTML a lista de palabras (parte 2)' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/de-html-a-lista-de-palabras-2

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by mariajoafana** [comment]
Línea 27: la palabra "añade" está repetida
Línea 39: corregir "cadema"
Línea 43: mayúscula después de punto en  "le dimos"
                "porque no tiene" está repetido dos veces
                 Sugiero cambiar "si nos hubiéramos sentido tentados" por "si hubiéramos querido".
Línea 52: renglón 4.  "angular" en vez de "angula"
Línea 61, (,) coma después de "if"
Línea 70: (,) coma después de "primera"
Línea 90: penúltimo renglón, eliminar espacio de más entre "si  no"
Línea 126: penúltimo renglón, eliminar espacio de más antes de  "Si..."
Línea 182: renglón 3, separar "cosasreferirse"

**Comment by arojascastro** [comment]
- L 43: en sucesión. le dimos --> something is wrong here
- L 43: porque no tiene porque no tiene --> repetido
- L 53: angula --> angular
- L 61: if --> *if* (cursiva)
- L 86: caracter --> carácter
- L 87: caracter --> carácter
- L 90: if / elif  --> *if / elif* (cursiva)
- L 94: Toma en cuenta  --> Ten en cuenta (?)
- L 124: caracter --> carácter
- L 141: Toma en cuenta --> something different (por ejemplo, Recuerda o no olvides o Ten presente)
- L 169: que tal mundo --> qué tal mundo
- L 182: caroo --> carro
- L 182: cosasreferir --> cosas referir
- L 182: que tal mundo! --> qué tal mundo!

**Comment by acrymble** [comment]
Please make sure only the editor closes a review ticket. No one told me this was ready for my check so I had left it open. If anyone other than the editor closes it then we have no control over quality checking. As it stands it didn't have the reviewer's names added to it.

**Comment by acrymble** [comment]
I've added the translation reviewers to this. It's now published.
