### ISSUE TITLE
Proposition de traduction en français: Du html à une liste de mots (part 2)

### ISSUE THREAD

**Issue by datalogism** [programminghistorian/ph-submissions#455]
Je propose la traduction de la leçon "[From html to list of words 2](https://programminghistorian.org/en/lessons/from-html-to-list-of-words-2)", rédigée par  @acrymble et William J. Turkel, sous le titre "Du html à une liste de mots  (partie 2)".

La traduction est complète et disponible ici https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/inactives/du-html-a-une-liste-de-mots-2.md;

Le processus de révision débutera dès qu'un(e) membre de l'équipe sera disponible pour se charger de la rédaction.

**Comment by anisa-hawes** [comment]
Hello all, 

Please note that this lesson's .md file has been moved to a new location within our Submissions Repository. It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/inactives

A consequence is that this lesson's preview link has changed. It is now: [http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/du-html-a-une-liste-de-mots-2](http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/du-html-a-une-liste-de-mots-2)

Please let me know if you encounter any difficulties or have any questions.

Very best,
Anisa

**Comment by anisa-hawes** [comment]
Dear @spapastamkou. This Issue might be another to close until it is actively being worked on?

**Comment by spapastamkou** [comment]
Je ferme ce ticket le temps que nous aurons trouvé un membre de l'équipe qui sera en mesure d'effectuer le suivi éditorial. cc @marie-flesch
