### ISSUE TITLE
Proposition de traduction: Reutilisation de code et modularite

### ISSUE THREAD

**Issue by datalogism** [programminghistorian/ph-submissions#456]
Je propose la traduction de la leçon "[Code Reuse and Modularity in Python](https://programminghistorian.org/en/lessons/code-reuse-and-modularity)", rédigée par A. Crymble et William J. Turkel, sous le titre "Réutilisation de code et modularité".

La traduction est complète et disponible ici https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/reutilisation-de-code-et-modularite.md;

Le processus de révision débutera dès qu'un(e) membre de l'équipe sera disponible pour se charger de la rédaction.

**Comment by anisa-hawes** [comment]
Hello all, 

Please note that this lesson's .md file has been moved to a new location within our Submissions Repository. It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/inactives

A consequence is that this lesson's preview link has changed. It is now: [http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/reutilisation-de-code-et-modularite](http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/inactives/reutilisation-de-code-et-modularite)

Please let me know if you encounter any difficulties or have any questions.

Very best,
Anisa

**Comment by spapastamkou** [comment]
C'est @marie-flesch qui prend en charge le suivi éditorial de cette traduction dont elle organisera la relecture à sa convenance.

La relecture peut se faire soit sur ce même ticket soit en fermant celui-ci et en ouvrant un nouveau (qui indexe à l'occasion le ticket de la proposition dans le commentaire initial), cf. cet exemple: https://github.com/programminghistorian/ph-submissions/issues/526) La 2e solution est peut-être plus propre (surtout que le lien de la prévisualisation va encore changer losque le fichier de la traduction sera dans le répertoire supérieur), mais c'est au choix de la rédactrice en charge.

**Comment by spapastamkou** [comment]
J'ai replacé le fichier dans le répertoire des traductions en cours (actives), puisque le processus de la relecture est sur le point de se lancer. La prévisualisation de la leçon est maintenant disponible ici: https://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/reutilisation-de-code-et-modularite

**Comment by marie-flesch** [comment]
Je ferme ce ticket car la relecture est en cours #539
