### ISSUE TITLE
Review of Linear and Logistic Regression Lesson for Programming Historian

### ISSUE THREAD

**Issue by rcmapp** [programminghistorian/ph-submissions#458]
Review of Linear and Logistic Regression Lesson for Programming Historian
By Rennie Mapp

INITIAL COMMENTS
I’m genuinely impressed by the coherence and extent of this lesson: it moves skillfully from concepts to descriptions of discrete steps to math to code.  It adheres to the PH model very well as far as I can tell.  Although I don’t perform text analytics regularly myself, I’m familiar with the concepts of text analytics and the purposes for which humanists use them. Thus it’s important to say that I’m offering the following comments from the point of view of someone who has organized and attended a lot of technical workshops for humanists, rather than as someone who regularly performs this kind of analysis myself.  I will follow the PH Reviewer Guidelines in my commentary, but I won’t have tested the lesson's computational methods.

AUDIENCE
1.  "Does the author address a consistent model reader throughout the lesson?"
- I don’t like to start with my strongest criticism because this lesson has so many strengths, but I think this is the area where the lesson needs the most work. Here are the stated goals: “to provide a high-level overview of linear and logistic regression, to describe how regression fits into data analysis research design, and to walk through running both algorithms in Python using the scikit-learn library.” By “high-level” I understand you to mean that you are providing a bird’s-eye overview that would be helpful for someone trying to understand the overarching principles as well as the specific steps (which seem masterfully captured to me).  There is something of a mismatch between the central goals of the lesson and the way that the lesson’s framing commentary goes on to guide the user. For example:

- “high-level overview of linear and logistic regression”  In paragraph 26, your high-level overview doesn’t quite deliver: you say “Arguably, what’s most important when learning about linear and logistic regression is obtaining high level intuition for what’s happening when you fit a model and predict from it, and that’s what we’ll focus on here.”  I would like to see more conclusions drawn around this idea.

2. Are some concepts or steps over-explained while other are under-explained?
- I found the math and statistics explanations to be excellent. This is no small accomplishment!  I really haven’t seen a more comprehensible or succinct explanation. 
- “data analysis research design”:  When you stated this as a goal I got quite excited because it’s a really important concept and I’d like to learn more. After many conversations with would-be computational humanists, I’ve learned that the biggest anxiety for those who are beginning to delve into computational methods of analysis is whether they will be worth the trouble. True, your CA article offers an example of a research outcome, but within this lesson I don’t think you deliver fully on this broad promise. 
3. Does the audience seem to match at least vaguely with other Programming Historian lessons? How is it new?
- This lesson is definitely well past the skills of a beginner, and yet it’s not intimidating or less manageable than other lessons.  The use cases are clear and easy to understand. I think it’s just right for PH.

GETTING READY
1. What software / programming languages are required?
- All good except you don’t mention the pandas library until paragraph 39–you should probably bring up earlier.
2. What prerequisite skills are needed?
- Here’s a confusing statement from the “Preparation” section (no paragraph number) in terms of both audience and getting ready: “To understand the steps used to produce the lesson dataset, it would be helpful to have some familiarity with concepts such as how text files are typically normalized, tokenized, and represented in vector space. However, these details are not needed to complete the lesson.” I don’t see how someone without an understanding of the concepts and principles of data preparation could get through this lesson, honestly.  Skipping that discussion is a good decision in a more advanced lesson, but you should be frank about it, and perhaps send readers to some good descriptions of the ideas behind that vital process.
3. What familiarity or experience is needed?
- see number 2
4. What data are needed? Is the dataset readily available?
- The dataset is well described but I can’t see any reference to a zipped set of text files, although the other PH lessons you cite (“Analyzing Documents with TF-IDF” and “Understanding and Using Common Similarity Measures for Text Analysis”) do offer zip files. I referred to your CA article and the github repository mentioned in the footnotes to that article, but I couldn’t see it.  This may be because of my own lack of technical proficiency, but I think having the dataset provided in an analogous way to the two other PH lessons would make sense. 

SKIMMABILITY
1. Are there clearly defined learning objectives or sets of skills to be learned listed near the top of the lesson?
- Yes.  I’ve already covered this under audience.
2. Are there useful secondary skills to be gained / practiced from the lesson?’
- I believe so
3. Do screenshots and other diagrams illustrate crucial steps / points of the lesson?’
- Yes, these seem very meticulous.
4. Do sections and section headings provide clear signage to the reader?
- Yes, very well done.

PAYOFF
1.  the tutorial suggest why the explained tools or techniques are useful in a general way?
- Yes—I really like the way this lesson builds on the CA article.  This helps a lot.
2. Does the tutorial suggest how a reader could apply the concepts (if not concrete steps) of the lesson to their own work?
- This ties in with the earlier issue of data research design.  I think a paragraph that offers some more typical research applications could be helpful.

WORKFLOW
1. Should a long lesson be divided into smaller lessons?
- I’d like to see this divided into a paired set of lessons, with the resulting opportunity to offer more contextualization about data research design.
2. Are there logical stopping points throughout the lesson
- Yes—it’s very logically structured.
3. If datasets are required, are they available to download at various points throughout the lesson (or different versions of them as the tutorial may require)?
- See “Getting Ready”  number 4

SUSTAINABILITY
1. Are all software versions and dependencies listed in the submission? Are these assets the most recent versions? 2. If the lesson uses older software versions, does the author note why?
- Not qualified to assess
3. If you have expertise in the specific methodology or tool(s) for the lesson, is the methodology generally up-to-date?
- Not qualified to assess
4. What are the data sources for the submission? Are they included in a way that does not heavily on third-party hosting?
- See issues with missing zip file, above
4. What kinds of other external links does the submission use? Are these current or are there other, more recent or appropriate, resources that could be linked to?
- Addressed above in the dataset section

INTEGRATING WITH THE PROGRAMMING HISTORIAN
1.  the lesson build upon an existing lesson and explain how?
- It does build on other lessons but without much explanation
2. Does the lesson tie into existing lessons and have appropriate links?
- Same as number 1

**Comment by anisa-hawes** [comment]
Hello @rcmapp. Please could you re-post your review as a comment within this Issue?: https://github.com/programminghistorian/ph-submissions/issues/436 

That way, the author + editor can read all reviewers' comments within the same thread, and a conversation can develop from there.

Thank you!

**Comment by drjwbaker** [comment]
Thanks @rcmapp! I've done this now so this is nothing further for you to do. Thanks so much for taking the time to review this article.

**Comment by rcmapp** [comment]
Sorry--I was on vacation last week and I'm just seeing this now.

*Rennie Mapp, PhD, MSMITProject manager for *



*strategic DH initiativesOffice of the VP for IT University of
Virginia(717)713-1204*

***@***.*** ***@***.***>*
