### ISSUE TITLE
Review Ticket for 'Normalizar datos de texto con Python' - Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#46]
The Programming Historian has received the following translation on 'Normalizar datos de texto con Python' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/normalizar-datos

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by mariajoafana** [comment]
Línea 58: sugiero cambiar el orden en la tercera oración para claridad así: "Queremos saber con qué frecuencia aparece cada palabra con significado en la transcripción del juicio."
Línea 89: Última oración corregir "ahcer"
Línea 91: última oracion, corregir "slución"
Línea 95: sugiero cambiar el orden de la tercera frase así: "Si dejamos la puntuación, esta echa a perder nuestras cuentas de frecuencia."
Línea 108: Revisar para claridad y puntuación: "se podría utilizar una expresión regular para ver si coincide con la subcadena **cualquer** letra entre la "a" y la "z"." Es un poco confusa y la larga esta oración. Separa "ocualquier"
Línea 110: coma (,) después de "Para acelerar el procesamiento"

**Comment by vgayolrs** [comment]
Thank you very much @mariajoafana !
Please, can you check one more time the sentence on line 108? If I am in the logic of the lessons (that is, I have read them in series) and I am involved learning Python, what code does and does not, in effect, the sentence can become little complex but not confused. Anyway I changed the order, so I would appreciate your opinion. Thank you in advance.

**Comment by mariajoafana** [comment]
Yes looks good! Only, correct "cualquer"

**Comment by vgayolrs** [comment]
oops! Done @mariajoafana . Thanks!

**Comment by arojascastro** [comment]
- L 30: Si no tienes estos archivos de la lección previa, puedes descargar un zip --> please add period at the end of the sentence.
- L 56: tokens --> *tokens* (add italics)
- L 87: hace muy fácil hacer mucho --> repetitive, please rewrite this sentence and avoid using "hacer" twice. Why not "facilita"?
- L 88: “Old Bailey” --> italics instead of " (?) I think in previous lessons you used italics.
- L 88:  trata de pensar en todo lo que podría ir mal y tratalo de antemano --> trátalo (otherwise is Argentinian ;)
- L 91: reefinamiento --> refinamiento
- L 108: if / else  --> *if / else* (italics? it needs to be highlighted somehow)
- L 141: asi que --> así que

**Comment by vgayolrs** [comment]
Thank you @arojascastro 
Everything done @acrymble

**Comment by acrymble** [comment]
translation reviewers added. Now published
