### ISSUE TITLE
Revisão da tradução da lição Normalização de Dados Textuais com Python

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#460]
O Programming Historian em português recebeu a proposta de tradução da lição 'Normalização de Dados Textuais com Python' feita pelo Felipe Lamarca. 

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/normalizacao-dados-textuais-python.md

Já a lição original está em: https://programminghistorian.org/en/lessons/normalizing-data

Agradeço ao @felipelmc pela nova contribuição.
Eu serei o editor da tradução. E vou marcar os revisores desta lição. 

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by JimmyMedeiros82** [comment]
A @GabrielaKucuruza será uma das revisoras desta lição. 
Agradeço por mais esta contribuição.

**Comment by JimmyMedeiros82** [comment]
Olá @Msaguedes poderia colaborar conosco sendo revisora desta lição traduzida?

**Comment by JimmyMedeiros82** [comment]
@josircg poderia nos ajudar com a revisão desta lição? Ou indicar alguém para colaborar com esta revisão?

**Comment by JimmyMedeiros82** [comment]
O segundo revisor será o @andresalvolns
Agradeço aos dois pela colaboração nesta lição!

**Comment by andresalvolns** [comment]
Boa tarde! Ótima tradução do @felipelmc. Aqui vão duas pequenas alterações que eu faria:

- [x] Linha 94: Substituir `“face a exceções”` por `“face de exceções”`.

- [x] Linha 111: Substituir `"corresponde à letra"` por `“representa a letra”` e `“correspondia a uma letra entre”` por `“se assemelha a uma letra entre”` para evitar a repetição de palavras. 

Qualquer comentário é só me contatar!

**Comment by felipelmc** [comment]
Desculpe a demora para responder, @andresalvolns. Muito obrigado pelos comentários. Aguardo a segunda revisão para ajustar a lição.

Abraços!

**Comment by GabrielaKucuruza** [comment]
Bom dia, @felipelmc! Primeiro de tudo, parabéns pela tradução. Seguem algumas sugestões de alterações:

- linha 58 - "Começaremos calculando as frequência" no lugar de  "Começaremos agora calculando as frequência"
- linha 92 - Em "Neste ponto, podemos examinar uma série de outras entradas do Old Bailey Online e uma ampla gama de outras fontes em potencial para **ter** certeza de que não há outros caracteres especiais que causarão problema posteriormente.", substituir "ter" por "termos" pela concordância verbal 
- linha 94 - Em "Você começa com um problema e parte de uma solução, e então refina a sua solução até que você tenha um resultado que funcione melhor.", acho que "depois continua refinando a sua solução" se alinha melhor com o sentido do texto original. 

Qualquer coisa, fico a disposição! Abraços!

**Comment by felipelmc** [comment]
Caros @GabrielaKucuruza @andresalvolns, agradeço imensamente as sugestões e informo que as alterações já foram realizadas. @JimmyMedeiros82, se estiver tudo de acordo, acredito que possamos passar para o próximo passo.

Grande abraço!

**Comment by JimmyMedeiros82** [comment]
Maravilha, @felipelmc 
Agradeço a colaboração feita pelo @andresalvolns e @GabrielaKucuruza 

@DanielAlvesLABDH temos uma nova lição apta para publicação.

**Comment by DanielAlvesLABDH** [comment]
Caros @JimmyMedeiros82, @felipelmc, @andresalvolns e @GabrielaKucuruza esta lição já está pronta a ser publicada. Muito obrigado pelo vosso trabalho. Abraço

**Comment by DanielAlvesLABDH** [comment]
Caros/as a lição está publicada. @JimmyMedeiros82 podes usar o https://doi.org/10.46430/phpt0029 para actualizar o bot do Twitter e encerrar o ticket. Obrigado! Ainda hoje darei início à publicação de outras lições...

**Comment by JimmyMedeiros82** [comment]
Atualização feita @DanielAlvesLABDH
