### ISSUE TITLE
Revisão da tradução da lição Contagem de Frequências de Palavras com Python

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#461]
O Programming Historian em português recebeu a proposta de tradução da lição 'Contagem de Frequências de Palavras com Python' feita pelo Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/contar-frequencias-palavras-python.md

Já a lição original está em: https://programminghistorian.org/en/lessons/counting-frequencies

Agradeço ao @felipelmc pela nova contribuição.
Eu serei o editor da tradução. E vou marcar os revisores desta lição, em seguida.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by JimmyMedeiros82** [comment]
Olá @joanacvp você poderia colaborar com a revisão desta tradução? Ou indicar alguém para nos ajudar?

**Comment by JimmyMedeiros82** [comment]
A @anacarolerthal será revisora da lição traduzida. 
Ana Carolina Erthal, agradeço pela colaboração. Estamos contentes pela parceria no projeto.

**Comment by anacarolerthal** [comment]
Fico feliz em participar! Obrigada pela oportunidade.

**Comment by joanacvp** [comment]
Olá a todos. Terei todo o gosto em fazer a revisão :)

**Comment by anacarolerthal** [comment]
A tradução ficou excelente! Seguem as minhas considerações e sugestões de alteração:

- [x] Linha 46: substituir `Você já viu que é mais fácil de processar` por `Você já viu que é fácil processar`. Não há comparação;
- [x] Linha 46: substituir `Lembre-se que` por `Lembre-se de que`;
- [x] Linha 107: modificar `listar as palavras na ordem do mais frequente para o menos frequente.` para `listar as palavras na ordem da mais frequente para a menos frequente.`;
- [x] Linha 107: `esses problemas` ao invés de `esse problema` (no texto original fala-se de "both problems"; 
- [x] Linha 153: a passagem "quando você `print(d['olá'])`" faz mais sentido em inglês. Sugiro "quando você realiza um `print(d['olá'])`";
- [x] Linha 222: para evitar a repetição da palavra `outros` sugiro trocar `diferenciar esse texto de outros textos sobre outros assuntos` por `diferenciar esse texto de outros textos sobre assuntos distintos`;
- [x] Linha 222: no texto original há uma menção ao fato de que as palavras funcionais são chamadas de `stop words`. Há uma tradução: "palavras vazias". A menção pode ser válida, então sugiro adicionar a frase `Palavras que são ignoradas dessa forma são conhecidas como _stopwords_.`;
- [x] Linha 287: trocar `Juntando tudo` por `Juntando Tudo`;
- [x] Como um comentário mais geral, talvez seja válido padronizar o idioma das strings utilizadas nos exemplos. Na parte Dicionários de Python as strings estão em português, mas no resto da lição foram mantidas em inglês;

Estou à disposição para qualquer questão!

**Comment by JimmyMedeiros82** [comment]
@anacarolerthal muito obrigado pela atenta revisão! 
Você topa revisar outra lição?

**Comment by anacarolerthal** [comment]
Com certeza, seria um prazer!

**Comment by joanacvp** [comment]
Boa tarde a todos. Mais uma vez, um óptimo trabalho @felipelmc! Seguem os meus comentários:

- [x] Linha 26 – Onde está “Esta lição ensinará a maneira fácil do Python de contar essas frequências” sugiro  “Esta lição ensinará uma maneira fácil de contar essas frequências com Python”
- [x] Linha 37 – retirar o “você” em “para que você possa”. Retirar o “isso” em “mas isso requer”.
- [x] Linha 43 – retirar o “você” em “você pode fazer”.
- [x] Linha 47 – retirar o “você” em “Você já viu”.
- [x] Linha 67 – onde está “começamos com uma string e a separamos em uma lista, como fizemos anteriormente” sugiro “começamos com uma string e separamo-la em uma lista, como fizemos anteriormente”
- [x] Linha 69 – retirar o “você” em “Você deve obter”.
- [x] Linha 87 – substituir o “econômica” por “económica”.
- [x] Linha 106 – retirar o “você” em “que você entenda”.
- [x] Linha 112 – retirar o “você” em “significa que você pode acessar” e em “você pode utilizar”.
- [x] Linha 138 – retirar o “você” em “significa que você não” e em “Você pode, por outro”
- [x] Linha 154 – onde está “tente pensar nele” sugiro “tente pensar neles”. Retirar o “você” em “Caso você não saiba”. Retirar o “se” em “se difere de”. Retirar o “você” de “você pode buscar” e de “quando você”.
- [x] Linha 156 – retirar o “você” de “observe que você usa”.
- [x] Linha 183 – onde está “Estude o programa e sua saída” sugiro “Estudo o programa e o seu resultado”.
- [x] Linha 223 – poderia ser interessante referir, mesmo que fixe em nota de rodapé, palavras similares para o caso português como: e, de, da, do, um, uma, ...
- [x] Linha 223 – retirar o “você” em “que você está construindo”.
- [x] Linha 313 – substituir “deve se parecer com isso” por “deve-se parecer com isto”
- [x] Concordo com a Ana na referência à utilização de strings em português. Creio que deveria ficar uniforme, mas compreendo que nas outras lições, em alguns casos, se optou pela versão inglesa. Talvez uniformizar tudo depois de estarem traduzidas todas as lições de Python @JimmyMedeiros82 e @DanielAlvesLABDH ?

Qualquer dúvida estou disponível!

**Comment by DanielAlvesLABDH** [comment]
Obrigado @joanacvp . Sim, acho que é uma tarefa de revisão geral que temos de fazer depois de passada esta fase de muitas traduções...

**Comment by JimmyMedeiros82** [comment]
Tem razão, @joanacvp 
Ao final, seria bom realizarmos um ajuste nas lições disponíveis. 
No momento, seguimos com a finalização desta tradução. Agradeço para ambas as revisões atentas.

**Comment by felipelmc** [comment]
Caros, acabo de fazer a revisão da lição. Aproveito a oportunidade para agradecer às revisoras, @anacarolerthal e @joanacvp, pelo trabalho atento. Conforme as sugestões, voltei à versão inglesa dos códigos onde havia traduzido para o português e adicionei, além disso, uma nota de rodapé com algumas _stopwords_ em português. Mais uma vez, muito obrigado. @JimmyMedeiros82 e @DanielAlvesLABDH, caso concordem com a versão atualizada, acredito que temos mais uma lição pronta para a publicação.

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH temos mais uma tradução bem feita!
Agradeço a colaboração de todos para o sucesso deste processo @felipelmc @anacarolerthal @joanacvp

**Comment by DanielAlvesLABDH** [comment]
Olá a todos/as. Obrigado ao @felipelmc por mais esta tradução. Tenho apenas um pedido a fazer antes de iniciar a revisão final e publicação. Acho que a tradução ficou óptima, mas para manter uma certa coerência com as traduções anteriores (vejam por exemplo https://programminghistorian.org/pt/licoes/manipular-strings-python) acho que parte do código deveria também ser traduzido para português. Obviamente apenas as frases e palavras usadas como exemplo para os exercícios. E apenas até à linha 158. Daí para a frente, tendo em conta que vamos continuar a usar o exemplo da página Old Bailey não podemos alterar.

**Comment by JimmyMedeiros82** [comment]
@felipelmc você poderia fazer este ajuste final? ele é bom para uniformizar as lições.

**Comment by felipelmc** [comment]
Caros @DanielAlvesLABDH @JimmyMedeiros82, acabo de implementar as sugestões. Os textos dos exemplos até a linha 158 estão todos traduzidos, com exceção dos nomes das variáveis, tal como foi feito na lição https://programminghistorian.org/pt/licoes/manipular-strings-python. Obrigado pela revisão!

**Comment by JimmyMedeiros82** [comment]
Excelente @felipelmc 
Obrigado pela celeridade nos ajustes.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @felipelmc! Obrigado a todos/as uma vez mais. Fiz uma revisão geral, mudei o nome do ficheiro (actualizei o respectivo link no comentário inicial do ticket) e acrescentei o DOI. Vou iniciar a publicação.

**Comment by DanielAlvesLABDH** [comment]
Olá a todos/as, temos mais uma lição publicada! E vão 23! Excelente trabalho @felipelmc @anacarolerthal @joanacvp e @JimmyMedeiros82. Jimmy, o DOI para o bot do Twitter é https://doi.org/10.46430/phpt0023. Abraço

**Comment by JimmyMedeiros82** [comment]
Ótima, notícia, @DanielAlvesLABDH 
Reforço o agradecimento a todos que participaram deste processo @felipelmc @anacarolerthal @joanacvp
