### ISSUE TITLE
Revisão da tradução da lição Criação e Visualização de Ficheiros HTML com Python

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#462]
O Programming Historian em português recebeu a proposta de tradução da lição 'Criação e Visualização de Ficheiros HTML com Python' feita pelo Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/criacao-visualizacao-ficheiros-html-python.md

Já a lição original está em: https://programminghistorian.org/en/lessons/creating-and-viewing-html-files-with-python

Agradeço ao @felipelmc pela nova contribuição.
Eu serei o editor da tradução. E vou marcar os revisores desta lição.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Obrigado @JimmyMedeiros82 e @felipelmc por mais uma tradução. Fiz ajustes no nome do ficheiro md e no ficheiro de imagem, bem como na sua localização e corrigi os links respectivos acima.

**Comment by JimmyMedeiros82** [comment]
Olá @josircg você topa colaborar como revisor desta lição?

**Comment by JimmyMedeiros82** [comment]
Olá @caiocmello você topa colaborar como revisor desta lição?

**Comment by caiocmello** [comment]
Ola Jimmy,

Obrigado por enviar o convite. Infelizmente, estou muito ocupado no momento
finalizando minha tese de doutorado. Gostaria muito de continuar
contribuindo em breve, contudo.

Atenciosamente,
Caio

Em ter., 22 de mar. de 2022 às 16:21, Jimmy Medeiros <
***@***.***> escreveu:

**Comment by JimmyMedeiros82** [comment]
Olá @caiocmello compreendo! Desejo sucesso na tese de doutorado!

**Comment by JimmyMedeiros82** [comment]
@ianaraujo você topa colaborar com a revisão desta lição?

**Comment by JimmyMedeiros82** [comment]
@GabrielaKucuruza você topa colaborar com a revisão desta outra lição?

**Comment by GabrielaKucuruza** [comment]
Oii @JimmyMedeiros82 topo sim!

**Comment by JimmyMedeiros82** [comment]
Oi @anacarolerthal você topa colaborar com esta revisão?
É bem parecida com outra que você fez a leitura crítica.

**Comment by anacarolerthal** [comment]
Olá @JimmyMedeiros82! Topo sim, será um prazer.

**Comment by anacarolerthal** [comment]
Tradução excelente, @felipelmc ! :)
A seguir as minhas considerações e sugestões:

- [x] Talvez tenha sido proposital, mas a última frase da seção `Objetivos da Lição` não consta na tradução.
- [x] Linha 46: substituir `abrí-lo` por `abri-lo`.
- [x] Linha 70: acredito que `Salve o programa acima` seja mais claro, por usar o termo mais comum para salvar documentos.
- [x] Linha 70: apesar de a tradução `Ficheiro -> Abrir` ser correta, no editor de texto o leitor encontrará `Arquivo -> Abrir` (ao menos no Brasil).
- [x] Linha 74: chequei no Firefox e para melhor adequação sugiro utilizar `Arquivo -> Nova aba` ao invés de `Ficheiro -> Nova Guia`. Ainda assim, o segundo passo para abrir um arquivo não parece existir na versão mais atualizada do Firefox. Para evitar dependência de atualizações do navegador, talvez uma possibilidade seja indicar a alternativa que você adicionou no parágrafo abaixo como caminho inicial.
- [x] Linha 74: `razão pela qual` ao invés de `razão para a qual`.
- [x] Linha 77: substituir `abrí-lo` por `abri-lo`.
- [x] Linha 82: substituir `abrí-lo` por `abri-lo`.

Estou à disposição!

**Comment by GabrielaKucuruza** [comment]
Bom dia, @felipelmc! Ótima tradução! Seguem apenas uma pequena sugestão (peço desculpas pela demora!)

- [x] linha 88 -  `se certificar` no lugar de `certifique-se`

Fico a disposição!

**Comment by felipelmc** [comment]
Muito obrigado pelas sugestões, @GabrielaKucuruza e @anacarolerthal. Todas as modificações já foram implementadas. @JimmyMedeiros82, se tudo estiver de acordo, podemos avançar com esta lição.

Abraços!

**Comment by JimmyMedeiros82** [comment]
Muito bom pessoal!
Agradeço ao @felipelmc @anacarolerthal e @GabrielaKucuruza pelo trabalho de tradução e revisão desta lição.

@DanielAlvesLABDH temos uma nova lição pronta par seguir para publicação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos/as! Vou dar início ao processo de publicação.
Apaguei a imagem pois não me parece que se justifique trocar a original.
Actualizei o comentário inicial do ticket.

**Comment by DanielAlvesLABDH** [comment]
Caros/as a lição está publicada. @JimmyMedeiros82 pode actualizar o bot do Twitter e encerrar o ticket. Obrigado! A equipe da FGV está TOP!

**Comment by JimmyMedeiros82** [comment]
Ótimas notícias, @DanielAlvesLABDH
