### ISSUE TITLE
Revisão da tradução da lição Saída de Dados como um Ficheiro HTML com Python

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#463]
O Programming Historian em português recebeu a proposta de tradução da lição 'Saída de Dados como um Ficheiro HTML com Python' feita pelo Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/saida-dados-ficheiro-html-python.md

Já a lição original está em: https://programminghistorian.org/en/lessons/output-data-as-html-file

Agradeço ao @felipelmc pela nova contribuição.
Eu serei o editor da tradução. E vou marcar os revisores desta lição.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Obrigado a ambos por mais uma tradução. Alterei o nome do ficheiro e a pasta. Actualizei o link acima

**Comment by JimmyMedeiros82** [comment]
@anacarolerthal muito obrigado por colaborar conosco em mais uma lição.

**Comment by anacarolerthal** [comment]
Agradeço o convite! Farei a revisão o mais breve possível.

**Comment by anacarolerthal** [comment]
Olá a todos! Mais uma tradução excelente do @felipelmc . Seguem minhas considerações:

- [x] Linha 48: substituir `abrí-lo` por `abri-lo`.
- [x] Linha 52: para evitar a repetição do verbo "considerar", sugiro `Se tomarmos o texto do livro como um dado` ao invés de `Se considerarmos que o texto do livro é um dado`.
- [x] Linha 90: trocar `função` por `funções`.
- [x] Linha 104: trocar ` horário e a data que foi criado` por ` horário e a data em que foi criado`.
- [x] Linha 134: para padronização com os outros comentários de código, adicionar um espaço no início.
- [x] Linha 140: para fins de padronização com a seção anterior, considero `Instruções para Windows` mais adequado.
- [x] Linha 181: no texto original a ideia é de `nome do programa que chamou a função` ao invés de `nome do programa que chamou pela função`.
- [x] Observei que nas lições anteriores utilizaria-se `Ficheiro de Dados Autodocumentado` e `Juntando Tudo` como título das duas últimas seções, mas a tradução do Felipe está conforme o texto original (em questão de minúsculas/maiúsculas). Não sei qual a forma ideal nesse caso, preferi apenas pontuar.

Foi um prazer revisar a tradução, estou à disposição!

**Comment by JimmyMedeiros82** [comment]
Oi @anacarolerthal muito obrigado pela revisão da tradução. 
Mais uma excelente contribuição.

**Comment by JimmyMedeiros82** [comment]
Olá @andresalvolns pode contribuir com esta revisão?
Pode ser feita após a conclusão da outra revisão.

**Comment by andresalvolns** [comment]
Claro, Jimmy!

Vou focar em uma das revisões por agora, mas acredito que depois eu precise
de um tempo para as A2’s e pra conseguirmos montar as aulas das lições de
junho.

**Comment by JimmyMedeiros82** [comment]
Claro, André! No seu ritmo. É só para já deixar na fila.

**Comment by JimmyMedeiros82** [comment]
@andresalvolns quando for possível, por favor, envie sua colaboração.
No seu tempo.

**Comment by andresalvolns** [comment]
Mais uma tradução muito bem feita pelo @felipelmc e uma revisão completa da @anacarolerthal.

Durante a minha revisão me deparei só com uma pequena alteração que eu faria:

- [x] Linha 187: Alterar `“Use (...)”` por `“Use também (...)”`

Qualquer coisa é só me escrever!

**Comment by JimmyMedeiros82** [comment]
Obrigado @andresalvolns pela colaboração!

**Comment by felipelmc** [comment]
Caros, agradeço as revisões atentas de @anacarolerthal e @andresalvolns. Acabei de fazer as modificações e o commit. @JimmyMedeiros82, se tudo estiver de acordo, podemos avançar com esta lição.

Fico à disposição. Um abraço!

**Comment by JimmyMedeiros82** [comment]
Agradeço a colaboração de todos para termos mais uma lição pronta para publicação.

@DanielAlvesLABDH podemos seguir e disponibilizar mais uma lição para o público

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos/as! Vou dar início ao processo de publicação.

**Comment by DanielAlvesLABDH** [comment]
Caros/as a lição está publicada. @JimmyMedeiros82 pode actualizar o bot do Twitter e encerrar o ticket. Obrigado!

**Comment by JimmyMedeiros82** [comment]
Ótimas notícias, @DanielAlvesLABDH
