### ISSUE TITLE
Revisão da tradução da lição Palavras-chave em Contexto (Usando n-gramas) com Python

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#464]
O Programming Historian em português recebeu a proposta de tradução da lição 'Palavras-chave em Contexto (Usando n-gramas) com Python' feita pelo Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/palavras-chave-contexto-usando-n-grams-python.md

Já a lição original está em: https://programminghistorian.org/en/lessons/keywords-in-context-using-n-grams

Agradeço ao @felipelmc pela nova contribuição.
Eu serei o editor da tradução. Vou marcar os revisores desta lição, em breve.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Uma vez mais obrigado Jimmy e Felipe. Alterei o nome do ficheiro e o respectivo link acima

**Comment by JimmyMedeiros82** [comment]
Olá @anacarolerthal  e @GabrielaKucuruza vocês topam colaborar com a revisão desta lição?

**Comment by anacarolerthal** [comment]
Com certeza! Será um prazer.

**Comment by GabrielaKucuruza** [comment]
Opa, sim! Vai ser ótimo colaborar com @anacarolerthal e @felipelmc nessa lição :-)

**Comment by JimmyMedeiros82** [comment]
Muito agradecido a ambas @anacarolerthal @GabrielaKucuruza

**Comment by anacarolerthal** [comment]
Felipe, excelente tradução mais uma vez! A lição me pareceu mais curta, então tive poucas observações, que seguem:

- [x] Linha 36: sugiro utilizar `à esquerda e à direita dela`.
- [x] Linha 40: `exibi-los` ao invés de `exibí-los`.
- [x] Linha 73: acredito que no texto original o sentido era mais próximo de `também podemos utilizar essa técnica para obter`.
- [x] Linha 146: `não precisam possuir` ao invés de `não possuem`.
- [x] Linha 146: substituir `todos os lugares que `wordlist` aparece` por `todos os lugares em que `wordlist` aparece`.
- [x] Linha 165: `temos que converter` ao invés de `nós convertemos`.

Estou a disposição! Um abraço.

**Comment by JimmyMedeiros82** [comment]
@GabrielaKucuruza quando for possível, por favor, envie sua colaboração.

**Comment by GabrielaKucuruza** [comment]
Bom dia @felipelmc e @JimmyMedeiros82, peço desculpas pela demora na revisão! Seguem os comentários e sugestões, parabéns pela tradução :)


- [x] linha 36 - sugiro utilizar "esta" no lugar de "essa"
- [x] linha 40 - Em "Na próxima lição, você aprenderá como gerar todos os n-gramas de uma determinada palavra-chave em um documento baixado da internet e **a** exibi-los claramente na janela do navegador", acho que soa melhor retirando o "a" em negrito.
- [x] linha 52 - acredito que substituir `texto` por `contexto` seja mais próximo do sentido original 


Fico a disposição, abraços!

**Comment by felipelmc** [comment]
@anacarolerthal @GabrielaKucuruza muito obrigado pelas revisões. Acabei de fazer o commit dos ajustes. @JimmyMedeiros82, caso esteja tudo de acordo, podemos avançar para o próximo passo.

Um abraço.

**Comment by JimmyMedeiros82** [comment]
A lição traduzida e revista está no link https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/palavras-chave-contexto-usando-n-grams-python.md
O link indicado cima está corrompido.

Agradeço ao @felipelmc pela tradução e as atentas revisões da @anacarolerthal e @GabrielaKucuruza 
Mais um trabalho incrível que fluiu muito bem.

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH temos mais uma lição traduzida e pronta para seguir para publicação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos/as, uma vez mais! Vou dar início ao processo de publicação.
Actualizei o comentário inicial do ticket com o link para o ficheiro.

**Comment by DanielAlvesLABDH** [comment]
Caros/as a lição está publicada. @JimmyMedeiros82 pode actualizar o bot do Twitter e encerrar o ticket. Obrigado! E já temos 32 lições traduzidas! 🤩🤩

**Comment by JimmyMedeiros82** [comment]
Muito bom, @DanielAlvesLABDH 
Vou trazer novas lições traduzidas para o PH! Vamos avançar mais um pouco.
