### ISSUE TITLE
Revisão da tradução da lição Download de Múltiplos Registros usando Query Strings

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#465]
O Programming Historian em português recebeu a proposta de tradução da lição 'Download de Múltiplos Registros usando Query Strings' feita pelo Felipe Lamarca.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/download-multiplos-registros-query-strings.md

Já a lição original está em: https://programminghistorian.org/en/lessons/downloading-multiple-records-using-query-strings

Agradeço ao @felipelmc pela nova contribuição.
Eu serei o editor da tradução. Irei marcar os revisores desta lição em breve.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes do Felipe. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by DanielAlvesLABDH** [comment]
Jimmy e Felipe, eu apaguei as imagens do repositório pois eram iguais às originais. Nestes casos, não precisamos gerar novas imagens, apenas manter os links para as mesmas dentro do ficheiro traduzido. No final a lição publicada vai buscar essas imagens. Na revisão da tradução peço que verifiquem os nomes dos ficheiros de imagens e revertem para os nomes originais, por favor. Actualizei também o link para o ficheiro traduzido no comentário inicial.

**Comment by JimmyMedeiros82** [comment]
Ficarei atento a isso, @DanielAlvesLABDH  nas próximas lições traduzidas. Temos outras.

**Comment by JimmyMedeiros82** [comment]
Olá @aracele você poderia nos ajudar a revisar a tradução desta lição? 
Ou indicar algum conhecido para esta tarefa?

**Comment by aracele** [comment]
> Olá @aracele você poderia nos ajudar a revisar a tradução desta lição? Ou indicar algum conhecido para esta tarefa?

Oi @JimmyMedeiros82 eu posso tentar ajudar, mas como tô um pouco aperreada, não garanto terminar rápido. Pode ser?

**Comment by JimmyMedeiros82** [comment]
Claro @aracele 
Seguimos no seu tempo.  Sem pressa. Importante é ter uma boa lição traduzida, ao final.

**Comment by JimmyMedeiros82** [comment]
O segundo revisor da lição será o @andresalvolns
Agradeço aos dois pela colaboração nesta lição!

**Comment by JimmyMedeiros82** [comment]
@andresalvolns quando for possível, por favor, envie sua colaboração.

**Comment by andresalvolns** [comment]
Desculpe a demora! Aqui vão algumas mudanças que eu faria pra mais essa ótima tradução do @felipelmc 

- [x] Linha 23: Alterar `“critérios de investigação”` por `“critérios de busca”`
- [x] Linha 42: Alterar` “fontes histórias”` por `“fontes históricas”`
- [ ] Linha 52 e 54: Aparentemente as figuras de tela não foram incluídas com êxito
- [x] Linha 56: Também alterar `“investigação”` por `“busca”`
- [x] Linha 60: Optei por manter `“investigação”` nesse caso por preferir não fazer uso de `“busca”` repetidamente
- [ ] Linha 62: Mesmo caso das linhas `52 e 54`
- [x] Linha 162: Com intenção de fugir da repetição dos termos, alterar `“resultado de busca da sua busca”` por `“resultado de busca da sua investigação”`
- [x] Linha 162: Alterar `“usaremos esse valor”` por `“usaremos o valor de entradas”`
- [x] Linha 618: A frase `“Isso é frequentemente usado ao lidar com erros, conhecido como “error handling””` foi pulada. Ela deve ser adicionada antes da frase `“Podemos usar isso ao nosso favor (...)”`.

Qualquer coisa só me contatar!

**Comment by aracele** [comment]
Olá, gente! Seguem também minhas sugestões de alteração. Parabéns pela tradução @felipelmc! 

- [x]  Estamos adotando algum padrão para os títulos e subtítulos? Reparei que em algumas lições eles estão com todas as palavras começando com letra maiúscula e em outras apenas a primeira palavra começando com a maiúscula. Nesta lição, por exemplo, não há um padrão sequer entre os subtítulos: uns iniciam todas as palavras com maiúscula e outros apenas a primeira palavra com maiúscula.
- [x]  Os links das linhas 42 e 46 não deveriam apontar para as respectivas páginas das lições no site? Eles estão apontando para páginas que não existem no Github.
- [ ]  Nas seções das linhas 58 e 48, "Aplicando nosso Conhecimento Histórico" e "A Investigação Avançada do OBO", a tradução de "search" como "investigação" me pareceu estranha para o contexto brasileiro. Está sendo adotada por ser mais comum no português de Portugal? Além disso, não há um padrão ao longo do texto em relação a isso. Em alguns momentos a palavra aparece como "investigação" (Exemplo: linhas 52, 54 e 56) e em outros aparece como "busca" (Exemplo: linhas 60, 62 e 64). Não seria melhor definir um padrão?
- [x] A tradução da sentença " While searches work similarly, the intricacies of database searches may not be entirely obvious" como "Enquanto investigadores trabalham de modo similar, os meandros de uma busca em uma base de dados podem não ser totalmente óbvias", na linha 60, me pareceu confusa. Acredito que "searches" se refira a "pesquisas" ou "buscas" e não a "investigadores". Uma sugestão seria: "Embora as pesquisas funcionem de forma semelhante, as complexidades das pesquisas em uma base de dados podem não ser totalmente óbvias". 
- [x] Na linha 60, em "O modo de investigação avançada do Old Bailey Online...", a tradução correta de "form" nesse contexto seria "formulário" e não "modo". A frase se refere ao modo de funcionamento do formuário de busca. Assim, minha sugestão seria "O formulário de busca avançada do Old Bailey Online...". 
- [x]  Também na linha 60: a palavra "palavra-chave" deve ser traduzida no plural "palavras-chave" conforme a versão original "keywords". 
- [x] Linha 64: na sentença "se torna mais comum a necessidade de instalar 1.300 ou até 130.000 registros...", acredito que a tradução de "download" mais adequada para o contexto seria "baixar" e não " instalar". 
- [x] Linha 74: Acho que a expressão "We had a look at URLs in Viewing HTML Files" ficaria melhor traduzida como "Vimos sobre URLs em Noções básicas de páginas web e HTML". O link para esta lição também está apontando para uma página inexistente do Github. 
- [x]  Linha 91: Acho que a frase "Observe que cada par nome/valor contém tanto um nome de variável: toYear, e depois atribui um valor a essa variável: 1750." poderia ficar mais clara se fosse reformulada para "Observe que cada par nome/valor contém um nome de variável: toYear e, em seguida, atribui a essa variável um valor: 1750".
- [x] Linha 97: Iniciar o parágrafo com letra maiúscula, tal como o original. Além disso, acredito que "This" no contexto se refira à variável mencionada no parágrafo anterior, portanto, seria mais adequado traduzir a sentença como "Ela contém o termo que digitamos na caixa de busca."
- [x] Também na linha 97: Em "as formas de busca (avançada ou não) ajudam" o termo "search form" também seria melhor traduzido como "o formulário de busca". Sugestão: "o formulário de busca (avançada ou não) ajuda...".
- [x] Linha 103: Link também apontando pra página inexistente. 
- [x]  Também na linha 103: Separar as palavras em "NoOld Bailey..." 
- [x]  Linha 107: "URLs" aparece precedida pelo artigo "a" enquanto em outros momentos aparece precedida pelo "o". Estamos adotando algum padrão em relação a isso? Estamos chamando "a URL" ou "o URL"? Ao longo do texto ambas as formas são usadas. Sugiro padronizar para apenas uma delas. 
- [x] Linha 110: link para a lição "De HTML para Lista de Palavras 2" apontando para uma página inexistente. 
- [x] Linha 112: O título da seção está com as palavras iniciando com letra minúscula. Ver primeiro comentário sobre adotar um padrão para tornar o texto mais consistente.
- [x] Linha 151: Não seria melhor "os vários componentes" ao invés de "as várias componentes da *Query String*"? 
- [x] Também na linha 151: link para a lição "Download de Páginas Web com Python" também apontando pra página inexistente.
- [x] Linha 162: Em "Vamos adaptar nosso programa para fazer o download da outra página contendo as outras 3 entradas ao mesmo tempo, então queremos ter certeza de obter as duas.", a frase ficou um pouco confusa. Acho que a tradução de "so we want to make sure we get both" poderia ser "assim queremos ter certeza que obteremos as duas".  
- [x] Também na linha 162: "Se parece com isso:" talvez ficasse melhor traduzido como "Ela se parecerá com isso:", já que se trata do visual da variável.
- [x] Linha 187: em "Para corrijir isso..." a forma correta da escrita é "corrigir".
- [x] Linha 216: o correto é "indentar" ao invés de "identar".
- [x] Linha 272: em "vamos cuidar de algumas "tarefas domésticas"." acredito que a tradução mais adequada pra "housekeeping" nesse contexto seja "tarefas de organização" e não " tarefas domésticas".
- [x] Linha 339: o link "Contagem de Frequências" está apontando pra uma página inexistente.
- [x] Linha 399: em "para uma busca avançada que definidos" corrigir "definidos" para "definimos".
- [x] Também na linha 399: link "Download de Páginas Web com Python" apontando para página inexistente.
- [x] Linha 616: em '"a conexão se esgotou"' acredito que uma tradução mais adequada seria "a conexão expirou".

**Comment by JimmyMedeiros82** [comment]
@aracele e @andresalvolns obrigado pela revisão atenta da tradução feita pelo @felipelmc

**Comment by JimmyMedeiros82** [comment]
@felipelmc os ajustes foram feitos, após as sugestões dos colegas?

**Comment by felipelmc** [comment]
@JimmyMedeiros82, peço desculpas, ainda não consegui. Até sexta-feira faço todas as alterações.

**Comment by JimmyMedeiros82** [comment]
Tá ótimo, @felipelmc 
Agradeço pela colaboração!

**Comment by felipelmc** [comment]
Caros, desculpem a demora para fazer os ajustes na lição. Acabo de fazer o commit com as mudanças sugeridas pelos colegas @aracele e @andresalvolns. Quando à consideração do @andresalvolns sobre as imagens, acredito que elas só passem a aparecer de fato no HTML da página no site do PH. A respeito da tradução de de "search" para "investigação", trata-se de um padrão definido pelo corpo editorial para a tradução de "pesquisa", @aracele. Podemos pensar um pouco mais sobre isso, se for o caso. De toda forma, a maior partes dos ajustes estão feitos @JimmyMedeiros82. Um abraço!

**Comment by JimmyMedeiros82** [comment]
@felipelmc agradeço pelos ajustes. Podemos manter o 'investigação'
Desta forma, @DanielAlvesLABDH temos outra lição pronta para publicação.

**Comment by JimmyMedeiros82** [comment]
Agradeço a todos por mais uma excelente contribuição.

**Comment by DanielAlvesLABDH** [comment]
Caros, agradeço todo o trabalho colocado nesta tradução e revisão! Vou fazer uma última leitura para iniciar o processo de publicação.

**Comment by DanielAlvesLABDH** [comment]
Conclui a revisão do texto traduzido e testei o código. Tudo certo. Falta apenas receber o DOI para iniciar o processo de publicação. Parabéns a todos/as e muito obrigado!

**Comment by DanielAlvesLABDH** [comment]
Olá @felipelmc, @aracele e @andresalvolns, muito obrigado pelo vosso contributo na tradução e revisão de mais uma lição para português. Já está publicada!
@JimmyMedeiros82 apesar do DOI ainda não estar activo (deve ficar brevemente), podes usar https://doi.org/10.46430/phpt0034 e actualizar o bot do Twitter. De seguida fechar mais um ticket! Obrigado por tudo!

**Comment by JimmyMedeiros82** [comment]
Bot atualizado @DanielAlvesLABDH 
Agradeço a todos pela colaboração! Contente demais pelo trabalho coletivo!
