### ISSUE TITLE
Revisão da tradução da lição Análise de sentimentos em R com ‘syuzhet’

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#467]
O Programming Historian em português recebeu a proposta de tradução da lição 'Análise de sentimentos em R com ‘syuzhet’' feita pela Diana Rodrigues.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/analise-sentimento-R-syuzhet.md

As imagens estão aqui: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/analise-sentimento-R-syuzhet

O ficheiro de texto está aqui: https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/analise-sentimento-R-syuzhet

Já a lição original está em: https://programminghistorian.org/es/lecciones/analisis-de-sentimientos-r

Agradeço a @dianarebelorodriguez pela nova contribuição.
Eu serei o editor da tradução. A Ana Guilia Aldgeire será uma das revisoras. Irei convidar o segundo revisor, em breve.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes da Diana. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by JimmyMedeiros82** [comment]
@anaricciardi você pode contribuir com a revisão desta lição?

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH posso convidar o @ianaraujo para contribuir com esta revisão, sendo o segundo avaliador?

**Comment by DanielAlvesLABDH** [comment]
Olá @JimmyMedeiros82 fiz a actualização do ficheiro e da sua localização. Actualizei o link no comentário inicial.
Em relação ao segundo revisor, o ideal era termos um do lado de Portugal, mas se não for possível avançamos com o Ian, sim. Ele tem feito um trabalho excelente noutras lições também. Será que a @joanacvp ou o @ilv2006 não nos podem ajudar a tentar identificar um/a colega em Portugal que pudesse ajudar aqui? Obrigado a todos

**Comment by DanielAlvesLABDH** [comment]
Actualizei o ficheiro .md da tradução já com os novos nomes das imagens e com a localização  correcta do ficheiro txt

**Comment by joanacvp** [comment]
Boa tarde. Será que a Diana Santos não poderia estar interessada em fazer a revisão?

**Comment by JimmyMedeiros82** [comment]
@ianaraujo você topa revisar esta lição?

**Comment by jenniferisasi** [comment]
@JimmyMedeiros82, mesmaa coisa :) agora temos um "tópico" para R ([#2523](https://github.com/programminghistorian/jekyll/pull/2524)), inclua-o com "r" nos metadados da lição.

**Comment by ianaraujo** [comment]
Claro, @JimmyMedeiros82! Vou trabalhar nisso essa semana.

**Comment by JimmyMedeiros82** [comment]
A Ana Giulia fará a revisão também. Estou marcando o perfil correto na postagem @AnagAldgeire
Ana, seja bem-vinda e agradeço a colaboração!

**Comment by AnagAldgeire** [comment]
Eu que agradeço o convite de participar na revisão desta lição! 
A seguir, seguem os meus comentários e sugestões já enviados e incorporados pela tradutora: 

- [x] Na seção "Objetivos", substituir "você estará apto a trabalhar" por "você estará apto a:"
- [x] Na seção "Objetivos", substituir "espanhol" por "português"
- [x] Na seção "Antes de começar: Análise de sentimentos", substituir "a saber" por "sendo estas"
- [x] Na seção "Antes de começar: Análise de sentimentos", substituir "mas também" por "e também"
- [x] Na seção "Dicionário de léxicos NRC", substituir "incluindo o inglês" por "incluindo o português"
- [x] Na seção "Pacote syuzhet", realçar "pacote R syuzhet" e "5 de junho de 2014" com sublinhado e cor da letra em azul 
- [x] Na seção "Pacote syuzhet", substituir "ele continuamente introduz mudanças e o mantém" por "ele continuamente introduz mudanças e é responsável por mantê-las"
- [x] Substituir, ao longo do texto, "embalagem" por "pacote"
- [x] Ao longo do texto realçar "syuzhet" com a cor da letra em vermelho e sublinhado de cinza 
- [x] Na seção "Baixar e preparar o texto", substituir "fio" por "string"
- [x] Na seção "Extração de dados com o NRC Sentiment Lexicon", realçar "get_nrc_sentiment" com a cor da letra em vermelho e sublinhado cinza 
- [x] Na seção "Contando o número de palavras com cada emoção", substituir "visualizemos" por "iremos visualizar"
- [x] Na seção "Nuvem de emoções", colocar "Dom Casmurro" itálico 
- [x] Na seção "Em Windows", realçar "comparison.cloud" com a cor da letra em vermelho e sublinhado cinza 
- [x] Na seção "Salve seus dados", substituir "quadro de dados" por "data frame"
- [x] Ao longo do texto, substituir "dataframe" por "data frame"

Parabéns @dianarebelorodriguez pelo excelente trabalho!

**Comment by ianaraujo** [comment]
Complementando a revisão da colega @AnagAldgeire, faço algumas sugestões:

- [x] Linha 31 - Substituir "algum conhecimento de R" por "algum conhecimento dessa linguagem".
- [x] Linha 31 - Não tenho uma sugestão específica, mas para o usuário iniciante talvez a expressão "carregar pacotes" não seja clara do que é necessário fazer. Talvez "importar". 
- [x] Linha 31 - Substituir "R Studio" por "RStudio". É bobagem e também não sei se pode alterar conforme foi escrito no original, mas o autor da lição hora escreve com espaço, hora escreve sem. Se possível manter tudo como "RStudio" e talvez adicionar um link direto para página de download (não sei se pode alterar o original nesse sentido). 
- [x] Linha 34 - Substituir "valor emocional" por "indicador de sentimento".
- [x] Linha 40 - Substituir "de" por "do".
- [x] Linha 54 - Substituir "anotado" por "construído". 
- [x] Linha 54 - Substituir "ela está disponível" por "ele está disponível". Imagino que o pronome esteja se referindo ao conjunto de dados ou aos léxicos. 
- [x] Linha 68 - Substituir "O léxico português" por "O léxico em português".
- [x] Linha 75 - Colocar "dataframe" em itálico. 
- [x] Linha  128 - Na nota da tradutora é preciso usar o ENTER entre as linhas 128, 129, 130 e 131 para melhorar o entendimento do código. Não sei se é possível, mas dentro da nota, enquanto expõe-se o código, seria interessante usar o recurso de bloco de código (```).
- [x] Linha 139 - Substituir "ambientada" por "ambientado".
- [x] Linha 149 - Substituir "para poder realizar a recuperação do sentimento" por "para poder obter o sentimento".
- [x] Linha 169 - Colocar "string" em itálico.
- [x] Linha 173 - Substituir "la función" por "a função".
- [x] Linha 176 - Remover espaços duplos ao redor de "<-".
- [x] Linha 187 - Substituir "análise de textos distantes" por "análise distante de textos".
- [x] Linha 205 - Remover espaços duplos ao redor de "<-".
- [x] Linha 214 - Substituir "o dizemos" por "a escrevemos".
- [x] Linha 219 - Substituir "executar" por "executarmos" e "deve" por "devemos".
- [x] Linha 272 - Colocar "barplot" em itálico.
- [x] Linha 300 - Substituir "de emoção" por "emoções de".
- [x] Linha 306 - Adicionar espaço após "sentimentos_df$sadness", antes do sinal de maior ">".
- [x] Linha 363 - Colocar "corpus" em itálico.
- [x] Linha 369 - Esses dois asteriscos (**) são propositais? 
- [x] Linha 385 - Substituir "termo português" por "termo em português".
- [x] Linha 415 - Traduzir o título para o português. Sugestão: "Visualizando a evolução dos sentimentos em um texto".
- [x] Linha 420 - Adicionar um espaço após o asterisco "*", antes de "-1".
- [x] Linha 449 - Substituir "um quadro de dados" por "uma tabela".

Parabéns @dianarebelorodriguez pela excelente tradução! Principalmente, pelo desafio de adaptar a lição original, buscando usar exemplos mais próximos da cultura brasileira. :clap:

**Comment by JimmyMedeiros82** [comment]
Agradeço demais pela revisão atenta do @ianaraujo e da @AnagAldgeire 
Teremos mais uma nova lição traduzida pela @dianarebelorodriguez 
Excelente, pessoal!

**Comment by dianarebelorodriguez** [comment]
Queridos, bom dia,

Desculpem a demora. Fiquei muito contente com as sugestões, são muito pertinentes e já foram integralmente incorporadas na tradução. Obrigada @AnagAldgeire e @ianaraujo pela dedicação na revisão e @JimmyMedeiros82 pelo esforço de avançar com a tradução. Creio que esteja pronta para publicação.

**Comment by JimmyMedeiros82** [comment]
Excelente, @dianarebelorodriguez 
Tenho apenas três pedidos de ajuste. 
1) Na linha 171 o link para a obra Dom Casmurro não abre. Está na seção "Carregar e preparar o texto". Poderia corrigir o link?
2) A imagem da linha 294 não abre. Por favor, verifique o que aconteceu.
3) Assim como no item anterior, a imagem da linha 417 não abre. Por favor, verifique o que aconteceu.

**Comment by dianarebelorodriguez** [comment]
Oi, @JimmyMedeiros82 , obrigada pelos comentários! 

O @DanielAlvesLABDH tinha feito essas modificações, porque eu só tinha o link e as imagens no Google Drive, não conseguia subir aqui no GitHub. Será que ele pode nos ajudar com isso? Espero que sim!

**Comment by JimmyMedeiros82** [comment]
@dianarebelorodriguez me envia os dois arquivos e eu coloco no GitHub e mudo o link na lição. O primeiro link você consegue atualizar?

**Comment by JimmyMedeiros82** [comment]
@dianarebelorodriguez feito! 
Mais uma vez, agradeço pela colaboração da Diana, assim como do @ianaraujo e @AnagAldgeire 

@DanielAlvesLABDH agora temos mais uma lição pronta para publicação.

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos/as por esta tradução e revisão. Ainda por cima adaptada para a análise desse clássico que é Dom Casmurro. Adorei! Fiz uma revisão final do texto, corrigi os links e acrescentei uma nota de tradução um pouco antes do início de utilização do texto em português. Vou pedir o DOI e dar início ao processo de publicação.

**Comment by DanielAlvesLABDH** [comment]
Caros/as temos mais uma lição publicada. Parabéns e obrigado por todo o vosso trabalho! @JimmyMedeiros82 pode actualizar o bot do Twitter e encerrar o ticket. Obrigado!

**Comment by JimmyMedeiros82** [comment]
Ótima notícia, @DanielAlvesLABDH
parabéns a todos. Nossa 22ª lição publicada
