### ISSUE TITLE
Revisão da tradução da lição Visualização e animação de tabelas históricas com R

### ISSUE THREAD

**Issue by JimmyMedeiros82** [programminghistorian/ph-submissions#468]
O Programming Historian em português recebeu a proposta de tradução da lição 'Visualização e animação de tabelas históricas com R' feita pela Diana Rodrigues.

A lição traduzida está no link a seguir: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/visualizacao-animacao-tabelas-historicas-R.md

Já a lição original está em: https://programminghistorian.org/es/lecciones/visualizacion-y-animacion-de-tablas-historicas-con-R

Agradeço a @dianarebelorodriguez pela nova contribuição.
Eu serei o editor da tradução. O @felipelmc será um dos revisores. Irei convidar o segundo revisor, em breve.

Peço para avaliarem a tradução para o português, assim como se há necessidade de adequação de dados ou algum conteúdo. Por favor, deixem suas sugestões neste ticket. Para cada modificação a ser sugerida, por favor, peço para indicar as linha de maneira que facilite os ajustes da Diana. O ideal é realizar as modificações após as sugestões dos dois revisores.

Todos os membros da comunidade estão convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores (/directrizes-revisor) e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o/a autor/tradutor(a) possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso mediador independente se achar necessário.
Se houver alguma preocupação da tradutora, ele pode entrar em contato com o mediador do PH em português (Luís Ferla).

**Comment by felipelmc** [comment]
Caros, é um prazer contribuir de alguma forma para a tradução desta lição! Os comentários e sugestões já foram previamente repassados à @dianarebelorodriguez e a lição já foi atualizada pela tradutora.

**Comment by DanielAlvesLABDH** [comment]
Caros, actualizei alguns detalhes no ficheiro e na sua localização. Fiz a actualização do link no comentário inicial da lição. O ficheiro está aqui: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/licoes/traducoes/visualizacao-animacao-tabelas-historicas-R.md
Agradeço muito ao @felipelmc pela sua revisão e à @dianarebelorodriguez por mais uma tradução.
Peço ao @felipelmc que se possível copie os seus comentários e sugestões para um comentário aqui no ticket. Temos por objectivo deixar um registo tão completo quanto possível do processo de revisão, pois este ticket é associado à publicação da lição para que os leitores possam mais tarde verificar todo o processo de revisão por pares. Desde já agradeço.

**Comment by felipelmc** [comment]
Claro, @DanielAlvesLABDH! Infelizmente não pude montar o esquema de apontamento das linhas que foram alteradas, uma vez que a revisão foi feita pelo Google Docs. Em todo caso, seguem os comentários e sugestões abaixo, já avaliados e acatados pela tradutora quando pareceu conveniente:

- Na seção "Os dados explorados", substituir "Ter" por "Dispor de";
- Na mesma seção, manter os nomes das colunas da tabela em espanhol e explicar o significado de cada uma delas em parênteses;
- Na seção "Processamento e limpeza de dados com R", ajustar "[...] mostra abaixo o nome de cada variável [...]" para "[...] mostra abaixo do nome de cada variável";
- Ao longo do texto, retificar "caracter" para "caractere";
- Substituir "laços" por "estruturas de repetição";
- Na seção "Visualização de tabelas com ggplot2", substituir "ver" por "visualizar";

Aproveito a oportunidade para parabenizar a @dianarebelorodriguez pela excelente tradução! Ótimo trabalho!

**Comment by jenniferisasi** [comment]
@JimmyMedeiros82 agora temos um "topic" para R ([#2523](https://github.com/programminghistorian/jekyll/pull/2524)), inclua-o com "r" nos metadados da lição. Obrigada.

**Comment by JimmyMedeiros82** [comment]
Ótima notícia, @jenniferisasi 
Farei o ajuste.

**Comment by JimmyMedeiros82** [comment]
Ana Giulia, você poderia colaborar com a revisão desta lição também @AnagAldgeire ?

**Comment by AnagAldgeire** [comment]
Claro, @JimmyMedeiros82! Ainda essa semana envio meus comentários e sugestões!

**Comment by AnagAldgeire** [comment]
Prezados, agradeço o convite para colaborar na revisão desta lição! A seguir seguem as minhas sugestões de alterações: 

- [x] Na seção "Objetivos", retirar ponto final do primeiro tópico 
- [x] Na seção "Introdução", substituir "ela permite" por "é possibilitado"
- [x] Na seção "Introdução", adicionar vírgula em "observar padrões e anomalias, e estabelecer relações temporais"
- [x] Na seção "Os dados explorados", substituir "dados quantitativamente processável" por "dados quantitativamente processáveis" e adicionar ponto final na frase. 
- [x] Na seção "Processamento e limpeza de dados com R", substituir "esteja contido dentro do pacote arrumado" por "esteja contido dentro do último"
- [x] Ao longo do texto, substituir "dataframe" por "data frame'
- [x] Na seção "Processamento e limpeza de dados com R", substituir "trabalhar com ela" por "trabalhar com eles"
- [x] Na seção "Processamento e limpeza de dados com R", substituir "recursos de exibição" por "funções de visualização"
- [x] Na seção "Explorando os dados", substituir "aberrações" por "valores atípicos"
- [x] Na seção "Explorando os dados", retirar "de usar" em "tabelas de contingência mais fácil de usar, usando pacotes disponíveis no CRAN"
- [x] Na seção "Visualização de tabelas com ggplot2", substituir "um ponto no avião" por "um ponto no plano"
- [x] Na seção "Visualização de tabelas com ggplot2", substituir "travessias variáveis" por "cruzamentos de variáveis"
- [x] Na seção "Visualização de tabelas com ggplot2", retirar "adicional" em "é possível adicionar uma camada adicional com a função"
- [x] Na seção "Animando a visualização dos dados com gganimate", inverter "renderização (rendering)" por "rendering (renderização)".
- [x] Na seção "Animando a visualização dos dados com gganimate", realçar "fps" com sombreado cinza 

Parabenizo a @dianarebelorodriguez por mais um excelente trabalho na tradução!

**Comment by JimmyMedeiros82** [comment]
Agradeço ao @felipelmc e @AnagAldgeire pela revisão! 
A @dianarebelorodriguez pode avançar nos ajustes para concluirmos mais uma tradução.

**Comment by dianarebelorodriguez** [comment]
Queridos, bom dia,

Desculpem pela demora em retornar. Fico feliz em anunciar que todas as sugestões foram devidamente incorporadas e a lição encontra-se pronta para publicação! Agradeço imensamente aos que se dedicaram à ela e também os parabenizo! @felipelmc @AnagAldgeire @JimmyMedeiros82 

Obs: A @AnagAldgeire também foi incluída como revisora no cabeçalho da lição. Podemos publicar!

**Comment by JimmyMedeiros82** [comment]
@DanielAlvesLABDH temos mais uma lição traduzida para ser publicada.

Ela, em breve, precisará ser atualizada, logo que concluirmos os ajustes da tradução da lição "Manipulação e transformação de dados em R" https://github.com/programminghistorian/ph-submissions/issues/397  Por enquanto, o link vai para a lição em inglês. Mas já temos tudo para disponibilizar para o público. 
Agradeço à @dianarebelorodriguez pela tradução e aos revisores @felipelmc e @AnagAldgeire pelo trabalho atento!

**Comment by DanielAlvesLABDH** [comment]
Obrigado a todos e todas! E parabéns por mais uma tradução concluída. Vou ter isso em conta quando publicar. De qualquer forma mudar o link posteriormente não será complicado. Abraço

**Comment by DanielAlvesLABDH** [comment]
Fiz todas as verificações e acho que está pronta para publicação. Fica a faltar a mudança do link para a lição em português, mas essa alteração fazemos mais tarde. Vou pedir o DOI e preparar os ficheiros para publicar. Obrigado à @dianarebelorodriguez pela excelente tradução, muito cuidada. Obrigado igualmente ao @felipelmc e à @AnagAldgeire pela revisão atenta. Ficou muito boa! Obrigado @JimmyMedeiros82 , temos mais uma a caminho!

**Comment by DanielAlvesLABDH** [comment]
Caros/as temos mais uma lição publicada. Parabéns e obrigado por todo o vosso trabalho! @JimmyMedeiros82 pode actualizar o bot do Twitter e encerrar o ticket. Obrigado!

**Comment by JimmyMedeiros82** [comment]
Trabalho encerrado!
