### ISSUE TITLE
Re-organising the FR file directories within ph-submissions

### ISSUE THREAD

**Issue by anisa-hawes** [programminghistorian/ph-submissions#474]
I am re-organising the FR file directories within ph-submissions.

N.B. I am aware that these changes will break links to live Lesson Previews, so my first task after merging will be:

* update all Preview links for lessons under active review
* let all active editors, authors and reviewers know that the file directory structure has changed for FR

In collaboration with @spapastamkou, I have created two sub-folders within the directory /fr:

fr/en-cours
fr/publiees

Nested within those, I have created:

fr/en-cours/traductions
fr/en-cours/originales

fr/en-cours/traductions/inactives
fr/en-cours/originales/inactives

fr/publiees/traductions
fr/publiees/originales

**Comment by spapastamkou** [comment]
Thank you!
