### ISSUE TITLE
Transkribus Tutorial

### ISSUE THREAD

**Issue by giuliataurino** [programminghistorian/ph-submissions#477]
The Programming Historian has received the following tutorial on 'Transkribus Tutorial' by @rpmacalp. This lesson is now under review and can be read at:

[http://programminghistorian.github.io/ph-submissions/en/drafts/originals/transkribus-tutorial](http://programminghistorian.github.io/ph-submissions/en/drafts/originals/transkribus-tutorial)

Please feel free to use the line numbers provided on the preview if that helps with anchoring your comments, although you can structure your review as you see fit.

I will act as editor for the review process. My role is to solicit two reviews from the community and to manage the discussions, which should be held here on this forum. I have already read through the lesson and provided feedback, to which the author has responded.

Members of the wider community are also invited to offer constructive feedback which should post to this message thread, but they are asked to first read our Reviewer Guidelines (http://programminghistorian.org/reviewer-guidelines) and to adhere to our anti-harassment policy (below). We ask that all reviews stop after the second formal review has been submitted so that the author can focus on any revisions. I will make an announcement on this thread when that has occurred.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. 

Our dedicated Ombudsperson is (Ian Milligan - http://programminghistorian.org/en/project-team). Please feel free to contact him at any time if you have concerns that you would like addressed by an impartial observer. Contacting the ombudsperson will have no impact on the outcome of any peer review.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. Thank you for helping us to create a safe space.

**Comment by anisa-hawes** [comment]
Hello @giuliataurino. Do you have an update on this lesson? 

Unless the author's new draft is forthcoming, I'd like to suggest we close this Issue.

If they decide to submit their lesson in the future, we can always reopen this and begin again.

**Comment by rpmacalp** [comment]
Good morning,

Apologies for the delay in submitting my revisions to this lesson. I was in the process of organizing some additional resources based on the processing of my doctoral data, which took longer than anticipated. At this stage in the process, I can aim to have the lesson to you by December 16th if that works well for all of you. Let me know if this proposed timeline works well!

Best,

Rebecca
_______________________________________
Rebecca MacAlpine (she/her) MA, OCT
PhD Candidate, Department of History, University of Waterloo
Graduate Student Developer, Centre of Teaching Excellence
Data Management and Curriculum Design Coordinator, The Artemisia Project
E: ***@***.******@***.***>

**Comment by anisa-hawes** [comment]
Thank you for getting in touch, @rpmacalp. It's great news that you'd like to submit a revised version of this lesson. 

When we receive your new submission, we can open a new Issue and generate a new preview.
