### ISSUE TITLE
Correção de problema na estrutura de diretórios de lições em português

### ISSUE THREAD

**Issue by ericbrasiln** [programminghistorian/ph-submissions#480]
Olá @JimmyMedeiros82 

Estava analisando a estrutura dos repositórios e arquivos das lições em português e percebi que há um problema na pasta [phsubmissions/pt](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/pt). O [commit ce8c3c0](https://github.com/programminghistorian/ph-submissions/commit/ce8c3c01500a778e1e78956090eb52440058b3d5) alterou o nome da pasta licoes para licores, o que criou uma nova pasta [pt/licores](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/pt/licores/tradu%C3%A7%C3%B5es) onde está a lição traduzida.

É preciso fazer um novo commit colocando a lição na pasta correta e excluíndo a pasta `licores`.

Te marquei aqui, pq vc é o editor dessa lição, de acordo com #444 
Mas eu posso fazer esse processo de correção, se vc preferir.

Abraços.

**Comment by JimmyMedeiros82** [comment]
oi @ericbrasiln se não for um problema para você, pode efetuar a correção!
Agradeço

**Comment by ericbrasiln** [comment]
Já realizei a correção. 

Corrigi a localização da tradução da lição: a pasta com nome errado (licores) foi excluída e o arquivo md da tradução foi inserida na pasta correta (pt/licoes/traducoes). Aqui o [commit](https://github.com/programminghistorian/ph-submissions/commit/755dd019c2ab2c18f01edd589c320937c662130f) 

Vou comentar na issue #444 apontando o novo caminho para o arquivo da tradução.
Abraços
