### ISSUE TITLE
La lecture multi-échelles de données structurées

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#482]
Le Programming Historian en français a reçu la traduction de la leçon intitulée 'La lecture évolutive de données structurées' par traduite par @annelaure-blog. La traduction est actuellement en cours d'évaluation et peut être consultée ici:

https://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/lecture-multi-echelles-donnees-structurees

Les membres de la communauté plus large sont aussi invités de fournir une critique constructive via ce fil de messages, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (cf. ci-dessous). Nous demandons que toute nouvelle évaluation cesse après que la seconde, parmi celles qui ont été formellement sollicitées, a été déposée, pour que l'auteur(e) puisse se concentrer sur les révisions à faire. Lorsque cela est le cas, je prendrai soin de l'indiquer dans le fil de discussion.

Politique contre le harcèlement.
_

Ceci est une déclaration des principes du Programming Historian en français et définit nos attentes concernant le ton et le style des échanges entre évaluateurs/évaluatrices, auteur(e)s, rédacteurs/rédactrices et toute autre personne contribuant à nos forums publics. Le Programming Historian en

Le _Programming Historian en français_ a pour but d'offrir un environnement académique ouvert, qui permet aux membres de la communauté de se sentir libres d'examiner des idées en détail, de poser des questions, de faire des suggestions, ou de formuler des demandes de clarification. Nous insistons sur l'importance de faire en sorte que cet espace de discussion reste respectueux et exempt de tout harcèlement pour tous les contributeur(trice)s, quels que soient leur genre, leur identité et leur expression de genre, leur orientation sexuelle, leur handicap, leur apparence physique, leur masse corporelle, leurs origines, leur âge, leur religion, ou leur expérience technique. Nous ne tolérons pas, sous quelque forme que ce soit, le harcèlement ou les attaques ad hominem contre les membres de la communauté. Les participant(e)s qui violeraient ces règles pourront être exclu(e)s de la communauté à la discrétion du comité éditorial. Si quelqu'un est témoin ou pense avoir été victime des agissements décrits plus haut, veuillez prendre contact avec notre médiatrice [Hélène Huet](/fr/equipe-projet). Merci de nous aider à créer un espace de discussion et d'échange sûr.

**Comment by tiagosousagarcia** [comment]
@spapastamkou this is the commissioned translation of #419, translated by @annelaure-blog. When you have the time, could you assign an editor and ask them to make an initial review so that we can finish our business with the translator?

I've made a very light technical review on uploading the files, but a more thorough one is still needed. @annelaure-blog also left me a couple of notes via email:
- Regarding links to other PH tutorials : I have linked to the english version if there was no french version online, otherwise I linked to the french version
- I did not modify or rewrote the sentences but I did, occasionally, split long sentences into two or three shorter sentences for readability purposes. I did not simplify or delete any content.
- I researched the links to the references at the end of the document and made sure each reference is linked to the proper article (I think there might have been some formatting issue in the english version). I think I have all the references right but it might be better for you to check.
- Line 48 : it feels like the sentence calls for other images that are missing ? It says " The visualisation looks a lot like the previous bar charts, but the difference here is facet_wrap, which creates three bar charts for each type of interaction". Its the only part of the tutorial that was not 100% clear to me. [we'll review that in the EN version]
 - all the 3 images have a "need caption" mention below that I did not translated or included in english [we'll correct that in the EN version]
 
I'm here to help in anyway that is needed, though my French is limited :)

**Comment by spapastamkou** [comment]
Thanks for the update @tiagosousagarcia. I @spapastamkou will be editor of the translated lesson. May I ask for some clarifications before? During the editing of the the translated lessons, we review the translation of the peer-reviewed original. How are we to process here? The FR translation here is the one of the lesson before or after peer-review? If the former, how and when the revisions will be integrated? If the latter, then I guess the question is answered:-) Thanks!

**Comment by tiagosousagarcia** [comment]
Thank you @spapastamkou! The original lesson has been through peer-review before the translation was commissioned, so I think it's ok to proceed as normal :)

The main difference is that this one will need an initial reading to see whether there are any major changes needed from the original translator at this stage; later, smaller changes will need to be introduced by the editor or someone else from the FR team. @annelaure-blog also offered to hold off on her normal review workflow until the team has had a chance to properly review the lesson but, in that case, any changes required from her should come at once. Or to put it simply, we either:

1. Check the translation now for any major changes, ask the translator to review, and then close our business with her at the point of re-delivery; any changes after that will need to be introduced by the team;
2. We close our business with the translator _now_, go through the full review process (up until after peer-review), and then ask her to address any reasonable changes (keeping in mind her role as a translator) -- the downside here is that she will have other work to attend to and may not come back to us within a reasonable time-frame.

I'll leave it up to you to decide which option is best, of course

**Comment by drjwbaker** [comment]
Chipping in here, I think we should do 1: check the review to see that we are broadly happy with the translation, ask the translator to make any changes we want, pay the translator and close our business with them, then move onto any localisation and PH-specific translation practices (e.g. variables in code).

**Comment by spapastamkou** [comment]
Thank you @tiagosousagarcia for the additional information. I will agree with @drjwbaker, it's better to get done with this first, as sometimes things can go unexpectedly with the reviews, and we also have the summer holiday approaching which will make it harder to get people together. Can we say something like a week from now, so around 5 July for me to make comments, if any?

**Comment by annelaure-blog** [comment]
Thank you everyone for your quick response and for the collective reviewing organisation. If I may respond here for my part, I can wait until the 5th of July for any comments you would like to make on the translation. I plan on working on it as soon as I recieve your comments so we should be able to close our business this same week. May I also say, I would welcome any chance to work on the Programming Historian content again as it has been a very interesting experience.

**Comment by tiagosousagarcia** [comment]
Many thanks for your flexibility @annelaure-blog!

**Comment by spapastamkou** [comment]
Bonjour @annelaure-blog. Avant toute chose, je vous remercie pour la traduction du tutoriel. Je partage donc avec vous l'essentiel de mes commentaires après avoir effectué une lecture préliminaire du texte. Ceux-ci sont notamment de deux types: 1) des commentaires qui portent sur le fond concernant certains termes, et 2) des commentaires sur la forme qui répèrent notamment quelques coquilles ou font quelques suggestions. 
D'une manière générale, je signale ci-dessous le numéro de ligne (qui correspond à l'affichage que j'ai eu en travaillant sur le fichier en local sur notepad++ mais qui correspond également à la version que vous pouvez trouver [en ligne sur notre dépôt](https://github.com/programminghistorian/ph-submissions/edit/gh-pages/fr/en-cours/traductions/lecture-donnees-structurees.md) une fois que le fichier est en mode modification (Edit this file). 
Lorsque le terme en question est rencontré plusieurs fois dans le document, je n'ai pas mis de no de ligne (mais il est facile de les répérer avec la fonction find).

**1. Sur le fond**   
Il s'agit notamment des traductions des termes suivants: scalable reading, close reading (en couple avec le terme distant reading), datapoint 

close/distant reading
Dans la littérature francophone (notamment en discutant des travaux de Franco Moretti), nous rencontrons le plus souvent les termes comme suit: 
distant reading -> lecture distante 
close reading -> lecture proche
Comme ces termes sont établis, plus ou moins, il me semble qu'il serait plus compréhensible pour le public de les suivre (et donc de remplacer lecture attentive par lecture proche). Il s'agit essentiellement de saisir facilement que ce dont il est question est une approche quanti/quali.   

scalable reading
De même, pour scalable reading: sans émettre des doutes quant à la pertinence en soi de la traduction proposée, lecture évolutive, le terme me semble peu courant en histoire et humanités numériques. Là, je crois que c'est qui est en jeu est la notion d'échelles que l'on peut multiplier et alterner pour une analyse plus pertinente. Est-ce que le terme lecture à échelles ou lecture multi-échelles vous conviendrait? Il me semble que le titre serait plus compréhensible pour le lectorat que nous visons. 

Enfin, dans le même ordre d'idées, il me semble un peu difficile à saisir en français les parties où il est question de "points de données", mais je comprends toute la difficulté puisque cela provient de l'original. Il s'agit là d'une question que je poserai ouvertement aux personnes qui s'attacheront à la relecture, il faudra peut-être trouver un moyen pour paraphraser ou ajouter des précisions pour la version finale à publier.   

**2. Sur la forme (coquilles etc)**
l. 67, 192, 195 artistes Danois -> artistes danois _puisque danois est utilisé ici comme adjectif_
l. 76 leur API dite "Essentielle" (*Essential*) que nous avons utilisé -> leur API dite "Essentielle" (*Essential*) que nous avons utilisée
ligne 76: 1. Utiliser l'une des APIs de Twitter, c'est-à-dire leur API dite "Essentielle" (*Essential*) que nous avons utilisé pour récupérer le jeu de données utilisé dans l'exemple (pour en savoir plus sur les APIs, vous pouvez consulter [cette section de la leçon sur introduire et peupler un site web avec des données API] -> _on rencontre trois fois dans la même phrase le verbe utiliser - varier avec un synonyme pour éviter la répétition?_
l.112 se raporter non pas à un évènement -> se rapporter
 l. 157 Puis la fonction est ensuite renseignée -> _Puis + ensuite = pléonasme?_
 l. 158 Les expressions régulières peuvent être vue comme une fonction "recherche et remplace" étendue -> vues _(au pluriel)_ - "fonction rechercher et remplacer" 
l. 163 sera différentes ce qu'elle était -> sera différente de ce qu'elle était 
 l. 182 vous avez ajouter -> ajouté 
 l. 190 en comparaison d'autres méthodes -> en comparaison avec? comparée à?
 l. 190 les compte dits "vérifiés" -> comptes 
 l. 194, 426 point de donnée -> point de données? _au pluriel_
 l. 195 les 20 oeuvres d'art les plus explosées -> exposées?
 l. 199 vous suivez chaque étape qui montrent  -> montre 
 l. 275 les comptes vérifiés moins représentés -> les moins représentés? 
 l. 275 que ceux des comptes non vérifiés -> qu'avec ceux 
 l. 290 et 326 VS -> versus
 l. 320 lectures distances -> distantes 
 l. 365 (et plusieurs autres dans le document) Environnement Global -> _sans majuscules_ 
 l. 372 contenues -> contenus
 _plusieurs lignes dans tout le document (en dehors des scripts): nous trouvons top (pour top 20) écrit de diverses manières: top, Top, TOP -> uniformiser en mettant partout: top_
 l. 392 exclue -> exclut 
 l. 420 prêt à être -> prêts
 l. 421 twitter -> Twitter;  conditions générale -> conditions générales; matching -> croisement?  
l. 425 Font-ils partis  -> partie

En conclusion, merci de me dire ce que vous en pensez sur les commentaires quant au fond, notamment pour les traductions de close et scalable reading (qui sont pour moi les plus importants à voir ensemble) et, quand vous le pouvez, effectuer les petites corrections de coquilles. 

J'aimerais également vous demander dans quelle mesure vous comptez suivre/vous impliquer dans le processus de relecture, puisqu'il est possible d'avoir à faire de petites modifications dans le texte à la suite des retours que nous aurons (habituellement deux relectures), et donc dans quelle mesure vous souhaitez avoir votre mot à dire sur le texte final à publier. En vous remerciant pour votre attention, je reste à votre disposition pour toute précision comlémentaire. Et encore merci pour votre travail, la tâche est loin d'être simple!

**Comment by spapastamkou** [comment]
@annelaure-blog Il nous faut aussi cette déclaration de cession de droits insérée en commentaire séparé (à moins que vous l'avez déjà rempli avec mon collègue @tiagosousagarcia (Tiago, maybe this is already done, I am just asking Anne-Laure if she has already sent you the declaration about the rights, which otherwise we'll need to have here in comment).

Je [prénom] [nom,] traductrice, cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier le tutoriel dont il est question dans ce ticket (y compris le résumé, les tables, les illustrations, les données, et des ressources supplémentaires) sous licence CC-BY <https://creativecommons.org/licenses/by/4.0/deed.fr>.

Merci à vous!

**Comment by annelaure-blog** [comment]
Bonjour @spapastamkou et merci pour votre relecture attentive (proche!) de la traduction.

Concernant les remarques sur le fond :
- je suis en accord avec l'emploi des termes "lecture proche" et "lecture distante" qui me semblent en effet plus lisibles. J'ai uniformisé ces formulations dans l'ensemble du texte pour traduire respectivement "close reading" et "distant reading".
- j'ai également remplacé "lecture évolutive" (scalable reading) par "lecture multi-échelles" (y compris dans le titre de la leçon et du fichier markdown), terme qui me semble plus pertinent pour traduire plus concrètement la notion d'échelles et de changements d'échelles permise par cette méthode d'analyse des données.
- Je trouve aussi que "point de donnée" n'est pas une formulation très lisible, j'avoue ne pas avoir identifié une traduction satisfaisante pour le moment. Le fait de parler de "point" n'a pas vraiment de sens en français pour désigner une donnée située dans un ensemble de plusieurs données. Peut-être que "donnée singulière", "donnée spécifique" ou "donnée unique" pourrait convenir...
- Une proposition que je peux vous faire serait d'ajouter une courte section en début de leçon afin de définir ces concepts (distant reading, close reading, scalable reading, data point) et d'expliquer brièvement les choix de traduction qui ont été opérés. La plupart des autres tutoriels sur ces sujets seront probablement en anglais. Il peut être utile pour les utilisateurs de connaître la traduction exacte et de comprendre, d'un point de vue du sens, à quoi ces termes réfèrent dans leur langue d'origine. Cela ajoute aussi des savoirs conceptuels utiles avant d'entrer dans le tutoriel technique.

Sur la forme :
- j'ai corrigé, sauf erreur de ma part, l'ensemble des coquilles identifiées (et quelques autres au passage).
- j'ai ajouté un lien vers les conditions générales d'utilisation des API Twitter (ligne 421), était-ce bien ce que vous souhaitiez par la mention "croisement" ?

Je suis intéressée à suivre le processus de relecture, s'il faut effectuer de petites modifications par la suite.
La formulation générale du texte en anglais était un peu surprenante parfois (répétitions et phrases relativement longues), et il est vrai que j'ai traduit de manière assez littérale sans trop reformuler, ne souhaitant pas dénaturer le contenu d'origine. Maintenant que le texte est en français, une phase de réécriture plus axée sur la pédagogie et la qualité de la formulation pourrait être utile.

Enfin, voici la mention liée aux droits :

Je, Anne-Laure Fréant, traductrice, cède à ProgHist Ltd de manière non-exclusive notamment le droit de publier le tutoriel dont il est question dans ce ticket (y compris le résumé, les tables, les illustrations, les données, et des ressources supplémentaires) sous licence CC-BY https://creativecommons.org/licenses/by/4.0/deed.fr.

Merci !

**Comment by spapastamkou** [comment]
Merci beaucoup @annelaure-blog ! 
Pour datapoint, je n'avais pas vraiment de proposition à faire, c'est pourquoi il me semble intéressant de dialoguer à ce sujet lors des relectures. Du coup, je suis contente que cela vous intéresse plus généralement de suivre, parce que sinon cela aurait été à moi, le cas échéant, de prendre des décisions qui portent tout de même sur votre traduction et il me semble franchement préférable d'avoir votre accord. Pour les modifications (finales), s'il y en a, je pourrai les intégrer si jamais vous êtes trop prise.

Sinon, je comprends parfaitement les difficultés d'adaptation depuis l'anglais, nous les rencontrons souvent par ici:-)

Autrement, pour expliquer les concepts, nous pouvons aussi ajouter des notes de fin propres à la traduction française. J'ai encore quelques modifs de mise en forme à faire et à ajouter les métadonnées dans le fichier et je peux me charger d'ajouter quelques lignes sur les close, distant et scalable reading en évoquant peut-être quelques références - je préfère laisser datapoint de côté pour le moment, qjuitte à compléter après les relectures. Donc, si vous avez des précisions que vous souhaitez ajouter sur la traduction, n'hésitez pas à me les faire parvenir (par mail, par comentaire ici, ou par comentaire dans le fichier), que ce soit avant ou après les relectures et selon votre convenance. Dans tous les cas, vous pourrez vérifier à la fin et solliciter des modifications si vous le souhaitez. 

Merci aussi pour la cession des droits.

**Comment by spapastamkou** [comment]
@tiagosousagarcia @drjwbaker I think @annelaure-blog and I are done here. We are very happy with the translation and if you have further things to check between you, please go on. Thank you very much all three for your work!

**Comment by annelaure-blog** [comment]
Thank you all. Just to inform you that I have sent you @tiagosousagarcia and @spapastamkou an email request for a recommandation on the freelance platform Malt which I sometimes use to find technical writing and translation projects. That is of course totally up to you if you feel like writing me a recommandation or not (it helps with visibility and profile strenght). I thank you in advance anyway and I remain available to follow up with the translation until publication.

**Comment by tiagosousagarcia** [comment]
Hello all -- just a quick note to say that this is my last week working for PH. It's been an absolute pleasure working on this: big thanks to @annelaure-blog who translated this tutorial, @spapastamkou who is taking it forward, and @maxodsbjerg and the rest of the authors of the original article. Well done everyone!

**Comment by spapastamkou** [comment]
@HuguesPecout sera le premier évaluateur de la traduction de cette leçon. Nous nous sommes fixé un délai pour la fin novembre que nous pourrons revoir si besoin. Merci, Hugues!

**Comment by spapastamkou** [comment]
Je viens de travailler sur la syntaxe markdown et maintenant les images de la leçon, ainsi que les notes, apparaissent normalement dans la prévisualisation. Aussi, j'ai traduit la légende de la 2e image mais pas les deux autres (pour le moment) - je me permettrai de demander l'avis de la traductrice de la leçon lorsque nous aurons achevé les relectures. La leçon est entièrement prête à être relue.

**Comment by spapastamkou** [comment]
Pour documenter et suivre: l'équipe ES soulève quelques soucis avec les images dans le cadre de [ce ticket ](https://github.com/programminghistorian/jekyll/issues/2707)sur jekyll

**Comment by rivaquiroga** [comment]
(Désolé, mais je ne parle pas très bien le français :broken_heart:).
Pour la traduction à l'espagnol on a recréé les graphiques pour pouvoir traduire le titre et les légendes. Voici le code au cas où vous voudriez les traduire aussi.

:page_facing_up: [replicate-figures.txt](https://github.com/programminghistorian/ph-submissions/files/9823979/replicate-figures.txt)

(Vous devez changer l'extension du fichier parce que GitHub ne permet pas les fichiers .R)

**Comment by spapastamkou** [comment]
Thanks so much @rivaquiroga! I was wondering if it was possible to do this, and it is so great to have the answer without even asking:-) I might write you when I am on this to be sure FR images are harmonized with the ES ones. Thanks again!

**Comment by spapastamkou** [comment]
Je dépose ici le lien vers la leçon originale en anglais pour faciliter les relecteurs: https://programminghistorian.org/en/lessons/scalable-reading-of-structured-data
(merci du rappel @HuguesPecout)

**Comment by spapastamkou** [comment]
J'en profite pour introduire aussi le 2e relecteur qui est: @tsoubiran

**Comment by spapastamkou** [comment]
A faire: mettre à jour le texte de la leçon en tenant compte des modifications faites dans l'original https://github.com/programminghistorian/jekyll/pull/2731

**Comment by anisa-hawes** [comment]
Bonjour à tous,

J'ai actualisé [Scalable Reading of Structured Data](https://github.com/programminghistorian/jekyll/pull/2731).

La discussion a été compliquée... donc je pense que la meilleure approche sera d'examiner la ['rich-diff'](https://github.com/programminghistorian/jekyll/pull/2731/files).

Anisa

**Comment by spapastamkou** [comment]
Thanks @anisa-hawes, I should be able to work on this this weekend - perhaps I will ask for confirmation/review of the commit if necessary.

**Comment by drjwbaker** [comment]
Is this ticket dormant?

**Comment by spapastamkou** [comment]
@drjwbaker We had exchanges with the translations reviewers by email around the initial date they had to submit their reviews; it is me who had not updated the issue. Both suggested that the translation had to be further aligned to the terminology that is used in the francophone literature especially for data analysis in the social science and humanities. They are not available before mid-March, and I will have an updated version of the translation to propose by then. I've been working on this locally but did not have much bandwidth until... quite soon.

**Comment by spapastamkou** [comment]
Tenir aussi compte de: https://github.com/programminghistorian/jekyll/issues/2848

**Comment by drjwbaker** [comment]
Thanks for the update @spapastamkou. No huge hurry!

**Comment by marie-flesch** [comment]
This lesson has been in limbo for more than a year, mostly due to the fact that it's no longer possible to extract data from Twitter for free. I have discussed the issue with the French team, and with @anisa-hawes . I have decided to adapt the lesson, using an existing dataset of tweets ([Présidentielle2017](https://www.ortolang.fr/market/corpora/corpus-presidentielle2017), available on Ortolang). This will entail making significant changes to the original, both in terms of the structure of the lesson and research questions. I am setting myself a deadline of 3 months, and will propose a new version by September 12th.

**Comment by marie-flesch** [comment]
Je ferme cet ticket, car j'en ai ouvert un nouveau (#622), qui sera consacré à la nouvelle version de la traduction.
