### ISSUE TITLE
Traducción: Scalable Reading of Structured Data

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#484]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

The Programming Historian en español ha recibido la siguiente propuesta de traducción: [Scalable Reading of Structured Data](https://github.com/programminghistorian/ph-submissions/issues/419). Esta traducción se encuentra en estos momentos en fase de traducción por @nllano.

**Comment by nllano** [comment]
¡Hola! Me asigné la traducción, para luego montar el draft traducido. 

@rivaquiroga Vi que los comentarios finales de Anisa aún no fueron respondidos, así que podemos a esperar a que la discusión termine para subir el draft de la traducción, ¿te parece?

¡Abrazos!

**Comment by rivaquiroga** [comment]
Sí, mejor esperar para tener claro cuál es la versión final que publicarán. ¡Muchas gracias!

**Comment by nllano** [comment]
¡Hola @rivaquiroga ! Estoy siguiendo la discusión de la lección original. Max ya respondió, solo falta que Anisa revise los ajustes y ya quedaría lista la lección original. 

Apenas eso ocurra, revisamos el tema de la captura de nuevos datos o traducción de los original, y le hago los ajustes a la traducción para subir el draft inicial. ¿Te parece?

**Comment by rivaquiroga** [comment]
@nllano, sí, perfecto. Todo indica que queda poco para poder comenzar el proceso de edición :crossed_fingers:

**Comment by anisa-hawes** [comment]
Hello @nllano, 

I hope you're well?

Just to let you know that EN [Scalable Reading of Structured Data has been published today](https://programminghistorian.org/en/lessons/scalable-reading-of-structured-data)!

**Comment by nllano** [comment]
Hi @anisa-hawes
I am doing great, thanks. Hope you're too.

Yeah! Congrats to the authors, editors, and the whole team. It's such a great lesson.
I am working on the last revision of the translation —with Riva's help— before uploading the draft files. 
I think I'll have everything ready next week.

Thanks!

**Comment by anisa-hawes** [comment]
Super! Let me know if I can help with anything 🙂

**Comment by rivaquiroga** [comment]
¡Hola @jamotilla! 
@nllano tiene prácticamente lista la traducción. Sin embargo, en el proceso identificamos algunos problemas con las figuras incluidas en el tutorial, que están descritos en este issue: https://github.com/programminghistorian/jekyll/issues/2707. Lo relativo a las figuras 1 y 2 es algo que podemos resolver por nuestra cuenta, pero en el caso de la figura 3 se necesita una respuesta por parte de los autores. Como no sabemos cuánto tiempo tomará eso, es necesario que decidamos qué hacer. Una opción es traducir la lección tal como está ahora y cuando haya respuesta modificamos el texto. La otra opción es eliminar la oración que causa confusión para que sea más fácil la revisión externa y luego editar el texto cuando sepamos a qué se referían los autores:

> ~~The visualisation looks a lot like the previous bar charts, but the difference here is facet_wrap, which creates three bar charts for each type of interaction.~~ The graph illustrates that tweets from verified accounts gets more attention than tweets from non-verified accounts.

¿Qué opción les parece mejor?

**Comment by nllano** [comment]
¡Hola @rivaquiroga y @jamotilla!

¿Cómo están? A mí me parece mejor la segunda opción —eliminar la oración y luego editar el texto.
Riva, gracias por la recreación de los gráficos y por abrir el issue :)

¡Un abrazo!

**Comment by jamotilla** [comment]
Hola @rivaquiroga y @nllano! Coincido con @nllano creo que la segunda opción nos puede funcionar. 

Saludos, JA

**Comment by anisa-hawes** [comment]
Hola,

Just a note to say that we are in touch with the authors and they are helping us by solving the [issues you've noted during the course of translation](https://github.com/programminghistorian/jekyll/issues/2707#issue-1412322494). They're also recreating the EN images for us, as I noted some inconsistencies with the titles and labelling. 

I'll update you here when we have a clearer timetable of when the updates will be ready.

A.

**Comment by nllano** [comment]
¡Hola @anisa-hawes!

That is great, thanks for the update :)

**Comment by rivaquiroga** [comment]
¡Hola! En este pull request está siendo actualizada la lección en inglés. Para que le den una mirada cuando esté listo para saber qué modificaciones se hicieron (sobre todo lo relativo al tercer gráfico): https://github.com/programminghistorian/jekyll/pull/2731

**Comment by anisa-hawes** [comment]
Thank you for updating your team, @rivaquiroga. I'm just writing to the authors again because I don't think these changes satisfy all of the suggestions made. I'll let you know asap.

**Comment by nllano** [comment]
Thanks, @anisa-hawes, and @rivaquiroga! I'll keep an eye on the editing process.

**Comment by anisa-hawes** [comment]
Hola @nllano. 

Just to let you know that [the updates to Scalable Reading of Structured Data are now merged in](https://github.com/programminghistorian/jekyll/pull/2731).

Best,
Anisa

**Comment by nllano** [comment]
Hola @anisa-hawes!

Great, thank you for the heads up.
I'll revise the final adjustments this weekend and upload the translation in order to move on to the editing phase. 

Best, 
Nico

**Comment by anisa-hawes** [comment]
Thank you, @nllano. I realise that the Issue is very long, and a little difficult to follow... so maybe the best approach is to review the individual changes [in the rich-diff](https://github.com/programminghistorian/jekyll/pull/2731/files).

**Comment by nllano** [comment]
That is a great recommendation, @anisa! I'll do that. 
Thanks!

**Comment by nllano** [comment]
¡Hola, @jamotilla!

¿Cómo vas? Espero que todo bien.
Finalmente llegó el momento de subir la versión inicial de la traducción de esta lección. 

El archivo está aqui: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/lectura-escalable-de-datos-estructurados.md

Sobre las imágenes. Riva nos ayudó recreando los gráficos, pero no estoy seguro si ya están en la carpeta correspondiente. Voy a preguntarle y te actualizo. 

Muchas gracias por la paciencia y disposición.
Cualquier duda o comentario estoy por aquí.

¡Un abrazo y seguimos!

**Comment by jamotilla** [comment]
Hola @nllano! Qué buena noticia! Comenzaré con la revisión de la traducción

**Comment by rivaquiroga** [comment]
¡Hola! Las imágenes actualizadas ya están en la carpeta correspondiente. 
@jamotilla, habría que abrir un issue nuevo con el mensaje inicial y cerrar este que era solo para avisar que la traducción estaba en curso.

**Comment by nllano** [comment]
@rivaquiroga ¡gracias por tu ayuda con las imágenes!
@jamotilla quedo a disposición para resolver/discutir cualquier cosa.

**Comment by drjwbaker** [comment]
Is this ticket dormant?

**Comment by rivaquiroga** [comment]
We are waiting for @jamotilla's review

**Comment by jenniferisasi** [comment]
As this is being reviewed in issue #541 I am going to close this ticket to avoid double channels
