### ISSUE TITLE
Traducción: Creating Deep Neural Networks for Regression Analysis Proposal (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#485]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

The Programming Historian en español ha recibido la siguiente propuesta de traducción: [Creating Deep Neural Networks for Regression Analysis Proposal](https://github.com/programminghistorian/ph-submissions/issues/414).

**Comment by jenniferisasi** [comment]
@rivaquiroga perdón que te moleste pero no veo indicación alguna sobre esta lección en el panel de proyectos en `jekyll` ni más información aquí, ¿sabes algo?

**Comment by rivaquiroga** [comment]
Olvidé agregarla al panel de proyectos :roll_eyes: 
Es una traducción para la que se supone hay financiamiento comprometido del proyecto JISC/TNA. En principio, la idea era que Nico Llano la tradujera una vez que terminara con la lección sobre rtweet.

**Comment by jenniferisasi** [comment]
Perfecto @rivaquiroga! Me imaginé que era de JISC/TNA porque fue Tiago quien abrió el ticket pero al no ver más actividad ni nada me quedé algo perdida :) 

Y como no pasa nada por preguntar: @nllano hiciste algo con esto? Por ponernos todos al día, gracias!!

**Comment by nllano** [comment]
¡Hola Jenn!

Todavía no hice nada..  pero aún quiero traducirla. 

Estoy trabajando en la revisión de una lección original y en la traducción (al portugués) de la segunda parte de la lección sobre TEI de Nicolás Vaughn. Luego que termine esas dos actividades retomo esta, ¿puede ser?

**Comment by jenniferisasi** [comment]
¡Gracias @nllano! Sí, claro, no hay problema por nuestra parte en esperar a que termines las que mencionas. Quería saber más que nada en qué punto estábamos porque había quedado el ticket abierto pero vacío :)

**Comment by rivaquiroga** [comment]
Por si acaso, la lección original no está publicada aún, así que tampoco podrías haber avanzado, @nllano :wink:

**Comment by nllano** [comment]
Sí, difícil comenzar sin tener la lección original publicada, jeje. 
Acabo de revisar la issue de la original y ya está casi lista para publicación. Así que los tiempos se están alineando 👍

**Comment by jenniferisasi** [comment]
¡Buenas! Vuelvo a pasar por aquí, ahora que la lección sí está publicada [https://programminghistorian.org/en/lessons/image-classification-neural-networks](https://programminghistorian.org/en/lessons/image-classification-neural-networks) @nllano ¿qué te parece?

**Comment by nllano** [comment]
¡Hola, @jenniferisasi! Qué bien. Aún estoy muy interesado en traducirla. Lo único es que necesitaría un plazo más extenso (hasta final de año) para poder entregarla. ¿Crees que sería posible?

**Comment by jenniferisasi** [comment]
Por mí no hay ningún problema, @nllano. Voy a preguntar a Anisa por privado por si hay algún plazo determinado y así, pero yo no le veo problema.

**Comment by jenniferisasi** [comment]
I am going to close this issue because the discussion has been inactive for a while and the draft is not in yet. We are more than happy to opening the issue back in the future. 

[Message in English for admin purposes @anisa-hawes and @charlottejmc ]

**Comment by jenniferisasi** [comment]
I am going to close this issue because the discussion has been inactive for a while and the draft is not in yet. We are more than happy to opening the issue back in the future. 

[Message in English for admin purposes @anisa-hawes and @charlottejmc ]
