### ISSUE TITLE
Traducción: Creación de aplicaciones web interactivas con R y Shiny (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#486]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

Previsualización: [https://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/creacion-de-aplicacion-shiny](https://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/creacion-de-aplicacion-shiny) 

The Programming Historian en español ha recibido la siguiente propuesta de traducción: [Building Interactive Applications with R and Shiny (PH/JISC/TNA)](https://github.com/programminghistorian/ph-submissions/issues/416).

**Comment by jenniferisasi** [comment]
Pending confirmation by @anisa-hawes that the lesson is completely ready, I am starting to draft a translation. 

@rivaquiroga, how are we going to proceed with this? Who is acting as editor?

**Comment by rivaquiroga** [comment]
Anisa está fuera hasta inicios de septiembre, pero se ve que la lección está lista porque ya pasó la revisión de estilo y se archivaron los enlaces. Así que no debería haber más modificaciones. 
Entre hoy y mañana enviaré un correo al @programminghistorian/spanish-team porque con esta son dos traducciones en busca de editor/a.

**Comment by jenniferisasi** [comment]
Primera nota: No he podido instalar `sf` directamente ... estoy poniendo algo con Homebrew que igual lo soluciona, pero no me huele bien para nuestros usuarios.

**Comment by jenniferisasi** [comment]
Parece que está solucionado el problema :) Continúo con la traducción.

**Comment by drjwbaker** [comment]
How is this translation progressing @jenniferisasi?

**Comment by jenniferisasi** [comment]
Hi @drjwbaker! Now that the lesson has been published I am continuing to translate and I have the core translation almost done; I am attempting a complete adaptation-translation so it is taking a little bit longer as I had to do a lot of data wrangling for the data set. Of course the semester got busier now, but I am trying to get it done as soon as I can

**Comment by jenniferisasi** [comment]
@rivaquiroga casi tengo la lección ya preparada (aunque me gustaría ampliar el final con tu ayuda si es que entiendes de Shiny) ¿cómo estamos de disponibilidad de editores?

**Comment by rivaquiroga** [comment]
Tantearemos disponibilidades!
Claro, cualquier duda sobre Shiny, me avisas

**Comment by jenniferisasi** [comment]
@rivaquiroga y @isag91 ya he subido los archivos de la lección, los datasets y las figuras en sus correspondientes carpetas. Quedo a la espera de iniciar el proceso de revisión. 

@rivaquiroga te quería preguntar si piensas que, mediante tu conocimiento, no deberíamos de añadir al código final las líneas de código que se propone añadir como "expansión" de la aplicación al final... no está en el original pero imagino que para alguien no bilingüe sea complicado de descifrar todo eso

**Comment by jenniferisasi** [comment]
> How is this translation progressing @jenniferisasi?

Hi @drjwbaker! This is now submitted to go through the peer-review process.

**Comment by rivaquiroga** [comment]
Sería buenísimo. En ese caso, en el código final se podría agregar un comentario en esas partes diciendo que esas líneas de código corresponden a las propuestas de mejora. O bien, dejar el código tal como está y agregar un enlace a la versión que incluye las tres posibles mejoras propuestas para quienes quieran explorar esas opciones.

**Comment by rivaquiroga** [comment]
(¡Me gusta mucho el ejemplo para la versión en español!)

**Comment by jenniferisasi** [comment]
> Sería buenísimo. En ese caso, en el código final se podría agregar un comentario en esas partes diciendo que esas líneas de código corresponden a las propuestas de mejora. O bien, dejar el código tal como está y agregar un enlace a la versión que incluye las tres posibles mejoras propuestas para quienes quieran explorar esas opciones.

¡Gracias! Sabía que te parecería bien :) Cuando tenga un ratito la semana que viene, desde Argentina, trataré de crear yo el código y si me atasco te pediré ayuda. Me gusta la idea de ponerlo simplemente en el "código completo" con un comentario con los #  y ya.

**Comment by jenniferisasi** [comment]
@rivaquiroga te voy avisando, no me salen los extras 🥹 😆

**Comment by rivaquiroga** [comment]
@jenniferisasi, quedo atenta!
Estoy en los días finales del semestre, pero a mediados de la próxima semana ya debería tener más disponibilidad para apoyar en esto

**Comment by isag91** [comment]
Hola @rivaquiroga  y @jenniferisasi,
¿Estamos listos para empezar el proceso de revisión o mejor esperamos al código adicional?

**Comment by jenniferisasi** [comment]
Hola @isag91
Creo que es más una decisión de @rivaquiroga como manager, pero a mi parecer se podría iniciar el proceso de revisión, ya que el código adicional es extra y no va a cambiar nada.

**Comment by rivaquiroga** [comment]
¡Hola! Disculpen, pero entre tanta notificación se me pasó este mensaje. Me parece que se podría iniciar el proceso de revisión ya que, como dice Jenn, el código extra no cambiará nada vinculado a la traducción.

**Comment by isag91** [comment]
La revisión está en proceso en el ticket #542 entonces cierro este.
