### ISSUE TITLE
Tradução da lição: Building Interactive Applications with R and Shiny (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#488]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

O Programming Historian em português recebeu uma proposta de tradução da lição [Building Interactive Applications with R and Shiny (PH/JISC/TNA)](https://github.com/programminghistorian/ph-submissions/issues/416). Actualmente, a lição original ainda está a seguir o processo editorial. Assim que este terminar serão apontados um editor e um tradutor, e a lição traduzida seguirá o normal percurso editorial.

**Comment by drjwbaker** [comment]
@aracele to complete translation once https://github.com/programminghistorian/ph-submissions/issues/416 is ready. Approximate 2 week timeline for translation.

**Comment by drjwbaker** [comment]
@aracele Looking at https://github.com/programminghistorian/ph-submissions/issues/416, I believe this is now ready to translate (@jenniferisasi has started an ES version at https://github.com/programminghistorian/ph-submissions/issues/486)

**Comment by jenniferisasi** [comment]
Hi all! I wanted to leave a note here warning that while translating the lesson #486 , I encountered an issue with installing `sf` package. The author is aware and we are seeing to fixing it (hopefully)

https://github.com/programminghistorian/ph-submissions/issues/416#issuecomment-1227267198

**Comment by aracele** [comment]
> @aracele Looking at #416, I believe this is now ready to translate (@jenniferisasi has started an ES version at #486)

Thank you @drjwbaker! I've already started the translation.

**Comment by aracele** [comment]
> Hi all! I wanted to leave a note here warning that while translating the lesson #486 , I encountered an issue with installing `sf` package. The author is aware and we are seeing to fixing it (hopefully)
> 
> [#416 (comment)](https://github.com/programminghistorian/ph-submissions/issues/416#issuecomment-1227267198)

Thank you for the note! I'm using GNU/Linux and here it worked. No problem for now.

**Comment by aracele** [comment]
> @aracele to complete translation once #416 is ready. Approximate 2 week timeline for translation.

It's done @drjwbaker! Now I'm waiting for more instructions from the Portuguese editor. 

https://github.com/programminghistorian/ph-submissions/commit/028fa2e12ef55c6f5e9f149e51f42ac7eeb6e0c0

**Comment by DanielAlvesLABDH** [comment]
Hi to all and sorry for the long silence. I will start the review process for the translation of this lesson made by @aracele. Thank you for this Aracele!

**Comment by anisa-hawes** [comment]
Hello @DanielAlvesLABDH. Shall we close this Issue now that you are working in #513?

As part of a reorganisation of the /pt directory, this lesson's .md file has been moved to: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/aplicacao-web-interativa-r-shiny-leaflet.md

The lesson preview is available here: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/aplicacao-web-interativa-r-shiny-leaflet

**Comment by DanielAlvesLABDH** [comment]
A revisão desta tradução está a ser feita aqui: https://github.com/programminghistorian/ph-submissions/issues/513
Vamos fechar este ticket. Obrigado @anisa-hawes
