### ISSUE TITLE
Tradução da lição: AI for automated transcription of Historical Documents (PH/TNA/JISC)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#489]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

O Programming Historian em português recebeu uma proposta de tradução da lição [AI for automated transcription of Historical Documents (PH/TNA/JISC)](https://github.com/programminghistorian/ph-submissions/issues/421). Actualmente, a lição original ainda está a seguir o processo editorial. Assim que este terminar serão apontados um editor e um tradutor, e a lição traduzida seguirá o normal percurso editorial.

**Comment by anisa-hawes** [comment]
When this submission is received, please add the .md file to this location: /ph-submissions/pt/esbocos/traducoes/

Thank you, Anisa

**Comment by DanielAlvesLABDH** [comment]
This translation is now being revised in https://github.com/programminghistorian/ph-submissions/issues/559
