### ISSUE TITLE
Review Ticket for 'Salida de datos como archivo HTML con Python' - Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#49]
The Programming Historian has received the following translation on 'Salida de datos como archivo HTML con Python' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/salida-de-datos-como-archivo-html

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by mariajoafana** [comment]
Líneas 22-23: arreglar enlace 
Línea 31: corregir "python-es-lecciones6"
Línea 35: añadir tilde a "cómo empotrar"
Línea 39: segundo renglón, corregir "concpeto"
Línea 41: tercer renglón, corregir "qeu"
Línea 87: corregir en segunda oración "fución"

**Comment by vgayolrs** [comment]
Dear @mariajoafana I have corrected almost everything but I do not understand the sign of line 31.
I just downloaded the zip file and it's correct. I think it corresponds exactly with the [original lesson](http://programminghistorian.org/lessons/output-data-as-html-file) (except renaming zip files). Could you clarify what the correction would be? Thank you in advance!

**Comment by mariajoafana** [comment]
Ahh ok, I thought that the 6 was a typo!

**Comment by arojascastro** [comment]
- L 30: python-es-lecciones6 --> italics?
- L 34: empotrar --> ?
- L 40: aprender a tomar ventaja de algunas opciones --> "tomar ventaja" me suena a "take advantage"... por qué no simplemente "aprender algunas opciones" etc.
- L 44: shell --> *shell* (italics)
- L 69: i.e. 3.023, 4.59, 1.0 --> por ejemplo 3.023, 4.59, 1.0 (en México usáis puntos para separar o comas?)
- L 90: seguna línea --> segunda línea
- L 190: Toma en cuenta --> una expresión distinta?
- L 190:  útlima sección -->  última sección

**Comment by vgayolrs** [comment]
Thanks @arojascastro 
About your question about decimal mark uses, we use decimal point. Perhaps this could be useful: https://en.wikipedia.org/wiki/Decimal_mark
Everythin done @acrymble

**Comment by acrymble** [comment]
translation reviewers added. now published.
