### ISSUE TITLE
Translation proposal: Sumarização de narrativas acerca de eventos do passado documentados na web utilizando Python: o caso do Arquivo.pt (PH/JISC/TNA)

### ISSUE THREAD

**Issue by tiagosousagarcia** [programminghistorian/ph-submissions#490]
> This ticket was opened in advance of submission in order to allow editors to adequately allocate resources for the translations coming out of the PH/TNA/JISC partnership

The Programming Historian has received a proposal to translate ["Sumarização de narrativas acerca de eventos do passado documentados na web utilizando Python: o caso do Arquivo.pt (PH/JISC/TNA)"](https://github.com/programminghistorian/ph-submissions/issues/420) into English. The original article is still going through its normal editorial process, at the end of which an editor and translator into English will be appointed.

**Comment by hawc2** [comment]
@tiagosousagarcia when do you expect this lesson would be translated?

**Comment by hawc2** [comment]
@drjwbaker who is handling this translation now, until it is assigned editor?

**Comment by drjwbaker** [comment]
@hawc2  Nobody at the moment. When Tiago left the project we had yet to receive confirmation that the EN team had the processes in place to receive an incoming translation. As for the translation itself, we have project budget for this. So the primary duties of the editor would be to work from the point of translation onwards.

As a site note, the authors of the original PT article are keen to see an EN translation (and they may wish to write it themselves).

**Comment by hawc2** [comment]
@drjwbaker a few of us will be meeting soon to discuss the English journal doing more translations, learning from how the other journals do it and improving our documentation for editors of translations. We'll be publishing our first translation soon, and we're aiming to do more translations in the coming year. 

So we can proceed with identifying translators interested in authoring this lesson in English,. By the time it's ready for review the English team should be ready to edit it.

**Comment by anisa-hawes** [comment]
This translation has not yet started. [When we receive the a first draft]( https://github.com/programminghistorian/ph-submissions/issues/487#issuecomment-1289523329), @hawc2 will assign an editor, who will open a new Issue and signal that the editorial process has begun.
