### ISSUE TITLE
Review Ticket for 'Palabras clave en contexto (usando n-grams) con Python' - Spanish translation

### ISSUE THREAD

**Issue by acrymble** [programminghistorian/ph-submissions#50]
The Programming Historian has received the following translation on 'Palabras clave en contexto (usando n-grams) con Python' by @vgayolrs . This lesson is now under review and can be read at:

http://programminghistorian.org/es/lecciones/palabras-clave-en-contexto-n-grams

I will act as editor for the review process. My role is to manage the discussions between the reviewers ( @arojascastro and @mariajoafana) and the author ( @vgayolrs ), which should be held here on this forum.

We ask that reviewers consider the clarity of the language with an international Spanish-speaking reader in mind. We recognise that there are many dialects of Spanish and that all are correct in their own cultural contexts. We encourage authors to use their own dialect when translating (keeping broad user needs in mind). We therefore ask that words or phrases are only changed from the suggested terms when it would impede understanding for a Spanish-speaker from another part of the world. For the sake of clarity, the author has written the translation from the perspective of a Mexican Spanish speaker.

I will endeavor to keep the conversation open here on Github. If anyone feels the need to discuss anything privately, you are welcome to email me. You can always turn to @ianmilligan1 or @amandavisconti if you feel there's a need for an ombudsperson to step in.

Anti-Harassment Policy
_

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudsperson ( @ianmilligan1 or @amandavisconti - http://programminghistorian.org/project-team). Thank you for helping us to create a safe space.

**Comment by mariajoafana** [comment]
This one looks good.

**Comment by vgayolrs** [comment]
Thank you @mariajoafana !

**Comment by arojascastro** [comment]
- L 36: Ahora que ya sabes cómo cosechar el contenido textual de una página Web --> cosechar? qué quieres decir? 
- L 38: de en qué lugar --> del lugar en que
- L 118: wordlist --> *wordlist* (italics)

**Comment by vgayolrs** [comment]
¡Gracias @arojascastro ! Destaco que L-118 cambió a `listaPalabras` porque hace referencia al fragmento de código anterior.
Done @acrymble

**Comment by acrymble** [comment]
translation reviewers added. published.
