### ISSUE TITLE
Proposition de leçon: Traiter un corpus de documents et gérer un projet de transcription automatique à l'aide d'eScriptorium

### ISSUE THREAD

**Issue by spapastamkou** [programminghistorian/ph-submissions#515]
Le Programming Historian en français a reçu la proposition suivante pour une leçon organisée autour de deux parties (deux leçons associées) intitulées: 
- "Traiter un corpus de documents à l'aide de la transcription automatique avec eScriptorium (I)"
- "Gérer un projet de transcription automatique à l'aide d'eScriptorium (II)"  
   
La proposition a été formulée de la part de: @alix-tz et @HugoSchtr  

Les principaux objectifs pédagogiques sont les suivants: 
- offrir une introduction à la transcription automatique et l'application eScriptorium
- initier à la création manuelle de données d'entraînement pour produire des modèles
- obtenir des connaissances sur l'entraînement et l'application de modèles de segmentation et de transcription avec eScriptorium

Concernant le dépôt de cette leçon: nous sommes en contact avec les auteurs depuis cet été et la livraison d'une première version était estimée pour cet automne - à voir si le délai habituel de 3 mois n'est pas revu à la baisse étant donné l'ouverture décalée de ce ticket.

**Comment by spapastamkou** [comment]
J'assigne temporairement ce ticket à moi et Matthias le temps de recevoir les leçons et assigner par la suite un ou plusieurs rédacteurs.

**Comment by spapastamkou** [comment]
@alix-tz @HugoSchtr Je réitère ici, pour en garder la trace, une préoccupation abordée lors de nos échanges concernant la place qu'auraient dans la leçon (première partie) les instructions pour l'installation en local de l'application. Nous aurons sans doute l'occasion d'en parler plus dans l'avenir, mais même si des instructions extrêmement détaillées ne peuvent pas être attendues (pour éviter l'allonger la leçon), il serait peut-être possible d'envisager de non pas seulement renvoyer le lectorat vers les instructions afférentes disponibles sur le dépôt github d'eS, mais d'orienter de manière même basique sur par exemple des problèmes auxquels un novice peut faire face, ou des cas avérés de difficultés (s'il y en a qui sont connus) et les solutions éventuelles... Bref, faciliter un peu de franchir la barrière technique, même si la leçon ne pourra pas tourner autour de cela? Merci à vous deux et à bientôt.

**Comment by spapastamkou** [comment]
@matgille sera en charge du suivi éditorial de cette leçon, merci à toi!

**Comment by alix-tz** [comment]
> @alix-tz @HugoSchtr Je réitère ici, pour en garder la trace, une préoccupation abordée lors de nos échanges concernant la place qu'auraient dans la leçon (première partie) les instructions pour l'installation en local de l'application. Nous aurons sans doute l'occasion d'en parler plus dans l'avenir, mais même si des instructions extrêmement détaillées ne peuvent pas être attendues (pour éviter l'allonger la leçon), il serait peut-être possible d'envisager de non pas seulement renvoyer le lectorat vers les instructions afférentes disponibles sur le dépôt github d'eS, mais d'orienter de manière même basique sur par exemple des problèmes auxquels un novice peut faire face, ou des cas avérés de difficultés (s'il y en a qui sont connus) et les solutions éventuelles... Bref, faciliter un peu de franchir la barrière technique, même si la leçon ne pourra pas tourner autour de cela? Merci à vous deux et à bientôt.

C'est bien noté pour l'idée de donner des pistes pour mieux comprendre comment faire l'installation ou au moins savoir par où commencer. 

On a pris du retard sur la rédaction car on a tous les deux été pas mal occupés, mais ça s'en vient !

**Comment by spapastamkou** [comment]
merci @alix-tz !

**Comment by marie-flesch** [comment]
Je ferme ce ticket qui dort depuis près d'un an. Il pourra être ré-ouvert sur demande des auteurices, s'iels souhaitent poursuivre le travail sur la leçon.
