### ISSUE TITLE
Review Ticket for 'Lessons Translations List'

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#52]
The list may be found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md

Can we add a column for the 'Editor' in charge of the reviewing process and a second column for one more reviewer (if you agree it is needed)?

Thoughts?

**Comment by acrymble** [comment]
sounds important to me.

**Comment by vgayolrs** [comment]
Of course! Thats great. Let me work on a proposal directly in the file.

**Comment by vgayolrs** [comment]
Done! Please @arojascastro & @acrymble check this.
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/lista-de-traducciones.md
I included the designated revision editor and made changes that allow for better tracking of the process of all the lessons. All the reviewers are in the same column. Please let me know any questions or suggestions. Thank you!

**Comment by arojascastro** [comment]
I am happy with that.

**Comment by acrymble** [comment]
It looks good.

It would be a good idea to assign editors to each of the lessons so that there is a clear understanding of who will do what. Then everyone can plan their time.

**Comment by arojascastro** [comment]
Just a question about this: is this list publicly available without a GitHub account? I got an email from a potential collaborator and told me that she cannot get access.

**Comment by acrymble** [comment]
Should be.
