### ISSUE TITLE
Revisão da tradução da lição "Leitura escalável de dados estruturados"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#534]
O Programming Historian em português recebeu a proposta de tradução sobre 'Leitura escalável de dados estruturados' da tradutora @joanacvp. 

O ficheiro md pode ser encontrado aqui: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/leitura-escalavel-dados-estruturados.md

Eu (@DanielAlvesLABDH) serei o editor no processo de revisão. O meu papel é solicitar duas revisões da comunidade e gerir as discussões, que devem ser realizadas aqui neste fórum. Eu já li a lição e forneci feedback, ao qual o autor respondeu.

Os membros da comunidade em geral também são convidados a oferecer feedback construtivo que deve ser publicado neste canal, mas é solicitado que leiam primeiro as diretrizes para revisores e sigam a nossa política anti-assédio (abaixo). Pedimos que todas as revisões parem após o envio da segunda revisão formal para que o autor possa concentrar-se no ajuste da lição. Eu farei um anúncio neste tópico quando isso ocorrer.

Vou me esforçar para manter a conversa aberta aqui no GitHub, mas se alguém sentir a necessidade de discutir algo em particular, pode entrar em contato comigo, ou pode sempre recorrer para o nosso ombudsperson Luís Ferla se achar necessário.

Política anti-assédio

Esta é uma declaração de princípios do Programming Historian em português e define o tom e estilo de toda a comunicação entre revisores, autores, editores e participantes.
O Programming Historian em português dedica-se a criar um ambiente académico aberto em que os membros da comunidade podem examinar em liberdade e detalhadamente ideias, fazer perguntas, sugestões ou pedir esclarecimentos. Este espaço tem que ser livre de assédio para todos no projeto, independentemente do género, identidade e expressão de género, orientação sexual, deficiência, aparência física, raça, idade, religião ou experiência técnica. Não é tolerado qualquer assédio ou ataque ad hominem a membros da comunidade de nenhuma forma. Os membros que violarem estas regras podem ser expulsos da comunidade, por avaliação do conselho editorial. Se alguém testemunhar ou sentir que foi vítima das atividades descritas acima, entre em contato com o nosso ombudsperson Luís Ferla. Obrigado por nos ajudar a criar um espaço seguro.

**Comment by leofn** [comment]
Olá @DanielAlvesLABDH eu posso contribuir com a revisão. Abs.

**Comment by DanielAlvesLABDH** [comment]
Muito obrigado por ter aceite o convite para revisor desta tradução Leonardo @leofn. Como é costume, depois de revista, peço que coloque aqui os seus comentários e sugestões.
Já fiz um segundo convite. Estou à espera de resposta de um colega português.

**Comment by DanielAlvesLABDH** [comment]
O colega Alcides Seiça @Alcides62 aceitou fazer a segunda revisão desta tradução. Agradeço muito a sua colaboração e estou disponível para esclarecer qualquer dúvida que tenha.

**Comment by anisa-hawes** [comment]
Hello all,

Please note that as part of a reorganisation of the /pt directory, this lesson's .md file has been moved to a new location within our Submissions Repository. 

It is now found here: https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/leitura-escalavel-dados-estruturados.md

A consequence is that this lesson's preview link has changed. It is now: http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/leitura-escalavel-dados-estruturados

Please let me know if you encounter any difficulties or have any questions.
Very best,  Anisa

**Comment by Alcides62** [comment]
Good afternoon

Following the review process of the Tutorial "Scalable reading of
structured data", together with an MS Word document, with annotations and
comments to the original text.

Best regards


Em qui., 8 de dez. de 2022 às 18:36, Anisa Hawes ***@***.***>
escreveu:

**Comment by DanielAlvesLABDH** [comment]
Caro @Alcides62 obrigado pela revisão. Pedia-lhe o favor de colocar num destes comentários o que incluiu nesse Word de que fala. Não usamos ficheiros aqui, deixamos tudo como comentários aqui. Veja este exemplo: https://github.com/programminghistorian/ph-submissions/issues/516#issuecomment-1283860269

**Comment by Alcides62** [comment]
Olá a todos
Antes de mais queria parabenizar os Autores pelo excelente trabalho de tradução e agradecer o convite do Dr. Daniel Alves para colaborar na sua revisão.
De seguida, apresento algumas sugestões e comentários, enumerados de acordo com os respetivos parágrafos no texto original:

Parágrafo 4 – O hyperlink não funciona. Abre um site inexistente.

Parágrafo 9 – Alterar “…métodos computacionais e os métodos da curadoria manual…” para “métodos computacionais e os métodos personalizados”.

Parágrafo 16 – Alterar “…pode obter um das seguintes forma:” para “pode ser obtida por uma das seguintes formas:”.

Parágrafo 17 – Os hyperlinks não funcionam. Abrem sites inexistentes.

Parágrafo 18 – O hyperlink não funciona. Abre um site inexistente.

Parágrafo 20 – O hyperlink não funciona. Abre um site inexistente.

Parágrafo 27 – Alterar “Trar-lhe-á 18.000 tweets…” para “Ser-lhe-ão devolvidos 18.000 tweets…”.

Parágrafo 28 – O hyperlink não funciona. Abre um site inexistente.

Parágrafo 35 – O hyperlink não funciona. Abre um site inexistente.

Parágrafos 38 e 39 – Penso que pretende incluir estas linhas no script R anterior.

Parágrafo 41 – Alterar “…linhatipo=tem_sesame_ht…” para “…tipo_linha=tem_sesame_ht…”.

Parágrafo 45 – Alterar “…em quantos tweets fora retweets ou originais” para “…em quantos tweets foram retweets ou originais”.

Script R após parágrafo 48 – O objeto / variável "verified" não faz parte da lista de dados atualmente extraídos do Twitter. A única variável binária atual é "is_quote_status".
Parágrafo 49 – Alterar “Aqui ‘pour’ (em português, derrama) os dados para o comando count (em português, contagem) e pede que sejam contabilizados …” para “Aqui ‘despejamos’ os dados para o comando count (em português, contagem) e pedimos que sejam contabilizados …”.

Script R após parágrafo 50 – O objeto / variável "verified" não faz parte da lista de dados atualmente extraídos do Twitter. A única variável binária atual é "is_quote_status".

Script R após parágrafo 52 – O objeto / variável "verified" não faz parte da lista de dados atualmente extraídos do Twitter. A única variável binária atual é "is_quote_status".

Script R após parágrafo 53 – Uma vez que a variável "verified" não existe, sugiro que se utilize a variável "is_quote_status ". Também precisa de alterar as etiquetas (labels).

Script R após parágrafo 56 – Uma vez que a variável "verified" não existe, sugiro que se utilize a variável "is_quote_status ". 

Parágrafo 57 – Alterar “…em português, favorito_conta” para “…em português, conta_favoritos”.

Script R após parágrafo 58 – Uma vez que a variável "verified" não existe, sugiro que se utilize a variável "is_quote_status". 

Script R após parágrafo 59 – Uma vez que a variável "verified" não existe, sugiro que se utilize a variável "is_quote_status ". Na linha de código” interactions  %>% ggplot(aes(x = verified, y = mean)) +” penso que deve substituir “y = mean” por “y = gns”. O código corrigido seria:
interactions %>%
  add_row(
    sesamestreet_data %>%
    group_by(is_quote_status) %>%
    summarise(gns = mean(retweet_count), .groups = "drop") %>%
    mutate(interaction = "retweet_count")) -> interactions

interactions  %>%
    ggplot(aes(x = is_quote_status, y = gns)) +
    geom_col() +
    facet_wrap(~interaction, nrow = 1) +
    labs(caption = "Total number of tweets: 2411",
               x = "Lang",
               y = "Average of engagements counts") +
    scale_x_discrete()

Parágrafo 60 – Alterar “…que cria um gráfico de três barras…” para “…que cria um gráfico de duas barras…”.

Script R após parágrafo 69 – Uma vez que a variável "is_retweet" não existe, sugiro uma abordagem alternativa:
library(dplyr)
df2 <- sesamestreet_data[str_detect(sesamestreet_data$full_text, "RT @"), ]
df3 <- anti_join(sesamestreet_data, df2, by='id')
df3 %>% arrange(desc(favorite_count))

Script R após parágrafo 74 – Uma vez que a variável "is_retweet" não existe, e de acordo com a abordagem alternativa sugerida, temos:
df3 %>%
    filter(favorite_count > 50) %>%
    arrange(desc(favorite_count)) -> sesamestreet_data_favorite_count_over_50

Script R após parágrafo 75 – Uma vez que a variável "is_retweet" não existe, e de acordo com a abordagem alternativa sugerida, temos:
sesamestreet_data_favorite_count_over_50 %>%
    select(favorite_count, id, is_quote_status, full_text) %>%
    arrange(desc(favorite_count))

Parágrafo 79 – Alterar “Escolhemos o formato JSON porque os nossos dados do Twitter sã ocompexos…” para “Escolhemos o formato JSON porque os nossos dados do Twitter são complexos …”.

Script R após parágrafo 86 – Uma vez que a variável "is_retweet" não existe, e de acordo com a abordagem alternativa sugerida, temos:
df3 %>%
    filter(is_quote_status == FALSE) %>%
    arrange(desc(favorite_count))

Script R após parágrafo 90 – Uma vez que a variável "is_retweet" não existe, e de acordo com a abordagem alternativa sugerida, temos:
df3 %>%
    filter(is_quote_status == FALSE) %>%
    filter(favorite_count > 15) %>%
    arrange(desc(favorite_count)) -> sesamestreet_data_favorite_count_over_15_is_quote_status_False

Script R após parágrafo 92 – Uma vez que as variáveis “screen_name” e “verified” não existem, sugiro uma abordagem alternativa:
sesamestreet_data_favorite_count_over_15_is_quote_status_False %>%
    select(favorite_count, id, is_quote_status, full_text) %>%
    arrange(desc(favorite_count))

Parágrafo 97 – Alterar “…distante reading Pode ajudar a determinar se dados individuais …” para “…distante reading pode ajudar a determinar se dados individuais são representativos …”.

Parágrafo 97 – Alterar “A exploração cronológica pode ajudar a determina onde os tweets selecionados…” para “A exploração cronológica pode ajudar a determinar onde os tweets selecionados…”.

Parágrafo 99 – O hyperlink não funciona. Abre um site inexistente.

Cumprimentos
Alcides Seiça

**Comment by DanielAlvesLABDH** [comment]
Caro @Alcides62 muito obrigado pela revisão detalhada.

**Comment by leofn** [comment]
Olá @Alcides62 @DanielAlvesLABDH 

Preciso de mais alguns dias para poder revisar a lição.
Daniel, por favor, tem algum prazo ou é ASAP.

Abs

**Comment by DanielAlvesLABDH** [comment]
Olá @leofn não tem problema de forem mais uns dias. Eu é que agradeço a vossa colaboração. Abraço

**Comment by joanacvp** [comment]
Olá a todos. Antes de mais aproveito para desejar um bom ano!
Posso introduzir já as alterações sugeridas pelo @Alcides62 ou preferem que aguarde também pelas observações do @leofn e coloco tudo na mesma altura? Obrigada

**Comment by DanielAlvesLABDH** [comment]
Olá @leofn, tudo bom? Ainda tem disponibilidade para avançar com esta revisão? Obrigado

**Comment by leofn** [comment]
Olá @DanielAlvesLABDH eu me passei completamente. Farei isso essa semana. Abs

**Comment by DanielAlvesLABDH** [comment]
Obrigado @leofn. Andamos todos com demasiadas tarefas. Abraço

**Comment by DanielAlvesLABDH** [comment]
Olá @leofn, será que agora está com mais disponibilidade para esta revisão? Qualquer dúvida, é só dizer! Obrigado uma vez mais

**Comment by DanielAlvesLABDH** [comment]
Olá Leonardo @leofn, ainda tens disponibilidade para fazer a revisão desta tradução? Estamos muito atrasados face ao plano inicial. Se não for possível, não há problema e eu posso procurar outro colega. Abraço

**Comment by DanielAlvesLABDH** [comment]
Olá de novo Leonardo (@leofn), peço desculpa pela insistência, mas podemos avançar com a revisão? Precisas de mais tempo? Abraço

**Comment by leofn** [comment]
Opa Daniel, peço mil desculpas, eu achei que já tinha colocado aqui. Por favor, deixe eu encontrar e coloco.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @leofn

**Comment by DanielAlvesLABDH** [comment]
O Leonardo (@leofn) ficou de entregar a sua revisão até final de Novembro. Depois disso a @joanacvp poderá introduzir as correcções necessárias.

**Comment by joanacvp** [comment]
Muito obrigada! Fica combinado :) !

**Comment by ericbrasiln** [comment]
Olá @DanielAlvesLABDH Como vai?

Você pretende continuar como editor desta lição? 
Conversei com o Leonardo e ele não poderá realizar a revisão

Assim, precisamos encontrar outro revisor.

Qualquer coisa, me avise.
Abraços

**Comment by anisa-hawes** [comment]
Hello @ericbrasiln. There are some complexities to consider with this lesson, because it was written before Twitter/X limited access to the API. 

Speaking with Marie recently, we think a sensible approach could be an adaptation of the EN original lesson so that it centres an historical Twitter dataset which is available to researchers open access. @marie-flesch has an idea to propose! I know @jenniferisasi and @hawc2 would like to be part of this conversation too (there are translations in-progress in both FR and ES at the moment).

**Comment by ericbrasiln** [comment]
Thanks for the info, @anisa-hawes 
Is there an issue where we can follow this discussion?

**Comment by anisa-hawes** [comment]
Dear @ericbrasiln. I'll keep you updated. I don't yet have any further information on this possibility. I'd like to suggest we discuss the ideas at our next Managing Editors meeting and I can add that to the agenda. 

One option (also in discussion with @jenniferisasi and the ES team) is to move forwards to publication with the understanding that unfortunately the lesson will not work as the authors intended right from day 1. I feel this could be frustrating for readers, as well as very disappointing for all who have contributed here. We applied a warning box to the EN original, which could be translated and applied:

```
<div class="alert alert-warning">
Access to Twitter’s API has recently changed. The Free Tier no longer allows users to search and download Twitter data. Unfortunately, this means that elements of this lesson will only work for those who are paying for an upgraded plan. At the moment, there are no special access plans for researchers or academics.
</div>
``` 

I think our second option could be to initiate a collaborative effort to adapt the original lesson for use with a historical dataset (we could work with the original authors, one of the translators who has worked on the lesson, or someone else in our wider community). This would be a substantial piece of work, and would likely necessitate us assigning a new DOI to the original.

**Comment by ericbrasiln** [comment]
Olá @joanacvp 

O time francês está trabalhando em um update da lição original, que pode ser acompanhada aqui: #622 . Poderemos editar essa tradução para refletir essas mudanças no futuro. E por essa razão estamos fechando essa _issue_.
