### ISSUE TITLE
Évaluation de traduction: Reutilisation de code et modularite

### ISSUE THREAD

**Issue by marie-flesch** [programminghistorian/ph-submissions#539]
Le Programming Historian en français a reçu la traduction du tutoriel "[Code Reuse and Modularity in Python](https://programminghistorian.org/en/lessons/code-reuse-and-modularity)" sous le titre "Reutilisation de code et modularite" par @datalogism  (ticket de proposition: #456). Une prévisualisation du texte est disponible ici: https://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/reutilisation-de-code-et-modularite

J'ai sollicité une relecture auprès de @hschoi4 ; je vais assurer le suivi éditorial de cette traduction et coordonner les échanges qui auront lieu dans cet espace. La relectrice pourra utiliser la numérotation des paragraphes fournie dans l'aperçu pour signaler ses commentaires, si cela lui convient, mais elle a la liberté de faire comme elle jugera mieux. Nos relecteurs peuvent aussi s'appuyer sur les [consignes aux traducteurs et aux traductrices](https://programminghistorian.org/fr/consignes-traducteurs#traduire-une-le%C3%A7on-et-la-mettre-en-page). Nous pouvons prévoir un délai de 30 jours environ, qui peut néanmoins être adapté si besoin.

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos consignes aux évaluateurs et évaluatrices (https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de l'évaluation formelle, pour que le traducteur puisse travailler sur la révision de son texte. L'annonce sera faite sur ce fil quand cette étape aura été atteinte.

Idéalement, la discussion reste ouverte au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu), si vous avez le sentiment qu'une médiation est nécessaire.

## Politique contre le harcèlement
Vous trouverez ci-dessous les principes du Programming Historian en français qui doivent inspirer les échanges entre évaluateurs et évaluatrices, auteur(e)s, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le Programming Historian en français tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu). Cette prise de contact n'aura aucun impact négatif sur le résultat de l'évaluation. Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by hschoi4** [comment]
Merci pour cette traduction. L'ensemble est clair et plutôt bien rédigé. Mes corrections sont surtout des fautes de frappes/orthographe. Il y a seulement le paragraphe 8 qu'il faudrait revoir, je trouvais ça moins clair que le reste de la leçon. J'ai proposé une version plus condensée, peut-être trop simplifiée par rapport à l'original ?
C'est simplement une suggestion :). Voici mes corrections :

## Objectifs de la leçon

- $3 :
  - ligne 6 : "Pour illustrer cela observons un exemple" -> Pour illuster cela, (virgule)
  - ligne 7 : "Supposez" -> "Supposons" me semble plus naturel
  - ligne 8 : "Sauvegardez là" -> Sauvegardez-la

- $5 :
  - ligne 4 : "vérifier seulement" -> vérifiez
  - ligne 5 : "que celle que vous nous présentons" -> que nous vous présentons

- $6 :
  - ligne 2 : "celle-ci est "invoquée" " -> qu'elle est "invoquée" : répétition de "celle-ci" dans la même phrase
  - ligne 4 : "l'exemple précédemment évoqué" -> quel exemple ? dans un autre article ?
  De manière générale, je suis un peu perplexe avec cette analogie du chien et du snack, je ne vois pas trop où se trouve la comparaison. Même dans la version originale, je ne trouve pas ça clair. À voir si vous souhaitez le conserver...
  - ligne 5 : "abouie" -> aboie
  - ligne 7 : ~~"à la fin de celui-ci"~~

## Modularité

Pour le paragraphe 8, les phrases sont longues et les formulations gênent un peu dans la compréhension du texte. Le texte gagnerait en clarté si les phrases étaient plus courtes. Je propose des corrections sur le texte original et une version plus courte. Encore une fois, je ne sais pas le degré de liberté que nous avons sur la traduction, certaines remarques sont peut-être hors contexte :).

- $8 :
  - ligne 1 : "tout tiens" -> ~~tout~~ tient
  - ligne 2 : "Lorsque vous souhaitez lancer un de vos programmes, il vous suffit de le soumettre à l’interpréteur." -> je trouve que cette phrase n'a pas vraiment sa place à cet endroit du paragraphe
  - ligne 3-4 : "Mais quand un programme commence à devenir plus important en terme de nombre de lignes" -> Mais quand un programme contient un nombre important de lignes / Mais quand un programme devient trop long en termes de lignes / Quand un programme devient trop long
  - ligne 6 : "si stockez celui-ci" -> si vous le stockez
  - ligne 7 : "permet ~~alors~~ de travailler" : répétition avec le "En effet" en début de phrase
  - ligne 8 : "toutes ensembles" -> toutes ensemble
  - ligne 9 : "serrez" -> serez
  - ligne 10 : "sépare un programme en module" -> modules, "obligé" -> obligés
  - ligne 11 : "ré-écrire" -> réécrire ou récrire mais pas de tiret
  - ligne 13 : "tache" -> tâche, j'aurais plutôt utilisé un terme comme "fonctionnalité"

Version plus courte : 
> Les programmes courts comme dans l'exemple tiennent facilement dans un seul fichier. Lorsqu'un programme devient plus long, il est possible de le séparer en plusieurs fichiers appelés modules. Cette modularité/Cela permet de travailler plus facilement sur les différentes parties de votre code et de simplifier l'utilisation de chaque module dans d'autres programmes. Il est également plus simple de repérer les sources d'erreurs. Lorsque vous divisez un programme en modules, vous pouvez cacher la manière dont est codée une fonctionnalité dans un module. Les autres modules n'ont pas besoin de savoir comment elle est codée s'ils n'en sont pas responsables. Ce principe est appelé "l'encapsulation".


- $9 :
  - ligne 3 : "enviable" -> judicieux ?
  - ligne 4 : "avant ~~de~~ d’ajouter le reste"
  - ligne 9 : "résoudre ceux-ci" -> de les résoudre un à un

- $10 :
  - ligne 1 : "quand nous écrit" -> quand nous avons écrit

- $11 :
  - ligne 1 : "sauvegarder le" -> sauvegardez-le

**Comment by marie-flesch** [comment]
Merci @hschoi4 pour ta relecture attentive ! @datalogism, je n'ai sollicité qu'une seule évaluation pour cette traduction qui était courte et de bonne qualité. Donc, tu peux examiner les suggestions de Hee-Soo et intégrer celles qui te paraissent judicieuses.

**Comment by datalogism** [comment]
Hello, Je fais cela en fin de semaine, merci @hschoi4 pour ces retours

**Comment by datalogism** [comment]
Hello, @marie-flesch , je viens de prendre en compte les corrections de @hschoi4, concernant : 
* Objectif de la leçon :  l'exemple du chien et du snack, j'étais aussi assez sceptique je l'ai donc suprimé
* Modularité :  je modifié le paragraphe ainsi :
> Dans notre exemple, le programme est très court et tient naturellement dans un unique fichier. Mais quand un programme contient un nombre important de lignes, il sera alors judicieux de le séparer en plusieurs  fichiers appelés *modules*.  Cette modularité facilitera grandement la maintenance de votre code, qui ne serait pas aussi évidente si le stockez dans un grand fichier. En effet, cette méthode de travail permet de travailler de manière indépendante sur chaque partie de votre code avant de les faire tenir toutes ensemble. En utilisant des modules, vous ne simplifierez pas seulement la réutilisation de votre code. Vous serez notamment capable repérer plus facilement la source des erreurs de vos programmes.  Lorsque vous divisez un programme en modules, vous n'êtes plus obligés de réécrire le détail de chaque procédure que vous souhaitez utiliser. Les autres modules n'ont pas besoin de savoir comment elle est codée s'ils n'en sont pas responsables. Ce principe est appelé "l'encapsulation".

J'espère que cela est bon pour vous ! Merci à vous deux pour ce travail de relecture

**Comment by marie-flesch** [comment]
Merci @datalogism ! Je vais regarder tout ça.

**Comment by spapastamkou** [comment]
@marie-flesch Quand tu es prête, merci de faire signe à AH pour vérifier le markdown et intégrer les liens permacc ici aussi! (Nous aurons vraisemblablement trois publications à faire bientôt, nous allons devoir nous organiser avec @matgille peut-être?).

**Comment by marie-flesch** [comment]
@anisa-hawes this lesson is ready :) Could you check the markdown and create the permacc links? 
@matgille  je te laisse ensuite prendre le relais pour la mise en ligne de cette leçon !

**Comment by matgille** [comment]
@marie-flesch Noté, je prends en charge la leçon quand tout sera prêt = )

**Comment by anisa-hawes** [comment]
Thank you, @marie-flesch! 

I will make time for this on Wednesday, and leave a note here in the Issue to let you know when everything is ready.

**Comment by anisa-hawes** [comment]
Bonjour @marie-flesch et @matgille, 

This lesson is ready for your final review.

- Preview: <http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/reutilisation-de-code-et-modularite>
- .md file: [/fr/en-cours/traductions/reutilisation-de-code-et-modularite.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/reutilisation-de-code-et-modularite.md)
- images: [no images]
- assets: [no assets]
- original avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]
- gallery avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]

Sustainability + accessibility actions status :

- [x] Typesetting
- [x] Addition of Perma.cc links
- Addition of alt-text for all figures - [not applicable – no figure images]
- [ ] Receipt of translator's copyright agreement

Bonjour Célian @datalogism, Vous saurez que nous demandons aux traducteurs et aux traductrices de compléter un formulaire de cession non exclusive de droits d’auteur et d’autorisation de publication. Pourriez-vous [télécharger ce formulaire](https://programminghistorian.org/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf), le compléter et me l'envoyer par courriel (admin [@] programminghistorian.org) ?

Next steps @marie-flesch et @matgille :
- [ ] Prepare x2 posts for our Twitter/Mastodon Bot (you can simply email them to me and I'll slot them into the Google Sheet upon publication)

**Comment by matgille** [comment]
Noted, @anisa-hawes, thanks ! I'll do it by the end of the week

**Comment by matgille** [comment]
- [x] Preview: <http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/reutilisation-de-code-et-modularite>
- [x] .md file: [/fr/en-cours/traductions/reutilisation-de-code-et-modularite.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/reutilisation-de-code-et-modularite.md)
- [x] images: [no images]
- [x] assets: [no assets]
- [x] original avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]
- [x] gallery avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]
- [x] DOI request

Sustainability + accessibility actions status :

- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Addition of alt-text for all figures - [not applicable – no figure images]
- [x] Receipt of translator's copyright agreement



- [x] Prepare x2 posts for our Twitter/Mastodon Bot (you can simply email them to me and I'll slot them into the Google Sheet upon publication)


Reviewed and approved = )

**Comment by matgille** [comment]
As for the tweets: 

`Rendez votre code plus clair avec la modularité permise par python ! Venez apprendre à créer des fonctions et des modules avec cette leçon sur Programming Historian!`

`Apprenez à organiser clairement votre code avec les fonctions et la modularité en python ! Suivez pas à pas notre nouvelle traduction sur Programming Historian en Français !`

**Comment by matgille** [comment]
I reckon it will be time soon to transfer the data to the jekyll repo ? Are we just waiting for Celian's copyright agreement ?

**Comment by datalogism** [comment]
Hello @matgille, @marie-flesch, @anisa-hawes  I just sent you the translator cp agreement by mail :) 
Thank you again for you work !

**Comment by anisa-hawes** [comment]
Dear Célian @datalogism,
I didn't receive the attachment! 
Are you able to re-send?: admin [@] programminghistorian.org
Thank you!

**Comment by marie-flesch** [comment]
La leçon est publiée mais je laisse ce ticket ouvert jusqu'à ce que Célian rentre de vacances et envoie le document à Anisa pour les droits :)

**Comment by datalogism** [comment]
Hello, thank you for the recall i didn't see it. All is fine now !
