### ISSUE TITLE
Proposed Lesson: Web Scraping with OpenRefine

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/ph-submissions#54]
The Programming Historian has received the following proposal for a lesson on 'Web Scraping with OpenRefine' by @evanwill. The proposed learning outcomes of the lesson are:

- fetch URLs to capture and enhance data sets via simple web scraping and APIs.
- parse HTML and JSON to create structured data values.
- automate tasks with Undo/redo Extract.

In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than June 2, 2017. The author agrees to contact the editor in advance if they need to revise the deadline.

If the lesson is not submitted by June 2, the editor will attempt to contact the authors. If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author.

The main editorial contact for this lessons is @jerielizabeth. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1 or @amandavisconti.

**Comment by evanwill** [comment]
@jerielizabeth: 

"OpenRefine: Fetching and Parsing Data from the Web " lesson is submitted as `openrefine-urls.md` in commit a030c3c8d4ed1fe36a651ef05717203258538d0c

Available at http://programminghistorian.github.io/ph-submissions/lessons/openrefine-urls

Thank you!

**Comment by jerielizabeth** [comment]
Excellent @evanwill! Thank you! 

I will look this over this week and get back to you!

**Comment by jerielizabeth** [comment]
@evanwill this looks excellent!! Thank you again! I honestly did not realize that you could do so much with OpenRefine.

I am making a few small structural changes to pull the lesson into line with our existing patterns (adjusting headers and adding internal links). I am also suggesting changing the filename to 'web-scraping-with-openrefine'. I will push up those changes and open a new issue for the lesson review. I have a few editorial suggestions that I'll make there.

**Comment by jerielizabeth** [comment]
Moving this over, I realized that I have created a bit of a inconsistency problem with the lesson name and slug. @evanwill what are your thoughts on the title, slug name? I worry a bit that 'web scraping' is too narrow for everything that this covers, but we do want the slug to be meaningful. 'fetch-and-parse-data-with-openrefine'? its long but matches the title.

**Comment by evanwill** [comment]
The edits look good, and internal links make sense, thank you. 

As for the name change--yes, I was feeling "web scraping" wasn't exactly the right title any more. 
I hesitated to make the slug too long so was trying to simplify with just `openrefine-urls`.
Another short option might be `openrefine-fetch-and-parse`, but I am good with the long file name if that fits with the website structure (i.e. `fetch-and-parse-data-with-openrefine`). 
It makes sense to reflect the title, but I wasn't feeling certain about the title.

**Comment by jerielizabeth** [comment]
Naming things. Always the unexpected problem. :) 

I like having the actions first, rather than the tool, in the title to catch the eye of readers who know what they want to do, but aren't sure how to go about it. 

What about "Parsing Web Queries with OpenRefine" and slug `parse-web-queries-with-openrefine`?

**Comment by evanwill** [comment]
"Web Queries" is an Excel thing, so I don't want to use it in the title due to possible confusion. 

I am leaning back to "Fetching and Parsing Data from the Web with OpenRefine", `fetch-and-parse-data-with-openrefine.md`. 
It captures the idea of a general and flexible tool, since I was trying to introduce functions that could be applied to a variety of uses where the material is web accessible.

**Comment by jerielizabeth** [comment]
That sounds good to me! I'll make the change!

**Comment by jerielizabeth** [comment]
I have opened a review ticket for this lesson (#69). This closes the proposal ticket.
