### ISSUE TITLE
Revisión de traducción: Creación de aplicaciones web interactivas con R y Shiny

### ISSUE THREAD

**Issue by isag91** [programminghistorian/ph-submissions#542]
The Programming Historian en español ha recibido la siguiente propuesta de traducción "Creación de aplicaciones web interactivas con R y Shiny" de la lección  [Making an Interactive Web Application with R and Shiny](https://programminghistorian.org/en/lessons/shiny-leaflet-newspaper-map-tutorial) por parte de @jenniferisasi. Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

Texto
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/creacion-de-aplicacion-shiny.md

Previsualización: https://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/creacion-de-aplicacion-shiny

Imágenes
https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/creacion-de-aplicacion-shiny

Por favor, utiliza los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editora durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios a la traductora, mi rol consistirá en solicitar otra revisión y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra [guía para revisores](http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros ombudpersons.

Política contra el acoso
Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, diversidad funcional, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros ombudsperson [Silvia Gutiérrez De la Torre](http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by isag91** [comment]
Hola @jenniferisasi ,

Me disculpo por demorarme con esta revisión.
Me pareció realmente super todo el trabajo que hiciste con la "hispanización" de la lección!

Ya hice un par de cambios relacionados con errores tipográficos y pequeños problemas de formato. Puedes verlos en la [historia](https://github.com/programminghistorian/ph-submissions/commits/gh-pages/es/borradores/traducciones/creacion-de-aplicacion-shiny.md).

Aquí van mis sugestiones. La mayoría son pequeños detalles. No dudes en omitir las que no te parecen pertinentes. Quedo atenta para cualquier duda.

- [x] 2. Puntos finales después de cada objetivo (ya que uno contiene más de una frase). 

- [x] 4. Punto final en vez de punto y coma entre “los archivos” y “por ejemplo”. 

- [x] 7. 8. El pronombre “éstas” viene sin tilde en el párrafo 7 y con en el párrafo 8. 

- [x] 9. “una función de render*” en vez de “la función de render*”. 

- [x] 11. La última frase del párrafo no está traducida “As an alternative, some of the functionality of Shiny can be replicated in a simple HTML page using the R package crosstalk”. 

- [x] 16. “una lista a nivel de título de los títulos periódicos” -> “una lista de los títulos de los periódicos” 

- [x] 17. “Por ejemplo, en el original una casilla tiene las preposiciones “del” y “al” o “a” y otras, en cambio...” La lectura de esa frase me resultó un poco difícil. A lo mejor “Por ejemplo, en el original, unas casillas indiquen el rango de fechas con preposiciones (“del” y “al” o “a”) mientras otras usan un guión o una coma”. También empezaría una nueva frase con “Aquí”. 

- [x] 18. “el primero y el final” -> “el primero y el último”. 

- [x] 19. “También hemos tenido que adaptar el ámbito geográfico dado por los datos de BNE, en su mayoría la capital de provincia, a la ciudad concreta en que se imprimió la publicación, disponible entre paréntesis...”. Me parece muy larga esta frase. -> “También hemos tenido que adaptar el ámbito geográfico dado por los datos de BNE – en su mayoría la capital de provincia – a la ciudad concreta en que se imprimió la publicación. Esa es disponible entre paréntesis...” 

- [x] 20. Para más consistencia, usar el infinitivo en el subtitulo "Configuración del entorno R y creación de una aplicación Shiny". 

- [x] 22. “R tiene un entorno de desarrollo integrado (IDE por sus siglas en inglés) llamado RStudio para usar junto con R y que proporciona muchas características que hacen que la codificación en este lenguaje sea más conveniente.” Sugiero suprimir “para usar junto con R y ” y “en este lenguaje”. 

- [x] 26. “los usuarios de Mac puede que tengan” -> “se puede que los usuarios de Mac tengan” 

- [x]  26. Me parecería mejor mencionar Linux directo al lado de Mac. Para los lectores quienes están siguiendo el tutorial paso a paso sin leer adelante, podrá evitar una perdida de tiempo buscando soluciones.
Sugiero algo como : "pero los usuarios de Mac y Linux tendrán que instalar la librería externa gdal para que sf funcione dentro de R. Los usuarios de Mac lo pueden hacer con Homebrew a través de la Terminal con los siguientes comandos:...

- [x] 38. “el app. R” -> “el script app.R” 

- [x] 39. No se tradujo “Next you’ll create each of these in turn.” 

- [x] 42. la variable `ui` -> la variable `interfaz_usuario` 

- [x] 44. “En R una función se crea como en comando” -> “En R una función se crea con el comando” 

- [ ] 48. El código no está alineado.  

- [ ] 52. “See the official documentation for more information on the various options and how to create these layouts.” No está traducida esta frase. 

- [x] 54. “sideLayout()” ->“sidebarLayout()” 

- [x] 61. Los dos párrafos antes de la figura 4 no están traducidos. Me parece que son útiles. 

- [x] 63. "leafletOutput(outputID = 'mapa')" -> "leafletOutput(outputId = 'mapa')"

- [x] 64. “un conjunto de datos geográfico” -> “un conjunto de datos geográficos” 

- [x] 70. Ya pusiste la línea de código “addCircleMarkers(data = mapa_df(), radius = ~sqrt(titulo))” en este bloque aunque la introduces en la sección siguiente. 

- [x] 83. “?circleMarkers”-> “?addCircleMarkers” 

- [x] 84. “Después, en otro contexto reactivo, observa, añadirás” -> “Después, en otro contexto reactivo, `observe`, añadirás” 

Comentarios generales 

- [ ] En algunos bloques de códigos, hay márgenes a la izquierda. Me parecería mejor sin ellas. 

- [ ] Un detalle mínimo, pero los variables lista_de_titulos y lista_de_coordenadas podrían volverse lista_titulos y lista_coordenadas para alinearse con interfaz_usuario. Incluso podrían escribirse en formato camelCase para que sean parecidas al resto del código de Shiny. 

- [ ] Tampoco me salió lo que se sugiere en “Mejorar la aplicación”. Creo que ya están trabajando en esto, pero me parece que hacen falta más explicaciones.

**Comment by jenniferisasi** [comment]
Hola @isag91, mil gracias! Nada, tranquila por las fechas, todos estamos ocupados y han sido vacaciones. He realizado todos los cambios que sugerías o he añadido las frases que me había comido (¡qué despiste!). Me faltan: 

 

- [ ] 48. El código no está alineado.
No entiendo bien qué quieres decir.
- [ ]  52. “See the official documentation for more information on the various options and how to create these layouts.” No está traducida esta frase.
Creo que lo quité directamente porque solo está en inglés y desvía la atención de la lección. ¿Qué te parece?

Me faltan los últimos cambios. Efectivamente, vamos a intentar añadir la parte de "mejorar la aplicación" porque, hasta sabiendo inglés, es complicado leer la documentación de ayuda en R.

**Comment by isag91** [comment]
Hola @jenniferisasi,

Gracias por realizar estos cambios! 
48: Quise decir (de forma poca clara) que la linea con la variable "lista_de_coordenadas" empieza más a la izquierda que las demás.
52: Claro, me parece bien omitir esta frase.

**Comment by isag91** [comment]
Ya que no falta casi nada para terminar esta ronda de revisiones, ya les presento a Angélica Avilés Bosques (@avianbomay), quien aceptó revisar una lección para el Programming Historian por primera vez. ¡Muchas gracias por su disponibilidad! 

Puede esperar a que @jenniferisasi confirme que está todo listo para empezar con la revisión. Vuelvo a poner el enlace de la guía para los revisores [aquí](https://programminghistorian.org/es/guia-para-revisores). ¡No dude en preguntar para cualquier duda!

**Comment by jenniferisasi** [comment]
¡Gracias @isag91! Acuso recepción de los mensajes y anoto en mi agenda acabar los cambios antes del fin de esta semana. 

Y bienvenida, @avianbomay! Gracias por revisar esta traducción, será un placer trabajar contigo.

**Comment by avianbomay** [comment]
Muchas gracias por esta oportunidad de poder ayudar! 😄

-A


Angélica Avilés
Ella/she/her
Ph.D.​ Student
The Ohio State University
Department of Linguistics
"Don't let the future frighten you, allow it to e m p o w e r." -John O' Callaghan

________________________________

**Comment by avianbomay** [comment]
Hola! Espero que estén bien y disculpen el delay. Estaba viajando y volviendo a coger el ritmo del semestre. El manual que han creado aquí me parece excelente! :D 
No hice ningún cambio como tal en el texto pero aquí les dejo mis sugerencias. Gracias por confiar en mi para ayudarles con esta revisión. 

1. Reorganizaria la oración: 
En esta lección no te enseñamos a programar en R más allá de lo necesario para crear una aplicación. Tener conocimiento básico de R y de tidyverse en particular será de gran utilidad. Tampoco se explica cómo publicar la aplicación en la web. ---> "Tener conocimiento básico de R y de tidyverse en particular será de gran utilidad. sin embargo, en esta lección no te enseñamos a programar en R más allá de lo necesario para crear una aplicación. Tampoco se le explicará cómo publicar la aplicación en la web." 

2. Y para tu aplicación usarás una función de render* para mostrar un mapa que se adapta a los cambios del data frame reactivo y se actualiza con ellos. ---> eliminar la "Y" simplemente comenzar con "Para tu aplicación..." 

3. En la sección de Configurar el entorno R y `creación de una aplicación, despues de el numero 5 creo que el "no obstante" no es necesario. 

4. En la sección de "Crear una aplicación Shiny vacía" --->  en la primera oración "una aplicación de Shiny consiste en un script..." cuando dice "que comunica a RStudio que se trata de una aplicación..." es un poco confuso. La pondría mas simple como: " ...que comunica a RStudio que es una aplicación y debe abrirla en una ventana...etc". 
5. en la sección de "Prueba la aplicación" -- en el último párrafo tiene "busy" u ocupado, lo pondría mejor: ...ocupado ("busy").

**Comment by isag91** [comment]
¡Muchas gracias por la revisión y sugestiones @avianbomay!

**Comment by isag91** [comment]
¡Hola @jenniferisasi!

Aquí viene el resumen de los cambios por hacer. Para cuestiones de estilo, te dejo arreglar las frases como te parezca mejor.

- [x] 3: "En esta lección no te enseñamos a programar en R más allá de lo necesario para crear una aplicación. Tener conocimiento básico de R y de tidyverse en particular será de gran utilidad. Tampoco se explica cómo publicar la aplicación en la web." ---> "Tener conocimiento básico de R y de tidyverse en particular será de gran utilidad. Sin embargo, en esta lección no te enseñamos a programar en R más allá de lo necesario para crear una aplicación. Tampoco se explica cómo publicar la aplicación en la web."

- [x] 9: "Y para tu aplicación usarás..."  ---> "Para tu aplicación usarás..."

- [x] 9: observe({}), and reactive({}) -> observe({}), y reactive({})

- [x] 21: Creo que el "no obstante" no es necesario.

- [x] 51: "busy" u ocupado -> ocupado (_busy_).

- [x] 62: Si te pierde -> Si te pierdes

**Comment by jenniferisasi** [comment]
Hola @isag91 y gracias por tu paciencia, estas semanas no había tenido tiempo de pasar por PH. He implementado los cambios que sugirió @avianbomay, ¡mil gracias por tu generoso mensaje!

Quedo a la espera de saber cuál es el próximo paso.

**Comment by avianbomay** [comment]
Hola!
Estamos en ese momento del semestre donde todo cae bajo la misma semana jajaja! Gracias por permitirme ayudar!

Buen día!

-A

Angélica Avilés
Ella/she/her(-s)
PhD Student
The Ohio State University
Department of Linguistics
"Don't let the future frighten you, allow it to e m p o w e r." -John O' Callaghan
________________________________

**Comment by isag91** [comment]
Hola @jenniferisasi ,

Muchas gracias y gracias por tu paciencia! Leí la lección otra vez e hice un par de cambios pequeños (typos etc.). Tengo un par de comentarios/sugestiones adicionales.

- [x] 16. "que nos referiremos como la ‘lista de coordenadas'" : supongo que tiene que decir "al que".
- [x] 17. Hay una razón para no poner los enlaces a las versiones raw de estos archivos ahí?
- [x] 19. Hemeroteca digital no viene siempre con mayúscula. 
- [x] 49. Imagino que los tabs en el bloque de código no están ahí a propósito.
- [x] 74. A lo mejor me equivoco, pero no es  'leafletOutput(outputId = 'mapa')' en vez de 'leafletOutput(mapa)'?
- [x] 74. Outputs -> Output ?
- [x] 80. dos pares de paréntesis -> "un par" o "dos paréntesis" 
- [ ] 90. Todavía tienes planeado añadir código extra?

A parte de eso, solo me queda reducir la figura 3 y creo que estaremos listas para publicar!

**Comment by jenniferisasi** [comment]
¡Gracias por tu ojo atento @isag91!

17. Ay, sí, faltan los enlaces, que hay que añadir (o creo que es mejor ya a estas alturas) una vez se muevan a Jekyll. 
74. Pues sí, lo tengo bien en mi código, no sé por qué ahí no pero creo que es porque en inglés también pone solo 'leafletOutput('map'), hmmm
90. No he sido capaz de adivinar yo misma cómo ampliar todo así que no sé, quizás @rivaquiroga sepa algo en 5 minutos o lo tendremos que dejar así

**Comment by rivaquiroga** [comment]
Mi único problema es que en mi computador nunca he podido instalar el paquete sf, así que no tengo cómo probar el código :broken_heart:. Dénme hasta el lunes para ver si me resulta conseguirme otra máquina para probar

**Comment by rivaquiroga** [comment]
¡Hola! 

1. Para usar `selectInput` para seleccionar las comunidades autónomas habría que agregarle una línea a lo que está en `sidebarPanel`:

```
sidebarPanel = sidebarPanel(sliderInput('años', 'Años', min = 1670, max = 2023, value = c(1800, 1850)),
                                selectInput('comunidad_autonoma', "Comunidad Autónoma", unique(lista_de_titulos$comunidad_autónoma), selected = "País Vasco", multiple = TRUE)),
```

(Hay que dejar por defecto un valor para que no arroje error, así que puse "País Vasco").

Y en el servidor hay que agregar una línea dentro de `filter` para que filtre también por comunidad autónoma:

```
  mapa_df = reactive({
    
    lista_de_titulos %>%
      filter(año_inicio > input$años[1] & año_inicio < input$años[2],
             comunidad_autónoma == input$comunidad_autonoma) %>% 
      count(poblacion, name = 'titulo') %>%
      left_join(lista_de_coordenadas, by = 'poblacion')%>%
      filter(!is.na(lng) & !is.na(lat)) %>%
      st_as_sf(coords = c('lng', 'lat')) %>%
      st_set_crs(4326)
  })
```

No sé si es un problema del computador en el que estoy trabajando (que es de 2013 y en el que solo pude instalar una versión un poco más antigua del paquete sf), pero cuando empiezo a seleccionar más comunidades algunas desaparecen. En todo caso, cuando se agrega lo de `leafletProxy` (el punto 3 más abajo) se arregla.

2. Respecto de agregar una etiqueta a dentro de `addCircleMarkers`, en los datos no encontré la variable `ciudad_publicacion` que es la que aparece sugerida en la lección. ¿Será `poblacion`? 

En ese caso, quedaría así esa línea de código:

```
addCircleMarkers(data = mapa_df(), radius = ~sqrt(titulo), label = ~poblacion)
```

3. Para usar `leafletProxy` habría que sacar los marcadores de `output$mapa` y ponerlos en un nuevo bloque de código (el de `observe`). Esa parte quedaría así:

```
  output$mapa = renderLeaflet({
    
    leaflet() %>%
      addTiles() %>%
      setView(lng =-3.700346, lat = 40.41669, zoom = 5.2) 
    
  })
  
    observe({
      leafletProxy("mapa", data = mapa_df()) %>% 
      addCircleMarkers(data = mapa_df(), radius = ~sqrt(titulo), label = ~poblacion)
    })

```

Dos comentarios adicionales:

- En los datos con los títulos la variable `comunidad_autónoma` quedó con tilde. Quizás sea mejor que quede sin, para que sea consistente con las otras variables en que se eliminó. Habría que actualizar el código también en ese caso. 
- Me queda la duda de si sería mejor dejar las variables `ui` y `server` en inglés. Cuando vi el código me costó entenderlo porque estaba buscando esas variables al principio para ver de qué se trataba la app. Incluso en las apps en español las personas tienden a dejar eso en inglés por convención.

Cualquier otra cosa que necesiten, me avisan.

**Comment by jenniferisasi** [comment]
Gracias @rivaquiroga por tomarte el tiempo de mirar el código y ampliarlo. Me apunto como tarea de esta semana mirarlo todo bien y te respondo @isag91 y con ello creo que quedaría todo listo.

**Comment by jenniferisasi** [comment]
Estoy probando el código extra y no me funciona lo de filtrar... sigo. ¡Lo conseguí! Se me había colado un paréntesis donde no era, se activaba todo pero no funcionaba el filtro. Listo, aunque ahora en el País Vasco también me muestra una imprenta en Barcelona así que voy a revisar los datos por si las moscas. En todo caso, ahora voy a editar esa última sección para que quede el código disponible con los añadidos. Mil gracias @rivaquiroga !

- He cambiado `ciudad_publicacion` por `poblacion`, error mío al escribir la lección. 
- He quitado la tilde de comunidad_autónoma en el CSV
- Puedo cambiar lo de `ui` y `server` si por convención se dejan en inglés :) Como siempre, @rivaquiroga tienes más conocimiento de lo que es standard en R que yo así que no hay problema

**Comment by jenniferisasi** [comment]
@isag91 cuando tengas un momento para leer la lección de nuevo me avisas y, si os parece bien, la pasamos para su publicación. Creo que @rivaquiroga debería de aparecer como revisora porque sabemos que se ha tomado el tiempo de hacer el código :) y ver si funciona.

**Comment by isag91** [comment]
Hola,
Muchas gracias @rivaquiroga y @jenniferisasi! Sí, me parece todo listo para publicar.

Texto: [https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/creacion-de-aplicacion-shiny.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/creacion-de-aplicacion-shiny.md)

Archivos: [https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/creacion-de-aplicacion-shiny](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/creacion-de-aplicacion-shiny)

Imagenes: [https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/creacion-de-aplicacion-shiny](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/creacion-de-aplicacion-shiny)

Imagen de la galeria: [https://github.com/programminghistorian/ph-submissions/blob/gh-pages/gallery/originals/shiny-leaflet-newspaper-map-tutorial-original.png](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/gallery/originals/shiny-leaflet-newspaper-map-tutorial-original.png)

**Comment by rivaquiroga** [comment]
@jenniferisasi, ¿agregaste enlaces nuevos a la lección? Si fuese el caso, lo único que faltaría para publicar sería pedirle a Anisa que los archive.

**Comment by jenniferisasi** [comment]
🤔 tengo que ver... gracias por recordármelo. Lo bueno de todo esto es que esta va a ser mi primera lección a transportar a `jekyll` y si pasa algo, es la mía jaja

**Comment by anisa-hawes** [comment]
Hello @jenniferisasi,

This lesson is ready for your final review 🙂 

- Preview: <http://programminghistorian.github.io/ph-submissions/es/borradores/traducciones/creacion-de-aplicacion-shiny>
- .md file: [/borradores/traducciones/creacion-de-aplicacion-shiny.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/traducciones/creacion-de-aplicacion-shiny.md)
- images: [/images/shiny-leaflet-newspaper-map-tutorial](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/shiny-leaflet-newspaper-map-tutorial) **Note**: I've moved the images to the original lesson's image directory (and also renamed and resized them). Images for translations will be uploaded to the original /images folder on Jekyll which is [here](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/shiny-leaflet-newspaper-map-tutorial).
- assets: [/assets/creacion-de-aplicacion-shiny](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/creacion-de-aplicacion-shiny)
- original avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]
- gallery avatar: [already on Jekyll – avatars for original lessons remain for any subsequent translation]

Sustainability + accessibility actions status :
- [x] Typesetting
- [x] Addition of Perma.cc links (I've added the new ones)
- [x] Thank you for preparing alt-text for all figures Jenn
- [x] Receipt of translator's copyright agreement : @jenniferisasi Please could you email me a completed copy of [this form](https://programminghistorian.org/assets/forms/Derechos-de-autor-y-de-publicacion.pdf)?

Next steps :
- [x] Thank you for preparing a translation of the `avatar_alt:`
- [x] Thank you for preparing a translation of the `abstract:`
- [ ] Jenn, we can work together to prepare x1 announcement post, + x2 posts for our Twitter/Mastodon Bot
- [x] I can request the DOI for this lesson (if you haven't already, Jenn?)
- [x] We already have an ES translation of Yann's bio for `ph_authors.yml`

**Comment by jenniferisasi** [comment]
Hi @anisa-hawes! 

Thanks for taking the time to review all the files and make the perma links already. I can certainly work with you to create announcements. I haven't requested the DOI already, so if you want to make this lesson part of the new workflow (like we chatted about) I will be more than happy if you take care of that and wait to hear from them.

**Comment by jenniferisasi** [comment]
The lesson has been published, yay! Gracias a todos por participar en la edición y revisión de esta traducción, ¡una más!
