### ISSUE TITLE
Nueva traducción: Preservar tus datos de investigación 

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#55]
The Programming Historian en español ha recibido la siguiente propuesta de traducción [PRESERVAR TUS DATOS DE INVESTIGACIÓN] de la lección [PRESERVING RESEARCH DATA] por parte de @vgayolrs . Esta traducción se encuentra en estos momentos en fase de revisión y puede leerse en:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/preservar-datos-de-investigacion.md

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.
Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

    El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Me suena mucho que las lecciones de @vgayolrs las revisé

**Comment by vgayolrs** [comment]
así es @arojascastro , de hecho tu nombre está en el YAML.

**Comment by mariajoafana** [comment]
L 26: sugerencias: Cambiar "usan cada vez más de las computadoras" por "usan las computadoras cada vez más "; Cambiar "Sus manuscritos son objetos digitales de un tiempo para acá..." por "Desde hace algún tiempo, sus manuscritos se han convertido en objetos digitales y en consecuencia su investigación ha cambiado -ya sea como..."  
L 28: renglón 8:  añadir "los" antes de "entender". Corregir "as" por "así"
L 64: renglón 4: entiendo que "paquetes de ofimáticas" es la forma correcta pero la verdad es que nunca la había escuchado. Se puede dejar así claro, pero si decides cambiarla podría reemplazarse por algo como "software de oficina"
        Renglón 10: cambiar "consultada" por "consultadas" y "buscada" por "buscadas" y "ni es adecuadas" por "ni son adecuadas"

**Comment by mariajoafana** [comment]
Muchas gracias @vgayolrs Todo se ve bien. Acabo de subir la lección a Jekyll y ya se puede ver en el sitio en español: http://programminghistorian.org/es/lecciones/preservar-datos-de-investigacion
Sin embargo, hay un par de cosas que no están saliendo: los nombres en "revisado por" y el texto de "acerca del autor"  Tienes ideas cómo arreglar esto? Si no, podemos crear un issue

**Comment by vgayolrs** [comment]
@mariajoafana : ¡gracias por la observación!

El problema de "acerca del autor" ya está resuelto. Puedes ver cuál es la mecánica (por si necesitases hacer posteriores arreglos) en el primer 'commit' de arriba. Es algo más o menos sencillo porque solamente hay que agregar, en este [archivo](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/authors.yml), la bio en español con la indicación previa de `es |`. Aunque creo que me voy a ir adelantando para arreglar todo eso de una vez.

El problema de los revisores de traducción era por un error en la definición del campo de metadatos respectivos en YAML, como puedes ver en el segundo 'commit'. Mil gracias, a tod@s!

Solamente yo tendría una duda antes de cerrar el ticket: al principio se cita un texto de Roy Rosenzweig con su título en español. En el ámbito de la academia anglosajona es un texto clásico, sobre todo entre humanistas digitales, y casi que no necesita más presentación. Pero el texto de Rosenzweig no ha sido traducido al español y, personalmente, creo que deberíamos dejarlo en inglés y poner una nota a pie de página con la referencia completa al artículo puesto que no es my conocido en el ámbito hispano-parlante. Pero me gustaría saber qué opinan ustedes para saber cómo enfrentar este tipo de cosas en las siguientes traducciones. Mil gracias.

**Comment by mariajoafana** [comment]
Mil gracias Víctor. Estoy de acuerdo con lo que dices del texto de Rosenzweig, dejarlo con su título original en inglés ya que no existe traducción. Avísame una vez hayas hecho el cambio y de ahí cerramos el ticket y ya podemos difundir esta lección!

**Comment by mariajoafana** [comment]
Listo, voy a cerrar esto, si aparece algo más por revisar la podemos volver a abrir.
