### ISSUE TITLE
Traduction en français : Démarrer avec Omeka

### ISSUE THREAD

**Issue by marie-flesch** [programminghistorian/ph-submissions#550]
Le *Programming Historian en français* reçu une proposition de traduction de la leçon [Up and Running with Omeka.net](https://programminghistorian.org/en/lessons/up-and-running-with-omeka). Cette traduction sera réalisée par @Leblance (Elina Leblanc). 

Nous avons convenu d'un délai de trois mois  pour la traduction. Une fois reçue, celle-ci sera confiée à un rédacteur ou à une rédactrice de l'équipe pour l'évaluation.

**Comment by anisa-hawes** [comment]
Bonjour, @marie-flesch.

Vous trouverez les fichiers ici : 
- .md file: [/en-cours/traductions/demarrer-avec-omeka-classic.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/demarrer-avec-omeka-classic.md)
- images: [/images/up-and-running-with-omeka](https://github.com/programminghistorian/jekyll/blob/gh-pages/images/up-and-running-with-omeka) (**Note to Marie**: Images for translations are uploaded to the original /images folder - both on ph-submissions and on Jekyll)
- assets: [aucun]

Vous pouvez parcourir l’aperçu de la soumission ici :
- Preview: <http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/demarrer-avec-omeka-classic>

N.B. Toutes les figures doivent être accompagnées d'un texte descriptif "alt-text". 

Exemple : `{% include figure.html filename="tr-fr-demarrer-avec-omeka-08.png" alt="DESCRIPTION VISUELLE DE L'IMAGE" caption="Ajouter un contenu" %}`

**Comment by marie-flesch** [comment]
Merci Anisa :)

**Comment by davvalent** [comment]
Bonjour,

Le suivi éditorial de cette leçon m’a été confié. Pour l’heure, j’ai effectué une première relecture et j’ai transmis à @Leblance mes remarques qui comprennent, entre autres, un suivi pour l’ajout du contenu des attributs alt, souligné plus haut par @anisa-hawes.

**Comment by Leblance** [comment]
Bonjour,

Je viens de modifier la leçon, en suivant les recommandations de @davvalent (Ajout des attributs alt et d'un nouveau paragraphe sur la traduction de l'interface en français ; reformulations et corrections du texte). J'ai quelques doutes sur la manière dont j'ai utilisé l'écriture épicène, dites-moi s'il faut que je modifie quelque chose.

**Comment by davvalent** [comment]
Bonjour @Leblance,

Merci pour les révisions. J’accuse réception de votre leçon révisée et je vous reviens sous peu pour la suite.

**Comment by davvalent** [comment]
Bonjour @Leblance,

J’ai procédé au téléversement des nouvelles images.
Avant de passer à la phase d’évaluation de la traduction, pourrais-je vous demander de confirmer qu’elles sont toutes au bon endroit en [consultant l’aperçu](https://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/demarrer-avec-omeka) de la leçon ?

En ce qui concerne l’écriture épicène, il serait préférable de ne pas modifier le texte à ce stade, comme nous entrerons bientôt en phase d’évaluation.
Une nouvelle phase de révision est prévue à la suite de l’évaluation et nous pourrons alors procéder aux rectifications nécessaires.

Par ailleurs, j’ai profité de ma plus récente relecture pour effectuer des corrections mineures de nature strictement typographique.

**Comment by Leblance** [comment]
Bonjour @davvalent,

Je vous remercie pour votre relecture et corrections. Je viens de relire le texte, les images sont bien au bon endroit.

**Comment by davvalent** [comment]
C’est moi qui vous remercie, @Leblance, pour les vérifications. Nous pouvons maintenant passer à la phase d’évaluation de la traduction.

Le *Programming Historian en français* a donc reçu la traduction « Démarrer avec Omeka » de @Leblance (Elina Leblanc), d’après l’article initialement paru en anglais [Up and Running with Omeka.net](https://programminghistorian.org/en/lessons/up-and-running-with-omeka). Cette leçon est maintenant en phase d’évaluation et peut être consultée ici : [http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/demarrer-avec-omeka](http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/demarrer-avec-omeka).

Comme mentionné plus haut, j’assume le rôle de rédacteur responsable du suivi du processus d’évaluation. Dans ce cadre, je vais solliciter une relecture formelle auprès de la communauté, annoncer ici le nom de la personne responsable de l’évaluation et coordonner les échanges qui auront lieu sur ce fil de commentaires.

Tout membre de la communauté peut également faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos [consignes aux évaluateurs et aux évaluatrices](https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous).

Les relecteurs et les relectrices peuvent utiliser la numérotation des paragraphes fournie dans l’aperçu de la leçon pour organiser leurs commentaires, si cela leur convient, tout en demeurant libres de présenter leur évaluation de la manière qui leur semble la meilleure.

Nous demandons que toutes les relectures cessent après réception de l’évaluation formelle, pour que la traductrice puisse travailler sur la révision de son texte. J’annoncerai sur ce fil quand cette étape aura été atteinte.

La discussion ouverte s’organise sur GitHub à même ce fil de commentaires. Si quelqu’un préfère de discuter de manière privée, merci de m’envoyer un courriel [david.valentine@umontreal.ca](mailto:david.valentine@umontreal.ca). Vous avez toujours la possibilité de vous tourner vers notre médiatrice si vous avez le sentiment qu’une médiation est nécessaire. Il n’y a aucun risque que ceci ait une incidence négative sur l’évaluation de cette leçon.

# Politique contre le harcèlement

Vous trouverez ci-dessous les principes du *Programming Historian en français* qui doivent inspirer les échanges entre évaluateurs et évaluatrices, autrices et auteurs, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le *Programming Historian en français* tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations de handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique.

Nous ne tolérons aucune forme de harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial.

Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre médiatrice ([Hélène Huet](mailto:hhuet@ufl.edu)). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by davvalent** [comment]
Bonjour,

Pierre Willaime (@pprw) a accepté de procéder à l’évaluation de cette leçon. Pour ce faire, nous avons convenu d’un délai qui nous mène au 17 septembre. Il nous partagera ses remarques à même ce fil de commentaires. J’effectuerai un suivi ici avec @Leblance lorsque Pierre aura soumis son évaluation. Merci @pprw !

**Comment by davvalent** [comment]
Cher @pprw,

Je vous écris pour effectuer un petit suivi sur l’évaluation de cette leçon.

J’aimerais m’assurer que tout se déroule comme vous le souhaitez et qu’il n’y a pas de questions en suspens. N’hésitez pas à me faire signe si je peux vous être utile.

En vous remerciant d’avance, et bien cordialement,

David

**Comment by pprw** [comment]
Bonjour à tous,

Désolé d'avoir tardé à relire cette traduction.

Voici quelques remarques destinées à améliorer la leçon. Elles sont mineures et ne portent pas sur la traduction proprement dite que j'ai trouvée sans erreur.

1. Il y a eu une nouvelle version d'Omeka (Omeka S) depuis l'écriture du tutoriel en anglais. La version présentée ici est Omeka Classic. Pour  éviter l'ambiguïté, je propose de remplacer le titre par "Démarrer avec Omeka Classic".

2. La tutoriel démarre par la présentation de l'offre d'hébergement officiel Omeka.net. Un nouvel utilisateur peut ne pas se rendre compte que Omeka Classic est un logiciel libre qu'on peut utiliser sur n'importe quel serveur.  Pour palier à ce manque (présent dans la version anglaise, la traduction n'est pas en cause), je propose de remplacer le paragraphe 2 par ce qui suit.

> Omeka Classic est un logiciel libre qui permet de créer un site web facilement afin de valoriser une collection de contenus (items). Vous pouvez installer Omeka Classic sur un serveur ou utiliser une installation existante proposée par un hébergeur. La suite de cette leçon présente Omeka Classic par l'offre d'hébergement "Omeka.net" proposée par l'éditeur du logiciel.

3.  Je propose la modification suivante du paragraphe 3 (en gras).

> Depuis la page Omeka.net, cliquez sur Pricing. Choisissez l’offre d’essai (Start your free Omeka trial). **Précisons que cette offre n'est pas soumisse à une durée contrairement à ce que son nom peut laisser penser.** Remplissez le formulaire d’inscription. Dans votre boîte de messagerie, vérifiez que vous avez reçu le lien pour activer votre compte.

4. Le paragraphe 49 mentionne une autre leçon, je ne crois pas qu'elle existe.
5.  Je propose de reformuler à la marge le paragraphe 50 de cette manière (disclaimer : je suis membre du bureau de l'association AUFO)

> Les créateurs d’Omeka ont rassemblé de nombreuses ressources utiles sur les [pages d’aide officielles](https://info.omeka.net/help/) du logiciel. [Le forum](https://forum.omeka.org) est un bon lieu pour poser des questions en anglais. Il existe également une association rassemblant [les usagers francophones d'Omeka](https://omeka.fr) qui met à disposition une liste de discussion ([omekafr-asso](https://groupes.renater.fr/sympa/review/omekafr-asso)),  propose de la documentation en français, une liste de projets utilisant ce Content Management System (CMS) et des informations relatives à la communauté francophone des utilisateurs et des utilisatrices d’Omeka. 

Merci pour cette traduction @Leblance et merci à l'équipe du PH.

Pierre

**Comment by davvalent** [comment]
Bonjour tout le monde,

Merci beaucoup, @pprw, pour votre relecture!

Les remarques de @pprw portent principalement sur le contexte d’utilisation d’Omeka propre à cette leçon. Ces quelques précisions semblent effectivement importantes étant donné les différentes modalités d’utilisation de ce logiciel.

J’ajoute quelques remarques en complément de celles de @pprw :

- Il existe une leçon en anglais sur [l’installation d’Omeka Classic sur un serveur web](https://programminghistorian.org/en/lessons/installing-omeka). Il pourrait être intéressant, en lien avec la remarque de Pierre, d’insérer un lien vers cette leçon dans le paragraphe 2 (à l’instar de ce que nous pouvons constater dans la [version espagnole](https://programminghistorian.org/es/lecciones/poniendo-omeka-a-funcionar), par exemple), en indiquant qu’il s’agit de la version anglaise.
- La leçon mentionnée au paragraphe 49 est celle-ci : [Creating an Omeka Exhibit](https://programminghistorian.org/en/lessons/creating-an-omeka-exhibit). Le premier paragraphe de cette leçon établit un lien avec [Up and Running with Omeka.net](https://programminghistorian.org/en/lessons/up-and-running-with-omeka), la version originale en anglais de la traduction qui nous occupe ici. Il m’apparaîtrait pertinent d’insérer un lien vers cette leçon puisque la mention n’aurait pas vraiment de sens sans cela. Il faudra toutefois indiquer qu’il s’agit de la version anglaise, la version française étant inexistante à ce jour.

@Leblance, nous pouvons maintenant passer à la seconde phase de révision. Dans un premier temps, je vous invite à intégrer dans le texte les remarques et suggestions que vous jugez pertinentes. Lorsque ce sera fait, merci de m’en aviser ici.

Par la suite, je procéderai à une relecture de la nouvelle version afin de vous transmettre, si nécessaire, mes remarques en lien avec cette seconde phase de révision.

Je vous propose un délai de quatre semaines pour que vous procédiez à l’intégration de vos modifications. Cela nous mènerait autour du 8 décembre. N’hésitez pas à me faire signe si vous avez besoin de plus de temps. D’ici là, je demeure à votre disposition si vous avez des questions pour la suite.

Bien cordialement,

David

**Comment by Leblance** [comment]
Bonjour à tous,

Merci beaucoup @pprw et @davvalent pour vos précieux retours. Je viens de terminer la révision, en intégrant toutes vos remarques et vos suggestions de modification qui permettent vraiment d'éclaircir plusieurs passages de la leçon.
Je pense n'avoir rien oublié ! Je reste à votre disposition pour la suite.

Bien cordialement,

Elina

**Comment by davvalent** [comment]
Merci @Leblance, je vous reviens au courant de la semaine prochaine. Bon weekend!

**Comment by davvalent** [comment]
Bonjour @Leblance,

Me revoilà pour la suite du suivi sur votre leçon, après un délai supplémentaire dont je m’excuse.

Merci encore pour l’intégration des révisions proposées précédemment. À la suite de l’intervention de notre évaluateur et de vos dernières modifications, j’aimerais proposer, pour la seconde phase de révision, une nouvelle ronde de suggestion de modifications qui ne touchent pratiquement que la forme.

Vous constaterez que certaines propositions s’éloignent un peu du texte original en anglais. Dans ce cas, il s’agit de propositions qui visent à améliorer la fluidité de certains passages, si vous le souhaitez.

Je vous invite à intégrer à la leçon les propositions qui vous conviennent. Lorsque ce sera fait, vous pouvez me faire signe ici même. Par la suite, nous devrions pouvoir nous diriger vers les dernières phases de la préparation de la leçon.

Finalement, n'hésitez pas à me contacter ici ou par courriel si vous avez des questions.

Merci, et bien cordialement,

David

# Propositions

La forme des propositions ci-dessous s'organise ainsi :

- § n : formulation actuelle dans la leçon **→** corrections et reformulations proposées **:** à la suite des deux-points suivent les explications lorsque nécessaire.

# Par §

- § 2 : valoriser une collection de contenus (items) → valoriser une collection de contenus ~~(items)~~ : retrancher « (items) » qui n’est plus pertinent avec l’utilisation de la version française de l’interface (le terme *items* n’apparaît plus dans la leçon ni dans l'interface).
- § 4 : n’est pas soumisse → n’est pas soumise
- § 4 : n’est pas soumise à une durée → n’est pas soumise à une durée limitée
- § 4 : intervertir les phrases « Précisons que cette offre n’est pas soumise [...] » et « Choisissez l’**offre d’essai** (*Start your free Omeka trial*). » : il serait probablement plus cohérent de fournir des précisions sur l’offre après avoir mentionné l’offre en question.
- § 7 : le titre que vous ~~voulez utiliser~~ → le titre que vous désirez : allègement
- § 9 : Pour voir à quoi il ressemble, → Pour en consulter un aperçu,
- § 11 : qui n’attend que d’être rempli. → qui n’attend que de recevoir des contenus OU qui n’attend que l’intégration des contenus.
- § 11 : Pour revenir sur votre tableau de bord, → Pour revenir à votre tableau de bord,
- § 17 : Parmi les extensions proposées, → Parmi les extensions disponibles, : pour éviter la répétition du mot « proposées » dans la même phrase
- § 17 : en laissant par défaut les options qui vous seront proposées → en utilisant les options proposées par défaut : pour alléger la phrase
- Pour le titre « Configurer votre site en français (note du traducteur) », je suggère d’utiliser « traductrice » au lieu de « traducteur », si, bien sûr, ce titre vous convient. Ou alors la formule « note de traduction », plus générique, mais épicène.
- § 19 : La configuration par défaut d’Omeka est en anglais. → Par défaut, Omeka utilise l’anglais.
- Liste à puce suivant le paragraphe 19 :
  - Deuxième élément de la liste à puce :
    - je propose de remplacer le point-virgule par un deux-points pour favoriser la continuité syntaxique de l’élément de la liste
    - reformulation : une fois que vous avez choisi une langue, cliquez sur **Save changes** → sélectionnez une langue et cliquez sur **Save changes** (formule simplifiée)
  - Troisième et dernier élément de la liste :
    - je propose que cet élément soit extrait de la liste pour devenir un paragraphe, puisqu’à ce stade, la configuration de la langue est terminée. Par le fait même, nous pourrions donc procéder à une reformulation :
      - Automatiquement, l’interface est traduite dans la langue choisie, dans notre cas le français&#x202F;; si vous souhaitez traduire l’interface dans une autre langue ou revenir à l’anglais, cliquez sur **Configurer**. → Automatiquement, l’interface est traduite dans la langue choisie (le français dans notre cas). Si vous souhaitez traduire l’interface dans une autre langue ou revenir à l’anglais, cliquez sur le bouton **Configurer** de l’extension **Locale**.
- § 23 : il serait pertinent d’insérer un lien vers Wikipédia pour en savoir plus sur Dublin Core : `[Dublin Core](https://fr.wikipedia.org/wiki/Dublin_Core)`
- § 25 : par exemple, si vous souhaitez ajouter plusieurs mots-clés à votre contenu → par exemple, si vous souhaitez ajouter plusieurs sujets à votre contenu : le champ « mots-clés » n’apparaît pas dans l’onglet Dublin Core de l’interface en français (puisque le terme `keyword` n’existe pas dans Dublin Core), mais plutôt en tant qu’onglet (à droite) dont il est question plus loin dans la leçon ; il serait préférable d’utiliser un champ disponible dans l’onglet Dublin Core, par exemple le champ Sujet, visible dans l’illustration, pour dissiper cette ambiguïté.
- § 30 : en cliquant sur **Fichiers** → en cliquant sur l’onglet **Fichiers**
- § 30 : dans la limite des 500 MB → dans la limite des 500 Mo : la version française d’Omeka ne traduit pas ce symbole, mais il m’apparaît préférable de le traduire dans le texte, comme cela n’aura pas d’incidence sur la manipulation de l’interface.
- § 31 : en cliquant sur le bouton du même nom → en cliquant sur l’onglet du même nom
- § 36 : ce n’est pas la page que vos utilisateurs et vos utilisatrices non connectés verront lorsqu’ils consulteront ce contenu sur votre site → ce n’est pas la page que les internautes verront en consultant ce contenu sur votre site : formulation épicène et allègement : il m’apparaît superflu de mentionner le fait que les utilisateurs et les utilisatrices sont non connectés ; il serait possible d’alléger considérablement la phrase en utilisant un nom collectif comme le public ou les internautes.
- § 36 : éditer le contenu en cliquant sur **Modifier** au-dessus → éditer le contenu en cliquant sur **Modifier** ~~au-dessus~~ : superflu
- § 44 : sélectionnez les contenus qui appartiennent à votre nouvelle collection → sélectionnez les contenus que vous souhaitez ajouter à votre nouvelle collection : clarification
- § 46 : souhaiteriez → souhaitez : le conditionnel, n’apparaissant nulle part dans la leçon, est superflu.
- § 49 : Il commence à prendre forme maintenant que vous avez aussi bien des contenus individuels que des collections thématiques. → Il commence à prendre forme grâce à des contenus individuels aussi bien qu’à des collections thématiques. Mea culpa : la répétition dans ce paragraphe de la formule « maintenant que vous avez » a été introduite sur la base d’une suggestion que je vous ai proposée lors de la révision initiale.
- § 50 : un bon lieu → un bon endroit

**Comment by davvalent** [comment]
Bonjour  @Leblance,

Je vous écris pour effectuer un suivi votre traduction.

J’aimerais m’assurer que tout se déroule comme vous le souhaitez et qu’il n’y a pas de questions en suspens. Surtout, n’hésitez pas à me faire signe si je peux vous être utile. Si nécessaire, vous pouvez m’écrire ici même ou par retour de courriel si vous préférez.

Bien cordialement,

David

**Comment by Leblance** [comment]
Bonjour @davvalent,

Je m'excuse pour le délai avec lequel je vous réponds. Je viens de relire la leçon en y intégrant vos suggestions. Merci beaucoup pour votre relecture très précise.

Je me tiens à disposition pour la suite (en étant plus réactive cette fois !).
Bien cordialement,

Elina Leblanc

**Comment by davvalent** [comment]
Merci @Leblance , je procéderai sous peu à une dernière relecture de la leçon et je vous reviens aussitôt que possible.

**Comment by davvalent** [comment]
Bonjour @Leblance,

Merci encore pour votre patience. J’ai effectué quelques retouches orthotypographiques et mis à jour les métadonnées. À ce stade, la leçon me semble prête pour passer à l’étape suivante avec @marie-flesch.

Note pour Marie : par endroits, le texte a été amendé de quelques ajouts qui précisent certains éléments contextuels de la leçon. Ces ajouts ne modifient aucunement la leçon sur le fond. Pour cette raison, je ne crois pas justifié de les signaler, à l’exception de la nouvelle section "Configurer votre site en français" dont l’ajout est signalé directement dans le titre (à l’instar de la [version portugaise](https://programminghistorian.org/pt/licoes/introducao-omeka-net#configurar-o-seu-site-para--portugu%C3%AAs-nota-da-tradu%C3%A7%C3%A3o)).

**Comment by marie-flesch** [comment]
Yoohoo, super @davvalent et bravo @Leblance ! Je suis très occupée cette semaine, mais je m'attelle à tout ça dès la semaine prochaine. Et c'est noté pour les ajouts !

**Comment by marie-flesch** [comment]
J'ai relu la traduction, elle est impeccable, bravo @davvalent et @Leblance ! La leçon est prête à partir en phase de publication @charlottejmc .

**Comment by anisa-hawes** [comment]
Bonjour Elina @Leblance,

Our Publishing team will now begin **Phase 6. Sustainability + Accessibility**. This is a series of checks and actions which include reviewing the lesson's typesetting + generating archival links.

--

Merci, @davvalent et @marie-flesch!

This lesson's sustainability + accessibility checks are now in progress. @charlottejmc and I will update you here in the Issue thread when these are complete so that you can read through the lesson one final time before we work together to stage it for publication. We'll aim to finish this work by the end of next week **Friday 15th March**.

- Preview: 

<http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/demarrer-avec-omeka-classic>  

Publisher's sustainability + accessibility actions:
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Check alt-text for all figures
- [x] Check/resize images
- [x] Check/adjust image filenames
- [x] Receipt of translator's copyright agreement : _Bonjour @Leblance, 
Notre formulaire de déclaration de droit d'auteur est une occasion de reconnaître le droit d'auteur et de nous accorder la permission de publier la leçon. Pourriez-vous [télécharger ce formulaire](https://programminghistorian.org/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf), le compléter et me l'envoyer par courriel (publishing.assistant [@] programminghistorian.org). Merci beaucoup_ ✨ 
- [x] Add doi
- [x] Add all contributor names to our list of Unique Contributors

Editorial input to YAML:
- [x] Translation of `avatar_alt:`
- [x] Translation of `abstract:`
- [x] Translation of author(s) bio for `ph_authors.yml`

Files we'll prepare for transfer to Jekyll:

**FR:**  
- .md file: [/en-cours/traductions/demarrer-avec-omeka-classic.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/demarrer-avec-omeka-classic.md)
- images: [/images/up-and-running-with-omeka](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/up-and-running-with-omeka)
- assets: [aucun]

Promotion:
- [x] Prepare announcement post (using template)
- [x] Prepare evergreen posts – @marie-flesch, could you help us by providing x2 posts for future promotion via our social media channels? You can add these directly to the `ph-evergreens-twitter-x` spreadsheet that has been shared with you, reply in a comment below, or email them to Charlotte at publishing.assistant[@]programminghistorian.org.

**Comment by anisa-hawes** [comment]
Bonjour @Leblance,

Notre formulaire de déclaration de droit d'auteur est une occasion de reconnaître le droit d'auteur et de nous accorder la permission de publier la leçon. Pourriez-vous [télécharger ce formulaire](https://programminghistorian.org/assets/forms/Droit-d-auteur-et-authorisation-de-publication.pdf), le compléter et l'envoyer par courriel á (publishing.assistant [@] programminghistorian.org). Merci beaucoup.

Anisa

**Comment by anisa-hawes** [comment]
[Démarrer avec Omeka Classic](https://programminghistorian.org/fr/lecons/demarrer-avec-omeka-classic) is published!

Congratulations @Leblance!
Thank you **all** for your contributions 

---

Our suggested citation for this lesson is:

>Miriam Posner, « Démarrer avec Omeka Classic », traduction par Elina Leblanc, Programming Historian en français 6 (2024), https://doi.org/10.46430/phfr0030.


We appreciate your help to circulate our social media announcements about this lesson among your networks:
Twitter/X: https://twitter.com/ProgHist/status/1770367273028485501
Mastodon: https://hcommons.social/@proghist/112127081142914225 

---


Sincere thanks.
