### ISSUE TITLE
Ticket de revisión de traducción: Introducción a Markdown

### ISSUE THREAD

**Issue by mariajoafana** [programminghistorian/ph-submissions#56]
The Programming Historian en español ha recibido la siguiente propuesta de traducción "Introducción a Markdown" de la lección ["Getting Started with Markdown"](http://programminghistorian.org/lessons/getting-started-with-markdown) por parte de @vgayolrs . Esta traducción se encuentra en estos momentos en fase de revisión a cargo de @juancobo y puede leerse en:

http://programminghistorian.github.io/ph-submissions/es/traducciones/introduccion-a-markdown

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.
Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

    El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by mariajoafana** [comment]
Acá van mis comentarios @vgayolrs 

2 "*The*" antes de *Programming Historian* 
3 Tal vez aclarar así: "una utilidad del lenguaje de programación Perl"
4 Corregir en el último renglón "compatibilidad de implican"
8 "*The*" antes *Programming Historian*
15 Corregir "Mardown"
18 añadir "la" antes de Markdown. Tilde en "esta"
21 "*The*" antes de *Programming Historian*
23 "*The*" antes de *Programming Historian*
38 "*The*" antes de *Programming Historian*
40 "*The*" antes de *Programming Historian*
41 Cambiar "notas d pie" por "notas al pie". Sugieron cambiar orden así: "con un par de corchetes adicional"
51 corregir "espacioes"
58 "*The*" antes de *Programming Historian*

**Comment by vgayolrs** [comment]
¡Muchas gracias @mariajoafana ! ¿Procedo a corregir o estamos esperando los comentarios de alguien más?

**Comment by mariajoafana** [comment]
Pues no tenemos por el momento a nadie para ser el segundo revisor. Yo creo que puedes hacer estas correcciones y de ahí decidimos vemos quien se anima?

**Comment by arojascastro** [comment]
Hola, @mariajoafana y @vgayolrs, María Paula García Mosquera me ha vuelto a escribir interesada. ¿Por qué no le pedimos que revise esta lección? Tienes su contacto, @mariajoafana, ¿verdad? ¿Le escribes tú?

**Comment by mariajoafana** [comment]
Si, me parece buena idea. Yo me contacto con ella.

**Comment by mariajoafana** [comment]
Queridos, @juancobo va a ayudarnos revisando esta la lección.

**Comment by arojascastro** [comment]
Hola @mariajoafana si neceistas otro revisor, tengo una candidata... let me know ;)

**Comment by juancobo** [comment]
Hola a todos. Acá van mis comentarios, por favor disculpen el retraso.

4 Falta la segunda raya parentética al final del párrafo: “—si alguna vez has intentado abrir un documento guardado en un formato … que implican—.“. También deberían ser rayas (“—“) en vez de guiones (“-“). 

9 Sugiero “Verás que mientras que el panel de la derecha cuenta con una presentación más elegante del texto, el archivo de Markdown de la izquierda es aún bastante legible”, pues es un poco más fiel al original.

10 Tilde en “ícono”.

11 Sugiero “de la izquierda”.

18 Añadir “la” antes de “sintaxis”.

27 Sugiero “… documentos que sean legibles como texto plano y que a la vez puedan traducirse a otros formatos.”

29 Faltan los dos acentos graves alrededor de `<br />`, como aparecen en la versión en Inglés.

30 Revisar las sangrías en la caja de texto: sobran dos antes de `<html>` y `</html.`, una antes de `<head>` y falta una antes de `<title>`.

31 Falta una sangría antes de `<html>`.

53 Sugiero “La versión básica de Markdown” como traducción de “The core Markdown spec”.

58 Falta un subtítulo antes de este párrafo; sugiero “Limitaciones de Markdown”. Sugiero “Esto puede arreglarse en parte” en vez de “de alguna manera”.

**Comment by mariajoafana** [comment]
Muchas gracias @juancobo 
@vgayolrs , todo tuyo para hacer las correcciones del caso

**Comment by vgayolrs** [comment]
¡Muchas gracias @mariajoafana y @juancobo  por sus observaciones! @mariajoafana , ya quedó todo corregido salvo el asunto marcado como "58" respecto a la adición de un subtítulo. Considero que si el original en inglés no lo lleva, podemos obviarlo. Sin embargo lo pongo a tu consideración como editora de la traducción. Por lo demás, se atendió el resto de las observaciones.

**Comment by juancobo** [comment]
¡Buenísimo, @vgayolrs! 

Lo del punto 58 lo sugerí porque el subtítulo sí está en el original en Inglés pero está ausente en la traducción.

**Comment by vgayolrs** [comment]
¡LLevas razón @juancobo !  Insertado subtítulo.
@mariajoafana : listo.

**Comment by mariajoafana** [comment]
Muchas gracias a todos. La lección ya está al aire (https://programminghistorian.org/es/lecciones/introduccion-a-markdown) Sin embargo, ya actualicé el authors.yml con la biografía de la autora en español, pero no se está mostrando en la página. @vgayolrs ¿alguna idea de cómo arreglar esto?

**Comment by vgayolrs** [comment]
Hola @mariajoafana , intento arreglar esto. Sin embargo, ¿no debería ser: "... es SIG, geógrafa y bibliotecaria de Informática en la Universidad de Ottawa"?

**Comment by mariajoafana** [comment]
Yo lo leí como que Sarah Simpkin es bibliotecaria de las tres cosas: SIG, geografía e informática

**Comment by vgayolrs** [comment]
@mariajoafana , ya está corregido el error. Puedes cerrar el ticket cuando quieras.

**Comment by mariajoafana** [comment]
Perfecto, gracias @vgayolrs y @juancobo Ya se puede difundir el tutorial. Voy a cerrar esto ya, cualquier cosa que surja lo podemos reabrir.

**Comment by mariajoafana** [comment]
@vgayolrs Reabro esto pues encontré algo que hay que cambiar. En el código que está entre las líneas 186 y 194 los tres acentos graves ``` no están apareciendo.

**Comment by vgayolrs** [comment]
@mariajoafana , creo que ya quedó (un lío con los espacios y sangrías). Cierro el tique pero ábrelo si se necesita algo más. Muchas gracias. Slds.
