### ISSUE TITLE
Tradução da lição: Download Automático com Wget

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#562]
O Programming Historian em Português recebeu a proposta de tradução da lição [Automated Downloading with Wget](https://programminghistorian.org/en/lessons/automated-downloading-with-wget). Agradeço à @Mariana-Penna pela proposta. Já fiz uma primeira revisão da mesma. @anisa-hawes irá fazer as verificações necessárias. @josircg fará o acompanhamento editorial (que acontecerá no ticket de revisão, que abriremos assim que as verificações forem realizadas por Anisa).

**Comment by anisa-hawes** [comment]
Olá Josir @josircg,

Key files are here:
- .md file: [/esbocos/traducoes/download-automatico-wget.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/download-automatico-wget.md)
- original images: [/images/automated-downloading-with-wget](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/automated-downloading-with-wget) **Note:** I think it would be good to create new images for this translation. What do you think @josircg? (If you agree, let me know. l'd be happy to receive them by email, and will resize, rename –according to a new file naming convention– and upload them here to the original images folder.)
- assets: [none]

A Preview of the lesson is available here:
- <http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/download-automatico-wget>

**Comment by josircg** [comment]
@anisa-hawes I don't think we need to change the images. There are just 2 images and they are almost the same in portuguese.

I didn't understand well. We will have another ticket to start the revision? Or the revision/editing will be done here?

**Comment by anisa-hawes** [comment]
Thank you @josircg. Okay. That is fine to keep the images, if they will be the same in PT.

The revision and editing will be done in this Issue, we will simply relabel it at each Phase of the workflow. 

In this case, I have relabelled it "Initial edit" and you are ready to move forwards.

**Comment by DanielAlvesLABDH** [comment]
O @ericbrasiln aceitou ficar como revisor desta tradução. Obrigado, uma vez mais. Eu e o @josircg iremos procurar mais alguém para fazer a segunda revisão.

**Comment by ericbrasiln** [comment]
Olá, pessoal

Fico feliz em ajudar com a revisão.

Curiosamente, eu estou usando esta lição em inglês como referência para outra tradução que estou fazendo e pensei na importância de tê-la traduzida para o português.

Obrigado, @Mariana-Penna

**Comment by josircg** [comment]
@ericbrasiln Aproveitei para testar o código e já coloco minhas sugestões abaixo para facilitar o seu trabalho:

- [x] parágrafo 10: Não sei se isso é normal em Portugal mas a construção "Se usa um sistema" soa estranho. Quem usa? Minha sugestão seria "Se você usa um sistema"
- [x] parágrafo 39: "na qual inserimos alguns comandos no Python" por "onde nós já trabalhamos com o Python"
- [x] parágrafo 41: "de forma que eles" por "o que indica que eles"
- [x] parágrafo 69: "ferramentas digital" por "ferramentas digitais"

**Comment by Mariana-Penna** [comment]
@josircg , obrigada pelos comentários, apenas uma observação, antes que o Eric avance na edição, é em relação ao primeiro ponto de alteração. No parágrafo 10, eu fiz desta maneira "Se usa um sistema" por sugestão dos colegas portugueses numa tradução anterior. Eu escrevia da maneira como você propôs, que nos é mais familiar, mas para eles creio que soe ainda mais estranho e para nós me parece que permanece suficientemente compreensível mesmo com a omissão do "você". O que acham?

**Comment by DanielAlvesLABDH** [comment]
Obrigado @Mariana-Penna, tem sido esse o entendimento, mas o principal é manter uma coerência ao longo da tradução. No final falamos todos a mesma língua!
Aproveito para dizer que estou a tentar encontrar alguém para uma segunda revisão. Espero ter novidades em breve. Mas se o @josircg já tiver encontrado alguém, seguimos em frente

**Comment by DanielAlvesLABDH** [comment]
@josircg, não consegui resposta positiva dos contactos que fiz. Alguma sugestão?

**Comment by josircg** [comment]
Não. Mandei até para uma lista grande de pessoas mas ninguém se interessou :(

**Comment by ericbrasiln** [comment]
Olá colegas!
@Mariana-Penna parabéns pela tradução.

Segue minha revisão e comentários.

- [x] 45: alt ainda não foi definido na legenda da imagem
- [x] 68: O resultado atualmente, em um sistema Linux em português (BR) é algo como:
```
wget: falta o URL
Uso: wget [OPÇÃO]... [URL]...

Tente "wget --help" para mais opções.`
```
- [x] 83: substituir: "de de obter" por "de obter"
- [x] 85: substituir "fazer o [download XCode via this link]" por "fazer o [download do XCode através deste link]"
- [x] 87: Acho que vale a pena traduzir os textos com links e atualizar as versões citadas (a da lição é de 2012 e não me parece ter sentido manter).
- [x] 87 a 93: Será que atualmente esse processo ainda é necessário para OS X? Acho que seria interessante atualizá-lo. Eu não uso OS X, então não sei dizer.
- [x] 95 corrigir "faciliar" para "facilita"
- [x] 99 a 101: O comando atual na página do Homebrew é
```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
- [x] 103: E acho que não usa mais o ruby- então valeria apena retirar a primeira frase desse parágrafo.
- [x] 121: a versão mais recente do wget é 1.21.2
- [x] 130: mesma coisa do segundo comentário
- [x] Sobre instalação no Linux: na linha 77 diz que caso o wget não esteja previamente instalado devemos seguir "as instruções abaixo para o OS X". Mas na verdade a instalação varia de acordo com a distribuição Linux. Acho que vale dizer que para distribuições baseadas no Ubuntu, a instalação do wget é através do comando: `sudo apt install wget`. e que em outras distribuições linux é possível instalar com o gerenciador de pacotes da distribuição. 
- [x] 145: substituir "[GNU website]" por "[website do GNU]"
- [x] 182: vale atualizar a versão atual do wget, 1.21.4
- [x] 223 a 228: Não é melhor atualizar essas saídas? Por exemplo, no meu sistema, a saída é:

```
Salvando em: ‘index.html’

index.html              [ <=>                ]  65,60K  --.-KB/s    em 0,04s   

2023-08-08 15:58:54 (1,83 MB/s) - ‘index.html’ salvo [67178]
```

- [ ] 224: Melhor formatar como comando do bash: "\```bash   -r \```"
- [x] 256: indicar alt text da imagem
- [x] 270: substituir " comando -`w 10`" por "comando `-w 10`"
- [x] 270: substituir "o comando `––random-wait`" por "o comando `--random-wait`"
- [x] 294: Melhor formatar como comando do bash: "\```bash -m \```"
- [x] 309: traduzir "wget manual" por "manual do wget"
- [x] Ao longo de toda tradução acho que vale a pena valiar o uso do artigo antes do wget, na linha 304 você utiliza "o wget será...". Me parece que assim soa melhor em português

**Comment by ericbrasiln** [comment]
Eu lembrei de mais uma coisa! 

A lição original usa OS X para se referir ao sistema operacional dos computadores Mac. Mas a partir de 2016, o sistema passou a se chamar macOS. Seria importante atualizar.

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln. Just saw your note and I've made that small change throughout the lesson: https://github.com/programminghistorian/ph-submissions/commit/7a3be0ee2b871681f24c2bb41edd4fb52370d8d3

I'll set myself a reminder to update the published EN and ES lessons next week.

**Comment by josircg** [comment]
Olá pessoal, a @saletefarias aceitou ser a segunda revisora. Obrigado pela disponibilidade Salete!

**Comment by saletefarias** [comment]
Olá! Finalmente cheguei por cá. Iniciei a revisão e logo no primeiro parágrafo me veio um questionamento. Não sei se é o local correto para esta observação, porém aqui vai: No primeiro parágrafo onde temos a Nota do Editor, há um aviso que caso o leitor ou leitora não tenha experiência com linha de comando ele ou ela podem acessar a lição [Introduction to the Bash Command Line](https://programminghistorian.org/en/lessons/intro-to-bash). Só que esta lição está em Inglês e em espanhol (não fica estranho traduzir uma lição para português e sugerir o uso de uma outra que ainda não foi traduzida para o português? Não seria interessante que as "lições-base" fossem traduzidas antes???. Peço desculpas pelo questionamento, provavelmente até já falaram disso por cá, mas me veio este questionamento.

**Comment by DanielAlvesLABDH** [comment]
Olá @saletefarias e muito obrigado por mais esta colaboração. Temos muitas lições onde isso acontece, pois quase todas as lições têm links para outras. O que costumamos fazer é colocar "(em inglês)" logo a seguir ao link para sinalizar que o utilizador vai encontrar uma página noutra língua. Por acaso esta lição em particular está neste momento a ser traduzida. Contudo, tendo em conta que ainda é capaz de demorar (não está a ser fácil encontrar revisores/as) sugiro que aqui seja colocado "(em inglês)" a seguir ao link.

**Comment by saletefarias** [comment]
> Olá @saletefarias e muito obrigado por mais esta colaboração. Temos muitas lições onde isso acontece, pois quase todas as lições têm links para outras. O que costumamos fazer é colocar "(em inglês)" logo a seguir ao link para sinalizar que o utilizador vai encontrar uma página noutra língua. Por acaso esta lição em particular está neste momento a ser traduzida. Contudo, tendo em conta que ainda é capaz de demorar (não está a ser fácil encontrar revisores/as) sugiro que aqui seja colocado "(em inglês)" a seguir ao link.

Obrigada pelo retorno @DanielAlvesLABDH . Pois, eu acabei de receber no email as discussões sobre ela e vi que está a ser traduzida.

**Comment by saletefarias** [comment]
Olá pessoas!
@Mariana-Penna  parabéns pela tradução. Ficou bem fácil de ler.

Segue minha revisão e comentários.

- [x] parágrafo 2: sugiro mudar `direcionada `para `destinada `ou `projetada`

- [x] parágrafo 3: mudar `opera através da linha de comando` por `executado por meio da linha de comando` 

- [x] parágrafo 4: traduzir a legenda da imagem -` A Linha de Comando do Mac, Terminal`

- [x] parágrafo 5: sugiro mudar `servir `por `pode ser útil`

- [x] parágrafo 5: no Brasil usamos muito a palavra `site `no lugar de `website`, mas os dois termos são compreendidos no BR, apenas um apontamento quanto a isto

- [x] parágrafo 5: sugiro substituir `Um comando permite fazer o download do website inteiro para seu computador` por `Um único comando permite fazer o download do site inteiro para seu computador`

- [x] parágrafo 5: substituir `back up` por `backup`

- [x] parágrafo 14: sugiro mudar `[download XCode via this link]` por ` [download do XCode através deste link]`

- [x] parágrafo 15 e parágrafo 16, citam versões antigas do MAC OS e do XCode. Penso que a tradução em português pode ficar com informação de hoje e periodicamente sofrer atualizações. **Atualmente o Xcode está na versão 15** lançada em 18/09/2023

- [x] parágrafo 16: substituir `Por exemplo, o Xcode 3.2 é a versão para o macOS 10.6 Snow Leopard, já o 3.0 é a versão para o macOS 10.5 Leopard, etc`. por **Por exemplo, o Xcode 15 é a versão para o macOS Ventura 13.6, macOS Monterey 12.7 e macOS Big Sur 11.7.10, já o Xcode 12.4 é a versão para o macOS Catalina 10.15.7, etc**.

- [x] parágrafo 20:  o comando agora para instalar o Homebrew é: 

>  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- [x] parágrafo 21: retirar o trecho: `Isto usa a linguagem de programação ruby, incorporada ao macOS, para instalar o Homebrew.`

- [x] Parágrafo 22: **a documentação oficial do Homebrew recomenda executar brew update duas vezes e brew doctor para verificar se há problemas com a instalação.**

- [x] parágrafo 24:  **a versão mais recente e estável do wget é a 1.21.4**. Recomendo não colocar na tradução a versão e deixar o texto assim: `Continuará o download da versão mais recente do wget. Depois que o script parar de ser executado, voltará à janela principal, então digite o seguinte comando no terminal:`

- [x] parágrafo 29: substituir `GNU website` por `website GNU`

- [x] parágrafo 37: Mudar o parágrafo inteiro para: `Para tal, visite este [website ] e faça o download da versão mais atual do wget.exe. O ficheiro estará na primeira linha da tabela e no segundo link na coluna x86, intitulado apenas de exe. Fazer download do arquivo zip pode fazer com que programas antivírus reconheçam o arquivo como perigoso.`

- [x] parágrafo 39: **não seria interessante retirar a referência ao Komodo Edit?? Na tradução fala que o leitor ou leitora possivelmente usou este editor previamente em outras lições. Será???? Penso que podia ser retirado esta informação**.

- [x] parágrafo 49: a minha saída foi 

![Captura de Ecrã wget windows](https://github.com/programminghistorian/ph-submissions/assets/6054157/38dba295-4507-4d28-8a01-968618898f78)

- [x] parágrafo 58: Traduzir legenda da imagem `A graphical representation of how ‘no-parent’ works with wget `para `Uma representação gráfica de como ‘no-parent’ funciona com wget`

- [x] parágrafo 68: substituir `back up` por `backup`

- [x] parágrafo 69: substituir `digital `por `digitais`

Vendo ali algumas observações do @ericbrasiln :
1. este processo ainda é necessário para macOS
2. acho interessante colocar uma saída atualizada como exemplo e dizer que pode ter algumas diferenças (a minha saída - no windows - apresenta alguns números diferentes)

Estas são minhas considerações. 
Abraços

**Comment by Mariana-Penna** [comment]
Olá caras e caros colegas! Primeiramente gostaria de agradecê-los enormemente a todas e todos pelas contribuições. Quero também me desculpar pela demora para realizar os acertos e ponderar as sugestões recebidas. Foi um período um tanto atribulado de adaptações devido ao meu retorno ao Brasil e às dinâmicas da maternidade. Mas enfim tentei atender às expectativas dos colegas revisores, espero que com algum sucesso. Destaco apenas que preciso de alguns esclarecimentos finais em relação à definição do alt e da formatação do comando do basch, conforme sugestões do @ericbrasiln. Deixei desmarcados estes pontos, uma vez que não soube solucionar. Mais uma vez, meu muito obrigada e aguardo para efetuar a revisão final. Abraços calorosos do coração do Brasil!

**Comment by josircg** [comment]
Olá @Mariana-Penna - obrigado pelos últimos ajustes!

Sobre o "alt": todas as imagens devem ter um texto explicando o que elas representam. No caso da linha 45, está faltando a descrição desta imagem em específico. Temos que substituir o texto "A INDICAR" com a descrição da imagem

sobre o bash, seria para colocar a mesma formatação para deixar o -r realçado, tal como nas outras linhas. Ficaria assim:

``` bash
-r
```

Caso ainda tenha dúvida, fico a disposição para te auxiliar.

**Comment by Mariana-Penna** [comment]
Muito obrigada @josircg pelas explicações. Só para confirmar, o alt inclui então uma espécie de meta dado oculto enquanto que a legenda é a informação visível sobre a imagem ou estou confundindo? Inseri praticamente a mesma informação no alt, modifico se for mais adequado. Em relação ao bash, não encontrei na parte mencionada (p. 224) esta ausência de realce, poderia confirmar pra mim?

**Comment by josircg** [comment]
Sobre o alt: é exatamente isso @Mariana-Penna - o alt serve para que robôs e pessoas com baixa/nenhuma visão saibam o que a imagem representa.

na linha 224, tem apenas um -r
quando você coloca a formatação, o texto fica com o fundo cinza. 

Durante a edição, clique no botão "code" para entender melhor como fica o markdown:

![erro](https://github.com/programminghistorian/ph-submissions/assets/634507/eef2a88a-221e-42dd-8d3c-539a96a5a338)

**Comment by ericbrasiln** [comment]
Olá @josircg 
Como vai?

Substituí o Daniel na função de editor-chefe da revista. Estou passando nas _issues_ abertas das noções traduções para acompanhar e me atualizar.

Temos alguma novidade no processo de tradução dessa lição?

Abraços

**Comment by josircg** [comment]
Olá Eric. Pelo meu entendimento, falta apenas a @Mariana-Penna ajustar a tradução a partir das mudanças sugeridas pela revisora e o artigo já estará pronto para ser finalizado.

**Comment by Mariana-Penna** [comment]
Oi colegas, peço desculpas se me equivoquei, mas salvo engano eu já tinha
concluído as revisões, não? Vou verificar mais tarde.
Abraços!

Mariana Affonso Penna
Professora da Licenciatura de História do Instituto Federal de Educação,
Ciência e Tecnologia de Goiás.
https://linktr.ee/mariana.affonso.penna
+55(62)99652-7225 (whatsapp)

Em ter., 23 de abr. de 2024, 07:43, Josir Cardoso Gomes <
***@***.***> escreveu:

**Comment by anisa-hawes** [comment]
Hello @josircg,

Thank you for moving this lesson onto its next Phase!

---

Hello @ericbrasiln,

If you're happy, Charlotte and I can move forwards with the Sustainability + Accessibility checks for this translation. 
Then we can prepare it for publication ✨

**Comment by ericbrasiln** [comment]
Hi @anisa-hawes and @josircg 
I've made some formatting adjustments and added some missing links. Check out this [commit](https://github.com/programminghistorian/ph-submissions/commit/489147264d294004a9d212dbddfbeb85d5f1ebde), please.
I think everything is now in order for us to proceed with the Sustainability + Accessibility checks.

**Comment by anisa-hawes** [comment]
Thank you, @ericbrasiln! Your commit looks good 🙂 

--

Olá @Mariana-Penna and @josircg,

Our Publishing team will now begin Phase 6. Sustainability + Accessibility. This is a series of checks and actions which include reviewing the lesson's typesetting + generating archival links.

- Preview: 
<http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/download-automatico-wget>  


Publisher's sustainability + accessibility actions:
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Addition of alt-text for all figures
- [x] Check/resize images
- [x] Check/adjust image filenames
- [x] Receipt of translator's copyright agreement [PT formulário de declaração](https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf)). _Olá @Mariana-Penna, O nosso formulário de declaração serve para reconhecer os seus direitos de autor e conceder-nos permissão para publicar esta lição. Por favor, pode descarregar [este formulário](https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf), preenchê-lo e enviá-lo por e-mail para Charlotte (publishing.assistant [@] programminghistorian.org)? Muito obrigada._
- [x] Add doi
- [x] Add all contributor names to our list of Unique Contributors
- [x] Add lesson slug to our Annual Count of Published Lessons   

Editorial input to YAML:
- [x] Translation of `avatar_alt:`
- [x] Translation of `abstract:`
- [x] Translation of author(s) bio for `ph_authors.yml`


Files to be transferred to Jekyll:

- .md file: [/esbocos/traducoes/download-automatico-wget.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/download-automatico-wget.md)
- images: [already on Jekyll]
- assets: [none]


Promotion:
- [x] Prepare announcement post (using template)
- [ ] Prepare evergreen posts – @ericbrasiln, could you please provide x2 posts for future promotion via our social media channels? You can add these directly to the `ph-evergreens-twitter-x` spreadsheet that has been shared with you, reply in a comment below, or email them to Charlotte at publishing.assistant[@]programminghistorian.org.

**Comment by anisa-hawes** [comment]
Olá @Mariana-Penna, 

O nosso formulário de declaração serve para reconhecer os seus direitos de autor e conceder-nos permissão para publicar esta lição. Por favor, pode descarregar este formulário, preenchê-lo e enviá-lo por e-mail para Charlotte (publishing.assistant [@] programminghistorian.org)? 

Muito obrigada!
Anisa

**Comment by Mariana-Penna** [comment]
Oi Anisa,

Espero que esteja tudo bem contigo! Só queria te avisar que enviei o formulário de declaração preenchido para a Charlotte. Peço desculpas pela demora. 

Agradeço muito pela oportunidade de colaborar com o Programming Historian!

Qualquer coisa, estou à disposição.

Abraços,
Mariana.

**Comment by anisa-hawes** [comment]
Muito obrigada @Mariana-Penna! 

--

Olá @ericbrasiln,

This translation is ready for your final read! I would be very pleased to connect with you next week to stage it for publication ✨ 

Very best,
Anisa

**Comment by anisa-hawes** [comment]
[Download Automático com Wget](https://programminghistorian.org/pt/licoes/download-automatico-wget) is published!

Congratulations @Mariana-Penna!
Thank you **all** for your contributions 

---

Our suggested citation for this lesson is:

>Ian Milligan, "Download Automático com Wget", traduzido por Mariana Affonso Penna, _Programming Historian em português_ 4 (2024), https://doi.org/10.46430/phpt0047.

We appreciate your help to circulate our social media announcements about this lesson among your networks:
Twitter/X: https://x.com/ProgHist/status/1801202719517966638
Mastodon: https://hcommons.social/@proghist/112608878382346481

---


Sincere thanks.
