### ISSUE TITLE
Propuesta de lección: Georreferenciación y visualización de itinerarios con Recogito y Visone

### ISSUE THREAD

**Issue by jenniferisasi** [programminghistorian/ph-submissions#570]
The _Programming historian en español_ ha recibido una propuesta de lección con el título provisional "Georreferenciación y visualización de itinerarios con Recogito y Visone" por Gimena del Rio Riande y @gabrielcalarco. Los objetivos de la lección son:

- Familiarizar a quienes utilicen el tutorial con el funcionamiento básico de Recogito para la anotación y georreferenciación de textos.
- Generar conciencia sobre las posibilidades que ofrecen las opciones de descarga de Recogito para reutilizar material propio o ajeno a través de otras herramientas complementarias.
- Ofrecer un recurso de visualización geográfica a través del uso de herramientas abiertas.

Si la lección no es entregada en la fecha acordada (alrededor del 24/07/2023), el editor intentará contactar con los autores de la lección. Si no recibe noticias, el ticket se cerrará. Éste podrá abrirse en el futuro a petición de los autores.

El principal contacto para esta lección es @mariajoafana que actuará como editora de la misma. Si se produce algún problema, los autores pueden contactar con nuestra ’ombudsperson' (Silvia Gutiérrez de la Torre - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by jenniferisasi** [comment]
¡Gracias @gabrielcalarco! Queda recibido el primer manuscrito de esta lección. 

@mariajoafana, voy a darle una primera vuelta para asegurarme de que quede resuelto cualquier problema de formato que no deje que salga la previsualización para que ya puedas proceder a una primera lectura (antes de la revisión por pares).

**Comment by anisa-hawes** [comment]
Gracias, @jenniferisasi ✨ 

I'm going to try this in Spanish ! > >

--

Puedes encontrar los archivos clave aquí:

- .md: [/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone.md)
- images: [/images/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/georreferenciacion-visualizacion-con-recogito-y-visone)
- assets: [/assets/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/georreferenciacion-visualizacion-con-recogito-y-visone)

Y puedes revisar la vista previa de la lección aquí:

- <https://programminghistorian.github.io/ph-submissions/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone>

**Comment by jenniferisasi** [comment]
Thank you @anisa-hawes! The preview looks great already. 

@mariajoafana esto significa que la lección está lista para entrar en el proceso editorial del que, a partir de ahora, tomas las riendas. Pero quedo pendiente de si hay alguna pregunta tanto por tu parte como por la parte de los autores ¡Adelante!

**Comment by mariajoafana** [comment]
Hola ! Listo, gracias, me pongo en la tarea

**Comment by mariajoafana** [comment]
Muchas gracias a los autores por una importante lección para PH. Algunos comentarios preliminares antes de invitar a los revisores:
Párrafo 2: Recomiendo explicarle a lector sobre qué tipos de fuentes documentales es posible aplicar metodologías de anotación y georreferenciación. Si bien el tutorial trabaja con un ejemplo específico, es útil para los lectores tener idea de qué tipos de fuentes se pueden trabajar (¿quizás diarios de viajes, descripciones geográficas, novelas, o cualquier tipo de texto rico en referencias de lugares?) Para explicar qué es georreferenciación sugiero enlazar el tutorial ["Georreferenciar con QGIS 2.0"](https://programminghistorian.org/es/lecciones/georreferenciar-qgis)) ya publicado en PH.
Párrafo 4: sugiero añadir una breve explicación sobre qué es anotación semántica, georreferenciación y qué usos comunes se les a estos flujos metodológicos en las humanidades. Esto se puede relacionar con las "humanidades espaciales" o el giro espacial en las humanidades para darle algo de contexto al flujo metodológico. 
Por último sugiero añadir una conclusión al tutorial que resuma lo aprendido.

**Comment by gabrielcalarco** [comment]
¡Muchas gracias @mariajoafana por tus comentarios! En breve estaremos revisando estos puntos que nos señalás en la lección.
¡Saludos!

**Comment by gabrielcalarco** [comment]
¡Hola!
Ya hice los agregados sugeridos por @mariajoafana y envié una pull request con las modificaciones.
Quedamos a su disposición para continuar el proceso.
¡Saludos!

**Comment by mariajoafana** [comment]
Muchas gracias @gabrielcalarco Entramos ahora a la fase de revisores. Les estaré comunicando pronto quiénes serán los revisores del tutorial.

**Comment by mariajoafana** [comment]
El primer revisor de la lección será @apicon a quien agradecemos. Anthony hará la primera ronda de comentarios y sugerencias. Después tendremos un segundo revisor.

Una vez Anthony deje sus comentarios, yo intervendré para recordarles que tendremos una segunda revisión. La recomendación es que esperemos a la segunda revisión antes de proceder a incorporar las modificaciones en el tutorial.

**Comment by apicon** [comment]
Estimado @gabrielcalarco, comparto la serie de comentarios, siguiendo la numeración de las líneas en edición:

35: “información topográfica” puede sonar ambiguo, tal vez podría funcionar mejor “topónimos”.

43: La explicación no es del todo clara, pensando que el texto es para un público amplio, sugiero revisar la idea y su redacción.  

121: Se podría agregar el archivo a descargar, para el caso de lector alguno que no desee hacer el procesamiento del paso anterior, sino que solo desee seguir el paso a paso de lectura.

132: Tal vez valdría la pena agregar anotación, breve y más bien genérica, del significado y las posibilidades de los otros archivos de descarga.

135: Tipeo con doble espacio

142: Dado que el tutorial indica que no es necesario tener experiencia previa en informática, creo que sería conveniente incluir una nota que recomiende los pasos de instalación. Esto incluiría la descompresión del archivo descargado para poder reproducirlo, así como la verificación e instalación de Java (incluso podríamos facilitar el enlace de descarga: https://www.java.com/en/download/), que es un paso previo a otras acciones que podrían parecer obvias.

211: Las conclusiones podrían ser más sugestivas, con el propósito de incorporar una reflexión sobre el potencial de la herramienta para leer, organizar y representar relatos de viaje.

Nota general: recomiendo aumentar la resolución de las imágenes de Recogito, seguí el tutorial en pantalla chica y se veían algo pixeladas

@mariajoafana, les agradezco la invitación a participar.

**Comment by mariajoafana** [comment]
Muchas gracias @apicon por tus comentarios. Como les comenté, antes de hacer la revisión completa del tutorial vamos a solicitar al segundo revisor sus comentarios.

**Comment by gabrielcalarco** [comment]
¡Muchas gracias @apicon! 
Quedamos atentos a los comentarios del segundo revisor para seguir adelante.
¡Saludos!

**Comment by jenniferisasi** [comment]
Pasando por todos los tickets para ver cómo vamos :) @mariajoafana ¿encontraste segundo revisor? Me dejas saber si necesitas de una mano.

**Comment by jenniferisasi** [comment]
Hola a todos. ¿Cómo vamos? @mariajoafana déjame saber si te puedo ayudar en esta fase de revisión.

**Comment by mariajoafana** [comment]
Disculpen la demora. La segunda revisora no ha podido completar su revisión entonces estoy incorporando a otro revisor al proceso.

**Comment by DLA-PSU** [comment]
Hola @mariajoafana gracias por dejarnos saber por aquí.

**Comment by jenniferisasi** [comment]
Hola @mariajoafana ¡gracias por dejarnos saber!

**Comment by mariajoafana** [comment]
Hola de nuevo, el segundo revisor del tutorial será @sebastiandiaz Sebastián hará la segunda ronda de comentarios y sugerencias. 
Una vez Sebastián deje sus comentarios, los autores podrán proceder a incorporar las modificaciones en el tutorial. Yo estaré atenta para resolver preguntas que puedan surgir en el proceso.

**Comment by mariajoafana** [comment]
@sebastiandiaz Te recomendamos leer toda la conversación sobre la revisión del tutorial y sobre todo los comentarios del primer revisor antes de hacer tus comentarios

**Comment by jenniferisasi** [comment]
Estimados, ¿cómo va todo? Paso por aquí para preguntar si @sebastiandiaz tiene fecha de entrega de su revisión para seguir a las siguientes fases de publicación. ¡Gracias!

**Comment by sebastiandiaz** [comment]
Hola, si disculpen la demora, estoy en cierre de semestre, lo puedo
entregar el 3 de junio

**Comment by jenniferisasi** [comment]
¡Gracias @sebastiandiaz!

**Comment by mariajoafana** [comment]
Hola @sebastiandiaz estamos atentos a tu revisión del tutorial.

**Comment by sebastiandiaz** [comment]
8: falta un punto (.)  despues de [La Argentina Manuscrita](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/georreferenciacion-visualizacion-con-recogito-y-visone/fragmento_La_Argentina_manuscrita_tutorial_recogito_visone.txt) 

14: agregar “topónimos” : El algoritmo analiza el texto e intenta identificar todas las palabras que pueden ser topónimos o nombres de lugares.

26: eliminar “en” de la siguiente frase. “Por ejemplo, en el comentario puedes añadir que no estás seguro de esa marca o que en hoy en día tiene otro nombre, etc.”

32: sobra una comilla antes de “Relations: “cambia el modo de anotación de Recogito a “Relations”, y limitar negrilla a “Relations” 

38: ¿falta la palabra “no”? “Te recomendamos que abras el archivo .csv que descargaste de la sección Annotations y revises que todas las entradas tengan cargadas los datos de longitud y latitud, ya que si esto [no] sucede debes cambiar la entrada de gazetteer utilizada para marcar ese lugar por otra que sí incluya la información geográfica.”

53: conviene llamar las figuras 15 y 16 dentro del texto. Creo que este comentario se puede extender al resto del instructivo, pero en este párrafo es crítico

62: cambiar “unos momentos” por  “un momento”. 

67: en este párrafo cambió el estilo de los botones de negrilla a comillas. Unificar.

Al igual que Anthony considero que las conclusiones podrían ser más sugestivas, y ojalá linkear a ejemplos mas concretos del tipo de cosas que se han hecho o pueden hacer con esto.

**Comment by sebastiandiaz** [comment]
Hola perdón por tan largo retraso. Creo que esos son mis comentarios. Son
solo de forma.... espero sean de ayuda :) pero quedo atento a ayudar en lo que necesiten, ahora tengo un poco mas de tiempo.

Saludosy gracias por la oportunidad

**Comment by sebastiandiaz** [comment]
Los puse en la cadena, pero aqui van también:

8: falta un punto (.) despues de La Argentina Manuscrita
<https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/georreferenciacion-visualizacion-con-recogito-y-visone/fragmento_La_Argentina_manuscrita_tutorial_recogito_visone.txt>

14: agregar “topónimos” : El algoritmo analiza el texto e intenta
identificar todas las palabras que pueden ser topónimos o nombres de
lugares.

26: eliminar “en” de la siguiente frase. “Por ejemplo, en el comentario
puedes añadir que no estás seguro de esa marca o que en hoy en día tiene
otro nombre, etc.”

32: sobra una comilla antes de “Relations: “cambia el modo de anotación de
Recogito a “Relations”, y limitar negrilla a “Relations”

38: ¿falta la palabra “no”? “Te recomendamos que abras el archivo .csv que
descargaste de la sección Annotations y revises que todas las entradas
tengan cargadas los datos de longitud y latitud, ya que si esto [no] sucede
debes cambiar la entrada de gazetteer utilizada para marcar ese lugar por
otra que sí incluya la información geográfica.”

53: conviene llamar las figuras 15 y 16 dentro del texto. Creo que este
comentario se puede extender al resto del instructivo, pero en este párrafo
es crítico

62: cambiar “unos momentos” por “un momento”.

67: en este párrafo cambió el estilo de los botones de negrilla a comillas.
Unificar.

Al igual que Anthony considero que las conclusiones podrían ser más
sugestivas, y ojalá linkear a ejemplos mas concretos del tipo de cosas que
se han hecho o pueden hacer con esto.

**Comment by gabrielcalarco** [comment]
Hola,

En los próximos días estaremos revisando sus sugerencias, y les escribiremos cuando lo tengamos listo o si nos surge alguna duda.

¡Saludos!

**Comment by mariajoafana** [comment]
Gracias @sebastiandiaz por las sugerencias. Quedo atenta para cualquier duda que surja en el proceso.

**Comment by sebastiandiaz** [comment]
Gracias a ustedes. Creo que lo mas importante esvaue en la intro y la
conclusion pongab ejemplos del tipo de cosas que se pueden hacer, hechos o
no con estas herranientas. El tipo de cosas

**Comment by anisa-hawes** [comment]
Hola Gabriel @gabrielcalarco y Gimena,

This phase is an opportunity for you to revise your draft in response to the peer reviewers' feedback. Feel free to ask your editor @mariajoafana questions if you are unsure.

Please make revisions via direct commits to your file: [/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone.md). Gabriel @gabrielcalarco, I have already sent you an invitation to grant you Write access to your file. @charlottejmc and I are here to help if you encounter any difficulties.

When you and Maria-José are all happy with the revised draft, the Managing Editor @jenniferisasi will read it through before we move forward to the next stage which is Phase 6: Sustainability + Accessibility checks.

Muchas gracias!

**Comment by jenniferisasi** [comment]
Gracias a todos and thanks @anisa-hawes. Estaré pendiente de la evolución de la última revisión para hacer la última lectura y poner en marcha la publicación de la lección.

**Comment by gabrielcalarco** [comment]
Hola a todos y todas,

Quería avisarles que ya hicimos las modificaciones solicitadas por los revisores.

En cuanto al comentario sobre la resolución de las imágenes, observé que el problema está en los archivos de imagen subidos al repositorio, pero no en los archivos que enviamos por mail, así que me pueden avisar si necesitan que reenvíe ese mensaje.

Quedamos a disposición para continuar con el proceso de edición.

Muchas gracias a los revisores por sus recomendaciones,

¡Saludos!
Gabriel.

**Comment by jenniferisasi** [comment]
¡Gracias, @gabrielcalarco! 

Cuando @mariajoafana me diga si está de acuerdo con los últimos cambios realizados, leeré la lección y podrá pasar a fase de copy-editing. 

Respecto a las imágenes, comprobando de nuevo el email veo que de nuestro lado las imágenes son de baja resolución (69KB, 48KB, etc.) y al abrirlas las veo borrosas igualmente - será que al añadir tantas el email mismo las bajó de calidad? De todos modos, creo que solo habría que arreglar la 2, 3 y 4 porque el resto se ven bien. 

Seguimos,

Jenn

**Comment by mariajoafana** [comment]
Hola! De acuerdo con los últimos cambios realizados.

**Comment by jenniferisasi** [comment]
Estimades todes: 

Gracias @mariajoafana por confirmarnos tu lectura. Acabo de re-leer la lección [switching to English for @anisa-hawes] and my only suggestion is that we add a short reference to some of our lessons on network analysis on paragraph n.41. If you agree, @gabrielcalarco, we/I can take care of that.

Other than that, the lesson is ready for our next phase, that is, copy editing! This can be done most probably during August if not earlier and be published by August/early September :)

**Comment by anisa-hawes** [comment]
Gracias, @jenniferisasi!

--

We are looking forward to supporting the next phases of this lesson's progress towards publication, @gabrielcalarco and @mariajoafana. Thank you for all your work 🙂

**Comment by charlottejmc** [comment]
Hello @gabrielcalarco,

Would you be able to try emailing me figures 2, 3 and 4 again? You can send them to publishing.assistant[@]programminghistorian.org, either all at once, or in 3 separate emails, if you feel that could help with the quality. 

Thank you!

**Comment by gabrielcalarco** [comment]
Hello @charlottejmc,

I have just sent the email with the attached images and also added the CSV file with the annotations suggested by Anthony.

Thank you!

**Comment by charlottejmc** [comment]
Hi @gabrielcalarco,

I've uploaded the 4 new images and you can see how they render in the [lesson preview](https://programminghistorian.github.io/ph-submissions/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone). Thanks also for your annotated CSV file – I've renamed it [lugares-marcados.csv](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/georreferenciacion-visualizacion-con-recogito-y-visone/lugares-marcados.csv) and updated the link which you helpfully provided in the lesson text.

Thanks again for your energy and your patience with this! ✨

**Comment by jenniferisasi** [comment]
¡Gracias a todos! I have been in touch with the Publishing Team and I am delighted to say that this lesson is ready to enter the last phase, that is, copyediting :) I will be in touch to confirm timelines with the copyeditor but it should ready to publish in early September.

**Comment by anisa-hawes** [comment]
Hola Gabriel @gabrielcalarco,

Esta lección está ahora con nuestro/a corrector/a de estilo Gimena @hdlabconicet, cuyo objetivo es completar el trabajo para ~septiembre.

@gabrielcalarco, tenga en cuenta que no tendrá acceso directo para realizar más ediciones en sus archivos durante esta fase.

Cualquier revisión adicional se puede discutir con su editora @mariajoafana una vez completadas las correcciones. 

Gracias por su comprensión.

Anisa

**Comment by anisa-hawes** [comment]
Hola Gabriel @gabrielcalarco and @jenniferisasi,

Happy September! 🍃 

@charlottejmc and I have been in touch with Gimena @hdlabconicet and we are expecting that the copyedit will be ready by the end of next week 13th September.

Thanks to all!

**Comment by jenniferisasi** [comment]
Greetings, all! Thanks for the update @anisa-hawes, looks like we are almost ready to publish this wonderful lesson 💫

**Comment by anisa-hawes** [comment]
Hola Gabriel @gabrielcalarco and @jenniferisasi,

A quick update to let you know that we are now expecting Gimena's @hdlabconicet copyedits will be ready by the end of next week 20th September.

Thank you for your patience ☺️

**Comment by charlottejmc** [comment]
Hello @jenniferisasi,

This lesson's sustainability + accessibility checks are in progress.

- Preview: 
 
<http://programminghistorian.github.io/ph-submissions/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone>  

Publisher's sustainability + accessibility actions:
- [x] Copyediting
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Check/resize images
- [x] Check/adjust image filenames
- [x] Receipt of author(s) copyright agreement – Hola @gabrielcalarco, nuestro formulario de declaración es para reconocer sus derechos de autor y concedernos permiso para publicar esta lección. Por favor, ¿podría descargar y rellenar [este formulario](https://programminghistorian.org/assets/forms/Derechos-de-autor-y-de-publicacion.pdf)? Envíelo por e-mail a (publishing.assistant [@] programminghistorian.org). Muchas gracias.
- [x] Request DOI
- [x] Remove outside contributors from ph-submissions   

Authorial / editorial input to YAML:
- [x] Define `difficulty:`, based on [the criteria set out here](https://github.com/programminghistorian/jekyll/wiki/defining-difficulty)
- [x] Define the research `activity:` this lesson supports (acquiring, transforming, analysing, presenting, or sustaining) **Choose one**
- [x] Define the lesson's `topics:` (api, python, data-management, data-manipulation, distant-reading, get-ready, lod ["Linked Open Data"], mapping, network-analysis, web-scraping, website ["Digital Publishing"], r, machine-learning, creative-coding, web-archiving or data-visualization) **Choose one or more. Let us know if you'd like us to add a new topic**. Topics are defined in [/_data/topics.yml](/https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/topics.yml).
- [x] Provide `alt-text` for all figures
- [x] Provide a short `abstract:` for the lesson
- [x] Agree an avatar (thumbnail image) to accompany the lesson

>The image must be:
>- copyright-free
>- non-offensive
>- an illustration (not a photograph)
>- at least 200 pixels width and height
>Image collections of the [British Library](https://www.flickr.com/photos/britishlibrary/albums), [Internet Archive Book Images](https://www.flickr.com/photos/internetarchivebookimages/), [Library of Congress Maps](https://www.loc.gov/maps/collections/) as well as their [Photos/Prints/Drawings](https://www.loc.gov/photos/collections/) or the [Virtual Manuscript Library of 
>Switzerland](https://www.e-codices.unifr.ch/en) are useful places to search

- [x] Provide `avatar_alt:` (visual description of that thumbnail image)
- [x] Provide author(s) bio for `ph_authors.yml` using this template:

Files we are preparing for transfer to Jekyll:

- .md file: [/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/borradores/originales/georreferenciacion-visualizacion-con-recogito-y-visone.md)
- images: [/images/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/georreferenciacion-visualizacion-con-recogito-y-visone)
- assets: [/assets/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/assets/georreferenciacion-visualizacion-con-recogito-y-visone) 
- original avatar: [/gallery/originals/georreferenciacion-visualizacion-con-recogito-y-visone-original](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/gallery/originals/georreferenciacion-visualizacion-con-recogito-y-visone-original.png)
- gallery avatar: [/gallery/georreferenciacion-visualizacion-con-recogito-y-visone](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/gallery/georreferenciacion-visualizacion-con-recogito-y-visone.png)

Promotion:
- [x] Prepare announcement post (using template)
- [x] Prepare evergreen posts – @jenniferisasi, could you please provide x2 posts for future promotion via our social media channels? You can add these directly to the `ph-evergreens-twitter-x` spreadsheet that has been shared with you, or email them to me at publishing.assistant[@]programminghistorian.org.

Publisher's post-publication tasks:
- [x] Add lesson slug to the Annual Count of Published Lessons
- [x] Update the ph_data folder in the ph-contributors repository

**Comment by charlottejmc** [comment]
Hi @Gimena and @gabrielcalarco, 

For the avatar (lesson's thumbnail image), would you like to use a screenshot of a visualisation you've created yourselves with Visone/Recogito? If you have a square, clear, screenshot of a project you particularly like, we could perhaps use that!

Otherwise, we can keep looking through the options mentioned in [my comment above](https://github.com/programminghistorian/ph-submissions/issues/570#issuecomment-2458877589).

**Comment by jenniferisasi** [comment]
Hi @charlottejmc! Just left the two promo posts on the spreadsheet. 

I would say this lesson is on a `difficulty: 1` (Beginner)
and `topics:`can be ` get-ready, mapping, data-visualization`
though I would certainly love to hear from the authors :)

**Comment by hdlabconicet** [comment]
Hi @charlottejmc!

Do you think this image will be usefull for the lesson's thumbnail?

![recogito_visone](https://github.com/user-attachments/assets/08b20379-5d16-4394-8f16-7fdb632a760d)

**Comment by charlottejmc** [comment]
Hello @hdlabconicet / @Gimena,

I think the textbox on this image would not render very well as a small thumbnail on our site, unfortunately... You can see our other lessons' thumbnails in our [Spanish directory](https://programminghistorian.org/es/lecciones/) for inspiration! 

Maybe a screenshot that shows the 'itineraries' you are building?

Otherwise, we have some suggestions of resources to look through:

>The image must be:
>- copyright-free
>- non-offensive
>- an illustration (not a photograph)
>- at least 200 pixels width and height
>Image collections of the [British Library](https://www.flickr.com/photos/britishlibrary/albums), [Internet Archive Book Images](https://www.flickr.com/photos/internetarchivebookimages/), [Library of Congress Maps](https://www.loc.gov/maps/collections/) as well as their [Photos/Prints/Drawings](https://www.loc.gov/photos/collections/) or the [Virtual Manuscript Library of 
>Switzerland](https://www.e-codices.unifr.ch/en) are useful places to search

One last thing we also need from you is the signed [copyright agreement](https://programminghistorian.org/assets/forms/Derechos-de-autor-y-de-publicacion.pdf) (@Gimena or @gabrielcalarco, only one is necessary!) 

Thank you for your help!

--- 

@jenniferisasi, thank you for providing the metadata. I think `presenting` is also an appropriate activity here.

**Comment by hdlabconicet** [comment]
Hello,

We are sending you another image that we believe could work for the thumbnail:

![Trapalandacuadrada](https://github.com/user-attachments/assets/0955392a-99ff-4ac9-bfe8-ecf881d9df76)

Regarding the difficulty level and the topics suggested by @jenniferisasi, they seem fine to us.

Best regards!

**Comment by charlottejmc** [comment]
Thanks @hdlabconicet, I think that could be a good fit! Do you by any chance have the original link, or a higher quality picture that I could work with?

**Comment by gabrielcalarco** [comment]
Hello @charlottejmc 

Let us know if the attached image works better.

It is from the David Rumsay's collection: [https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~288459~90060143:trapalanda?annotId=356083795](https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~288459~90060143:trapalanda?annotId=356083795)

Best wishes!
![tutorial_recogito_visone_portada](https://github.com/user-attachments/assets/ddf3f7dc-6ec1-406c-92b6-e67d51692725)

**Comment by charlottejmc** [comment]
Thank you very much @gabrielcalarco and @Gimena, this new option is great! I've set it up for you.  

Would "Mapa francês da América do Sul do século XVIII" be an appropriate alt-text description of this image?

**Comment by gabrielcalarco** [comment]
Hi @charlottejmc,

That description is ok, but in Spanish would be:

"Mapa francés de América del Sur del siglo XVIII."

Best regards!

**Comment by charlottejmc** [comment]
You're completely right @gabrielcalarco, thank you – I chose the wrong language for the translation software's output! 😅

**Comment by anisa-hawes** [comment]
[Georreferenciación y visualización de itinerarios con Recogito y Visone](https://programminghistorian.org/es/lecciones/georreferenciacion-visualizacion-con-recogito-y-visone) is published!

Congratulations @Gimena, @gabrielcalarco, and the whole team at @hdlabconicet!
Thank you to **all** who have contributed, including the reviewers @apicon & @sebastiandiaz + editor @mariajoafana!

---

Our suggested citation for this lesson is:

>Gabriel Calarco y Gimena del Río Riande, "Georreferenciación y visualización de itinerarios con Recogito y Visone", Programming Historian en español 8 (2024), https://doi.org/10.46430/phes0067..

We appreciate your help to circulate our social media announcements about this lesson among your networks:


Bluesky: https://bsky.app/profile/proghist.bsky.social/post/3ld4llehe7k2r
Mastodon: https://hcommons.social/@proghist/113640571521324882

---


Sincere thanks from all at PH ✨

**Comment by mariajoafana** [comment]
Hi all, I'm sorry to reopen this ticket, but I noticed that image 5 in the tutorial does not correspond to the image cited. It shows an imagen of the sharing options in Recogito. The image should be of the place annotation options in the interface.

**Comment by charlottejmc** [comment]
Thank you for bringing this up, @mariajoafana. I've opened [Issue #3496](https://github.com/programminghistorian/jekyll/issues/3496) in our Jekyll repository, which is where we can make changes to published lessons. Could you reply in that issue with some further information? For example, is the image needed already included (but misnumbered) in the [images](https://github.com/programminghistorian/jekyll/tree/gh-pages/images/georreferenciacion-visualizacion-con-recogito-y-visone), or do we need to request a new screenshot?
