### ISSUE TITLE
Tradução de lição: "Introdução à Linha de Comando Bash"

### ISSUE THREAD

**Issue by DanielAlvesLABDH** [programminghistorian/ph-submissions#573]
O Programming Historian em Português recebeu a proposta de tradução da lição [Introduction to the Bash Command Line](https://programminghistorian.org/en/lessons/intro-to-bash). Agradeço ao @ericbrasiln pela proposta. Já fiz uma primeira revisão da mesma. @anisa-hawes irá fazer as verificações necessárias. Irei convidar um editor para acompanhar a revisão desta tradução.

**Comment by DanielAlvesLABDH** [comment]
O @josircg aceitou ficar como editor desta proposta de tradução. Ele conduzirá o processo e irá fazer os convites para os revisores. Muito obrigado!

**Comment by anisa-hawes** [comment]
Obrigada, @DanielAlvesLABDH.

Pode encontrar os ficheiros principais aqui:

- .md: [/pt/esbocos/traducoes/introducao-linha-comando-bash](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/introducao-linha-comando-bash.md)
- images: [/images/intro-to-bash](https://github.com/programminghistorian/ph-submissions/tree/gh-pages/images/intro-to-bash)
- assets: [none]

E pode consultar a pré-visualização da lição aqui:

- <http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/introducao-linha-comando-bash>

---

I won't attempt to write this in Portuguese (!) but I note that there is one heading and two column titles which haven't yet been translated from English:

Reference Guide (line 377) 
Command (line 381)
What It Does (line 381)

**Comment by DanielAlvesLABDH** [comment]
Thank you @anisa-hawes. Always alert and very helpful. 
@ericbrasiln pode verificar o que falta, por favor?

**Comment by anisa-hawes** [comment]
Hello @ericbrasiln. It is just these words:

"Reference Guide" (line 377)
"Command" (line 381)
"What It Does" (line 381)

--

"Guia de referência" ?
"Comando" ?
"O que ele faz" ?

(I just didn't want to add the Portuguese words there without any confidence).

**Comment by ericbrasiln** [comment]
Thanks @anisa-hawes 
Seu português está ótimo. 😄

**Comment by anisa-hawes** [comment]
Obrigada @ericbrasiln. I've made those small updates: https://github.com/programminghistorian/ph-submissions/commit/884dba1bd0724f955ddc155cb6ee45be7d675fd2

**Comment by DanielAlvesLABDH** [comment]
Olá @josircg, ainda não conseguiu encontrar revisores para esta tradução?

**Comment by josircg** [comment]
Infelizmente não. Na verdade, a minha fonte de revisores secou. Tenho buscado no IBICT, na comunidade de software livre a qual pertenço e agora também com alunos da FGV.

**Comment by DanielAlvesLABDH** [comment]
Obrigado @josircg. Pergunto à equipa @programminghistorian/portuguese-team se têm sugestões?

**Comment by DanielAlvesLABDH** [comment]
O Ricardo Basílio @ricardobasiliopt concordou em ser um dos revisores desta tradução. Desde já agradeço.

**Comment by ericbrasiln** [comment]
Boa tarde, @josircg 

A Diana dos Santos aceitou ser revisora desta tradução. Eu já enviei o convite para ela fazer parte do repositório e caso você concorde, vou marcá-la aqui para que ela inicie a revisão.
Abraços

**Comment by dianamsmpsantos** [comment]
Por favor usem Diana Santos e não Diana dos Santos

**Comment by josircg** [comment]
Excelente Eric! Obrigado pela indicação! Seja bemvinda @dianamsmpsantos

**Comment by dianamsmpsantos** [comment]
Obrigada!
Aqui vão as minhas sugestões:
Sugiro dizer A shell e não o shell, visto que é descrita com UMA interface.
- [linha 45] Interfaces de linha de comando possuem vantagens para usuários de computador que precisam -> As interfaces de linha de comando possuem vantagens para usuários de computador que precise
- [linha 46] por padrão -> por norma
- [linha 46] atingir tarefas similares -> desempenhar tarefas similares
- [linha 48] é um interpretador de linha de comando que provê uma interface de usuário para o sistema operacional -> é uma interface de linha de comando no sistema operacional
- [linha 48] pelo seus sistema -> pelo seu sistema
- [linha 52] Para aqueles(as) com macOS, e a maioria das distribuições Linux, -> Usuários de macOS, e a maioria das distribuições Linux:
- [linha 52] Para aqueles com Windows,-> Usuários de Windows:
- [linha 52] Ele pode ser instalado após o download do -> Primeiro, obtenham o
- [linha 56] por padrão -> por norma
- [linha 66] 'Novel' é um agradável -> 'Novel' é agradável
- [linha 66] em geral, ou pôr todos os nomes de comandos em inglês, ou em português. Misturar Properties com Propriedades não me parece bem...
- [linha 72] Se Movendo -> Passeando (porque senão parece para um leitor português "se" no sentido condicional)
- [linha 74] paço -> passo
- [linha 78] apertar Enter -> premir/carregar 
- [linha 78] O caminho -> o caminho
- [linha 78] home/USERNAME -> /home/USERNAME
- [linha 80] aqueles utilizando Windows e aqueles utilizando macOS/Linux -> quem utiliza Windows e quem utiliza macOS/Linux
- [linha 84] uma vez que -> desde que
- [linha 86] de quais ficheiros estão -> dos ficheiros que estão
- [linha 92] flags (bandeiras) -> sinalizadores
- [linha 92] provê ao computador -> fornecem ao computador
- [linha 92] qual tipo de retorno ou manipulação você pretende realizar -> o tipo de retorno ou manipulação que você pretende realizar
- [linha 98] você se ficará mais familiarizado -> você ficará mais familiarizado
- [linha 100] aperte -> digite
- [linha 128] bites -> bits
- [linha 128] Entretanto -> Contudo
- [linha 128] Comumente, -> Em geral,
- [linha 128] medida de como -> medida como
- [linha 150] explorado -> explorador
- [linha 166] visite seu diretório documentos -> visite seu diretório de documentos (ou colocar estes nomes de diretorios noutra font, como está depois na mesma linha?)
- [linha 166] para se mover para uma irmã, você deve retornar ao pai comum. -> para se mover para uma localização irmã, você deve retornar à "mãe" comum. 
- [linha 168] no seus sistema -> no seu sistema
- [linha 186] Certifique-se de deixar -> Certifique-se de que deixou
- [linha 190] opera-los -> operá-los
- [linha 194] Você sempre pode -> Você pode sempre
- [linha 200] sugiro mudar "autocompletar" para "completar" em todos os casos
- [linha 202] você pode simplesmente -> pode simplesmente
- [linha 214] pode informar ao computador -> pode indicar ao computador 
- [linha 214] Por padrão, deve ser o TextEdit no macOS ou Notepad no Windows. -> O padrão deve ser o TextEdit no macOS ou o Notepad no Windows
- [linha 240] Você também deseja mudar -> Você também pode desejar mudar
- [linha 252] renomeado -> mudado o nome a
- [linha 258] aperte Enter -> depois Enter
- [linha 260 e 262] em-dobro -> duplicado
- [linha 268] apertar Enter -> depois Enter
- [linha 268] em ordem alfabética -> por ordem alfabética
- [linha 268] se você precisa -> se você precisar
- [linha 268] é ? que é um -> é ?, que é um
- [linha 282] há um bom guia (em inglês) disponível -> existe um bom guia em inglês.
- [linha 284] uma prêmio -> um prêmio
- [linha 286 e 288] irá lhe mover uma página -> irá mudar para uma página
- [linha 302] penso que os comandos do VIM são em inglês
- [linha 320] deletar -> apagar, ou remover...
- [linha 353] O comando ./ refere-se -> ./ refere-se
- [linha 353] Este é um comando realmente valioso -> Esta é um elemento da linguagem de comandos realmente valioso
- [linha 367] Conclusões -> Conclusão
- [linha 371] aqueles de vocês no macOS ou Linux -> quem usa macOS ou Linux
- [linha 371] de quais processos estão -> dos processos que estão
- [linha 373] de nível iniciante -> introdutória
- [linha 375] Antes que perceba -> Antes que se aperceba

Muitas das minhas sugestões tentam dar uma versão mais fácil de compreender a um leitor português. Não são exatamente correções da tradução, que está bem em português do Brasil, mas para tornar mais claro para uma audiência portuguesa.

Espero que sejam úteis
Diana

**Comment by josircg** [comment]
Obrigado @dianamsmpsantos! 

No Brasil, os profissionais de TI chamam "o" shell e em Portual, após consulta com alguns amigos, fui informado que alguns falam "o" e outros falam "a". Dessa forma, sugiro manter o "o" shell.

**Comment by ericbrasiln** [comment]
Olá @josircg 

Farei as alterações sugeridas na próxima semana!

Obrigado @dianamsmpsantos pelos comentários

**Comment by ericbrasiln** [comment]
Olá @josircg 
Fiz as alterações propostas pela @dianamsmpsantos. 
As mudanças podem ser vistas [aqui](https://github.com/programminghistorian/ph-submissions/commit/9c669e1b6bc120044d2db91a34327d2e3ea947a7).

Como a revisão da Diana foi bastante cuidadosa e trata-se de uma tradução, o que acha de avançarmos com o processo de publicação mesmo com apenas uma revisão?

Estamos tentando zerar as issues em aberto de traduções até o fim do ano.

Qualquer dúvida é só me marcar aqui.
Abraços

**Comment by josircg** [comment]
Excelente @ericbrasiln ! Concordo plenamente que um revisor é suficiente para as traduções (na verdade, são dois revisores porque o editor também revisa). Últimos ajustes:

* linha 184: não existe o comando explorer no Linux. Assim, deve-se substituir "no macOS e Linux" para -> "no macOS" 
* linha 217: idem
* linha 387: idem

Ainda sobre as linhas 184 e 217: apesar de não existir essa info no texto original, seria interessante incluir um parágrafo 

"no Linux: vim 2600-0.txt"

* As imagens não estão aparecendo no preview. Elas serão incluídas depois?
* Senti falta também já incluir os alt-texts das imagens.

De resto já está pronto para ser finalizado.

**Comment by anisa-hawes** [comment]
Olá Josir @josircg,

Apologies. A small mistake on our side was causing the problem with the figures - that's corrected now 🙂 

< http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/introducao-linha-comando-bash >

**Comment by ericbrasiln** [comment]
Oi @josircg 
Que ótimo, vamos avançar.

Apenas um comentário sobre a questão do `explorer`. Seu comentário diz:

> Últimos ajustes:
> 
>     * linha 184: não existe o comando explorer no Linux. Assim, deve-se substituir "no macOS e Linux" para -> "no macOS"
> 
>     * linha 217: idem
> 
>     * linha 387: idem
> 
> 
> Ainda sobre as linhas 184 e 217: apesar de não existir essa info no texto original, seria interessante incluir um parágrafo
> 
> "no Linux: vim 2600-0.txt"

Entretanto, nessas linhas as frases são "Por fim, tente `open .` no macOS e Linux ou `explorer .` no Windows.

Portanto, não está dizendo que é para usar `explorer` no Linux em nenhuma dessas linhas.

Acabei de incluir os alt-texts das imagens: [84870ab](https://github.com/programminghistorian/ph-submissions/commit/84870ab76228e7e7cb59ee502795345ccb6bdb2b)

Qualquer coisa, é só falar.

**Comment by josircg** [comment]
Troquei o texto! Desculpe! É o comando open que não existe no Linux!
Na verdade, o comando open faz outra função diferente do open no MacOS.

**Comment by ericbrasiln** [comment]
@josircg Mas o `open` no Linux faz o que está pedindo na lição, não? Abre o arquivo com o programa padrão.

> Troquei o texto! Desculpe! É o comando open que não existe no Linux! Na verdade, o comando open faz outra função diferente do open no MacOS.

**Comment by josircg** [comment]
Não Eric. O open abre um programa em um Virtual Terminal e depende de uma configuração especial. Dá para implementar a mesma funcionalidade que o open do Mac. Mas isso não vem configurado "de fábrica".
https://www.hongkiat.com/blog/linux-command-open/

**Comment by charlottejmc** [comment]
Hello @ericbrasiln,

This lesson's sustainability + accessibility checks are in progress.

- Preview: 

<http://programminghistorian.github.io/ph-submissions/pt/esbocos/traducoes/introducao-linha-comando-bash>  

Publisher's sustainability + accessibility actions:
- [x] Typesetting
- [x] Addition of Perma.cc links
- [x] Addition of alt-text for all figures
- [x] Check/resize images
- [x] Check/adjust image filenames
- [x] Receipt of translator's copyright agreement – Olá @ericbrasiln, o nosso formulário de declaração serve para reconhecer os seus direitos de autor e conceder-nos permissão para publicar esta lição. Por favor, pode descarregar [este formulário](https://programminghistorian.org/assets/forms/Direitos-autorais-e-permissao-para-publicar.pdf), preenchê-lo e enviá-lo por e-mail para mim (publishing.assistant [@] programminghistorian.org)? Muito obrigada.
- [x] Request DOI
- [ ] ~~Remove outside contributors from ph-submissions~~

Editorial input to YAML:
- [x] Translation of `avatar_alt:`
- [x] Translation of `abstract:`
- [x] Translation of author(s) bio for [ph_authors.yml](https://github.com/programminghistorian/jekyll/blob/gh-pages/_data/ph_authors.yml)

Files we are preparing for transfer to Jekyll:
 
- .md file: [/esbocos/traducoes/introducao-linha-comando-bash.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/pt/esbocos/traducoes/introducao-linha-comando-bash.md)
- images: [already on Jekyll]
- assets: [none]


Promotion:
- [x] Prepare announcement post (using template)
- [x] Prepare evergreen posts – @ericbrasiln, could you please provide x2 posts for future promotion via our social media channels? You can add these directly to the `ph-evergreens-twitter-x` spreadsheet that has been shared with you, reply in a comment below, or email them to me at publishing.assistant[@]programminghistorian.org.

Publisher's post-publication tasks:
- [x] Add lesson slug to the Annual Count of Published Lessons
- [x] Update the ph_data folder in the ph-contributors repository

**Comment by ericbrasiln** [comment]
> Não Eric. O open abre um programa em um Virtual Terminal e depende de uma configuração especial. Dá para implementar a mesma funcionalidade que o open do Mac. Mas isso não vem configurado "de fábrica". https://www.hongkiat.com/blog/linux-command-open/

Caramba! eu achava que era um comando nativo também. Nesse caso, removi a informação erra da tradução.

**Comment by anisa-hawes** [comment]
[Introdução à Linha de Comando Bash](https://programminghistorian.org/pt/licoes/introducao-linha-comando-bash) is published!

Congratulations @ericbrasiln !
Thank you to **all** who have contributed, @dianamsmpsantos as reviewer, and @josircg as editor!

---

Our suggested citation for this translation is:

>Ian Milligan e James Baker, "Introdução à Linha de Comando Bash", traduzido por Eric Brasil, Programming Historian em português 4 (2024), https://doi.org/10.46430/phpt0049.

We appreciate your help to circulate our social media announcements about this lesson among your networks:

Bluesky: https://bsky.app/profile/proghist.bsky.social/post/3ld4lvr3qdc2r
Mastodon: https://hcommons.social/@proghist/113640580514924160

---


Sincere thanks from all at PH ✨
