### ISSUE TITLE
Traduction en français : Du Html à une liste de mots (partie 2)

### ISSUE THREAD

**Issue by marie-flesch** [programminghistorian/ph-submissions#584]
_Programming Historian_ en français a reçu une proposition de traduction de la leçon [From HTML to List of Words (part 2)](https://programminghistorian.org/en/lessons/from-html-to-list-of-words-2) de la part de notre cher Célian Ringwald (@datalogism), qui avait déjà traduit [la partie 1](https://github.com/programminghistorian/ph-submissions/issues/560). 

La traduction a été réalisée il y a un petit bout de temps. Le suivi éditorial de la partie 1 touchant à sa fin, nous sommes prêt·es à enfin lancer le suivi de la partie 2 :tada:

C'est @emilienschultz  qui se chargera du suivi de la leçon ; il la prendra en charge dès qu'Anisa aura fait les vérifications nécessaires :)

**Comment by anisa-hawes** [comment]
Bonjour @marie-flesch,

Vous trouverez les fichiers ici : 
- .md file: [/en-cours/traductions/du-html-a-une-liste-de-mots-2](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/du-html-a-une-liste-de-mots-2.md)
- images: [none]
- assets: [Already on Jekyll](https://programminghistorian.org/assets/python-lessons2.zip)

Vous pouvez parcourir l’aperçu de la soumission ici :
- Preview: <http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/du-html-a-une-liste-de-mots-2>

**Comment by emilienschultz** [comment]
Hello. J'ai fait une lecture et envoyé un petit mail à @datalogism avec quelques commentaires. Dès que j'ai son retour, je contacterai les évaluateurs.

**Comment by emilienschultz** [comment]
Le *Programming Historian en français* a reçu la traduction de  "Du Html à une liste de mots (partie 2)" de  @datalogism . Cette leçon est maintenant en cours d'évaluation.

J'assume le rôle de rédacteur en charge du suivi du processus de l'évaluation. L'évaluation sera réalisée par Béatrice Mazoyer @bmaz et Florian Barras @florianbarras

Les relecteurs et relectrices peuvent utiliser la numérotation des lignes fournie dans l'aperçu pour organiser leurs commentaires, si cela leur convient, tout en restant libres de présenter leur évaluation de la manière qui leur semble la meilleure. 

Tout membre de la communauté peut faire un retour constructif sur ce fil de commentaires, après avoir pris connaissance de nos [consignes aux évaluateurs et évaluatrices](https://programminghistorian.org/fr/consignes-evaluateurs) et accepté notre politique contre le harcèlement (voir ci-dessous). Nous demandons que toutes les relectures cessent après réception de la seconde évaluation formelle, pour que l'auteur puisse travailler sur la révision de son texte. Le rédacteur ou la rédactrice l'annoncera sur ce fil quand cette étape aura été atteinte.

La discussion s'organise au niveau de Github. Si quelqu'un préfère de discuter de manière privée, merci de m'envoyer un message électronique. Vous avez toujours la possibilité de vous tourner vers notre médiatrice [Hélène Huet](mailto:hhuet@ufl.edu) si vous avez le sentiment qu'une médiation est nécessaire. Ceci ne risque d'avoir aucune incidence négative sur l'évaluation de cette leçon.       

## Politique contre le harcèlement

Vous trouverez ci-dessous les principes du *Programming Historian en français* qui doivent inspirer les échanges entre évaluateurs et évaluatrices, autrices et auteurs, rédacteurs et rédactrices, ainsi que toute personne contribuant à nos forums publics.

Le *Programming Historian en français* tient à garantir un environnement académique ouvert à la communauté, qui offre la pleine liberté d’explorer minutieusement des idées, poser des questions, faire des suggestions ou demander des clarifications. Il fournit aussi un espace libre de toute discrimination envers les personnes contribuant au projet indépendamment du genre, de l’orientation sexuelle, des situations d’handicap, de l’apparence physique, de la masse corporelle, de l’origine, de l’âge, de la religion ou de l’expérience technique. Nous ne tolérons aucune forme d’harcèlement ou d’attaque personnelle contre les membres de la communauté. Les personnes qui violent ces règles sont susceptibles d’être expulsées de la communauté à la discrétion du conseil éditorial. Toute personne en mesure de témoigner de tels comportements ou qui en est la victime peut contacter notre dispositif de médiation ([Hélène Huet](mailto:hhuet@ufl.edu)). Merci de nous aider à créer un espace d’échange et de discussion sûr.

**Comment by florianbarras** [comment]
Bonjour à toutes et à tous,
Ci-dessous, voici ma contribution pour ce que je propose comme modification à l'article - que j'ai d'ailleurs trouvé excellent et facile à comprendre, même à mon niveau de connaissance python.

Ligne 38 : 
•	orthographe :  précédante -> précédente
•	Ortographe : Jusque là -> « Jusque-là »

43 : 
Pour compréhension, proposer de change r :
•	« Inspecter chaque caractère de la chaîne pageContents un à un  « En « Inspecter un à un  chaque caractère de la chaîne pageContents»

44 : Ajouter le signe « < » après caractère ouvrant, vu qu’il est ajouté au caractère fermant.
Proposition : Si le caractère est un crochet ouvrant (<), nous sommes alors à l’intérieur d’une balise : nous ignorons donc ce caractère et nous ignorerons aussi les suivants; 

46 : qu’est-ce un caractère courant ? Pas sûr que ça soit clair ainsi.

61 : Pourquoi le gras est-il jusqu’à « évaluer si » ? et pas jusqu’au bout de la phrase ? La seconde option me semble plus appropriée, p.ex : 
Mais avant cela, nous allons découvrir quelques techniques nous permettant de répéter une tache et d’évaluer si une condition est remplie.
66 : Attention à l’espace avant le point à la première phrase phrase : Comme de nombreux autres langages de programmation, Python propose plusieurs moyens de réaliser des boucles .
Corriger en : Comme de nombreux autres langages de programmation, Python propose plusieurs moyens de réaliser des boucles.
80 : identation -> corriger en « indentation »
119 : ajouter un tirer entre « pourrions » et « nous » -> « pourrions-nous »
164 : « devons-nous y prendre » il manque un mot, p.ex : « voici maintenant comment nous devons nous y prendre »

168 : « quand nous entions » -> je pense, « quand nous étions au sein d’une balise … » 

194 : « un objet de type fichier spécifique » -> ça sonne bizarre pour moi, est-ce une spécificité de la manière dont les programmateurs python discutent d’un objet texte (étant moi-même plutôt néophyte, je ne sais pas !) ? Si pas, rajouter par exemple « un objet tel qu’un type de fichier spécifique ».

203 : « Copiez ou tapez le programme … » je préfère le verbe « écrivez » au verbe « tapez », proposition : « Copiez ou écrivez le programme … »

231 : « le modification » -> changer en « les modifications »
231 bis : « avant de pouvoir le relancer Python » -> enlever le « le » -> proposition : « avant de pouvoir relancer Python »
233 : ajouter une virgule à « comme nous l’avons vu à l’instant, découper celle-ci en une liste de mot » 

281 : « afin de vous assurer une version mise à jour du code » -> sonne bizarre pour moi. Proposition : « afin de vous assurer d’avoir une version mise à jour du code ».

**Comment by datalogism** [comment]
Merci pour ton premier retour @florianbarras :) .
Comme tes commentaires me paraissait tous clair, j'ai  repris chacune de tes propositions.
Et ai eu  pu prendre le temps aujourd'hui de les reprendre et de les corriger directement. Ce qui laissera l'occasion à [@bma](https://github.com/bmaz) de repartir sur une version déjà plus clean. 
A très vite pour la prochaine vague de corrections :D

**Comment by bmaz** [comment]
Bonjour à toutes et à tous,

Voici mes propositions de modifications.

## Corrections orthographiques ou grammaticales 

59 consiste [...] de tester → à tester 

61 siune → si une

82 user du doubler signe égal → double 

125 différente que → différente de

162 Il permet (2e phrase) → Elle permet 

164 précédant → précédent 

177 une variable appelé → appelée 

177 nous pourront → nous pourrons

179 le contenu [...] n'est plus égale → n'est plus égal

227 Modifiez [...] puis relancer → relancez

231 vous devez sauvegardez → sauvegarder 

233 sauvegardez son contenu [...] et découper → découpez

269 intial → initial

## Surlignage 

Les expressions "boucle `for`", "instruction `if`", etc., ainsi que les noms de variables ou de fonctions devraient toujours être surlignées de la même manière, et non pas en italique ou en gras. Voici les lignes où cette convention n'a pas été suivie :

68 *trucbidule* ou bien encore *k*

68 variable '*trucbidule*'

89 *l'instruction si*

97 *l'instruction elif*

117 *boucle for*

164 la fonction *print*

177 '*theResult*'

179 *myText*

194 des fichiers comme *f*

223 boucle for

223 *charlist*

## Tournures des phrases

J'ai fait beaucoup de remarques ci-dessous, notamment pour essayer d'alléger la tournure des phrases, mais il existe probablement d'autres formulations encore plus simples. N'hésitez pas à ignorer mes remarques.

68 Nous avons ici nommé cette variable `char` → Ici, nous avons choisi d'appeler cette variable 

69 Pour ces raisons nommer sa variable '*trucbidule*' n'est pas forcément le meilleur choix de nom de variable → Pour cette raison, / C'est pourquoi `trucbidule` n'est pas forcément le meilleur choix de nom de variable

89  permet de spécifier ce que nous souhaitons faire dans le cas où la condition spécifiée n'est pas réalisée. (2 fois spécifier) → permet d'indiquer…

117 Ou s'il fait partie au contraire du contenu à extraire, dans quel cas nous, ajouterons alors → Si, à l'inverse, il fait partie du contenu à extraire, nous ajouterons alors

119 Cependant comment pourrions-nous garder en mémoire le fait que nous soyons ou non au sein d'une balise ? → Comment garder en mémoire le fait d'être ou non à l'intérieur d'une balise ?

119 Nous utiliserons à ce titre une variable de type entier, → Nous utiliserons pour cela une variable de type *entier*

121 La fonction de suppression de balises → 
La fonction de suppression des balises

123 Mettons désormais en pratique ce que nous avons pu apprendre ensemble, la version finale de la fonction `stripTags` nous permettant d'atteindre notre objectif est décrite plus bas. → Mettons à présent en pratique ce que nous venons d'apprendre. La version finale de la fonction `stripTags`, qui nous permet de réaliser notre objectif, est décrite ci-dessous.

123 Faites encore une fois bien attention à l'indentation de manière à ce qu'elle soit bien équivalente à ce qui est illustré ci-dessous lorsque vous remplacerez l'ancienne fonction `stripTags` dans `obo.py` avec la nouvelle. → 
Lorsque vous remplacerez l'ancienne fonction `stripTags` par la nouvelle dans le fichier `obo.py`, faites à nouveau bien attention à l'*indentation*, de manière à ce qu'elle soit identique à ce qui est indiqué ci-dessous.

134 Retourne indice → Renvoie l'indice

136 idem

142 booléen pour repérage contenu (je ne suis pas sûre que la notion de booléen ait déjà été introduite) → variable pour repérer l'intérieur d'une balise

143 variable contenant contenu → variable agrégeant les contenus

164 Cependant, et dans la majorité des cas → Cependant, dans la majorité des cas

164 voici maintenant comment devrions-nous y prendre : → voici comment s'y prendre / voici comment faire

177 En utilisant l'instruction `return`, nous sommes alors capables de sauvegarder la sortie de la fonction `stripTags` directement dans une variable → L'instruction `return` nous permet de transférer directement la valeur de sortie de la fonction `stripTags` dans une variable 

179 Vous remarquerez que le contenu retourné par l'exemple d'utilisation de  `stripTags` ci-dessus → Vous remarquerez que dans l'exemple ci-dessus, le contenu renvoyé par la fonction  `stripTags`

181 Depuis que nous avons redéfini `stripTags`, le programme `trial-content.py` réalise maintenant autre chose (plus proche de notre objectif). → Maintenant que nous avons redéfini `stripTags`, le programme `trial-content.py` fournit un résultat différent, plus proche de notre objectif.

187 quand vous aviez besoin de stocker → pour stocker 

187 chaîne de caractères : peut-être ajouter un lien vers la documentation de python sur les strings, comme cela a été fait à la ligne du dessous pour les integers?

187/189 nous avons généralement choisi de le faire au format chaîne de caractère. Mais cela n'a pas été toujours le cas → nous avons le plus souvent choisi de le faire au format chaîne de caractères. Cependant, il existe d'autres formats 

189 Avec les entiers, vous pouvez réaliser des opérations mathématiques mais il n'est pas possible d'y stocker des fractions et des nombres décimaux. → Les entiers permettent de réaliser des opérations mathématiques, mais il n'est pas possible d'y stocker des fractions ou des nombres décimaux

201 est cependant aussi très utile → est aussi très utile

201 collections ordonnées d'autres objets → collections ordonnées d'objets

241-244 les commentaires sont d'abord à la 3e personne du singulier (requête, lit) puis à la 1e personne du pluriel (Nous utilisons et transformons). Peut-être uniformiser ?

249 Vous devriez obtenir quelque chose ressemblant à cela : → Le résultat obtenu devrait ressembler à la liste ci-dessous :

269 En tant qu'être humain, vous avez la capacité de lire → Un humain peut facilement lire

269 pour l'automatisation d'un traitement sur des textes. → pour automatiser le traitement de contenus textuels.

## Autres remarques

Quels sont les choix faits jusqu'ici concernant l'inclusivité ? Ligne 82, "Les programmeurs débutants ont souvent tendance à confondre ces deux utilisations." pourrait être remplacé par "Les programmeuses et programmeurs", ou par "Lorsque l'on débute en programmation, il est courant de confondre"

Par ailleurs, une attention particulière devrait être portée à la place des virgules et à la ponctuation en général. Si besoin, je ferai une deuxième relecture à ce sujet la semaine prochaine.

**Comment by datalogism** [comment]
Bonjour Béatrice et merci pour tes retours. 
Concernant l'inclusivité, tu as tout à fait raison cette remarque. 
Je revois ma copie en intégrant tes suggestions cette semaine.
Une dernière relecture serait à la suite judicieux.

**Comment by emilienschultz** [comment]
Merci beaucoup @bmaz et @florianbarras pour vos relectures de l'article. 

Par ma faute, car j'ai pas rappelé qu'il était préférable d'attendre le deuxième retour avant les modifications, @bmaz a dû travailler sur une version déjà révisée (merci !), ce qui fait qu'une partie des remarques de @florianbarras a déjà été prises en compte.

En synthèse des deux lectures, il apparaît que ce sont surtout des aspects liés à la formulation. Il n'y a pas de souci majeur sur la leçon.

Je laisse donc @datalogism (qui vient de répondre en même temps que j'écris ^^) prendre en compte les retours de formulation, et faire un passage encore sur l'inclusivité suite à la remarque que certaines tournures peuvent encore être améliorées.

Je ferai une relecture une fois qu'il a intégré les éléments, complétée par celle de Béatrice si elle a du temps à ce moment-là.

Bonne reprise @datalogism ! Merci.

**Comment by datalogism** [comment]
Hello je viens d'appliquer les correctifs répondant aux revues de @bmaz,
j'ai revu aussi quelques tournures de phrases ambigues, coquilles trouvées en chemin et changé quelques liens obsolètes. 
Redites moi !

**Comment by emilienschultz** [comment]
Merci @datalogism pour cette intégration. J'ai refait une passe sur le texte et j'ai encore quelques petites remarques avant de passer la main
(Lignes du markdown)

- L46 : rajouter "jusqu'à la fin de la balise" pour ne pas avoir l'impression qu'on va tout ignorer ?
- L47 : est-ce qu'il ne faudrait pas formuler plutôt "Si le caractère est un crochet fermant (`>`) cela signifie que nous sommes toujours dans une balise mais que ressortons de celle-ci : nous ignorons ce caractère et inspecterons alors avec attention les suivants;"
- L52 : le titre n'est pas fini : "Fichiers nécessaires au suivi de la leçon" ?
- L63 : la traduction me paraît pas fidèle : plutôt "Pour ce faire" que "Mais avant cela", qui indique qu'il faut apprendre des choses pour le faire. + il y a deux fois nous, un peut être enlevé.
- L68 : ce n'est pas clair si on parle de la boucle for en général, ou de l'exemple. Dans "Cette instruction permet de demander à l'interpréteur" préférer "L'instruction ci-dessous utilise la boucle for pour demander à ...". De même ce n'est pas "Une variable" mais "La variable"
- L70 : peut être plutôt parler de termes spécifique à Python que de fonction Python, ce n'est pas systématiquement des fonctions. Plus, peut-être préciser que la coloration met en évidence les mots spécifiques à Python (là c'est implicite). Il manque aussi un espace après "pourquoi"
- L80 : Je trouve la formulation "d'un mécanisme de contrôle concernant le contenu de notre chaîne de caractères" difficile à comprendre à la relecture, et il manque la traduction de la fin de la phrase. Peut-être quelque chose de plus simple comme "Nous avons besoin de vérifier le contenu de la chaîne de caractères pour décider quoi faire"
- L82 : Je propose une reformulation : "Python n'exécutera le code indenté que si la condition définie est vérifiée.", la formulation actuelle laisse un peu d'ambiguité j'ai l'impression
- L115 : un chevron, et pas une 
- L119 : passage du nous au vous à corriger
- L125 : un espace de trop avant la virgule
- L144 : accent : intérieur
- L149 : ajouter un commentaire en plus "Tester les différentes situations" ?
- L164 : la traduction me semble un peu loin en relisant, est-ce qu'il n'est pas préférable de dire "L'instruction Python `continue` est utilisée dans les boucles pour passer à l'itération suivante" ? Sinon il manque une partie de l'information et la phrase suivante parle de condition (qui n'est pas liée par définition à l'opération continue, mais un cas d'usage)
- L166 : traduction plutôt "elle peut renvoyer" que "elle renvoie"
- L168 : pas de tiret "devrions-nous"
- L183 : manque un espace  après "la fonction", et je pense que les virgules devraient être enlevées ou déplacées "Vous remarquerez que, dans l'exemple ci-dessus, le contenu renvoyé par la fonction`stripTags()` n'est plus égal"
- L185 : il manque des guillemets autour du deuxième "trial-content.py"
- L191 : Plutôt "avec un format" que "au format" non ? et manipulés sans S (c'est le format)
- L228 : bloc plutôt que block ; définit (manque un t), guillemets pour for, et je m'interroge sur le terme "blanc" : des séparations vides plutôt non ? Je ne sais pas...
- L236 : "Essayez d'exécuter" plutôt qu'"Exécutez" non ?
- L246 : Manque "la" avant suppression
- L272 : Nous plutôt que vous ? Et l'apposition entre les virgules est un peu lourde, mettre au début ? "Comme nous le verrons dans la prochaine leçon, ce format ..."

Désolé de rajouter ça mais on touche le bout :)

**Comment by datalogism** [comment]
Hello @emilienschultz ne t'excuses pas, c'est au contraire moi qui te remercie de ta vigilance.
Je revois cela fin avant la semaine pro et te fais signe lorsque c'est corrigé !

**Comment by datalogism** [comment]
Hello @emilienschultz c'est bon pour moi. J'ai appliqué toute tes propositions. Concernant les termes "blancs", je suis parti sur l'expression "caractère invisible" qui me parait bien coller.  N'hesitez pas à me redire si d'autres modifs devaient être encore appliquées :)

**Comment by emilienschultz** [comment]
Hello 

Merci encore @datalogism 

j'ai fait un passage pour 1/ corriger des coquilles 2/ mettre des espaces insécables 3/ faire quelques modifications pour alléger le texte. J'ai fait les modifications/propositions suivantes directement dans le fichier mis à jour (dans certains cas, je me suis permis de reprendre la formulation de phrase, je te laisse @datalogism rejeter mes propositions si ça va trop loin du sens initial)  :

l28 : enlevé "indidivudel" après "liste de mots"
l39 : enlever "concrètement"
l65 : enlevé "autre" avant "langages de programmation" ; remplacé "boucle" par "répétition" , reformulation de la phrase "La variable `char` contiendra alors successivement chaque caractère de la chaîne `pageContents` parcourue." pour plus de simplicité.
l67 : point ajouté et Toutefois plutôt que "mais" ; remplacé "certaines nominations ne sont pas mobilisables" et reformulation de la phrase par "Cependant certains termes ne peuvent être utilisés car ils sont déjà attribués à une notion spécifique du langage Python (comme par exemple `for`)"
l67 : remplacement de "disponible au nommage" par "possible" ; remplacé "évidemment plus astucieux" par "il est préférable"
l77 : valeur plutôt que contenu
l124 : enlever "à présent"
l161 : je reformule la phrase si cela va pour rendre la lecture plus dynamique : "Nous voici ici face à deux nouvelles instructions Python" par "Ce code nous fait découvrir deux nouvelles instructions" 
l167 : enlevé "Désormais" et "devrions"
l206 : mise au singulier de la phrase (liste plutôt que listes, et ajout "d'autres")

Dès que @datalogism tu es ok, je te laisse @marie-flesch passer dessus ? (en espérant que j'ai rien oublié, ou sinon signale le moi).

**Comment by datalogism** [comment]
Hello @emilienschultz ! 

Je suis d'accord avec toute tes reformulations et corrections, excepté celle qui concerne le remplacement de "boucle" par "répétition". Je serai à la limite d'accord si l'on part sur quelque chose du genre "Python propose plusieurs moyens permettant de répéter l'exécution d'une séquence d'instructions." comme cela est introduit dans l'article Wikipedia introduisant la boucle for https://fr.wikipedia.org/wiki/Boucle_for
Qu'en penses-tu ? 

Dans tout les cas je tiens encore une fois à te remercier pour ta vigilance et ta patience

**Comment by datalogism** [comment]
[@emilienschultz pour confirmation] j'ai balayé tes commentaires, peux tu me confirmer que tu les as tous bien appliqués directement ?

**Comment by emilienschultz** [comment]
Merci pour ta réactivité @datalogism 
Oui, ok pour ta formulation antérieure ou la formulation que tu proposes. Effectivement, ce n'est pas clair la manière dont j'ai écris. Tu refais la modifs ou je la fais (dans quel sens si c'est le cas ?)
Oui j'ai appliqué directement (je me suis permis en même temps que la correction de coquilles...)

**Comment by marie-flesch** [comment]
Du coup @datalogism c'est bon pour toi ou tu veux relire une dernière fois ?

**Comment by datalogism** [comment]
Je relis ça si je peux ce weekend.

**Comment by marie-flesch** [comment]
Ok ça marche !

**Comment by datalogism** [comment]
Hello c'est bon pour moi ! @emilienschultz @marie-flesch @anisa-hawes

**Comment by marie-flesch** [comment]
Top! Je vais tâcher de regarder ça cette semaine et ensuite je ferai signe à Anisa et Charlotte.

**Comment by marie-flesch** [comment]
J'ai enfin relu la leçon après dix jours de conférences qui m'ont pas mal ralentie... Excellent travail tout le monde, y avait vraiment pas beaucoup de coquilles :) J'ai principalement modifié les "chaînes" en "chaines", pour appliquer les rectifications orthographiques de 1990.

J'ai aussi beaucoup apprécié les ajouts de commentaires dans le code, qui sont effectivement très précieux ! Il y a juste un petit détail que je ne comprends pas, peut-être parce que je ne suis pas très habituée à Python. Dans le code ci-dessous, que veut dire "typer", @datalogism ou @emilienschultz ? (Je le comprends comme : renvoyer la structure du contenu, mais je ne sais pas si c'est ça). Par ailleurs il faudrait mettre le verbe à la troisième personne ("type") par souci de cohérence avec les autres commentaires.

> obo.py
>  stripTags(pageContents):
>    Typer le contenu du code source de la page
    pageContents = str(pageContents) 

Enfin, j'ai une question / suggestion. Dans la section "Les listes Python", la leçon dit de "modifier la chaine s2", puis demande : 
> Qu’est-il arrivé au point d’exclamation ?

C'est donc ma question aussi :) Pourrait-on préciser en deux mots ce qui lui arrive ? Je sais que ce n'est pas précisé dans la leçon en anglais, mais ça serait un ajout utile, je pense, car ça fait bizarre d'avoir une question sans réponse. 

Tu peux modifier directement la leçon @datalogism ou répondre ici et je ferai l'ajout moi-même, comme tu préfères !

**Comment by datalogism** [comment]
Hello, ok merci beaucoup @marie-flesch,
 j'ai précisé la question que tu soulevai avec les types :
  " # Type le contenu du code source de la page comme une chaine de caractère" 
  
  Concernant la question réthorique, elle provient du fait qu'en anglais la typographie n'impose pas d'espace après le point d'exclamation, l'exemple en français est moins parlant. Mais en le tournant ainsi cela devrait ne pas être trop mal pour la compréhension des lecteurs :
  
  Si vous avez bien écrit « salut le monde! » sans espaces avant le point d'exclamation, celui-ci se retrouvera dans le même élément de la liste que « monde », alors que si vous avez ajouté un espace pour corriger cette erreur typographique, le point d'exclamation sera placé dans un élément différent de la liste mots. Vérifiez si cela est bien le cas.
  
  J'ai corrigé cela directement dans le texte. N'hésitez pas à me redire si je dois revenir encore dessus.
  Bonne semaine

**Comment by marie-flesch** [comment]
Du coup (juste pour vérifier si j'ai bien compris), il faut mettre une espace pour avoir le résultat que l'on souhaite, c'est ça ?

**Comment by datalogism** [comment]
Il n'y a pas de bon/mauvais résultat ici, c'est juste pour faire comprendre à l'étudiant l'impact de l'espace dans le découpage fait par la fonction split()

**Comment by marie-flesch** [comment]
ah ok, merci :)

**Comment by marie-flesch** [comment]
@anisa-hawes and @charlottejmc, this lesson is ready for you :)

**Comment by charlottejmc** [comment]
Hello @marie-flesch ,

This lesson's sustainability + accessibility checks are in progress.

- Preview: 

**FR:** <http://programminghistorian.github.io/ph-submissions/fr/en-cours/traductions/du-html-a-une-liste-de-mots-2>  

Publisher's sustainability + accessibility actions:
- [x] Typesetting
- [x] Addition of Perma.cc links
- ~[ ] Addition of alt-text for all figures~
- ~[ ] Check/resize images~
- ~[ ] Check/adjust image filenames~
- [x] Receipt of translator's copyright agreement
- [x] Added doi

Editorial input to YAML:
- [x] Translation of `avatar_alt` (see English version below):
```
A soldier being mocked by a man.
```
- [x] Translation of `abstract:` –> J'ai suggéré un nouvel abstract, car celui qui était donné initialement n'était qu'une copie des deux premières lignes de la leçon (un oubli, je pense). @marie-flesch et/ou @datalogism, sentez-vous libre de le modifier ! 
- [x] Translation of author(s) bio for `ph_authors.yml`


Files to be transferred to Jekyll:

**FR:**  
- .md file: [/en-cours/traductions/du-html-a-une-liste-de-mots-2.md](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/fr/en-cours/traductions/du-html-a-une-liste-de-mots-2.md)
- images: [pas d'image pour cette leçon]
- assets: [/assets/python-lessons2.zip](https://github.com/programminghistorian/ph-submissions/blob/gh-pages/assets/python-lessons2.zip) 


Promotion:
- [x] Prepare announcement post (using template)
- [x] Prepare x2 posts for future promotion via our social media channels

**Comment by marie-flesch** [comment]
Awesome, thank you @charlottejmc ! I'll take care of the translation of avatar_alt and of the two social media posts.

**Comment by marie-flesch** [comment]
Je n'avais pas vu que tu avais changé l'abstract @charlottejmc, merci ! J'ai juste enlevé un mot et ajouté le nom de la leçon (pour des raisons de clarté, car ce n'est pas la précédente sur notre site). Dans la leçon originale l'abstract était aussi la première phrase du texte, mais c'est bien mieux comme ça :)

**Comment by anisa-hawes** [comment]
_Du HTML à une liste de mots (partie 2)_ is published! 🎉

Congratulations on another translation @datalogism!
Thank you **all** for your contributions ✨

---

Our suggested citation for this lesson is:

>William J. Turkel et Adam Crymble, « Du HTML à une liste de mots (partie 2) », traduction par Célian Ringwald, Programming Historian en français 5 (2023), https://doi.org/10.46430/phfr0028.

We appreciate your help to circulate our social media announcements about this lesson among your networks:
Twitter/X: https://twitter.com/ProgHist/status/1724792943247298657
Mastodon: https://hcommons.social/@proghist/111414993167826903

---

I'd be also grateful if you might consider supporting our efforts to grow _Programming Historian_'s [community of Institutional Partners](https://programminghistorian.org/fr/pi). This is a [network of organisations](https://programminghistorian.org/fr/nos-soutiens) across Europe, Canada, North America and Latin America who have invested in our success by contributing an annual membership fee in lieu of subscription.

Institutional Partnerships enable us to keep developing our model of sustainable, open-access publishing, and empower us to continue creating peer-reviewed, multilingual lessons for digital humanists around the globe.

If you think that supporting Open Access initiatives may be among the strategic priorities of the university or library where you work, please let me know.

You can email me <admin [@] programminghistorian.org>, and I can send you an information pack to share with your colleagues. Alternatively, feel free to put me in touch with the person or department you think would be best-placed to discuss this opportunity.

Sincere thanks,
Anisa

**Comment by marie-flesch** [comment]
Thank you Anisa, et bravo et merci à toutes celles et ceux qui ont travaillé sur cette leçon !
