### ISSUE TITLE
UI Suggestions and Fixes

### ISSUE THREAD

**Issue by TartejBrothers** [programminghistorian/ph-submissions#594]
Bottom footer is not aligned to the center in the desktop view, it is fine in the mobile view. 

The font looks a bit outdated, might be better if Poppins or any other modern font is used.

**Comment by TartejBrothers** [comment]
[proposal]

**Comment by anisa-hawes** [comment]
Thank you for sharing these observations and suggestions, @TartejBrothers. 

We'll certainly keep these in mind for the future 🙂
