### ISSUE TITLE
Ticket de revisión de traducción: Poniendo Omeka a funcionar

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#61]
The Programming Historian en español ha recibido la siguiente propuesta de traducción "Poniendo Omeka a funcionar" de la lección [Up and running with Omeka.net] (http://programminghistorian.org/lessons/up-and-running-with-omeka) por parte de @mariajoafana . Esta traducción se encuentra en estos momentos en fase de revisión por parte de Maria Paula García y @aliciacbu y puede leerse en:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/poniendo-omeka-a-funcionar.md

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.
Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

    El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Enviado mensaje a Maria Paula García el día 30 de marzo. Pendiente de respuesta y de comunicación de nombre de usuario de GitHub. 

Añado a @aliciacbu como segunda revisora. Por favor, lee la lección y comenta aquí lo que creas pertinente.

**Comment by arojascastro** [comment]
Añado a @aliciacbu como segunda revisora. Por favor, lee la lección y comenta aquí lo que creas pertinente.

**Comment by vgayolrs** [comment]
@mariajoafana @arojascastro 

Unos comentarios de revisión como miembro de la comunidad:

L-14: qudarte con este -> quedarte con este
L-27: No tiene que hacer clic -> No tienes que hacer clic
L-39: Introduce alguna informaci;on sobre tu colecci;on y acu;erdate -> Introduce alguna información sobre tu colección y acuérdate
L-41: Para llenar la colección que acbaas -> Para llenar la colección que acabas
L-47: El equipo de Omeka has compilado -> El equipo de Omeka ha compilado
L-47: arreglar enlaces

__Nota__: me parece excelente añadir la nota de traducción acerca de la posibilidad de tener el sitio en español. Sin embargo, la liga al [Manual de uso de Omeka](https://issuu.com/ralcaraz/docs/omeka-manual) de Rubén Alcaraz puede crear confusión en un usuario que está configurando un sitio en [omeka.net](http://omeka.net), ya que en general se dedica a explicar la instalación de [Omeka](http://omeka.org) en un servidor y no tanto a la utilización de omeka.net (además que está desactualizado). En vez de ello, yo sugiero incluir en alguna parte del apartado "Instala algunos plug-ins" (aunque sería mejor que estuviera al principio, en el acápite 'Crea tu nuevo sitio Omeka') la explicación de cómo configurar el sitio en español en omeka.net mediante el plugin 'Local' que lo permite.

De hacerlo así, por cierto, permitiría rescribir el tutorial mucho más apegado a la realidad de un sitio en omeka.net administrado en español pues, por ejemplo, en vez de 'items' tendremos 'elementos', y todo el resto de las indicaciones en las que se hace referencia a los menús e instrucciones en inglés se podrían cambiar al español. Es solamente una sugerencia, pero creo que mejoraría en mucho la traducción.

**Comment by arojascastro** [comment]
Muchas gracias @vgayolrs. Por favor, @aliciacbu ten en cuenta los comentarios precedentes y dinos si coincides (al margen de tus correcciones o sugerencias).

**Comment by arojascastro** [comment]
Mis comentarios:

- 32: Después de haber entrado al enlace --> Tras hacer clic en el enlace (u otra expresión más simple)
- 32: haz clic en "Add a Site" (Añadir un sitio). --> negrita en lugar de comillas (?). Esto lo sugiero porque veo que en adelante usas negrita. Hay que unificar comillas o negrita.
- 41: Para ver como se ve haz --> Para ver tu sitio, haz... (repites dos veces el verbo ver y además el "como" debería llevar tilde si decides usarlo) 
- 54: themes --> añadir cursiva
- 61: (dashboard) . --> sobra espacio
- 61: qudarte  --> quedarte
- 93: el Creator sería  --> el Creator sería... (añadir puntos suspensivos)
- 95: se consistente --> sé consistente
- 102: (No tiene que hacer clic en Add Item, Añadir ítem, antes de que hagas esto; Omeka guardará automáticamente tu información) Puedes --> (No tiene que hacer clic en Add Item, Añadir ítem, antes de que hagas esto; Omeka guardará automáticamente tu información). Puedes (Falta punto después del paréntesis)
- 106: Cuanodo --> Cuando
- 115: Esta no es la página pública de tu ítem. --> quitar punto
- 120:  derecha.) -->  derecha).
- 134: Añade una colección.) --> Añade una colección).
- 141: informaci;on sobre tu colecci;on y acu;erdate --> información sobre tu colección y acuérdate
- 141: Public button --> falta negrita 
- 148: acbaas  --> acabas
- 150: Escoje la colección --> Escoge la colección
- 155: página.) --> página).
- 168: arreglar links
- 170: eliminar "Written with Stackedit"

Estoy de acuerdo en que el enlace al tutorial puede crear confusión... entiendo que el resto de tutoriales sobre Omeka son sobre Omeka.net no? Quizás se podría añadir un apartado aclarando la diferencia entre Omeka.net y Omeka.org y sobre el plugin que recomienda @vgayolrs... pero esto depende de ti @mariajoafana: tu trabajo ya está hecho.

En cualquier caso, esperemos a los comentarios de @aliciacbu.

**Comment by aliciacbu** [comment]
Hola, 
Os comparto mis sugerencias:

- 34: Llena --> Rellena ("rellenar" se ajusta más al sentido de la frase, DRAE  tr. Cubrir con los datos necesarios espacios en blanco en formularios, documentos, etc.) 
- 54: cambiado --> por medio de las plantillas
- 86: —por ejemplo.... tu ítem— (el inciso debe ser precedido por la barra, sin el espacio)
- 93: —bueno (sin el espacio)
- 102: no tiene --> no tienes
- 102: antes de que hagas esto --> antes de hacer esto
- 102: quitaría el Añadir ítem o en caso de mantenerlo lo pondría entre paréntesis como el resto de traducciones
- 104: —persona..... mineral— (sin espacios)
- 120: navegue la página --> navegue por la página
- 120: del tu ítem --> de tu ítem
- 127: navega en --> navega por
- 134: haz clic en la pestana Collections (Colecciones) y haz clic --> haz clic en la pestaña Collections (Colecciones) y en (quitar el segundo verbo para evitar repeticiones)
- 162: deber --> debes
- 164: uno colección --> una colección 

Personalmente, me parece imprescindible hacer una pequeña aclaración de la diferencia entre Omeka.net y Omeka.org y optaría, como ha sugerido el compañero @vgayolrs, por incluirla al inicio. Se podría hacer hincapié en recomendar la instalación de Omeka.org a los usuarios avanzados, ya que uno de los inconvenientes de Omeka.net es que no está actualizada a las últimas versiones, entre otras muchas cosas.

El [manual de Ruben Alcaraz](http://www.rubenalcaraz.es/manual-omeka/) también se encuentra disponible en versión web y me parece adecuado citarlo si finalmente se incluye una breve explicación de Omeka.org.

**Comment by arojascastro** [comment]
Gracias @aliciacbu. Resumo:
- Parece que todos estamos de acuerdo en que hay que añadir al principio una apartado aclarando las diferencias entre Omeka.net y Omeka.org. 
- Si se hace esto, creo que ya no sería confuso añadir el manual de Rubén Alcaraz (en la bibliografía, si hay más entradas, o bien en una nota al final).
- Por favor, @mariajoafana corrige las erratas señaladas. Puedes añadir las sugerencias de cambio, siempre y cuando respeten la variante colombiana -- queda a tu discreción.

Cuando hagas las modificaciones, por favor, comunícanoslo por aquí y cerraremos este "issue" antes de publicar la lección. 

Gracias a todos @mariajoafana @aliciacbu @vgayolrs

**Comment by mariajoafana** [comment]
Perfecto, gracias @aliciacbu @vgayolrs @arojascastro. Pronto les aviso cuando estén hechas las correcciones.

**Comment by mariajoafana** [comment]
Hola! Acabo de hacer las correcciones. Muchas gracias a todos. Sobre el asunto de Omeka.net y Omeka.org añadí una nota aclaratoria al comienzo también anotando que la traducción de nuestro tutorial sobre cómo instalar Omeka  que está en proceso. Esto habría que actualizarlo una vez esa traducción este lista. No se si sea mejor omitir esto y así ahorrarnos una edición adicional después. 
Añadí además un vínculo el manual en "Recursos adicionales" .  
Por favor lean la nota aclaratoria y la sección "Recursos adicionales" a ver que les parece.

**Comment by arojascastro** [comment]
Gracias @mariajoafana. Me parece buena idea poner esa aclaración al principio. Hay que acordarse de actualizar el enlace en el futuro. Solo un par de retoques:

> *Nota de la traductora*: Antes de empezar es importante aclarar las diferencias entre Omeka.net y Omeka.org. Este tutorial es sobre Omeka.net, una plataforma de publicación en línea que permite a cualquier persona con una cuenta de acceso crear o colaborar en un sitio web para exhibir colecciones y construir exhibiciones digitales. Omeka.net es una extensión de Omeka.org que está disponible para bajar e instalar en un servidor de tu propiedad. La traducción al español del tutorial de The Programming Historian sobre cómo instalar Omeka en un servidor se encuentra en proceso.

- Poner la nota como destacado y *Nota de la traductora* en femenino (¿?) y en cursiva. *The Programming Historian en español*. Falta *en español* 
- sobre Omeka.net que es una plataforma -->  sobre Omeka.net, una plataforma... (para no repetir la cláusula *que*)
- Duda: 'exhibición' no es un calco de *exhibition*, pregunto. ¿No es mejor 'exposición'? [RAE](http://dle.rae.es/?id=HKleAWS). En la lección utilizas una vez 'exhibición' y ninguna vez exposición.

**Comment by mariajoafana** [comment]
Gracias @arojascastro ya hice los cambios. Creo que tienes razón y que la palabra exposición es mejor. Hice el cambio en toda la lección.

**Comment by arojascastro** [comment]
Entonces está lista para publicar. Me pongo a ello en breve.

**Comment by arojascastro** [comment]
Hola @aliciacbu y @mariajoafana, la lección ya está publicada: http://programminghistorian.org/es/lecciones/poniendo-omeka-a-funcionar

El índice de lecciones también ha sido actualizado. Cierro este *issue*. Si surge algo más, podemos abrirlo. Por favor, ayudad a difundir la lección.
