### ISSUE TITLE
Ticket de revisión de traducción: Introducción a línea de comandos en Bash

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#62]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción "Introducción a la línea de comandos de Bash" de la lección [Intro to the Bash Command Line] http://programminghistorian.org/lessons/intro-to-bash) por parte de @vgayolrs . Esta traducción se encuentra en estos momentos en fase de revisión por parte [pendiente de asignación de revisores externos] y puede leerse en:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/introduccion-a-bash.md

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.
Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

    El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
He enviado petición a Antonio Sánchez Padial; estoy a la espera de su respuesta.

**Comment by arojascastro** [comment]
@ajspadial se encargará de la revisión, pero no podrá introducir su revisión hasta mayo. Quedamos a la espera. Mientras tanto, en breve publicaré mis comentarios.

**Comment by arojascastro** [comment]
Mis comentarios; no he encontrado gran cosa:

- 23: Programming Historian en español  --> The Programming Historian en español (Añadir The o no, pero hay que unificar en cualquier caso con el resto de lecciones).
- 35: tienen suerte pues ya tienen --> repetición "tienen"... es posible buscar una alternativa?
- 121: lo mismo que en comentario 23 --> hay que unificar el nombre de nuestra web
- 129: click  --> clic (creo que tenemos otras lecciones en que hemos aceptado click, hay que revisar esta cuestión, quizá)
- 145: lo mismo que en comentario 23 
- 153: ser llevado a  --> una construcción pasiva... muy poco frecuente en español, sí en inglés... puedes convertirla en voz activa?
- 175: (¡adivinaste!), --> quitar coma (?)
- 177: puede escribir --> puedes
- 233: Enter --> Intro (?)
- 233: shell --> cursiva (?)
- 239: puede ayudar a evitar escribir  --> muchos verbos, contrucción complicada... ¿puedes simplicarla? Por ejemplo: la utilización de un comodín evita escribir
- 247: muy poderoso que es  --> un editor de texto ideal para... (es decir, eliminar "poderoso"; en inglés lo usan mucho, pero en español creo que solo lo usamos con personas u organismos, así que traduciría "con muchas funciones" o "muy útil", o simplemente lo eliminaría).
- 247: bash --> cursiva (?)
- 261: Windows: Shift+FlechaArriba) --> falta punto final tras el paréntesis de cierre
- 265: Dado que estás haciendo todo con el teclado, en vez de tener que mantener pulsada la tecla de flecha para moverte por el documento, esto te permite pasar volando hacia atrás y adelante. --> no acabo de entender esta frase...
- 319: creo que las notas las marcamos como bloque en markdown (?) o bien las deberíamos poner como nota al pie... Por ejemplo:

> esto es una nota en destacado porque es importante

- 357: imprime --> Imprime (mayúscula inicial)
- 366-368: falta punto final (.) (para unificar con el resto)

Quedamos a la espera de los comentarios de @ajspadial. ¡Gracias!

**Comment by ajspadial** [comment]
A continuación, mis comentarios. Hago muchas alusiones al español de España. Hay algunas traducciones que me parecen demasiado directas del Inglés, y que no suenan bien en español de España. Hago esta precisión, porque es posible que sean expresiones correctas en otros países hispanohablantes, pero está fuera de mi conocimiento.

23: ¿Un emulador? Esto no aparece en el original. Tampoco sé a qué se refiere el traductor (probablemente esto sea culpa mía)

23: "**Interfaz Gráfica de Usuario**, o GUI". Añadiría ", por sus siglas en inglés" y opcionalmente el significado de las siglas.

27: "puedes agregar variables", creo que parámetros un término más adecuado (modifiers en el original).

27: "basadas en texto", suena raro en español de España. Tal vez "en un archivo de texto."

29: "pueden seguir adelante", suena raro en español de España. Quitaría el "adelante".

31: "para ajustarse" --> "que se ajusten" en español de España.

49: "mirar repetidamente" --> "mirar continuamente" en español de España.

49: "estarás viendo este" --> "lo estarás viendo" en español de España

TODO::: 73: "banderas" --> no me gusta mucho, pero no encuentro una alternativa. Yo siempre los he llamado parámetros 

145: "emulador" --> definitivamente lo eliminaría, "utilizando la línea de comandos" sin más (salvo el caso de Git Bash, tal vez, pero creo que esto confunde más que aclara)

167: "uno debería hacer todo esto"  --> "alguien querría hacer esto" en español de España

167: "la principal razón es obtener la experiencia necesaria para trabajar en la línea de comandos" --> creo que el original se ajusta más a "la razón principal es la extrema comodidad de trabajar con la línea de comandos"

175: Después del paréntesis de las soluciones alternativas, añadiría. "Del mismo modo es recomendable evitar la ñ, y el resto de caracteres especiales del castellano, tildes, etc. Aunque los sistemas actuales son capaces de utilizarlos, podemos encontrar problemas si tenemos que utilizar estos ficheros en sistemas antiguos"

225 y siguientes: aparece "tosltoy" por "tolstoi". En vi/vim `:%s/tolstoy/tolstoi/g`

243: al final "... recordar es un marcador de posición para un sólo carácter ..."  --> "... recordar es `?`, que reemplaza un único carácter ..."

247: "poderoso"  --> "potente" ?

253: "Vim" debería ir en mayúscula. En el original va en minúscula en esa línea, pero en el resto del texto se refiere a él en mayúscula, como nombre propio. Consideraría que la minúscula del original es una errata.

259: "sería un éxito el hacerlo" --> "lo cual sería todo un logro, por cierto" Creo que en español hace falta remarcar la ironía, puede confundirse con un logro/éxito/achievement del tutorial ;-)

259: "En seguida" --> "A continuación" en español de España

283: "para regresar al modo de lectura" --> "para abandonar el modo de inserción de texto". Es más correcto. Si bien es cierto que el original habla de ese "modo de lectura", que técnicamente no existe en Vim: https://en.wikibooks.org/wiki/Learning_the_vi_Editor/Vim/Modes

285: "hacer cambios" --> "guardar cambios". En el original "make saves"

285, 291: Hay que pulsar ENTER después del comando. En inglés tampoco lo dice, pero en los comando anteriores como `a` no es necesario, por lo que me parece necesario para los comandos `:w`, `:wq`, etc.

345: `du` no informa del uso de la memoria, si no del uso del disco. Para mí la diferencia está clara y es importante, pero naturalmente tengo un sesgo técnico. En el original dice memoria, de igual modo.

347: "involucrarte con los scripts". Involucrarte suena "comprometido" en español de España, ¿qué tal "meterte" o "atreverte"?

358 y siguientes: "Enlista"  -> "Lista" o "Muestra" en español de España

359 y siguientes: No estoy seguro que usar `*` en esta tabla sea una buena idea, ya que en el mismo tutorial hemos introducido el uso del comodín `*` con propósitos parecidos. Lo cambiaría por `<nombre_comando>`, `<nombre_directorio>`, etc.

**Comment by ajspadial** [comment]
Disculpad el retraso!

**Comment by ajspadial** [comment]
Por si no queda claro, en la línea 23 (y otras donde aparece) propongo eliminar el término emulador.

**Comment by arojascastro** [comment]
Muchas gracias @ajspadial, todo aclarado. 

@vgayolrs todo tuyo: por favor, corrige las erratas y acepta las sugerencias que sean calcos del inglés. Como anteriormente dije, los ibéricos agradeceríamos una lista de las expresiones que nos suenan a inglés, pero que son corrientes en México y otros países latinoamericanos. 

Cuando hayas introducido los cambios, @vgayolrs publica un mensaje aquí para que prosiga con la publicación del tutorial. Gracias.

**Comment by vgayolrs** [comment]
¡Muchas gracias @ajspadial y @arojascastro por sus observaciones ! El fin de semana me pongo a trabajar con esto y, de haber alguna duda, los estaré importunando por aquí. ¡Saludos!

**Comment by vgayolrs** [comment]
Muchas gracias a ambos. Solamente falta decidir sobre pequeños detalles de 27, 345 y 359.

**Comment by ajspadial** [comment]
Si necesitas ayuda no dudes en ponerte en contacto

**Comment by vgayolrs** [comment]
@arojascastro , perdón por el retraso. Corregidas las líneas 27 y 345. Sobre 359 y subsiguientes, me parece muy buena la propuesta de @ajspadial , pero significa cambiar mucho con respecto al original en inglés donde se ha esplegado la lista de comandos y funciones utilizando el "*". Si no tienes inconveniente como editor, procedo a cambiarla toda.

**Comment by arojascastro** [comment]
Gracias @vgayolrs, creo que podemos publicar sin ese cambio, si la lección funciona y es correcto. Así que adelante, por favor, introduce los cambios que creas convenientes. Gracias @ajspadial por tu revisión.

**Comment by vgayolrs** [comment]
@arojascastro : los demás cambios ya están hechos. Así que, cuando quieras, es publicable.

**Comment by arojascastro** [comment]
Lección publicada: https://programminghistorian.org/es/lecciones/introduccion-a-bash

Gracias @vgayolrs y @ajspadial - por favor, difundid :)
