### ISSUE TITLE
Ticket de revisión de traducción: Instalar módulos de Python con pip

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#63]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción "Instalar módulos de Python con pic" de la lección [Installing Python Modules with pip](http://programminghistorian.org/lessons/installing-python-modules-pip) por parte de @vgayolrs . Esta traducción se encuentra en estos momentos en fase de revisión por parte @morethanbooks y puede leerse en:

https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/instalar-modulos-python-pip.md

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro.

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.
Política contra el acoso

Esta es una declaración de los principios de Programming Historian en español y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

    El objetivo de The Programming Historian en español es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque ad hominem. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Añado a @morethanbooks (José Calvo) como revisor de esta lección; introducirá los comentarios hacia el 20 de abril.

**Comment by ajspadial** [comment]
En español de España, al menos, no sé en otros países, usamos _librería_ como traducción de _library_, enlugar del más correcto _biblioteca_. Imagino que será po algún motivo histórico dentro de las traducciones en el campo de la informática.

**Comment by morethanbooks** [comment]
Hola:
aquí va mi revisión. He estado echando un ojo y creo que, como señala @ajspadial es más frecuente _librería_ aunque se percibe como más correcto _biblioteca_ (por ejemplo, en wikipedia está lematizado como _Biblioteca_ aunque referenciado desde la página de desambiguación de _librería_ https://es.wikipedia.org/wiki/Librer%C3%ADa_%28desambiguaci%C3%B3n%29).

La traducción de la lección contiene toda y solo la información original. Como la mayor parte de traducciones que todos hacemos, queda un español con sabor inglés. Propongo algunas modificaciones que buscan que el texto tenga en español un tono más natural (aunque eso signifique a veces eliminar pronombres o modificar tiempos verbales en relación al original).

Modificaría "Esta lección te muestra" por "Esta lección muestra".
Modificaría "pero para el propósito de esta lección" por "pero para esta lección"
Modificaría "en Python 2.7.9 y posteriores" por " en Python 2.7.9 y versiones más nuevas"
Modificaría "Este tutorial será muy" por "Este tutorial es"
Modificaría "versiones anteriores de Python" por "versiones antiguas de Python"
Modificaría "ahorrar mucha escritura de código" por "ahorrar escribir mucho código"
Modificaría "¡No permitas que esto te asuste!" por "¡No le tengas miedo!"
Modificaría " como quieras, como:" por " como quieras, por ejemplo:"
Modificaría "esta lección te muestra" por "esta lección explica"
Modificaría "en la instalación regular" por "en la instalación por defecto"
Modificaría "una secuencia de comandos " por "una secuencia de comandos  (script)"
Modificaría "es posible que la secuencia de comandos del script seguramante falle" por "la secuencia de comandos del script seguramente falle"
Modificaría "instalarte un virus" por "instalarte virus"
Modificaría "Como en las plataformas anteriores" por "Como en los sistemas operativos"
Modificaría "Cuando abres este enlace te puede asustar el revoltijo masivo de código que te aguarda" por "Cuando abres este enlace, te puede asustar el revoltijo horrible que te espera"
Modificaría "Será buena idea" por "Puede ser buena idea"
Modificaría "Una vez que guardes" por "Una vez guardes"
Modificaría "actualizada regularmente" por "actualizada de manera regular"
Modificaría "Ahora que ya tienes pip resultará" por "Ahora que ya tienes pip, resultará"
Modificaría " todo el trabajo por nosotros" por " todo el trabajo por ti"
Modificaría "el imprescindible comando pip" por " el comando pip necesario"


Esta es mi primera revisión de este tipo, espero estar haciendo las cositas bien. Abrazos!

**Comment by arojascastro** [comment]
Muchas gracias @morethanbooks por tu revisión; en breve introduciré mis comentarios, y así @vgayolrs podrá introducir los cambios pertinentes. Gracias también a @ajspadial por su contribución.

**Comment by arojascastro** [comment]
Aquí van mis comentarios:

- en general, concuerdo con lo que dicen @ajspadial y @morethanbooks sobre el término "librería". Sin embargo, en el portal lingüístico de Windows (y en los producto de Windows), recomiendan y usan "biblioteca" (https://www.microsoft.com/Language/es-es/Search.aspx?sString=library%20&langID=es-es). Dejo la elección al gusto del traductor, pero, en cualquier caso, pondría una nota explicativa justificando la decisión.
- 22:  Una de las cosas buenas de utilizar --> una de las principales ventajas 
- 22: en forma automática --> de forma automática (?)
- 22: continuamente  --> (eliminar: me suena inglés, no es necesario)
- 22: No permitas --> calco del inglés... buscar una alternativa
- 25: la nota no debería marcarse de manera distinta en markdown para distinguirla como bloque?
- 39: utilizando el comando curl que descarga el script de perl para la instalación de pip. ---> ??? sé que no es tu culpa, Victor, pero esta frase me parece ininteligible, demasiado argot seguido, ¿podríamos clarificar los términos de alguna manera?
- 51: es posible que la secuencia de comandos del script seguramante falle porque no tendrá permisos para actualizar ciertos directorios en tu sistema de archivos que están establecidos de manera predeterminada para evitar que scripts aleatorios puedan cambiar archivos importantes e instalarte un virus --> esta frase es muy larga. ¿Puedes poner algún punto o reescribirla?
- 51: confiable --> me suena a calco de "reliable", no sé si en México se usa, pero yo diría "seguro" o "en el que puedes confiar"... "confiable" me suena raro, poco usado... 
- 51: sudo --> ¿cursiva? ¿código?
- 59: Será buena idea  --> calco del inglés (?) Yo lo eliminaría y diría solo: "Guarda..."
- 82: por las mismas razones explicadas antes --> me suena a traducción literal de "for the same reasons explained before"... (alternativa: eliminar "recuerda" y decir "como ya hemos explicado antes..." )
- 82: sudo --> cursiva? o marcar con código en markdown?
- 88: Felices instalaciones --> ¡A disfrutar! o ¡Que disfrutes! o ¡Ya estás listo para trabajar! O simplemente eliminar: en español no somos tan coloquiales, creo.

Por favor, @vgayolrs introduce los cambios que creas convenientes, sobre todo teniendo en cuenta que podemos haber señalado como equívocas algunas expresiones típicas del español de México; en tal caso, puedes ignorar nuestras sugerencias. 

Por ejemplo, veo que @morethanbooks te señala el uso de "Una vez que", que yo también te he señalado en otras traducciones; creo que en español ibérico no usamos ese "que", etc. Estaría bien, por lo demás, que nos dijeras qué usos son correctos en México y no en la península ibérica, para tenerlo en cuenta de cara a las próximas traducciones. 

Los calcos del inglés, creo, sí que deberían modificarse. 

¡Gracias a todos @vgayolrs, @morethanbooks y @ajspadial !

**Comment by vgayolrs** [comment]
¡Muchas gracias por sus comentarios @morethanbooks , @ajspadial y @arojascastro !
En breve me ocupo de la revisión.

**Comment by vgayolrs** [comment]
La corrección quedó lista @arojascastro Muchas gracias por todas las observaciones. Lo único que no entendí fue tu comentario a la línea 25 que es donde comienzan cuatro líneas en bloque de código.

**Comment by arojascastro** [comment]
Perdón, me refería a la línea 35. No sé si debería ir como destacado:

> nota...

Ver las instrucciones: http://programminghistorian.org/es/flujo-de-trabajo-nuevas-lecciones

**Comment by vgayolrs** [comment]
Listo @arojascastro . Ya introduje el redireccionamiento en YAML y la etiqueta para que pongas los revisores de traducción. Mil gracias y saludos.

**Comment by arojascastro** [comment]
Gracias @vgayolrs . Tengo una duda: el archivo está tanto en la carpeta submissions como en la de jekyll... en cuál has hecho las modificaciones?

**Comment by vgayolrs** [comment]
@arojascastro 
la correcta es: /ph-submissions/es/traducciones/instalar-modulos-python-pip.md
(se ve por la fecha de última edición)
la de Jekyll la subió Caleb en febrero como prototipo para hacer pruebas.

**Comment by arojascastro** [comment]
Proceso de revisión terminado y lección publicada: http://programminghistorian.org/es/lecciones/instalar-modulos-python-pip

Ahora solo falta compartir en redes. Gracias a @vgayolrs, @morethanbooks y @ajspadial. Cierro *issue* si no hay más comentarios.
