### ISSUE TITLE
Ticket de revisión de traducción: Introducción al control de versiones con GitHub Desktop

### ISSUE THREAD

**Issue by vgayolrs** [programminghistorian/ph-submissions#64]
[__Nota__: Esta traducción de @arojascastro ya la habíamos revisado @mariajoafana y yo en el antiguo repositorio. La traducción ya está en /programminghistorian/jekyll y solamente hace falta revisar algunos detalles antes de publicarla, como las imágenes. Es cuestión de darle una última leída. Abro este Ticket con el único objeto de seguir el flujo de trabajo.] 

*The Programming Historian en español* ha recibido la traducción "Introducción al control de versiones con GitHub Desktop" de la lección ["An Introduction to Version Control Using GitHub Desktop"](http://programminghistorian.org/lessons/getting-started-with-github-desktop) por parte de @arojascastro . Esta traducción se encuentra en estos momentos en fase de revisión por @mariajoafana  y puede leerse en:

https://github.com/programminghistorian/jekyll/blob/gh-pages/es/lecciones/introduccion-control-versiones-github-desktop.md

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by vgayolrs** [comment]
@mariajoafana Las imágenes ya fueron subidas por @arojascastro (¡gracias!) hace un momento. La versión "en vivo" de la traducción puede verse en: http://programminghistorian.org/es/lecciones/introduccion-control-versiones-github-desktop

Mis observaciones para @arojascastro  como editor son:

98 GUI -> ¿incluir  "por sus siglas en inglés"?
114 'portabilidad' -> ¿quitar entrecomillado? Se acepta el término en RAE
118 dar formato aj nuestro -> dar formato a nuestro 
118 el nombre de 'markdown'-. -> guión de cierre ants de punto se suprime
119 explorar su funcionamiento una vez te sientas -> explorar su funcionamiento una vez que te sientas
119 Si añades la sintaxis Markdown a tus **docuemntos** 
119 arreglar enlaces
152 que acabamos de añadir a **GirHub**
160 Guarda los cambios efectuados y **vuelva** a GitHub Desktop
166 las **modificacione** realizadas
176 es importante estos cambios -> es importante que estos cambios 
176 difícil **asilar** los problemas 
182 se vuelve difíciles -> se vuelven difíciles
215 corregir enlaces
231 Una vez tu documento está en línea ->  Una vez **que** tu documento está en línea
231 tu documento en local -> ¿localmente?
299 control de versiones son un documento  -> control de versiones **con** un documento
299 arreglar enlaces
301 arreglar enlaces

@mariajoafana  si tienes alguna otra observación bienvenida.

**Comment by arojascastro** [comment]
¡Gracias, @vgayolrs ! He realizado los cambios en e17c346fcdffe8845fd20005e31d9549c3de3979 -- quedo a la espera de lo que diga @mariajoafana.

**Comment by mariajoafana** [comment]
Muy bien, volví a revisar y vi algunas cosas más. Acá van mis sugerencias: 

76 Añadir "The" a *Programming Historia en español* 
82 Creo que debería ser "A medida que la investigación **incluya**" en vez de "incluye". También cambiar "conjunto" por "conjuntos"
88 Creo que Humanidades y Ciencias Sociales no debería  ir en mayúscula. 
94 Lo mismo  con mayúscula en Humanidades Digitales
142 No encontré "clicar" en la RAE , sugiero entonces camibiar por "hacer clic"
150 "clicamos" por "hacemos clic"
223 renglón 5, creo que queda mejor "repositorio abierto" en vez de "repositorio en abierto". En el siguiente renglón cambiar "clicar" por "hacer clic"
231 tercer renglón, cambiar "en remoto" por remotamente 
233 Sugiero cambiar título por: "Cómo hacer cambios remotamente" 
235 cambiar "clica" por haz "clic"
243 "clica" por "haz clic"
247 cambiar "debería" por "deberías"
255 "clica" por "haz clic"
259 cambiar "en remoto" por "remotamente"
269 "en local" por "localmente"
275 corregir "continaución"
287 "clicar" por "hacer clic"
299 renglón 5, eliminar "will"

**Comment by vgayolrs** [comment]
¡Muchas gracias @mariajoafana ! 
@arojascastro : todo tuyo.

**Comment by arojascastro** [comment]
¡Gracias a los dos! Ya he introducido las correcciones de ambos. Cuando quieras @vgayolrs puedes cerrar este issue. Y si os parece bien difundiré la lección en Twitter.

**Comment by vgayolrs** [comment]
Traducción publicada. Gracias a tod@s!
