### ISSUE TITLE
Ticket de revisión de traducción: Uso de SPARQL para acceder a datos abiertos y enlazados

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#67]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Uso de SPARQL para acceder a datos abiertos y enlazados* de la lección [Using SPARQL to access Linked Open Data](http://programminghistorian.org/lessons/graph-databases-and-SPARQL) por parte de Nuria Rodríguez Ortega (@airun72). Esta traducción se encuentra en estos momentos en fase de revisión por parte de Juan Antonio Pastor Sánchez (@j-pastor) y puede leerse en:

### Texto
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/sparql-datos-abiertos-enlazados.md

### Imágenes 
https://github.com/PH-espagnol/jekyll/tree/gh-pages/images/graph-databases-and-SPARQL

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Muchas gracias @airun72 por la excelente traducción. Aquí van algunas observaciones mías:

- 58: --> interregar --> interrogar
- 58: consula --> consulta
- 62: objeto; ej.: --> objeto. Por ejemplo:
- en general: .) --> ). (punto detrás de paréntesis de cierre)
- 135: )en rojo --> ) en rojo (hay que separar)
- 145: Advierte --> Ten en cuenta (sugerencia?)
- 169: el modo como --> el modo en que (sugerencia: hay muchos "comos" en ese párrafo)
- 169: trabejemos --> trabajemos
- 173:  `PREFIX rkm:, que representa la cadena completa <http//data.rijksmuseum.nl>` -->  `PREFIX rkm:`, que representa la cadena completa `<http//data.rijksmuseum.nl>`, (sugerencia)
- 175: quereamos --> queramos
- 175: `dct vs`. --> `dct` vs.
- 209: complejas consultas --> consultas complejas (invertir orden)
- 223: 'objetos artísticos' --> "objetos artísticos" (sugerencia)
- 251: En las consultas anteriores, --> En los ejemplos anteriores o En los casos anteriores (sugerencia, para no repetir consultas en la misma frase)
- 331: ,y los --> , y los (introducir espacio antes de y)
- 331: DBPedia --> DBpedia (dos veces en este párrafo)
- 370: ULAN (Union List of Artist Names) del GRI --> puedes desarrollaro GRI (?) y dar algún enlace (?)
- 378: contiene --> contienen (?)
- 380: u Open Refine.  --> u Open Refine). (es decir, falta paréntesis de cierre)
- 380: (Para un tutorial sobre cómo utilizar programas de línea de comando, véase "Introduction to the Bash Command Line" --> (Para un tutorial sobre cómo utilizar programas de línea de comando, véase "Introduction to the Bash Command Line") (es decir, falta el paréntesis de cierre).
- 394: cambiar enlace a la traducción española sobre redes (http://programminghistorian.org/es/lecciones/creando-diagramas-de-redes-desde-fuentes-historicas)    
- 399: deceneas --> decenas (?)
- 405: detalladao --> detallado

Por favor, no introduzcas los cambios hasta que el segundo revisor publique su intervención.

**Comment by arojascastro** [comment]
Copio aquí los cambios realizados por @j-pastor en su *pull request* https://github.com/programminghistorian/ph-submissions/pull/74 : 

-  Bloque YAML: Uso de SPARQL para acceder a Datos abiertos y enlazados --> Uso de SPARQL para acceder a datos abiertos enlazados
- 23: datos abiertos y enlazados --> datos abiertos enlazados
- 32: RDF y Datos abiertos y enlazados -->  RDF y datos abiertos enlazados 
- 51: Bases de datos orientadas a grafo, RDF y Datos abiertos y enlazados --> Bases de datos orientadas a grafos, RDF y datos abiertos enlazados
- 182: Datos abiertos y enlazados --> datos abiertos enlazados

Por favor, @j-pastor si quieres añadir más sugerencias de cambio hazlo en este *issue*; a continuación, cerraré tu *pull request* porque es @airun72 quien debe modificar el archivo. Gracias.

**Comment by arojascastro** [comment]
Querida @airun72, ya puedes realizar las modificaciones. 

Por favor, corrige las erratas señaladas. 

En cuanto a los cambios estilísticos, me parece que en general son razonables y respetuosos. Pero si tienes buenas razones para no introducir algún cambio, publica un mensaje breve aquí para que quede constancia.

Cuando termines con los cambios, por favor, háznoslo saber y procederemos a publicar la lección en la web.

Gracias a @j-pastor por revisar la lección.

**Comment by airun72** [comment]
Ya he incorporado todos los cambios indicados.

**Comment by arojascastro** [comment]
@airun72 no veo los cambios, el archivo no se ha modificado desde el 8 de marzo, ¿seguro que los has hecho aquí? https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/sparql-datos-abiertos-y-enlazados.md

Si tienes el archivo nuevo en local, puedes enviármelo por email y ya me encargo yo de subirlo donde corresponde.

**Comment by airun72** [comment]
Sí, aquí 
https://github.com/programminghistorian/ph-submissions/edit/gh-pages/es/traducciones/sparql-datos-abiertos-y-enlazados.md

¿Debo clicar el botón "propose file change" que aparece en la parte 
inferior?

---
Nuria Rodríguez Ortega
Directora Dpto. Historia del Arte
Universidad de Málaga
Facultad de Filosofía y Letras
Campus de Teatinos, s/n
Málaga, 29071
Telf.: 952 132223 / 952131690
Fax: 952 133441

---------------

Professor and Chair of the Art History Department
University of Málaga (Spain)
Facultad de Filosofía y Letras
Campus de Teatinos, s/n
Málaga, 29071 (Spain)
Phone: 00 34 952132223 / 952131690
Fax: 00 34 952133441

**Comment by arojascastro** [comment]
@airun72 No acabo de entender qué es lo que ocurre; tienes que hacer un *commit* para que los cambios se guarden y todos tengamos el archivo actualizado.

**Comment by airun72** [comment]
No, no lo tengo en local, he introducido directamente los cambios en GitHub. ¿Cómo hago el _commit_?

**Comment by airun72** [comment]
Me he dado cuenta de que en la parte superior de la pantalla me aparece este mensaje: 

You’re editing a file in a project you don’t have write access to. We’ve created a fork of this project for you to commit your proposed changes to. Submitting a change to this file will write it to a new branch in your fork, so you can send a pull request.

**Comment by arojascastro** [comment]
Ok, perdona. Te he dado permiso para escribir @airun72. Tienes que aceptar mi invitación. Si no puedes, envía el cambio (submit) y entonces pídenos un pull request para que yo lo apruebe. Lamento las molestias.

**Comment by airun72** [comment]
Ok, ya estoy. Entonces, introduzco otra vez los cambios y clico en commit changes, ¿no?

**Comment by arojascastro** [comment]
Ostras, ¿los has perdido? Lo lamento mucho. ¿Sigue saliendo la opción "pull request"?

**Comment by airun72** [comment]
Acabo de crear un pull request, por si es más rápido. 

No, no los había perdido, afortunadamente.

**Comment by arojascastro** [comment]
Ok, perdona, y lo tenemos actualizado. Solo una pequeña pregunta @airun72 : ¿quieres que cambiemos el nombre de archivo *datos abiertos y enlazados* y pase a llamarse *datos abiertos enlazados*? Lo mismo ocurre en el índice y en encabezado de una sección. A mí me parece bien no quitar la *y* pero por unificar...

**Comment by airun72** [comment]
Sí, de acuerdo con el argumento de Juan Antonio Pastor, procede 
cambiarlo porque parece que la denominación aceptada es "datos abiertos 
enlazados", aunque genera una rara construcción en español.

De todos modos, acabo de enviar una consulta a la Fundéu, a ver qué 
dicen.

N

---
Nuria Rodríguez Ortega
Directora Dpto. Historia del Arte
Universidad de Málaga
Facultad de Filosofía y Letras
Campus de Teatinos, s/n
Málaga, 29071
Telf.: 952 132223 / 952131690
Fax: 952 133441

---------------

Professor and Chair of the Art History Department
University of Málaga (Spain)
Facultad de Filosofía y Letras
Campus de Teatinos, s/n
Málaga, 29071 (Spain)
Phone: 00 34 952132223 / 952131690
Fax: 00 34 952133441

**Comment by arojascastro** [comment]
Ok, pues entonces esperamos @airun72. Aunque si no te parece bien, no hace falta cambiarlo, a mí no me molesta. Escríbime cuando creas que la lección está lista y la publicamos en la web.

**Comment by airun72** [comment]
Ok, a la espera de confirmar este dato, estaría ya lista. Te aviso.

N

---
Nuria Rodríguez Ortega
Directora Dpto. Historia del Arte
Universidad de Málaga
Facultad de Filosofía y Letras
Campus de Teatinos, s/n
Málaga, 29071
Telf.: 952 132223 / 952131690
Fax: 952 133441

---------------

Professor and Chair of the Art History Department
University of Málaga (Spain)
Facultad de Filosofía y Letras
Campus de Teatinos, s/n
Málaga, 29071 (Spain)
Phone: 00 34 952132223 / 952131690
Fax: 00 34 952133441

**Comment by airun72** [comment]
En relación con la consulta que teníamos pendiente, Fundéu me remite a http://www.wikilengua.org/index.php/Uni%C3%B3n_de_adjetivos De acuerdo con Wikilengua, lo correcto en español sería "datos abiertos y enlazados", con la conjunción. Pero, efectivamente, la práctica en español es la que indica Juan Antonio Pastor, "datos abiertos enlazados", aparece así en todos los artículos, proyectos, webs, etc., por lo que creo que deberíamos utilizar esta.  

Por tanto, quedaría únicamente cambiar el nombre del archivo para ser consistente con el uso que se ha hecho de esta expresión en el texto. 

Cambiado esto, por mí está ok para publicar.

**Comment by arojascastro** [comment]
Acabo de publicar la lección aquí: http://programminghistorian.org/es/lecciones/sparql-datos-abiertos-enlazados

¡Gracias @airun72 y @j-pastor! Cierro este *issue* pero si hay algún problema se puede abrir. 

Le daremos difusión a la lección cuando termine el fin de semana.

**Comment by airun72** [comment]
Estupendo. Voy a buscar otra que pueda ser de interés para mis estudiantes. Me ha gustado mucho la experiencia.

**Comment by arojascastro** [comment]
¡Genial! Acaban de publicar otra lección sobre LOD: http://programminghistorian.org/lessons/intro-to-linked-data

No hemos actualizado aún la lista de traducciones, así que mejor consulta la web inglesa.

**Comment by airun72** [comment]
Ok!
