### ISSUE TITLE
Proposed Lesson: Exploring and Analyzing Network Data with Python

### ISSUE THREAD

**Issue by walshbr** [programminghistorian/ph-submissions#70]
The Programming Historian has received the following proposal for a lesson on 'Exploring and Analyzing Network Data with Python' by @jrladd @jmotis and @scottbot. The proposed learning outcomes of the lesson are:

- introduce the NetworkX package for working with network data in Python
- analyze humanities network data to find:
    - network structure and path lengths
    - important or central nodes
    - communities and subgroups

The authors have requested an initial round of editorial feedback from me by email before moving to GitHub. In order to promote speedy publication of this important topic, we have agreed to a submission date of no later than May 17, 2017. The author agrees to contact the editor in advance if they need to revise the deadline.

If the lesson is not submitted by May 17, the editor will attempt to contact the authors. If they do not receive an update, this ticket will be closed. The ticket can be reopened at a future date at the request of the author.

The main editorial contact for this lessons is @walshbr. If there are any concerns from the authors they can contact the Ombudsperson @ianmilligan1 or @amandavisconti

**Comment by walshbr** [comment]
Just an update, since it's May 17th - @jrladd and I have been in contact. They've got a draft ready to give to me in the next couple days, and I'll review it and give an initial round of feedback off-GitHub as requested by the authors. Will transfer to a submission ticket when ready.

**Comment by acrymble** [comment]
We've just had a new lesson proposal (#91) that also proposes to use NetworkX. Are you at a stage where you can share the draft text so that we can formulate that lesson to be complementary?

**Comment by walshbr** [comment]
Thanks @acrymble - just pinged @jrladd by email as well.

**Comment by jrladd** [comment]
@acrymble Thanks for the heads up. I just sent @walshbr a message that I hope will help with this. Let us know if there's more we can do!

**Comment by jrladd** [comment]
Here's a list of what we're covering in Python, @acrymble :

- processing network data from CSVs
- creating a NetworkX Graph object and adding data
- adding node and edge attributes
- calculating density, shortest paths, largest components, and diameter
- three types of centrality: degree, betweennness, eigenvector
- modularity with the python-louvain Python package
- exporting data and writing it to file

**Comment by walshbr** [comment]
Thanks @jrladd - when you get the draft to me I'll aim for a quick turnaround to you so that we can get up on GitHub as soon as possible.

**Comment by walshbr** [comment]
@acrymble - the draft is posted now [here](http://programminghistorian.github.io/ph-submissions/lessons/exploring-and-analyzing-network-data-with-python) - moving conversation to the review ticket #92
