### ISSUE TITLE
Ticket de revisión de traducción: Limpieza de datos con OpenRefine

### ISSUE THREAD

**Issue by arojascastro** [programminghistorian/ph-submissions#73]
*The Programming Historian en español* ha recibido la siguiente propuesta de traducción *Limpieza de datos con OpenRefine* de la lección [Cleaning Data with OpenRefine](http://programminghistorian.org/lessons/cleaning-data-with-openrefine) por parte de @mjcolmenero. Esta traducción se encuentra en estos momentos en fase de revisión por parte de @LuisinaSilva y puede leerse en:

### Texto
https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/limpieza-de-datos-con-OpenRefine.md

### Imágenes
https://github.com/programminghistorian/jekyll/tree/gh-pages/images/cleaning-data-with-openrefine

Por favor, estás en libertad de utilizar los números de línea proporcionados en la vista previa, si eso ayuda a señalar mejor tus comentarios. Pero puedes estructurar tu revisión como mejor te parezca.

En adelante, intervendré como editor durante el proceso de revisión. Tras haber leído la lección y haber enviado mis comentarios al traductor, mi rol consistirá en solicitar otra revisión por parte de uno de los miembros de nuestro comité editorial y gestionar las conversaciones que se produzcan en este foro. 

Otros miembros de nuestra comunidad también están invitados a ofrecer sus comentarios de una manera constructiva; los comentarios deberán publicarse en este hilo de conversación, por lo que se recomienda haber leído nuestra guía para revisores (http://programminghistorian.org/es/guia-para-revisores) y tener en cuenta nuestra política contra el acoso (ver más abajo). No se aceptarán más comentarios por parte de la comunidad tras la publicación de la segunda revisión formal a fin de que el traductor pueda empezar a trabajar en los cambios solicitados. Cuando esto ocurra, publicaré un anuncio aquí.

Asimismo, me comprometo a mantener la conversación abierta a todo el mundo en GitHub. Pero si alguno de los participantes quiere ponerse en contacto en privado conmigo, puede escribirme un correo electrónico. También es posible contactar con nuestros 'ombudpersons'.

## Política contra el acoso

Esta es una declaración de los principios de *Programming Historian en español* y establece las expectativas para el tono y el estilo de toda la correspondencia entre los revisores, autores, editores y colaboradores de nuestros foros públicos.

> El objetivo de *The Programming Historian en español* es ofrecer un entorno abierto en el que la comunidad de participantes sean libres para analizar ideas, realizar preguntas, sugerir cambios, y pedir aclaraciones; también queremos que sea un espacio libre de acoso y hostigamento para todo el mundo con independencia de su género, identidad, orientación sexual, minusvalía, apariencia física, tamaño corporal, raza, edad, religión o conocimientos informáticos. No se tolerará ningún tipo de acoso o ataque *ad hominem*. Los participantes que violen esta regla podrán ser expulsados del proceso editorial a discreción del equipo editorial. Si presencias o sientes que has sido víctima de algún tipo de acoso, por favor, contacta con nuestros 'ombudspersons' (María José Afanador-Llach o Víctor Gayol - http://programminghistorian.org/es/equipo-de-proyecto).

**Comment by arojascastro** [comment]
Gracias @mjcolmenero por tu excelente traducción. Hay muy pocos errores, lo único que he encontrado es lo siguiente:

- En general, en *The Programming Historian en español* hemos utilizado hasta el momento la segunda persona del singular, es decir, tú en lugar de usted. Habría, por tanto, que cambiar las formas verbales y los pronombres, pero no sé qué opinan los otros editores: ¿qué os parece @vgayolrs @mariajoafana? 
- 31: semi-) automatizados --> semiautomatizados (?)
- 35 --> celdas (?)
- 39: Interactive Data Transformation --> *Interactive Data Transformation* (añadir cursiva)
- 51: Lección --> lección (?)
- 53: mejores s  --> mejores (sobra una s)
- 93: dress'(7.279). --> dress' (7.279). (separar)
- 99:  los grupos . -->  los grupos. (quitar espacio)
- 103: separaramos --> separáramos (?)
- 107: ¿cómo corregimos estos valores?. --> ¿cómo corregimos estos valores? (Quitar punto)
- 128: software --> *software* (añadir cursiva)
- 142:  'Editar celdas' > 'Transformaciones comunes' > 'a número' -->  'Editar celdas' > 'Transformaciones comunes' > 'a número'. (añadir punto final)

@acrymble the translator asks if we should host the file provided by the museum. So my question is why is not hosted in /assets in the original lesson?

**Comment by arojascastro** [comment]
Añado a @LuisinaSilva como revisora externa. Por favor, introduce aquí tus propuestas de cambio en las próximas dos semanas.

**Comment by mjcolmenero** [comment]
Muchas gracias por tu revisión @arojascastro 👍. Corrijo todo lo que indicas para que el segundo revisor ya no lo encuentre.
Sólo una cosa: no planteaba traducir los metadatos sino alojar el archivo por si el museo lo retira en algún momento. La lección no funcionaría sin el.

**Comment by mjcolmenero** [comment]
Tras revisar el texto para corregir lo indicado he encontrado lo siguiente:
31: (semi-)automated  en el original. He eliminado el espacio en la traducción.
51: with the Lesson en el original. Lo dejo en mayúscula salvo que me indiquéis lo contrario
128: software --> software (añadir cursiva).  Lo he sustituido por programa. 
Reviso el tratamiento de la segunda persona cuando me lo indiquéis.
Saludos,

**Comment by arojascastro** [comment]
¡Gracias a ti! Y gracias también por la aclaración - ahora lo modifico. 

Pregunta: @mjcolmenero  ¿dónde has hecho las modificaciones? Si las haces aquí (https://github.com/programminghistorian/ph-submissions/blob/gh-pages/es/traducciones/limpieza-de-datos-con-OpenRefine.md) las tendremos todos.

**Comment by mjcolmenero** [comment]
Respuesta: @arojascastro las he hecho ahí mismo. Pero grabé as tarde, quizás por eso no las viste.

**Comment by vgayolrs** [comment]
De acuerdo con tu primera observación @arojascastro .

**Comment by LuisinaSilva** [comment]
Hola a todos!

Muy buena traducción! Acá van algunas sugerencias. 

24) en lugar de la palabra "actuar" tal vez poner proceder. 
35) sacar "con los que tratar y"
35) en lugar de "contenidos" poner "incluido"
35) cambiar "que dar respuesta" por "responder"
39) cambiar "Tiempo atrás" por "En el pasado" 
39) doble espacio entre  DE y PROGRAMAS "el uso de  programas"
39) doble espacio entre DATOS y el paréntesis. "interactiva de datos  (*Interactive"
41) sacar palabra "comunes" al final de la oración. 
43) doble espacio "nos  centraremos"
51) al final de la última oración "capaz de continuar esta Lección." En lugar de continuar se puede poner "entender" o "seguir" esta lección. 
53) En "encontrarás las mejores" cambiar por "encontrarás mayormente" o "principalmente"
53) Si se modifica la frase como propuse hay que sacar el "y" que está antes de "en comparación" 
61) Agregar la palabra(s)  "presione" o "haga clic" antes de "Acepte y la ..."
61) Poner "aparecerán" en lugar de  "aparecerá" (plural- página y programa)
63) Extra espacio antes del punto. "*OpenRefine* ." 
65) En lugar de "persistente" poner tal vez "permanente"
65) Al final de la oración donde está nuevamente la palabra "persistente" cambiarla por "correspondiente" 
71) Doble espacio entre la coma y categorías  "(por ejemplo,  Categorías)"
71) Poner la palabra "enlentecer" en lugar de "ralentizar".
71) Doble espacio "exploraremos  más"
81) Doble espacio "ha  afectado"
83) Agregar "antes" después de la palabra "paso". "En el paso mencionado"
83) Doble espacio "representa  o"
87) En vez de poner " De media," escribir "En promedio" 
89) Doble espacio "están  justo"
89) Doble espacio "notó  que"
89) Doble espacio "hay  9"
93) Falta una coma entre estas palabras? "general rápida" 
103) Creo que que se entiende mejor si ponemos "proceso de separación" en lugar de "proceso de desagregación"

Saludos-

**Comment by arojascastro** [comment]
¡Gracias @LuisinaSilva! 

Por favor, @mjcolmenero modifica el texto para acomodarlo a la segunda persona del singular en lugar del *usted*. 

También corrige las erratas que hemos encontrado y ten en cuenta nuestras sugerencias de cambio que atañen al estilo. Si crees que alguna de nuestras sugerencias no es necesaria, eres libre de mantener el texto, pero, en general, creo que no son muy invasivas y que mejorarán tu traducción. 

Si tienes alguna duda, escríbenos aquí y te contestaremos. Cuando termines con los cambies, por favor, publica un mensaje en este *issue* para que yo pueda actualizar los metadatos y publicar la lección en la web. 

Muchas gracias a todos.

**Comment by mjcolmenero** [comment]
Estimada @LuisinaSilva:

Muchísimas gracias por la concienzuda revisión que siempre beneficia al texto final.

En primer lugar he eliminado todos los dobles espacios (y alguno más que encontré).

Tu numeración no coincidía con las líneas (correlativa comenzando en 24) pero he ido encontrando todos los detalles.

En "con los que tratar y" pensé en traducir como lidiar pero al final me decanté por tratar (para no ponerme taurina ni localista). Los autores quieren resaltar que son fenómenos usuales para los que hay que estar preparados. No parece importar eliminar ese trozo.

He aceptado algunas cosas pero otras me cuesta un poco más. Lo justifico a continuación. Si a pesar de ello os parece mejor la otra opción lo modificaré:

- en cuanto a "incluidos" por "contenidos" la verdad es que lo que creo que quedaría mejor es "los datos **de** una hoja de cálculo o **en** una base de datos". Dudé ya en una primera ocasión y ahora es así como lo he dejado.

- cambiar "Tiempo atrás" por "En el pasado" ---- para un historiador el pasado puede ser muuuuy lejos y en el contexto de esta frase el tiempo transcurrido es muy pequeño. Por eso deseché traducirlo como "en el pasado". Quizás "Un tiempo atrás" sea más correcto...

- En "encontrarás las mejores" cambiar por "encontrarás mayormente" o "principalmente"  ----- el problema es que no se está indicando cantidad (más nombres de esto que de aquello) sino calidad: una muy buena elección de términos que representan dos dominios (historia social y artes decorativas). 

- En lugar de "persistente" poner tal vez "permanente": se usan indistintamente en la literatura. Y creo que debe estar repetida para que el lector sepa que nos estamos refiriendo a ese concepto (se repite también en el original por este motivo).

- Falta una coma entre estas palabras? "general rápida". No, no falta

- Creo que que se entiende mejor si ponemos "proceso de separación" en lugar de "proceso de desagregación". He cambiado también el encabezado Desagregar por Separar para adaptarlo a esta sugerencia de cambio.

@arojascastro Ya he puesto en segunda persona del singular todo el texto (salvo error inadvertido).

Muchísimas gracias a los dos por todo el trabajo realizado.
Un cordial saludo,

**Comment by arojascastro** [comment]
Gracias @mjcolmenero y @LuisinaSilva. 

Acabo de hacer una lectura y me parece que está muy bien. He modificado algunas cosillas que he visto referente al usted, pero por lo demás creo que está lista para publicarse. 

¿Os parece bien? @LuisinaSilva @mjcolmenero

**Comment by mjcolmenero** [comment]
Por mí bien. La última palabra para  @LuisinaSilva.
Saludos y gracias

**Comment by LuisinaSilva** [comment]
Hola @arojascastro y @mjcolmenero!

Recién la vi y creo que quedó muy bien- 

Saludos y estamos en contacto

**Comment by arojascastro** [comment]
Hola @mjcolmenero y @LuisinaSilva, he publicado la lección aquí: http://programminghistorian.org/es/lecciones/limpieza-de-datos-con-OpenRefine

Hay un problema con el markdown: el \> no está bloqueando la etiqueta y genera un bloque de texto. Hasta que no lo resuelva, no difundamos la lección, por favor. 

@acrymble @wcaleb any idea why \> is not scaping the tag > in this lesson? http://programminghistorian.org/es/lecciones/limpieza-de-datos-con-OpenRefine

**Comment by arojascastro** [comment]
Ok, solucionado! Gracias @mjcolmenero @LuisinaSilva. Ayudadnos a difundir, por favor.
