### ISSUE TITLE
Proposed Lesson: Creating a Scalar project

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/ph-submissions#90]
The Programming Historian has received a proposal for a lesson on creating a Scalar project / sharing research findings via Scalar.

## Anti-Harassment Policy

This is a statement of the Programming Historian's principles and sets expectations for the tone and style of all correspondence between reviewers, authors, editors, and contributors to our public forums.

> The Programming Historian is dedicated to providing an open scholarly environment that offers community participants the freedom to thoroughly scrutinize ideas, to ask questions, make suggestions, or to requests for clarification, but also provides a harassment-free space for all contributors to the project, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion, or technical experience. We do not tolerate harassment or ad hominem attacks of community participants in any form. Participants violating these rules may be expelled from the community at the discretion of the editorial board. If anyone witnesses or feels they have been the victim of the above described activity, please contact our ombudspeople (Ian Milligan and Amanda Visconti - <http://programminghistorian.org/project-team>). Thank you for helping us to create a safe space.

**Comment by jerielizabeth** [comment]
I received a draft of this lesson on August 30 and have provided initial feedback.

**Comment by acrymble** [comment]
Is this still going ahead @jerielizabeth ?

**Comment by jerielizabeth** [comment]
I followed up with the authors a second time on January 8, 2018 and have received no response. I am closing the issue, and will reopen if there is further correspondence in the future.
