### ISSUE TITLE
Proposed Lesson: Named Entity Extraction from Data Collections

### ISSUE THREAD

**Issue by jerielizabeth** [programminghistorian/ph-submissions#93]
The Programming Historian has received a proposal for a lesson on Named Entity Extraction from data collections.

**Comment by acrymble** [comment]
Any update on this? There is no date associated with this @jerielizabeth

**Comment by jerielizabeth** [comment]
I followed up with the author on January 8, 2018 and have not heard back. 

I am closing the issue, but will reopen should there be any updates in the future.
