### ISSUE TITLE
Update figure.html includes

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/ph-submissions#97]
The redesign meant some thorough updates to the way that figure.html includes worked, and right now someone trying to write a lesson following our author guidelines will see only broken image links in the lesson previews on ph-submissions. I'll work some more on this.

**Comment by wcaleb** [comment]
Are you sure it's not just the avatar at the top that breaks? The previews for current submissions appear to work unless I'm missing something.

**Comment by mdlincoln** [comment]
The previews work ok if someone is using the `![]()` syntax. However, if they actually follow the author guidelines and use `{% include figure.hml ... %}` then things break down a bit. I noticed the problem when I tried to add the changes to the correspondence analysis lesson I'm editing.

**Comment by mdlincoln** [comment]
Closed with d783b0d335c8aa628ad6dce5bffd16a64b5254f3
