### ISSUE TITLE
Restore line numbers to lesson previews

### ISSUE THREAD

**Issue by mdlincoln** [programminghistorian/ph-submissions#98]

**Comment by wcaleb** [comment]
I'm almost done with this.

**Comment by mdlincoln** [comment]
Great! No pressure - I was just marking it here since I knew you were working on it.

**Comment by wcaleb** [comment]
The new containers made it difficult to float the line numbers to the left as before, so I've put them at the end of the paragraph to the right. If this looks too confusing, then I can get back into it and see how better to anchor them to the left.
